; Problem taken from https://github.com/AI-Planning/classical-domains

(define (problem roverprob2413) (:domain Rover)
(:objects
	general - Lander
	colour high_res low_res - Mode
	rover0 rover1 rover2 rover3 rover4 rover5 - Rover
	rover0store rover1store rover2store rover3store rover4store rover5store - Store
	waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 waypoint11 waypoint12 waypoint13 waypoint14 waypoint15 waypoint16 waypoint17 waypoint18 waypoint19 waypoint20 waypoint21 waypoint22 waypoint23 waypoint24 waypoint25 waypoint26 waypoint27 waypoint28 waypoint29 waypoint30 waypoint31 waypoint32 waypoint33 waypoint34 waypoint35 waypoint36 waypoint37 waypoint38 waypoint39 - Waypoint
	camera0 camera1 camera2 camera3 camera4 camera5 camera6 camera7 - Camera
	objective0 objective1 objective2 objective3 objective4 objective5 objective6 objective7 objective8 objective9 - Objective
	)
(:init
	(at_soil_sample waypoint0)
	(at_soil_sample waypoint1)
	(at_soil_sample waypoint2)
	(at_rock_sample waypoint2)
	(at_soil_sample waypoint3)
	(at_soil_sample waypoint4)
	(at_rock_sample waypoint4)
	(at_rock_sample waypoint5)
	(at_rock_sample waypoint7)
	(at_soil_sample waypoint9)
	(at_rock_sample waypoint11)
	(at_soil_sample waypoint12)
	(at_soil_sample waypoint14)
	(at_rock_sample waypoint14)
	(at_rock_sample waypoint16)
	(at_soil_sample waypoint17)
	(at_soil_sample waypoint18)
	(at_soil_sample waypoint21)
	(at_rock_sample waypoint21)
	(at_rock_sample waypoint23)
	(at_soil_sample waypoint24)
	(at_rock_sample waypoint24)
	(at_rock_sample waypoint25)
	(at_soil_sample waypoint26)
	(at_soil_sample waypoint27)
	(at_rock_sample waypoint27)
	(at_rock_sample waypoint28)
	(at_soil_sample waypoint31)
	(at_rock_sample waypoint31)
	(at_soil_sample waypoint32)
	(at_soil_sample waypoint37)
	(at_soil_sample waypoint38)
	(at_rock_sample waypoint38)
	(at_lander general waypoint2)
	(channel_free general)
	(at rover0 waypoint4)
	(store_of rover0store rover0)
	(empty rover0store)
	(equipped_for_soil_analysis rover0)
	(equipped_for_rock_analysis rover0)
	(equipped_for_imaging rover0)
	(at rover1 waypoint16)
	(store_of rover1store rover1)
	(empty rover1store)
	(equipped_for_soil_analysis rover1)
	(equipped_for_rock_analysis rover1)
	(equipped_for_imaging rover1)
	(at rover2 waypoint3)
	(store_of rover2store rover2)
	(empty rover2store)
	(equipped_for_rock_analysis rover2)
	(equipped_for_imaging rover2)
	(at rover3 waypoint4)
	(store_of rover3store rover3)
	(empty rover3store)
	(equipped_for_soil_analysis rover3)
	(equipped_for_imaging rover3)
	(at rover4 waypoint0)
	(store_of rover4store rover4)
	(empty rover4store)
	(equipped_for_soil_analysis rover4)
	(equipped_for_rock_analysis rover4)
	(equipped_for_imaging rover4)
	(at rover5 waypoint10)
	(store_of rover5store rover5)
	(empty rover5store)
	(equipped_for_rock_analysis rover5)
	(equipped_for_imaging rover5)
	(on_board camera0 rover3)
	(calibration_target camera0 objective9)
	(supports camera0 colour)
	(on_board camera1 rover3)
	(calibration_target camera1 objective2)
	(supports camera1 colour)
	(supports camera1 low_res)
	(on_board camera2 rover4)
	(calibration_target camera2 objective3)
	(supports camera2 colour)
	(supports camera2 high_res)
	(supports camera2 low_res)
	(on_board camera3 rover1)
	(calibration_target camera3 objective8)
	(supports camera3 colour)
	(supports camera3 high_res)
	(supports camera3 low_res)
	(on_board camera4 rover5)
	(calibration_target camera4 objective1)
	(supports camera4 colour)
	(supports camera4 high_res)
	(on_board camera5 rover0)
	(calibration_target camera5 objective6)
	(supports camera5 low_res)
	(on_board camera6 rover2)
	(calibration_target camera6 objective5)
	(supports camera6 colour)
	(supports camera6 low_res)
	(on_board camera7 rover2)
	(calibration_target camera7 objective9)
	(supports camera7 high_res)
)

(:goal (and
(communicated_soil_data waypoint17)
(communicated_soil_data waypoint3)
(communicated_soil_data waypoint18)
(communicated_soil_data waypoint1)
(communicated_soil_data waypoint38)
(communicated_rock_data waypoint14)
(communicated_rock_data waypoint21)
(communicated_rock_data waypoint24)
(communicated_rock_data waypoint7)
(communicated_rock_data waypoint31)
(communicated_rock_data waypoint25)
(communicated_image_data objective6 low_res)
(communicated_image_data objective9 high_res)
(communicated_image_data objective8 high_res)
(communicated_image_data objective3 high_res)
(communicated_image_data objective1 low_res)
	)
)
)
