; Problem taken from https://github.com/AI-Planning/classical-domains

(define (problem roverprob2006) (:domain Rover)
(:objects
	general - Lander
	colour high_res low_res - Mode
	rover0 rover1 rover2 rover3 rover4 rover5 rover6 rover7 rover8 rover9 rover10 rover11 rover12 rover13 - Rover
	rover0store rover1store rover2store rover3store rover4store rover5store rover6store rover7store rover8store rover9store rover10store rover11store rover12store rover13store - Store
	waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 waypoint11 waypoint12 waypoint13 waypoint14 waypoint15 waypoint16 waypoint17 waypoint18 waypoint19 waypoint20 waypoint21 waypoint22 waypoint23 waypoint24 waypoint25 waypoint26 waypoint27 waypoint28 waypoint29 waypoint30 waypoint31 waypoint32 waypoint33 waypoint34 waypoint35 waypoint36 waypoint37 waypoint38 waypoint39 waypoint40 waypoint41 waypoint42 waypoint43 waypoint44 waypoint45 waypoint46 waypoint47 waypoint48 waypoint49 waypoint50 waypoint51 waypoint52 waypoint53 waypoint54 waypoint55 waypoint56 waypoint57 waypoint58 waypoint59 waypoint60 waypoint61 waypoint62 waypoint63 waypoint64 waypoint65 waypoint66 waypoint67 waypoint68 waypoint69 waypoint70 waypoint71 waypoint72 waypoint73 waypoint74 waypoint75 waypoint76 waypoint77 waypoint78 waypoint79 waypoint80 waypoint81 waypoint82 waypoint83 waypoint84 waypoint85 waypoint86 waypoint87 waypoint88 waypoint89 waypoint90 waypoint91 waypoint92 waypoint93 waypoint94 - Waypoint
	camera0 camera1 camera2 camera3 camera4 camera5 camera6 camera7 camera8 camera9 camera10 camera11 camera12 camera13 camera14 camera15 - Camera
	objective0 objective1 objective2 objective3 objective4 objective5 objective6 objective7 objective8 objective9 objective10 objective11 objective12 objective13 - Objective
	)
(:init
	(at_soil_sample waypoint1)
	(at_rock_sample waypoint1)
	(at_soil_sample waypoint2)
	(at_soil_sample waypoint3)
	(at_rock_sample waypoint3)
	(at_soil_sample waypoint5)
	(at_soil_sample waypoint6)
	(at_soil_sample waypoint7)
	(at_soil_sample waypoint8)
	(at_rock_sample waypoint8)
	(at_rock_sample waypoint9)
	(at_rock_sample waypoint10)
	(at_rock_sample waypoint11)
	(at_rock_sample waypoint12)
	(at_soil_sample waypoint13)
	(at_rock_sample waypoint13)
	(at_soil_sample waypoint14)
	(at_rock_sample waypoint14)
	(at_rock_sample waypoint15)
	(at_rock_sample waypoint16)
	(at_rock_sample waypoint17)
	(at_soil_sample waypoint19)
	(at_soil_sample waypoint20)
	(at_soil_sample waypoint21)
	(at_rock_sample waypoint21)
	(at_rock_sample waypoint22)
	(at_soil_sample waypoint23)
	(at_rock_sample waypoint23)
	(at_rock_sample waypoint24)
	(at_rock_sample waypoint25)
	(at_rock_sample waypoint30)
	(at_soil_sample waypoint31)
	(at_rock_sample waypoint32)
	(at_rock_sample waypoint33)
	(at_soil_sample waypoint34)
	(at_rock_sample waypoint34)
	(at_rock_sample waypoint35)
	(at_rock_sample waypoint36)
	(at_rock_sample waypoint37)
	(at_rock_sample waypoint40)
	(at_rock_sample waypoint41)
	(at_soil_sample waypoint42)
	(at_rock_sample waypoint42)
	(at_soil_sample waypoint43)
	(at_soil_sample waypoint45)
	(at_rock_sample waypoint45)
	(at_rock_sample waypoint47)
	(at_rock_sample waypoint49)
	(at_soil_sample waypoint50)
	(at_rock_sample waypoint52)
	(at_soil_sample waypoint53)
	(at_rock_sample waypoint54)
	(at_rock_sample waypoint55)
	(at_rock_sample waypoint56)
	(at_soil_sample waypoint57)
	(at_rock_sample waypoint57)
	(at_soil_sample waypoint58)
	(at_rock_sample waypoint58)
	(at_soil_sample waypoint60)
	(at_rock_sample waypoint61)
	(at_soil_sample waypoint62)
	(at_rock_sample waypoint62)
	(at_rock_sample waypoint63)
	(at_soil_sample waypoint65)
	(at_rock_sample waypoint66)
	(at_rock_sample waypoint67)
	(at_soil_sample waypoint69)
	(at_rock_sample waypoint70)
	(at_rock_sample waypoint72)
	(at_soil_sample waypoint74)
	(at_rock_sample waypoint74)
	(at_soil_sample waypoint76)
	(at_rock_sample waypoint76)
	(at_soil_sample waypoint77)
	(at_rock_sample waypoint77)
	(at_soil_sample waypoint78)
	(at_rock_sample waypoint78)
	(at_soil_sample waypoint80)
	(at_rock_sample waypoint80)
	(at_soil_sample waypoint82)
	(at_rock_sample waypoint83)
	(at_soil_sample waypoint85)
	(at_rock_sample waypoint85)
	(at_rock_sample waypoint88)
	(at_soil_sample waypoint89)
	(at_rock_sample waypoint89)
	(at_soil_sample waypoint90)
	(at_soil_sample waypoint91)
	(at_rock_sample waypoint91)
	(at_soil_sample waypoint92)
	(at_lander general waypoint84)
	(channel_free general)
	(at rover0 waypoint60)
	(store_of rover0store rover0)
	(empty rover0store)
	(equipped_for_soil_analysis rover0)
	(equipped_for_imaging rover0)
	(at rover1 waypoint25)
	(store_of rover1store rover1)
	(empty rover1store)
	(equipped_for_imaging rover1)
	(at rover2 waypoint47)
	(store_of rover2store rover2)
	(empty rover2store)
	(equipped_for_soil_analysis rover2)
	(equipped_for_imaging rover2)
	(at rover3 waypoint93)
	(store_of rover3store rover3)
	(empty rover3store)
	(equipped_for_soil_analysis rover3)
	(equipped_for_imaging rover3)
	(at rover4 waypoint32)
	(store_of rover4store rover4)
	(empty rover4store)
	(equipped_for_rock_analysis rover4)
	(at rover5 waypoint43)
	(store_of rover5store rover5)
	(empty rover5store)
	(equipped_for_rock_analysis rover5)
	(equipped_for_imaging rover5)
	(at rover6 waypoint16)
	(store_of rover6store rover6)
	(empty rover6store)
	(equipped_for_soil_analysis rover6)
	(equipped_for_imaging rover6)
	(at rover7 waypoint64)
	(store_of rover7store rover7)
	(empty rover7store)
	(equipped_for_imaging rover7)
	(at rover8 waypoint78)
	(store_of rover8store rover8)
	(empty rover8store)
	(equipped_for_soil_analysis rover8)
	(equipped_for_imaging rover8)
	(at rover9 waypoint63)
	(store_of rover9store rover9)
	(empty rover9store)
	(equipped_for_rock_analysis rover9)
	(equipped_for_imaging rover9)
	(at rover10 waypoint73)
	(store_of rover10store rover10)
	(empty rover10store)
	(equipped_for_soil_analysis rover10)
	(equipped_for_imaging rover10)
	(at rover11 waypoint0)
	(store_of rover11store rover11)
	(empty rover11store)
	(equipped_for_imaging rover11)
	(at rover12 waypoint4)
	(store_of rover12store rover12)
	(empty rover12store)
	(equipped_for_rock_analysis rover12)
	(equipped_for_imaging rover12)
	(at rover13 waypoint46)
	(store_of rover13store rover13)
	(empty rover13store)
	(equipped_for_rock_analysis rover13)
	(equipped_for_imaging rover13)
	(on_board camera0 rover10)
	(calibration_target camera0 objective8)
	(supports camera0 low_res)
	(on_board camera1 rover13)
	(calibration_target camera1 objective10)
	(supports camera1 high_res)
	(supports camera1 low_res)
	(on_board camera2 rover3)
	(calibration_target camera2 objective3)
	(supports camera2 colour)
	(on_board camera3 rover5)
	(calibration_target camera3 objective5)
	(supports camera3 high_res)
	(supports camera3 low_res)
	(on_board camera4 rover7)
	(calibration_target camera4 objective10)
	(supports camera4 high_res)
	(on_board camera5 rover9)
	(calibration_target camera5 objective2)
	(supports camera5 colour)
	(supports camera5 low_res)
	(on_board camera6 rover5)
	(calibration_target camera6 objective13)
	(supports camera6 colour)
	(supports camera6 low_res)
	(on_board camera7 rover5)
	(calibration_target camera7 objective6)
	(supports camera7 high_res)
	(supports camera7 low_res)
	(on_board camera8 rover13)
	(calibration_target camera8 objective4)
	(supports camera8 colour)
	(supports camera8 high_res)
	(supports camera8 low_res)
	(on_board camera9 rover8)
	(calibration_target camera9 objective9)
	(supports camera9 high_res)
	(on_board camera10 rover2)
	(calibration_target camera10 objective12)
	(supports camera10 low_res)
	(on_board camera11 rover12)
	(calibration_target camera11 objective6)
	(supports camera11 low_res)
	(on_board camera12 rover0)
	(calibration_target camera12 objective10)
	(supports camera12 colour)
	(supports camera12 high_res)
	(supports camera12 low_res)
	(on_board camera13 rover1)
	(calibration_target camera13 objective10)
	(supports camera13 high_res)
	(on_board camera14 rover6)
	(calibration_target camera14 objective7)
	(supports camera14 colour)
	(supports camera14 high_res)
	(supports camera14 low_res)
	(on_board camera15 rover11)
	(calibration_target camera15 objective13)
	(supports camera15 colour)
	(supports camera15 low_res)
)

(:goal (and
(communicated_soil_data waypoint21)
(communicated_soil_data waypoint62)
(communicated_soil_data waypoint89)
(communicated_soil_data waypoint80)
(communicated_soil_data waypoint58)
(communicated_soil_data waypoint77)
(communicated_soil_data waypoint1)
(communicated_soil_data waypoint3)
(communicated_soil_data waypoint19)
(communicated_soil_data waypoint5)
(communicated_soil_data waypoint60)
(communicated_soil_data waypoint42)
(communicated_soil_data waypoint7)
(communicated_soil_data waypoint14)
(communicated_soil_data waypoint57)
(communicated_soil_data waypoint31)
(communicated_soil_data waypoint65)
(communicated_soil_data waypoint50)
(communicated_soil_data waypoint90)
(communicated_soil_data waypoint85)
(communicated_soil_data waypoint45)
(communicated_soil_data waypoint78)
(communicated_soil_data waypoint20)
(communicated_soil_data waypoint6)
(communicated_soil_data waypoint43)
(communicated_soil_data waypoint74)
(communicated_soil_data waypoint13)
(communicated_soil_data waypoint2)
(communicated_soil_data waypoint69)
(communicated_soil_data waypoint23)
(communicated_soil_data waypoint76)
(communicated_soil_data waypoint34)
(communicated_soil_data waypoint92)
(communicated_soil_data waypoint8)
(communicated_soil_data waypoint91)
(communicated_soil_data waypoint82)
(communicated_rock_data waypoint8)
(communicated_rock_data waypoint3)
(communicated_rock_data waypoint78)
(communicated_rock_data waypoint67)
(communicated_rock_data waypoint55)
(communicated_rock_data waypoint45)
(communicated_rock_data waypoint61)
(communicated_rock_data waypoint23)
(communicated_rock_data waypoint15)
(communicated_rock_data waypoint37)
(communicated_rock_data waypoint17)
(communicated_rock_data waypoint11)
(communicated_rock_data waypoint91)
(communicated_rock_data waypoint77)
(communicated_rock_data waypoint56)
(communicated_rock_data waypoint74)
(communicated_image_data objective11 low_res)
(communicated_image_data objective10 low_res)
(communicated_image_data objective13 low_res)
(communicated_image_data objective2 low_res)
(communicated_image_data objective12 high_res)
(communicated_image_data objective4 colour)
(communicated_image_data objective6 high_res)
(communicated_image_data objective13 high_res)
(communicated_image_data objective3 colour)
(communicated_image_data objective1 high_res)
(communicated_image_data objective12 low_res)
	)
)
)
