; Problem taken from https://github.com/AI-Planning/classical-domains

(define (problem roverprob4621) (:domain Rover)
(:objects
	general - Lander
	colour high_res low_res - Mode
	rover0 rover1 rover2 rover3 rover4 rover5 - Rover
	rover0store rover1store rover2store rover3store rover4store rover5store - Store
	waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 waypoint11 waypoint12 waypoint13 waypoint14 waypoint15 waypoint16 waypoint17 waypoint18 waypoint19 - Waypoint
	camera0 camera1 camera2 camera3 camera4 camera5 camera6 - Camera
	objective0 objective1 objective2 objective3 objective4 objective5 objective6 - Objective
	)
(:init
	(at_soil_sample waypoint0)
	(at_rock_sample waypoint1)
	(at_rock_sample waypoint2)
	(at_soil_sample waypoint3)
	(at_rock_sample waypoint4)
	(at_rock_sample waypoint5)
	(at_rock_sample waypoint6)
	(at_rock_sample waypoint7)
	(at_soil_sample waypoint8)
	(at_soil_sample waypoint9)
	(at_rock_sample waypoint9)
	(at_soil_sample waypoint10)
	(at_soil_sample waypoint11)
	(at_soil_sample waypoint12)
	(at_rock_sample waypoint12)
	(at_soil_sample waypoint13)
	(at_rock_sample waypoint13)
	(at_soil_sample waypoint14)
	(at_soil_sample waypoint15)
	(at_soil_sample waypoint17)
	(at_rock_sample waypoint17)
	(at_soil_sample waypoint18)
	(at_rock_sample waypoint18)
	(at_soil_sample waypoint19)
	(at_lander general waypoint17)
	(channel_free general)
	(at rover0 waypoint2)
	(store_of rover0store rover0)
	(empty rover0store)
	(equipped_for_soil_analysis rover0)
	(equipped_for_rock_analysis rover0)
	(equipped_for_imaging rover0)
	(at rover1 waypoint9)
	(store_of rover1store rover1)
	(empty rover1store)
	(equipped_for_rock_analysis rover1)
	(equipped_for_imaging rover1)
	(at rover2 waypoint0)
	(store_of rover2store rover2)
	(empty rover2store)
	(equipped_for_soil_analysis rover2)
	(equipped_for_imaging rover2)
	(at rover3 waypoint18)
	(store_of rover3store rover3)
	(empty rover3store)
	(equipped_for_rock_analysis rover3)
	(equipped_for_imaging rover3)
	(at rover4 waypoint3)
	(store_of rover4store rover4)
	(empty rover4store)
	(equipped_for_soil_analysis rover4)
	(equipped_for_imaging rover4)
	(at rover5 waypoint0)
	(store_of rover5store rover5)
	(empty rover5store)
	(equipped_for_rock_analysis rover5)
	(equipped_for_imaging rover5)
	(on_board camera0 rover1)
	(calibration_target camera0 objective4)
	(supports camera0 high_res)
	(on_board camera1 rover2)
	(calibration_target camera1 objective6)
	(supports camera1 colour)
	(supports camera1 low_res)
	(on_board camera2 rover4)
	(calibration_target camera2 objective0)
	(supports camera2 colour)
	(supports camera2 high_res)
	(on_board camera3 rover3)
	(calibration_target camera3 objective6)
	(supports camera3 colour)
	(on_board camera4 rover3)
	(calibration_target camera4 objective4)
	(supports camera4 high_res)
	(supports camera4 low_res)
	(on_board camera5 rover0)
	(calibration_target camera5 objective2)
	(supports camera5 colour)
	(on_board camera6 rover5)
	(calibration_target camera6 objective6)
	(supports camera6 high_res)
	(supports camera6 low_res)

    ; action literals
    (navigate rover0 waypoint0)
    (navigate rover0 waypoint1)
    (navigate rover0 waypoint2)
    (navigate rover0 waypoint3)
    (navigate rover0 waypoint4)
    (navigate rover0 waypoint5)
    (navigate rover0 waypoint6)
    (navigate rover0 waypoint7)
    (navigate rover0 waypoint8)
    (navigate rover0 waypoint9)
    (navigate rover0 waypoint10)
    (navigate rover0 waypoint11)
    (navigate rover0 waypoint12)
    (navigate rover0 waypoint13)
    (navigate rover0 waypoint14)
    (navigate rover0 waypoint15)
    (navigate rover0 waypoint16)
    (navigate rover0 waypoint17)
    (navigate rover0 waypoint18)
    (navigate rover0 waypoint19)
    (navigate rover1 waypoint0)
    (navigate rover1 waypoint1)
    (navigate rover1 waypoint2)
    (navigate rover1 waypoint3)
    (navigate rover1 waypoint4)
    (navigate rover1 waypoint5)
    (navigate rover1 waypoint6)
    (navigate rover1 waypoint7)
    (navigate rover1 waypoint8)
    (navigate rover1 waypoint9)
    (navigate rover1 waypoint10)
    (navigate rover1 waypoint11)
    (navigate rover1 waypoint12)
    (navigate rover1 waypoint13)
    (navigate rover1 waypoint14)
    (navigate rover1 waypoint15)
    (navigate rover1 waypoint16)
    (navigate rover1 waypoint17)
    (navigate rover1 waypoint18)
    (navigate rover1 waypoint19)
    (navigate rover2 waypoint0)
    (navigate rover2 waypoint1)
    (navigate rover2 waypoint2)
    (navigate rover2 waypoint3)
    (navigate rover2 waypoint4)
    (navigate rover2 waypoint5)
    (navigate rover2 waypoint6)
    (navigate rover2 waypoint7)
    (navigate rover2 waypoint8)
    (navigate rover2 waypoint9)
    (navigate rover2 waypoint10)
    (navigate rover2 waypoint11)
    (navigate rover2 waypoint12)
    (navigate rover2 waypoint13)
    (navigate rover2 waypoint14)
    (navigate rover2 waypoint15)
    (navigate rover2 waypoint16)
    (navigate rover2 waypoint17)
    (navigate rover2 waypoint18)
    (navigate rover2 waypoint19)
    (navigate rover3 waypoint0)
    (navigate rover3 waypoint1)
    (navigate rover3 waypoint2)
    (navigate rover3 waypoint3)
    (navigate rover3 waypoint4)
    (navigate rover3 waypoint5)
    (navigate rover3 waypoint6)
    (navigate rover3 waypoint7)
    (navigate rover3 waypoint8)
    (navigate rover3 waypoint9)
    (navigate rover3 waypoint10)
    (navigate rover3 waypoint11)
    (navigate rover3 waypoint12)
    (navigate rover3 waypoint13)
    (navigate rover3 waypoint14)
    (navigate rover3 waypoint15)
    (navigate rover3 waypoint16)
    (navigate rover3 waypoint17)
    (navigate rover3 waypoint18)
    (navigate rover3 waypoint19)
    (navigate rover4 waypoint0)
    (navigate rover4 waypoint1)
    (navigate rover4 waypoint2)
    (navigate rover4 waypoint3)
    (navigate rover4 waypoint4)
    (navigate rover4 waypoint5)
    (navigate rover4 waypoint6)
    (navigate rover4 waypoint7)
    (navigate rover4 waypoint8)
    (navigate rover4 waypoint9)
    (navigate rover4 waypoint10)
    (navigate rover4 waypoint11)
    (navigate rover4 waypoint12)
    (navigate rover4 waypoint13)
    (navigate rover4 waypoint14)
    (navigate rover4 waypoint15)
    (navigate rover4 waypoint16)
    (navigate rover4 waypoint17)
    (navigate rover4 waypoint18)
    (navigate rover4 waypoint19)
    (navigate rover5 waypoint0)
    (navigate rover5 waypoint1)
    (navigate rover5 waypoint2)
    (navigate rover5 waypoint3)
    (navigate rover5 waypoint4)
    (navigate rover5 waypoint5)
    (navigate rover5 waypoint6)
    (navigate rover5 waypoint7)
    (navigate rover5 waypoint8)
    (navigate rover5 waypoint9)
    (navigate rover5 waypoint10)
    (navigate rover5 waypoint11)
    (navigate rover5 waypoint12)
    (navigate rover5 waypoint13)
    (navigate rover5 waypoint14)
    (navigate rover5 waypoint15)
    (navigate rover5 waypoint16)
    (navigate rover5 waypoint17)
    (navigate rover5 waypoint18)
    (navigate rover5 waypoint19)
    (sample_soil rover0)
    (sample_rock rover0)
    (drop rover0)
    (sample_soil rover1)
    (sample_rock rover1)
    (drop rover1)
    (sample_soil rover2)
    (sample_rock rover2)
    (drop rover2)
    (sample_soil rover3)
    (sample_rock rover3)
    (drop rover3)
    (sample_soil rover4)
    (sample_rock rover4)
    (drop rover4)
    (sample_soil rover5)
    (sample_rock rover5)
    (drop rover5)
    (calibrate camera0 objective0)
    (calibrate camera0 objective1)
    (calibrate camera0 objective2)
    (calibrate camera0 objective3)
    (calibrate camera0 objective4)
    (calibrate camera0 objective5)
    (calibrate camera0 objective6)
    (calibrate camera1 objective0)
    (calibrate camera1 objective1)
    (calibrate camera1 objective2)
    (calibrate camera1 objective3)
    (calibrate camera1 objective4)
    (calibrate camera1 objective5)
    (calibrate camera1 objective6)
    (calibrate camera2 objective0)
    (calibrate camera2 objective1)
    (calibrate camera2 objective2)
    (calibrate camera2 objective3)
    (calibrate camera2 objective4)
    (calibrate camera2 objective5)
    (calibrate camera2 objective6)
    (calibrate camera3 objective0)
    (calibrate camera3 objective1)
    (calibrate camera3 objective2)
    (calibrate camera3 objective3)
    (calibrate camera3 objective4)
    (calibrate camera3 objective5)
    (calibrate camera3 objective6)
    (calibrate camera4 objective0)
    (calibrate camera4 objective1)
    (calibrate camera4 objective2)
    (calibrate camera4 objective3)
    (calibrate camera4 objective4)
    (calibrate camera4 objective5)
    (calibrate camera4 objective6)
    (calibrate camera5 objective0)
    (calibrate camera5 objective1)
    (calibrate camera5 objective2)
    (calibrate camera5 objective3)
    (calibrate camera5 objective4)
    (calibrate camera5 objective5)
    (calibrate camera5 objective6)
    (calibrate camera6 objective0)
    (calibrate camera6 objective1)
    (calibrate camera6 objective2)
    (calibrate camera6 objective3)
    (calibrate camera6 objective4)
    (calibrate camera6 objective5)
    (calibrate camera6 objective6)
    (take_image objective0 camera0 colour)
    (take_image objective0 camera0 high_res)
    (take_image objective0 camera0 low_res)
    (take_image objective0 camera1 colour)
    (take_image objective0 camera1 high_res)
    (take_image objective0 camera1 low_res)
    (take_image objective0 camera2 colour)
    (take_image objective0 camera2 high_res)
    (take_image objective0 camera2 low_res)
    (take_image objective0 camera3 colour)
    (take_image objective0 camera3 high_res)
    (take_image objective0 camera3 low_res)
    (take_image objective0 camera4 colour)
    (take_image objective0 camera4 high_res)
    (take_image objective0 camera4 low_res)
    (take_image objective0 camera5 colour)
    (take_image objective0 camera5 high_res)
    (take_image objective0 camera5 low_res)
    (take_image objective0 camera6 colour)
    (take_image objective0 camera6 high_res)
    (take_image objective0 camera6 low_res)
    (take_image objective1 camera0 colour)
    (take_image objective1 camera0 high_res)
    (take_image objective1 camera0 low_res)
    (take_image objective1 camera1 colour)
    (take_image objective1 camera1 high_res)
    (take_image objective1 camera1 low_res)
    (take_image objective1 camera2 colour)
    (take_image objective1 camera2 high_res)
    (take_image objective1 camera2 low_res)
    (take_image objective1 camera3 colour)
    (take_image objective1 camera3 high_res)
    (take_image objective1 camera3 low_res)
    (take_image objective1 camera4 colour)
    (take_image objective1 camera4 high_res)
    (take_image objective1 camera4 low_res)
    (take_image objective1 camera5 colour)
    (take_image objective1 camera5 high_res)
    (take_image objective1 camera5 low_res)
    (take_image objective1 camera6 colour)
    (take_image objective1 camera6 high_res)
    (take_image objective1 camera6 low_res)
    (take_image objective2 camera0 colour)
    (take_image objective2 camera0 high_res)
    (take_image objective2 camera0 low_res)
    (take_image objective2 camera1 colour)
    (take_image objective2 camera1 high_res)
    (take_image objective2 camera1 low_res)
    (take_image objective2 camera2 colour)
    (take_image objective2 camera2 high_res)
    (take_image objective2 camera2 low_res)
    (take_image objective2 camera3 colour)
    (take_image objective2 camera3 high_res)
    (take_image objective2 camera3 low_res)
    (take_image objective2 camera4 colour)
    (take_image objective2 camera4 high_res)
    (take_image objective2 camera4 low_res)
    (take_image objective2 camera5 colour)
    (take_image objective2 camera5 high_res)
    (take_image objective2 camera5 low_res)
    (take_image objective2 camera6 colour)
    (take_image objective2 camera6 high_res)
    (take_image objective2 camera6 low_res)
    (take_image objective3 camera0 colour)
    (take_image objective3 camera0 high_res)
    (take_image objective3 camera0 low_res)
    (take_image objective3 camera1 colour)
    (take_image objective3 camera1 high_res)
    (take_image objective3 camera1 low_res)
    (take_image objective3 camera2 colour)
    (take_image objective3 camera2 high_res)
    (take_image objective3 camera2 low_res)
    (take_image objective3 camera3 colour)
    (take_image objective3 camera3 high_res)
    (take_image objective3 camera3 low_res)
    (take_image objective3 camera4 colour)
    (take_image objective3 camera4 high_res)
    (take_image objective3 camera4 low_res)
    (take_image objective3 camera5 colour)
    (take_image objective3 camera5 high_res)
    (take_image objective3 camera5 low_res)
    (take_image objective3 camera6 colour)
    (take_image objective3 camera6 high_res)
    (take_image objective3 camera6 low_res)
    (take_image objective4 camera0 colour)
    (take_image objective4 camera0 high_res)
    (take_image objective4 camera0 low_res)
    (take_image objective4 camera1 colour)
    (take_image objective4 camera1 high_res)
    (take_image objective4 camera1 low_res)
    (take_image objective4 camera2 colour)
    (take_image objective4 camera2 high_res)
    (take_image objective4 camera2 low_res)
    (take_image objective4 camera3 colour)
    (take_image objective4 camera3 high_res)
    (take_image objective4 camera3 low_res)
    (take_image objective4 camera4 colour)
    (take_image objective4 camera4 high_res)
    (take_image objective4 camera4 low_res)
    (take_image objective4 camera5 colour)
    (take_image objective4 camera5 high_res)
    (take_image objective4 camera5 low_res)
    (take_image objective4 camera6 colour)
    (take_image objective4 camera6 high_res)
    (take_image objective4 camera6 low_res)
    (take_image objective5 camera0 colour)
    (take_image objective5 camera0 high_res)
    (take_image objective5 camera0 low_res)
    (take_image objective5 camera1 colour)
    (take_image objective5 camera1 high_res)
    (take_image objective5 camera1 low_res)
    (take_image objective5 camera2 colour)
    (take_image objective5 camera2 high_res)
    (take_image objective5 camera2 low_res)
    (take_image objective5 camera3 colour)
    (take_image objective5 camera3 high_res)
    (take_image objective5 camera3 low_res)
    (take_image objective5 camera4 colour)
    (take_image objective5 camera4 high_res)
    (take_image objective5 camera4 low_res)
    (take_image objective5 camera5 colour)
    (take_image objective5 camera5 high_res)
    (take_image objective5 camera5 low_res)
    (take_image objective5 camera6 colour)
    (take_image objective5 camera6 high_res)
    (take_image objective5 camera6 low_res)
    (take_image objective6 camera0 colour)
    (take_image objective6 camera0 high_res)
    (take_image objective6 camera0 low_res)
    (take_image objective6 camera1 colour)
    (take_image objective6 camera1 high_res)
    (take_image objective6 camera1 low_res)
    (take_image objective6 camera2 colour)
    (take_image objective6 camera2 high_res)
    (take_image objective6 camera2 low_res)
    (take_image objective6 camera3 colour)
    (take_image objective6 camera3 high_res)
    (take_image objective6 camera3 low_res)
    (take_image objective6 camera4 colour)
    (take_image objective6 camera4 high_res)
    (take_image objective6 camera4 low_res)
    (take_image objective6 camera5 colour)
    (take_image objective6 camera5 high_res)
    (take_image objective6 camera5 low_res)
    (take_image objective6 camera6 colour)
    (take_image objective6 camera6 high_res)
    (take_image objective6 camera6 low_res)
    (communicate_soil_data rover0 waypoint0)
    (communicate_rock_data rover0 waypoint0)
    (communicate_soil_data rover0 waypoint1)
    (communicate_rock_data rover0 waypoint1)
    (communicate_soil_data rover0 waypoint2)
    (communicate_rock_data rover0 waypoint2)
    (communicate_soil_data rover0 waypoint3)
    (communicate_rock_data rover0 waypoint3)
    (communicate_soil_data rover0 waypoint4)
    (communicate_rock_data rover0 waypoint4)
    (communicate_soil_data rover0 waypoint5)
    (communicate_rock_data rover0 waypoint5)
    (communicate_soil_data rover0 waypoint6)
    (communicate_rock_data rover0 waypoint6)
    (communicate_soil_data rover0 waypoint7)
    (communicate_rock_data rover0 waypoint7)
    (communicate_soil_data rover0 waypoint8)
    (communicate_rock_data rover0 waypoint8)
    (communicate_soil_data rover0 waypoint9)
    (communicate_rock_data rover0 waypoint9)
    (communicate_soil_data rover0 waypoint10)
    (communicate_rock_data rover0 waypoint10)
    (communicate_soil_data rover0 waypoint11)
    (communicate_rock_data rover0 waypoint11)
    (communicate_soil_data rover0 waypoint12)
    (communicate_rock_data rover0 waypoint12)
    (communicate_soil_data rover0 waypoint13)
    (communicate_rock_data rover0 waypoint13)
    (communicate_soil_data rover0 waypoint14)
    (communicate_rock_data rover0 waypoint14)
    (communicate_soil_data rover0 waypoint15)
    (communicate_rock_data rover0 waypoint15)
    (communicate_soil_data rover0 waypoint16)
    (communicate_rock_data rover0 waypoint16)
    (communicate_soil_data rover0 waypoint17)
    (communicate_rock_data rover0 waypoint17)
    (communicate_soil_data rover0 waypoint18)
    (communicate_rock_data rover0 waypoint18)
    (communicate_soil_data rover0 waypoint19)
    (communicate_rock_data rover0 waypoint19)
    (communicate_soil_data rover1 waypoint0)
    (communicate_rock_data rover1 waypoint0)
    (communicate_soil_data rover1 waypoint1)
    (communicate_rock_data rover1 waypoint1)
    (communicate_soil_data rover1 waypoint2)
    (communicate_rock_data rover1 waypoint2)
    (communicate_soil_data rover1 waypoint3)
    (communicate_rock_data rover1 waypoint3)
    (communicate_soil_data rover1 waypoint4)
    (communicate_rock_data rover1 waypoint4)
    (communicate_soil_data rover1 waypoint5)
    (communicate_rock_data rover1 waypoint5)
    (communicate_soil_data rover1 waypoint6)
    (communicate_rock_data rover1 waypoint6)
    (communicate_soil_data rover1 waypoint7)
    (communicate_rock_data rover1 waypoint7)
    (communicate_soil_data rover1 waypoint8)
    (communicate_rock_data rover1 waypoint8)
    (communicate_soil_data rover1 waypoint9)
    (communicate_rock_data rover1 waypoint9)
    (communicate_soil_data rover1 waypoint10)
    (communicate_rock_data rover1 waypoint10)
    (communicate_soil_data rover1 waypoint11)
    (communicate_rock_data rover1 waypoint11)
    (communicate_soil_data rover1 waypoint12)
    (communicate_rock_data rover1 waypoint12)
    (communicate_soil_data rover1 waypoint13)
    (communicate_rock_data rover1 waypoint13)
    (communicate_soil_data rover1 waypoint14)
    (communicate_rock_data rover1 waypoint14)
    (communicate_soil_data rover1 waypoint15)
    (communicate_rock_data rover1 waypoint15)
    (communicate_soil_data rover1 waypoint16)
    (communicate_rock_data rover1 waypoint16)
    (communicate_soil_data rover1 waypoint17)
    (communicate_rock_data rover1 waypoint17)
    (communicate_soil_data rover1 waypoint18)
    (communicate_rock_data rover1 waypoint18)
    (communicate_soil_data rover1 waypoint19)
    (communicate_rock_data rover1 waypoint19)
    (communicate_soil_data rover2 waypoint0)
    (communicate_rock_data rover2 waypoint0)
    (communicate_soil_data rover2 waypoint1)
    (communicate_rock_data rover2 waypoint1)
    (communicate_soil_data rover2 waypoint2)
    (communicate_rock_data rover2 waypoint2)
    (communicate_soil_data rover2 waypoint3)
    (communicate_rock_data rover2 waypoint3)
    (communicate_soil_data rover2 waypoint4)
    (communicate_rock_data rover2 waypoint4)
    (communicate_soil_data rover2 waypoint5)
    (communicate_rock_data rover2 waypoint5)
    (communicate_soil_data rover2 waypoint6)
    (communicate_rock_data rover2 waypoint6)
    (communicate_soil_data rover2 waypoint7)
    (communicate_rock_data rover2 waypoint7)
    (communicate_soil_data rover2 waypoint8)
    (communicate_rock_data rover2 waypoint8)
    (communicate_soil_data rover2 waypoint9)
    (communicate_rock_data rover2 waypoint9)
    (communicate_soil_data rover2 waypoint10)
    (communicate_rock_data rover2 waypoint10)
    (communicate_soil_data rover2 waypoint11)
    (communicate_rock_data rover2 waypoint11)
    (communicate_soil_data rover2 waypoint12)
    (communicate_rock_data rover2 waypoint12)
    (communicate_soil_data rover2 waypoint13)
    (communicate_rock_data rover2 waypoint13)
    (communicate_soil_data rover2 waypoint14)
    (communicate_rock_data rover2 waypoint14)
    (communicate_soil_data rover2 waypoint15)
    (communicate_rock_data rover2 waypoint15)
    (communicate_soil_data rover2 waypoint16)
    (communicate_rock_data rover2 waypoint16)
    (communicate_soil_data rover2 waypoint17)
    (communicate_rock_data rover2 waypoint17)
    (communicate_soil_data rover2 waypoint18)
    (communicate_rock_data rover2 waypoint18)
    (communicate_soil_data rover2 waypoint19)
    (communicate_rock_data rover2 waypoint19)
    (communicate_soil_data rover3 waypoint0)
    (communicate_rock_data rover3 waypoint0)
    (communicate_soil_data rover3 waypoint1)
    (communicate_rock_data rover3 waypoint1)
    (communicate_soil_data rover3 waypoint2)
    (communicate_rock_data rover3 waypoint2)
    (communicate_soil_data rover3 waypoint3)
    (communicate_rock_data rover3 waypoint3)
    (communicate_soil_data rover3 waypoint4)
    (communicate_rock_data rover3 waypoint4)
    (communicate_soil_data rover3 waypoint5)
    (communicate_rock_data rover3 waypoint5)
    (communicate_soil_data rover3 waypoint6)
    (communicate_rock_data rover3 waypoint6)
    (communicate_soil_data rover3 waypoint7)
    (communicate_rock_data rover3 waypoint7)
    (communicate_soil_data rover3 waypoint8)
    (communicate_rock_data rover3 waypoint8)
    (communicate_soil_data rover3 waypoint9)
    (communicate_rock_data rover3 waypoint9)
    (communicate_soil_data rover3 waypoint10)
    (communicate_rock_data rover3 waypoint10)
    (communicate_soil_data rover3 waypoint11)
    (communicate_rock_data rover3 waypoint11)
    (communicate_soil_data rover3 waypoint12)
    (communicate_rock_data rover3 waypoint12)
    (communicate_soil_data rover3 waypoint13)
    (communicate_rock_data rover3 waypoint13)
    (communicate_soil_data rover3 waypoint14)
    (communicate_rock_data rover3 waypoint14)
    (communicate_soil_data rover3 waypoint15)
    (communicate_rock_data rover3 waypoint15)
    (communicate_soil_data rover3 waypoint16)
    (communicate_rock_data rover3 waypoint16)
    (communicate_soil_data rover3 waypoint17)
    (communicate_rock_data rover3 waypoint17)
    (communicate_soil_data rover3 waypoint18)
    (communicate_rock_data rover3 waypoint18)
    (communicate_soil_data rover3 waypoint19)
    (communicate_rock_data rover3 waypoint19)
    (communicate_soil_data rover4 waypoint0)
    (communicate_rock_data rover4 waypoint0)
    (communicate_soil_data rover4 waypoint1)
    (communicate_rock_data rover4 waypoint1)
    (communicate_soil_data rover4 waypoint2)
    (communicate_rock_data rover4 waypoint2)
    (communicate_soil_data rover4 waypoint3)
    (communicate_rock_data rover4 waypoint3)
    (communicate_soil_data rover4 waypoint4)
    (communicate_rock_data rover4 waypoint4)
    (communicate_soil_data rover4 waypoint5)
    (communicate_rock_data rover4 waypoint5)
    (communicate_soil_data rover4 waypoint6)
    (communicate_rock_data rover4 waypoint6)
    (communicate_soil_data rover4 waypoint7)
    (communicate_rock_data rover4 waypoint7)
    (communicate_soil_data rover4 waypoint8)
    (communicate_rock_data rover4 waypoint8)
    (communicate_soil_data rover4 waypoint9)
    (communicate_rock_data rover4 waypoint9)
    (communicate_soil_data rover4 waypoint10)
    (communicate_rock_data rover4 waypoint10)
    (communicate_soil_data rover4 waypoint11)
    (communicate_rock_data rover4 waypoint11)
    (communicate_soil_data rover4 waypoint12)
    (communicate_rock_data rover4 waypoint12)
    (communicate_soil_data rover4 waypoint13)
    (communicate_rock_data rover4 waypoint13)
    (communicate_soil_data rover4 waypoint14)
    (communicate_rock_data rover4 waypoint14)
    (communicate_soil_data rover4 waypoint15)
    (communicate_rock_data rover4 waypoint15)
    (communicate_soil_data rover4 waypoint16)
    (communicate_rock_data rover4 waypoint16)
    (communicate_soil_data rover4 waypoint17)
    (communicate_rock_data rover4 waypoint17)
    (communicate_soil_data rover4 waypoint18)
    (communicate_rock_data rover4 waypoint18)
    (communicate_soil_data rover4 waypoint19)
    (communicate_rock_data rover4 waypoint19)
    (communicate_soil_data rover5 waypoint0)
    (communicate_rock_data rover5 waypoint0)
    (communicate_soil_data rover5 waypoint1)
    (communicate_rock_data rover5 waypoint1)
    (communicate_soil_data rover5 waypoint2)
    (communicate_rock_data rover5 waypoint2)
    (communicate_soil_data rover5 waypoint3)
    (communicate_rock_data rover5 waypoint3)
    (communicate_soil_data rover5 waypoint4)
    (communicate_rock_data rover5 waypoint4)
    (communicate_soil_data rover5 waypoint5)
    (communicate_rock_data rover5 waypoint5)
    (communicate_soil_data rover5 waypoint6)
    (communicate_rock_data rover5 waypoint6)
    (communicate_soil_data rover5 waypoint7)
    (communicate_rock_data rover5 waypoint7)
    (communicate_soil_data rover5 waypoint8)
    (communicate_rock_data rover5 waypoint8)
    (communicate_soil_data rover5 waypoint9)
    (communicate_rock_data rover5 waypoint9)
    (communicate_soil_data rover5 waypoint10)
    (communicate_rock_data rover5 waypoint10)
    (communicate_soil_data rover5 waypoint11)
    (communicate_rock_data rover5 waypoint11)
    (communicate_soil_data rover5 waypoint12)
    (communicate_rock_data rover5 waypoint12)
    (communicate_soil_data rover5 waypoint13)
    (communicate_rock_data rover5 waypoint13)
    (communicate_soil_data rover5 waypoint14)
    (communicate_rock_data rover5 waypoint14)
    (communicate_soil_data rover5 waypoint15)
    (communicate_rock_data rover5 waypoint15)
    (communicate_soil_data rover5 waypoint16)
    (communicate_rock_data rover5 waypoint16)
    (communicate_soil_data rover5 waypoint17)
    (communicate_rock_data rover5 waypoint17)
    (communicate_soil_data rover5 waypoint18)
    (communicate_rock_data rover5 waypoint18)
    (communicate_soil_data rover5 waypoint19)
    (communicate_rock_data rover5 waypoint19)
    (communicate_image_data rover0 objective0 colour)
    (communicate_image_data rover0 objective0 high_res)
    (communicate_image_data rover0 objective0 low_res)
    (communicate_image_data rover0 objective1 colour)
    (communicate_image_data rover0 objective1 high_res)
    (communicate_image_data rover0 objective1 low_res)
    (communicate_image_data rover0 objective2 colour)
    (communicate_image_data rover0 objective2 high_res)
    (communicate_image_data rover0 objective2 low_res)
    (communicate_image_data rover0 objective3 colour)
    (communicate_image_data rover0 objective3 high_res)
    (communicate_image_data rover0 objective3 low_res)
    (communicate_image_data rover0 objective4 colour)
    (communicate_image_data rover0 objective4 high_res)
    (communicate_image_data rover0 objective4 low_res)
    (communicate_image_data rover0 objective5 colour)
    (communicate_image_data rover0 objective5 high_res)
    (communicate_image_data rover0 objective5 low_res)
    (communicate_image_data rover0 objective6 colour)
    (communicate_image_data rover0 objective6 high_res)
    (communicate_image_data rover0 objective6 low_res)
    (communicate_image_data rover1 objective0 colour)
    (communicate_image_data rover1 objective0 high_res)
    (communicate_image_data rover1 objective0 low_res)
    (communicate_image_data rover1 objective1 colour)
    (communicate_image_data rover1 objective1 high_res)
    (communicate_image_data rover1 objective1 low_res)
    (communicate_image_data rover1 objective2 colour)
    (communicate_image_data rover1 objective2 high_res)
    (communicate_image_data rover1 objective2 low_res)
    (communicate_image_data rover1 objective3 colour)
    (communicate_image_data rover1 objective3 high_res)
    (communicate_image_data rover1 objective3 low_res)
    (communicate_image_data rover1 objective4 colour)
    (communicate_image_data rover1 objective4 high_res)
    (communicate_image_data rover1 objective4 low_res)
    (communicate_image_data rover1 objective5 colour)
    (communicate_image_data rover1 objective5 high_res)
    (communicate_image_data rover1 objective5 low_res)
    (communicate_image_data rover1 objective6 colour)
    (communicate_image_data rover1 objective6 high_res)
    (communicate_image_data rover1 objective6 low_res)
    (communicate_image_data rover2 objective0 colour)
    (communicate_image_data rover2 objective0 high_res)
    (communicate_image_data rover2 objective0 low_res)
    (communicate_image_data rover2 objective1 colour)
    (communicate_image_data rover2 objective1 high_res)
    (communicate_image_data rover2 objective1 low_res)
    (communicate_image_data rover2 objective2 colour)
    (communicate_image_data rover2 objective2 high_res)
    (communicate_image_data rover2 objective2 low_res)
    (communicate_image_data rover2 objective3 colour)
    (communicate_image_data rover2 objective3 high_res)
    (communicate_image_data rover2 objective3 low_res)
    (communicate_image_data rover2 objective4 colour)
    (communicate_image_data rover2 objective4 high_res)
    (communicate_image_data rover2 objective4 low_res)
    (communicate_image_data rover2 objective5 colour)
    (communicate_image_data rover2 objective5 high_res)
    (communicate_image_data rover2 objective5 low_res)
    (communicate_image_data rover2 objective6 colour)
    (communicate_image_data rover2 objective6 high_res)
    (communicate_image_data rover2 objective6 low_res)
    (communicate_image_data rover3 objective0 colour)
    (communicate_image_data rover3 objective0 high_res)
    (communicate_image_data rover3 objective0 low_res)
    (communicate_image_data rover3 objective1 colour)
    (communicate_image_data rover3 objective1 high_res)
    (communicate_image_data rover3 objective1 low_res)
    (communicate_image_data rover3 objective2 colour)
    (communicate_image_data rover3 objective2 high_res)
    (communicate_image_data rover3 objective2 low_res)
    (communicate_image_data rover3 objective3 colour)
    (communicate_image_data rover3 objective3 high_res)
    (communicate_image_data rover3 objective3 low_res)
    (communicate_image_data rover3 objective4 colour)
    (communicate_image_data rover3 objective4 high_res)
    (communicate_image_data rover3 objective4 low_res)
    (communicate_image_data rover3 objective5 colour)
    (communicate_image_data rover3 objective5 high_res)
    (communicate_image_data rover3 objective5 low_res)
    (communicate_image_data rover3 objective6 colour)
    (communicate_image_data rover3 objective6 high_res)
    (communicate_image_data rover3 objective6 low_res)
    (communicate_image_data rover4 objective0 colour)
    (communicate_image_data rover4 objective0 high_res)
    (communicate_image_data rover4 objective0 low_res)
    (communicate_image_data rover4 objective1 colour)
    (communicate_image_data rover4 objective1 high_res)
    (communicate_image_data rover4 objective1 low_res)
    (communicate_image_data rover4 objective2 colour)
    (communicate_image_data rover4 objective2 high_res)
    (communicate_image_data rover4 objective2 low_res)
    (communicate_image_data rover4 objective3 colour)
    (communicate_image_data rover4 objective3 high_res)
    (communicate_image_data rover4 objective3 low_res)
    (communicate_image_data rover4 objective4 colour)
    (communicate_image_data rover4 objective4 high_res)
    (communicate_image_data rover4 objective4 low_res)
    (communicate_image_data rover4 objective5 colour)
    (communicate_image_data rover4 objective5 high_res)
    (communicate_image_data rover4 objective5 low_res)
    (communicate_image_data rover4 objective6 colour)
    (communicate_image_data rover4 objective6 high_res)
    (communicate_image_data rover4 objective6 low_res)
    (communicate_image_data rover5 objective0 colour)
    (communicate_image_data rover5 objective0 high_res)
    (communicate_image_data rover5 objective0 low_res)
    (communicate_image_data rover5 objective1 colour)
    (communicate_image_data rover5 objective1 high_res)
    (communicate_image_data rover5 objective1 low_res)
    (communicate_image_data rover5 objective2 colour)
    (communicate_image_data rover5 objective2 high_res)
    (communicate_image_data rover5 objective2 low_res)
    (communicate_image_data rover5 objective3 colour)
    (communicate_image_data rover5 objective3 high_res)
    (communicate_image_data rover5 objective3 low_res)
    (communicate_image_data rover5 objective4 colour)
    (communicate_image_data rover5 objective4 high_res)
    (communicate_image_data rover5 objective4 low_res)
    (communicate_image_data rover5 objective5 colour)
    (communicate_image_data rover5 objective5 high_res)
    (communicate_image_data rover5 objective5 low_res)
    (communicate_image_data rover5 objective6 colour)
    (communicate_image_data rover5 objective6 high_res)
    (communicate_image_data rover5 objective6 low_res)
    )

(:goal (and
(communicated_soil_data waypoint14)
(communicated_soil_data waypoint0)
(communicated_rock_data waypoint4)
(communicated_rock_data waypoint7)
(communicated_rock_data waypoint2)
(communicated_rock_data waypoint5)
(communicated_rock_data waypoint6)
(communicated_image_data objective5 colour)
(communicated_image_data objective3 low_res)
(communicated_image_data objective2 colour)
(communicated_image_data objective4 high_res)
	)
)
)
