; Problem taken from https://github.com/AI-Planning/classical-domains

(define (problem roverprob2006) (:domain Rover)
(:objects
	general - Lander
	colour high_res low_res - Mode
	rover0 rover1 rover2 rover3 rover4 rover5 rover6 rover7 rover8 rover9 rover10 rover11 rover12 rover13 - Rover
	rover0store rover1store rover2store rover3store rover4store rover5store rover6store rover7store rover8store rover9store rover10store rover11store rover12store rover13store - Store
	waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 waypoint11 waypoint12 waypoint13 waypoint14 waypoint15 waypoint16 waypoint17 waypoint18 waypoint19 waypoint20 waypoint21 waypoint22 waypoint23 waypoint24 waypoint25 waypoint26 waypoint27 waypoint28 waypoint29 waypoint30 waypoint31 waypoint32 waypoint33 waypoint34 waypoint35 waypoint36 waypoint37 waypoint38 waypoint39 waypoint40 waypoint41 waypoint42 waypoint43 waypoint44 waypoint45 waypoint46 waypoint47 waypoint48 waypoint49 waypoint50 waypoint51 waypoint52 waypoint53 waypoint54 waypoint55 waypoint56 waypoint57 waypoint58 waypoint59 waypoint60 waypoint61 waypoint62 waypoint63 waypoint64 waypoint65 waypoint66 waypoint67 waypoint68 waypoint69 waypoint70 waypoint71 waypoint72 waypoint73 waypoint74 waypoint75 waypoint76 waypoint77 waypoint78 waypoint79 waypoint80 waypoint81 waypoint82 waypoint83 waypoint84 waypoint85 waypoint86 waypoint87 waypoint88 waypoint89 waypoint90 waypoint91 waypoint92 waypoint93 waypoint94 waypoint95 waypoint96 waypoint97 waypoint98 waypoint99 - Waypoint
	camera0 camera1 camera2 camera3 camera4 camera5 camera6 camera7 camera8 camera9 camera10 camera11 camera12 camera13 camera14 - Camera
	objective0 objective1 objective2 objective3 objective4 objective5 objective6 objective7 objective8 objective9 objective10 - Objective
	)
(:init
	(at_soil_sample waypoint0)
	(at_rock_sample waypoint0)
	(at_rock_sample waypoint2)
	(at_soil_sample waypoint3)
	(at_soil_sample waypoint4)
	(at_rock_sample waypoint5)
	(at_rock_sample waypoint7)
	(at_rock_sample waypoint8)
	(at_soil_sample waypoint9)
	(at_soil_sample waypoint10)
	(at_rock_sample waypoint10)
	(at_soil_sample waypoint11)
	(at_soil_sample waypoint14)
	(at_soil_sample waypoint15)
	(at_rock_sample waypoint16)
	(at_rock_sample waypoint17)
	(at_rock_sample waypoint18)
	(at_soil_sample waypoint19)
	(at_rock_sample waypoint19)
	(at_soil_sample waypoint20)
	(at_rock_sample waypoint22)
	(at_soil_sample waypoint23)
	(at_rock_sample waypoint23)
	(at_rock_sample waypoint24)
	(at_rock_sample waypoint25)
	(at_soil_sample waypoint26)
	(at_rock_sample waypoint26)
	(at_soil_sample waypoint28)
	(at_soil_sample waypoint29)
	(at_soil_sample waypoint30)
	(at_rock_sample waypoint30)
	(at_soil_sample waypoint31)
	(at_rock_sample waypoint31)
	(at_soil_sample waypoint32)
	(at_soil_sample waypoint33)
	(at_rock_sample waypoint33)
	(at_soil_sample waypoint34)
	(at_soil_sample waypoint35)
	(at_soil_sample waypoint36)
	(at_soil_sample waypoint37)
	(at_rock_sample waypoint39)
	(at_soil_sample waypoint40)
	(at_soil_sample waypoint41)
	(at_soil_sample waypoint43)
	(at_rock_sample waypoint43)
	(at_soil_sample waypoint44)
	(at_soil_sample waypoint45)
	(at_rock_sample waypoint46)
	(at_soil_sample waypoint47)
	(at_rock_sample waypoint47)
	(at_soil_sample waypoint49)
	(at_soil_sample waypoint50)
	(at_rock_sample waypoint51)
	(at_soil_sample waypoint53)
	(at_rock_sample waypoint53)
	(at_rock_sample waypoint54)
	(at_rock_sample waypoint56)
	(at_rock_sample waypoint58)
	(at_soil_sample waypoint59)
	(at_soil_sample waypoint60)
	(at_soil_sample waypoint61)
	(at_rock_sample waypoint61)
	(at_soil_sample waypoint62)
	(at_rock_sample waypoint62)
	(at_soil_sample waypoint63)
	(at_rock_sample waypoint63)
	(at_rock_sample waypoint64)
	(at_soil_sample waypoint66)
	(at_rock_sample waypoint66)
	(at_rock_sample waypoint67)
	(at_rock_sample waypoint68)
	(at_soil_sample waypoint69)
	(at_rock_sample waypoint69)
	(at_rock_sample waypoint70)
	(at_soil_sample waypoint71)
	(at_rock_sample waypoint72)
	(at_soil_sample waypoint73)
	(at_rock_sample waypoint73)
	(at_soil_sample waypoint74)
	(at_rock_sample waypoint75)
	(at_soil_sample waypoint77)
	(at_rock_sample waypoint77)
	(at_rock_sample waypoint78)
	(at_soil_sample waypoint79)
	(at_rock_sample waypoint79)
	(at_rock_sample waypoint80)
	(at_soil_sample waypoint81)
	(at_soil_sample waypoint82)
	(at_rock_sample waypoint82)
	(at_soil_sample waypoint83)
	(at_soil_sample waypoint84)
	(at_rock_sample waypoint84)
	(at_rock_sample waypoint86)
	(at_rock_sample waypoint87)
	(at_rock_sample waypoint88)
	(at_rock_sample waypoint89)
	(at_soil_sample waypoint90)
	(at_rock_sample waypoint90)
	(at_soil_sample waypoint91)
	(at_rock_sample waypoint91)
	(at_rock_sample waypoint92)
	(at_soil_sample waypoint93)
	(at_soil_sample waypoint94)
	(at_rock_sample waypoint94)
	(at_soil_sample waypoint95)
	(at_rock_sample waypoint95)
	(at_soil_sample waypoint96)
	(at_soil_sample waypoint97)
	(at_rock_sample waypoint97)
	(at_rock_sample waypoint98)
	(at_soil_sample waypoint99)
	(at_lander general waypoint21)
	(channel_free general)
	(at rover0 waypoint5)
	(store_of rover0store rover0)
	(empty rover0store)
	(equipped_for_soil_analysis rover0)
	(equipped_for_rock_analysis rover0)
	(equipped_for_imaging rover0)
	(at rover1 waypoint94)
	(store_of rover1store rover1)
	(empty rover1store)
	(equipped_for_rock_analysis rover1)
	(at rover2 waypoint86)
	(store_of rover2store rover2)
	(empty rover2store)
	(equipped_for_soil_analysis rover2)
	(equipped_for_rock_analysis rover2)
	(equipped_for_imaging rover2)
	(at rover3 waypoint63)
	(store_of rover3store rover3)
	(empty rover3store)
	(equipped_for_soil_analysis rover3)
	(equipped_for_rock_analysis rover3)
	(equipped_for_imaging rover3)
	(at rover4 waypoint49)
	(store_of rover4store rover4)
	(empty rover4store)
	(equipped_for_soil_analysis rover4)
	(equipped_for_rock_analysis rover4)
	(equipped_for_imaging rover4)
	(at rover5 waypoint57)
	(store_of rover5store rover5)
	(empty rover5store)
	(equipped_for_soil_analysis rover5)
	(equipped_for_rock_analysis rover5)
	(equipped_for_imaging rover5)
	(at rover6 waypoint22)
	(store_of rover6store rover6)
	(empty rover6store)
	(equipped_for_soil_analysis rover6)
	(equipped_for_rock_analysis rover6)
	(equipped_for_imaging rover6)
	(at rover7 waypoint85)
	(store_of rover7store rover7)
	(empty rover7store)
	(equipped_for_imaging rover7)
	(at rover8 waypoint77)
	(store_of rover8store rover8)
	(empty rover8store)
	(equipped_for_soil_analysis rover8)
	(equipped_for_rock_analysis rover8)
	(at rover9 waypoint12)
	(store_of rover9store rover9)
	(empty rover9store)
	(equipped_for_soil_analysis rover9)
	(at rover10 waypoint45)
	(store_of rover10store rover10)
	(empty rover10store)
	(equipped_for_imaging rover10)
	(at rover11 waypoint35)
	(store_of rover11store rover11)
	(empty rover11store)
	(equipped_for_soil_analysis rover11)
	(equipped_for_rock_analysis rover11)
	(equipped_for_imaging rover11)
	(at rover12 waypoint59)
	(store_of rover12store rover12)
	(empty rover12store)
	(equipped_for_rock_analysis rover12)
	(equipped_for_imaging rover12)
	(at rover13 waypoint66)
	(store_of rover13store rover13)
	(empty rover13store)
	(equipped_for_rock_analysis rover13)
	(equipped_for_imaging rover13)
	(on_board camera0 rover2)
	(calibration_target camera0 objective2)
	(supports camera0 low_res)
	(on_board camera1 rover13)
	(calibration_target camera1 objective3)
	(supports camera1 colour)
	(supports camera1 low_res)
	(on_board camera2 rover11)
	(calibration_target camera2 objective7)
	(supports camera2 high_res)
	(supports camera2 low_res)
	(on_board camera3 rover7)
	(calibration_target camera3 objective9)
	(supports camera3 colour)
	(supports camera3 high_res)
	(on_board camera4 rover12)
	(calibration_target camera4 objective7)
	(supports camera4 colour)
	(supports camera4 low_res)
	(on_board camera5 rover7)
	(calibration_target camera5 objective5)
	(supports camera5 colour)
	(supports camera5 high_res)
	(on_board camera6 rover7)
	(calibration_target camera6 objective0)
	(supports camera6 colour)
	(supports camera6 high_res)
	(supports camera6 low_res)
	(on_board camera7 rover3)
	(calibration_target camera7 objective10)
	(supports camera7 colour)
	(supports camera7 low_res)
	(on_board camera8 rover3)
	(calibration_target camera8 objective8)
	(supports camera8 colour)
	(supports camera8 high_res)
	(supports camera8 low_res)
	(on_board camera9 rover11)
	(calibration_target camera9 objective3)
	(supports camera9 colour)
	(supports camera9 low_res)
	(on_board camera10 rover0)
	(calibration_target camera10 objective2)
	(supports camera10 low_res)
	(on_board camera11 rover4)
	(calibration_target camera11 objective8)
	(supports camera11 low_res)
	(on_board camera12 rover5)
	(calibration_target camera12 objective1)
	(supports camera12 colour)
	(supports camera12 high_res)
	(supports camera12 low_res)
	(on_board camera13 rover6)
	(calibration_target camera13 objective3)
	(supports camera13 colour)
	(supports camera13 low_res)
	(on_board camera14 rover10)
	(calibration_target camera14 objective9)
	(supports camera14 high_res)
)

(:goal (and
(communicated_soil_data waypoint53)
(communicated_soil_data waypoint20)
(communicated_soil_data waypoint33)
(communicated_soil_data waypoint29)
(communicated_soil_data waypoint10)
(communicated_soil_data waypoint4)
(communicated_soil_data waypoint59)
(communicated_soil_data waypoint60)
(communicated_soil_data waypoint28)
(communicated_soil_data waypoint99)
(communicated_soil_data waypoint97)
(communicated_rock_data waypoint75)
(communicated_rock_data waypoint97)
(communicated_rock_data waypoint17)
(communicated_rock_data waypoint58)
(communicated_rock_data waypoint54)
(communicated_rock_data waypoint70)
(communicated_rock_data waypoint92)
(communicated_rock_data waypoint79)
(communicated_rock_data waypoint8)
(communicated_rock_data waypoint56)
(communicated_rock_data waypoint87)
(communicated_rock_data waypoint80)
(communicated_rock_data waypoint84)
(communicated_rock_data waypoint25)
(communicated_rock_data waypoint16)
(communicated_rock_data waypoint63)
(communicated_rock_data waypoint68)
(communicated_rock_data waypoint47)
(communicated_rock_data waypoint64)
(communicated_rock_data waypoint23)
(communicated_rock_data waypoint82)
(communicated_rock_data waypoint61)
(communicated_rock_data waypoint24)
(communicated_rock_data waypoint19)
(communicated_rock_data waypoint94)
(communicated_rock_data waypoint22)
(communicated_rock_data waypoint51)
(communicated_rock_data waypoint66)
(communicated_rock_data waypoint5)
(communicated_rock_data waypoint39)
(communicated_rock_data waypoint86)
(communicated_rock_data waypoint26)
(communicated_rock_data waypoint7)
(communicated_rock_data waypoint69)
(communicated_rock_data waypoint91)
(communicated_rock_data waypoint89)
(communicated_rock_data waypoint98)
(communicated_image_data objective10 colour)
(communicated_image_data objective5 low_res)
(communicated_image_data objective7 colour)
(communicated_image_data objective9 high_res)
(communicated_image_data objective8 low_res)
(communicated_image_data objective7 low_res)
(communicated_image_data objective3 colour)
(communicated_image_data objective10 high_res)
(communicated_image_data objective6 colour)
(communicated_image_data objective2 colour)
(communicated_image_data objective4 low_res)
(communicated_image_data objective9 low_res)
(communicated_image_data objective9 colour)
(communicated_image_data objective10 low_res)
(communicated_image_data objective4 high_res)
(communicated_image_data objective4 colour)
(communicated_image_data objective7 high_res)
(communicated_image_data objective0 low_res)
(communicated_image_data objective6 low_res)
(communicated_image_data objective8 high_res)
(communicated_image_data objective8 colour)
	)
)
)
