; Problem taken from https://github.com/AI-Planning/classical-domains

(define (problem roverprob5621) (:domain Rover)
(:objects
	general - Lander
	colour high_res low_res - Mode
	rover0 rover1 rover2 rover3 rover4 rover5 rover6 rover7 rover8 rover9 - Rover
	rover0store rover1store rover2store rover3store rover4store rover5store rover6store rover7store rover8store rover9store - Store
	waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 waypoint11 waypoint12 waypoint13 waypoint14 waypoint15 waypoint16 waypoint17 waypoint18 waypoint19 waypoint20 waypoint21 waypoint22 waypoint23 waypoint24 waypoint25 waypoint26 waypoint27 waypoint28 waypoint29 waypoint30 waypoint31 waypoint32 waypoint33 waypoint34 waypoint35 waypoint36 waypoint37 waypoint38 waypoint39 waypoint40 waypoint41 waypoint42 waypoint43 waypoint44 waypoint45 waypoint46 waypoint47 waypoint48 waypoint49 - Waypoint
	camera0 camera1 camera2 camera3 camera4 camera5 camera6 camera7 camera8 camera9 camera10 camera11 camera12 camera13 - Camera
	objective0 objective1 objective2 objective3 objective4 objective5 objective6 objective7 - Objective
	)
(:init
	(at_soil_sample waypoint0)
	(at_rock_sample waypoint0)
	(at_soil_sample waypoint1)
	(at_rock_sample waypoint1)
	(at_rock_sample waypoint2)
	(at_soil_sample waypoint3)
	(at_soil_sample waypoint4)
	(at_rock_sample waypoint7)
	(at_soil_sample waypoint8)
	(at_soil_sample waypoint10)
	(at_soil_sample waypoint11)
	(at_rock_sample waypoint11)
	(at_rock_sample waypoint13)
	(at_rock_sample waypoint14)
	(at_rock_sample waypoint15)
	(at_soil_sample waypoint16)
	(at_soil_sample waypoint18)
	(at_soil_sample waypoint22)
	(at_rock_sample waypoint23)
	(at_soil_sample waypoint24)
	(at_soil_sample waypoint25)
	(at_soil_sample waypoint26)
	(at_soil_sample waypoint31)
	(at_rock_sample waypoint31)
	(at_soil_sample waypoint32)
	(at_rock_sample waypoint32)
	(at_soil_sample waypoint33)
	(at_rock_sample waypoint33)
	(at_soil_sample waypoint34)
	(at_rock_sample waypoint34)
	(at_soil_sample waypoint35)
	(at_rock_sample waypoint35)
	(at_rock_sample waypoint36)
	(at_soil_sample waypoint37)
	(at_rock_sample waypoint37)
	(at_soil_sample waypoint38)
	(at_rock_sample waypoint38)
	(at_soil_sample waypoint39)
	(at_soil_sample waypoint41)
	(at_rock_sample waypoint42)
	(at_rock_sample waypoint43)
	(at_rock_sample waypoint44)
	(at_soil_sample waypoint45)
	(at_soil_sample waypoint46)
	(at_soil_sample waypoint47)
	(at_soil_sample waypoint48)
	(at_rock_sample waypoint48)
	(at_soil_sample waypoint49)
	(at_lander general waypoint36)
	(channel_free general)
	(at rover0 waypoint0)
	(store_of rover0store rover0)
	(empty rover0store)
	(equipped_for_rock_analysis rover0)
	(equipped_for_imaging rover0)
	(at rover1 waypoint46)
	(store_of rover1store rover1)
	(empty rover1store)
	(equipped_for_soil_analysis rover1)
	(equipped_for_rock_analysis rover1)
	(equipped_for_imaging rover1)
	(at rover2 waypoint11)
	(store_of rover2store rover2)
	(empty rover2store)
	(equipped_for_soil_analysis rover2)
	(equipped_for_rock_analysis rover2)
	(equipped_for_imaging rover2)
	(at rover3 waypoint47)
	(store_of rover3store rover3)
	(empty rover3store)
	(equipped_for_rock_analysis rover3)
	(equipped_for_imaging rover3)
	(at rover4 waypoint26)
	(store_of rover4store rover4)
	(empty rover4store)
	(equipped_for_rock_analysis rover4)
	(equipped_for_imaging rover4)
	(at rover5 waypoint37)
	(store_of rover5store rover5)
	(empty rover5store)
	(equipped_for_soil_analysis rover5)
	(equipped_for_rock_analysis rover5)
	(equipped_for_imaging rover5)
	(at rover6 waypoint14)
	(store_of rover6store rover6)
	(empty rover6store)
	(equipped_for_soil_analysis rover6)
	(equipped_for_rock_analysis rover6)
	(equipped_for_imaging rover6)
	(at rover7 waypoint34)
	(store_of rover7store rover7)
	(empty rover7store)
	(equipped_for_soil_analysis rover7)
	(equipped_for_imaging rover7)
	(at rover8 waypoint13)
	(store_of rover8store rover8)
	(empty rover8store)
	(equipped_for_soil_analysis rover8)
	(equipped_for_imaging rover8)
	(at rover9 waypoint17)
	(store_of rover9store rover9)
	(empty rover9store)
	(equipped_for_rock_analysis rover9)
	(equipped_for_imaging rover9)
	(on_board camera0 rover0)
	(calibration_target camera0 objective3)
	(supports camera0 colour)
	(supports camera0 high_res)
	(on_board camera1 rover3)
	(calibration_target camera1 objective7)
	(supports camera1 colour)
	(supports camera1 high_res)
	(on_board camera2 rover5)
	(calibration_target camera2 objective3)
	(supports camera2 high_res)
	(on_board camera3 rover6)
	(calibration_target camera3 objective6)
	(supports camera3 colour)
	(supports camera3 high_res)
	(supports camera3 low_res)
	(on_board camera4 rover5)
	(calibration_target camera4 objective1)
	(supports camera4 high_res)
	(on_board camera5 rover6)
	(calibration_target camera5 objective4)
	(supports camera5 low_res)
	(on_board camera6 rover1)
	(calibration_target camera6 objective3)
	(supports camera6 colour)
	(supports camera6 low_res)
	(on_board camera7 rover1)
	(calibration_target camera7 objective0)
	(supports camera7 low_res)
	(on_board camera8 rover4)
	(calibration_target camera8 objective1)
	(supports camera8 colour)
	(supports camera8 high_res)
	(supports camera8 low_res)
	(on_board camera9 rover5)
	(calibration_target camera9 objective5)
	(supports camera9 colour)
	(supports camera9 high_res)
	(supports camera9 low_res)
	(on_board camera10 rover9)
	(calibration_target camera10 objective1)
	(supports camera10 high_res)
	(supports camera10 low_res)
	(on_board camera11 rover8)
	(calibration_target camera11 objective7)
	(supports camera11 low_res)
	(on_board camera12 rover2)
	(calibration_target camera12 objective5)
	(supports camera12 colour)
	(supports camera12 low_res)
	(on_board camera13 rover7)
	(calibration_target camera13 objective0)
	(supports camera13 colour)
	(supports camera13 low_res)
)

(:goal (and
(communicated_soil_data waypoint16)
(communicated_soil_data waypoint11)
(communicated_soil_data waypoint24)
(communicated_soil_data waypoint46)
(communicated_soil_data waypoint1)
(communicated_soil_data waypoint39)
(communicated_soil_data waypoint10)
(communicated_soil_data waypoint31)
(communicated_soil_data waypoint45)
(communicated_soil_data waypoint18)
(communicated_soil_data waypoint49)
(communicated_soil_data waypoint41)
(communicated_soil_data waypoint25)
(communicated_rock_data waypoint48)
(communicated_rock_data waypoint1)
(communicated_rock_data waypoint2)
(communicated_rock_data waypoint13)
(communicated_rock_data waypoint15)
(communicated_rock_data waypoint43)
(communicated_image_data objective1 high_res)
(communicated_image_data objective6 high_res)
(communicated_image_data objective7 colour)
(communicated_image_data objective5 high_res)
(communicated_image_data objective1 colour)
(communicated_image_data objective1 low_res)
	)
)
)
