; Problem taken from https://github.com/AI-Planning/classical-domains

(define (problem roverprob5142) (:domain Rover)
(:objects
	general - Lander
	colour high_res low_res - Mode
	rover0 rover1 rover2 rover3 - Rover
	rover0store rover1store rover2store rover3store - Store
	waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 waypoint11 - Waypoint
	camera0 camera1 camera2 camera3 - Camera
	objective0 objective1 objective2 objective3 objective4 - Objective
	)
(:init
	(at_soil_sample waypoint0)
	(at_soil_sample waypoint1)
	(at_rock_sample waypoint1)
	(at_rock_sample waypoint2)
	(at_rock_sample waypoint3)
	(at_soil_sample waypoint4)
	(at_soil_sample waypoint5)
	(at_rock_sample waypoint5)
	(at_soil_sample waypoint7)
	(at_soil_sample waypoint8)
	(at_rock_sample waypoint8)
	(at_soil_sample waypoint9)
	(at_rock_sample waypoint9)
	(at_rock_sample waypoint10)
	(at_soil_sample waypoint11)
	(at_rock_sample waypoint11)
	(at_lander general waypoint6)
	(channel_free general)
	(at rover0 waypoint6)
	(store_of rover0store rover0)
	(empty rover0store)
	(equipped_for_soil_analysis rover0)
	(equipped_for_rock_analysis rover0)
	(equipped_for_imaging rover0)
	(at rover1 waypoint2)
	(store_of rover1store rover1)
	(empty rover1store)
	(equipped_for_soil_analysis rover1)
	(equipped_for_rock_analysis rover1)
	(at rover2 waypoint9)
	(store_of rover2store rover2)
	(empty rover2store)
	(equipped_for_rock_analysis rover2)
	(equipped_for_imaging rover2)
	(at rover3 waypoint0)
	(store_of rover3store rover3)
	(empty rover3store)
	(equipped_for_rock_analysis rover3)
	(on_board camera0 rover2)
	(calibration_target camera0 objective3)
	(supports camera0 low_res)
	(on_board camera1 rover2)
	(calibration_target camera1 objective4)
	(supports camera1 colour)
	(on_board camera2 rover0)
	(calibration_target camera2 objective2)
	(supports camera2 high_res)
	(on_board camera3 rover2)
	(calibration_target camera3 objective3)
	(supports camera3 colour)
	(supports camera3 high_res)
	(supports camera3 low_res)
)

(:goal (and
(communicated_soil_data waypoint4)
(communicated_soil_data waypoint9)
(communicated_soil_data waypoint1)
(communicated_soil_data waypoint7)
(communicated_rock_data waypoint3)
(communicated_rock_data waypoint10)
(communicated_rock_data waypoint5)
(communicated_rock_data waypoint1)
(communicated_image_data objective0 high_res)
(communicated_image_data objective4 high_res)
(communicated_image_data objective2 high_res)
	)
)
)
