; Problem taken from https://github.com/AI-Planning/classical-domains

(define (problem roverprob7182) (:domain Rover)
(:objects
	general - Lander
	colour high_res low_res - Mode
	rover0 rover1 rover2 rover3 rover4 rover5 rover6 rover7 rover8 rover9 - Rover
	rover0store rover1store rover2store rover3store rover4store rover5store rover6store rover7store rover8store rover9store - Store
	waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 waypoint11 waypoint12 waypoint13 waypoint14 waypoint15 waypoint16 waypoint17 waypoint18 waypoint19 waypoint20 waypoint21 waypoint22 waypoint23 waypoint24 waypoint25 waypoint26 waypoint27 waypoint28 waypoint29 waypoint30 waypoint31 waypoint32 waypoint33 waypoint34 waypoint35 waypoint36 waypoint37 waypoint38 waypoint39 - Waypoint
	camera0 camera1 camera2 camera3 camera4 camera5 camera6 camera7 camera8 camera9 camera10 camera11 camera12 camera13 - Camera
	objective0 objective1 objective2 objective3 objective4 objective5 objective6 objective7 - Objective
	)
(:init
	(at_soil_sample waypoint0)
	(at_rock_sample waypoint0)
	(at_soil_sample waypoint1)
	(at_rock_sample waypoint1)
	(at_soil_sample waypoint2)
	(at_soil_sample waypoint3)
	(at_rock_sample waypoint4)
	(at_rock_sample waypoint5)
	(at_soil_sample waypoint6)
	(at_soil_sample waypoint10)
	(at_soil_sample waypoint12)
	(at_rock_sample waypoint12)
	(at_soil_sample waypoint15)
	(at_rock_sample waypoint15)
	(at_soil_sample waypoint17)
	(at_rock_sample waypoint17)
	(at_rock_sample waypoint18)
	(at_soil_sample waypoint20)
	(at_rock_sample waypoint20)
	(at_soil_sample waypoint24)
	(at_rock_sample waypoint24)
	(at_soil_sample waypoint25)
	(at_rock_sample waypoint27)
	(at_soil_sample waypoint28)
	(at_rock_sample waypoint29)
	(at_soil_sample waypoint32)
	(at_soil_sample waypoint33)
	(at_rock_sample waypoint33)
	(at_soil_sample waypoint34)
	(at_soil_sample waypoint35)
	(at_rock_sample waypoint35)
	(at_soil_sample waypoint36)
	(at_soil_sample waypoint37)
	(at_rock_sample waypoint37)
	(at_rock_sample waypoint39)
	(at_lander general waypoint29)
	(channel_free general)
	(at rover0 waypoint20)
	(store_of rover0store rover0)
	(empty rover0store)
	(equipped_for_soil_analysis rover0)
	(equipped_for_imaging rover0)
	(at rover1 waypoint5)
	(store_of rover1store rover1)
	(empty rover1store)
	(equipped_for_soil_analysis rover1)
	(equipped_for_imaging rover1)
	(at rover2 waypoint16)
	(store_of rover2store rover2)
	(empty rover2store)
	(equipped_for_rock_analysis rover2)
	(at rover3 waypoint20)
	(store_of rover3store rover3)
	(empty rover3store)
	(equipped_for_soil_analysis rover3)
	(equipped_for_rock_analysis rover3)
	(equipped_for_imaging rover3)
	(at rover4 waypoint11)
	(store_of rover4store rover4)
	(empty rover4store)
	(equipped_for_soil_analysis rover4)
	(equipped_for_imaging rover4)
	(at rover5 waypoint35)
	(store_of rover5store rover5)
	(empty rover5store)
	(equipped_for_imaging rover5)
	(at rover6 waypoint8)
	(store_of rover6store rover6)
	(empty rover6store)
	(equipped_for_rock_analysis rover6)
	(equipped_for_imaging rover6)
	(at rover7 waypoint2)
	(store_of rover7store rover7)
	(empty rover7store)
	(equipped_for_soil_analysis rover7)
	(equipped_for_imaging rover7)
	(at rover8 waypoint28)
	(store_of rover8store rover8)
	(empty rover8store)
	(equipped_for_soil_analysis rover8)
	(equipped_for_imaging rover8)
	(at rover9 waypoint14)
	(store_of rover9store rover9)
	(empty rover9store)
	(equipped_for_soil_analysis rover9)
	(equipped_for_rock_analysis rover9)
	(equipped_for_imaging rover9)
	(on_board camera0 rover6)
	(calibration_target camera0 objective0)
	(supports camera0 colour)
	(on_board camera1 rover1)
	(calibration_target camera1 objective5)
	(supports camera1 colour)
	(supports camera1 high_res)
	(supports camera1 low_res)
	(on_board camera2 rover6)
	(calibration_target camera2 objective4)
	(supports camera2 low_res)
	(on_board camera3 rover4)
	(calibration_target camera3 objective1)
	(supports camera3 colour)
	(supports camera3 high_res)
	(supports camera3 low_res)
	(on_board camera4 rover6)
	(calibration_target camera4 objective4)
	(supports camera4 colour)
	(supports camera4 high_res)
	(on_board camera5 rover9)
	(calibration_target camera5 objective6)
	(supports camera5 colour)
	(supports camera5 high_res)
	(on_board camera6 rover8)
	(calibration_target camera6 objective3)
	(supports camera6 colour)
	(supports camera6 high_res)
	(supports camera6 low_res)
	(on_board camera7 rover6)
	(calibration_target camera7 objective7)
	(supports camera7 high_res)
	(supports camera7 low_res)
	(on_board camera8 rover9)
	(calibration_target camera8 objective2)
	(supports camera8 colour)
	(supports camera8 high_res)
	(on_board camera9 rover9)
	(calibration_target camera9 objective3)
	(supports camera9 low_res)
	(on_board camera10 rover0)
	(calibration_target camera10 objective1)
	(supports camera10 high_res)
	(supports camera10 low_res)
	(on_board camera11 rover7)
	(calibration_target camera11 objective0)
	(supports camera11 colour)
	(supports camera11 low_res)
	(on_board camera12 rover3)
	(calibration_target camera12 objective1)
	(supports camera12 colour)
	(supports camera12 low_res)
	(on_board camera13 rover5)
	(calibration_target camera13 objective0)
	(supports camera13 colour)
	(supports camera13 high_res)
)

(:goal (and
(communicated_soil_data waypoint10)
(communicated_soil_data waypoint28)
(communicated_soil_data waypoint2)
(communicated_soil_data waypoint24)
(communicated_soil_data waypoint15)
(communicated_soil_data waypoint17)
(communicated_soil_data waypoint3)
(communicated_soil_data waypoint0)
(communicated_rock_data waypoint4)
(communicated_rock_data waypoint17)
(communicated_rock_data waypoint33)
(communicated_rock_data waypoint24)
(communicated_rock_data waypoint27)
(communicated_rock_data waypoint18)
(communicated_image_data objective7 high_res)
(communicated_image_data objective5 low_res)
(communicated_image_data objective4 low_res)
(communicated_image_data objective4 high_res)
(communicated_image_data objective2 low_res)
	)
)
)
