; Problem taken from https://github.com/AI-Planning/classical-domains

(define (problem roverprob2006) (:domain Rover)
(:objects
	general - Lander
	colour high_res low_res - Mode
	rover0 rover1 rover2 rover3 rover4 rover5 rover6 rover7 rover8 rover9 rover10 rover11 rover12 rover13 - Rover
	rover0store rover1store rover2store rover3store rover4store rover5store rover6store rover7store rover8store rover9store rover10store rover11store rover12store rover13store - Store
	waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 waypoint11 waypoint12 waypoint13 waypoint14 waypoint15 waypoint16 waypoint17 waypoint18 waypoint19 waypoint20 waypoint21 waypoint22 waypoint23 waypoint24 waypoint25 waypoint26 waypoint27 waypoint28 waypoint29 waypoint30 waypoint31 waypoint32 waypoint33 waypoint34 waypoint35 waypoint36 waypoint37 waypoint38 waypoint39 waypoint40 waypoint41 waypoint42 waypoint43 waypoint44 waypoint45 waypoint46 waypoint47 waypoint48 waypoint49 waypoint50 waypoint51 waypoint52 waypoint53 waypoint54 waypoint55 waypoint56 waypoint57 waypoint58 waypoint59 waypoint60 waypoint61 waypoint62 waypoint63 waypoint64 waypoint65 waypoint66 waypoint67 waypoint68 waypoint69 waypoint70 waypoint71 waypoint72 waypoint73 waypoint74 waypoint75 waypoint76 waypoint77 waypoint78 waypoint79 - Waypoint
	camera0 camera1 camera2 camera3 camera4 camera5 camera6 camera7 camera8 camera9 camera10 camera11 camera12 camera13 camera14 - Camera
	objective0 objective1 objective2 objective3 objective4 objective5 objective6 objective7 objective8 objective9 - Objective
	)
(:init
	(at_soil_sample waypoint1)
	(at_rock_sample waypoint1)
	(at_soil_sample waypoint2)
	(at_soil_sample waypoint3)
	(at_soil_sample waypoint5)
	(at_rock_sample waypoint5)
	(at_soil_sample waypoint9)
	(at_soil_sample waypoint10)
	(at_rock_sample waypoint10)
	(at_soil_sample waypoint11)
	(at_soil_sample waypoint13)
	(at_rock_sample waypoint13)
	(at_soil_sample waypoint14)
	(at_rock_sample waypoint14)
	(at_rock_sample waypoint15)
	(at_soil_sample waypoint16)
	(at_rock_sample waypoint16)
	(at_soil_sample waypoint18)
	(at_rock_sample waypoint18)
	(at_rock_sample waypoint20)
	(at_soil_sample waypoint21)
	(at_rock_sample waypoint21)
	(at_rock_sample waypoint23)
	(at_rock_sample waypoint24)
	(at_rock_sample waypoint26)
	(at_soil_sample waypoint27)
	(at_rock_sample waypoint27)
	(at_rock_sample waypoint28)
	(at_soil_sample waypoint29)
	(at_rock_sample waypoint30)
	(at_soil_sample waypoint31)
	(at_rock_sample waypoint31)
	(at_soil_sample waypoint32)
	(at_rock_sample waypoint32)
	(at_soil_sample waypoint33)
	(at_rock_sample waypoint35)
	(at_soil_sample waypoint37)
	(at_rock_sample waypoint37)
	(at_rock_sample waypoint38)
	(at_rock_sample waypoint39)
	(at_rock_sample waypoint40)
	(at_soil_sample waypoint41)
	(at_rock_sample waypoint41)
	(at_soil_sample waypoint42)
	(at_rock_sample waypoint42)
	(at_soil_sample waypoint43)
	(at_rock_sample waypoint45)
	(at_rock_sample waypoint46)
	(at_rock_sample waypoint47)
	(at_soil_sample waypoint48)
	(at_rock_sample waypoint48)
	(at_rock_sample waypoint49)
	(at_soil_sample waypoint50)
	(at_rock_sample waypoint51)
	(at_soil_sample waypoint54)
	(at_rock_sample waypoint54)
	(at_soil_sample waypoint55)
	(at_rock_sample waypoint55)
	(at_rock_sample waypoint57)
	(at_soil_sample waypoint59)
	(at_soil_sample waypoint60)
	(at_rock_sample waypoint61)
	(at_soil_sample waypoint63)
	(at_soil_sample waypoint64)
	(at_rock_sample waypoint64)
	(at_soil_sample waypoint65)
	(at_soil_sample waypoint66)
	(at_rock_sample waypoint66)
	(at_soil_sample waypoint67)
	(at_rock_sample waypoint69)
	(at_rock_sample waypoint70)
	(at_soil_sample waypoint71)
	(at_rock_sample waypoint71)
	(at_soil_sample waypoint73)
	(at_soil_sample waypoint74)
	(at_rock_sample waypoint74)
	(at_rock_sample waypoint75)
	(at_soil_sample waypoint76)
	(at_rock_sample waypoint76)
	(at_soil_sample waypoint77)
	(at_rock_sample waypoint78)
	(at_soil_sample waypoint79)
	(at_lander general waypoint66)
	(channel_free general)
	(at rover0 waypoint38)
	(store_of rover0store rover0)
	(empty rover0store)
	(equipped_for_rock_analysis rover0)
	(equipped_for_imaging rover0)
	(at rover1 waypoint6)
	(store_of rover1store rover1)
	(empty rover1store)
	(equipped_for_soil_analysis rover1)
	(at rover2 waypoint22)
	(store_of rover2store rover2)
	(empty rover2store)
	(equipped_for_rock_analysis rover2)
	(equipped_for_imaging rover2)
	(at rover3 waypoint8)
	(store_of rover3store rover3)
	(empty rover3store)
	(equipped_for_rock_analysis rover3)
	(equipped_for_imaging rover3)
	(at rover4 waypoint30)
	(store_of rover4store rover4)
	(empty rover4store)
	(equipped_for_imaging rover4)
	(at rover5 waypoint23)
	(store_of rover5store rover5)
	(empty rover5store)
	(equipped_for_imaging rover5)
	(at rover6 waypoint44)
	(store_of rover6store rover6)
	(empty rover6store)
	(equipped_for_imaging rover6)
	(at rover7 waypoint62)
	(store_of rover7store rover7)
	(empty rover7store)
	(equipped_for_soil_analysis rover7)
	(equipped_for_rock_analysis rover7)
	(equipped_for_imaging rover7)
	(at rover8 waypoint42)
	(store_of rover8store rover8)
	(empty rover8store)
	(equipped_for_soil_analysis rover8)
	(at rover9 waypoint1)
	(store_of rover9store rover9)
	(empty rover9store)
	(equipped_for_soil_analysis rover9)
	(equipped_for_imaging rover9)
	(at rover10 waypoint56)
	(store_of rover10store rover10)
	(empty rover10store)
	(equipped_for_soil_analysis rover10)
	(equipped_for_imaging rover10)
	(at rover11 waypoint6)
	(store_of rover11store rover11)
	(empty rover11store)
	(equipped_for_rock_analysis rover11)
	(equipped_for_imaging rover11)
	(at rover12 waypoint31)
	(store_of rover12store rover12)
	(empty rover12store)
	(equipped_for_rock_analysis rover12)
	(equipped_for_imaging rover12)
	(at rover13 waypoint30)
	(store_of rover13store rover13)
	(empty rover13store)
	(equipped_for_rock_analysis rover13)
	(equipped_for_imaging rover13)
	(on_board camera0 rover13)
	(calibration_target camera0 objective3)
	(supports camera0 low_res)
	(on_board camera1 rover2)
	(calibration_target camera1 objective9)
	(supports camera1 high_res)
	(supports camera1 low_res)
	(on_board camera2 rover9)
	(calibration_target camera2 objective5)
	(supports camera2 low_res)
	(on_board camera3 rover0)
	(calibration_target camera3 objective0)
	(supports camera3 colour)
	(supports camera3 high_res)
	(supports camera3 low_res)
	(on_board camera4 rover12)
	(calibration_target camera4 objective2)
	(supports camera4 colour)
	(supports camera4 high_res)
	(supports camera4 low_res)
	(on_board camera5 rover0)
	(calibration_target camera5 objective6)
	(supports camera5 colour)
	(supports camera5 high_res)
	(supports camera5 low_res)
	(on_board camera6 rover7)
	(calibration_target camera6 objective0)
	(supports camera6 colour)
	(supports camera6 low_res)
	(on_board camera7 rover3)
	(calibration_target camera7 objective0)
	(supports camera7 colour)
	(supports camera7 high_res)
	(on_board camera8 rover9)
	(calibration_target camera8 objective6)
	(supports camera8 low_res)
	(on_board camera9 rover5)
	(calibration_target camera9 objective2)
	(supports camera9 high_res)
	(on_board camera10 rover11)
	(calibration_target camera10 objective6)
	(supports camera10 colour)
	(supports camera10 high_res)
	(on_board camera11 rover11)
	(calibration_target camera11 objective1)
	(supports camera11 colour)
	(on_board camera12 rover4)
	(calibration_target camera12 objective4)
	(supports camera12 colour)
	(supports camera12 low_res)
	(on_board camera13 rover6)
	(calibration_target camera13 objective5)
	(supports camera13 colour)
	(on_board camera14 rover10)
	(calibration_target camera14 objective4)
	(supports camera14 colour)
	(supports camera14 high_res)
)

(:goal (and
(communicated_soil_data waypoint67)
(communicated_soil_data waypoint2)
(communicated_soil_data waypoint42)
(communicated_soil_data waypoint66)
(communicated_soil_data waypoint16)
(communicated_soil_data waypoint79)
(communicated_soil_data waypoint31)
(communicated_soil_data waypoint29)
(communicated_soil_data waypoint55)
(communicated_soil_data waypoint1)
(communicated_soil_data waypoint33)
(communicated_soil_data waypoint32)
(communicated_soil_data waypoint77)
(communicated_soil_data waypoint54)
(communicated_soil_data waypoint48)
(communicated_soil_data waypoint13)
(communicated_soil_data waypoint74)
(communicated_soil_data waypoint5)
(communicated_rock_data waypoint40)
(communicated_rock_data waypoint70)
(communicated_rock_data waypoint45)
(communicated_rock_data waypoint32)
(communicated_rock_data waypoint39)
(communicated_rock_data waypoint76)
(communicated_rock_data waypoint46)
(communicated_rock_data waypoint78)
(communicated_rock_data waypoint55)
(communicated_rock_data waypoint54)
(communicated_image_data objective1 high_res)
(communicated_image_data objective1 colour)
(communicated_image_data objective3 high_res)
(communicated_image_data objective5 high_res)
(communicated_image_data objective3 low_res)
(communicated_image_data objective9 low_res)
(communicated_image_data objective5 low_res)
(communicated_image_data objective6 high_res)
(communicated_image_data objective7 colour)
(communicated_image_data objective7 low_res)
(communicated_image_data objective6 colour)
(communicated_image_data objective1 low_res)
(communicated_image_data objective9 colour)
	)
)
)
