; Problem taken from https://github.com/AI-Planning/classical-domains

(define (problem roverprob2006) (:domain Rover)
(:objects
	general - Lander
	colour high_res low_res - Mode
	rover0 rover1 rover2 rover3 rover4 rover5 rover6 rover7 rover8 rover9 rover10 rover11 rover12 rover13 - Rover
	rover0store rover1store rover2store rover3store rover4store rover5store rover6store rover7store rover8store rover9store rover10store rover11store rover12store rover13store - Store
	waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 waypoint11 waypoint12 waypoint13 waypoint14 waypoint15 waypoint16 waypoint17 waypoint18 waypoint19 waypoint20 waypoint21 waypoint22 waypoint23 waypoint24 waypoint25 waypoint26 waypoint27 waypoint28 waypoint29 waypoint30 waypoint31 waypoint32 waypoint33 waypoint34 waypoint35 waypoint36 waypoint37 waypoint38 waypoint39 waypoint40 waypoint41 waypoint42 waypoint43 waypoint44 waypoint45 waypoint46 waypoint47 waypoint48 waypoint49 waypoint50 waypoint51 waypoint52 waypoint53 waypoint54 waypoint55 waypoint56 waypoint57 waypoint58 waypoint59 waypoint60 waypoint61 waypoint62 waypoint63 waypoint64 waypoint65 waypoint66 waypoint67 waypoint68 waypoint69 waypoint70 waypoint71 waypoint72 waypoint73 waypoint74 waypoint75 waypoint76 waypoint77 waypoint78 waypoint79 waypoint80 waypoint81 waypoint82 waypoint83 waypoint84 - Waypoint
	camera0 camera1 camera2 camera3 camera4 camera5 camera6 camera7 camera8 camera9 camera10 camera11 camera12 camera13 camera14 camera15 camera16 camera17 - Camera
	objective0 objective1 objective2 objective3 objective4 objective5 objective6 objective7 objective8 objective9 objective10 objective11 objective12 - Objective
	)
(:init
	(at_soil_sample waypoint0)
	(at_rock_sample waypoint3)
	(at_rock_sample waypoint4)
	(at_soil_sample waypoint5)
	(at_soil_sample waypoint6)
	(at_soil_sample waypoint7)
	(at_rock_sample waypoint7)
	(at_rock_sample waypoint8)
	(at_soil_sample waypoint9)
	(at_soil_sample waypoint10)
	(at_soil_sample waypoint11)
	(at_rock_sample waypoint11)
	(at_soil_sample waypoint12)
	(at_rock_sample waypoint13)
	(at_soil_sample waypoint14)
	(at_rock_sample waypoint14)
	(at_rock_sample waypoint16)
	(at_rock_sample waypoint17)
	(at_soil_sample waypoint18)
	(at_rock_sample waypoint20)
	(at_soil_sample waypoint22)
	(at_rock_sample waypoint22)
	(at_soil_sample waypoint23)
	(at_rock_sample waypoint23)
	(at_rock_sample waypoint24)
	(at_soil_sample waypoint25)
	(at_soil_sample waypoint29)
	(at_soil_sample waypoint30)
	(at_rock_sample waypoint31)
	(at_rock_sample waypoint32)
	(at_soil_sample waypoint34)
	(at_soil_sample waypoint35)
	(at_rock_sample waypoint35)
	(at_soil_sample waypoint36)
	(at_rock_sample waypoint37)
	(at_soil_sample waypoint39)
	(at_soil_sample waypoint41)
	(at_rock_sample waypoint42)
	(at_soil_sample waypoint43)
	(at_soil_sample waypoint44)
	(at_soil_sample waypoint45)
	(at_rock_sample waypoint48)
	(at_soil_sample waypoint49)
	(at_rock_sample waypoint49)
	(at_rock_sample waypoint50)
	(at_soil_sample waypoint51)
	(at_rock_sample waypoint51)
	(at_soil_sample waypoint52)
	(at_rock_sample waypoint52)
	(at_rock_sample waypoint53)
	(at_rock_sample waypoint54)
	(at_soil_sample waypoint55)
	(at_rock_sample waypoint55)
	(at_soil_sample waypoint56)
	(at_soil_sample waypoint57)
	(at_rock_sample waypoint57)
	(at_rock_sample waypoint58)
	(at_soil_sample waypoint59)
	(at_rock_sample waypoint59)
	(at_soil_sample waypoint60)
	(at_soil_sample waypoint61)
	(at_rock_sample waypoint65)
	(at_rock_sample waypoint66)
	(at_soil_sample waypoint67)
	(at_rock_sample waypoint67)
	(at_soil_sample waypoint69)
	(at_rock_sample waypoint69)
	(at_rock_sample waypoint70)
	(at_soil_sample waypoint71)
	(at_rock_sample waypoint71)
	(at_soil_sample waypoint72)
	(at_soil_sample waypoint74)
	(at_soil_sample waypoint76)
	(at_rock_sample waypoint77)
	(at_soil_sample waypoint78)
	(at_rock_sample waypoint78)
	(at_soil_sample waypoint79)
	(at_rock_sample waypoint79)
	(at_rock_sample waypoint80)
	(at_soil_sample waypoint81)
	(at_rock_sample waypoint81)
	(at_rock_sample waypoint82)
	(at_rock_sample waypoint83)
	(at_soil_sample waypoint84)
	(at_rock_sample waypoint84)
	(at_lander general waypoint84)
	(channel_free general)
	(at rover0 waypoint13)
	(store_of rover0store rover0)
	(empty rover0store)
	(equipped_for_soil_analysis rover0)
	(equipped_for_rock_analysis rover0)
	(equipped_for_imaging rover0)
	(at rover1 waypoint48)
	(store_of rover1store rover1)
	(empty rover1store)
	(equipped_for_soil_analysis rover1)
	(equipped_for_imaging rover1)
	(at rover2 waypoint22)
	(store_of rover2store rover2)
	(empty rover2store)
	(equipped_for_imaging rover2)
	(at rover3 waypoint49)
	(store_of rover3store rover3)
	(empty rover3store)
	(equipped_for_imaging rover3)
	(at rover4 waypoint72)
	(store_of rover4store rover4)
	(empty rover4store)
	(equipped_for_soil_analysis rover4)
	(equipped_for_imaging rover4)
	(at rover5 waypoint30)
	(store_of rover5store rover5)
	(empty rover5store)
	(equipped_for_soil_analysis rover5)
	(equipped_for_imaging rover5)
	(at rover6 waypoint11)
	(store_of rover6store rover6)
	(empty rover6store)
	(equipped_for_imaging rover6)
	(at rover7 waypoint29)
	(store_of rover7store rover7)
	(empty rover7store)
	(equipped_for_soil_analysis rover7)
	(equipped_for_imaging rover7)
	(at rover8 waypoint83)
	(store_of rover8store rover8)
	(empty rover8store)
	(equipped_for_soil_analysis rover8)
	(equipped_for_rock_analysis rover8)
	(equipped_for_imaging rover8)
	(at rover9 waypoint53)
	(store_of rover9store rover9)
	(empty rover9store)
	(equipped_for_imaging rover9)
	(at rover10 waypoint75)
	(store_of rover10store rover10)
	(empty rover10store)
	(equipped_for_soil_analysis rover10)
	(equipped_for_rock_analysis rover10)
	(equipped_for_imaging rover10)
	(at rover11 waypoint28)
	(store_of rover11store rover11)
	(empty rover11store)
	(equipped_for_rock_analysis rover11)
	(equipped_for_imaging rover11)
	(at rover12 waypoint77)
	(store_of rover12store rover12)
	(empty rover12store)
	(equipped_for_soil_analysis rover12)
	(equipped_for_rock_analysis rover12)
	(equipped_for_imaging rover12)
	(at rover13 waypoint5)
	(store_of rover13store rover13)
	(empty rover13store)
	(equipped_for_rock_analysis rover13)
	(equipped_for_imaging rover13)
	(on_board camera0 rover3)
	(calibration_target camera0 objective2)
	(supports camera0 colour)
	(supports camera0 high_res)
	(on_board camera1 rover1)
	(calibration_target camera1 objective10)
	(supports camera1 colour)
	(supports camera1 low_res)
	(on_board camera2 rover7)
	(calibration_target camera2 objective0)
	(supports camera2 low_res)
	(on_board camera3 rover12)
	(calibration_target camera3 objective11)
	(supports camera3 colour)
	(supports camera3 high_res)
	(on_board camera4 rover7)
	(calibration_target camera4 objective6)
	(supports camera4 colour)
	(on_board camera5 rover0)
	(calibration_target camera5 objective1)
	(supports camera5 colour)
	(supports camera5 high_res)
	(on_board camera6 rover5)
	(calibration_target camera6 objective11)
	(supports camera6 colour)
	(supports camera6 high_res)
	(supports camera6 low_res)
	(on_board camera7 rover0)
	(calibration_target camera7 objective1)
	(supports camera7 low_res)
	(on_board camera8 rover11)
	(calibration_target camera8 objective1)
	(supports camera8 high_res)
	(supports camera8 low_res)
	(on_board camera9 rover0)
	(calibration_target camera9 objective8)
	(supports camera9 colour)
	(supports camera9 high_res)
	(on_board camera10 rover4)
	(calibration_target camera10 objective8)
	(supports camera10 colour)
	(on_board camera11 rover1)
	(calibration_target camera11 objective4)
	(supports camera11 colour)
	(on_board camera12 rover2)
	(calibration_target camera12 objective8)
	(supports camera12 high_res)
	(supports camera12 low_res)
	(on_board camera13 rover6)
	(calibration_target camera13 objective6)
	(supports camera13 colour)
	(supports camera13 high_res)
	(supports camera13 low_res)
	(on_board camera14 rover8)
	(calibration_target camera14 objective0)
	(supports camera14 colour)
	(supports camera14 low_res)
	(on_board camera15 rover9)
	(calibration_target camera15 objective9)
	(supports camera15 low_res)
	(on_board camera16 rover10)
	(calibration_target camera16 objective12)
	(supports camera16 colour)
	(supports camera16 high_res)
	(on_board camera17 rover13)
	(calibration_target camera17 objective8)
	(supports camera17 colour)
)

(:goal (and
(communicated_soil_data waypoint81)
(communicated_soil_data waypoint0)
(communicated_soil_data waypoint11)
(communicated_soil_data waypoint22)
(communicated_soil_data waypoint44)
(communicated_soil_data waypoint9)
(communicated_soil_data waypoint10)
(communicated_soil_data waypoint67)
(communicated_soil_data waypoint84)
(communicated_soil_data waypoint18)
(communicated_soil_data waypoint61)
(communicated_soil_data waypoint51)
(communicated_soil_data waypoint30)
(communicated_soil_data waypoint71)
(communicated_soil_data waypoint35)
(communicated_soil_data waypoint49)
(communicated_soil_data waypoint78)
(communicated_soil_data waypoint57)
(communicated_soil_data waypoint79)
(communicated_soil_data waypoint12)
(communicated_soil_data waypoint45)
(communicated_soil_data waypoint6)
(communicated_soil_data waypoint43)
(communicated_soil_data waypoint41)
(communicated_soil_data waypoint60)
(communicated_rock_data waypoint80)
(communicated_rock_data waypoint50)
(communicated_rock_data waypoint54)
(communicated_rock_data waypoint4)
(communicated_rock_data waypoint59)
(communicated_rock_data waypoint83)
(communicated_rock_data waypoint16)
(communicated_rock_data waypoint65)
(communicated_rock_data waypoint7)
(communicated_rock_data waypoint55)
(communicated_rock_data waypoint11)
(communicated_rock_data waypoint77)
(communicated_rock_data waypoint31)
(communicated_rock_data waypoint51)
(communicated_rock_data waypoint20)
(communicated_rock_data waypoint42)
(communicated_rock_data waypoint81)
(communicated_rock_data waypoint79)
(communicated_rock_data waypoint8)
(communicated_rock_data waypoint13)
(communicated_rock_data waypoint82)
(communicated_image_data objective6 high_res)
(communicated_image_data objective2 high_res)
(communicated_image_data objective10 low_res)
(communicated_image_data objective1 high_res)
(communicated_image_data objective4 low_res)
(communicated_image_data objective10 colour)
(communicated_image_data objective6 low_res)
(communicated_image_data objective1 colour)
(communicated_image_data objective11 low_res)
(communicated_image_data objective9 low_res)
(communicated_image_data objective4 colour)
(communicated_image_data objective12 colour)
	)
)
)
