; Problem taken from https://github.com/AI-Planning/classical-domains

(define (problem roverprob7182) (:domain Rover)
(:objects
	general - Lander
	colour high_res low_res - Mode
	rover0 rover1 rover2 rover3 rover4 rover5 rover6 rover7 rover8 rover9 - Rover
	rover0store rover1store rover2store rover3store rover4store rover5store rover6store rover7store rover8store rover9store - Store
	waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 waypoint11 waypoint12 waypoint13 waypoint14 waypoint15 waypoint16 waypoint17 waypoint18 waypoint19 waypoint20 waypoint21 waypoint22 waypoint23 waypoint24 waypoint25 waypoint26 waypoint27 waypoint28 waypoint29 waypoint30 waypoint31 waypoint32 waypoint33 waypoint34 waypoint35 waypoint36 waypoint37 waypoint38 waypoint39 - Waypoint
	camera0 camera1 camera2 camera3 camera4 camera5 camera6 camera7 camera8 camera9 camera10 camera11 camera12 camera13 - Camera
	objective0 objective1 objective2 objective3 objective4 objective5 objective6 objective7 - Objective
	)
(:init
	(at_soil_sample waypoint0)
	(at_rock_sample waypoint0)
	(at_soil_sample waypoint1)
	(at_rock_sample waypoint1)
	(at_soil_sample waypoint2)
	(at_soil_sample waypoint3)
	(at_rock_sample waypoint4)
	(at_rock_sample waypoint5)
	(at_soil_sample waypoint6)
	(at_soil_sample waypoint10)
	(at_soil_sample waypoint12)
	(at_rock_sample waypoint12)
	(at_soil_sample waypoint15)
	(at_rock_sample waypoint15)
	(at_soil_sample waypoint17)
	(at_rock_sample waypoint17)
	(at_rock_sample waypoint18)
	(at_soil_sample waypoint20)
	(at_rock_sample waypoint20)
	(at_soil_sample waypoint24)
	(at_rock_sample waypoint24)
	(at_soil_sample waypoint25)
	(at_rock_sample waypoint27)
	(at_soil_sample waypoint28)
	(at_rock_sample waypoint29)
	(at_soil_sample waypoint32)
	(at_soil_sample waypoint33)
	(at_rock_sample waypoint33)
	(at_soil_sample waypoint34)
	(at_soil_sample waypoint35)
	(at_rock_sample waypoint35)
	(at_soil_sample waypoint36)
	(at_soil_sample waypoint37)
	(at_rock_sample waypoint37)
	(at_rock_sample waypoint39)
	(at_lander general waypoint29)
	(channel_free general)
	(at rover0 waypoint20)
	(store_of rover0store rover0)
	(empty rover0store)
	(equipped_for_soil_analysis rover0)
	(equipped_for_imaging rover0)
	(at rover1 waypoint5)
	(store_of rover1store rover1)
	(empty rover1store)
	(equipped_for_soil_analysis rover1)
	(equipped_for_imaging rover1)
	(at rover2 waypoint16)
	(store_of rover2store rover2)
	(empty rover2store)
	(equipped_for_rock_analysis rover2)
	(at rover3 waypoint20)
	(store_of rover3store rover3)
	(empty rover3store)
	(equipped_for_soil_analysis rover3)
	(equipped_for_rock_analysis rover3)
	(equipped_for_imaging rover3)
	(at rover4 waypoint11)
	(store_of rover4store rover4)
	(empty rover4store)
	(equipped_for_soil_analysis rover4)
	(equipped_for_imaging rover4)
	(at rover5 waypoint35)
	(store_of rover5store rover5)
	(empty rover5store)
	(equipped_for_imaging rover5)
	(at rover6 waypoint8)
	(store_of rover6store rover6)
	(empty rover6store)
	(equipped_for_rock_analysis rover6)
	(equipped_for_imaging rover6)
	(at rover7 waypoint2)
	(store_of rover7store rover7)
	(empty rover7store)
	(equipped_for_soil_analysis rover7)
	(equipped_for_imaging rover7)
	(at rover8 waypoint28)
	(store_of rover8store rover8)
	(empty rover8store)
	(equipped_for_soil_analysis rover8)
	(equipped_for_imaging rover8)
	(at rover9 waypoint14)
	(store_of rover9store rover9)
	(empty rover9store)
	(equipped_for_soil_analysis rover9)
	(equipped_for_rock_analysis rover9)
	(equipped_for_imaging rover9)
	(on_board camera0 rover6)
	(calibration_target camera0 objective0)
	(supports camera0 colour)
	(on_board camera1 rover1)
	(calibration_target camera1 objective5)
	(supports camera1 colour)
	(supports camera1 high_res)
	(supports camera1 low_res)
	(on_board camera2 rover6)
	(calibration_target camera2 objective4)
	(supports camera2 low_res)
	(on_board camera3 rover4)
	(calibration_target camera3 objective1)
	(supports camera3 colour)
	(supports camera3 high_res)
	(supports camera3 low_res)
	(on_board camera4 rover6)
	(calibration_target camera4 objective4)
	(supports camera4 colour)
	(supports camera4 high_res)
	(on_board camera5 rover9)
	(calibration_target camera5 objective6)
	(supports camera5 colour)
	(supports camera5 high_res)
	(on_board camera6 rover8)
	(calibration_target camera6 objective3)
	(supports camera6 colour)
	(supports camera6 high_res)
	(supports camera6 low_res)
	(on_board camera7 rover6)
	(calibration_target camera7 objective7)
	(supports camera7 high_res)
	(supports camera7 low_res)
	(on_board camera8 rover9)
	(calibration_target camera8 objective2)
	(supports camera8 colour)
	(supports camera8 high_res)
	(on_board camera9 rover9)
	(calibration_target camera9 objective3)
	(supports camera9 low_res)
	(on_board camera10 rover0)
	(calibration_target camera10 objective1)
	(supports camera10 high_res)
	(supports camera10 low_res)
	(on_board camera11 rover7)
	(calibration_target camera11 objective0)
	(supports camera11 colour)
	(supports camera11 low_res)
	(on_board camera12 rover3)
	(calibration_target camera12 objective1)
	(supports camera12 colour)
	(supports camera12 low_res)
	(on_board camera13 rover5)
	(calibration_target camera13 objective0)
	(supports camera13 colour)
	(supports camera13 high_res)

    ; action literals
    (navigate rover0 waypoint0)
    (navigate rover0 waypoint1)
    (navigate rover0 waypoint2)
    (navigate rover0 waypoint3)
    (navigate rover0 waypoint4)
    (navigate rover0 waypoint5)
    (navigate rover0 waypoint6)
    (navigate rover0 waypoint7)
    (navigate rover0 waypoint8)
    (navigate rover0 waypoint9)
    (navigate rover0 waypoint10)
    (navigate rover0 waypoint11)
    (navigate rover0 waypoint12)
    (navigate rover0 waypoint13)
    (navigate rover0 waypoint14)
    (navigate rover0 waypoint15)
    (navigate rover0 waypoint16)
    (navigate rover0 waypoint17)
    (navigate rover0 waypoint18)
    (navigate rover0 waypoint19)
    (navigate rover0 waypoint20)
    (navigate rover0 waypoint21)
    (navigate rover0 waypoint22)
    (navigate rover0 waypoint23)
    (navigate rover0 waypoint24)
    (navigate rover0 waypoint25)
    (navigate rover0 waypoint26)
    (navigate rover0 waypoint27)
    (navigate rover0 waypoint28)
    (navigate rover0 waypoint29)
    (navigate rover0 waypoint30)
    (navigate rover0 waypoint31)
    (navigate rover0 waypoint32)
    (navigate rover0 waypoint33)
    (navigate rover0 waypoint34)
    (navigate rover0 waypoint35)
    (navigate rover0 waypoint36)
    (navigate rover0 waypoint37)
    (navigate rover0 waypoint38)
    (navigate rover0 waypoint39)
    (navigate rover1 waypoint0)
    (navigate rover1 waypoint1)
    (navigate rover1 waypoint2)
    (navigate rover1 waypoint3)
    (navigate rover1 waypoint4)
    (navigate rover1 waypoint5)
    (navigate rover1 waypoint6)
    (navigate rover1 waypoint7)
    (navigate rover1 waypoint8)
    (navigate rover1 waypoint9)
    (navigate rover1 waypoint10)
    (navigate rover1 waypoint11)
    (navigate rover1 waypoint12)
    (navigate rover1 waypoint13)
    (navigate rover1 waypoint14)
    (navigate rover1 waypoint15)
    (navigate rover1 waypoint16)
    (navigate rover1 waypoint17)
    (navigate rover1 waypoint18)
    (navigate rover1 waypoint19)
    (navigate rover1 waypoint20)
    (navigate rover1 waypoint21)
    (navigate rover1 waypoint22)
    (navigate rover1 waypoint23)
    (navigate rover1 waypoint24)
    (navigate rover1 waypoint25)
    (navigate rover1 waypoint26)
    (navigate rover1 waypoint27)
    (navigate rover1 waypoint28)
    (navigate rover1 waypoint29)
    (navigate rover1 waypoint30)
    (navigate rover1 waypoint31)
    (navigate rover1 waypoint32)
    (navigate rover1 waypoint33)
    (navigate rover1 waypoint34)
    (navigate rover1 waypoint35)
    (navigate rover1 waypoint36)
    (navigate rover1 waypoint37)
    (navigate rover1 waypoint38)
    (navigate rover1 waypoint39)
    (navigate rover2 waypoint0)
    (navigate rover2 waypoint1)
    (navigate rover2 waypoint2)
    (navigate rover2 waypoint3)
    (navigate rover2 waypoint4)
    (navigate rover2 waypoint5)
    (navigate rover2 waypoint6)
    (navigate rover2 waypoint7)
    (navigate rover2 waypoint8)
    (navigate rover2 waypoint9)
    (navigate rover2 waypoint10)
    (navigate rover2 waypoint11)
    (navigate rover2 waypoint12)
    (navigate rover2 waypoint13)
    (navigate rover2 waypoint14)
    (navigate rover2 waypoint15)
    (navigate rover2 waypoint16)
    (navigate rover2 waypoint17)
    (navigate rover2 waypoint18)
    (navigate rover2 waypoint19)
    (navigate rover2 waypoint20)
    (navigate rover2 waypoint21)
    (navigate rover2 waypoint22)
    (navigate rover2 waypoint23)
    (navigate rover2 waypoint24)
    (navigate rover2 waypoint25)
    (navigate rover2 waypoint26)
    (navigate rover2 waypoint27)
    (navigate rover2 waypoint28)
    (navigate rover2 waypoint29)
    (navigate rover2 waypoint30)
    (navigate rover2 waypoint31)
    (navigate rover2 waypoint32)
    (navigate rover2 waypoint33)
    (navigate rover2 waypoint34)
    (navigate rover2 waypoint35)
    (navigate rover2 waypoint36)
    (navigate rover2 waypoint37)
    (navigate rover2 waypoint38)
    (navigate rover2 waypoint39)
    (navigate rover3 waypoint0)
    (navigate rover3 waypoint1)
    (navigate rover3 waypoint2)
    (navigate rover3 waypoint3)
    (navigate rover3 waypoint4)
    (navigate rover3 waypoint5)
    (navigate rover3 waypoint6)
    (navigate rover3 waypoint7)
    (navigate rover3 waypoint8)
    (navigate rover3 waypoint9)
    (navigate rover3 waypoint10)
    (navigate rover3 waypoint11)
    (navigate rover3 waypoint12)
    (navigate rover3 waypoint13)
    (navigate rover3 waypoint14)
    (navigate rover3 waypoint15)
    (navigate rover3 waypoint16)
    (navigate rover3 waypoint17)
    (navigate rover3 waypoint18)
    (navigate rover3 waypoint19)
    (navigate rover3 waypoint20)
    (navigate rover3 waypoint21)
    (navigate rover3 waypoint22)
    (navigate rover3 waypoint23)
    (navigate rover3 waypoint24)
    (navigate rover3 waypoint25)
    (navigate rover3 waypoint26)
    (navigate rover3 waypoint27)
    (navigate rover3 waypoint28)
    (navigate rover3 waypoint29)
    (navigate rover3 waypoint30)
    (navigate rover3 waypoint31)
    (navigate rover3 waypoint32)
    (navigate rover3 waypoint33)
    (navigate rover3 waypoint34)
    (navigate rover3 waypoint35)
    (navigate rover3 waypoint36)
    (navigate rover3 waypoint37)
    (navigate rover3 waypoint38)
    (navigate rover3 waypoint39)
    (navigate rover4 waypoint0)
    (navigate rover4 waypoint1)
    (navigate rover4 waypoint2)
    (navigate rover4 waypoint3)
    (navigate rover4 waypoint4)
    (navigate rover4 waypoint5)
    (navigate rover4 waypoint6)
    (navigate rover4 waypoint7)
    (navigate rover4 waypoint8)
    (navigate rover4 waypoint9)
    (navigate rover4 waypoint10)
    (navigate rover4 waypoint11)
    (navigate rover4 waypoint12)
    (navigate rover4 waypoint13)
    (navigate rover4 waypoint14)
    (navigate rover4 waypoint15)
    (navigate rover4 waypoint16)
    (navigate rover4 waypoint17)
    (navigate rover4 waypoint18)
    (navigate rover4 waypoint19)
    (navigate rover4 waypoint20)
    (navigate rover4 waypoint21)
    (navigate rover4 waypoint22)
    (navigate rover4 waypoint23)
    (navigate rover4 waypoint24)
    (navigate rover4 waypoint25)
    (navigate rover4 waypoint26)
    (navigate rover4 waypoint27)
    (navigate rover4 waypoint28)
    (navigate rover4 waypoint29)
    (navigate rover4 waypoint30)
    (navigate rover4 waypoint31)
    (navigate rover4 waypoint32)
    (navigate rover4 waypoint33)
    (navigate rover4 waypoint34)
    (navigate rover4 waypoint35)
    (navigate rover4 waypoint36)
    (navigate rover4 waypoint37)
    (navigate rover4 waypoint38)
    (navigate rover4 waypoint39)
    (navigate rover5 waypoint0)
    (navigate rover5 waypoint1)
    (navigate rover5 waypoint2)
    (navigate rover5 waypoint3)
    (navigate rover5 waypoint4)
    (navigate rover5 waypoint5)
    (navigate rover5 waypoint6)
    (navigate rover5 waypoint7)
    (navigate rover5 waypoint8)
    (navigate rover5 waypoint9)
    (navigate rover5 waypoint10)
    (navigate rover5 waypoint11)
    (navigate rover5 waypoint12)
    (navigate rover5 waypoint13)
    (navigate rover5 waypoint14)
    (navigate rover5 waypoint15)
    (navigate rover5 waypoint16)
    (navigate rover5 waypoint17)
    (navigate rover5 waypoint18)
    (navigate rover5 waypoint19)
    (navigate rover5 waypoint20)
    (navigate rover5 waypoint21)
    (navigate rover5 waypoint22)
    (navigate rover5 waypoint23)
    (navigate rover5 waypoint24)
    (navigate rover5 waypoint25)
    (navigate rover5 waypoint26)
    (navigate rover5 waypoint27)
    (navigate rover5 waypoint28)
    (navigate rover5 waypoint29)
    (navigate rover5 waypoint30)
    (navigate rover5 waypoint31)
    (navigate rover5 waypoint32)
    (navigate rover5 waypoint33)
    (navigate rover5 waypoint34)
    (navigate rover5 waypoint35)
    (navigate rover5 waypoint36)
    (navigate rover5 waypoint37)
    (navigate rover5 waypoint38)
    (navigate rover5 waypoint39)
    (navigate rover6 waypoint0)
    (navigate rover6 waypoint1)
    (navigate rover6 waypoint2)
    (navigate rover6 waypoint3)
    (navigate rover6 waypoint4)
    (navigate rover6 waypoint5)
    (navigate rover6 waypoint6)
    (navigate rover6 waypoint7)
    (navigate rover6 waypoint8)
    (navigate rover6 waypoint9)
    (navigate rover6 waypoint10)
    (navigate rover6 waypoint11)
    (navigate rover6 waypoint12)
    (navigate rover6 waypoint13)
    (navigate rover6 waypoint14)
    (navigate rover6 waypoint15)
    (navigate rover6 waypoint16)
    (navigate rover6 waypoint17)
    (navigate rover6 waypoint18)
    (navigate rover6 waypoint19)
    (navigate rover6 waypoint20)
    (navigate rover6 waypoint21)
    (navigate rover6 waypoint22)
    (navigate rover6 waypoint23)
    (navigate rover6 waypoint24)
    (navigate rover6 waypoint25)
    (navigate rover6 waypoint26)
    (navigate rover6 waypoint27)
    (navigate rover6 waypoint28)
    (navigate rover6 waypoint29)
    (navigate rover6 waypoint30)
    (navigate rover6 waypoint31)
    (navigate rover6 waypoint32)
    (navigate rover6 waypoint33)
    (navigate rover6 waypoint34)
    (navigate rover6 waypoint35)
    (navigate rover6 waypoint36)
    (navigate rover6 waypoint37)
    (navigate rover6 waypoint38)
    (navigate rover6 waypoint39)
    (navigate rover7 waypoint0)
    (navigate rover7 waypoint1)
    (navigate rover7 waypoint2)
    (navigate rover7 waypoint3)
    (navigate rover7 waypoint4)
    (navigate rover7 waypoint5)
    (navigate rover7 waypoint6)
    (navigate rover7 waypoint7)
    (navigate rover7 waypoint8)
    (navigate rover7 waypoint9)
    (navigate rover7 waypoint10)
    (navigate rover7 waypoint11)
    (navigate rover7 waypoint12)
    (navigate rover7 waypoint13)
    (navigate rover7 waypoint14)
    (navigate rover7 waypoint15)
    (navigate rover7 waypoint16)
    (navigate rover7 waypoint17)
    (navigate rover7 waypoint18)
    (navigate rover7 waypoint19)
    (navigate rover7 waypoint20)
    (navigate rover7 waypoint21)
    (navigate rover7 waypoint22)
    (navigate rover7 waypoint23)
    (navigate rover7 waypoint24)
    (navigate rover7 waypoint25)
    (navigate rover7 waypoint26)
    (navigate rover7 waypoint27)
    (navigate rover7 waypoint28)
    (navigate rover7 waypoint29)
    (navigate rover7 waypoint30)
    (navigate rover7 waypoint31)
    (navigate rover7 waypoint32)
    (navigate rover7 waypoint33)
    (navigate rover7 waypoint34)
    (navigate rover7 waypoint35)
    (navigate rover7 waypoint36)
    (navigate rover7 waypoint37)
    (navigate rover7 waypoint38)
    (navigate rover7 waypoint39)
    (navigate rover8 waypoint0)
    (navigate rover8 waypoint1)
    (navigate rover8 waypoint2)
    (navigate rover8 waypoint3)
    (navigate rover8 waypoint4)
    (navigate rover8 waypoint5)
    (navigate rover8 waypoint6)
    (navigate rover8 waypoint7)
    (navigate rover8 waypoint8)
    (navigate rover8 waypoint9)
    (navigate rover8 waypoint10)
    (navigate rover8 waypoint11)
    (navigate rover8 waypoint12)
    (navigate rover8 waypoint13)
    (navigate rover8 waypoint14)
    (navigate rover8 waypoint15)
    (navigate rover8 waypoint16)
    (navigate rover8 waypoint17)
    (navigate rover8 waypoint18)
    (navigate rover8 waypoint19)
    (navigate rover8 waypoint20)
    (navigate rover8 waypoint21)
    (navigate rover8 waypoint22)
    (navigate rover8 waypoint23)
    (navigate rover8 waypoint24)
    (navigate rover8 waypoint25)
    (navigate rover8 waypoint26)
    (navigate rover8 waypoint27)
    (navigate rover8 waypoint28)
    (navigate rover8 waypoint29)
    (navigate rover8 waypoint30)
    (navigate rover8 waypoint31)
    (navigate rover8 waypoint32)
    (navigate rover8 waypoint33)
    (navigate rover8 waypoint34)
    (navigate rover8 waypoint35)
    (navigate rover8 waypoint36)
    (navigate rover8 waypoint37)
    (navigate rover8 waypoint38)
    (navigate rover8 waypoint39)
    (navigate rover9 waypoint0)
    (navigate rover9 waypoint1)
    (navigate rover9 waypoint2)
    (navigate rover9 waypoint3)
    (navigate rover9 waypoint4)
    (navigate rover9 waypoint5)
    (navigate rover9 waypoint6)
    (navigate rover9 waypoint7)
    (navigate rover9 waypoint8)
    (navigate rover9 waypoint9)
    (navigate rover9 waypoint10)
    (navigate rover9 waypoint11)
    (navigate rover9 waypoint12)
    (navigate rover9 waypoint13)
    (navigate rover9 waypoint14)
    (navigate rover9 waypoint15)
    (navigate rover9 waypoint16)
    (navigate rover9 waypoint17)
    (navigate rover9 waypoint18)
    (navigate rover9 waypoint19)
    (navigate rover9 waypoint20)
    (navigate rover9 waypoint21)
    (navigate rover9 waypoint22)
    (navigate rover9 waypoint23)
    (navigate rover9 waypoint24)
    (navigate rover9 waypoint25)
    (navigate rover9 waypoint26)
    (navigate rover9 waypoint27)
    (navigate rover9 waypoint28)
    (navigate rover9 waypoint29)
    (navigate rover9 waypoint30)
    (navigate rover9 waypoint31)
    (navigate rover9 waypoint32)
    (navigate rover9 waypoint33)
    (navigate rover9 waypoint34)
    (navigate rover9 waypoint35)
    (navigate rover9 waypoint36)
    (navigate rover9 waypoint37)
    (navigate rover9 waypoint38)
    (navigate rover9 waypoint39)
    (sample_soil rover0)
    (sample_rock rover0)
    (drop rover0)
    (sample_soil rover1)
    (sample_rock rover1)
    (drop rover1)
    (sample_soil rover2)
    (sample_rock rover2)
    (drop rover2)
    (sample_soil rover3)
    (sample_rock rover3)
    (drop rover3)
    (sample_soil rover4)
    (sample_rock rover4)
    (drop rover4)
    (sample_soil rover5)
    (sample_rock rover5)
    (drop rover5)
    (sample_soil rover6)
    (sample_rock rover6)
    (drop rover6)
    (sample_soil rover7)
    (sample_rock rover7)
    (drop rover7)
    (sample_soil rover8)
    (sample_rock rover8)
    (drop rover8)
    (sample_soil rover9)
    (sample_rock rover9)
    (drop rover9)
    (calibrate camera0 objective0)
    (calibrate camera0 objective1)
    (calibrate camera0 objective2)
    (calibrate camera0 objective3)
    (calibrate camera0 objective4)
    (calibrate camera0 objective5)
    (calibrate camera0 objective6)
    (calibrate camera0 objective7)
    (calibrate camera1 objective0)
    (calibrate camera1 objective1)
    (calibrate camera1 objective2)
    (calibrate camera1 objective3)
    (calibrate camera1 objective4)
    (calibrate camera1 objective5)
    (calibrate camera1 objective6)
    (calibrate camera1 objective7)
    (calibrate camera2 objective0)
    (calibrate camera2 objective1)
    (calibrate camera2 objective2)
    (calibrate camera2 objective3)
    (calibrate camera2 objective4)
    (calibrate camera2 objective5)
    (calibrate camera2 objective6)
    (calibrate camera2 objective7)
    (calibrate camera3 objective0)
    (calibrate camera3 objective1)
    (calibrate camera3 objective2)
    (calibrate camera3 objective3)
    (calibrate camera3 objective4)
    (calibrate camera3 objective5)
    (calibrate camera3 objective6)
    (calibrate camera3 objective7)
    (calibrate camera4 objective0)
    (calibrate camera4 objective1)
    (calibrate camera4 objective2)
    (calibrate camera4 objective3)
    (calibrate camera4 objective4)
    (calibrate camera4 objective5)
    (calibrate camera4 objective6)
    (calibrate camera4 objective7)
    (calibrate camera5 objective0)
    (calibrate camera5 objective1)
    (calibrate camera5 objective2)
    (calibrate camera5 objective3)
    (calibrate camera5 objective4)
    (calibrate camera5 objective5)
    (calibrate camera5 objective6)
    (calibrate camera5 objective7)
    (calibrate camera6 objective0)
    (calibrate camera6 objective1)
    (calibrate camera6 objective2)
    (calibrate camera6 objective3)
    (calibrate camera6 objective4)
    (calibrate camera6 objective5)
    (calibrate camera6 objective6)
    (calibrate camera6 objective7)
    (calibrate camera7 objective0)
    (calibrate camera7 objective1)
    (calibrate camera7 objective2)
    (calibrate camera7 objective3)
    (calibrate camera7 objective4)
    (calibrate camera7 objective5)
    (calibrate camera7 objective6)
    (calibrate camera7 objective7)
    (calibrate camera8 objective0)
    (calibrate camera8 objective1)
    (calibrate camera8 objective2)
    (calibrate camera8 objective3)
    (calibrate camera8 objective4)
    (calibrate camera8 objective5)
    (calibrate camera8 objective6)
    (calibrate camera8 objective7)
    (calibrate camera9 objective0)
    (calibrate camera9 objective1)
    (calibrate camera9 objective2)
    (calibrate camera9 objective3)
    (calibrate camera9 objective4)
    (calibrate camera9 objective5)
    (calibrate camera9 objective6)
    (calibrate camera9 objective7)
    (calibrate camera10 objective0)
    (calibrate camera10 objective1)
    (calibrate camera10 objective2)
    (calibrate camera10 objective3)
    (calibrate camera10 objective4)
    (calibrate camera10 objective5)
    (calibrate camera10 objective6)
    (calibrate camera10 objective7)
    (calibrate camera11 objective0)
    (calibrate camera11 objective1)
    (calibrate camera11 objective2)
    (calibrate camera11 objective3)
    (calibrate camera11 objective4)
    (calibrate camera11 objective5)
    (calibrate camera11 objective6)
    (calibrate camera11 objective7)
    (calibrate camera12 objective0)
    (calibrate camera12 objective1)
    (calibrate camera12 objective2)
    (calibrate camera12 objective3)
    (calibrate camera12 objective4)
    (calibrate camera12 objective5)
    (calibrate camera12 objective6)
    (calibrate camera12 objective7)
    (calibrate camera13 objective0)
    (calibrate camera13 objective1)
    (calibrate camera13 objective2)
    (calibrate camera13 objective3)
    (calibrate camera13 objective4)
    (calibrate camera13 objective5)
    (calibrate camera13 objective6)
    (calibrate camera13 objective7)
    (take_image objective0 camera0 colour)
    (take_image objective0 camera0 high_res)
    (take_image objective0 camera0 low_res)
    (take_image objective0 camera1 colour)
    (take_image objective0 camera1 high_res)
    (take_image objective0 camera1 low_res)
    (take_image objective0 camera2 colour)
    (take_image objective0 camera2 high_res)
    (take_image objective0 camera2 low_res)
    (take_image objective0 camera3 colour)
    (take_image objective0 camera3 high_res)
    (take_image objective0 camera3 low_res)
    (take_image objective0 camera4 colour)
    (take_image objective0 camera4 high_res)
    (take_image objective0 camera4 low_res)
    (take_image objective0 camera5 colour)
    (take_image objective0 camera5 high_res)
    (take_image objective0 camera5 low_res)
    (take_image objective0 camera6 colour)
    (take_image objective0 camera6 high_res)
    (take_image objective0 camera6 low_res)
    (take_image objective0 camera7 colour)
    (take_image objective0 camera7 high_res)
    (take_image objective0 camera7 low_res)
    (take_image objective0 camera8 colour)
    (take_image objective0 camera8 high_res)
    (take_image objective0 camera8 low_res)
    (take_image objective0 camera9 colour)
    (take_image objective0 camera9 high_res)
    (take_image objective0 camera9 low_res)
    (take_image objective0 camera10 colour)
    (take_image objective0 camera10 high_res)
    (take_image objective0 camera10 low_res)
    (take_image objective0 camera11 colour)
    (take_image objective0 camera11 high_res)
    (take_image objective0 camera11 low_res)
    (take_image objective0 camera12 colour)
    (take_image objective0 camera12 high_res)
    (take_image objective0 camera12 low_res)
    (take_image objective0 camera13 colour)
    (take_image objective0 camera13 high_res)
    (take_image objective0 camera13 low_res)
    (take_image objective1 camera0 colour)
    (take_image objective1 camera0 high_res)
    (take_image objective1 camera0 low_res)
    (take_image objective1 camera1 colour)
    (take_image objective1 camera1 high_res)
    (take_image objective1 camera1 low_res)
    (take_image objective1 camera2 colour)
    (take_image objective1 camera2 high_res)
    (take_image objective1 camera2 low_res)
    (take_image objective1 camera3 colour)
    (take_image objective1 camera3 high_res)
    (take_image objective1 camera3 low_res)
    (take_image objective1 camera4 colour)
    (take_image objective1 camera4 high_res)
    (take_image objective1 camera4 low_res)
    (take_image objective1 camera5 colour)
    (take_image objective1 camera5 high_res)
    (take_image objective1 camera5 low_res)
    (take_image objective1 camera6 colour)
    (take_image objective1 camera6 high_res)
    (take_image objective1 camera6 low_res)
    (take_image objective1 camera7 colour)
    (take_image objective1 camera7 high_res)
    (take_image objective1 camera7 low_res)
    (take_image objective1 camera8 colour)
    (take_image objective1 camera8 high_res)
    (take_image objective1 camera8 low_res)
    (take_image objective1 camera9 colour)
    (take_image objective1 camera9 high_res)
    (take_image objective1 camera9 low_res)
    (take_image objective1 camera10 colour)
    (take_image objective1 camera10 high_res)
    (take_image objective1 camera10 low_res)
    (take_image objective1 camera11 colour)
    (take_image objective1 camera11 high_res)
    (take_image objective1 camera11 low_res)
    (take_image objective1 camera12 colour)
    (take_image objective1 camera12 high_res)
    (take_image objective1 camera12 low_res)
    (take_image objective1 camera13 colour)
    (take_image objective1 camera13 high_res)
    (take_image objective1 camera13 low_res)
    (take_image objective2 camera0 colour)
    (take_image objective2 camera0 high_res)
    (take_image objective2 camera0 low_res)
    (take_image objective2 camera1 colour)
    (take_image objective2 camera1 high_res)
    (take_image objective2 camera1 low_res)
    (take_image objective2 camera2 colour)
    (take_image objective2 camera2 high_res)
    (take_image objective2 camera2 low_res)
    (take_image objective2 camera3 colour)
    (take_image objective2 camera3 high_res)
    (take_image objective2 camera3 low_res)
    (take_image objective2 camera4 colour)
    (take_image objective2 camera4 high_res)
    (take_image objective2 camera4 low_res)
    (take_image objective2 camera5 colour)
    (take_image objective2 camera5 high_res)
    (take_image objective2 camera5 low_res)
    (take_image objective2 camera6 colour)
    (take_image objective2 camera6 high_res)
    (take_image objective2 camera6 low_res)
    (take_image objective2 camera7 colour)
    (take_image objective2 camera7 high_res)
    (take_image objective2 camera7 low_res)
    (take_image objective2 camera8 colour)
    (take_image objective2 camera8 high_res)
    (take_image objective2 camera8 low_res)
    (take_image objective2 camera9 colour)
    (take_image objective2 camera9 high_res)
    (take_image objective2 camera9 low_res)
    (take_image objective2 camera10 colour)
    (take_image objective2 camera10 high_res)
    (take_image objective2 camera10 low_res)
    (take_image objective2 camera11 colour)
    (take_image objective2 camera11 high_res)
    (take_image objective2 camera11 low_res)
    (take_image objective2 camera12 colour)
    (take_image objective2 camera12 high_res)
    (take_image objective2 camera12 low_res)
    (take_image objective2 camera13 colour)
    (take_image objective2 camera13 high_res)
    (take_image objective2 camera13 low_res)
    (take_image objective3 camera0 colour)
    (take_image objective3 camera0 high_res)
    (take_image objective3 camera0 low_res)
    (take_image objective3 camera1 colour)
    (take_image objective3 camera1 high_res)
    (take_image objective3 camera1 low_res)
    (take_image objective3 camera2 colour)
    (take_image objective3 camera2 high_res)
    (take_image objective3 camera2 low_res)
    (take_image objective3 camera3 colour)
    (take_image objective3 camera3 high_res)
    (take_image objective3 camera3 low_res)
    (take_image objective3 camera4 colour)
    (take_image objective3 camera4 high_res)
    (take_image objective3 camera4 low_res)
    (take_image objective3 camera5 colour)
    (take_image objective3 camera5 high_res)
    (take_image objective3 camera5 low_res)
    (take_image objective3 camera6 colour)
    (take_image objective3 camera6 high_res)
    (take_image objective3 camera6 low_res)
    (take_image objective3 camera7 colour)
    (take_image objective3 camera7 high_res)
    (take_image objective3 camera7 low_res)
    (take_image objective3 camera8 colour)
    (take_image objective3 camera8 high_res)
    (take_image objective3 camera8 low_res)
    (take_image objective3 camera9 colour)
    (take_image objective3 camera9 high_res)
    (take_image objective3 camera9 low_res)
    (take_image objective3 camera10 colour)
    (take_image objective3 camera10 high_res)
    (take_image objective3 camera10 low_res)
    (take_image objective3 camera11 colour)
    (take_image objective3 camera11 high_res)
    (take_image objective3 camera11 low_res)
    (take_image objective3 camera12 colour)
    (take_image objective3 camera12 high_res)
    (take_image objective3 camera12 low_res)
    (take_image objective3 camera13 colour)
    (take_image objective3 camera13 high_res)
    (take_image objective3 camera13 low_res)
    (take_image objective4 camera0 colour)
    (take_image objective4 camera0 high_res)
    (take_image objective4 camera0 low_res)
    (take_image objective4 camera1 colour)
    (take_image objective4 camera1 high_res)
    (take_image objective4 camera1 low_res)
    (take_image objective4 camera2 colour)
    (take_image objective4 camera2 high_res)
    (take_image objective4 camera2 low_res)
    (take_image objective4 camera3 colour)
    (take_image objective4 camera3 high_res)
    (take_image objective4 camera3 low_res)
    (take_image objective4 camera4 colour)
    (take_image objective4 camera4 high_res)
    (take_image objective4 camera4 low_res)
    (take_image objective4 camera5 colour)
    (take_image objective4 camera5 high_res)
    (take_image objective4 camera5 low_res)
    (take_image objective4 camera6 colour)
    (take_image objective4 camera6 high_res)
    (take_image objective4 camera6 low_res)
    (take_image objective4 camera7 colour)
    (take_image objective4 camera7 high_res)
    (take_image objective4 camera7 low_res)
    (take_image objective4 camera8 colour)
    (take_image objective4 camera8 high_res)
    (take_image objective4 camera8 low_res)
    (take_image objective4 camera9 colour)
    (take_image objective4 camera9 high_res)
    (take_image objective4 camera9 low_res)
    (take_image objective4 camera10 colour)
    (take_image objective4 camera10 high_res)
    (take_image objective4 camera10 low_res)
    (take_image objective4 camera11 colour)
    (take_image objective4 camera11 high_res)
    (take_image objective4 camera11 low_res)
    (take_image objective4 camera12 colour)
    (take_image objective4 camera12 high_res)
    (take_image objective4 camera12 low_res)
    (take_image objective4 camera13 colour)
    (take_image objective4 camera13 high_res)
    (take_image objective4 camera13 low_res)
    (take_image objective5 camera0 colour)
    (take_image objective5 camera0 high_res)
    (take_image objective5 camera0 low_res)
    (take_image objective5 camera1 colour)
    (take_image objective5 camera1 high_res)
    (take_image objective5 camera1 low_res)
    (take_image objective5 camera2 colour)
    (take_image objective5 camera2 high_res)
    (take_image objective5 camera2 low_res)
    (take_image objective5 camera3 colour)
    (take_image objective5 camera3 high_res)
    (take_image objective5 camera3 low_res)
    (take_image objective5 camera4 colour)
    (take_image objective5 camera4 high_res)
    (take_image objective5 camera4 low_res)
    (take_image objective5 camera5 colour)
    (take_image objective5 camera5 high_res)
    (take_image objective5 camera5 low_res)
    (take_image objective5 camera6 colour)
    (take_image objective5 camera6 high_res)
    (take_image objective5 camera6 low_res)
    (take_image objective5 camera7 colour)
    (take_image objective5 camera7 high_res)
    (take_image objective5 camera7 low_res)
    (take_image objective5 camera8 colour)
    (take_image objective5 camera8 high_res)
    (take_image objective5 camera8 low_res)
    (take_image objective5 camera9 colour)
    (take_image objective5 camera9 high_res)
    (take_image objective5 camera9 low_res)
    (take_image objective5 camera10 colour)
    (take_image objective5 camera10 high_res)
    (take_image objective5 camera10 low_res)
    (take_image objective5 camera11 colour)
    (take_image objective5 camera11 high_res)
    (take_image objective5 camera11 low_res)
    (take_image objective5 camera12 colour)
    (take_image objective5 camera12 high_res)
    (take_image objective5 camera12 low_res)
    (take_image objective5 camera13 colour)
    (take_image objective5 camera13 high_res)
    (take_image objective5 camera13 low_res)
    (take_image objective6 camera0 colour)
    (take_image objective6 camera0 high_res)
    (take_image objective6 camera0 low_res)
    (take_image objective6 camera1 colour)
    (take_image objective6 camera1 high_res)
    (take_image objective6 camera1 low_res)
    (take_image objective6 camera2 colour)
    (take_image objective6 camera2 high_res)
    (take_image objective6 camera2 low_res)
    (take_image objective6 camera3 colour)
    (take_image objective6 camera3 high_res)
    (take_image objective6 camera3 low_res)
    (take_image objective6 camera4 colour)
    (take_image objective6 camera4 high_res)
    (take_image objective6 camera4 low_res)
    (take_image objective6 camera5 colour)
    (take_image objective6 camera5 high_res)
    (take_image objective6 camera5 low_res)
    (take_image objective6 camera6 colour)
    (take_image objective6 camera6 high_res)
    (take_image objective6 camera6 low_res)
    (take_image objective6 camera7 colour)
    (take_image objective6 camera7 high_res)
    (take_image objective6 camera7 low_res)
    (take_image objective6 camera8 colour)
    (take_image objective6 camera8 high_res)
    (take_image objective6 camera8 low_res)
    (take_image objective6 camera9 colour)
    (take_image objective6 camera9 high_res)
    (take_image objective6 camera9 low_res)
    (take_image objective6 camera10 colour)
    (take_image objective6 camera10 high_res)
    (take_image objective6 camera10 low_res)
    (take_image objective6 camera11 colour)
    (take_image objective6 camera11 high_res)
    (take_image objective6 camera11 low_res)
    (take_image objective6 camera12 colour)
    (take_image objective6 camera12 high_res)
    (take_image objective6 camera12 low_res)
    (take_image objective6 camera13 colour)
    (take_image objective6 camera13 high_res)
    (take_image objective6 camera13 low_res)
    (take_image objective7 camera0 colour)
    (take_image objective7 camera0 high_res)
    (take_image objective7 camera0 low_res)
    (take_image objective7 camera1 colour)
    (take_image objective7 camera1 high_res)
    (take_image objective7 camera1 low_res)
    (take_image objective7 camera2 colour)
    (take_image objective7 camera2 high_res)
    (take_image objective7 camera2 low_res)
    (take_image objective7 camera3 colour)
    (take_image objective7 camera3 high_res)
    (take_image objective7 camera3 low_res)
    (take_image objective7 camera4 colour)
    (take_image objective7 camera4 high_res)
    (take_image objective7 camera4 low_res)
    (take_image objective7 camera5 colour)
    (take_image objective7 camera5 high_res)
    (take_image objective7 camera5 low_res)
    (take_image objective7 camera6 colour)
    (take_image objective7 camera6 high_res)
    (take_image objective7 camera6 low_res)
    (take_image objective7 camera7 colour)
    (take_image objective7 camera7 high_res)
    (take_image objective7 camera7 low_res)
    (take_image objective7 camera8 colour)
    (take_image objective7 camera8 high_res)
    (take_image objective7 camera8 low_res)
    (take_image objective7 camera9 colour)
    (take_image objective7 camera9 high_res)
    (take_image objective7 camera9 low_res)
    (take_image objective7 camera10 colour)
    (take_image objective7 camera10 high_res)
    (take_image objective7 camera10 low_res)
    (take_image objective7 camera11 colour)
    (take_image objective7 camera11 high_res)
    (take_image objective7 camera11 low_res)
    (take_image objective7 camera12 colour)
    (take_image objective7 camera12 high_res)
    (take_image objective7 camera12 low_res)
    (take_image objective7 camera13 colour)
    (take_image objective7 camera13 high_res)
    (take_image objective7 camera13 low_res)
    (communicate_soil_data rover0 waypoint0)
    (communicate_rock_data rover0 waypoint0)
    (communicate_soil_data rover0 waypoint1)
    (communicate_rock_data rover0 waypoint1)
    (communicate_soil_data rover0 waypoint2)
    (communicate_rock_data rover0 waypoint2)
    (communicate_soil_data rover0 waypoint3)
    (communicate_rock_data rover0 waypoint3)
    (communicate_soil_data rover0 waypoint4)
    (communicate_rock_data rover0 waypoint4)
    (communicate_soil_data rover0 waypoint5)
    (communicate_rock_data rover0 waypoint5)
    (communicate_soil_data rover0 waypoint6)
    (communicate_rock_data rover0 waypoint6)
    (communicate_soil_data rover0 waypoint7)
    (communicate_rock_data rover0 waypoint7)
    (communicate_soil_data rover0 waypoint8)
    (communicate_rock_data rover0 waypoint8)
    (communicate_soil_data rover0 waypoint9)
    (communicate_rock_data rover0 waypoint9)
    (communicate_soil_data rover0 waypoint10)
    (communicate_rock_data rover0 waypoint10)
    (communicate_soil_data rover0 waypoint11)
    (communicate_rock_data rover0 waypoint11)
    (communicate_soil_data rover0 waypoint12)
    (communicate_rock_data rover0 waypoint12)
    (communicate_soil_data rover0 waypoint13)
    (communicate_rock_data rover0 waypoint13)
    (communicate_soil_data rover0 waypoint14)
    (communicate_rock_data rover0 waypoint14)
    (communicate_soil_data rover0 waypoint15)
    (communicate_rock_data rover0 waypoint15)
    (communicate_soil_data rover0 waypoint16)
    (communicate_rock_data rover0 waypoint16)
    (communicate_soil_data rover0 waypoint17)
    (communicate_rock_data rover0 waypoint17)
    (communicate_soil_data rover0 waypoint18)
    (communicate_rock_data rover0 waypoint18)
    (communicate_soil_data rover0 waypoint19)
    (communicate_rock_data rover0 waypoint19)
    (communicate_soil_data rover0 waypoint20)
    (communicate_rock_data rover0 waypoint20)
    (communicate_soil_data rover0 waypoint21)
    (communicate_rock_data rover0 waypoint21)
    (communicate_soil_data rover0 waypoint22)
    (communicate_rock_data rover0 waypoint22)
    (communicate_soil_data rover0 waypoint23)
    (communicate_rock_data rover0 waypoint23)
    (communicate_soil_data rover0 waypoint24)
    (communicate_rock_data rover0 waypoint24)
    (communicate_soil_data rover0 waypoint25)
    (communicate_rock_data rover0 waypoint25)
    (communicate_soil_data rover0 waypoint26)
    (communicate_rock_data rover0 waypoint26)
    (communicate_soil_data rover0 waypoint27)
    (communicate_rock_data rover0 waypoint27)
    (communicate_soil_data rover0 waypoint28)
    (communicate_rock_data rover0 waypoint28)
    (communicate_soil_data rover0 waypoint29)
    (communicate_rock_data rover0 waypoint29)
    (communicate_soil_data rover0 waypoint30)
    (communicate_rock_data rover0 waypoint30)
    (communicate_soil_data rover0 waypoint31)
    (communicate_rock_data rover0 waypoint31)
    (communicate_soil_data rover0 waypoint32)
    (communicate_rock_data rover0 waypoint32)
    (communicate_soil_data rover0 waypoint33)
    (communicate_rock_data rover0 waypoint33)
    (communicate_soil_data rover0 waypoint34)
    (communicate_rock_data rover0 waypoint34)
    (communicate_soil_data rover0 waypoint35)
    (communicate_rock_data rover0 waypoint35)
    (communicate_soil_data rover0 waypoint36)
    (communicate_rock_data rover0 waypoint36)
    (communicate_soil_data rover0 waypoint37)
    (communicate_rock_data rover0 waypoint37)
    (communicate_soil_data rover0 waypoint38)
    (communicate_rock_data rover0 waypoint38)
    (communicate_soil_data rover0 waypoint39)
    (communicate_rock_data rover0 waypoint39)
    (communicate_soil_data rover1 waypoint0)
    (communicate_rock_data rover1 waypoint0)
    (communicate_soil_data rover1 waypoint1)
    (communicate_rock_data rover1 waypoint1)
    (communicate_soil_data rover1 waypoint2)
    (communicate_rock_data rover1 waypoint2)
    (communicate_soil_data rover1 waypoint3)
    (communicate_rock_data rover1 waypoint3)
    (communicate_soil_data rover1 waypoint4)
    (communicate_rock_data rover1 waypoint4)
    (communicate_soil_data rover1 waypoint5)
    (communicate_rock_data rover1 waypoint5)
    (communicate_soil_data rover1 waypoint6)
    (communicate_rock_data rover1 waypoint6)
    (communicate_soil_data rover1 waypoint7)
    (communicate_rock_data rover1 waypoint7)
    (communicate_soil_data rover1 waypoint8)
    (communicate_rock_data rover1 waypoint8)
    (communicate_soil_data rover1 waypoint9)
    (communicate_rock_data rover1 waypoint9)
    (communicate_soil_data rover1 waypoint10)
    (communicate_rock_data rover1 waypoint10)
    (communicate_soil_data rover1 waypoint11)
    (communicate_rock_data rover1 waypoint11)
    (communicate_soil_data rover1 waypoint12)
    (communicate_rock_data rover1 waypoint12)
    (communicate_soil_data rover1 waypoint13)
    (communicate_rock_data rover1 waypoint13)
    (communicate_soil_data rover1 waypoint14)
    (communicate_rock_data rover1 waypoint14)
    (communicate_soil_data rover1 waypoint15)
    (communicate_rock_data rover1 waypoint15)
    (communicate_soil_data rover1 waypoint16)
    (communicate_rock_data rover1 waypoint16)
    (communicate_soil_data rover1 waypoint17)
    (communicate_rock_data rover1 waypoint17)
    (communicate_soil_data rover1 waypoint18)
    (communicate_rock_data rover1 waypoint18)
    (communicate_soil_data rover1 waypoint19)
    (communicate_rock_data rover1 waypoint19)
    (communicate_soil_data rover1 waypoint20)
    (communicate_rock_data rover1 waypoint20)
    (communicate_soil_data rover1 waypoint21)
    (communicate_rock_data rover1 waypoint21)
    (communicate_soil_data rover1 waypoint22)
    (communicate_rock_data rover1 waypoint22)
    (communicate_soil_data rover1 waypoint23)
    (communicate_rock_data rover1 waypoint23)
    (communicate_soil_data rover1 waypoint24)
    (communicate_rock_data rover1 waypoint24)
    (communicate_soil_data rover1 waypoint25)
    (communicate_rock_data rover1 waypoint25)
    (communicate_soil_data rover1 waypoint26)
    (communicate_rock_data rover1 waypoint26)
    (communicate_soil_data rover1 waypoint27)
    (communicate_rock_data rover1 waypoint27)
    (communicate_soil_data rover1 waypoint28)
    (communicate_rock_data rover1 waypoint28)
    (communicate_soil_data rover1 waypoint29)
    (communicate_rock_data rover1 waypoint29)
    (communicate_soil_data rover1 waypoint30)
    (communicate_rock_data rover1 waypoint30)
    (communicate_soil_data rover1 waypoint31)
    (communicate_rock_data rover1 waypoint31)
    (communicate_soil_data rover1 waypoint32)
    (communicate_rock_data rover1 waypoint32)
    (communicate_soil_data rover1 waypoint33)
    (communicate_rock_data rover1 waypoint33)
    (communicate_soil_data rover1 waypoint34)
    (communicate_rock_data rover1 waypoint34)
    (communicate_soil_data rover1 waypoint35)
    (communicate_rock_data rover1 waypoint35)
    (communicate_soil_data rover1 waypoint36)
    (communicate_rock_data rover1 waypoint36)
    (communicate_soil_data rover1 waypoint37)
    (communicate_rock_data rover1 waypoint37)
    (communicate_soil_data rover1 waypoint38)
    (communicate_rock_data rover1 waypoint38)
    (communicate_soil_data rover1 waypoint39)
    (communicate_rock_data rover1 waypoint39)
    (communicate_soil_data rover2 waypoint0)
    (communicate_rock_data rover2 waypoint0)
    (communicate_soil_data rover2 waypoint1)
    (communicate_rock_data rover2 waypoint1)
    (communicate_soil_data rover2 waypoint2)
    (communicate_rock_data rover2 waypoint2)
    (communicate_soil_data rover2 waypoint3)
    (communicate_rock_data rover2 waypoint3)
    (communicate_soil_data rover2 waypoint4)
    (communicate_rock_data rover2 waypoint4)
    (communicate_soil_data rover2 waypoint5)
    (communicate_rock_data rover2 waypoint5)
    (communicate_soil_data rover2 waypoint6)
    (communicate_rock_data rover2 waypoint6)
    (communicate_soil_data rover2 waypoint7)
    (communicate_rock_data rover2 waypoint7)
    (communicate_soil_data rover2 waypoint8)
    (communicate_rock_data rover2 waypoint8)
    (communicate_soil_data rover2 waypoint9)
    (communicate_rock_data rover2 waypoint9)
    (communicate_soil_data rover2 waypoint10)
    (communicate_rock_data rover2 waypoint10)
    (communicate_soil_data rover2 waypoint11)
    (communicate_rock_data rover2 waypoint11)
    (communicate_soil_data rover2 waypoint12)
    (communicate_rock_data rover2 waypoint12)
    (communicate_soil_data rover2 waypoint13)
    (communicate_rock_data rover2 waypoint13)
    (communicate_soil_data rover2 waypoint14)
    (communicate_rock_data rover2 waypoint14)
    (communicate_soil_data rover2 waypoint15)
    (communicate_rock_data rover2 waypoint15)
    (communicate_soil_data rover2 waypoint16)
    (communicate_rock_data rover2 waypoint16)
    (communicate_soil_data rover2 waypoint17)
    (communicate_rock_data rover2 waypoint17)
    (communicate_soil_data rover2 waypoint18)
    (communicate_rock_data rover2 waypoint18)
    (communicate_soil_data rover2 waypoint19)
    (communicate_rock_data rover2 waypoint19)
    (communicate_soil_data rover2 waypoint20)
    (communicate_rock_data rover2 waypoint20)
    (communicate_soil_data rover2 waypoint21)
    (communicate_rock_data rover2 waypoint21)
    (communicate_soil_data rover2 waypoint22)
    (communicate_rock_data rover2 waypoint22)
    (communicate_soil_data rover2 waypoint23)
    (communicate_rock_data rover2 waypoint23)
    (communicate_soil_data rover2 waypoint24)
    (communicate_rock_data rover2 waypoint24)
    (communicate_soil_data rover2 waypoint25)
    (communicate_rock_data rover2 waypoint25)
    (communicate_soil_data rover2 waypoint26)
    (communicate_rock_data rover2 waypoint26)
    (communicate_soil_data rover2 waypoint27)
    (communicate_rock_data rover2 waypoint27)
    (communicate_soil_data rover2 waypoint28)
    (communicate_rock_data rover2 waypoint28)
    (communicate_soil_data rover2 waypoint29)
    (communicate_rock_data rover2 waypoint29)
    (communicate_soil_data rover2 waypoint30)
    (communicate_rock_data rover2 waypoint30)
    (communicate_soil_data rover2 waypoint31)
    (communicate_rock_data rover2 waypoint31)
    (communicate_soil_data rover2 waypoint32)
    (communicate_rock_data rover2 waypoint32)
    (communicate_soil_data rover2 waypoint33)
    (communicate_rock_data rover2 waypoint33)
    (communicate_soil_data rover2 waypoint34)
    (communicate_rock_data rover2 waypoint34)
    (communicate_soil_data rover2 waypoint35)
    (communicate_rock_data rover2 waypoint35)
    (communicate_soil_data rover2 waypoint36)
    (communicate_rock_data rover2 waypoint36)
    (communicate_soil_data rover2 waypoint37)
    (communicate_rock_data rover2 waypoint37)
    (communicate_soil_data rover2 waypoint38)
    (communicate_rock_data rover2 waypoint38)
    (communicate_soil_data rover2 waypoint39)
    (communicate_rock_data rover2 waypoint39)
    (communicate_soil_data rover3 waypoint0)
    (communicate_rock_data rover3 waypoint0)
    (communicate_soil_data rover3 waypoint1)
    (communicate_rock_data rover3 waypoint1)
    (communicate_soil_data rover3 waypoint2)
    (communicate_rock_data rover3 waypoint2)
    (communicate_soil_data rover3 waypoint3)
    (communicate_rock_data rover3 waypoint3)
    (communicate_soil_data rover3 waypoint4)
    (communicate_rock_data rover3 waypoint4)
    (communicate_soil_data rover3 waypoint5)
    (communicate_rock_data rover3 waypoint5)
    (communicate_soil_data rover3 waypoint6)
    (communicate_rock_data rover3 waypoint6)
    (communicate_soil_data rover3 waypoint7)
    (communicate_rock_data rover3 waypoint7)
    (communicate_soil_data rover3 waypoint8)
    (communicate_rock_data rover3 waypoint8)
    (communicate_soil_data rover3 waypoint9)
    (communicate_rock_data rover3 waypoint9)
    (communicate_soil_data rover3 waypoint10)
    (communicate_rock_data rover3 waypoint10)
    (communicate_soil_data rover3 waypoint11)
    (communicate_rock_data rover3 waypoint11)
    (communicate_soil_data rover3 waypoint12)
    (communicate_rock_data rover3 waypoint12)
    (communicate_soil_data rover3 waypoint13)
    (communicate_rock_data rover3 waypoint13)
    (communicate_soil_data rover3 waypoint14)
    (communicate_rock_data rover3 waypoint14)
    (communicate_soil_data rover3 waypoint15)
    (communicate_rock_data rover3 waypoint15)
    (communicate_soil_data rover3 waypoint16)
    (communicate_rock_data rover3 waypoint16)
    (communicate_soil_data rover3 waypoint17)
    (communicate_rock_data rover3 waypoint17)
    (communicate_soil_data rover3 waypoint18)
    (communicate_rock_data rover3 waypoint18)
    (communicate_soil_data rover3 waypoint19)
    (communicate_rock_data rover3 waypoint19)
    (communicate_soil_data rover3 waypoint20)
    (communicate_rock_data rover3 waypoint20)
    (communicate_soil_data rover3 waypoint21)
    (communicate_rock_data rover3 waypoint21)
    (communicate_soil_data rover3 waypoint22)
    (communicate_rock_data rover3 waypoint22)
    (communicate_soil_data rover3 waypoint23)
    (communicate_rock_data rover3 waypoint23)
    (communicate_soil_data rover3 waypoint24)
    (communicate_rock_data rover3 waypoint24)
    (communicate_soil_data rover3 waypoint25)
    (communicate_rock_data rover3 waypoint25)
    (communicate_soil_data rover3 waypoint26)
    (communicate_rock_data rover3 waypoint26)
    (communicate_soil_data rover3 waypoint27)
    (communicate_rock_data rover3 waypoint27)
    (communicate_soil_data rover3 waypoint28)
    (communicate_rock_data rover3 waypoint28)
    (communicate_soil_data rover3 waypoint29)
    (communicate_rock_data rover3 waypoint29)
    (communicate_soil_data rover3 waypoint30)
    (communicate_rock_data rover3 waypoint30)
    (communicate_soil_data rover3 waypoint31)
    (communicate_rock_data rover3 waypoint31)
    (communicate_soil_data rover3 waypoint32)
    (communicate_rock_data rover3 waypoint32)
    (communicate_soil_data rover3 waypoint33)
    (communicate_rock_data rover3 waypoint33)
    (communicate_soil_data rover3 waypoint34)
    (communicate_rock_data rover3 waypoint34)
    (communicate_soil_data rover3 waypoint35)
    (communicate_rock_data rover3 waypoint35)
    (communicate_soil_data rover3 waypoint36)
    (communicate_rock_data rover3 waypoint36)
    (communicate_soil_data rover3 waypoint37)
    (communicate_rock_data rover3 waypoint37)
    (communicate_soil_data rover3 waypoint38)
    (communicate_rock_data rover3 waypoint38)
    (communicate_soil_data rover3 waypoint39)
    (communicate_rock_data rover3 waypoint39)
    (communicate_soil_data rover4 waypoint0)
    (communicate_rock_data rover4 waypoint0)
    (communicate_soil_data rover4 waypoint1)
    (communicate_rock_data rover4 waypoint1)
    (communicate_soil_data rover4 waypoint2)
    (communicate_rock_data rover4 waypoint2)
    (communicate_soil_data rover4 waypoint3)
    (communicate_rock_data rover4 waypoint3)
    (communicate_soil_data rover4 waypoint4)
    (communicate_rock_data rover4 waypoint4)
    (communicate_soil_data rover4 waypoint5)
    (communicate_rock_data rover4 waypoint5)
    (communicate_soil_data rover4 waypoint6)
    (communicate_rock_data rover4 waypoint6)
    (communicate_soil_data rover4 waypoint7)
    (communicate_rock_data rover4 waypoint7)
    (communicate_soil_data rover4 waypoint8)
    (communicate_rock_data rover4 waypoint8)
    (communicate_soil_data rover4 waypoint9)
    (communicate_rock_data rover4 waypoint9)
    (communicate_soil_data rover4 waypoint10)
    (communicate_rock_data rover4 waypoint10)
    (communicate_soil_data rover4 waypoint11)
    (communicate_rock_data rover4 waypoint11)
    (communicate_soil_data rover4 waypoint12)
    (communicate_rock_data rover4 waypoint12)
    (communicate_soil_data rover4 waypoint13)
    (communicate_rock_data rover4 waypoint13)
    (communicate_soil_data rover4 waypoint14)
    (communicate_rock_data rover4 waypoint14)
    (communicate_soil_data rover4 waypoint15)
    (communicate_rock_data rover4 waypoint15)
    (communicate_soil_data rover4 waypoint16)
    (communicate_rock_data rover4 waypoint16)
    (communicate_soil_data rover4 waypoint17)
    (communicate_rock_data rover4 waypoint17)
    (communicate_soil_data rover4 waypoint18)
    (communicate_rock_data rover4 waypoint18)
    (communicate_soil_data rover4 waypoint19)
    (communicate_rock_data rover4 waypoint19)
    (communicate_soil_data rover4 waypoint20)
    (communicate_rock_data rover4 waypoint20)
    (communicate_soil_data rover4 waypoint21)
    (communicate_rock_data rover4 waypoint21)
    (communicate_soil_data rover4 waypoint22)
    (communicate_rock_data rover4 waypoint22)
    (communicate_soil_data rover4 waypoint23)
    (communicate_rock_data rover4 waypoint23)
    (communicate_soil_data rover4 waypoint24)
    (communicate_rock_data rover4 waypoint24)
    (communicate_soil_data rover4 waypoint25)
    (communicate_rock_data rover4 waypoint25)
    (communicate_soil_data rover4 waypoint26)
    (communicate_rock_data rover4 waypoint26)
    (communicate_soil_data rover4 waypoint27)
    (communicate_rock_data rover4 waypoint27)
    (communicate_soil_data rover4 waypoint28)
    (communicate_rock_data rover4 waypoint28)
    (communicate_soil_data rover4 waypoint29)
    (communicate_rock_data rover4 waypoint29)
    (communicate_soil_data rover4 waypoint30)
    (communicate_rock_data rover4 waypoint30)
    (communicate_soil_data rover4 waypoint31)
    (communicate_rock_data rover4 waypoint31)
    (communicate_soil_data rover4 waypoint32)
    (communicate_rock_data rover4 waypoint32)
    (communicate_soil_data rover4 waypoint33)
    (communicate_rock_data rover4 waypoint33)
    (communicate_soil_data rover4 waypoint34)
    (communicate_rock_data rover4 waypoint34)
    (communicate_soil_data rover4 waypoint35)
    (communicate_rock_data rover4 waypoint35)
    (communicate_soil_data rover4 waypoint36)
    (communicate_rock_data rover4 waypoint36)
    (communicate_soil_data rover4 waypoint37)
    (communicate_rock_data rover4 waypoint37)
    (communicate_soil_data rover4 waypoint38)
    (communicate_rock_data rover4 waypoint38)
    (communicate_soil_data rover4 waypoint39)
    (communicate_rock_data rover4 waypoint39)
    (communicate_soil_data rover5 waypoint0)
    (communicate_rock_data rover5 waypoint0)
    (communicate_soil_data rover5 waypoint1)
    (communicate_rock_data rover5 waypoint1)
    (communicate_soil_data rover5 waypoint2)
    (communicate_rock_data rover5 waypoint2)
    (communicate_soil_data rover5 waypoint3)
    (communicate_rock_data rover5 waypoint3)
    (communicate_soil_data rover5 waypoint4)
    (communicate_rock_data rover5 waypoint4)
    (communicate_soil_data rover5 waypoint5)
    (communicate_rock_data rover5 waypoint5)
    (communicate_soil_data rover5 waypoint6)
    (communicate_rock_data rover5 waypoint6)
    (communicate_soil_data rover5 waypoint7)
    (communicate_rock_data rover5 waypoint7)
    (communicate_soil_data rover5 waypoint8)
    (communicate_rock_data rover5 waypoint8)
    (communicate_soil_data rover5 waypoint9)
    (communicate_rock_data rover5 waypoint9)
    (communicate_soil_data rover5 waypoint10)
    (communicate_rock_data rover5 waypoint10)
    (communicate_soil_data rover5 waypoint11)
    (communicate_rock_data rover5 waypoint11)
    (communicate_soil_data rover5 waypoint12)
    (communicate_rock_data rover5 waypoint12)
    (communicate_soil_data rover5 waypoint13)
    (communicate_rock_data rover5 waypoint13)
    (communicate_soil_data rover5 waypoint14)
    (communicate_rock_data rover5 waypoint14)
    (communicate_soil_data rover5 waypoint15)
    (communicate_rock_data rover5 waypoint15)
    (communicate_soil_data rover5 waypoint16)
    (communicate_rock_data rover5 waypoint16)
    (communicate_soil_data rover5 waypoint17)
    (communicate_rock_data rover5 waypoint17)
    (communicate_soil_data rover5 waypoint18)
    (communicate_rock_data rover5 waypoint18)
    (communicate_soil_data rover5 waypoint19)
    (communicate_rock_data rover5 waypoint19)
    (communicate_soil_data rover5 waypoint20)
    (communicate_rock_data rover5 waypoint20)
    (communicate_soil_data rover5 waypoint21)
    (communicate_rock_data rover5 waypoint21)
    (communicate_soil_data rover5 waypoint22)
    (communicate_rock_data rover5 waypoint22)
    (communicate_soil_data rover5 waypoint23)
    (communicate_rock_data rover5 waypoint23)
    (communicate_soil_data rover5 waypoint24)
    (communicate_rock_data rover5 waypoint24)
    (communicate_soil_data rover5 waypoint25)
    (communicate_rock_data rover5 waypoint25)
    (communicate_soil_data rover5 waypoint26)
    (communicate_rock_data rover5 waypoint26)
    (communicate_soil_data rover5 waypoint27)
    (communicate_rock_data rover5 waypoint27)
    (communicate_soil_data rover5 waypoint28)
    (communicate_rock_data rover5 waypoint28)
    (communicate_soil_data rover5 waypoint29)
    (communicate_rock_data rover5 waypoint29)
    (communicate_soil_data rover5 waypoint30)
    (communicate_rock_data rover5 waypoint30)
    (communicate_soil_data rover5 waypoint31)
    (communicate_rock_data rover5 waypoint31)
    (communicate_soil_data rover5 waypoint32)
    (communicate_rock_data rover5 waypoint32)
    (communicate_soil_data rover5 waypoint33)
    (communicate_rock_data rover5 waypoint33)
    (communicate_soil_data rover5 waypoint34)
    (communicate_rock_data rover5 waypoint34)
    (communicate_soil_data rover5 waypoint35)
    (communicate_rock_data rover5 waypoint35)
    (communicate_soil_data rover5 waypoint36)
    (communicate_rock_data rover5 waypoint36)
    (communicate_soil_data rover5 waypoint37)
    (communicate_rock_data rover5 waypoint37)
    (communicate_soil_data rover5 waypoint38)
    (communicate_rock_data rover5 waypoint38)
    (communicate_soil_data rover5 waypoint39)
    (communicate_rock_data rover5 waypoint39)
    (communicate_soil_data rover6 waypoint0)
    (communicate_rock_data rover6 waypoint0)
    (communicate_soil_data rover6 waypoint1)
    (communicate_rock_data rover6 waypoint1)
    (communicate_soil_data rover6 waypoint2)
    (communicate_rock_data rover6 waypoint2)
    (communicate_soil_data rover6 waypoint3)
    (communicate_rock_data rover6 waypoint3)
    (communicate_soil_data rover6 waypoint4)
    (communicate_rock_data rover6 waypoint4)
    (communicate_soil_data rover6 waypoint5)
    (communicate_rock_data rover6 waypoint5)
    (communicate_soil_data rover6 waypoint6)
    (communicate_rock_data rover6 waypoint6)
    (communicate_soil_data rover6 waypoint7)
    (communicate_rock_data rover6 waypoint7)
    (communicate_soil_data rover6 waypoint8)
    (communicate_rock_data rover6 waypoint8)
    (communicate_soil_data rover6 waypoint9)
    (communicate_rock_data rover6 waypoint9)
    (communicate_soil_data rover6 waypoint10)
    (communicate_rock_data rover6 waypoint10)
    (communicate_soil_data rover6 waypoint11)
    (communicate_rock_data rover6 waypoint11)
    (communicate_soil_data rover6 waypoint12)
    (communicate_rock_data rover6 waypoint12)
    (communicate_soil_data rover6 waypoint13)
    (communicate_rock_data rover6 waypoint13)
    (communicate_soil_data rover6 waypoint14)
    (communicate_rock_data rover6 waypoint14)
    (communicate_soil_data rover6 waypoint15)
    (communicate_rock_data rover6 waypoint15)
    (communicate_soil_data rover6 waypoint16)
    (communicate_rock_data rover6 waypoint16)
    (communicate_soil_data rover6 waypoint17)
    (communicate_rock_data rover6 waypoint17)
    (communicate_soil_data rover6 waypoint18)
    (communicate_rock_data rover6 waypoint18)
    (communicate_soil_data rover6 waypoint19)
    (communicate_rock_data rover6 waypoint19)
    (communicate_soil_data rover6 waypoint20)
    (communicate_rock_data rover6 waypoint20)
    (communicate_soil_data rover6 waypoint21)
    (communicate_rock_data rover6 waypoint21)
    (communicate_soil_data rover6 waypoint22)
    (communicate_rock_data rover6 waypoint22)
    (communicate_soil_data rover6 waypoint23)
    (communicate_rock_data rover6 waypoint23)
    (communicate_soil_data rover6 waypoint24)
    (communicate_rock_data rover6 waypoint24)
    (communicate_soil_data rover6 waypoint25)
    (communicate_rock_data rover6 waypoint25)
    (communicate_soil_data rover6 waypoint26)
    (communicate_rock_data rover6 waypoint26)
    (communicate_soil_data rover6 waypoint27)
    (communicate_rock_data rover6 waypoint27)
    (communicate_soil_data rover6 waypoint28)
    (communicate_rock_data rover6 waypoint28)
    (communicate_soil_data rover6 waypoint29)
    (communicate_rock_data rover6 waypoint29)
    (communicate_soil_data rover6 waypoint30)
    (communicate_rock_data rover6 waypoint30)
    (communicate_soil_data rover6 waypoint31)
    (communicate_rock_data rover6 waypoint31)
    (communicate_soil_data rover6 waypoint32)
    (communicate_rock_data rover6 waypoint32)
    (communicate_soil_data rover6 waypoint33)
    (communicate_rock_data rover6 waypoint33)
    (communicate_soil_data rover6 waypoint34)
    (communicate_rock_data rover6 waypoint34)
    (communicate_soil_data rover6 waypoint35)
    (communicate_rock_data rover6 waypoint35)
    (communicate_soil_data rover6 waypoint36)
    (communicate_rock_data rover6 waypoint36)
    (communicate_soil_data rover6 waypoint37)
    (communicate_rock_data rover6 waypoint37)
    (communicate_soil_data rover6 waypoint38)
    (communicate_rock_data rover6 waypoint38)
    (communicate_soil_data rover6 waypoint39)
    (communicate_rock_data rover6 waypoint39)
    (communicate_soil_data rover7 waypoint0)
    (communicate_rock_data rover7 waypoint0)
    (communicate_soil_data rover7 waypoint1)
    (communicate_rock_data rover7 waypoint1)
    (communicate_soil_data rover7 waypoint2)
    (communicate_rock_data rover7 waypoint2)
    (communicate_soil_data rover7 waypoint3)
    (communicate_rock_data rover7 waypoint3)
    (communicate_soil_data rover7 waypoint4)
    (communicate_rock_data rover7 waypoint4)
    (communicate_soil_data rover7 waypoint5)
    (communicate_rock_data rover7 waypoint5)
    (communicate_soil_data rover7 waypoint6)
    (communicate_rock_data rover7 waypoint6)
    (communicate_soil_data rover7 waypoint7)
    (communicate_rock_data rover7 waypoint7)
    (communicate_soil_data rover7 waypoint8)
    (communicate_rock_data rover7 waypoint8)
    (communicate_soil_data rover7 waypoint9)
    (communicate_rock_data rover7 waypoint9)
    (communicate_soil_data rover7 waypoint10)
    (communicate_rock_data rover7 waypoint10)
    (communicate_soil_data rover7 waypoint11)
    (communicate_rock_data rover7 waypoint11)
    (communicate_soil_data rover7 waypoint12)
    (communicate_rock_data rover7 waypoint12)
    (communicate_soil_data rover7 waypoint13)
    (communicate_rock_data rover7 waypoint13)
    (communicate_soil_data rover7 waypoint14)
    (communicate_rock_data rover7 waypoint14)
    (communicate_soil_data rover7 waypoint15)
    (communicate_rock_data rover7 waypoint15)
    (communicate_soil_data rover7 waypoint16)
    (communicate_rock_data rover7 waypoint16)
    (communicate_soil_data rover7 waypoint17)
    (communicate_rock_data rover7 waypoint17)
    (communicate_soil_data rover7 waypoint18)
    (communicate_rock_data rover7 waypoint18)
    (communicate_soil_data rover7 waypoint19)
    (communicate_rock_data rover7 waypoint19)
    (communicate_soil_data rover7 waypoint20)
    (communicate_rock_data rover7 waypoint20)
    (communicate_soil_data rover7 waypoint21)
    (communicate_rock_data rover7 waypoint21)
    (communicate_soil_data rover7 waypoint22)
    (communicate_rock_data rover7 waypoint22)
    (communicate_soil_data rover7 waypoint23)
    (communicate_rock_data rover7 waypoint23)
    (communicate_soil_data rover7 waypoint24)
    (communicate_rock_data rover7 waypoint24)
    (communicate_soil_data rover7 waypoint25)
    (communicate_rock_data rover7 waypoint25)
    (communicate_soil_data rover7 waypoint26)
    (communicate_rock_data rover7 waypoint26)
    (communicate_soil_data rover7 waypoint27)
    (communicate_rock_data rover7 waypoint27)
    (communicate_soil_data rover7 waypoint28)
    (communicate_rock_data rover7 waypoint28)
    (communicate_soil_data rover7 waypoint29)
    (communicate_rock_data rover7 waypoint29)
    (communicate_soil_data rover7 waypoint30)
    (communicate_rock_data rover7 waypoint30)
    (communicate_soil_data rover7 waypoint31)
    (communicate_rock_data rover7 waypoint31)
    (communicate_soil_data rover7 waypoint32)
    (communicate_rock_data rover7 waypoint32)
    (communicate_soil_data rover7 waypoint33)
    (communicate_rock_data rover7 waypoint33)
    (communicate_soil_data rover7 waypoint34)
    (communicate_rock_data rover7 waypoint34)
    (communicate_soil_data rover7 waypoint35)
    (communicate_rock_data rover7 waypoint35)
    (communicate_soil_data rover7 waypoint36)
    (communicate_rock_data rover7 waypoint36)
    (communicate_soil_data rover7 waypoint37)
    (communicate_rock_data rover7 waypoint37)
    (communicate_soil_data rover7 waypoint38)
    (communicate_rock_data rover7 waypoint38)
    (communicate_soil_data rover7 waypoint39)
    (communicate_rock_data rover7 waypoint39)
    (communicate_soil_data rover8 waypoint0)
    (communicate_rock_data rover8 waypoint0)
    (communicate_soil_data rover8 waypoint1)
    (communicate_rock_data rover8 waypoint1)
    (communicate_soil_data rover8 waypoint2)
    (communicate_rock_data rover8 waypoint2)
    (communicate_soil_data rover8 waypoint3)
    (communicate_rock_data rover8 waypoint3)
    (communicate_soil_data rover8 waypoint4)
    (communicate_rock_data rover8 waypoint4)
    (communicate_soil_data rover8 waypoint5)
    (communicate_rock_data rover8 waypoint5)
    (communicate_soil_data rover8 waypoint6)
    (communicate_rock_data rover8 waypoint6)
    (communicate_soil_data rover8 waypoint7)
    (communicate_rock_data rover8 waypoint7)
    (communicate_soil_data rover8 waypoint8)
    (communicate_rock_data rover8 waypoint8)
    (communicate_soil_data rover8 waypoint9)
    (communicate_rock_data rover8 waypoint9)
    (communicate_soil_data rover8 waypoint10)
    (communicate_rock_data rover8 waypoint10)
    (communicate_soil_data rover8 waypoint11)
    (communicate_rock_data rover8 waypoint11)
    (communicate_soil_data rover8 waypoint12)
    (communicate_rock_data rover8 waypoint12)
    (communicate_soil_data rover8 waypoint13)
    (communicate_rock_data rover8 waypoint13)
    (communicate_soil_data rover8 waypoint14)
    (communicate_rock_data rover8 waypoint14)
    (communicate_soil_data rover8 waypoint15)
    (communicate_rock_data rover8 waypoint15)
    (communicate_soil_data rover8 waypoint16)
    (communicate_rock_data rover8 waypoint16)
    (communicate_soil_data rover8 waypoint17)
    (communicate_rock_data rover8 waypoint17)
    (communicate_soil_data rover8 waypoint18)
    (communicate_rock_data rover8 waypoint18)
    (communicate_soil_data rover8 waypoint19)
    (communicate_rock_data rover8 waypoint19)
    (communicate_soil_data rover8 waypoint20)
    (communicate_rock_data rover8 waypoint20)
    (communicate_soil_data rover8 waypoint21)
    (communicate_rock_data rover8 waypoint21)
    (communicate_soil_data rover8 waypoint22)
    (communicate_rock_data rover8 waypoint22)
    (communicate_soil_data rover8 waypoint23)
    (communicate_rock_data rover8 waypoint23)
    (communicate_soil_data rover8 waypoint24)
    (communicate_rock_data rover8 waypoint24)
    (communicate_soil_data rover8 waypoint25)
    (communicate_rock_data rover8 waypoint25)
    (communicate_soil_data rover8 waypoint26)
    (communicate_rock_data rover8 waypoint26)
    (communicate_soil_data rover8 waypoint27)
    (communicate_rock_data rover8 waypoint27)
    (communicate_soil_data rover8 waypoint28)
    (communicate_rock_data rover8 waypoint28)
    (communicate_soil_data rover8 waypoint29)
    (communicate_rock_data rover8 waypoint29)
    (communicate_soil_data rover8 waypoint30)
    (communicate_rock_data rover8 waypoint30)
    (communicate_soil_data rover8 waypoint31)
    (communicate_rock_data rover8 waypoint31)
    (communicate_soil_data rover8 waypoint32)
    (communicate_rock_data rover8 waypoint32)
    (communicate_soil_data rover8 waypoint33)
    (communicate_rock_data rover8 waypoint33)
    (communicate_soil_data rover8 waypoint34)
    (communicate_rock_data rover8 waypoint34)
    (communicate_soil_data rover8 waypoint35)
    (communicate_rock_data rover8 waypoint35)
    (communicate_soil_data rover8 waypoint36)
    (communicate_rock_data rover8 waypoint36)
    (communicate_soil_data rover8 waypoint37)
    (communicate_rock_data rover8 waypoint37)
    (communicate_soil_data rover8 waypoint38)
    (communicate_rock_data rover8 waypoint38)
    (communicate_soil_data rover8 waypoint39)
    (communicate_rock_data rover8 waypoint39)
    (communicate_soil_data rover9 waypoint0)
    (communicate_rock_data rover9 waypoint0)
    (communicate_soil_data rover9 waypoint1)
    (communicate_rock_data rover9 waypoint1)
    (communicate_soil_data rover9 waypoint2)
    (communicate_rock_data rover9 waypoint2)
    (communicate_soil_data rover9 waypoint3)
    (communicate_rock_data rover9 waypoint3)
    (communicate_soil_data rover9 waypoint4)
    (communicate_rock_data rover9 waypoint4)
    (communicate_soil_data rover9 waypoint5)
    (communicate_rock_data rover9 waypoint5)
    (communicate_soil_data rover9 waypoint6)
    (communicate_rock_data rover9 waypoint6)
    (communicate_soil_data rover9 waypoint7)
    (communicate_rock_data rover9 waypoint7)
    (communicate_soil_data rover9 waypoint8)
    (communicate_rock_data rover9 waypoint8)
    (communicate_soil_data rover9 waypoint9)
    (communicate_rock_data rover9 waypoint9)
    (communicate_soil_data rover9 waypoint10)
    (communicate_rock_data rover9 waypoint10)
    (communicate_soil_data rover9 waypoint11)
    (communicate_rock_data rover9 waypoint11)
    (communicate_soil_data rover9 waypoint12)
    (communicate_rock_data rover9 waypoint12)
    (communicate_soil_data rover9 waypoint13)
    (communicate_rock_data rover9 waypoint13)
    (communicate_soil_data rover9 waypoint14)
    (communicate_rock_data rover9 waypoint14)
    (communicate_soil_data rover9 waypoint15)
    (communicate_rock_data rover9 waypoint15)
    (communicate_soil_data rover9 waypoint16)
    (communicate_rock_data rover9 waypoint16)
    (communicate_soil_data rover9 waypoint17)
    (communicate_rock_data rover9 waypoint17)
    (communicate_soil_data rover9 waypoint18)
    (communicate_rock_data rover9 waypoint18)
    (communicate_soil_data rover9 waypoint19)
    (communicate_rock_data rover9 waypoint19)
    (communicate_soil_data rover9 waypoint20)
    (communicate_rock_data rover9 waypoint20)
    (communicate_soil_data rover9 waypoint21)
    (communicate_rock_data rover9 waypoint21)
    (communicate_soil_data rover9 waypoint22)
    (communicate_rock_data rover9 waypoint22)
    (communicate_soil_data rover9 waypoint23)
    (communicate_rock_data rover9 waypoint23)
    (communicate_soil_data rover9 waypoint24)
    (communicate_rock_data rover9 waypoint24)
    (communicate_soil_data rover9 waypoint25)
    (communicate_rock_data rover9 waypoint25)
    (communicate_soil_data rover9 waypoint26)
    (communicate_rock_data rover9 waypoint26)
    (communicate_soil_data rover9 waypoint27)
    (communicate_rock_data rover9 waypoint27)
    (communicate_soil_data rover9 waypoint28)
    (communicate_rock_data rover9 waypoint28)
    (communicate_soil_data rover9 waypoint29)
    (communicate_rock_data rover9 waypoint29)
    (communicate_soil_data rover9 waypoint30)
    (communicate_rock_data rover9 waypoint30)
    (communicate_soil_data rover9 waypoint31)
    (communicate_rock_data rover9 waypoint31)
    (communicate_soil_data rover9 waypoint32)
    (communicate_rock_data rover9 waypoint32)
    (communicate_soil_data rover9 waypoint33)
    (communicate_rock_data rover9 waypoint33)
    (communicate_soil_data rover9 waypoint34)
    (communicate_rock_data rover9 waypoint34)
    (communicate_soil_data rover9 waypoint35)
    (communicate_rock_data rover9 waypoint35)
    (communicate_soil_data rover9 waypoint36)
    (communicate_rock_data rover9 waypoint36)
    (communicate_soil_data rover9 waypoint37)
    (communicate_rock_data rover9 waypoint37)
    (communicate_soil_data rover9 waypoint38)
    (communicate_rock_data rover9 waypoint38)
    (communicate_soil_data rover9 waypoint39)
    (communicate_rock_data rover9 waypoint39)
    (communicate_image_data rover0 objective0 colour)
    (communicate_image_data rover0 objective0 high_res)
    (communicate_image_data rover0 objective0 low_res)
    (communicate_image_data rover0 objective1 colour)
    (communicate_image_data rover0 objective1 high_res)
    (communicate_image_data rover0 objective1 low_res)
    (communicate_image_data rover0 objective2 colour)
    (communicate_image_data rover0 objective2 high_res)
    (communicate_image_data rover0 objective2 low_res)
    (communicate_image_data rover0 objective3 colour)
    (communicate_image_data rover0 objective3 high_res)
    (communicate_image_data rover0 objective3 low_res)
    (communicate_image_data rover0 objective4 colour)
    (communicate_image_data rover0 objective4 high_res)
    (communicate_image_data rover0 objective4 low_res)
    (communicate_image_data rover0 objective5 colour)
    (communicate_image_data rover0 objective5 high_res)
    (communicate_image_data rover0 objective5 low_res)
    (communicate_image_data rover0 objective6 colour)
    (communicate_image_data rover0 objective6 high_res)
    (communicate_image_data rover0 objective6 low_res)
    (communicate_image_data rover0 objective7 colour)
    (communicate_image_data rover0 objective7 high_res)
    (communicate_image_data rover0 objective7 low_res)
    (communicate_image_data rover1 objective0 colour)
    (communicate_image_data rover1 objective0 high_res)
    (communicate_image_data rover1 objective0 low_res)
    (communicate_image_data rover1 objective1 colour)
    (communicate_image_data rover1 objective1 high_res)
    (communicate_image_data rover1 objective1 low_res)
    (communicate_image_data rover1 objective2 colour)
    (communicate_image_data rover1 objective2 high_res)
    (communicate_image_data rover1 objective2 low_res)
    (communicate_image_data rover1 objective3 colour)
    (communicate_image_data rover1 objective3 high_res)
    (communicate_image_data rover1 objective3 low_res)
    (communicate_image_data rover1 objective4 colour)
    (communicate_image_data rover1 objective4 high_res)
    (communicate_image_data rover1 objective4 low_res)
    (communicate_image_data rover1 objective5 colour)
    (communicate_image_data rover1 objective5 high_res)
    (communicate_image_data rover1 objective5 low_res)
    (communicate_image_data rover1 objective6 colour)
    (communicate_image_data rover1 objective6 high_res)
    (communicate_image_data rover1 objective6 low_res)
    (communicate_image_data rover1 objective7 colour)
    (communicate_image_data rover1 objective7 high_res)
    (communicate_image_data rover1 objective7 low_res)
    (communicate_image_data rover2 objective0 colour)
    (communicate_image_data rover2 objective0 high_res)
    (communicate_image_data rover2 objective0 low_res)
    (communicate_image_data rover2 objective1 colour)
    (communicate_image_data rover2 objective1 high_res)
    (communicate_image_data rover2 objective1 low_res)
    (communicate_image_data rover2 objective2 colour)
    (communicate_image_data rover2 objective2 high_res)
    (communicate_image_data rover2 objective2 low_res)
    (communicate_image_data rover2 objective3 colour)
    (communicate_image_data rover2 objective3 high_res)
    (communicate_image_data rover2 objective3 low_res)
    (communicate_image_data rover2 objective4 colour)
    (communicate_image_data rover2 objective4 high_res)
    (communicate_image_data rover2 objective4 low_res)
    (communicate_image_data rover2 objective5 colour)
    (communicate_image_data rover2 objective5 high_res)
    (communicate_image_data rover2 objective5 low_res)
    (communicate_image_data rover2 objective6 colour)
    (communicate_image_data rover2 objective6 high_res)
    (communicate_image_data rover2 objective6 low_res)
    (communicate_image_data rover2 objective7 colour)
    (communicate_image_data rover2 objective7 high_res)
    (communicate_image_data rover2 objective7 low_res)
    (communicate_image_data rover3 objective0 colour)
    (communicate_image_data rover3 objective0 high_res)
    (communicate_image_data rover3 objective0 low_res)
    (communicate_image_data rover3 objective1 colour)
    (communicate_image_data rover3 objective1 high_res)
    (communicate_image_data rover3 objective1 low_res)
    (communicate_image_data rover3 objective2 colour)
    (communicate_image_data rover3 objective2 high_res)
    (communicate_image_data rover3 objective2 low_res)
    (communicate_image_data rover3 objective3 colour)
    (communicate_image_data rover3 objective3 high_res)
    (communicate_image_data rover3 objective3 low_res)
    (communicate_image_data rover3 objective4 colour)
    (communicate_image_data rover3 objective4 high_res)
    (communicate_image_data rover3 objective4 low_res)
    (communicate_image_data rover3 objective5 colour)
    (communicate_image_data rover3 objective5 high_res)
    (communicate_image_data rover3 objective5 low_res)
    (communicate_image_data rover3 objective6 colour)
    (communicate_image_data rover3 objective6 high_res)
    (communicate_image_data rover3 objective6 low_res)
    (communicate_image_data rover3 objective7 colour)
    (communicate_image_data rover3 objective7 high_res)
    (communicate_image_data rover3 objective7 low_res)
    (communicate_image_data rover4 objective0 colour)
    (communicate_image_data rover4 objective0 high_res)
    (communicate_image_data rover4 objective0 low_res)
    (communicate_image_data rover4 objective1 colour)
    (communicate_image_data rover4 objective1 high_res)
    (communicate_image_data rover4 objective1 low_res)
    (communicate_image_data rover4 objective2 colour)
    (communicate_image_data rover4 objective2 high_res)
    (communicate_image_data rover4 objective2 low_res)
    (communicate_image_data rover4 objective3 colour)
    (communicate_image_data rover4 objective3 high_res)
    (communicate_image_data rover4 objective3 low_res)
    (communicate_image_data rover4 objective4 colour)
    (communicate_image_data rover4 objective4 high_res)
    (communicate_image_data rover4 objective4 low_res)
    (communicate_image_data rover4 objective5 colour)
    (communicate_image_data rover4 objective5 high_res)
    (communicate_image_data rover4 objective5 low_res)
    (communicate_image_data rover4 objective6 colour)
    (communicate_image_data rover4 objective6 high_res)
    (communicate_image_data rover4 objective6 low_res)
    (communicate_image_data rover4 objective7 colour)
    (communicate_image_data rover4 objective7 high_res)
    (communicate_image_data rover4 objective7 low_res)
    (communicate_image_data rover5 objective0 colour)
    (communicate_image_data rover5 objective0 high_res)
    (communicate_image_data rover5 objective0 low_res)
    (communicate_image_data rover5 objective1 colour)
    (communicate_image_data rover5 objective1 high_res)
    (communicate_image_data rover5 objective1 low_res)
    (communicate_image_data rover5 objective2 colour)
    (communicate_image_data rover5 objective2 high_res)
    (communicate_image_data rover5 objective2 low_res)
    (communicate_image_data rover5 objective3 colour)
    (communicate_image_data rover5 objective3 high_res)
    (communicate_image_data rover5 objective3 low_res)
    (communicate_image_data rover5 objective4 colour)
    (communicate_image_data rover5 objective4 high_res)
    (communicate_image_data rover5 objective4 low_res)
    (communicate_image_data rover5 objective5 colour)
    (communicate_image_data rover5 objective5 high_res)
    (communicate_image_data rover5 objective5 low_res)
    (communicate_image_data rover5 objective6 colour)
    (communicate_image_data rover5 objective6 high_res)
    (communicate_image_data rover5 objective6 low_res)
    (communicate_image_data rover5 objective7 colour)
    (communicate_image_data rover5 objective7 high_res)
    (communicate_image_data rover5 objective7 low_res)
    (communicate_image_data rover6 objective0 colour)
    (communicate_image_data rover6 objective0 high_res)
    (communicate_image_data rover6 objective0 low_res)
    (communicate_image_data rover6 objective1 colour)
    (communicate_image_data rover6 objective1 high_res)
    (communicate_image_data rover6 objective1 low_res)
    (communicate_image_data rover6 objective2 colour)
    (communicate_image_data rover6 objective2 high_res)
    (communicate_image_data rover6 objective2 low_res)
    (communicate_image_data rover6 objective3 colour)
    (communicate_image_data rover6 objective3 high_res)
    (communicate_image_data rover6 objective3 low_res)
    (communicate_image_data rover6 objective4 colour)
    (communicate_image_data rover6 objective4 high_res)
    (communicate_image_data rover6 objective4 low_res)
    (communicate_image_data rover6 objective5 colour)
    (communicate_image_data rover6 objective5 high_res)
    (communicate_image_data rover6 objective5 low_res)
    (communicate_image_data rover6 objective6 colour)
    (communicate_image_data rover6 objective6 high_res)
    (communicate_image_data rover6 objective6 low_res)
    (communicate_image_data rover6 objective7 colour)
    (communicate_image_data rover6 objective7 high_res)
    (communicate_image_data rover6 objective7 low_res)
    (communicate_image_data rover7 objective0 colour)
    (communicate_image_data rover7 objective0 high_res)
    (communicate_image_data rover7 objective0 low_res)
    (communicate_image_data rover7 objective1 colour)
    (communicate_image_data rover7 objective1 high_res)
    (communicate_image_data rover7 objective1 low_res)
    (communicate_image_data rover7 objective2 colour)
    (communicate_image_data rover7 objective2 high_res)
    (communicate_image_data rover7 objective2 low_res)
    (communicate_image_data rover7 objective3 colour)
    (communicate_image_data rover7 objective3 high_res)
    (communicate_image_data rover7 objective3 low_res)
    (communicate_image_data rover7 objective4 colour)
    (communicate_image_data rover7 objective4 high_res)
    (communicate_image_data rover7 objective4 low_res)
    (communicate_image_data rover7 objective5 colour)
    (communicate_image_data rover7 objective5 high_res)
    (communicate_image_data rover7 objective5 low_res)
    (communicate_image_data rover7 objective6 colour)
    (communicate_image_data rover7 objective6 high_res)
    (communicate_image_data rover7 objective6 low_res)
    (communicate_image_data rover7 objective7 colour)
    (communicate_image_data rover7 objective7 high_res)
    (communicate_image_data rover7 objective7 low_res)
    (communicate_image_data rover8 objective0 colour)
    (communicate_image_data rover8 objective0 high_res)
    (communicate_image_data rover8 objective0 low_res)
    (communicate_image_data rover8 objective1 colour)
    (communicate_image_data rover8 objective1 high_res)
    (communicate_image_data rover8 objective1 low_res)
    (communicate_image_data rover8 objective2 colour)
    (communicate_image_data rover8 objective2 high_res)
    (communicate_image_data rover8 objective2 low_res)
    (communicate_image_data rover8 objective3 colour)
    (communicate_image_data rover8 objective3 high_res)
    (communicate_image_data rover8 objective3 low_res)
    (communicate_image_data rover8 objective4 colour)
    (communicate_image_data rover8 objective4 high_res)
    (communicate_image_data rover8 objective4 low_res)
    (communicate_image_data rover8 objective5 colour)
    (communicate_image_data rover8 objective5 high_res)
    (communicate_image_data rover8 objective5 low_res)
    (communicate_image_data rover8 objective6 colour)
    (communicate_image_data rover8 objective6 high_res)
    (communicate_image_data rover8 objective6 low_res)
    (communicate_image_data rover8 objective7 colour)
    (communicate_image_data rover8 objective7 high_res)
    (communicate_image_data rover8 objective7 low_res)
    (communicate_image_data rover9 objective0 colour)
    (communicate_image_data rover9 objective0 high_res)
    (communicate_image_data rover9 objective0 low_res)
    (communicate_image_data rover9 objective1 colour)
    (communicate_image_data rover9 objective1 high_res)
    (communicate_image_data rover9 objective1 low_res)
    (communicate_image_data rover9 objective2 colour)
    (communicate_image_data rover9 objective2 high_res)
    (communicate_image_data rover9 objective2 low_res)
    (communicate_image_data rover9 objective3 colour)
    (communicate_image_data rover9 objective3 high_res)
    (communicate_image_data rover9 objective3 low_res)
    (communicate_image_data rover9 objective4 colour)
    (communicate_image_data rover9 objective4 high_res)
    (communicate_image_data rover9 objective4 low_res)
    (communicate_image_data rover9 objective5 colour)
    (communicate_image_data rover9 objective5 high_res)
    (communicate_image_data rover9 objective5 low_res)
    (communicate_image_data rover9 objective6 colour)
    (communicate_image_data rover9 objective6 high_res)
    (communicate_image_data rover9 objective6 low_res)
    (communicate_image_data rover9 objective7 colour)
    (communicate_image_data rover9 objective7 high_res)
    (communicate_image_data rover9 objective7 low_res)
    )

(:goal (and
(communicated_soil_data waypoint10)
(communicated_soil_data waypoint28)
(communicated_soil_data waypoint2)
(communicated_soil_data waypoint24)
(communicated_soil_data waypoint15)
(communicated_soil_data waypoint17)
(communicated_soil_data waypoint3)
(communicated_soil_data waypoint0)
(communicated_rock_data waypoint4)
(communicated_rock_data waypoint17)
(communicated_rock_data waypoint33)
(communicated_rock_data waypoint24)
(communicated_rock_data waypoint27)
(communicated_rock_data waypoint18)
(communicated_image_data objective7 high_res)
(communicated_image_data objective5 low_res)
(communicated_image_data objective4 low_res)
(communicated_image_data objective4 high_res)
(communicated_image_data objective2 low_res)
	)
)
)
