; Problem taken from https://github.com/AI-Planning/classical-domains

(define (problem roverprob7652) (:domain Rover)
(:objects
	general - Lander
	colour high_res low_res - Mode
	rover0 rover1 rover2 rover3 rover4 rover5 rover6 rover7 rover8 rover9 - Rover
	rover0store rover1store rover2store rover3store rover4store rover5store rover6store rover7store rover8store rover9store - Store
	waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 waypoint11 waypoint12 waypoint13 waypoint14 waypoint15 waypoint16 waypoint17 waypoint18 waypoint19 waypoint20 waypoint21 waypoint22 waypoint23 waypoint24 waypoint25 waypoint26 waypoint27 waypoint28 waypoint29 waypoint30 waypoint31 waypoint32 waypoint33 waypoint34 - Waypoint
	camera0 camera1 camera2 camera3 camera4 camera5 camera6 camera7 camera8 camera9 camera10 camera11 camera12 - Camera
	objective0 objective1 objective2 objective3 objective4 objective5 objective6 objective7 - Objective
	)
(:init
	(at_soil_sample waypoint0)
	(at_rock_sample waypoint0)
	(at_soil_sample waypoint1)
	(at_soil_sample waypoint3)
	(at_rock_sample waypoint3)
	(at_soil_sample waypoint4)
	(at_rock_sample waypoint4)
	(at_rock_sample waypoint5)
	(at_soil_sample waypoint6)
	(at_soil_sample waypoint8)
	(at_rock_sample waypoint8)
	(at_rock_sample waypoint9)
	(at_soil_sample waypoint10)
	(at_rock_sample waypoint10)
	(at_rock_sample waypoint11)
	(at_soil_sample waypoint12)
	(at_soil_sample waypoint14)
	(at_rock_sample waypoint14)
	(at_rock_sample waypoint15)
	(at_soil_sample waypoint16)
	(at_soil_sample waypoint18)
	(at_rock_sample waypoint18)
	(at_soil_sample waypoint19)
	(at_soil_sample waypoint20)
	(at_soil_sample waypoint21)
	(at_rock_sample waypoint21)
	(at_rock_sample waypoint23)
	(at_soil_sample waypoint24)
	(at_soil_sample waypoint25)
	(at_rock_sample waypoint26)
	(at_soil_sample waypoint27)
	(at_rock_sample waypoint27)
	(at_rock_sample waypoint28)
	(at_rock_sample waypoint29)
	(at_soil_sample waypoint32)
	(at_rock_sample waypoint32)
	(at_lander general waypoint6)
	(channel_free general)
	(at rover0 waypoint22)
	(store_of rover0store rover0)
	(empty rover0store)
	(equipped_for_soil_analysis rover0)
	(equipped_for_imaging rover0)
	(at rover1 waypoint19)
	(store_of rover1store rover1)
	(empty rover1store)
	(equipped_for_rock_analysis rover1)
	(equipped_for_imaging rover1)
	(at rover2 waypoint32)
	(store_of rover2store rover2)
	(empty rover2store)
	(equipped_for_soil_analysis rover2)
	(at rover3 waypoint17)
	(store_of rover3store rover3)
	(empty rover3store)
	(equipped_for_soil_analysis rover3)
	(equipped_for_imaging rover3)
	(at rover4 waypoint23)
	(store_of rover4store rover4)
	(empty rover4store)
	(equipped_for_soil_analysis rover4)
	(equipped_for_imaging rover4)
	(at rover5 waypoint20)
	(store_of rover5store rover5)
	(empty rover5store)
	(equipped_for_rock_analysis rover5)
	(at rover6 waypoint9)
	(store_of rover6store rover6)
	(empty rover6store)
	(equipped_for_soil_analysis rover6)
	(equipped_for_imaging rover6)
	(at rover7 waypoint6)
	(store_of rover7store rover7)
	(empty rover7store)
	(equipped_for_soil_analysis rover7)
	(equipped_for_imaging rover7)
	(at rover8 waypoint29)
	(store_of rover8store rover8)
	(empty rover8store)
	(equipped_for_rock_analysis rover8)
	(equipped_for_imaging rover8)
	(at rover9 waypoint20)
	(store_of rover9store rover9)
	(empty rover9store)
	(equipped_for_imaging rover9)
	(on_board camera0 rover8)
	(calibration_target camera0 objective4)
	(supports camera0 high_res)
	(supports camera0 low_res)
	(on_board camera1 rover3)
	(calibration_target camera1 objective6)
	(supports camera1 colour)
	(on_board camera2 rover9)
	(calibration_target camera2 objective2)
	(supports camera2 colour)
	(supports camera2 high_res)
	(on_board camera3 rover8)
	(calibration_target camera3 objective7)
	(supports camera3 colour)
	(supports camera3 low_res)
	(on_board camera4 rover6)
	(calibration_target camera4 objective4)
	(supports camera4 high_res)
	(supports camera4 low_res)
	(on_board camera5 rover7)
	(calibration_target camera5 objective3)
	(supports camera5 colour)
	(supports camera5 low_res)
	(on_board camera6 rover3)
	(calibration_target camera6 objective1)
	(supports camera6 colour)
	(supports camera6 high_res)
	(supports camera6 low_res)
	(on_board camera7 rover3)
	(calibration_target camera7 objective3)
	(supports camera7 high_res)
	(supports camera7 low_res)
	(on_board camera8 rover7)
	(calibration_target camera8 objective1)
	(supports camera8 colour)
	(on_board camera9 rover7)
	(calibration_target camera9 objective7)
	(supports camera9 low_res)
	(on_board camera10 rover0)
	(calibration_target camera10 objective2)
	(supports camera10 high_res)
	(supports camera10 low_res)
	(on_board camera11 rover1)
	(calibration_target camera11 objective2)
	(supports camera11 colour)
	(supports camera11 high_res)
	(on_board camera12 rover4)
	(calibration_target camera12 objective0)
	(supports camera12 colour)
	(supports camera12 high_res)
)

(:goal (and
(communicated_soil_data waypoint25)
(communicated_soil_data waypoint3)
(communicated_soil_data waypoint14)
(communicated_soil_data waypoint21)
(communicated_soil_data waypoint32)
(communicated_soil_data waypoint10)
(communicated_soil_data waypoint8)
(communicated_soil_data waypoint0)
(communicated_rock_data waypoint32)
(communicated_rock_data waypoint29)
(communicated_rock_data waypoint28)
(communicated_rock_data waypoint11)
(communicated_rock_data waypoint10)
(communicated_rock_data waypoint9)
(communicated_rock_data waypoint4)
(communicated_rock_data waypoint26)
(communicated_image_data objective7 colour)
(communicated_image_data objective5 high_res)
(communicated_image_data objective5 colour)
(communicated_image_data objective0 high_res)
	)
)
)
