; Problem taken from https://github.com/AI-Planning/classical-domains

(define (problem roverprob1234) (:domain Rover)
(:objects
	general - Lander
	colour high_res low_res - Mode
	rover0 rover1 rover2 rover3 rover4 rover5 rover6 rover7 - Rover
	rover0store rover1store rover2store rover3store rover4store rover5store rover6store rover7store - Store
	waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 waypoint11 waypoint12 waypoint13 waypoint14 waypoint15 waypoint16 waypoint17 waypoint18 waypoint19 waypoint20 waypoint21 waypoint22 waypoint23 waypoint24 waypoint25 waypoint26 waypoint27 waypoint28 waypoint29 waypoint30 waypoint31 waypoint32 waypoint33 waypoint34 waypoint35 waypoint36 waypoint37 waypoint38 waypoint39 - Waypoint
	camera0 camera1 camera2 camera3 camera4 camera5 camera6 camera7 camera8 - Camera
	objective0 objective1 objective2 objective3 objective4 objective5 objective6 objective7 - Objective
	)
(:init
	(at_rock_sample waypoint0)
	(at_soil_sample waypoint1)
	(at_soil_sample waypoint2)
	(at_soil_sample waypoint3)
	(at_rock_sample waypoint3)
	(at_rock_sample waypoint4)
	(at_soil_sample waypoint5)
	(at_soil_sample waypoint7)
	(at_rock_sample waypoint7)
	(at_soil_sample waypoint8)
	(at_soil_sample waypoint10)
	(at_soil_sample waypoint11)
	(at_rock_sample waypoint11)
	(at_soil_sample waypoint12)
	(at_rock_sample waypoint12)
	(at_soil_sample waypoint13)
	(at_soil_sample waypoint14)
	(at_rock_sample waypoint15)
	(at_soil_sample waypoint18)
	(at_rock_sample waypoint18)
	(at_soil_sample waypoint20)
	(at_rock_sample waypoint20)
	(at_soil_sample waypoint21)
	(at_rock_sample waypoint21)
	(at_soil_sample waypoint22)
	(at_soil_sample waypoint24)
	(at_soil_sample waypoint26)
	(at_soil_sample waypoint27)
	(at_soil_sample waypoint30)
	(at_rock_sample waypoint31)
	(at_rock_sample waypoint32)
	(at_rock_sample waypoint33)
	(at_soil_sample waypoint34)
	(at_rock_sample waypoint34)
	(at_soil_sample waypoint36)
	(at_rock_sample waypoint36)
	(at_rock_sample waypoint37)
	(at_rock_sample waypoint38)
	(at_soil_sample waypoint39)
	(at_lander general waypoint3)
	(channel_free general)
	(at rover0 waypoint21)
	(store_of rover0store rover0)
	(empty rover0store)
	(equipped_for_rock_analysis rover0)
	(equipped_for_imaging rover0)
	(at rover1 waypoint30)
	(store_of rover1store rover1)
	(empty rover1store)
	(equipped_for_soil_analysis rover1)
	(equipped_for_rock_analysis rover1)
	(equipped_for_imaging rover1)
	(at rover2 waypoint10)
	(store_of rover2store rover2)
	(empty rover2store)
	(equipped_for_rock_analysis rover2)
	(equipped_for_imaging rover2)
	(at rover3 waypoint0)
	(store_of rover3store rover3)
	(empty rover3store)
	(equipped_for_rock_analysis rover3)
	(equipped_for_imaging rover3)
	(at rover4 waypoint38)
	(store_of rover4store rover4)
	(empty rover4store)
	(equipped_for_rock_analysis rover4)
	(at rover5 waypoint29)
	(store_of rover5store rover5)
	(empty rover5store)
	(equipped_for_soil_analysis rover5)
	(equipped_for_imaging rover5)
	(at rover6 waypoint26)
	(store_of rover6store rover6)
	(empty rover6store)
	(equipped_for_rock_analysis rover6)
	(equipped_for_imaging rover6)
	(at rover7 waypoint34)
	(store_of rover7store rover7)
	(empty rover7store)
	(equipped_for_soil_analysis rover7)
	(equipped_for_imaging rover7)
	(on_board camera0 rover0)
	(calibration_target camera0 objective7)
	(supports camera0 colour)
	(on_board camera1 rover7)
	(calibration_target camera1 objective2)
	(supports camera1 colour)
	(supports camera1 high_res)
	(supports camera1 low_res)
	(on_board camera2 rover6)
	(calibration_target camera2 objective6)
	(supports camera2 colour)
	(supports camera2 low_res)
	(on_board camera3 rover3)
	(calibration_target camera3 objective0)
	(supports camera3 colour)
	(on_board camera4 rover5)
	(calibration_target camera4 objective6)
	(supports camera4 colour)
	(on_board camera5 rover1)
	(calibration_target camera5 objective4)
	(supports camera5 colour)
	(supports camera5 low_res)
	(on_board camera6 rover3)
	(calibration_target camera6 objective1)
	(supports camera6 colour)
	(on_board camera7 rover3)
	(calibration_target camera7 objective7)
	(supports camera7 low_res)
	(on_board camera8 rover2)
	(calibration_target camera8 objective2)
	(supports camera8 colour)
)

(:goal (and
(communicated_soil_data waypoint10)
(communicated_soil_data waypoint39)
(communicated_soil_data waypoint34)
(communicated_soil_data waypoint11)
(communicated_soil_data waypoint7)
(communicated_soil_data waypoint12)
(communicated_soil_data waypoint14)
(communicated_soil_data waypoint36)
(communicated_soil_data waypoint22)
(communicated_rock_data waypoint4)
(communicated_rock_data waypoint18)
(communicated_rock_data waypoint36)
(communicated_rock_data waypoint34)
(communicated_rock_data waypoint3)
(communicated_rock_data waypoint37)
(communicated_rock_data waypoint20)
(communicated_rock_data waypoint0)
(communicated_rock_data waypoint32)
(communicated_rock_data waypoint21)
(communicated_image_data objective4 colour)
(communicated_image_data objective1 low_res)
	)
)
)
