; Problem taken from https://github.com/AI-Planning/classical-domains

(define (problem roverprob2006) (:domain Rover)
(:objects
	general - Lander
	colour high_res low_res - Mode
	rover0 rover1 rover2 rover3 rover4 rover5 rover6 rover7 rover8 rover9 rover10 rover11 - Rover
	rover0store rover1store rover2store rover3store rover4store rover5store rover6store rover7store rover8store rover9store rover10store rover11store - Store
	waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 waypoint11 waypoint12 waypoint13 waypoint14 waypoint15 waypoint16 waypoint17 waypoint18 waypoint19 waypoint20 waypoint21 waypoint22 waypoint23 waypoint24 waypoint25 waypoint26 waypoint27 waypoint28 waypoint29 waypoint30 waypoint31 waypoint32 waypoint33 waypoint34 waypoint35 waypoint36 waypoint37 waypoint38 waypoint39 waypoint40 waypoint41 waypoint42 waypoint43 waypoint44 waypoint45 waypoint46 waypoint47 waypoint48 waypoint49 waypoint50 waypoint51 waypoint52 waypoint53 waypoint54 waypoint55 waypoint56 waypoint57 waypoint58 waypoint59 - Waypoint
	camera0 camera1 camera2 camera3 camera4 camera5 camera6 camera7 camera8 camera9 camera10 camera11 camera12 camera13 - Camera
	objective0 objective1 objective2 objective3 objective4 objective5 objective6 objective7 objective8 objective9 objective10 - Objective
	)
(:init
	(at_rock_sample waypoint1)
	(at_rock_sample waypoint2)
	(at_soil_sample waypoint3)
	(at_rock_sample waypoint4)
	(at_soil_sample waypoint6)
	(at_soil_sample waypoint7)
	(at_soil_sample waypoint8)
	(at_rock_sample waypoint11)
	(at_soil_sample waypoint12)
	(at_rock_sample waypoint12)
	(at_soil_sample waypoint13)
	(at_rock_sample waypoint13)
	(at_rock_sample waypoint16)
	(at_rock_sample waypoint17)
	(at_rock_sample waypoint18)
	(at_rock_sample waypoint21)
	(at_soil_sample waypoint22)
	(at_rock_sample waypoint22)
	(at_rock_sample waypoint24)
	(at_soil_sample waypoint25)
	(at_soil_sample waypoint27)
	(at_soil_sample waypoint28)
	(at_rock_sample waypoint28)
	(at_rock_sample waypoint29)
	(at_soil_sample waypoint30)
	(at_rock_sample waypoint30)
	(at_soil_sample waypoint31)
	(at_rock_sample waypoint31)
	(at_rock_sample waypoint32)
	(at_soil_sample waypoint33)
	(at_soil_sample waypoint34)
	(at_rock_sample waypoint35)
	(at_soil_sample waypoint36)
	(at_rock_sample waypoint37)
	(at_soil_sample waypoint38)
	(at_rock_sample waypoint38)
	(at_soil_sample waypoint39)
	(at_rock_sample waypoint39)
	(at_rock_sample waypoint41)
	(at_rock_sample waypoint42)
	(at_rock_sample waypoint43)
	(at_soil_sample waypoint44)
	(at_rock_sample waypoint45)
	(at_soil_sample waypoint46)
	(at_soil_sample waypoint47)
	(at_soil_sample waypoint48)
	(at_rock_sample waypoint48)
	(at_soil_sample waypoint49)
	(at_rock_sample waypoint49)
	(at_rock_sample waypoint50)
	(at_soil_sample waypoint51)
	(at_rock_sample waypoint51)
	(at_soil_sample waypoint52)
	(at_soil_sample waypoint53)
	(at_rock_sample waypoint53)
	(at_soil_sample waypoint54)
	(at_rock_sample waypoint54)
	(at_rock_sample waypoint55)
	(at_rock_sample waypoint56)
	(at_soil_sample waypoint57)
	(at_soil_sample waypoint58)
	(at_rock_sample waypoint58)
	(at_soil_sample waypoint59)
	(at_rock_sample waypoint59)
	(at_lander general waypoint26)
	(channel_free general)
	(at rover0 waypoint11)
	(store_of rover0store rover0)
	(empty rover0store)
	(equipped_for_rock_analysis rover0)
	(equipped_for_imaging rover0)
	(at rover1 waypoint5)
	(store_of rover1store rover1)
	(empty rover1store)
	(equipped_for_soil_analysis rover1)
	(equipped_for_imaging rover1)
	(at rover2 waypoint56)
	(store_of rover2store rover2)
	(empty rover2store)
	(equipped_for_rock_analysis rover2)
	(equipped_for_imaging rover2)
	(at rover3 waypoint40)
	(store_of rover3store rover3)
	(empty rover3store)
	(equipped_for_imaging rover3)
	(at rover4 waypoint49)
	(store_of rover4store rover4)
	(empty rover4store)
	(equipped_for_rock_analysis rover4)
	(at rover5 waypoint45)
	(store_of rover5store rover5)
	(empty rover5store)
	(equipped_for_soil_analysis rover5)
	(equipped_for_rock_analysis rover5)
	(equipped_for_imaging rover5)
	(at rover6 waypoint22)
	(store_of rover6store rover6)
	(empty rover6store)
	(equipped_for_soil_analysis rover6)
	(equipped_for_imaging rover6)
	(at rover7 waypoint31)
	(store_of rover7store rover7)
	(empty rover7store)
	(equipped_for_rock_analysis rover7)
	(at rover8 waypoint27)
	(store_of rover8store rover8)
	(empty rover8store)
	(equipped_for_rock_analysis rover8)
	(equipped_for_imaging rover8)
	(at rover9 waypoint38)
	(store_of rover9store rover9)
	(empty rover9store)
	(equipped_for_soil_analysis rover9)
	(at rover10 waypoint42)
	(store_of rover10store rover10)
	(empty rover10store)
	(equipped_for_soil_analysis rover10)
	(equipped_for_imaging rover10)
	(at rover11 waypoint51)
	(store_of rover11store rover11)
	(empty rover11store)
	(equipped_for_soil_analysis rover11)
	(equipped_for_rock_analysis rover11)
	(equipped_for_imaging rover11)
	(on_board camera0 rover5)
	(calibration_target camera0 objective6)
	(supports camera0 colour)
	(on_board camera1 rover2)
	(calibration_target camera1 objective1)
	(supports camera1 high_res)
	(supports camera1 low_res)
	(on_board camera2 rover1)
	(calibration_target camera2 objective10)
	(supports camera2 colour)
	(supports camera2 low_res)
	(on_board camera3 rover6)
	(calibration_target camera3 objective9)
	(supports camera3 low_res)
	(on_board camera4 rover6)
	(calibration_target camera4 objective5)
	(supports camera4 high_res)
	(on_board camera5 rover8)
	(calibration_target camera5 objective1)
	(supports camera5 high_res)
	(supports camera5 low_res)
	(on_board camera6 rover6)
	(calibration_target camera6 objective10)
	(supports camera6 colour)
	(supports camera6 low_res)
	(on_board camera7 rover8)
	(calibration_target camera7 objective10)
	(supports camera7 colour)
	(supports camera7 low_res)
	(on_board camera8 rover8)
	(calibration_target camera8 objective2)
	(supports camera8 colour)
	(supports camera8 high_res)
	(supports camera8 low_res)
	(on_board camera9 rover2)
	(calibration_target camera9 objective0)
	(supports camera9 high_res)
	(on_board camera10 rover0)
	(calibration_target camera10 objective8)
	(supports camera10 high_res)
	(on_board camera11 rover3)
	(calibration_target camera11 objective2)
	(supports camera11 colour)
	(supports camera11 high_res)
	(on_board camera12 rover10)
	(calibration_target camera12 objective10)
	(supports camera12 colour)
	(supports camera12 low_res)
	(on_board camera13 rover11)
	(calibration_target camera13 objective9)
	(supports camera13 colour)
)

(:goal (and
(communicated_soil_data waypoint38)
(communicated_soil_data waypoint49)
(communicated_soil_data waypoint34)
(communicated_soil_data waypoint51)
(communicated_soil_data waypoint59)
(communicated_soil_data waypoint52)
(communicated_soil_data waypoint46)
(communicated_soil_data waypoint3)
(communicated_soil_data waypoint7)
(communicated_soil_data waypoint54)
(communicated_soil_data waypoint30)
(communicated_soil_data waypoint53)
(communicated_soil_data waypoint36)
(communicated_soil_data waypoint58)
(communicated_soil_data waypoint31)
(communicated_rock_data waypoint45)
(communicated_rock_data waypoint29)
(communicated_rock_data waypoint41)
(communicated_rock_data waypoint56)
(communicated_rock_data waypoint54)
(communicated_rock_data waypoint55)
(communicated_rock_data waypoint11)
(communicated_rock_data waypoint53)
(communicated_rock_data waypoint37)
(communicated_rock_data waypoint38)
(communicated_rock_data waypoint50)
(communicated_rock_data waypoint18)
(communicated_rock_data waypoint17)
(communicated_rock_data waypoint43)
(communicated_image_data objective3 low_res)
(communicated_image_data objective6 colour)
(communicated_image_data objective3 high_res)
(communicated_image_data objective9 high_res)
(communicated_image_data objective4 high_res)
(communicated_image_data objective0 colour)
	)
)
)
