; Problem taken from https://github.com/AI-Planning/classical-domains

(define (problem roverprob2006) (:domain Rover)
(:objects
	general - Lander
	colour high_res low_res - Mode
	rover0 rover1 rover2 rover3 rover4 rover5 rover6 rover7 rover8 rover9 rover10 rover11 - Rover
	rover0store rover1store rover2store rover3store rover4store rover5store rover6store rover7store rover8store rover9store rover10store rover11store - Store
	waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 waypoint11 waypoint12 waypoint13 waypoint14 waypoint15 waypoint16 waypoint17 waypoint18 waypoint19 waypoint20 waypoint21 waypoint22 waypoint23 waypoint24 waypoint25 waypoint26 waypoint27 waypoint28 waypoint29 waypoint30 waypoint31 waypoint32 waypoint33 waypoint34 waypoint35 waypoint36 waypoint37 waypoint38 waypoint39 waypoint40 waypoint41 waypoint42 waypoint43 waypoint44 waypoint45 waypoint46 waypoint47 waypoint48 waypoint49 waypoint50 waypoint51 waypoint52 waypoint53 waypoint54 waypoint55 waypoint56 waypoint57 waypoint58 waypoint59 waypoint60 waypoint61 waypoint62 waypoint63 waypoint64 - Waypoint
	camera0 camera1 camera2 camera3 camera4 camera5 camera6 camera7 camera8 camera9 camera10 camera11 - Camera
	objective0 objective1 objective2 objective3 objective4 objective5 objective6 objective7 objective8 - Objective
	)
(:init
	(at_rock_sample waypoint0)
	(at_soil_sample waypoint1)
	(at_rock_sample waypoint1)
	(at_soil_sample waypoint2)
	(at_soil_sample waypoint4)
	(at_rock_sample waypoint4)
	(at_rock_sample waypoint5)
	(at_soil_sample waypoint6)
	(at_rock_sample waypoint6)
	(at_soil_sample waypoint8)
	(at_rock_sample waypoint8)
	(at_rock_sample waypoint9)
	(at_soil_sample waypoint10)
	(at_rock_sample waypoint10)
	(at_rock_sample waypoint11)
	(at_rock_sample waypoint13)
	(at_soil_sample waypoint14)
	(at_rock_sample waypoint15)
	(at_soil_sample waypoint16)
	(at_rock_sample waypoint16)
	(at_soil_sample waypoint19)
	(at_rock_sample waypoint19)
	(at_rock_sample waypoint20)
	(at_rock_sample waypoint21)
	(at_soil_sample waypoint22)
	(at_rock_sample waypoint22)
	(at_rock_sample waypoint24)
	(at_soil_sample waypoint26)
	(at_soil_sample waypoint28)
	(at_rock_sample waypoint29)
	(at_rock_sample waypoint33)
	(at_soil_sample waypoint34)
	(at_rock_sample waypoint35)
	(at_rock_sample waypoint36)
	(at_soil_sample waypoint38)
	(at_rock_sample waypoint38)
	(at_soil_sample waypoint39)
	(at_rock_sample waypoint40)
	(at_soil_sample waypoint42)
	(at_rock_sample waypoint43)
	(at_soil_sample waypoint44)
	(at_rock_sample waypoint44)
	(at_soil_sample waypoint45)
	(at_rock_sample waypoint46)
	(at_soil_sample waypoint47)
	(at_rock_sample waypoint47)
	(at_soil_sample waypoint48)
	(at_soil_sample waypoint49)
	(at_rock_sample waypoint49)
	(at_soil_sample waypoint50)
	(at_soil_sample waypoint51)
	(at_rock_sample waypoint52)
	(at_rock_sample waypoint53)
	(at_soil_sample waypoint54)
	(at_rock_sample waypoint54)
	(at_soil_sample waypoint55)
	(at_soil_sample waypoint56)
	(at_rock_sample waypoint56)
	(at_rock_sample waypoint57)
	(at_rock_sample waypoint58)
	(at_soil_sample waypoint59)
	(at_soil_sample waypoint60)
	(at_rock_sample waypoint60)
	(at_soil_sample waypoint61)
	(at_rock_sample waypoint61)
	(at_soil_sample waypoint62)
	(at_soil_sample waypoint63)
	(at_rock_sample waypoint64)
	(at_lander general waypoint63)
	(channel_free general)
	(at rover0 waypoint19)
	(store_of rover0store rover0)
	(empty rover0store)
	(equipped_for_rock_analysis rover0)
	(equipped_for_imaging rover0)
	(at rover1 waypoint31)
	(store_of rover1store rover1)
	(empty rover1store)
	(equipped_for_soil_analysis rover1)
	(equipped_for_imaging rover1)
	(at rover2 waypoint26)
	(store_of rover2store rover2)
	(empty rover2store)
	(equipped_for_rock_analysis rover2)
	(at rover3 waypoint63)
	(store_of rover3store rover3)
	(empty rover3store)
	(equipped_for_rock_analysis rover3)
	(equipped_for_imaging rover3)
	(at rover4 waypoint40)
	(store_of rover4store rover4)
	(empty rover4store)
	(equipped_for_rock_analysis rover4)
	(at rover5 waypoint53)
	(store_of rover5store rover5)
	(empty rover5store)
	(equipped_for_soil_analysis rover5)
	(equipped_for_rock_analysis rover5)
	(at rover6 waypoint37)
	(store_of rover6store rover6)
	(empty rover6store)
	(equipped_for_imaging rover6)
	(at rover7 waypoint35)
	(store_of rover7store rover7)
	(empty rover7store)
	(equipped_for_rock_analysis rover7)
	(equipped_for_imaging rover7)
	(at rover8 waypoint21)
	(store_of rover8store rover8)
	(empty rover8store)
	(equipped_for_soil_analysis rover8)
	(equipped_for_rock_analysis rover8)
	(equipped_for_imaging rover8)
	(at rover9 waypoint30)
	(store_of rover9store rover9)
	(empty rover9store)
	(equipped_for_imaging rover9)
	(at rover10 waypoint52)
	(store_of rover10store rover10)
	(empty rover10store)
	(equipped_for_soil_analysis rover10)
	(equipped_for_rock_analysis rover10)
	(equipped_for_imaging rover10)
	(at rover11 waypoint55)
	(store_of rover11store rover11)
	(empty rover11store)
	(equipped_for_soil_analysis rover11)
	(equipped_for_rock_analysis rover11)
	(on_board camera0 rover10)
	(calibration_target camera0 objective7)
	(supports camera0 colour)
	(supports camera0 high_res)
	(supports camera0 low_res)
	(on_board camera1 rover1)
	(calibration_target camera1 objective6)
	(supports camera1 colour)
	(supports camera1 high_res)
	(on_board camera2 rover0)
	(calibration_target camera2 objective1)
	(supports camera2 colour)
	(supports camera2 high_res)
	(on_board camera3 rover3)
	(calibration_target camera3 objective7)
	(supports camera3 colour)
	(on_board camera4 rover7)
	(calibration_target camera4 objective8)
	(supports camera4 high_res)
	(supports camera4 low_res)
	(on_board camera5 rover3)
	(calibration_target camera5 objective2)
	(supports camera5 colour)
	(on_board camera6 rover7)
	(calibration_target camera6 objective3)
	(supports camera6 high_res)
	(supports camera6 low_res)
	(on_board camera7 rover0)
	(calibration_target camera7 objective6)
	(supports camera7 colour)
	(supports camera7 high_res)
	(on_board camera8 rover9)
	(calibration_target camera8 objective1)
	(supports camera8 colour)
	(supports camera8 high_res)
	(supports camera8 low_res)
	(on_board camera9 rover0)
	(calibration_target camera9 objective7)
	(supports camera9 colour)
	(on_board camera10 rover6)
	(calibration_target camera10 objective6)
	(supports camera10 colour)
	(on_board camera11 rover8)
	(calibration_target camera11 objective7)
	(supports camera11 high_res)
)

(:goal (and
(communicated_soil_data waypoint1)
(communicated_soil_data waypoint62)
(communicated_soil_data waypoint50)
(communicated_soil_data waypoint16)
(communicated_soil_data waypoint10)
(communicated_soil_data waypoint2)
(communicated_soil_data waypoint4)
(communicated_soil_data waypoint26)
(communicated_soil_data waypoint6)
(communicated_soil_data waypoint39)
(communicated_soil_data waypoint19)
(communicated_soil_data waypoint45)
(communicated_soil_data waypoint42)
(communicated_soil_data waypoint61)
(communicated_soil_data waypoint38)
(communicated_soil_data waypoint54)
(communicated_soil_data waypoint8)
(communicated_soil_data waypoint51)
(communicated_rock_data waypoint54)
(communicated_rock_data waypoint46)
(communicated_rock_data waypoint40)
(communicated_rock_data waypoint56)
(communicated_rock_data waypoint22)
(communicated_rock_data waypoint38)
(communicated_rock_data waypoint11)
(communicated_rock_data waypoint20)
(communicated_rock_data waypoint10)
(communicated_rock_data waypoint9)
(communicated_rock_data waypoint5)
(communicated_rock_data waypoint43)
(communicated_rock_data waypoint24)
(communicated_rock_data waypoint4)
(communicated_rock_data waypoint60)
(communicated_rock_data waypoint13)
(communicated_rock_data waypoint57)
(communicated_rock_data waypoint21)
(communicated_rock_data waypoint33)
(communicated_image_data objective6 colour)
(communicated_image_data objective6 high_res)
(communicated_image_data objective3 colour)
(communicated_image_data objective1 colour)
(communicated_image_data objective3 low_res)
(communicated_image_data objective4 colour)
(communicated_image_data objective3 high_res)
	)
)
)
