; Problem taken from https://github.com/AI-Planning/classical-domains

(define (problem roverprob8327) (:domain Rover)
(:objects
	general - Lander
	colour high_res low_res - Mode
	rover0 rover1 rover2 rover3 rover4 rover5 - Rover
	rover0store rover1store rover2store rover3store rover4store rover5store - Store
	waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 waypoint11 waypoint12 waypoint13 waypoint14 waypoint15 waypoint16 waypoint17 waypoint18 waypoint19 - Waypoint
	camera0 camera1 camera2 camera3 camera4 camera5 camera6 - Camera
	objective0 objective1 objective2 objective3 objective4 objective5 objective6 objective7 - Objective
	)
(:init
	(at_soil_sample waypoint3)
	(at_rock_sample waypoint3)
	(at_rock_sample waypoint4)
	(at_soil_sample waypoint5)
	(at_rock_sample waypoint6)
	(at_soil_sample waypoint8)
	(at_rock_sample waypoint9)
	(at_soil_sample waypoint11)
	(at_soil_sample waypoint12)
	(at_soil_sample waypoint14)
	(at_soil_sample waypoint15)
	(at_soil_sample waypoint16)
	(at_soil_sample waypoint17)
	(at_rock_sample waypoint17)
	(at_soil_sample waypoint18)
	(at_rock_sample waypoint19)
	(at_lander general waypoint6)
	(channel_free general)
	(at rover0 waypoint2)
	(store_of rover0store rover0)
	(empty rover0store)
	(equipped_for_imaging rover0)
	(at rover1 waypoint6)
	(store_of rover1store rover1)
	(empty rover1store)
	(equipped_for_imaging rover1)
	(at rover2 waypoint13)
	(store_of rover2store rover2)
	(empty rover2store)
	(equipped_for_soil_analysis rover2)
	(equipped_for_imaging rover2)
	(at rover3 waypoint11)
	(store_of rover3store rover3)
	(empty rover3store)
	(equipped_for_soil_analysis rover3)
	(equipped_for_rock_analysis rover3)
	(equipped_for_imaging rover3)
	(at rover4 waypoint0)
	(store_of rover4store rover4)
	(empty rover4store)
	(equipped_for_soil_analysis rover4)
	(equipped_for_rock_analysis rover4)
	(equipped_for_imaging rover4)
	(at rover5 waypoint12)
	(store_of rover5store rover5)
	(empty rover5store)
	(equipped_for_soil_analysis rover5)
	(equipped_for_rock_analysis rover5)
	(equipped_for_imaging rover5)
	(on_board camera0 rover2)
	(calibration_target camera0 objective0)
	(supports camera0 colour)
	(supports camera0 high_res)
	(supports camera0 low_res)
	(on_board camera1 rover1)
	(calibration_target camera1 objective1)
	(supports camera1 high_res)
	(on_board camera2 rover1)
	(calibration_target camera2 objective0)
	(supports camera2 high_res)
	(supports camera2 low_res)
	(on_board camera3 rover0)
	(calibration_target camera3 objective5)
	(supports camera3 high_res)
	(on_board camera4 rover4)
	(calibration_target camera4 objective2)
	(supports camera4 colour)
	(supports camera4 low_res)
	(on_board camera5 rover3)
	(calibration_target camera5 objective0)
	(supports camera5 colour)
	(supports camera5 low_res)
	(on_board camera6 rover5)
	(calibration_target camera6 objective6)
	(supports camera6 colour)
	(supports camera6 high_res)
	(supports camera6 low_res)
)

(:goal (and
(communicated_soil_data waypoint18)
(communicated_soil_data waypoint8)
(communicated_soil_data waypoint5)
(communicated_rock_data waypoint17)
(communicated_rock_data waypoint6)
(communicated_rock_data waypoint9)
(communicated_rock_data waypoint19)
(communicated_rock_data waypoint3)
(communicated_rock_data waypoint4)
(communicated_image_data objective7 low_res)
(communicated_image_data objective4 high_res)
(communicated_image_data objective0 colour)
(communicated_image_data objective6 low_res)
(communicated_image_data objective7 colour)
(communicated_image_data objective2 low_res)
(communicated_image_data objective0 high_res)
(communicated_image_data objective5 colour)
	)
)
)
