import re
from pathlib import Path
import random

import dspy

from nl_pddlgym.constants import (
    prompts_dir,
    pddlgym_action_prompts_dir,
    pddlgym_domain_prompts_dir,
    pddlgym_object_names_prompts_dir,
    pddlgym_problem_prompts_dir,
)

import nl_pddlgym
from nl_pddlgym.core import PDDLEnv


def get_pddl_gym_domain_prompt(file_name: str) -> str:
    with open(pddlgym_domain_prompts_dir / file_name) as f:
        return f.read()


def get_pddl_gym_problem_prompt(file_name: str) -> str:
    with open(pddlgym_problem_prompts_dir / file_name) as f:
        return f.read()


def get_action_schema_prompt(file_name: str) -> str:
    with open(pddlgym_action_prompts_dir / file_name) as f:
        return f.read()


def get_object_names_prompt(file_name: str) -> str:
    with open(pddlgym_object_names_prompts_dir / file_name) as f:
        return f.read()


def get_combined_pddlgym_prompt(domain: str, problem: str) -> str:
    with open(pddlgym_domain_prompts_dir / domain) as f:
        domain = f.read()
    with open(pddlgym_problem_prompts_dir / problem) as f:
        problem = f.read()
    with open(prompts_dir / "task.md") as f:
        return f.read().format(
            domain=domain,
            problem=problem,
        )


def goal_reached(domain_name: str, problem_index: int, plan_file: Path):
    """
    Convenience function for mapping plan files generated by FastDownward to the
    representation expected by pddlgym and checking for plan success.
    """
    env: PDDLEnv = nl_pddlgym.make(f"{domain_name}-v0")  # type: ignore
    env.fix_problem_index(problem_index)
    state, _ = env.reset()
    with open(plan_file) as f:
        content = f.read().lower()
    plan = []
    for line in content.splitlines():
        line = line.strip()
        match = re.match(
            r"^\((?P<function>\S+)(?:\s+(?P<parameters>.*))?\)$",
            line,
        )
        if match:
            action = match.group("function")
            parameters_str = match.group("parameters") or ""
            parameters = parameters_str.split() if parameters_str else []
            if env.domain.operators_as_actions:
                if action not in env.domain.operators:
                    return False
                plan.append(f"{action} {' '.join(parameters)}")
            else:
                # Accept if action is a known predicate (predicate format) or a known operator (operator format)
                is_known_predicate = action in env.domain.predicates
                is_known_operator = action in env.domain.operators
                if not is_known_predicate and not is_known_operator:
                    return False
                plan.append(f"{action} {' '.join(parameters)}")
    # Parse plan steps into action literals
    parsed_plan = []
    for plan_step in plan:
        plan_step_split = plan_step.split()
        action_name = plan_step_split[0].lower()
        object_names = plan_step_split[1:]

        # Try predicate-based matching first
        matched = False
        for a in list(env.domain.actions):
            pred = env.domain.predicates.get(a if isinstance(a, str) else a.name)
            if pred is None:
                continue
            pname = a if isinstance(a, str) else a.name
            if pname.lower() == action_name and len(object_names) == pred.arity:
                args = []
                for name in object_names:
                    matches = [o for o in state.objects if o.name == name]
                    if len(matches) != 1:
                        break
                    args.append(matches[0])
                if len(args) == pred.arity:
                    parsed_plan.append(pred(*args))
                    matched = True
                    break
        if matched:
            continue

        # Fall back to operator-based parsing
        if action_name not in env.domain.operators:
            return False
        from nl_pddlgym.structs import Predicate

        op = env.domain.operators[action_name]
        ptypes = [p.var_type for p in op.params]
        pred = Predicate(action_name, len(ptypes), ptypes)
        args = []
        for name in object_names:
            matches = [o for o in state.objects if o.name == name]
            if len(matches) != 1:
                return False
            args.append(matches[0])
        if len(args) < len(op.params):
            # Partial params: pad to match operator arity
            pred = Predicate(action_name, len(args), ptypes[: len(args)])
        parsed_plan.append(pred(*args))

    plan = parsed_plan

    terminated = False
    while not terminated:
        try:
            action = plan.pop(0)
        except IndexError:
            return False
        try:
            state, _, terminated, _, _ = env.step(action)
        except Exception:
            return False
    return True


class Problem:
    def __init__(
        self,
        domain_prompt_file: str,
        problem_prompt_file: str,
        action_schema_prompt_file: str,
        object_names_prompt_file: str,
        domain_name: str,
        problem_idx: int,
    ):
        self.domain_prompt_file = domain_prompt_file
        self.problem_prompt_file = problem_prompt_file
        self.action_schema_prompt_file = action_schema_prompt_file
        self.object_names_prompt_file = object_names_prompt_file
        self.domain_name = domain_name
        self.problem_idx = problem_idx

    def make_dspy_example(self) -> dspy.Example:
        """
        Create DSPy example object for the given domain and problem in the format
        expected by https://github.com/vDawgg/pddl_pipeline
        """
        return dspy.Example(
            task_description=get_combined_pddlgym_prompt(
                self.domain_prompt_file,
                self.problem_prompt_file,
            ),
            action_schema=get_action_schema_prompt(self.action_schema_prompt_file),
            object_names=get_object_names_prompt(self.object_names_prompt_file),
            domain_name=self.domain_name,
            problem_index=self.problem_idx,
        ).with_inputs("task_description", "action_schema", "object_names")

    def goal_reached(self, plan_file: Path) -> bool:
        return goal_reached(self.domain_name, self.problem_idx, plan_file)


class NlPddlGymDs:
    def __init__(self, split: tuple = (80, 20), shuffle_ds: bool | int = True):
        """
        Wrapper for the NL-pddlgym dataset.
        Always shuffles the data while making sure the distribution of problems
        is respected across the different splits.

        The domains baking, open_stacks, rearrangement, and ring_and_peg are
        held out entirely for testing and never appear in the training or
        validation sets.

        Parameters
        ----------
        split : tuple
            Train/val split ratios for the remaining domains. Must be a 2-tuple
            (train_percent, val_percent) summing to 100.
        shuffle_ds : bool | int
            Controls whether the shuffle is repeatable. If True, shuffles
            deterministically with a default seed. If an int, uses that as the
            seed. If False, shuffles non-deterministically.
        """
        assert len(split) == 2, "Split must contain exactly 2 ratios (train, val)."
        assert sum(split) == 100, "Splits must sum to 100"
        # baking
        baking = [
            Problem(
                domain_prompt_file="Baking.md",
                problem_prompt_file=f"Baking_{i}.md",
                action_schema_prompt_file="Baking.md",
                object_names_prompt_file="Baking.md",
                domain_name="PDDLEnvBaking",
                problem_idx=i,
            )
            for i in range(20)
        ]
        # blocks
        blocks = [
            Problem(
                domain_prompt_file="Blocks.md",
                problem_prompt_file=f"Blocks_{i}.md",
                action_schema_prompt_file="Blocks.md",
                object_names_prompt_file="Blocks.md",
                domain_name="PDDLEnvBlocks",
                problem_idx=i,
            )
            for i in range(5)
        ]
        blocks.extend(
            [
                Problem(
                    domain_prompt_file="Blocks.md",
                    problem_prompt_file=f"BlocksMedium_{i}.md",
                    action_schema_prompt_file="Blocks.md",
                    object_names_prompt_file="Blocks.md",
                    domain_name="PDDLEnvBlocks_medium",
                    problem_idx=i,
                )
                for i in range(40)
            ]
        )
        # briefcaseworld
        briefcaseworld = [
            Problem(
                domain_prompt_file="BriefcaseWorld.md",
                problem_prompt_file=f"BriefcaseWorld_{i}.md",
                action_schema_prompt_file="BriefcaseWorld.md",
                object_names_prompt_file="BriefcaseWorld.md",
                domain_name="PDDLEnvBriefcaseworld",
                problem_idx=i,
            )
            for i in range(30)
        ]
        # driverlog
        driverlog = [
            Problem(
                domain_prompt_file="DriverLog.md",
                problem_prompt_file=f"DriverLog_{i}.md",
                action_schema_prompt_file="DriverLog.md",
                object_names_prompt_file="DriverLog.md",
                domain_name="PDDLEnvDriverlog",
                problem_idx=i,
            )
            for i in range(20)
        ]
        # elevator
        elevator = [
            Problem(
                domain_prompt_file="Elevator.md",
                problem_prompt_file=f"Elevator_{i}.md",
                action_schema_prompt_file="Elevator.md",
                object_names_prompt_file="Elevator.md",
                domain_name="PDDLEnvElevator",
                problem_idx=i,
            )
            for i in range(20)
        ]
        # ferry
        ferry = [
            Problem(
                domain_prompt_file="Ferry.md",
                problem_prompt_file=f"Ferry_{i}.md",
                action_schema_prompt_file="Ferry.md",
                object_names_prompt_file="Ferry.md",
                domain_name="PDDLEnvFerry",
                problem_idx=i,
            )
            for i in range(20)
        ]
        # gripper
        gripper = [
            Problem(
                domain_prompt_file="Gripper.md",
                problem_prompt_file=f"Gripper_{i}.md",
                action_schema_prompt_file="Gripper.md",
                object_names_prompt_file="Gripper.md",
                domain_name="PDDLEnvGripper",
                problem_idx=i,
            )
            for i in range(10)
        ]
        gripper.extend(
            [
                Problem(
                    domain_prompt_file="Gripper.md",
                    problem_prompt_file=f"ManyGripper_{i}.md",
                    action_schema_prompt_file="Gripper.md",
                    object_names_prompt_file="Gripper.md",
                    domain_name="PDDLEnvManygripper",
                    problem_idx=i,
                )
                for i in range(40)
            ]
        )
        # hanoi
        hanoi = [
            Problem(
                domain_prompt_file="Hanoi.md",
                problem_prompt_file=f"Hanoi_{i}.md",
                action_schema_prompt_file="Hanoi.md",
                object_names_prompt_file="Hanoi.md",
                domain_name="PDDLEnvHanoi",
                problem_idx=i,
            )
            for i in range(20)
        ]
        # minecraft
        minecraft = [
            Problem(
                domain_prompt_file="Minecraft.md",
                problem_prompt_file=f"Minecraft_{i}.md",
                action_schema_prompt_file="Minecraft.md",
                object_names_prompt_file="Minecraft.md",
                domain_name="PDDLEnvMinecraft",
                problem_idx=i,
            )
            for i in range(30)
        ]
        minecraft.extend(
            Problem(
                domain_prompt_file="Minecraft.md",
                problem_prompt_file=f"MinecraftTest_{i}.md",
                action_schema_prompt_file="Minecraft.md",
                object_names_prompt_file="Minecraft.md",
                domain_name="PDDLEnvMinecraftTest",
                problem_idx=i,
            )
            for i in range(30)
        )
        # movie
        movie = [
            Problem(
                domain_prompt_file="Movie.md",
                problem_prompt_file=f"Movie_{i}.md",
                action_schema_prompt_file="Movie.md",
                object_names_prompt_file="Movie.md",
                domain_name="PDDLEnvMovie",
                problem_idx=i,
            )
            for i in range(10)
        ]
        # needle sorting
        needle_sorting = [
            Problem(
                domain_prompt_file="NeedleSorting.md",
                problem_prompt_file=f"NeedleSorting_{i}.md",
                action_schema_prompt_file="NeedleSorting.md",
                object_names_prompt_file="NeedleSorting.md",
                domain_name="PDDLEnvNeedle_sorting",
                problem_idx=i,
            )
            for i in range(20)
        ]
        # needle transfer
        needle_transfer = [
            Problem(
                domain_prompt_file="NeedleTransfer.md",
                problem_prompt_file=f"NeedleTransfer_{i}.md",
                action_schema_prompt_file="NeedleTransfer.md",
                object_names_prompt_file="NeedleTransfer.md",
                domain_name="PDDLEnvNeedle_transfer",
                problem_idx=i,
            )
            for i in range(20)
        ]
        # newspapers
        newspapers = [
            Problem(
                domain_prompt_file="Newspapers.md",
                problem_prompt_file=f"Newspapers_{i}.md",
                action_schema_prompt_file="Newspapers.md",
                object_names_prompt_file="Newspapers.md",
                domain_name="PDDLEnvNewspapers",
                problem_idx=i,
            )
            for i in range(40)
        ]
        # open stacks
        open_stacks = [
            Problem(
                domain_prompt_file="OpenStacks.md",
                problem_prompt_file=f"OpenStacks_{i}.md",
                action_schema_prompt_file="OpenStacks.md",
                object_names_prompt_file="OpenStacks.md",
                domain_name="PDDLEnvOpen_stacks",
                problem_idx=i,
            )
            for i in range(30)
        ]
        # rearrangement
        rearrangement = [
            Problem(
                domain_prompt_file="Rearrangement.md",
                problem_prompt_file=f"Rearrangement_{i}.md",
                action_schema_prompt_file="Rearrangement.md",
                object_names_prompt_file="Rearrangement.md",
                domain_name="PDDLEnvRearrangement",
                problem_idx=i,
            )
            for i in range(20)
        ]
        # ring and peg
        ring_and_peg = [
            Problem(
                domain_prompt_file="RingAndPeg.md",
                problem_prompt_file=f"RingAndPeg_{i}.md",
                action_schema_prompt_file="RingAndPeg.md",
                object_names_prompt_file="RingAndPeg.md",
                domain_name="PDDLEnvRing_and_peg",
                problem_idx=i,
            )
            for i in range(30)
        ]
        # rovers
        rovers = [
            Problem(
                domain_prompt_file="Rovers.md",
                problem_prompt_file=f"Rovers_{i}.md",
                action_schema_prompt_file="Rovers.md",
                object_names_prompt_file="Rovers.md",
                domain_name="PDDLEnvRovers",
                problem_idx=i,
            )
            for i in range(40)
        ]
        # satellite
        satellite = [
            Problem(
                domain_prompt_file="Satellite.md",
                problem_prompt_file=f"Satellite_{i}.md",
                action_schema_prompt_file="Satellite.md",
                object_names_prompt_file="Satellite.md",
                domain_name="PDDLEnvSatellite",
                problem_idx=i,
            )
            for i in range(36)
        ]
        # schedule
        schedule = [
            Problem(
                domain_prompt_file="Schedule.md",
                problem_prompt_file=f"Schedule_{i}.md",
                action_schema_prompt_file="Schedule.md",
                object_names_prompt_file="Schedule.md",
                domain_name="PDDLEnvSchedule",
                problem_idx=i,
            )
            for i in range(50)
        ]
        # search and rescue
        search_and_rescue = [
            Problem(
                domain_prompt_file="SearchAndRescue.md",
                problem_prompt_file=f"SearchAndRescueLevel1_{i}.md",
                action_schema_prompt_file="SearchAndRescue.md",
                object_names_prompt_file="SearchAndRescue.md",
                domain_name="PDDLSearchAndRescueLevel1",
                problem_idx=i,
            )
            for i in range(20)
        ]
        search_and_rescue.extend(
            [
                Problem(
                    domain_prompt_file="SearchAndRescue.md",
                    problem_prompt_file=f"SearchAndRescueLevel2_{i}.md",
                    action_schema_prompt_file="SearchAndRescue.md",
                    object_names_prompt_file="SearchAndRescue.md",
                    domain_name="PDDLSearchAndRescueLevel2",
                    problem_idx=i,
                )
                for i in range(50)
            ]
        )
        # spanner learning
        spanner_learning = [
            Problem(
                domain_prompt_file="SpannerLearning.md",
                problem_prompt_file=f"SpannerLearning_{i}.md",
                action_schema_prompt_file="SpannerLearning.md",
                object_names_prompt_file="SpannerLearning.md",
                domain_name="PDDLEnvSpannerlearning",
                problem_idx=i,
            )
            for i in range(10)
        ]
        # tpp
        tpp = [
            Problem(
                domain_prompt_file="Tpp.md",
                problem_prompt_file=f"Tpp_{i}.md",
                action_schema_prompt_file="Tpp.md",
                object_names_prompt_file="Tpp.md",
                domain_name="PDDLEnvTpp",
                problem_idx=i,
            )
            for i in range(30)
        ]
        # zeno travel
        zeno_travel = [
            Problem(
                domain_prompt_file="ZenoTravel.md",
                problem_prompt_file=f"ZenoTravel_{i}.md",
                action_schema_prompt_file="ZenoTravel.md",
                object_names_prompt_file="ZenoTravel.md",
                domain_name="PDDLEnvZenotravel",
                problem_idx=i,
            )
            for i in range(20)
        ]

        splittable_problems = [
            baking,
            blocks,
            briefcaseworld,
            driverlog,
            ferry,
            gripper,
            minecraft,
            movie,
            needle_sorting,
            needle_transfer,
            newspapers,
            open_stacks,
            rearrangement,
            rovers,
            schedule,
            search_and_rescue,
            spanner_learning,
            tpp,
            zeno_travel,
        ]
        test_only_problems = [
            hanoi,
            satellite,
            elevator,
            ring_and_peg,
        ]

        if isinstance(shuffle_ds, bool):
            rng = random.Random(0) if shuffle_ds else random.Random()
        else:
            rng = random.Random(shuffle_ds)
        [rng.shuffle(probs) for probs in splittable_problems]

        train_ratio = split[0] / 100
        train_sizes = [int(len(probs) * train_ratio) for probs in splittable_problems]

        self.train = [
            prob
            for size, probs in zip(train_sizes, splittable_problems)
            for prob in probs[:size]
        ]
        self.val = [
            prob
            for size, probs in zip(train_sizes, splittable_problems)
            for prob in probs[size:]
        ]
        self.test = [prob for probs in test_only_problems for prob in probs]

        rng.shuffle(self.train)
        rng.shuffle(self.val)
        rng.shuffle(self.test)

    def make_dspy_ds(
        self,
    ) -> tuple[list[dspy.Example], list[dspy.Example], list[dspy.Example]]:
        """
        Make dataset for prompt optimization from natural language descriptions of
        pddlgym tasks in the format expected by DSPy.
        """
        train = [prob.make_dspy_example() for prob in self.train]
        val = [prob.make_dspy_example() for prob in self.val]
        test = [prob.make_dspy_example() for prob in self.test]
        return train, val, test
