(define (problem RING_AND_PEG_17)
    (:domain RING_AND_PEG)
    (:objects
        olive_ring maroon_ring navy_ring lime_ring coral_ring gold_ring
        olive_peg maroon_peg navy_peg lime_peg coral_peg gold_peg red_peg start_position
    )
    (:init
        (ring olive_ring)
        (ring maroon_ring)
        (ring navy_ring)
        (ring lime_ring)
        (ring coral_ring)
        (ring gold_ring)
        (peg olive_peg)
        (peg maroon_peg)
        (peg navy_peg)
        (peg lime_peg)
        (peg coral_peg)
        (peg gold_peg)
        (peg red_peg)
        (peg start_position)
        (onpeg olive_ring olive_peg)
        (onpeg maroon_ring maroon_peg)
        (onpeg navy_ring navy_peg)
        (onpeg lime_ring coral_peg)
        (onpeg coral_ring gold_peg)
        (onpeg gold_ring lime_peg)
        (pegempty red_peg)
        (at start_position)
        (handempty)

    ; action literals
    (move coral_peg)
    (move gold_peg)
    (move lime_peg)
    (move maroon_peg)
    (move navy_peg)
    (move olive_peg)
    (move red_peg)
    (move start_position)
    (pick)
    (place)
    )
    (:goal         (and (onpeg olive_ring olive_peg) (onpeg maroon_ring maroon_peg) (onpeg navy_ring navy_peg) (onpeg lime_ring lime_peg) (onpeg coral_ring coral_peg) (onpeg gold_ring gold_peg)))
)
