(define (problem RING_AND_PEG_06)
    (:domain RING_AND_PEG)
    (:objects
        blue_ring pink_ring
        blue_peg pink_peg red_peg green_peg yellow_peg start_position
    )
    (:init
        (ring blue_ring)
        (ring pink_ring)
        (peg blue_peg)
        (peg pink_peg)
        (peg red_peg)
        (peg green_peg)
        (peg yellow_peg)
        (peg start_position)
        (onpeg blue_ring green_peg)
        (onpeg pink_ring pink_peg)
        (pegempty red_peg)
        (pegempty blue_peg)
        (pegempty yellow_peg)
        (at start_position)
        (handempty)

    ; action literals
    (move blue_peg)
    (move green_peg)
    (move pink_peg)
    (move red_peg)
    (move start_position)
    (move yellow_peg)
    (pick)
    (place)
    )
    (:goal         (and (onpeg blue_ring blue_peg) (onpeg pink_ring pink_peg)))
)
