(define (problem baking)
    (:domain baking)

    (:objects
      oven-0 oven-1 oven-2 oven-3 oven-4 - oven
      egg-0 egg-1 egg-2 egg-3 egg-4 egg-5 egg-6 egg-7 egg-8 egg-9 - ingredient
      flour-0 flour-1 flour-2 flour-3 flour-4 flour-5 flour-6 flour-7 flour-8 flour-9 - ingredient
      pan-0 pan-1 pan-2 pan-3 pan-4 - pan
      new-0 new-1 new-2 new-3 new-4 new-5 new-6 new-7 new-8 new-9 - ingredient
      soap-0 - soap
      soap-1 - soap
      soap-2 - soap
      soap-3 - soap
      soap-4 - soap
      soap-5 - soap
      soap-6 - soap
    )

    (:init
    (isegg egg-0)
    (isegg egg-1)
    (isegg egg-2)
    (isegg egg-3)
    (isegg egg-4)
    (isegg egg-5)
    (isegg egg-6)
    (isegg egg-7)
    (isegg egg-8)
    (isegg egg-9)
    (isflour flour-0)
    (isflour flour-1)
    (isflour flour-2)
    (isflour flour-3)
    (isflour flour-4)
    (isflour flour-5)
    (isflour flour-6)
    (isflour flour-7)
    (isflour flour-8)
    (isflour flour-9)
    (hypothetical new-0)
    (hypothetical new-1)
    (hypothetical new-2)
    (hypothetical new-3)
    (hypothetical new-4)
    (hypothetical new-5)
    (hypothetical new-6)
    (hypothetical new-7)
    (hypothetical new-8)
    (hypothetical new-9)
    (panisclean pan-0)
    (panisclean pan-1)
    (panisclean pan-2)
    (panisclean pan-3)
    (panisclean pan-4)

    ; action literals

    (putegginpan egg-0 pan-0)
    (putegginpan egg-0 pan-1)
    (putegginpan egg-0 pan-2)
    (putegginpan egg-0 pan-3)
    (putegginpan egg-0 pan-4)
    (putegginpan egg-1 pan-0)
    (putegginpan egg-1 pan-1)
    (putegginpan egg-1 pan-2)
    (putegginpan egg-1 pan-3)
    (putegginpan egg-1 pan-4)
    (putegginpan egg-2 pan-0)
    (putegginpan egg-2 pan-1)
    (putegginpan egg-2 pan-2)
    (putegginpan egg-2 pan-3)
    (putegginpan egg-2 pan-4)
    (putegginpan egg-3 pan-0)
    (putegginpan egg-3 pan-1)
    (putegginpan egg-3 pan-2)
    (putegginpan egg-3 pan-3)
    (putegginpan egg-3 pan-4)
    (putegginpan egg-4 pan-0)
    (putegginpan egg-4 pan-1)
    (putegginpan egg-4 pan-2)
    (putegginpan egg-4 pan-3)
    (putegginpan egg-4 pan-4)
    (putegginpan egg-5 pan-0)
    (putegginpan egg-5 pan-1)
    (putegginpan egg-5 pan-2)
    (putegginpan egg-5 pan-3)
    (putegginpan egg-5 pan-4)
    (putegginpan egg-6 pan-0)
    (putegginpan egg-6 pan-1)
    (putegginpan egg-6 pan-2)
    (putegginpan egg-6 pan-3)
    (putegginpan egg-6 pan-4)
    (putegginpan egg-7 pan-0)
    (putegginpan egg-7 pan-1)
    (putegginpan egg-7 pan-2)
    (putegginpan egg-7 pan-3)
    (putegginpan egg-7 pan-4)
    (putegginpan egg-8 pan-0)
    (putegginpan egg-8 pan-1)
    (putegginpan egg-8 pan-2)
    (putegginpan egg-8 pan-3)
    (putegginpan egg-8 pan-4)
    (putegginpan egg-9 pan-0)
    (putegginpan egg-9 pan-1)
    (putegginpan egg-9 pan-2)
    (putegginpan egg-9 pan-3)
    (putegginpan egg-9 pan-4)
    (putflourinpan flour-0 pan-0)
    (putflourinpan flour-0 pan-1)
    (putflourinpan flour-0 pan-2)
    (putflourinpan flour-0 pan-3)
    (putflourinpan flour-0 pan-4)
    (putflourinpan flour-1 pan-0)
    (putflourinpan flour-1 pan-1)
    (putflourinpan flour-1 pan-2)
    (putflourinpan flour-1 pan-3)
    (putflourinpan flour-1 pan-4)
    (putflourinpan flour-2 pan-0)
    (putflourinpan flour-2 pan-1)
    (putflourinpan flour-2 pan-2)
    (putflourinpan flour-2 pan-3)
    (putflourinpan flour-2 pan-4)
    (putflourinpan flour-3 pan-0)
    (putflourinpan flour-3 pan-1)
    (putflourinpan flour-3 pan-2)
    (putflourinpan flour-3 pan-3)
    (putflourinpan flour-3 pan-4)
    (putflourinpan flour-4 pan-0)
    (putflourinpan flour-4 pan-1)
    (putflourinpan flour-4 pan-2)
    (putflourinpan flour-4 pan-3)
    (putflourinpan flour-4 pan-4)
    (putflourinpan flour-5 pan-0)
    (putflourinpan flour-5 pan-1)
    (putflourinpan flour-5 pan-2)
    (putflourinpan flour-5 pan-3)
    (putflourinpan flour-5 pan-4)
    (putflourinpan flour-6 pan-0)
    (putflourinpan flour-6 pan-1)
    (putflourinpan flour-6 pan-2)
    (putflourinpan flour-6 pan-3)
    (putflourinpan flour-6 pan-4)
    (putflourinpan flour-7 pan-0)
    (putflourinpan flour-7 pan-1)
    (putflourinpan flour-7 pan-2)
    (putflourinpan flour-7 pan-3)
    (putflourinpan flour-7 pan-4)
    (putflourinpan flour-8 pan-0)
    (putflourinpan flour-8 pan-1)
    (putflourinpan flour-8 pan-2)
    (putflourinpan flour-8 pan-3)
    (putflourinpan flour-8 pan-4)
    (putflourinpan flour-9 pan-0)
    (putflourinpan flour-9 pan-1)
    (putflourinpan flour-9 pan-2)
    (putflourinpan flour-9 pan-3)
    (putflourinpan flour-9 pan-4)
    (mix pan-0)
    (mix pan-1)
    (mix pan-2)
    (mix pan-3)
    (mix pan-4)
    (putpaninoven pan-0 oven-0)
    (putpaninoven pan-0 oven-1)
    (putpaninoven pan-0 oven-2)
    (putpaninoven pan-0 oven-3)
    (putpaninoven pan-0 oven-4)
    (putpaninoven pan-1 oven-0)
    (putpaninoven pan-1 oven-1)
    (putpaninoven pan-1 oven-2)
    (putpaninoven pan-1 oven-3)
    (putpaninoven pan-1 oven-4)
    (putpaninoven pan-2 oven-0)
    (putpaninoven pan-2 oven-1)
    (putpaninoven pan-2 oven-2)
    (putpaninoven pan-2 oven-3)
    (putpaninoven pan-2 oven-4)
    (putpaninoven pan-3 oven-0)
    (putpaninoven pan-3 oven-1)
    (putpaninoven pan-3 oven-2)
    (putpaninoven pan-3 oven-3)
    (putpaninoven pan-3 oven-4)
    (putpaninoven pan-4 oven-0)
    (putpaninoven pan-4 oven-1)
    (putpaninoven pan-4 oven-2)
    (putpaninoven pan-4 oven-3)
    (putpaninoven pan-4 oven-4)
    (removepanfromoven pan-0)
    (removepanfromoven pan-1)
    (removepanfromoven pan-2)
    (removepanfromoven pan-3)
    (removepanfromoven pan-4)
    (bakecake new-0 oven-0)
    (bakecake new-0 oven-1)
    (bakecake new-0 oven-2)
    (bakecake new-0 oven-3)
    (bakecake new-0 oven-4)
    (bakecake new-1 oven-0)
    (bakecake new-1 oven-1)
    (bakecake new-1 oven-2)
    (bakecake new-1 oven-3)
    (bakecake new-1 oven-4)
    (bakecake new-2 oven-0)
    (bakecake new-2 oven-1)
    (bakecake new-2 oven-2)
    (bakecake new-2 oven-3)
    (bakecake new-2 oven-4)
    (bakecake new-3 oven-0)
    (bakecake new-3 oven-1)
    (bakecake new-3 oven-2)
    (bakecake new-3 oven-3)
    (bakecake new-3 oven-4)
    (bakecake new-4 oven-0)
    (bakecake new-4 oven-1)
    (bakecake new-4 oven-2)
    (bakecake new-4 oven-3)
    (bakecake new-4 oven-4)
    (bakecake new-5 oven-0)
    (bakecake new-5 oven-1)
    (bakecake new-5 oven-2)
    (bakecake new-5 oven-3)
    (bakecake new-5 oven-4)
    (bakecake new-6 oven-0)
    (bakecake new-6 oven-1)
    (bakecake new-6 oven-2)
    (bakecake new-6 oven-3)
    (bakecake new-6 oven-4)
    (bakecake new-7 oven-0)
    (bakecake new-7 oven-1)
    (bakecake new-7 oven-2)
    (bakecake new-7 oven-3)
    (bakecake new-7 oven-4)
    (bakecake new-8 oven-0)
    (bakecake new-8 oven-1)
    (bakecake new-8 oven-2)
    (bakecake new-8 oven-3)
    (bakecake new-8 oven-4)
    (bakecake new-9 oven-0)
    (bakecake new-9 oven-1)
    (bakecake new-9 oven-2)
    (bakecake new-9 oven-3)
    (bakecake new-9 oven-4)
    (bakesouffle new-0 oven-0)
    (bakesouffle new-0 oven-1)
    (bakesouffle new-0 oven-2)
    (bakesouffle new-0 oven-3)
    (bakesouffle new-0 oven-4)
    (bakesouffle new-1 oven-0)
    (bakesouffle new-1 oven-1)
    (bakesouffle new-1 oven-2)
    (bakesouffle new-1 oven-3)
    (bakesouffle new-1 oven-4)
    (bakesouffle new-2 oven-0)
    (bakesouffle new-2 oven-1)
    (bakesouffle new-2 oven-2)
    (bakesouffle new-2 oven-3)
    (bakesouffle new-2 oven-4)
    (bakesouffle new-3 oven-0)
    (bakesouffle new-3 oven-1)
    (bakesouffle new-3 oven-2)
    (bakesouffle new-3 oven-3)
    (bakesouffle new-3 oven-4)
    (bakesouffle new-4 oven-0)
    (bakesouffle new-4 oven-1)
    (bakesouffle new-4 oven-2)
    (bakesouffle new-4 oven-3)
    (bakesouffle new-4 oven-4)
    (bakesouffle new-5 oven-0)
    (bakesouffle new-5 oven-1)
    (bakesouffle new-5 oven-2)
    (bakesouffle new-5 oven-3)
    (bakesouffle new-5 oven-4)
    (bakesouffle new-6 oven-0)
    (bakesouffle new-6 oven-1)
    (bakesouffle new-6 oven-2)
    (bakesouffle new-6 oven-3)
    (bakesouffle new-6 oven-4)
    (bakesouffle new-7 oven-0)
    (bakesouffle new-7 oven-1)
    (bakesouffle new-7 oven-2)
    (bakesouffle new-7 oven-3)
    (bakesouffle new-7 oven-4)
    (bakesouffle new-8 oven-0)
    (bakesouffle new-8 oven-1)
    (bakesouffle new-8 oven-2)
    (bakesouffle new-8 oven-3)
    (bakesouffle new-8 oven-4)
    (bakesouffle new-9 oven-0)
    (bakesouffle new-9 oven-1)
    (bakesouffle new-9 oven-2)
    (bakesouffle new-9 oven-3)
    (bakesouffle new-9 oven-4)
    (cleanpan pan-0 soap-0)
    (cleanpan pan-1 soap-0)
    (cleanpan pan-2 soap-0)
    (cleanpan pan-3 soap-0)
    (cleanpan pan-4 soap-0)
    (cleanpan pan-0 soap-1)
    (cleanpan pan-1 soap-1)
    (cleanpan pan-2 soap-1)
    (cleanpan pan-3 soap-1)
    (cleanpan pan-4 soap-1)
    (cleanpan pan-0 soap-2)
    (cleanpan pan-1 soap-2)
    (cleanpan pan-2 soap-2)
    (cleanpan pan-3 soap-2)
    (cleanpan pan-4 soap-2)
    (cleanpan pan-0 soap-3)
    (cleanpan pan-1 soap-3)
    (cleanpan pan-2 soap-3)
    (cleanpan pan-3 soap-3)
    (cleanpan pan-4 soap-3)
    (cleanpan pan-0 soap-4)
    (cleanpan pan-1 soap-4)
    (cleanpan pan-2 soap-4)
    (cleanpan pan-3 soap-4)
    (cleanpan pan-4 soap-4)
    (cleanpan pan-0 soap-5)
    (cleanpan pan-1 soap-5)
    (cleanpan pan-2 soap-5)
    (cleanpan pan-3 soap-5)
    (cleanpan pan-4 soap-5)
    (cleanpan pan-0 soap-6)
    (cleanpan pan-1 soap-6)
    (cleanpan pan-2 soap-6)
    (cleanpan pan-3 soap-6)
    (cleanpan pan-4 soap-6)
    )

    (:goal         (and (iscake new-0) (iscake new-1) (iscake new-2) (iscake new-3) (iscake new-4) (iscake new-5) (iscake new-6) (iscake new-7) (iscake new-8) (iscake new-9)))
)
