(define (problem baking)
    (:domain baking)

    (:objects
      oven-0 oven-1 oven-2 - oven
      egg-0 egg-1 egg-2 egg-3 - ingredient
      flour-0 flour-1 - ingredient
      pan-0 pan-1 - pan
      new-0 new-1 new-2 new-3 - ingredient
      soap-0 soap-1 - soap
    )

    (:init
    (isegg egg-0)
    (isegg egg-1)
    (isegg egg-2)
    (isegg egg-3)
    (isflour flour-0)
    (isflour flour-1)
    (hypothetical new-0)
    (hypothetical new-1)
    (hypothetical new-2)
    (hypothetical new-3)
    (panisclean pan-0)
    (panisclean pan-1)

    ; action literals

    (putegginpan egg-0 pan-0)
    (putegginpan egg-0 pan-1)
    (putegginpan egg-1 pan-0)
    (putegginpan egg-1 pan-1)
    (putegginpan egg-2 pan-0)
    (putegginpan egg-2 pan-1)
    (putegginpan egg-3 pan-0)
    (putegginpan egg-3 pan-1)
    (putflourinpan flour-0 pan-0)
    (putflourinpan flour-0 pan-1)
    (putflourinpan flour-1 pan-0)
    (putflourinpan flour-1 pan-1)
    (mix pan-0)
    (mix pan-1)
    (putpaninoven pan-0 oven-0)
    (putpaninoven pan-0 oven-1)
    (putpaninoven pan-0 oven-2)
    (putpaninoven pan-1 oven-0)
    (putpaninoven pan-1 oven-1)
    (putpaninoven pan-1 oven-2)
    (removepanfromoven pan-0)
    (removepanfromoven pan-1)
    (bakecake new-0 oven-0)
    (bakecake new-0 oven-1)
    (bakecake new-0 oven-2)
    (bakecake new-1 oven-0)
    (bakecake new-1 oven-1)
    (bakecake new-1 oven-2)
    (bakecake new-2 oven-0)
    (bakecake new-2 oven-1)
    (bakecake new-2 oven-2)
    (bakecake new-3 oven-0)
    (bakecake new-3 oven-1)
    (bakecake new-3 oven-2)
    (bakesouffle new-0 oven-0)
    (bakesouffle new-0 oven-1)
    (bakesouffle new-0 oven-2)
    (bakesouffle new-1 oven-0)
    (bakesouffle new-1 oven-1)
    (bakesouffle new-1 oven-2)
    (bakesouffle new-2 oven-0)
    (bakesouffle new-2 oven-1)
    (bakesouffle new-2 oven-2)
    (bakesouffle new-3 oven-0)
    (bakesouffle new-3 oven-1)
    (bakesouffle new-3 oven-2)
    (cleanpan pan-0 soap-0)
    (cleanpan pan-0 soap-1)
    (cleanpan pan-1 soap-0)
    (cleanpan pan-1 soap-1)
    )

    (:goal         (and (iscake new-0) (iscake new-1) (issouffle new-2) (issouffle new-3)))
)
