(define (problem depotprob8715) (:domain Depot)
(:objects
	depot0 depot1 depot2 depot3 depot4 depot5 - Depot
	distributor0 distributor1 distributor2 distributor3 distributor4 distributor5 - Distributor
	truck0 truck1 truck2 truck3 truck4 truck5 - Truck
	pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 pallet6 pallet7 pallet8 pallet9 pallet10 pallet11 pallet12 pallet13 pallet14 pallet15 pallet16 pallet17 pallet18 pallet19 - Pallet
	crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 crate8 crate9 - Crate
	hoist0 hoist1 hoist2 hoist3 hoist4 hoist5 hoist6 hoist7 hoist8 hoist9 hoist10 hoist11 hoist12 hoist13 hoist14 - Hoist)
(:init
	(at pallet0 depot0)
	(clear crate1)
	(at pallet1 depot1)
	(clear crate5)
	(at pallet2 depot2)
	(clear pallet2)
	(at pallet3 depot3)
	(clear pallet3)
	(at pallet4 depot4)
	(clear crate6)
	(at pallet5 depot5)
	(clear pallet5)
	(at pallet6 distributor0)
	(clear pallet6)
	(at pallet7 distributor1)
	(clear crate8)
	(at pallet8 distributor2)
	(clear crate4)
	(at pallet9 distributor3)
	(clear pallet9)
	(at pallet10 distributor4)
	(clear pallet10)
	(at pallet11 distributor5)
	(clear pallet11)
	(at pallet12 distributor1)
	(clear pallet12)
	(at pallet13 distributor5)
	(clear crate2)
	(at pallet14 depot2)
	(clear pallet14)
	(at pallet15 depot1)
	(clear crate3)
	(at pallet16 depot1)
	(clear crate0)
	(at pallet17 distributor2)
	(clear pallet17)
	(at pallet18 depot4)
	(clear crate7)
	(at pallet19 depot1)
	(clear crate9)
	(at truck0 distributor2)
	(at truck1 depot0)
	(at truck2 distributor3)
	(at truck3 distributor0)
	(at truck4 depot0)
	(at truck5 depot4)
	(at hoist0 depot0)
	(available hoist0)
	(at hoist1 depot1)
	(available hoist1)
	(at hoist2 depot2)
	(available hoist2)
	(at hoist3 depot3)
	(available hoist3)
	(at hoist4 depot4)
	(available hoist4)
	(at hoist5 depot5)
	(available hoist5)
	(at hoist6 distributor0)
	(available hoist6)
	(at hoist7 distributor1)
	(available hoist7)
	(at hoist8 distributor2)
	(available hoist8)
	(at hoist9 distributor3)
	(available hoist9)
	(at hoist10 distributor4)
	(available hoist10)
	(at hoist11 distributor5)
	(available hoist11)
	(at hoist12 depot5)
	(available hoist12)
	(at hoist13 depot1)
	(available hoist13)
	(at hoist14 depot4)
	(available hoist14)
	(at crate0 depot1)
	(on crate0 pallet16)
	(at crate1 depot0)
	(on crate1 pallet0)
	(at crate2 distributor5)
	(on crate2 pallet13)
	(at crate3 depot1)
	(on crate3 pallet15)
	(at crate4 distributor2)
	(on crate4 pallet8)
	(at crate5 depot1)
	(on crate5 pallet1)
	(at crate6 depot4)
	(on crate6 pallet4)
	(at crate7 depot4)
	(on crate7 pallet18)
	(at crate8 distributor1)
	(on crate8 pallet7)
	(at crate9 depot1)
	(on crate9 pallet19)

    ; action literals
    (drive truck0 depot0)
    (drive truck0 depot1)
    (drive truck0 depot2)
    (drive truck0 depot3)
    (drive truck0 depot4)
    (drive truck0 depot5)
    (drive truck0 distributor0)
    (drive truck0 distributor1)
    (drive truck0 distributor2)
    (drive truck0 distributor3)
    (drive truck0 distributor4)
    (drive truck0 distributor5)
    (drive truck1 depot0)
    (drive truck1 depot1)
    (drive truck1 depot2)
    (drive truck1 depot3)
    (drive truck1 depot4)
    (drive truck1 depot5)
    (drive truck1 distributor0)
    (drive truck1 distributor1)
    (drive truck1 distributor2)
    (drive truck1 distributor3)
    (drive truck1 distributor4)
    (drive truck1 distributor5)
    (drive truck2 depot0)
    (drive truck2 depot1)
    (drive truck2 depot2)
    (drive truck2 depot3)
    (drive truck2 depot4)
    (drive truck2 depot5)
    (drive truck2 distributor0)
    (drive truck2 distributor1)
    (drive truck2 distributor2)
    (drive truck2 distributor3)
    (drive truck2 distributor4)
    (drive truck2 distributor5)
    (drive truck3 depot0)
    (drive truck3 depot1)
    (drive truck3 depot2)
    (drive truck3 depot3)
    (drive truck3 depot4)
    (drive truck3 depot5)
    (drive truck3 distributor0)
    (drive truck3 distributor1)
    (drive truck3 distributor2)
    (drive truck3 distributor3)
    (drive truck3 distributor4)
    (drive truck3 distributor5)
    (drive truck4 depot0)
    (drive truck4 depot1)
    (drive truck4 depot2)
    (drive truck4 depot3)
    (drive truck4 depot4)
    (drive truck4 depot5)
    (drive truck4 distributor0)
    (drive truck4 distributor1)
    (drive truck4 distributor2)
    (drive truck4 distributor3)
    (drive truck4 distributor4)
    (drive truck4 distributor5)
    (drive truck5 depot0)
    (drive truck5 depot1)
    (drive truck5 depot2)
    (drive truck5 depot3)
    (drive truck5 depot4)
    (drive truck5 depot5)
    (drive truck5 distributor0)
    (drive truck5 distributor1)
    (drive truck5 distributor2)
    (drive truck5 distributor3)
    (drive truck5 distributor4)
    (drive truck5 distributor5)
    (lift hoist0 crate0)
    (lift hoist0 crate1)
    (lift hoist0 crate2)
    (lift hoist0 crate3)
    (lift hoist0 crate4)
    (lift hoist0 crate5)
    (lift hoist0 crate6)
    (lift hoist0 crate7)
    (lift hoist0 crate8)
    (lift hoist0 crate9)
    (lift hoist1 crate0)
    (lift hoist1 crate1)
    (lift hoist1 crate2)
    (lift hoist1 crate3)
    (lift hoist1 crate4)
    (lift hoist1 crate5)
    (lift hoist1 crate6)
    (lift hoist1 crate7)
    (lift hoist1 crate8)
    (lift hoist1 crate9)
    (lift hoist2 crate0)
    (lift hoist2 crate1)
    (lift hoist2 crate2)
    (lift hoist2 crate3)
    (lift hoist2 crate4)
    (lift hoist2 crate5)
    (lift hoist2 crate6)
    (lift hoist2 crate7)
    (lift hoist2 crate8)
    (lift hoist2 crate9)
    (lift hoist3 crate0)
    (lift hoist3 crate1)
    (lift hoist3 crate2)
    (lift hoist3 crate3)
    (lift hoist3 crate4)
    (lift hoist3 crate5)
    (lift hoist3 crate6)
    (lift hoist3 crate7)
    (lift hoist3 crate8)
    (lift hoist3 crate9)
    (lift hoist4 crate0)
    (lift hoist4 crate1)
    (lift hoist4 crate2)
    (lift hoist4 crate3)
    (lift hoist4 crate4)
    (lift hoist4 crate5)
    (lift hoist4 crate6)
    (lift hoist4 crate7)
    (lift hoist4 crate8)
    (lift hoist4 crate9)
    (lift hoist5 crate0)
    (lift hoist5 crate1)
    (lift hoist5 crate2)
    (lift hoist5 crate3)
    (lift hoist5 crate4)
    (lift hoist5 crate5)
    (lift hoist5 crate6)
    (lift hoist5 crate7)
    (lift hoist5 crate8)
    (lift hoist5 crate9)
    (lift hoist6 crate0)
    (lift hoist6 crate1)
    (lift hoist6 crate2)
    (lift hoist6 crate3)
    (lift hoist6 crate4)
    (lift hoist6 crate5)
    (lift hoist6 crate6)
    (lift hoist6 crate7)
    (lift hoist6 crate8)
    (lift hoist6 crate9)
    (lift hoist7 crate0)
    (lift hoist7 crate1)
    (lift hoist7 crate2)
    (lift hoist7 crate3)
    (lift hoist7 crate4)
    (lift hoist7 crate5)
    (lift hoist7 crate6)
    (lift hoist7 crate7)
    (lift hoist7 crate8)
    (lift hoist7 crate9)
    (lift hoist8 crate0)
    (lift hoist8 crate1)
    (lift hoist8 crate2)
    (lift hoist8 crate3)
    (lift hoist8 crate4)
    (lift hoist8 crate5)
    (lift hoist8 crate6)
    (lift hoist8 crate7)
    (lift hoist8 crate8)
    (lift hoist8 crate9)
    (lift hoist9 crate0)
    (lift hoist9 crate1)
    (lift hoist9 crate2)
    (lift hoist9 crate3)
    (lift hoist9 crate4)
    (lift hoist9 crate5)
    (lift hoist9 crate6)
    (lift hoist9 crate7)
    (lift hoist9 crate8)
    (lift hoist9 crate9)
    (lift hoist10 crate0)
    (lift hoist10 crate1)
    (lift hoist10 crate2)
    (lift hoist10 crate3)
    (lift hoist10 crate4)
    (lift hoist10 crate5)
    (lift hoist10 crate6)
    (lift hoist10 crate7)
    (lift hoist10 crate8)
    (lift hoist10 crate9)
    (lift hoist11 crate0)
    (lift hoist11 crate1)
    (lift hoist11 crate2)
    (lift hoist11 crate3)
    (lift hoist11 crate4)
    (lift hoist11 crate5)
    (lift hoist11 crate6)
    (lift hoist11 crate7)
    (lift hoist11 crate8)
    (lift hoist11 crate9)
    (lift hoist12 crate0)
    (lift hoist12 crate1)
    (lift hoist12 crate2)
    (lift hoist12 crate3)
    (lift hoist12 crate4)
    (lift hoist12 crate5)
    (lift hoist12 crate6)
    (lift hoist12 crate7)
    (lift hoist12 crate8)
    (lift hoist12 crate9)
    (lift hoist13 crate0)
    (lift hoist13 crate1)
    (lift hoist13 crate2)
    (lift hoist13 crate3)
    (lift hoist13 crate4)
    (lift hoist13 crate5)
    (lift hoist13 crate6)
    (lift hoist13 crate7)
    (lift hoist13 crate8)
    (lift hoist13 crate9)
    (lift hoist14 crate0)
    (lift hoist14 crate1)
    (lift hoist14 crate2)
    (lift hoist14 crate3)
    (lift hoist14 crate4)
    (lift hoist14 crate5)
    (lift hoist14 crate6)
    (lift hoist14 crate7)
    (lift hoist14 crate8)
    (lift hoist14 crate9)
    (drop hoist0 crate0)
    (drop hoist0 crate1)
    (drop hoist0 crate2)
    (drop hoist0 crate3)
    (drop hoist0 crate4)
    (drop hoist0 crate5)
    (drop hoist0 crate6)
    (drop hoist0 crate7)
    (drop hoist0 crate8)
    (drop hoist0 crate9)
    (drop hoist1 crate0)
    (drop hoist1 crate1)
    (drop hoist1 crate2)
    (drop hoist1 crate3)
    (drop hoist1 crate4)
    (drop hoist1 crate5)
    (drop hoist1 crate6)
    (drop hoist1 crate7)
    (drop hoist1 crate8)
    (drop hoist1 crate9)
    (drop hoist2 crate0)
    (drop hoist2 crate1)
    (drop hoist2 crate2)
    (drop hoist2 crate3)
    (drop hoist2 crate4)
    (drop hoist2 crate5)
    (drop hoist2 crate6)
    (drop hoist2 crate7)
    (drop hoist2 crate8)
    (drop hoist2 crate9)
    (drop hoist3 crate0)
    (drop hoist3 crate1)
    (drop hoist3 crate2)
    (drop hoist3 crate3)
    (drop hoist3 crate4)
    (drop hoist3 crate5)
    (drop hoist3 crate6)
    (drop hoist3 crate7)
    (drop hoist3 crate8)
    (drop hoist3 crate9)
    (drop hoist4 crate0)
    (drop hoist4 crate1)
    (drop hoist4 crate2)
    (drop hoist4 crate3)
    (drop hoist4 crate4)
    (drop hoist4 crate5)
    (drop hoist4 crate6)
    (drop hoist4 crate7)
    (drop hoist4 crate8)
    (drop hoist4 crate9)
    (drop hoist5 crate0)
    (drop hoist5 crate1)
    (drop hoist5 crate2)
    (drop hoist5 crate3)
    (drop hoist5 crate4)
    (drop hoist5 crate5)
    (drop hoist5 crate6)
    (drop hoist5 crate7)
    (drop hoist5 crate8)
    (drop hoist5 crate9)
    (drop hoist6 crate0)
    (drop hoist6 crate1)
    (drop hoist6 crate2)
    (drop hoist6 crate3)
    (drop hoist6 crate4)
    (drop hoist6 crate5)
    (drop hoist6 crate6)
    (drop hoist6 crate7)
    (drop hoist6 crate8)
    (drop hoist6 crate9)
    (drop hoist7 crate0)
    (drop hoist7 crate1)
    (drop hoist7 crate2)
    (drop hoist7 crate3)
    (drop hoist7 crate4)
    (drop hoist7 crate5)
    (drop hoist7 crate6)
    (drop hoist7 crate7)
    (drop hoist7 crate8)
    (drop hoist7 crate9)
    (drop hoist8 crate0)
    (drop hoist8 crate1)
    (drop hoist8 crate2)
    (drop hoist8 crate3)
    (drop hoist8 crate4)
    (drop hoist8 crate5)
    (drop hoist8 crate6)
    (drop hoist8 crate7)
    (drop hoist8 crate8)
    (drop hoist8 crate9)
    (drop hoist9 crate0)
    (drop hoist9 crate1)
    (drop hoist9 crate2)
    (drop hoist9 crate3)
    (drop hoist9 crate4)
    (drop hoist9 crate5)
    (drop hoist9 crate6)
    (drop hoist9 crate7)
    (drop hoist9 crate8)
    (drop hoist9 crate9)
    (drop hoist10 crate0)
    (drop hoist10 crate1)
    (drop hoist10 crate2)
    (drop hoist10 crate3)
    (drop hoist10 crate4)
    (drop hoist10 crate5)
    (drop hoist10 crate6)
    (drop hoist10 crate7)
    (drop hoist10 crate8)
    (drop hoist10 crate9)
    (drop hoist11 crate0)
    (drop hoist11 crate1)
    (drop hoist11 crate2)
    (drop hoist11 crate3)
    (drop hoist11 crate4)
    (drop hoist11 crate5)
    (drop hoist11 crate6)
    (drop hoist11 crate7)
    (drop hoist11 crate8)
    (drop hoist11 crate9)
    (drop hoist12 crate0)
    (drop hoist12 crate1)
    (drop hoist12 crate2)
    (drop hoist12 crate3)
    (drop hoist12 crate4)
    (drop hoist12 crate5)
    (drop hoist12 crate6)
    (drop hoist12 crate7)
    (drop hoist12 crate8)
    (drop hoist12 crate9)
    (drop hoist13 crate0)
    (drop hoist13 crate1)
    (drop hoist13 crate2)
    (drop hoist13 crate3)
    (drop hoist13 crate4)
    (drop hoist13 crate5)
    (drop hoist13 crate6)
    (drop hoist13 crate7)
    (drop hoist13 crate8)
    (drop hoist13 crate9)
    (drop hoist14 crate0)
    (drop hoist14 crate1)
    (drop hoist14 crate2)
    (drop hoist14 crate3)
    (drop hoist14 crate4)
    (drop hoist14 crate5)
    (drop hoist14 crate6)
    (drop hoist14 crate7)
    (drop hoist14 crate8)
    (drop hoist14 crate9)
    (load hoist0 crate0 truck0)
    (load hoist0 crate0 truck1)
    (load hoist0 crate0 truck2)
    (load hoist0 crate0 truck3)
    (load hoist0 crate0 truck4)
    (load hoist0 crate0 truck5)
    (load hoist0 crate1 truck0)
    (load hoist0 crate1 truck1)
    (load hoist0 crate1 truck2)
    (load hoist0 crate1 truck3)
    (load hoist0 crate1 truck4)
    (load hoist0 crate1 truck5)
    (load hoist0 crate2 truck0)
    (load hoist0 crate2 truck1)
    (load hoist0 crate2 truck2)
    (load hoist0 crate2 truck3)
    (load hoist0 crate2 truck4)
    (load hoist0 crate2 truck5)
    (load hoist0 crate3 truck0)
    (load hoist0 crate3 truck1)
    (load hoist0 crate3 truck2)
    (load hoist0 crate3 truck3)
    (load hoist0 crate3 truck4)
    (load hoist0 crate3 truck5)
    (load hoist0 crate4 truck0)
    (load hoist0 crate4 truck1)
    (load hoist0 crate4 truck2)
    (load hoist0 crate4 truck3)
    (load hoist0 crate4 truck4)
    (load hoist0 crate4 truck5)
    (load hoist0 crate5 truck0)
    (load hoist0 crate5 truck1)
    (load hoist0 crate5 truck2)
    (load hoist0 crate5 truck3)
    (load hoist0 crate5 truck4)
    (load hoist0 crate5 truck5)
    (load hoist0 crate6 truck0)
    (load hoist0 crate6 truck1)
    (load hoist0 crate6 truck2)
    (load hoist0 crate6 truck3)
    (load hoist0 crate6 truck4)
    (load hoist0 crate6 truck5)
    (load hoist0 crate7 truck0)
    (load hoist0 crate7 truck1)
    (load hoist0 crate7 truck2)
    (load hoist0 crate7 truck3)
    (load hoist0 crate7 truck4)
    (load hoist0 crate7 truck5)
    (load hoist0 crate8 truck0)
    (load hoist0 crate8 truck1)
    (load hoist0 crate8 truck2)
    (load hoist0 crate8 truck3)
    (load hoist0 crate8 truck4)
    (load hoist0 crate8 truck5)
    (load hoist0 crate9 truck0)
    (load hoist0 crate9 truck1)
    (load hoist0 crate9 truck2)
    (load hoist0 crate9 truck3)
    (load hoist0 crate9 truck4)
    (load hoist0 crate9 truck5)
    (load hoist1 crate0 truck0)
    (load hoist1 crate0 truck1)
    (load hoist1 crate0 truck2)
    (load hoist1 crate0 truck3)
    (load hoist1 crate0 truck4)
    (load hoist1 crate0 truck5)
    (load hoist1 crate1 truck0)
    (load hoist1 crate1 truck1)
    (load hoist1 crate1 truck2)
    (load hoist1 crate1 truck3)
    (load hoist1 crate1 truck4)
    (load hoist1 crate1 truck5)
    (load hoist1 crate2 truck0)
    (load hoist1 crate2 truck1)
    (load hoist1 crate2 truck2)
    (load hoist1 crate2 truck3)
    (load hoist1 crate2 truck4)
    (load hoist1 crate2 truck5)
    (load hoist1 crate3 truck0)
    (load hoist1 crate3 truck1)
    (load hoist1 crate3 truck2)
    (load hoist1 crate3 truck3)
    (load hoist1 crate3 truck4)
    (load hoist1 crate3 truck5)
    (load hoist1 crate4 truck0)
    (load hoist1 crate4 truck1)
    (load hoist1 crate4 truck2)
    (load hoist1 crate4 truck3)
    (load hoist1 crate4 truck4)
    (load hoist1 crate4 truck5)
    (load hoist1 crate5 truck0)
    (load hoist1 crate5 truck1)
    (load hoist1 crate5 truck2)
    (load hoist1 crate5 truck3)
    (load hoist1 crate5 truck4)
    (load hoist1 crate5 truck5)
    (load hoist1 crate6 truck0)
    (load hoist1 crate6 truck1)
    (load hoist1 crate6 truck2)
    (load hoist1 crate6 truck3)
    (load hoist1 crate6 truck4)
    (load hoist1 crate6 truck5)
    (load hoist1 crate7 truck0)
    (load hoist1 crate7 truck1)
    (load hoist1 crate7 truck2)
    (load hoist1 crate7 truck3)
    (load hoist1 crate7 truck4)
    (load hoist1 crate7 truck5)
    (load hoist1 crate8 truck0)
    (load hoist1 crate8 truck1)
    (load hoist1 crate8 truck2)
    (load hoist1 crate8 truck3)
    (load hoist1 crate8 truck4)
    (load hoist1 crate8 truck5)
    (load hoist1 crate9 truck0)
    (load hoist1 crate9 truck1)
    (load hoist1 crate9 truck2)
    (load hoist1 crate9 truck3)
    (load hoist1 crate9 truck4)
    (load hoist1 crate9 truck5)
    (load hoist2 crate0 truck0)
    (load hoist2 crate0 truck1)
    (load hoist2 crate0 truck2)
    (load hoist2 crate0 truck3)
    (load hoist2 crate0 truck4)
    (load hoist2 crate0 truck5)
    (load hoist2 crate1 truck0)
    (load hoist2 crate1 truck1)
    (load hoist2 crate1 truck2)
    (load hoist2 crate1 truck3)
    (load hoist2 crate1 truck4)
    (load hoist2 crate1 truck5)
    (load hoist2 crate2 truck0)
    (load hoist2 crate2 truck1)
    (load hoist2 crate2 truck2)
    (load hoist2 crate2 truck3)
    (load hoist2 crate2 truck4)
    (load hoist2 crate2 truck5)
    (load hoist2 crate3 truck0)
    (load hoist2 crate3 truck1)
    (load hoist2 crate3 truck2)
    (load hoist2 crate3 truck3)
    (load hoist2 crate3 truck4)
    (load hoist2 crate3 truck5)
    (load hoist2 crate4 truck0)
    (load hoist2 crate4 truck1)
    (load hoist2 crate4 truck2)
    (load hoist2 crate4 truck3)
    (load hoist2 crate4 truck4)
    (load hoist2 crate4 truck5)
    (load hoist2 crate5 truck0)
    (load hoist2 crate5 truck1)
    (load hoist2 crate5 truck2)
    (load hoist2 crate5 truck3)
    (load hoist2 crate5 truck4)
    (load hoist2 crate5 truck5)
    (load hoist2 crate6 truck0)
    (load hoist2 crate6 truck1)
    (load hoist2 crate6 truck2)
    (load hoist2 crate6 truck3)
    (load hoist2 crate6 truck4)
    (load hoist2 crate6 truck5)
    (load hoist2 crate7 truck0)
    (load hoist2 crate7 truck1)
    (load hoist2 crate7 truck2)
    (load hoist2 crate7 truck3)
    (load hoist2 crate7 truck4)
    (load hoist2 crate7 truck5)
    (load hoist2 crate8 truck0)
    (load hoist2 crate8 truck1)
    (load hoist2 crate8 truck2)
    (load hoist2 crate8 truck3)
    (load hoist2 crate8 truck4)
    (load hoist2 crate8 truck5)
    (load hoist2 crate9 truck0)
    (load hoist2 crate9 truck1)
    (load hoist2 crate9 truck2)
    (load hoist2 crate9 truck3)
    (load hoist2 crate9 truck4)
    (load hoist2 crate9 truck5)
    (load hoist3 crate0 truck0)
    (load hoist3 crate0 truck1)
    (load hoist3 crate0 truck2)
    (load hoist3 crate0 truck3)
    (load hoist3 crate0 truck4)
    (load hoist3 crate0 truck5)
    (load hoist3 crate1 truck0)
    (load hoist3 crate1 truck1)
    (load hoist3 crate1 truck2)
    (load hoist3 crate1 truck3)
    (load hoist3 crate1 truck4)
    (load hoist3 crate1 truck5)
    (load hoist3 crate2 truck0)
    (load hoist3 crate2 truck1)
    (load hoist3 crate2 truck2)
    (load hoist3 crate2 truck3)
    (load hoist3 crate2 truck4)
    (load hoist3 crate2 truck5)
    (load hoist3 crate3 truck0)
    (load hoist3 crate3 truck1)
    (load hoist3 crate3 truck2)
    (load hoist3 crate3 truck3)
    (load hoist3 crate3 truck4)
    (load hoist3 crate3 truck5)
    (load hoist3 crate4 truck0)
    (load hoist3 crate4 truck1)
    (load hoist3 crate4 truck2)
    (load hoist3 crate4 truck3)
    (load hoist3 crate4 truck4)
    (load hoist3 crate4 truck5)
    (load hoist3 crate5 truck0)
    (load hoist3 crate5 truck1)
    (load hoist3 crate5 truck2)
    (load hoist3 crate5 truck3)
    (load hoist3 crate5 truck4)
    (load hoist3 crate5 truck5)
    (load hoist3 crate6 truck0)
    (load hoist3 crate6 truck1)
    (load hoist3 crate6 truck2)
    (load hoist3 crate6 truck3)
    (load hoist3 crate6 truck4)
    (load hoist3 crate6 truck5)
    (load hoist3 crate7 truck0)
    (load hoist3 crate7 truck1)
    (load hoist3 crate7 truck2)
    (load hoist3 crate7 truck3)
    (load hoist3 crate7 truck4)
    (load hoist3 crate7 truck5)
    (load hoist3 crate8 truck0)
    (load hoist3 crate8 truck1)
    (load hoist3 crate8 truck2)
    (load hoist3 crate8 truck3)
    (load hoist3 crate8 truck4)
    (load hoist3 crate8 truck5)
    (load hoist3 crate9 truck0)
    (load hoist3 crate9 truck1)
    (load hoist3 crate9 truck2)
    (load hoist3 crate9 truck3)
    (load hoist3 crate9 truck4)
    (load hoist3 crate9 truck5)
    (load hoist4 crate0 truck0)
    (load hoist4 crate0 truck1)
    (load hoist4 crate0 truck2)
    (load hoist4 crate0 truck3)
    (load hoist4 crate0 truck4)
    (load hoist4 crate0 truck5)
    (load hoist4 crate1 truck0)
    (load hoist4 crate1 truck1)
    (load hoist4 crate1 truck2)
    (load hoist4 crate1 truck3)
    (load hoist4 crate1 truck4)
    (load hoist4 crate1 truck5)
    (load hoist4 crate2 truck0)
    (load hoist4 crate2 truck1)
    (load hoist4 crate2 truck2)
    (load hoist4 crate2 truck3)
    (load hoist4 crate2 truck4)
    (load hoist4 crate2 truck5)
    (load hoist4 crate3 truck0)
    (load hoist4 crate3 truck1)
    (load hoist4 crate3 truck2)
    (load hoist4 crate3 truck3)
    (load hoist4 crate3 truck4)
    (load hoist4 crate3 truck5)
    (load hoist4 crate4 truck0)
    (load hoist4 crate4 truck1)
    (load hoist4 crate4 truck2)
    (load hoist4 crate4 truck3)
    (load hoist4 crate4 truck4)
    (load hoist4 crate4 truck5)
    (load hoist4 crate5 truck0)
    (load hoist4 crate5 truck1)
    (load hoist4 crate5 truck2)
    (load hoist4 crate5 truck3)
    (load hoist4 crate5 truck4)
    (load hoist4 crate5 truck5)
    (load hoist4 crate6 truck0)
    (load hoist4 crate6 truck1)
    (load hoist4 crate6 truck2)
    (load hoist4 crate6 truck3)
    (load hoist4 crate6 truck4)
    (load hoist4 crate6 truck5)
    (load hoist4 crate7 truck0)
    (load hoist4 crate7 truck1)
    (load hoist4 crate7 truck2)
    (load hoist4 crate7 truck3)
    (load hoist4 crate7 truck4)
    (load hoist4 crate7 truck5)
    (load hoist4 crate8 truck0)
    (load hoist4 crate8 truck1)
    (load hoist4 crate8 truck2)
    (load hoist4 crate8 truck3)
    (load hoist4 crate8 truck4)
    (load hoist4 crate8 truck5)
    (load hoist4 crate9 truck0)
    (load hoist4 crate9 truck1)
    (load hoist4 crate9 truck2)
    (load hoist4 crate9 truck3)
    (load hoist4 crate9 truck4)
    (load hoist4 crate9 truck5)
    (load hoist5 crate0 truck0)
    (load hoist5 crate0 truck1)
    (load hoist5 crate0 truck2)
    (load hoist5 crate0 truck3)
    (load hoist5 crate0 truck4)
    (load hoist5 crate0 truck5)
    (load hoist5 crate1 truck0)
    (load hoist5 crate1 truck1)
    (load hoist5 crate1 truck2)
    (load hoist5 crate1 truck3)
    (load hoist5 crate1 truck4)
    (load hoist5 crate1 truck5)
    (load hoist5 crate2 truck0)
    (load hoist5 crate2 truck1)
    (load hoist5 crate2 truck2)
    (load hoist5 crate2 truck3)
    (load hoist5 crate2 truck4)
    (load hoist5 crate2 truck5)
    (load hoist5 crate3 truck0)
    (load hoist5 crate3 truck1)
    (load hoist5 crate3 truck2)
    (load hoist5 crate3 truck3)
    (load hoist5 crate3 truck4)
    (load hoist5 crate3 truck5)
    (load hoist5 crate4 truck0)
    (load hoist5 crate4 truck1)
    (load hoist5 crate4 truck2)
    (load hoist5 crate4 truck3)
    (load hoist5 crate4 truck4)
    (load hoist5 crate4 truck5)
    (load hoist5 crate5 truck0)
    (load hoist5 crate5 truck1)
    (load hoist5 crate5 truck2)
    (load hoist5 crate5 truck3)
    (load hoist5 crate5 truck4)
    (load hoist5 crate5 truck5)
    (load hoist5 crate6 truck0)
    (load hoist5 crate6 truck1)
    (load hoist5 crate6 truck2)
    (load hoist5 crate6 truck3)
    (load hoist5 crate6 truck4)
    (load hoist5 crate6 truck5)
    (load hoist5 crate7 truck0)
    (load hoist5 crate7 truck1)
    (load hoist5 crate7 truck2)
    (load hoist5 crate7 truck3)
    (load hoist5 crate7 truck4)
    (load hoist5 crate7 truck5)
    (load hoist5 crate8 truck0)
    (load hoist5 crate8 truck1)
    (load hoist5 crate8 truck2)
    (load hoist5 crate8 truck3)
    (load hoist5 crate8 truck4)
    (load hoist5 crate8 truck5)
    (load hoist5 crate9 truck0)
    (load hoist5 crate9 truck1)
    (load hoist5 crate9 truck2)
    (load hoist5 crate9 truck3)
    (load hoist5 crate9 truck4)
    (load hoist5 crate9 truck5)
    (load hoist6 crate0 truck0)
    (load hoist6 crate0 truck1)
    (load hoist6 crate0 truck2)
    (load hoist6 crate0 truck3)
    (load hoist6 crate0 truck4)
    (load hoist6 crate0 truck5)
    (load hoist6 crate1 truck0)
    (load hoist6 crate1 truck1)
    (load hoist6 crate1 truck2)
    (load hoist6 crate1 truck3)
    (load hoist6 crate1 truck4)
    (load hoist6 crate1 truck5)
    (load hoist6 crate2 truck0)
    (load hoist6 crate2 truck1)
    (load hoist6 crate2 truck2)
    (load hoist6 crate2 truck3)
    (load hoist6 crate2 truck4)
    (load hoist6 crate2 truck5)
    (load hoist6 crate3 truck0)
    (load hoist6 crate3 truck1)
    (load hoist6 crate3 truck2)
    (load hoist6 crate3 truck3)
    (load hoist6 crate3 truck4)
    (load hoist6 crate3 truck5)
    (load hoist6 crate4 truck0)
    (load hoist6 crate4 truck1)
    (load hoist6 crate4 truck2)
    (load hoist6 crate4 truck3)
    (load hoist6 crate4 truck4)
    (load hoist6 crate4 truck5)
    (load hoist6 crate5 truck0)
    (load hoist6 crate5 truck1)
    (load hoist6 crate5 truck2)
    (load hoist6 crate5 truck3)
    (load hoist6 crate5 truck4)
    (load hoist6 crate5 truck5)
    (load hoist6 crate6 truck0)
    (load hoist6 crate6 truck1)
    (load hoist6 crate6 truck2)
    (load hoist6 crate6 truck3)
    (load hoist6 crate6 truck4)
    (load hoist6 crate6 truck5)
    (load hoist6 crate7 truck0)
    (load hoist6 crate7 truck1)
    (load hoist6 crate7 truck2)
    (load hoist6 crate7 truck3)
    (load hoist6 crate7 truck4)
    (load hoist6 crate7 truck5)
    (load hoist6 crate8 truck0)
    (load hoist6 crate8 truck1)
    (load hoist6 crate8 truck2)
    (load hoist6 crate8 truck3)
    (load hoist6 crate8 truck4)
    (load hoist6 crate8 truck5)
    (load hoist6 crate9 truck0)
    (load hoist6 crate9 truck1)
    (load hoist6 crate9 truck2)
    (load hoist6 crate9 truck3)
    (load hoist6 crate9 truck4)
    (load hoist6 crate9 truck5)
    (load hoist7 crate0 truck0)
    (load hoist7 crate0 truck1)
    (load hoist7 crate0 truck2)
    (load hoist7 crate0 truck3)
    (load hoist7 crate0 truck4)
    (load hoist7 crate0 truck5)
    (load hoist7 crate1 truck0)
    (load hoist7 crate1 truck1)
    (load hoist7 crate1 truck2)
    (load hoist7 crate1 truck3)
    (load hoist7 crate1 truck4)
    (load hoist7 crate1 truck5)
    (load hoist7 crate2 truck0)
    (load hoist7 crate2 truck1)
    (load hoist7 crate2 truck2)
    (load hoist7 crate2 truck3)
    (load hoist7 crate2 truck4)
    (load hoist7 crate2 truck5)
    (load hoist7 crate3 truck0)
    (load hoist7 crate3 truck1)
    (load hoist7 crate3 truck2)
    (load hoist7 crate3 truck3)
    (load hoist7 crate3 truck4)
    (load hoist7 crate3 truck5)
    (load hoist7 crate4 truck0)
    (load hoist7 crate4 truck1)
    (load hoist7 crate4 truck2)
    (load hoist7 crate4 truck3)
    (load hoist7 crate4 truck4)
    (load hoist7 crate4 truck5)
    (load hoist7 crate5 truck0)
    (load hoist7 crate5 truck1)
    (load hoist7 crate5 truck2)
    (load hoist7 crate5 truck3)
    (load hoist7 crate5 truck4)
    (load hoist7 crate5 truck5)
    (load hoist7 crate6 truck0)
    (load hoist7 crate6 truck1)
    (load hoist7 crate6 truck2)
    (load hoist7 crate6 truck3)
    (load hoist7 crate6 truck4)
    (load hoist7 crate6 truck5)
    (load hoist7 crate7 truck0)
    (load hoist7 crate7 truck1)
    (load hoist7 crate7 truck2)
    (load hoist7 crate7 truck3)
    (load hoist7 crate7 truck4)
    (load hoist7 crate7 truck5)
    (load hoist7 crate8 truck0)
    (load hoist7 crate8 truck1)
    (load hoist7 crate8 truck2)
    (load hoist7 crate8 truck3)
    (load hoist7 crate8 truck4)
    (load hoist7 crate8 truck5)
    (load hoist7 crate9 truck0)
    (load hoist7 crate9 truck1)
    (load hoist7 crate9 truck2)
    (load hoist7 crate9 truck3)
    (load hoist7 crate9 truck4)
    (load hoist7 crate9 truck5)
    (load hoist8 crate0 truck0)
    (load hoist8 crate0 truck1)
    (load hoist8 crate0 truck2)
    (load hoist8 crate0 truck3)
    (load hoist8 crate0 truck4)
    (load hoist8 crate0 truck5)
    (load hoist8 crate1 truck0)
    (load hoist8 crate1 truck1)
    (load hoist8 crate1 truck2)
    (load hoist8 crate1 truck3)
    (load hoist8 crate1 truck4)
    (load hoist8 crate1 truck5)
    (load hoist8 crate2 truck0)
    (load hoist8 crate2 truck1)
    (load hoist8 crate2 truck2)
    (load hoist8 crate2 truck3)
    (load hoist8 crate2 truck4)
    (load hoist8 crate2 truck5)
    (load hoist8 crate3 truck0)
    (load hoist8 crate3 truck1)
    (load hoist8 crate3 truck2)
    (load hoist8 crate3 truck3)
    (load hoist8 crate3 truck4)
    (load hoist8 crate3 truck5)
    (load hoist8 crate4 truck0)
    (load hoist8 crate4 truck1)
    (load hoist8 crate4 truck2)
    (load hoist8 crate4 truck3)
    (load hoist8 crate4 truck4)
    (load hoist8 crate4 truck5)
    (load hoist8 crate5 truck0)
    (load hoist8 crate5 truck1)
    (load hoist8 crate5 truck2)
    (load hoist8 crate5 truck3)
    (load hoist8 crate5 truck4)
    (load hoist8 crate5 truck5)
    (load hoist8 crate6 truck0)
    (load hoist8 crate6 truck1)
    (load hoist8 crate6 truck2)
    (load hoist8 crate6 truck3)
    (load hoist8 crate6 truck4)
    (load hoist8 crate6 truck5)
    (load hoist8 crate7 truck0)
    (load hoist8 crate7 truck1)
    (load hoist8 crate7 truck2)
    (load hoist8 crate7 truck3)
    (load hoist8 crate7 truck4)
    (load hoist8 crate7 truck5)
    (load hoist8 crate8 truck0)
    (load hoist8 crate8 truck1)
    (load hoist8 crate8 truck2)
    (load hoist8 crate8 truck3)
    (load hoist8 crate8 truck4)
    (load hoist8 crate8 truck5)
    (load hoist8 crate9 truck0)
    (load hoist8 crate9 truck1)
    (load hoist8 crate9 truck2)
    (load hoist8 crate9 truck3)
    (load hoist8 crate9 truck4)
    (load hoist8 crate9 truck5)
    (load hoist9 crate0 truck0)
    (load hoist9 crate0 truck1)
    (load hoist9 crate0 truck2)
    (load hoist9 crate0 truck3)
    (load hoist9 crate0 truck4)
    (load hoist9 crate0 truck5)
    (load hoist9 crate1 truck0)
    (load hoist9 crate1 truck1)
    (load hoist9 crate1 truck2)
    (load hoist9 crate1 truck3)
    (load hoist9 crate1 truck4)
    (load hoist9 crate1 truck5)
    (load hoist9 crate2 truck0)
    (load hoist9 crate2 truck1)
    (load hoist9 crate2 truck2)
    (load hoist9 crate2 truck3)
    (load hoist9 crate2 truck4)
    (load hoist9 crate2 truck5)
    (load hoist9 crate3 truck0)
    (load hoist9 crate3 truck1)
    (load hoist9 crate3 truck2)
    (load hoist9 crate3 truck3)
    (load hoist9 crate3 truck4)
    (load hoist9 crate3 truck5)
    (load hoist9 crate4 truck0)
    (load hoist9 crate4 truck1)
    (load hoist9 crate4 truck2)
    (load hoist9 crate4 truck3)
    (load hoist9 crate4 truck4)
    (load hoist9 crate4 truck5)
    (load hoist9 crate5 truck0)
    (load hoist9 crate5 truck1)
    (load hoist9 crate5 truck2)
    (load hoist9 crate5 truck3)
    (load hoist9 crate5 truck4)
    (load hoist9 crate5 truck5)
    (load hoist9 crate6 truck0)
    (load hoist9 crate6 truck1)
    (load hoist9 crate6 truck2)
    (load hoist9 crate6 truck3)
    (load hoist9 crate6 truck4)
    (load hoist9 crate6 truck5)
    (load hoist9 crate7 truck0)
    (load hoist9 crate7 truck1)
    (load hoist9 crate7 truck2)
    (load hoist9 crate7 truck3)
    (load hoist9 crate7 truck4)
    (load hoist9 crate7 truck5)
    (load hoist9 crate8 truck0)
    (load hoist9 crate8 truck1)
    (load hoist9 crate8 truck2)
    (load hoist9 crate8 truck3)
    (load hoist9 crate8 truck4)
    (load hoist9 crate8 truck5)
    (load hoist9 crate9 truck0)
    (load hoist9 crate9 truck1)
    (load hoist9 crate9 truck2)
    (load hoist9 crate9 truck3)
    (load hoist9 crate9 truck4)
    (load hoist9 crate9 truck5)
    (load hoist10 crate0 truck0)
    (load hoist10 crate0 truck1)
    (load hoist10 crate0 truck2)
    (load hoist10 crate0 truck3)
    (load hoist10 crate0 truck4)
    (load hoist10 crate0 truck5)
    (load hoist10 crate1 truck0)
    (load hoist10 crate1 truck1)
    (load hoist10 crate1 truck2)
    (load hoist10 crate1 truck3)
    (load hoist10 crate1 truck4)
    (load hoist10 crate1 truck5)
    (load hoist10 crate2 truck0)
    (load hoist10 crate2 truck1)
    (load hoist10 crate2 truck2)
    (load hoist10 crate2 truck3)
    (load hoist10 crate2 truck4)
    (load hoist10 crate2 truck5)
    (load hoist10 crate3 truck0)
    (load hoist10 crate3 truck1)
    (load hoist10 crate3 truck2)
    (load hoist10 crate3 truck3)
    (load hoist10 crate3 truck4)
    (load hoist10 crate3 truck5)
    (load hoist10 crate4 truck0)
    (load hoist10 crate4 truck1)
    (load hoist10 crate4 truck2)
    (load hoist10 crate4 truck3)
    (load hoist10 crate4 truck4)
    (load hoist10 crate4 truck5)
    (load hoist10 crate5 truck0)
    (load hoist10 crate5 truck1)
    (load hoist10 crate5 truck2)
    (load hoist10 crate5 truck3)
    (load hoist10 crate5 truck4)
    (load hoist10 crate5 truck5)
    (load hoist10 crate6 truck0)
    (load hoist10 crate6 truck1)
    (load hoist10 crate6 truck2)
    (load hoist10 crate6 truck3)
    (load hoist10 crate6 truck4)
    (load hoist10 crate6 truck5)
    (load hoist10 crate7 truck0)
    (load hoist10 crate7 truck1)
    (load hoist10 crate7 truck2)
    (load hoist10 crate7 truck3)
    (load hoist10 crate7 truck4)
    (load hoist10 crate7 truck5)
    (load hoist10 crate8 truck0)
    (load hoist10 crate8 truck1)
    (load hoist10 crate8 truck2)
    (load hoist10 crate8 truck3)
    (load hoist10 crate8 truck4)
    (load hoist10 crate8 truck5)
    (load hoist10 crate9 truck0)
    (load hoist10 crate9 truck1)
    (load hoist10 crate9 truck2)
    (load hoist10 crate9 truck3)
    (load hoist10 crate9 truck4)
    (load hoist10 crate9 truck5)
    (load hoist11 crate0 truck0)
    (load hoist11 crate0 truck1)
    (load hoist11 crate0 truck2)
    (load hoist11 crate0 truck3)
    (load hoist11 crate0 truck4)
    (load hoist11 crate0 truck5)
    (load hoist11 crate1 truck0)
    (load hoist11 crate1 truck1)
    (load hoist11 crate1 truck2)
    (load hoist11 crate1 truck3)
    (load hoist11 crate1 truck4)
    (load hoist11 crate1 truck5)
    (load hoist11 crate2 truck0)
    (load hoist11 crate2 truck1)
    (load hoist11 crate2 truck2)
    (load hoist11 crate2 truck3)
    (load hoist11 crate2 truck4)
    (load hoist11 crate2 truck5)
    (load hoist11 crate3 truck0)
    (load hoist11 crate3 truck1)
    (load hoist11 crate3 truck2)
    (load hoist11 crate3 truck3)
    (load hoist11 crate3 truck4)
    (load hoist11 crate3 truck5)
    (load hoist11 crate4 truck0)
    (load hoist11 crate4 truck1)
    (load hoist11 crate4 truck2)
    (load hoist11 crate4 truck3)
    (load hoist11 crate4 truck4)
    (load hoist11 crate4 truck5)
    (load hoist11 crate5 truck0)
    (load hoist11 crate5 truck1)
    (load hoist11 crate5 truck2)
    (load hoist11 crate5 truck3)
    (load hoist11 crate5 truck4)
    (load hoist11 crate5 truck5)
    (load hoist11 crate6 truck0)
    (load hoist11 crate6 truck1)
    (load hoist11 crate6 truck2)
    (load hoist11 crate6 truck3)
    (load hoist11 crate6 truck4)
    (load hoist11 crate6 truck5)
    (load hoist11 crate7 truck0)
    (load hoist11 crate7 truck1)
    (load hoist11 crate7 truck2)
    (load hoist11 crate7 truck3)
    (load hoist11 crate7 truck4)
    (load hoist11 crate7 truck5)
    (load hoist11 crate8 truck0)
    (load hoist11 crate8 truck1)
    (load hoist11 crate8 truck2)
    (load hoist11 crate8 truck3)
    (load hoist11 crate8 truck4)
    (load hoist11 crate8 truck5)
    (load hoist11 crate9 truck0)
    (load hoist11 crate9 truck1)
    (load hoist11 crate9 truck2)
    (load hoist11 crate9 truck3)
    (load hoist11 crate9 truck4)
    (load hoist11 crate9 truck5)
    (load hoist12 crate0 truck0)
    (load hoist12 crate0 truck1)
    (load hoist12 crate0 truck2)
    (load hoist12 crate0 truck3)
    (load hoist12 crate0 truck4)
    (load hoist12 crate0 truck5)
    (load hoist12 crate1 truck0)
    (load hoist12 crate1 truck1)
    (load hoist12 crate1 truck2)
    (load hoist12 crate1 truck3)
    (load hoist12 crate1 truck4)
    (load hoist12 crate1 truck5)
    (load hoist12 crate2 truck0)
    (load hoist12 crate2 truck1)
    (load hoist12 crate2 truck2)
    (load hoist12 crate2 truck3)
    (load hoist12 crate2 truck4)
    (load hoist12 crate2 truck5)
    (load hoist12 crate3 truck0)
    (load hoist12 crate3 truck1)
    (load hoist12 crate3 truck2)
    (load hoist12 crate3 truck3)
    (load hoist12 crate3 truck4)
    (load hoist12 crate3 truck5)
    (load hoist12 crate4 truck0)
    (load hoist12 crate4 truck1)
    (load hoist12 crate4 truck2)
    (load hoist12 crate4 truck3)
    (load hoist12 crate4 truck4)
    (load hoist12 crate4 truck5)
    (load hoist12 crate5 truck0)
    (load hoist12 crate5 truck1)
    (load hoist12 crate5 truck2)
    (load hoist12 crate5 truck3)
    (load hoist12 crate5 truck4)
    (load hoist12 crate5 truck5)
    (load hoist12 crate6 truck0)
    (load hoist12 crate6 truck1)
    (load hoist12 crate6 truck2)
    (load hoist12 crate6 truck3)
    (load hoist12 crate6 truck4)
    (load hoist12 crate6 truck5)
    (load hoist12 crate7 truck0)
    (load hoist12 crate7 truck1)
    (load hoist12 crate7 truck2)
    (load hoist12 crate7 truck3)
    (load hoist12 crate7 truck4)
    (load hoist12 crate7 truck5)
    (load hoist12 crate8 truck0)
    (load hoist12 crate8 truck1)
    (load hoist12 crate8 truck2)
    (load hoist12 crate8 truck3)
    (load hoist12 crate8 truck4)
    (load hoist12 crate8 truck5)
    (load hoist12 crate9 truck0)
    (load hoist12 crate9 truck1)
    (load hoist12 crate9 truck2)
    (load hoist12 crate9 truck3)
    (load hoist12 crate9 truck4)
    (load hoist12 crate9 truck5)
    (load hoist13 crate0 truck0)
    (load hoist13 crate0 truck1)
    (load hoist13 crate0 truck2)
    (load hoist13 crate0 truck3)
    (load hoist13 crate0 truck4)
    (load hoist13 crate0 truck5)
    (load hoist13 crate1 truck0)
    (load hoist13 crate1 truck1)
    (load hoist13 crate1 truck2)
    (load hoist13 crate1 truck3)
    (load hoist13 crate1 truck4)
    (load hoist13 crate1 truck5)
    (load hoist13 crate2 truck0)
    (load hoist13 crate2 truck1)
    (load hoist13 crate2 truck2)
    (load hoist13 crate2 truck3)
    (load hoist13 crate2 truck4)
    (load hoist13 crate2 truck5)
    (load hoist13 crate3 truck0)
    (load hoist13 crate3 truck1)
    (load hoist13 crate3 truck2)
    (load hoist13 crate3 truck3)
    (load hoist13 crate3 truck4)
    (load hoist13 crate3 truck5)
    (load hoist13 crate4 truck0)
    (load hoist13 crate4 truck1)
    (load hoist13 crate4 truck2)
    (load hoist13 crate4 truck3)
    (load hoist13 crate4 truck4)
    (load hoist13 crate4 truck5)
    (load hoist13 crate5 truck0)
    (load hoist13 crate5 truck1)
    (load hoist13 crate5 truck2)
    (load hoist13 crate5 truck3)
    (load hoist13 crate5 truck4)
    (load hoist13 crate5 truck5)
    (load hoist13 crate6 truck0)
    (load hoist13 crate6 truck1)
    (load hoist13 crate6 truck2)
    (load hoist13 crate6 truck3)
    (load hoist13 crate6 truck4)
    (load hoist13 crate6 truck5)
    (load hoist13 crate7 truck0)
    (load hoist13 crate7 truck1)
    (load hoist13 crate7 truck2)
    (load hoist13 crate7 truck3)
    (load hoist13 crate7 truck4)
    (load hoist13 crate7 truck5)
    (load hoist13 crate8 truck0)
    (load hoist13 crate8 truck1)
    (load hoist13 crate8 truck2)
    (load hoist13 crate8 truck3)
    (load hoist13 crate8 truck4)
    (load hoist13 crate8 truck5)
    (load hoist13 crate9 truck0)
    (load hoist13 crate9 truck1)
    (load hoist13 crate9 truck2)
    (load hoist13 crate9 truck3)
    (load hoist13 crate9 truck4)
    (load hoist13 crate9 truck5)
    (load hoist14 crate0 truck0)
    (load hoist14 crate0 truck1)
    (load hoist14 crate0 truck2)
    (load hoist14 crate0 truck3)
    (load hoist14 crate0 truck4)
    (load hoist14 crate0 truck5)
    (load hoist14 crate1 truck0)
    (load hoist14 crate1 truck1)
    (load hoist14 crate1 truck2)
    (load hoist14 crate1 truck3)
    (load hoist14 crate1 truck4)
    (load hoist14 crate1 truck5)
    (load hoist14 crate2 truck0)
    (load hoist14 crate2 truck1)
    (load hoist14 crate2 truck2)
    (load hoist14 crate2 truck3)
    (load hoist14 crate2 truck4)
    (load hoist14 crate2 truck5)
    (load hoist14 crate3 truck0)
    (load hoist14 crate3 truck1)
    (load hoist14 crate3 truck2)
    (load hoist14 crate3 truck3)
    (load hoist14 crate3 truck4)
    (load hoist14 crate3 truck5)
    (load hoist14 crate4 truck0)
    (load hoist14 crate4 truck1)
    (load hoist14 crate4 truck2)
    (load hoist14 crate4 truck3)
    (load hoist14 crate4 truck4)
    (load hoist14 crate4 truck5)
    (load hoist14 crate5 truck0)
    (load hoist14 crate5 truck1)
    (load hoist14 crate5 truck2)
    (load hoist14 crate5 truck3)
    (load hoist14 crate5 truck4)
    (load hoist14 crate5 truck5)
    (load hoist14 crate6 truck0)
    (load hoist14 crate6 truck1)
    (load hoist14 crate6 truck2)
    (load hoist14 crate6 truck3)
    (load hoist14 crate6 truck4)
    (load hoist14 crate6 truck5)
    (load hoist14 crate7 truck0)
    (load hoist14 crate7 truck1)
    (load hoist14 crate7 truck2)
    (load hoist14 crate7 truck3)
    (load hoist14 crate7 truck4)
    (load hoist14 crate7 truck5)
    (load hoist14 crate8 truck0)
    (load hoist14 crate8 truck1)
    (load hoist14 crate8 truck2)
    (load hoist14 crate8 truck3)
    (load hoist14 crate8 truck4)
    (load hoist14 crate8 truck5)
    (load hoist14 crate9 truck0)
    (load hoist14 crate9 truck1)
    (load hoist14 crate9 truck2)
    (load hoist14 crate9 truck3)
    (load hoist14 crate9 truck4)
    (load hoist14 crate9 truck5)
    (unload hoist0 crate0 truck0)
    (unload hoist0 crate0 truck1)
    (unload hoist0 crate0 truck2)
    (unload hoist0 crate0 truck3)
    (unload hoist0 crate0 truck4)
    (unload hoist0 crate0 truck5)
    (unload hoist0 crate1 truck0)
    (unload hoist0 crate1 truck1)
    (unload hoist0 crate1 truck2)
    (unload hoist0 crate1 truck3)
    (unload hoist0 crate1 truck4)
    (unload hoist0 crate1 truck5)
    (unload hoist0 crate2 truck0)
    (unload hoist0 crate2 truck1)
    (unload hoist0 crate2 truck2)
    (unload hoist0 crate2 truck3)
    (unload hoist0 crate2 truck4)
    (unload hoist0 crate2 truck5)
    (unload hoist0 crate3 truck0)
    (unload hoist0 crate3 truck1)
    (unload hoist0 crate3 truck2)
    (unload hoist0 crate3 truck3)
    (unload hoist0 crate3 truck4)
    (unload hoist0 crate3 truck5)
    (unload hoist0 crate4 truck0)
    (unload hoist0 crate4 truck1)
    (unload hoist0 crate4 truck2)
    (unload hoist0 crate4 truck3)
    (unload hoist0 crate4 truck4)
    (unload hoist0 crate4 truck5)
    (unload hoist0 crate5 truck0)
    (unload hoist0 crate5 truck1)
    (unload hoist0 crate5 truck2)
    (unload hoist0 crate5 truck3)
    (unload hoist0 crate5 truck4)
    (unload hoist0 crate5 truck5)
    (unload hoist0 crate6 truck0)
    (unload hoist0 crate6 truck1)
    (unload hoist0 crate6 truck2)
    (unload hoist0 crate6 truck3)
    (unload hoist0 crate6 truck4)
    (unload hoist0 crate6 truck5)
    (unload hoist0 crate7 truck0)
    (unload hoist0 crate7 truck1)
    (unload hoist0 crate7 truck2)
    (unload hoist0 crate7 truck3)
    (unload hoist0 crate7 truck4)
    (unload hoist0 crate7 truck5)
    (unload hoist0 crate8 truck0)
    (unload hoist0 crate8 truck1)
    (unload hoist0 crate8 truck2)
    (unload hoist0 crate8 truck3)
    (unload hoist0 crate8 truck4)
    (unload hoist0 crate8 truck5)
    (unload hoist0 crate9 truck0)
    (unload hoist0 crate9 truck1)
    (unload hoist0 crate9 truck2)
    (unload hoist0 crate9 truck3)
    (unload hoist0 crate9 truck4)
    (unload hoist0 crate9 truck5)
    (unload hoist1 crate0 truck0)
    (unload hoist1 crate0 truck1)
    (unload hoist1 crate0 truck2)
    (unload hoist1 crate0 truck3)
    (unload hoist1 crate0 truck4)
    (unload hoist1 crate0 truck5)
    (unload hoist1 crate1 truck0)
    (unload hoist1 crate1 truck1)
    (unload hoist1 crate1 truck2)
    (unload hoist1 crate1 truck3)
    (unload hoist1 crate1 truck4)
    (unload hoist1 crate1 truck5)
    (unload hoist1 crate2 truck0)
    (unload hoist1 crate2 truck1)
    (unload hoist1 crate2 truck2)
    (unload hoist1 crate2 truck3)
    (unload hoist1 crate2 truck4)
    (unload hoist1 crate2 truck5)
    (unload hoist1 crate3 truck0)
    (unload hoist1 crate3 truck1)
    (unload hoist1 crate3 truck2)
    (unload hoist1 crate3 truck3)
    (unload hoist1 crate3 truck4)
    (unload hoist1 crate3 truck5)
    (unload hoist1 crate4 truck0)
    (unload hoist1 crate4 truck1)
    (unload hoist1 crate4 truck2)
    (unload hoist1 crate4 truck3)
    (unload hoist1 crate4 truck4)
    (unload hoist1 crate4 truck5)
    (unload hoist1 crate5 truck0)
    (unload hoist1 crate5 truck1)
    (unload hoist1 crate5 truck2)
    (unload hoist1 crate5 truck3)
    (unload hoist1 crate5 truck4)
    (unload hoist1 crate5 truck5)
    (unload hoist1 crate6 truck0)
    (unload hoist1 crate6 truck1)
    (unload hoist1 crate6 truck2)
    (unload hoist1 crate6 truck3)
    (unload hoist1 crate6 truck4)
    (unload hoist1 crate6 truck5)
    (unload hoist1 crate7 truck0)
    (unload hoist1 crate7 truck1)
    (unload hoist1 crate7 truck2)
    (unload hoist1 crate7 truck3)
    (unload hoist1 crate7 truck4)
    (unload hoist1 crate7 truck5)
    (unload hoist1 crate8 truck0)
    (unload hoist1 crate8 truck1)
    (unload hoist1 crate8 truck2)
    (unload hoist1 crate8 truck3)
    (unload hoist1 crate8 truck4)
    (unload hoist1 crate8 truck5)
    (unload hoist1 crate9 truck0)
    (unload hoist1 crate9 truck1)
    (unload hoist1 crate9 truck2)
    (unload hoist1 crate9 truck3)
    (unload hoist1 crate9 truck4)
    (unload hoist1 crate9 truck5)
    (unload hoist2 crate0 truck0)
    (unload hoist2 crate0 truck1)
    (unload hoist2 crate0 truck2)
    (unload hoist2 crate0 truck3)
    (unload hoist2 crate0 truck4)
    (unload hoist2 crate0 truck5)
    (unload hoist2 crate1 truck0)
    (unload hoist2 crate1 truck1)
    (unload hoist2 crate1 truck2)
    (unload hoist2 crate1 truck3)
    (unload hoist2 crate1 truck4)
    (unload hoist2 crate1 truck5)
    (unload hoist2 crate2 truck0)
    (unload hoist2 crate2 truck1)
    (unload hoist2 crate2 truck2)
    (unload hoist2 crate2 truck3)
    (unload hoist2 crate2 truck4)
    (unload hoist2 crate2 truck5)
    (unload hoist2 crate3 truck0)
    (unload hoist2 crate3 truck1)
    (unload hoist2 crate3 truck2)
    (unload hoist2 crate3 truck3)
    (unload hoist2 crate3 truck4)
    (unload hoist2 crate3 truck5)
    (unload hoist2 crate4 truck0)
    (unload hoist2 crate4 truck1)
    (unload hoist2 crate4 truck2)
    (unload hoist2 crate4 truck3)
    (unload hoist2 crate4 truck4)
    (unload hoist2 crate4 truck5)
    (unload hoist2 crate5 truck0)
    (unload hoist2 crate5 truck1)
    (unload hoist2 crate5 truck2)
    (unload hoist2 crate5 truck3)
    (unload hoist2 crate5 truck4)
    (unload hoist2 crate5 truck5)
    (unload hoist2 crate6 truck0)
    (unload hoist2 crate6 truck1)
    (unload hoist2 crate6 truck2)
    (unload hoist2 crate6 truck3)
    (unload hoist2 crate6 truck4)
    (unload hoist2 crate6 truck5)
    (unload hoist2 crate7 truck0)
    (unload hoist2 crate7 truck1)
    (unload hoist2 crate7 truck2)
    (unload hoist2 crate7 truck3)
    (unload hoist2 crate7 truck4)
    (unload hoist2 crate7 truck5)
    (unload hoist2 crate8 truck0)
    (unload hoist2 crate8 truck1)
    (unload hoist2 crate8 truck2)
    (unload hoist2 crate8 truck3)
    (unload hoist2 crate8 truck4)
    (unload hoist2 crate8 truck5)
    (unload hoist2 crate9 truck0)
    (unload hoist2 crate9 truck1)
    (unload hoist2 crate9 truck2)
    (unload hoist2 crate9 truck3)
    (unload hoist2 crate9 truck4)
    (unload hoist2 crate9 truck5)
    (unload hoist3 crate0 truck0)
    (unload hoist3 crate0 truck1)
    (unload hoist3 crate0 truck2)
    (unload hoist3 crate0 truck3)
    (unload hoist3 crate0 truck4)
    (unload hoist3 crate0 truck5)
    (unload hoist3 crate1 truck0)
    (unload hoist3 crate1 truck1)
    (unload hoist3 crate1 truck2)
    (unload hoist3 crate1 truck3)
    (unload hoist3 crate1 truck4)
    (unload hoist3 crate1 truck5)
    (unload hoist3 crate2 truck0)
    (unload hoist3 crate2 truck1)
    (unload hoist3 crate2 truck2)
    (unload hoist3 crate2 truck3)
    (unload hoist3 crate2 truck4)
    (unload hoist3 crate2 truck5)
    (unload hoist3 crate3 truck0)
    (unload hoist3 crate3 truck1)
    (unload hoist3 crate3 truck2)
    (unload hoist3 crate3 truck3)
    (unload hoist3 crate3 truck4)
    (unload hoist3 crate3 truck5)
    (unload hoist3 crate4 truck0)
    (unload hoist3 crate4 truck1)
    (unload hoist3 crate4 truck2)
    (unload hoist3 crate4 truck3)
    (unload hoist3 crate4 truck4)
    (unload hoist3 crate4 truck5)
    (unload hoist3 crate5 truck0)
    (unload hoist3 crate5 truck1)
    (unload hoist3 crate5 truck2)
    (unload hoist3 crate5 truck3)
    (unload hoist3 crate5 truck4)
    (unload hoist3 crate5 truck5)
    (unload hoist3 crate6 truck0)
    (unload hoist3 crate6 truck1)
    (unload hoist3 crate6 truck2)
    (unload hoist3 crate6 truck3)
    (unload hoist3 crate6 truck4)
    (unload hoist3 crate6 truck5)
    (unload hoist3 crate7 truck0)
    (unload hoist3 crate7 truck1)
    (unload hoist3 crate7 truck2)
    (unload hoist3 crate7 truck3)
    (unload hoist3 crate7 truck4)
    (unload hoist3 crate7 truck5)
    (unload hoist3 crate8 truck0)
    (unload hoist3 crate8 truck1)
    (unload hoist3 crate8 truck2)
    (unload hoist3 crate8 truck3)
    (unload hoist3 crate8 truck4)
    (unload hoist3 crate8 truck5)
    (unload hoist3 crate9 truck0)
    (unload hoist3 crate9 truck1)
    (unload hoist3 crate9 truck2)
    (unload hoist3 crate9 truck3)
    (unload hoist3 crate9 truck4)
    (unload hoist3 crate9 truck5)
    (unload hoist4 crate0 truck0)
    (unload hoist4 crate0 truck1)
    (unload hoist4 crate0 truck2)
    (unload hoist4 crate0 truck3)
    (unload hoist4 crate0 truck4)
    (unload hoist4 crate0 truck5)
    (unload hoist4 crate1 truck0)
    (unload hoist4 crate1 truck1)
    (unload hoist4 crate1 truck2)
    (unload hoist4 crate1 truck3)
    (unload hoist4 crate1 truck4)
    (unload hoist4 crate1 truck5)
    (unload hoist4 crate2 truck0)
    (unload hoist4 crate2 truck1)
    (unload hoist4 crate2 truck2)
    (unload hoist4 crate2 truck3)
    (unload hoist4 crate2 truck4)
    (unload hoist4 crate2 truck5)
    (unload hoist4 crate3 truck0)
    (unload hoist4 crate3 truck1)
    (unload hoist4 crate3 truck2)
    (unload hoist4 crate3 truck3)
    (unload hoist4 crate3 truck4)
    (unload hoist4 crate3 truck5)
    (unload hoist4 crate4 truck0)
    (unload hoist4 crate4 truck1)
    (unload hoist4 crate4 truck2)
    (unload hoist4 crate4 truck3)
    (unload hoist4 crate4 truck4)
    (unload hoist4 crate4 truck5)
    (unload hoist4 crate5 truck0)
    (unload hoist4 crate5 truck1)
    (unload hoist4 crate5 truck2)
    (unload hoist4 crate5 truck3)
    (unload hoist4 crate5 truck4)
    (unload hoist4 crate5 truck5)
    (unload hoist4 crate6 truck0)
    (unload hoist4 crate6 truck1)
    (unload hoist4 crate6 truck2)
    (unload hoist4 crate6 truck3)
    (unload hoist4 crate6 truck4)
    (unload hoist4 crate6 truck5)
    (unload hoist4 crate7 truck0)
    (unload hoist4 crate7 truck1)
    (unload hoist4 crate7 truck2)
    (unload hoist4 crate7 truck3)
    (unload hoist4 crate7 truck4)
    (unload hoist4 crate7 truck5)
    (unload hoist4 crate8 truck0)
    (unload hoist4 crate8 truck1)
    (unload hoist4 crate8 truck2)
    (unload hoist4 crate8 truck3)
    (unload hoist4 crate8 truck4)
    (unload hoist4 crate8 truck5)
    (unload hoist4 crate9 truck0)
    (unload hoist4 crate9 truck1)
    (unload hoist4 crate9 truck2)
    (unload hoist4 crate9 truck3)
    (unload hoist4 crate9 truck4)
    (unload hoist4 crate9 truck5)
    (unload hoist5 crate0 truck0)
    (unload hoist5 crate0 truck1)
    (unload hoist5 crate0 truck2)
    (unload hoist5 crate0 truck3)
    (unload hoist5 crate0 truck4)
    (unload hoist5 crate0 truck5)
    (unload hoist5 crate1 truck0)
    (unload hoist5 crate1 truck1)
    (unload hoist5 crate1 truck2)
    (unload hoist5 crate1 truck3)
    (unload hoist5 crate1 truck4)
    (unload hoist5 crate1 truck5)
    (unload hoist5 crate2 truck0)
    (unload hoist5 crate2 truck1)
    (unload hoist5 crate2 truck2)
    (unload hoist5 crate2 truck3)
    (unload hoist5 crate2 truck4)
    (unload hoist5 crate2 truck5)
    (unload hoist5 crate3 truck0)
    (unload hoist5 crate3 truck1)
    (unload hoist5 crate3 truck2)
    (unload hoist5 crate3 truck3)
    (unload hoist5 crate3 truck4)
    (unload hoist5 crate3 truck5)
    (unload hoist5 crate4 truck0)
    (unload hoist5 crate4 truck1)
    (unload hoist5 crate4 truck2)
    (unload hoist5 crate4 truck3)
    (unload hoist5 crate4 truck4)
    (unload hoist5 crate4 truck5)
    (unload hoist5 crate5 truck0)
    (unload hoist5 crate5 truck1)
    (unload hoist5 crate5 truck2)
    (unload hoist5 crate5 truck3)
    (unload hoist5 crate5 truck4)
    (unload hoist5 crate5 truck5)
    (unload hoist5 crate6 truck0)
    (unload hoist5 crate6 truck1)
    (unload hoist5 crate6 truck2)
    (unload hoist5 crate6 truck3)
    (unload hoist5 crate6 truck4)
    (unload hoist5 crate6 truck5)
    (unload hoist5 crate7 truck0)
    (unload hoist5 crate7 truck1)
    (unload hoist5 crate7 truck2)
    (unload hoist5 crate7 truck3)
    (unload hoist5 crate7 truck4)
    (unload hoist5 crate7 truck5)
    (unload hoist5 crate8 truck0)
    (unload hoist5 crate8 truck1)
    (unload hoist5 crate8 truck2)
    (unload hoist5 crate8 truck3)
    (unload hoist5 crate8 truck4)
    (unload hoist5 crate8 truck5)
    (unload hoist5 crate9 truck0)
    (unload hoist5 crate9 truck1)
    (unload hoist5 crate9 truck2)
    (unload hoist5 crate9 truck3)
    (unload hoist5 crate9 truck4)
    (unload hoist5 crate9 truck5)
    (unload hoist6 crate0 truck0)
    (unload hoist6 crate0 truck1)
    (unload hoist6 crate0 truck2)
    (unload hoist6 crate0 truck3)
    (unload hoist6 crate0 truck4)
    (unload hoist6 crate0 truck5)
    (unload hoist6 crate1 truck0)
    (unload hoist6 crate1 truck1)
    (unload hoist6 crate1 truck2)
    (unload hoist6 crate1 truck3)
    (unload hoist6 crate1 truck4)
    (unload hoist6 crate1 truck5)
    (unload hoist6 crate2 truck0)
    (unload hoist6 crate2 truck1)
    (unload hoist6 crate2 truck2)
    (unload hoist6 crate2 truck3)
    (unload hoist6 crate2 truck4)
    (unload hoist6 crate2 truck5)
    (unload hoist6 crate3 truck0)
    (unload hoist6 crate3 truck1)
    (unload hoist6 crate3 truck2)
    (unload hoist6 crate3 truck3)
    (unload hoist6 crate3 truck4)
    (unload hoist6 crate3 truck5)
    (unload hoist6 crate4 truck0)
    (unload hoist6 crate4 truck1)
    (unload hoist6 crate4 truck2)
    (unload hoist6 crate4 truck3)
    (unload hoist6 crate4 truck4)
    (unload hoist6 crate4 truck5)
    (unload hoist6 crate5 truck0)
    (unload hoist6 crate5 truck1)
    (unload hoist6 crate5 truck2)
    (unload hoist6 crate5 truck3)
    (unload hoist6 crate5 truck4)
    (unload hoist6 crate5 truck5)
    (unload hoist6 crate6 truck0)
    (unload hoist6 crate6 truck1)
    (unload hoist6 crate6 truck2)
    (unload hoist6 crate6 truck3)
    (unload hoist6 crate6 truck4)
    (unload hoist6 crate6 truck5)
    (unload hoist6 crate7 truck0)
    (unload hoist6 crate7 truck1)
    (unload hoist6 crate7 truck2)
    (unload hoist6 crate7 truck3)
    (unload hoist6 crate7 truck4)
    (unload hoist6 crate7 truck5)
    (unload hoist6 crate8 truck0)
    (unload hoist6 crate8 truck1)
    (unload hoist6 crate8 truck2)
    (unload hoist6 crate8 truck3)
    (unload hoist6 crate8 truck4)
    (unload hoist6 crate8 truck5)
    (unload hoist6 crate9 truck0)
    (unload hoist6 crate9 truck1)
    (unload hoist6 crate9 truck2)
    (unload hoist6 crate9 truck3)
    (unload hoist6 crate9 truck4)
    (unload hoist6 crate9 truck5)
    (unload hoist7 crate0 truck0)
    (unload hoist7 crate0 truck1)
    (unload hoist7 crate0 truck2)
    (unload hoist7 crate0 truck3)
    (unload hoist7 crate0 truck4)
    (unload hoist7 crate0 truck5)
    (unload hoist7 crate1 truck0)
    (unload hoist7 crate1 truck1)
    (unload hoist7 crate1 truck2)
    (unload hoist7 crate1 truck3)
    (unload hoist7 crate1 truck4)
    (unload hoist7 crate1 truck5)
    (unload hoist7 crate2 truck0)
    (unload hoist7 crate2 truck1)
    (unload hoist7 crate2 truck2)
    (unload hoist7 crate2 truck3)
    (unload hoist7 crate2 truck4)
    (unload hoist7 crate2 truck5)
    (unload hoist7 crate3 truck0)
    (unload hoist7 crate3 truck1)
    (unload hoist7 crate3 truck2)
    (unload hoist7 crate3 truck3)
    (unload hoist7 crate3 truck4)
    (unload hoist7 crate3 truck5)
    (unload hoist7 crate4 truck0)
    (unload hoist7 crate4 truck1)
    (unload hoist7 crate4 truck2)
    (unload hoist7 crate4 truck3)
    (unload hoist7 crate4 truck4)
    (unload hoist7 crate4 truck5)
    (unload hoist7 crate5 truck0)
    (unload hoist7 crate5 truck1)
    (unload hoist7 crate5 truck2)
    (unload hoist7 crate5 truck3)
    (unload hoist7 crate5 truck4)
    (unload hoist7 crate5 truck5)
    (unload hoist7 crate6 truck0)
    (unload hoist7 crate6 truck1)
    (unload hoist7 crate6 truck2)
    (unload hoist7 crate6 truck3)
    (unload hoist7 crate6 truck4)
    (unload hoist7 crate6 truck5)
    (unload hoist7 crate7 truck0)
    (unload hoist7 crate7 truck1)
    (unload hoist7 crate7 truck2)
    (unload hoist7 crate7 truck3)
    (unload hoist7 crate7 truck4)
    (unload hoist7 crate7 truck5)
    (unload hoist7 crate8 truck0)
    (unload hoist7 crate8 truck1)
    (unload hoist7 crate8 truck2)
    (unload hoist7 crate8 truck3)
    (unload hoist7 crate8 truck4)
    (unload hoist7 crate8 truck5)
    (unload hoist7 crate9 truck0)
    (unload hoist7 crate9 truck1)
    (unload hoist7 crate9 truck2)
    (unload hoist7 crate9 truck3)
    (unload hoist7 crate9 truck4)
    (unload hoist7 crate9 truck5)
    (unload hoist8 crate0 truck0)
    (unload hoist8 crate0 truck1)
    (unload hoist8 crate0 truck2)
    (unload hoist8 crate0 truck3)
    (unload hoist8 crate0 truck4)
    (unload hoist8 crate0 truck5)
    (unload hoist8 crate1 truck0)
    (unload hoist8 crate1 truck1)
    (unload hoist8 crate1 truck2)
    (unload hoist8 crate1 truck3)
    (unload hoist8 crate1 truck4)
    (unload hoist8 crate1 truck5)
    (unload hoist8 crate2 truck0)
    (unload hoist8 crate2 truck1)
    (unload hoist8 crate2 truck2)
    (unload hoist8 crate2 truck3)
    (unload hoist8 crate2 truck4)
    (unload hoist8 crate2 truck5)
    (unload hoist8 crate3 truck0)
    (unload hoist8 crate3 truck1)
    (unload hoist8 crate3 truck2)
    (unload hoist8 crate3 truck3)
    (unload hoist8 crate3 truck4)
    (unload hoist8 crate3 truck5)
    (unload hoist8 crate4 truck0)
    (unload hoist8 crate4 truck1)
    (unload hoist8 crate4 truck2)
    (unload hoist8 crate4 truck3)
    (unload hoist8 crate4 truck4)
    (unload hoist8 crate4 truck5)
    (unload hoist8 crate5 truck0)
    (unload hoist8 crate5 truck1)
    (unload hoist8 crate5 truck2)
    (unload hoist8 crate5 truck3)
    (unload hoist8 crate5 truck4)
    (unload hoist8 crate5 truck5)
    (unload hoist8 crate6 truck0)
    (unload hoist8 crate6 truck1)
    (unload hoist8 crate6 truck2)
    (unload hoist8 crate6 truck3)
    (unload hoist8 crate6 truck4)
    (unload hoist8 crate6 truck5)
    (unload hoist8 crate7 truck0)
    (unload hoist8 crate7 truck1)
    (unload hoist8 crate7 truck2)
    (unload hoist8 crate7 truck3)
    (unload hoist8 crate7 truck4)
    (unload hoist8 crate7 truck5)
    (unload hoist8 crate8 truck0)
    (unload hoist8 crate8 truck1)
    (unload hoist8 crate8 truck2)
    (unload hoist8 crate8 truck3)
    (unload hoist8 crate8 truck4)
    (unload hoist8 crate8 truck5)
    (unload hoist8 crate9 truck0)
    (unload hoist8 crate9 truck1)
    (unload hoist8 crate9 truck2)
    (unload hoist8 crate9 truck3)
    (unload hoist8 crate9 truck4)
    (unload hoist8 crate9 truck5)
    (unload hoist9 crate0 truck0)
    (unload hoist9 crate0 truck1)
    (unload hoist9 crate0 truck2)
    (unload hoist9 crate0 truck3)
    (unload hoist9 crate0 truck4)
    (unload hoist9 crate0 truck5)
    (unload hoist9 crate1 truck0)
    (unload hoist9 crate1 truck1)
    (unload hoist9 crate1 truck2)
    (unload hoist9 crate1 truck3)
    (unload hoist9 crate1 truck4)
    (unload hoist9 crate1 truck5)
    (unload hoist9 crate2 truck0)
    (unload hoist9 crate2 truck1)
    (unload hoist9 crate2 truck2)
    (unload hoist9 crate2 truck3)
    (unload hoist9 crate2 truck4)
    (unload hoist9 crate2 truck5)
    (unload hoist9 crate3 truck0)
    (unload hoist9 crate3 truck1)
    (unload hoist9 crate3 truck2)
    (unload hoist9 crate3 truck3)
    (unload hoist9 crate3 truck4)
    (unload hoist9 crate3 truck5)
    (unload hoist9 crate4 truck0)
    (unload hoist9 crate4 truck1)
    (unload hoist9 crate4 truck2)
    (unload hoist9 crate4 truck3)
    (unload hoist9 crate4 truck4)
    (unload hoist9 crate4 truck5)
    (unload hoist9 crate5 truck0)
    (unload hoist9 crate5 truck1)
    (unload hoist9 crate5 truck2)
    (unload hoist9 crate5 truck3)
    (unload hoist9 crate5 truck4)
    (unload hoist9 crate5 truck5)
    (unload hoist9 crate6 truck0)
    (unload hoist9 crate6 truck1)
    (unload hoist9 crate6 truck2)
    (unload hoist9 crate6 truck3)
    (unload hoist9 crate6 truck4)
    (unload hoist9 crate6 truck5)
    (unload hoist9 crate7 truck0)
    (unload hoist9 crate7 truck1)
    (unload hoist9 crate7 truck2)
    (unload hoist9 crate7 truck3)
    (unload hoist9 crate7 truck4)
    (unload hoist9 crate7 truck5)
    (unload hoist9 crate8 truck0)
    (unload hoist9 crate8 truck1)
    (unload hoist9 crate8 truck2)
    (unload hoist9 crate8 truck3)
    (unload hoist9 crate8 truck4)
    (unload hoist9 crate8 truck5)
    (unload hoist9 crate9 truck0)
    (unload hoist9 crate9 truck1)
    (unload hoist9 crate9 truck2)
    (unload hoist9 crate9 truck3)
    (unload hoist9 crate9 truck4)
    (unload hoist9 crate9 truck5)
    (unload hoist10 crate0 truck0)
    (unload hoist10 crate0 truck1)
    (unload hoist10 crate0 truck2)
    (unload hoist10 crate0 truck3)
    (unload hoist10 crate0 truck4)
    (unload hoist10 crate0 truck5)
    (unload hoist10 crate1 truck0)
    (unload hoist10 crate1 truck1)
    (unload hoist10 crate1 truck2)
    (unload hoist10 crate1 truck3)
    (unload hoist10 crate1 truck4)
    (unload hoist10 crate1 truck5)
    (unload hoist10 crate2 truck0)
    (unload hoist10 crate2 truck1)
    (unload hoist10 crate2 truck2)
    (unload hoist10 crate2 truck3)
    (unload hoist10 crate2 truck4)
    (unload hoist10 crate2 truck5)
    (unload hoist10 crate3 truck0)
    (unload hoist10 crate3 truck1)
    (unload hoist10 crate3 truck2)
    (unload hoist10 crate3 truck3)
    (unload hoist10 crate3 truck4)
    (unload hoist10 crate3 truck5)
    (unload hoist10 crate4 truck0)
    (unload hoist10 crate4 truck1)
    (unload hoist10 crate4 truck2)
    (unload hoist10 crate4 truck3)
    (unload hoist10 crate4 truck4)
    (unload hoist10 crate4 truck5)
    (unload hoist10 crate5 truck0)
    (unload hoist10 crate5 truck1)
    (unload hoist10 crate5 truck2)
    (unload hoist10 crate5 truck3)
    (unload hoist10 crate5 truck4)
    (unload hoist10 crate5 truck5)
    (unload hoist10 crate6 truck0)
    (unload hoist10 crate6 truck1)
    (unload hoist10 crate6 truck2)
    (unload hoist10 crate6 truck3)
    (unload hoist10 crate6 truck4)
    (unload hoist10 crate6 truck5)
    (unload hoist10 crate7 truck0)
    (unload hoist10 crate7 truck1)
    (unload hoist10 crate7 truck2)
    (unload hoist10 crate7 truck3)
    (unload hoist10 crate7 truck4)
    (unload hoist10 crate7 truck5)
    (unload hoist10 crate8 truck0)
    (unload hoist10 crate8 truck1)
    (unload hoist10 crate8 truck2)
    (unload hoist10 crate8 truck3)
    (unload hoist10 crate8 truck4)
    (unload hoist10 crate8 truck5)
    (unload hoist10 crate9 truck0)
    (unload hoist10 crate9 truck1)
    (unload hoist10 crate9 truck2)
    (unload hoist10 crate9 truck3)
    (unload hoist10 crate9 truck4)
    (unload hoist10 crate9 truck5)
    (unload hoist11 crate0 truck0)
    (unload hoist11 crate0 truck1)
    (unload hoist11 crate0 truck2)
    (unload hoist11 crate0 truck3)
    (unload hoist11 crate0 truck4)
    (unload hoist11 crate0 truck5)
    (unload hoist11 crate1 truck0)
    (unload hoist11 crate1 truck1)
    (unload hoist11 crate1 truck2)
    (unload hoist11 crate1 truck3)
    (unload hoist11 crate1 truck4)
    (unload hoist11 crate1 truck5)
    (unload hoist11 crate2 truck0)
    (unload hoist11 crate2 truck1)
    (unload hoist11 crate2 truck2)
    (unload hoist11 crate2 truck3)
    (unload hoist11 crate2 truck4)
    (unload hoist11 crate2 truck5)
    (unload hoist11 crate3 truck0)
    (unload hoist11 crate3 truck1)
    (unload hoist11 crate3 truck2)
    (unload hoist11 crate3 truck3)
    (unload hoist11 crate3 truck4)
    (unload hoist11 crate3 truck5)
    (unload hoist11 crate4 truck0)
    (unload hoist11 crate4 truck1)
    (unload hoist11 crate4 truck2)
    (unload hoist11 crate4 truck3)
    (unload hoist11 crate4 truck4)
    (unload hoist11 crate4 truck5)
    (unload hoist11 crate5 truck0)
    (unload hoist11 crate5 truck1)
    (unload hoist11 crate5 truck2)
    (unload hoist11 crate5 truck3)
    (unload hoist11 crate5 truck4)
    (unload hoist11 crate5 truck5)
    (unload hoist11 crate6 truck0)
    (unload hoist11 crate6 truck1)
    (unload hoist11 crate6 truck2)
    (unload hoist11 crate6 truck3)
    (unload hoist11 crate6 truck4)
    (unload hoist11 crate6 truck5)
    (unload hoist11 crate7 truck0)
    (unload hoist11 crate7 truck1)
    (unload hoist11 crate7 truck2)
    (unload hoist11 crate7 truck3)
    (unload hoist11 crate7 truck4)
    (unload hoist11 crate7 truck5)
    (unload hoist11 crate8 truck0)
    (unload hoist11 crate8 truck1)
    (unload hoist11 crate8 truck2)
    (unload hoist11 crate8 truck3)
    (unload hoist11 crate8 truck4)
    (unload hoist11 crate8 truck5)
    (unload hoist11 crate9 truck0)
    (unload hoist11 crate9 truck1)
    (unload hoist11 crate9 truck2)
    (unload hoist11 crate9 truck3)
    (unload hoist11 crate9 truck4)
    (unload hoist11 crate9 truck5)
    (unload hoist12 crate0 truck0)
    (unload hoist12 crate0 truck1)
    (unload hoist12 crate0 truck2)
    (unload hoist12 crate0 truck3)
    (unload hoist12 crate0 truck4)
    (unload hoist12 crate0 truck5)
    (unload hoist12 crate1 truck0)
    (unload hoist12 crate1 truck1)
    (unload hoist12 crate1 truck2)
    (unload hoist12 crate1 truck3)
    (unload hoist12 crate1 truck4)
    (unload hoist12 crate1 truck5)
    (unload hoist12 crate2 truck0)
    (unload hoist12 crate2 truck1)
    (unload hoist12 crate2 truck2)
    (unload hoist12 crate2 truck3)
    (unload hoist12 crate2 truck4)
    (unload hoist12 crate2 truck5)
    (unload hoist12 crate3 truck0)
    (unload hoist12 crate3 truck1)
    (unload hoist12 crate3 truck2)
    (unload hoist12 crate3 truck3)
    (unload hoist12 crate3 truck4)
    (unload hoist12 crate3 truck5)
    (unload hoist12 crate4 truck0)
    (unload hoist12 crate4 truck1)
    (unload hoist12 crate4 truck2)
    (unload hoist12 crate4 truck3)
    (unload hoist12 crate4 truck4)
    (unload hoist12 crate4 truck5)
    (unload hoist12 crate5 truck0)
    (unload hoist12 crate5 truck1)
    (unload hoist12 crate5 truck2)
    (unload hoist12 crate5 truck3)
    (unload hoist12 crate5 truck4)
    (unload hoist12 crate5 truck5)
    (unload hoist12 crate6 truck0)
    (unload hoist12 crate6 truck1)
    (unload hoist12 crate6 truck2)
    (unload hoist12 crate6 truck3)
    (unload hoist12 crate6 truck4)
    (unload hoist12 crate6 truck5)
    (unload hoist12 crate7 truck0)
    (unload hoist12 crate7 truck1)
    (unload hoist12 crate7 truck2)
    (unload hoist12 crate7 truck3)
    (unload hoist12 crate7 truck4)
    (unload hoist12 crate7 truck5)
    (unload hoist12 crate8 truck0)
    (unload hoist12 crate8 truck1)
    (unload hoist12 crate8 truck2)
    (unload hoist12 crate8 truck3)
    (unload hoist12 crate8 truck4)
    (unload hoist12 crate8 truck5)
    (unload hoist12 crate9 truck0)
    (unload hoist12 crate9 truck1)
    (unload hoist12 crate9 truck2)
    (unload hoist12 crate9 truck3)
    (unload hoist12 crate9 truck4)
    (unload hoist12 crate9 truck5)
    (unload hoist13 crate0 truck0)
    (unload hoist13 crate0 truck1)
    (unload hoist13 crate0 truck2)
    (unload hoist13 crate0 truck3)
    (unload hoist13 crate0 truck4)
    (unload hoist13 crate0 truck5)
    (unload hoist13 crate1 truck0)
    (unload hoist13 crate1 truck1)
    (unload hoist13 crate1 truck2)
    (unload hoist13 crate1 truck3)
    (unload hoist13 crate1 truck4)
    (unload hoist13 crate1 truck5)
    (unload hoist13 crate2 truck0)
    (unload hoist13 crate2 truck1)
    (unload hoist13 crate2 truck2)
    (unload hoist13 crate2 truck3)
    (unload hoist13 crate2 truck4)
    (unload hoist13 crate2 truck5)
    (unload hoist13 crate3 truck0)
    (unload hoist13 crate3 truck1)
    (unload hoist13 crate3 truck2)
    (unload hoist13 crate3 truck3)
    (unload hoist13 crate3 truck4)
    (unload hoist13 crate3 truck5)
    (unload hoist13 crate4 truck0)
    (unload hoist13 crate4 truck1)
    (unload hoist13 crate4 truck2)
    (unload hoist13 crate4 truck3)
    (unload hoist13 crate4 truck4)
    (unload hoist13 crate4 truck5)
    (unload hoist13 crate5 truck0)
    (unload hoist13 crate5 truck1)
    (unload hoist13 crate5 truck2)
    (unload hoist13 crate5 truck3)
    (unload hoist13 crate5 truck4)
    (unload hoist13 crate5 truck5)
    (unload hoist13 crate6 truck0)
    (unload hoist13 crate6 truck1)
    (unload hoist13 crate6 truck2)
    (unload hoist13 crate6 truck3)
    (unload hoist13 crate6 truck4)
    (unload hoist13 crate6 truck5)
    (unload hoist13 crate7 truck0)
    (unload hoist13 crate7 truck1)
    (unload hoist13 crate7 truck2)
    (unload hoist13 crate7 truck3)
    (unload hoist13 crate7 truck4)
    (unload hoist13 crate7 truck5)
    (unload hoist13 crate8 truck0)
    (unload hoist13 crate8 truck1)
    (unload hoist13 crate8 truck2)
    (unload hoist13 crate8 truck3)
    (unload hoist13 crate8 truck4)
    (unload hoist13 crate8 truck5)
    (unload hoist13 crate9 truck0)
    (unload hoist13 crate9 truck1)
    (unload hoist13 crate9 truck2)
    (unload hoist13 crate9 truck3)
    (unload hoist13 crate9 truck4)
    (unload hoist13 crate9 truck5)
    (unload hoist14 crate0 truck0)
    (unload hoist14 crate0 truck1)
    (unload hoist14 crate0 truck2)
    (unload hoist14 crate0 truck3)
    (unload hoist14 crate0 truck4)
    (unload hoist14 crate0 truck5)
    (unload hoist14 crate1 truck0)
    (unload hoist14 crate1 truck1)
    (unload hoist14 crate1 truck2)
    (unload hoist14 crate1 truck3)
    (unload hoist14 crate1 truck4)
    (unload hoist14 crate1 truck5)
    (unload hoist14 crate2 truck0)
    (unload hoist14 crate2 truck1)
    (unload hoist14 crate2 truck2)
    (unload hoist14 crate2 truck3)
    (unload hoist14 crate2 truck4)
    (unload hoist14 crate2 truck5)
    (unload hoist14 crate3 truck0)
    (unload hoist14 crate3 truck1)
    (unload hoist14 crate3 truck2)
    (unload hoist14 crate3 truck3)
    (unload hoist14 crate3 truck4)
    (unload hoist14 crate3 truck5)
    (unload hoist14 crate4 truck0)
    (unload hoist14 crate4 truck1)
    (unload hoist14 crate4 truck2)
    (unload hoist14 crate4 truck3)
    (unload hoist14 crate4 truck4)
    (unload hoist14 crate4 truck5)
    (unload hoist14 crate5 truck0)
    (unload hoist14 crate5 truck1)
    (unload hoist14 crate5 truck2)
    (unload hoist14 crate5 truck3)
    (unload hoist14 crate5 truck4)
    (unload hoist14 crate5 truck5)
    (unload hoist14 crate6 truck0)
    (unload hoist14 crate6 truck1)
    (unload hoist14 crate6 truck2)
    (unload hoist14 crate6 truck3)
    (unload hoist14 crate6 truck4)
    (unload hoist14 crate6 truck5)
    (unload hoist14 crate7 truck0)
    (unload hoist14 crate7 truck1)
    (unload hoist14 crate7 truck2)
    (unload hoist14 crate7 truck3)
    (unload hoist14 crate7 truck4)
    (unload hoist14 crate7 truck5)
    (unload hoist14 crate8 truck0)
    (unload hoist14 crate8 truck1)
    (unload hoist14 crate8 truck2)
    (unload hoist14 crate8 truck3)
    (unload hoist14 crate8 truck4)
    (unload hoist14 crate8 truck5)
    (unload hoist14 crate9 truck0)
    (unload hoist14 crate9 truck1)
    (unload hoist14 crate9 truck2)
    (unload hoist14 crate9 truck3)
    (unload hoist14 crate9 truck4)
    (unload hoist14 crate9 truck5)
    )

(:goal (and
		(on crate0 pallet2)
		(on crate1 pallet7)
		(on crate2 pallet11)
		(on crate3 pallet3)
		(on crate5 pallet5)
		(on crate6 pallet12)
		(on crate7 pallet18)
		(on crate8 pallet15)
	)
))
