(define (problem depotprob9876) (:domain Depot)
(:objects
	depot0 depot1 depot2 - Depot
	distributor0 distributor1 distributor2 - Distributor
	truck0 truck1 - Truck
	pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 - Pallet
	crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 crate8 crate9 crate10 crate11 crate12 crate13 crate14 - Crate
	hoist0 hoist1 hoist2 hoist3 hoist4 hoist5 - Hoist)
(:init
	(at pallet0 depot0)
	(clear pallet0)
	(at pallet1 depot1)
	(clear crate12)
	(at pallet2 depot2)
	(clear pallet2)
	(at pallet3 distributor0)
	(clear crate4)
	(at pallet4 distributor1)
	(clear crate14)
	(at pallet5 distributor2)
	(clear crate13)
	(at truck0 distributor1)
	(at truck1 depot1)
	(at hoist0 depot0)
	(available hoist0)
	(at hoist1 depot1)
	(available hoist1)
	(at hoist2 depot2)
	(available hoist2)
	(at hoist3 distributor0)
	(available hoist3)
	(at hoist4 distributor1)
	(available hoist4)
	(at hoist5 distributor2)
	(available hoist5)
	(at crate0 distributor2)
	(on crate0 pallet5)
	(at crate1 depot1)
	(on crate1 pallet1)
	(at crate2 distributor0)
	(on crate2 pallet3)
	(at crate3 distributor2)
	(on crate3 crate0)
	(at crate4 distributor0)
	(on crate4 crate2)
	(at crate5 depot1)
	(on crate5 crate1)
	(at crate6 distributor2)
	(on crate6 crate3)
	(at crate7 distributor2)
	(on crate7 crate6)
	(at crate8 distributor2)
	(on crate8 crate7)
	(at crate9 distributor2)
	(on crate9 crate8)
	(at crate10 depot1)
	(on crate10 crate5)
	(at crate11 distributor1)
	(on crate11 pallet4)
	(at crate12 depot1)
	(on crate12 crate10)
	(at crate13 distributor2)
	(on crate13 crate9)
	(at crate14 distributor1)
	(on crate14 crate11)

    ; action literals
    (drive truck0 depot0)
    (drive truck0 depot1)
    (drive truck0 depot2)
    (drive truck0 distributor0)
    (drive truck0 distributor1)
    (drive truck0 distributor2)
    (drive truck1 depot0)
    (drive truck1 depot1)
    (drive truck1 depot2)
    (drive truck1 distributor0)
    (drive truck1 distributor1)
    (drive truck1 distributor2)
    (lift hoist0 crate0)
    (lift hoist0 crate1)
    (lift hoist0 crate2)
    (lift hoist0 crate3)
    (lift hoist0 crate4)
    (lift hoist0 crate5)
    (lift hoist0 crate6)
    (lift hoist0 crate7)
    (lift hoist0 crate8)
    (lift hoist0 crate9)
    (lift hoist0 crate10)
    (lift hoist0 crate11)
    (lift hoist0 crate12)
    (lift hoist0 crate13)
    (lift hoist0 crate14)
    (lift hoist1 crate0)
    (lift hoist1 crate1)
    (lift hoist1 crate2)
    (lift hoist1 crate3)
    (lift hoist1 crate4)
    (lift hoist1 crate5)
    (lift hoist1 crate6)
    (lift hoist1 crate7)
    (lift hoist1 crate8)
    (lift hoist1 crate9)
    (lift hoist1 crate10)
    (lift hoist1 crate11)
    (lift hoist1 crate12)
    (lift hoist1 crate13)
    (lift hoist1 crate14)
    (lift hoist2 crate0)
    (lift hoist2 crate1)
    (lift hoist2 crate2)
    (lift hoist2 crate3)
    (lift hoist2 crate4)
    (lift hoist2 crate5)
    (lift hoist2 crate6)
    (lift hoist2 crate7)
    (lift hoist2 crate8)
    (lift hoist2 crate9)
    (lift hoist2 crate10)
    (lift hoist2 crate11)
    (lift hoist2 crate12)
    (lift hoist2 crate13)
    (lift hoist2 crate14)
    (lift hoist3 crate0)
    (lift hoist3 crate1)
    (lift hoist3 crate2)
    (lift hoist3 crate3)
    (lift hoist3 crate4)
    (lift hoist3 crate5)
    (lift hoist3 crate6)
    (lift hoist3 crate7)
    (lift hoist3 crate8)
    (lift hoist3 crate9)
    (lift hoist3 crate10)
    (lift hoist3 crate11)
    (lift hoist3 crate12)
    (lift hoist3 crate13)
    (lift hoist3 crate14)
    (lift hoist4 crate0)
    (lift hoist4 crate1)
    (lift hoist4 crate2)
    (lift hoist4 crate3)
    (lift hoist4 crate4)
    (lift hoist4 crate5)
    (lift hoist4 crate6)
    (lift hoist4 crate7)
    (lift hoist4 crate8)
    (lift hoist4 crate9)
    (lift hoist4 crate10)
    (lift hoist4 crate11)
    (lift hoist4 crate12)
    (lift hoist4 crate13)
    (lift hoist4 crate14)
    (lift hoist5 crate0)
    (lift hoist5 crate1)
    (lift hoist5 crate2)
    (lift hoist5 crate3)
    (lift hoist5 crate4)
    (lift hoist5 crate5)
    (lift hoist5 crate6)
    (lift hoist5 crate7)
    (lift hoist5 crate8)
    (lift hoist5 crate9)
    (lift hoist5 crate10)
    (lift hoist5 crate11)
    (lift hoist5 crate12)
    (lift hoist5 crate13)
    (lift hoist5 crate14)
    (drop hoist0 crate0)
    (drop hoist0 crate1)
    (drop hoist0 crate2)
    (drop hoist0 crate3)
    (drop hoist0 crate4)
    (drop hoist0 crate5)
    (drop hoist0 crate6)
    (drop hoist0 crate7)
    (drop hoist0 crate8)
    (drop hoist0 crate9)
    (drop hoist0 crate10)
    (drop hoist0 crate11)
    (drop hoist0 crate12)
    (drop hoist0 crate13)
    (drop hoist0 crate14)
    (drop hoist1 crate0)
    (drop hoist1 crate1)
    (drop hoist1 crate2)
    (drop hoist1 crate3)
    (drop hoist1 crate4)
    (drop hoist1 crate5)
    (drop hoist1 crate6)
    (drop hoist1 crate7)
    (drop hoist1 crate8)
    (drop hoist1 crate9)
    (drop hoist1 crate10)
    (drop hoist1 crate11)
    (drop hoist1 crate12)
    (drop hoist1 crate13)
    (drop hoist1 crate14)
    (drop hoist2 crate0)
    (drop hoist2 crate1)
    (drop hoist2 crate2)
    (drop hoist2 crate3)
    (drop hoist2 crate4)
    (drop hoist2 crate5)
    (drop hoist2 crate6)
    (drop hoist2 crate7)
    (drop hoist2 crate8)
    (drop hoist2 crate9)
    (drop hoist2 crate10)
    (drop hoist2 crate11)
    (drop hoist2 crate12)
    (drop hoist2 crate13)
    (drop hoist2 crate14)
    (drop hoist3 crate0)
    (drop hoist3 crate1)
    (drop hoist3 crate2)
    (drop hoist3 crate3)
    (drop hoist3 crate4)
    (drop hoist3 crate5)
    (drop hoist3 crate6)
    (drop hoist3 crate7)
    (drop hoist3 crate8)
    (drop hoist3 crate9)
    (drop hoist3 crate10)
    (drop hoist3 crate11)
    (drop hoist3 crate12)
    (drop hoist3 crate13)
    (drop hoist3 crate14)
    (drop hoist4 crate0)
    (drop hoist4 crate1)
    (drop hoist4 crate2)
    (drop hoist4 crate3)
    (drop hoist4 crate4)
    (drop hoist4 crate5)
    (drop hoist4 crate6)
    (drop hoist4 crate7)
    (drop hoist4 crate8)
    (drop hoist4 crate9)
    (drop hoist4 crate10)
    (drop hoist4 crate11)
    (drop hoist4 crate12)
    (drop hoist4 crate13)
    (drop hoist4 crate14)
    (drop hoist5 crate0)
    (drop hoist5 crate1)
    (drop hoist5 crate2)
    (drop hoist5 crate3)
    (drop hoist5 crate4)
    (drop hoist5 crate5)
    (drop hoist5 crate6)
    (drop hoist5 crate7)
    (drop hoist5 crate8)
    (drop hoist5 crate9)
    (drop hoist5 crate10)
    (drop hoist5 crate11)
    (drop hoist5 crate12)
    (drop hoist5 crate13)
    (drop hoist5 crate14)
    (load hoist0 crate0 truck0)
    (load hoist0 crate0 truck1)
    (load hoist0 crate1 truck0)
    (load hoist0 crate1 truck1)
    (load hoist0 crate2 truck0)
    (load hoist0 crate2 truck1)
    (load hoist0 crate3 truck0)
    (load hoist0 crate3 truck1)
    (load hoist0 crate4 truck0)
    (load hoist0 crate4 truck1)
    (load hoist0 crate5 truck0)
    (load hoist0 crate5 truck1)
    (load hoist0 crate6 truck0)
    (load hoist0 crate6 truck1)
    (load hoist0 crate7 truck0)
    (load hoist0 crate7 truck1)
    (load hoist0 crate8 truck0)
    (load hoist0 crate8 truck1)
    (load hoist0 crate9 truck0)
    (load hoist0 crate9 truck1)
    (load hoist0 crate10 truck0)
    (load hoist0 crate10 truck1)
    (load hoist0 crate11 truck0)
    (load hoist0 crate11 truck1)
    (load hoist0 crate12 truck0)
    (load hoist0 crate12 truck1)
    (load hoist0 crate13 truck0)
    (load hoist0 crate13 truck1)
    (load hoist0 crate14 truck0)
    (load hoist0 crate14 truck1)
    (load hoist1 crate0 truck0)
    (load hoist1 crate0 truck1)
    (load hoist1 crate1 truck0)
    (load hoist1 crate1 truck1)
    (load hoist1 crate2 truck0)
    (load hoist1 crate2 truck1)
    (load hoist1 crate3 truck0)
    (load hoist1 crate3 truck1)
    (load hoist1 crate4 truck0)
    (load hoist1 crate4 truck1)
    (load hoist1 crate5 truck0)
    (load hoist1 crate5 truck1)
    (load hoist1 crate6 truck0)
    (load hoist1 crate6 truck1)
    (load hoist1 crate7 truck0)
    (load hoist1 crate7 truck1)
    (load hoist1 crate8 truck0)
    (load hoist1 crate8 truck1)
    (load hoist1 crate9 truck0)
    (load hoist1 crate9 truck1)
    (load hoist1 crate10 truck0)
    (load hoist1 crate10 truck1)
    (load hoist1 crate11 truck0)
    (load hoist1 crate11 truck1)
    (load hoist1 crate12 truck0)
    (load hoist1 crate12 truck1)
    (load hoist1 crate13 truck0)
    (load hoist1 crate13 truck1)
    (load hoist1 crate14 truck0)
    (load hoist1 crate14 truck1)
    (load hoist2 crate0 truck0)
    (load hoist2 crate0 truck1)
    (load hoist2 crate1 truck0)
    (load hoist2 crate1 truck1)
    (load hoist2 crate2 truck0)
    (load hoist2 crate2 truck1)
    (load hoist2 crate3 truck0)
    (load hoist2 crate3 truck1)
    (load hoist2 crate4 truck0)
    (load hoist2 crate4 truck1)
    (load hoist2 crate5 truck0)
    (load hoist2 crate5 truck1)
    (load hoist2 crate6 truck0)
    (load hoist2 crate6 truck1)
    (load hoist2 crate7 truck0)
    (load hoist2 crate7 truck1)
    (load hoist2 crate8 truck0)
    (load hoist2 crate8 truck1)
    (load hoist2 crate9 truck0)
    (load hoist2 crate9 truck1)
    (load hoist2 crate10 truck0)
    (load hoist2 crate10 truck1)
    (load hoist2 crate11 truck0)
    (load hoist2 crate11 truck1)
    (load hoist2 crate12 truck0)
    (load hoist2 crate12 truck1)
    (load hoist2 crate13 truck0)
    (load hoist2 crate13 truck1)
    (load hoist2 crate14 truck0)
    (load hoist2 crate14 truck1)
    (load hoist3 crate0 truck0)
    (load hoist3 crate0 truck1)
    (load hoist3 crate1 truck0)
    (load hoist3 crate1 truck1)
    (load hoist3 crate2 truck0)
    (load hoist3 crate2 truck1)
    (load hoist3 crate3 truck0)
    (load hoist3 crate3 truck1)
    (load hoist3 crate4 truck0)
    (load hoist3 crate4 truck1)
    (load hoist3 crate5 truck0)
    (load hoist3 crate5 truck1)
    (load hoist3 crate6 truck0)
    (load hoist3 crate6 truck1)
    (load hoist3 crate7 truck0)
    (load hoist3 crate7 truck1)
    (load hoist3 crate8 truck0)
    (load hoist3 crate8 truck1)
    (load hoist3 crate9 truck0)
    (load hoist3 crate9 truck1)
    (load hoist3 crate10 truck0)
    (load hoist3 crate10 truck1)
    (load hoist3 crate11 truck0)
    (load hoist3 crate11 truck1)
    (load hoist3 crate12 truck0)
    (load hoist3 crate12 truck1)
    (load hoist3 crate13 truck0)
    (load hoist3 crate13 truck1)
    (load hoist3 crate14 truck0)
    (load hoist3 crate14 truck1)
    (load hoist4 crate0 truck0)
    (load hoist4 crate0 truck1)
    (load hoist4 crate1 truck0)
    (load hoist4 crate1 truck1)
    (load hoist4 crate2 truck0)
    (load hoist4 crate2 truck1)
    (load hoist4 crate3 truck0)
    (load hoist4 crate3 truck1)
    (load hoist4 crate4 truck0)
    (load hoist4 crate4 truck1)
    (load hoist4 crate5 truck0)
    (load hoist4 crate5 truck1)
    (load hoist4 crate6 truck0)
    (load hoist4 crate6 truck1)
    (load hoist4 crate7 truck0)
    (load hoist4 crate7 truck1)
    (load hoist4 crate8 truck0)
    (load hoist4 crate8 truck1)
    (load hoist4 crate9 truck0)
    (load hoist4 crate9 truck1)
    (load hoist4 crate10 truck0)
    (load hoist4 crate10 truck1)
    (load hoist4 crate11 truck0)
    (load hoist4 crate11 truck1)
    (load hoist4 crate12 truck0)
    (load hoist4 crate12 truck1)
    (load hoist4 crate13 truck0)
    (load hoist4 crate13 truck1)
    (load hoist4 crate14 truck0)
    (load hoist4 crate14 truck1)
    (load hoist5 crate0 truck0)
    (load hoist5 crate0 truck1)
    (load hoist5 crate1 truck0)
    (load hoist5 crate1 truck1)
    (load hoist5 crate2 truck0)
    (load hoist5 crate2 truck1)
    (load hoist5 crate3 truck0)
    (load hoist5 crate3 truck1)
    (load hoist5 crate4 truck0)
    (load hoist5 crate4 truck1)
    (load hoist5 crate5 truck0)
    (load hoist5 crate5 truck1)
    (load hoist5 crate6 truck0)
    (load hoist5 crate6 truck1)
    (load hoist5 crate7 truck0)
    (load hoist5 crate7 truck1)
    (load hoist5 crate8 truck0)
    (load hoist5 crate8 truck1)
    (load hoist5 crate9 truck0)
    (load hoist5 crate9 truck1)
    (load hoist5 crate10 truck0)
    (load hoist5 crate10 truck1)
    (load hoist5 crate11 truck0)
    (load hoist5 crate11 truck1)
    (load hoist5 crate12 truck0)
    (load hoist5 crate12 truck1)
    (load hoist5 crate13 truck0)
    (load hoist5 crate13 truck1)
    (load hoist5 crate14 truck0)
    (load hoist5 crate14 truck1)
    (unload hoist0 crate0 truck0)
    (unload hoist0 crate0 truck1)
    (unload hoist0 crate1 truck0)
    (unload hoist0 crate1 truck1)
    (unload hoist0 crate2 truck0)
    (unload hoist0 crate2 truck1)
    (unload hoist0 crate3 truck0)
    (unload hoist0 crate3 truck1)
    (unload hoist0 crate4 truck0)
    (unload hoist0 crate4 truck1)
    (unload hoist0 crate5 truck0)
    (unload hoist0 crate5 truck1)
    (unload hoist0 crate6 truck0)
    (unload hoist0 crate6 truck1)
    (unload hoist0 crate7 truck0)
    (unload hoist0 crate7 truck1)
    (unload hoist0 crate8 truck0)
    (unload hoist0 crate8 truck1)
    (unload hoist0 crate9 truck0)
    (unload hoist0 crate9 truck1)
    (unload hoist0 crate10 truck0)
    (unload hoist0 crate10 truck1)
    (unload hoist0 crate11 truck0)
    (unload hoist0 crate11 truck1)
    (unload hoist0 crate12 truck0)
    (unload hoist0 crate12 truck1)
    (unload hoist0 crate13 truck0)
    (unload hoist0 crate13 truck1)
    (unload hoist0 crate14 truck0)
    (unload hoist0 crate14 truck1)
    (unload hoist1 crate0 truck0)
    (unload hoist1 crate0 truck1)
    (unload hoist1 crate1 truck0)
    (unload hoist1 crate1 truck1)
    (unload hoist1 crate2 truck0)
    (unload hoist1 crate2 truck1)
    (unload hoist1 crate3 truck0)
    (unload hoist1 crate3 truck1)
    (unload hoist1 crate4 truck0)
    (unload hoist1 crate4 truck1)
    (unload hoist1 crate5 truck0)
    (unload hoist1 crate5 truck1)
    (unload hoist1 crate6 truck0)
    (unload hoist1 crate6 truck1)
    (unload hoist1 crate7 truck0)
    (unload hoist1 crate7 truck1)
    (unload hoist1 crate8 truck0)
    (unload hoist1 crate8 truck1)
    (unload hoist1 crate9 truck0)
    (unload hoist1 crate9 truck1)
    (unload hoist1 crate10 truck0)
    (unload hoist1 crate10 truck1)
    (unload hoist1 crate11 truck0)
    (unload hoist1 crate11 truck1)
    (unload hoist1 crate12 truck0)
    (unload hoist1 crate12 truck1)
    (unload hoist1 crate13 truck0)
    (unload hoist1 crate13 truck1)
    (unload hoist1 crate14 truck0)
    (unload hoist1 crate14 truck1)
    (unload hoist2 crate0 truck0)
    (unload hoist2 crate0 truck1)
    (unload hoist2 crate1 truck0)
    (unload hoist2 crate1 truck1)
    (unload hoist2 crate2 truck0)
    (unload hoist2 crate2 truck1)
    (unload hoist2 crate3 truck0)
    (unload hoist2 crate3 truck1)
    (unload hoist2 crate4 truck0)
    (unload hoist2 crate4 truck1)
    (unload hoist2 crate5 truck0)
    (unload hoist2 crate5 truck1)
    (unload hoist2 crate6 truck0)
    (unload hoist2 crate6 truck1)
    (unload hoist2 crate7 truck0)
    (unload hoist2 crate7 truck1)
    (unload hoist2 crate8 truck0)
    (unload hoist2 crate8 truck1)
    (unload hoist2 crate9 truck0)
    (unload hoist2 crate9 truck1)
    (unload hoist2 crate10 truck0)
    (unload hoist2 crate10 truck1)
    (unload hoist2 crate11 truck0)
    (unload hoist2 crate11 truck1)
    (unload hoist2 crate12 truck0)
    (unload hoist2 crate12 truck1)
    (unload hoist2 crate13 truck0)
    (unload hoist2 crate13 truck1)
    (unload hoist2 crate14 truck0)
    (unload hoist2 crate14 truck1)
    (unload hoist3 crate0 truck0)
    (unload hoist3 crate0 truck1)
    (unload hoist3 crate1 truck0)
    (unload hoist3 crate1 truck1)
    (unload hoist3 crate2 truck0)
    (unload hoist3 crate2 truck1)
    (unload hoist3 crate3 truck0)
    (unload hoist3 crate3 truck1)
    (unload hoist3 crate4 truck0)
    (unload hoist3 crate4 truck1)
    (unload hoist3 crate5 truck0)
    (unload hoist3 crate5 truck1)
    (unload hoist3 crate6 truck0)
    (unload hoist3 crate6 truck1)
    (unload hoist3 crate7 truck0)
    (unload hoist3 crate7 truck1)
    (unload hoist3 crate8 truck0)
    (unload hoist3 crate8 truck1)
    (unload hoist3 crate9 truck0)
    (unload hoist3 crate9 truck1)
    (unload hoist3 crate10 truck0)
    (unload hoist3 crate10 truck1)
    (unload hoist3 crate11 truck0)
    (unload hoist3 crate11 truck1)
    (unload hoist3 crate12 truck0)
    (unload hoist3 crate12 truck1)
    (unload hoist3 crate13 truck0)
    (unload hoist3 crate13 truck1)
    (unload hoist3 crate14 truck0)
    (unload hoist3 crate14 truck1)
    (unload hoist4 crate0 truck0)
    (unload hoist4 crate0 truck1)
    (unload hoist4 crate1 truck0)
    (unload hoist4 crate1 truck1)
    (unload hoist4 crate2 truck0)
    (unload hoist4 crate2 truck1)
    (unload hoist4 crate3 truck0)
    (unload hoist4 crate3 truck1)
    (unload hoist4 crate4 truck0)
    (unload hoist4 crate4 truck1)
    (unload hoist4 crate5 truck0)
    (unload hoist4 crate5 truck1)
    (unload hoist4 crate6 truck0)
    (unload hoist4 crate6 truck1)
    (unload hoist4 crate7 truck0)
    (unload hoist4 crate7 truck1)
    (unload hoist4 crate8 truck0)
    (unload hoist4 crate8 truck1)
    (unload hoist4 crate9 truck0)
    (unload hoist4 crate9 truck1)
    (unload hoist4 crate10 truck0)
    (unload hoist4 crate10 truck1)
    (unload hoist4 crate11 truck0)
    (unload hoist4 crate11 truck1)
    (unload hoist4 crate12 truck0)
    (unload hoist4 crate12 truck1)
    (unload hoist4 crate13 truck0)
    (unload hoist4 crate13 truck1)
    (unload hoist4 crate14 truck0)
    (unload hoist4 crate14 truck1)
    (unload hoist5 crate0 truck0)
    (unload hoist5 crate0 truck1)
    (unload hoist5 crate1 truck0)
    (unload hoist5 crate1 truck1)
    (unload hoist5 crate2 truck0)
    (unload hoist5 crate2 truck1)
    (unload hoist5 crate3 truck0)
    (unload hoist5 crate3 truck1)
    (unload hoist5 crate4 truck0)
    (unload hoist5 crate4 truck1)
    (unload hoist5 crate5 truck0)
    (unload hoist5 crate5 truck1)
    (unload hoist5 crate6 truck0)
    (unload hoist5 crate6 truck1)
    (unload hoist5 crate7 truck0)
    (unload hoist5 crate7 truck1)
    (unload hoist5 crate8 truck0)
    (unload hoist5 crate8 truck1)
    (unload hoist5 crate9 truck0)
    (unload hoist5 crate9 truck1)
    (unload hoist5 crate10 truck0)
    (unload hoist5 crate10 truck1)
    (unload hoist5 crate11 truck0)
    (unload hoist5 crate11 truck1)
    (unload hoist5 crate12 truck0)
    (unload hoist5 crate12 truck1)
    (unload hoist5 crate13 truck0)
    (unload hoist5 crate13 truck1)
    (unload hoist5 crate14 truck0)
    (unload hoist5 crate14 truck1)
    )

(:goal (and
		(on crate0 pallet4)
		(on crate1 crate12)
		(on crate2 crate0)
		(on crate3 crate9)
		(on crate5 pallet0)
		(on crate6 crate2)
		(on crate9 pallet2)
		(on crate10 crate13)
		(on crate12 pallet5)
		(on crate13 pallet1)
		(on crate14 crate10)
	)
))
