(define (domain hanoi)
  (:requirements :strips)
  (:predicates
  (clear ?x)
  (on ?x ?y)
  (smaller ?x ?y)
  (move ?disc ?to)
  (peg_top ?peg ?obj)
  (top ?obj ?topobj)
  )

  ; (:actions move)

  (:action move
    :parameters (?disc ?from ?dest ?target ?src_peg ?dest_peg)
    :precondition (and (move ?disc ?dest) (on ?disc ?from) (clear ?disc)
                       (top ?dest ?target) (smaller ?target ?disc)
                       (peg_top ?src_peg ?disc)
                       (peg_top ?dest_peg ?target))
    :effect  (and (clear ?from)
                  (on ?disc ?target)
                  (not (on ?disc ?from))
                  (not (clear ?target))
                  (not (top ?dest ?target))
                  (top ?dest ?disc)
                  (not (top ?src_peg ?disc))
                  (top ?src_peg ?from)
                  (not (top ?from ?disc))
                  (top ?from ?from)
                  (not (peg_top ?src_peg ?disc))
                  (peg_top ?src_peg ?from)
                  (not (peg_top ?dest_peg ?target))
                  (peg_top ?dest_peg ?disc)))
  )
