; Problem taken from https://github.com/AI-Planning/classical-domains

(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0
	instrument0
	instrument1
	instrument2
	satellite1
	instrument3
	instrument4
	instrument5
	satellite2
	instrument6
	satellite3
	instrument7
	satellite4
	instrument8
	instrument9
	instrument10
	spectrograph0
	image3
	image4
	infrared1
	image2
	Star4
	Star3
	GroundStation1
	Star0
	Star2
	Planet5
	Phenomenon6
	Phenomenon7
	Phenomenon8
	Star9
	Planet10
	Planet11
	Phenomenon12
	Phenomenon13
	Star14
)
(:init
	(satellite satellite0)
	(instrument instrument0)
	(supports instrument0 infrared1)
	(supports instrument0 image4)
	(calibration_target instrument0 Star3)
	(instrument instrument1)
	(supports instrument1 image4)
	(supports instrument1 image2)
	(supports instrument1 spectrograph0)
	(calibration_target instrument1 Star4)
	(instrument instrument2)
	(supports instrument2 image2)
	(calibration_target instrument2 Star2)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star0)
	(satellite satellite1)
	(instrument instrument3)
	(supports instrument3 image2)
	(supports instrument3 image3)
	(supports instrument3 image4)
	(calibration_target instrument3 Star2)
	(instrument instrument4)
	(supports instrument4 image3)
	(supports instrument4 image2)
	(calibration_target instrument4 Star3)
	(instrument instrument5)
	(supports instrument5 image4)
	(supports instrument5 infrared1)
	(supports instrument5 spectrograph0)
	(calibration_target instrument5 Star3)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Planet11)
	(satellite satellite2)
	(instrument instrument6)
	(supports instrument6 image2)
	(supports instrument6 spectrograph0)
	(calibration_target instrument6 Star2)
	(on_board instrument6 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Phenomenon6)
	(satellite satellite3)
	(instrument instrument7)
	(supports instrument7 image3)
	(supports instrument7 spectrograph0)
	(supports instrument7 image4)
	(calibration_target instrument7 Star0)
	(on_board instrument7 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Planet10)
	(satellite satellite4)
	(instrument instrument8)
	(supports instrument8 image4)
	(supports instrument8 infrared1)
	(supports instrument8 image3)
	(calibration_target instrument8 GroundStation1)
	(instrument instrument9)
	(supports instrument9 image4)
	(calibration_target instrument9 Star0)
	(instrument instrument10)
	(supports instrument10 image2)
	(supports instrument10 infrared1)
	(supports instrument10 image4)
	(calibration_target instrument10 Star2)
	(on_board instrument8 satellite4)
	(on_board instrument9 satellite4)
	(on_board instrument10 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star9)
	(mode spectrograph0)
	(mode image3)
	(mode image4)
	(mode infrared1)
	(mode image2)
	(direction Star4)
	(direction Star3)
	(direction GroundStation1)
	(direction Star0)
	(direction Star2)
	(direction Planet5)
	(direction Phenomenon6)
	(direction Phenomenon7)
	(direction Phenomenon8)
	(direction Star9)
	(direction Planet10)
	(direction Planet11)
	(direction Phenomenon12)
	(direction Phenomenon13)
	(direction Star14)

    ; action literals
    (turn_to satellite0 GroundStation1)
    (turn_to satellite0 Phenomenon12)
    (turn_to satellite0 Phenomenon13)
    (turn_to satellite0 Phenomenon6)
    (turn_to satellite0 Phenomenon7)
    (turn_to satellite0 Phenomenon8)
    (turn_to satellite0 Planet10)
    (turn_to satellite0 Planet11)
    (turn_to satellite0 Planet5)
    (turn_to satellite0 Star0)
    (turn_to satellite0 Star14)
    (turn_to satellite0 Star2)
    (turn_to satellite0 Star3)
    (turn_to satellite0 Star4)
    (turn_to satellite0 Star9)
    (turn_to satellite1 GroundStation1)
    (turn_to satellite1 Phenomenon12)
    (turn_to satellite1 Phenomenon13)
    (turn_to satellite1 Phenomenon6)
    (turn_to satellite1 Phenomenon7)
    (turn_to satellite1 Phenomenon8)
    (turn_to satellite1 Planet10)
    (turn_to satellite1 Planet11)
    (turn_to satellite1 Planet5)
    (turn_to satellite1 Star0)
    (turn_to satellite1 Star14)
    (turn_to satellite1 Star2)
    (turn_to satellite1 Star3)
    (turn_to satellite1 Star4)
    (turn_to satellite1 Star9)
    (turn_to satellite2 GroundStation1)
    (turn_to satellite2 Phenomenon12)
    (turn_to satellite2 Phenomenon13)
    (turn_to satellite2 Phenomenon6)
    (turn_to satellite2 Phenomenon7)
    (turn_to satellite2 Phenomenon8)
    (turn_to satellite2 Planet10)
    (turn_to satellite2 Planet11)
    (turn_to satellite2 Planet5)
    (turn_to satellite2 Star0)
    (turn_to satellite2 Star14)
    (turn_to satellite2 Star2)
    (turn_to satellite2 Star3)
    (turn_to satellite2 Star4)
    (turn_to satellite2 Star9)
    (turn_to satellite3 GroundStation1)
    (turn_to satellite3 Phenomenon12)
    (turn_to satellite3 Phenomenon13)
    (turn_to satellite3 Phenomenon6)
    (turn_to satellite3 Phenomenon7)
    (turn_to satellite3 Phenomenon8)
    (turn_to satellite3 Planet10)
    (turn_to satellite3 Planet11)
    (turn_to satellite3 Planet5)
    (turn_to satellite3 Star0)
    (turn_to satellite3 Star14)
    (turn_to satellite3 Star2)
    (turn_to satellite3 Star3)
    (turn_to satellite3 Star4)
    (turn_to satellite3 Star9)
    (turn_to satellite4 GroundStation1)
    (turn_to satellite4 Phenomenon12)
    (turn_to satellite4 Phenomenon13)
    (turn_to satellite4 Phenomenon6)
    (turn_to satellite4 Phenomenon7)
    (turn_to satellite4 Phenomenon8)
    (turn_to satellite4 Planet10)
    (turn_to satellite4 Planet11)
    (turn_to satellite4 Planet5)
    (turn_to satellite4 Star0)
    (turn_to satellite4 Star14)
    (turn_to satellite4 Star2)
    (turn_to satellite4 Star3)
    (turn_to satellite4 Star4)
    (turn_to satellite4 Star9)
    (switch_on instrument0)
    (switch_off instrument0)
    (switch_on instrument1)
    (switch_off instrument1)
    (switch_on instrument10)
    (switch_off instrument10)
    (switch_on instrument2)
    (switch_off instrument2)
    (switch_on instrument3)
    (switch_off instrument3)
    (switch_on instrument4)
    (switch_off instrument4)
    (switch_on instrument5)
    (switch_off instrument5)
    (switch_on instrument6)
    (switch_off instrument6)
    (switch_on instrument7)
    (switch_off instrument7)
    (switch_on instrument8)
    (switch_off instrument8)
    (switch_on instrument9)
    (switch_off instrument9)
    (calibrate instrument0 GroundStation1)
    (calibrate instrument0 Phenomenon12)
    (calibrate instrument0 Phenomenon13)
    (calibrate instrument0 Phenomenon6)
    (calibrate instrument0 Phenomenon7)
    (calibrate instrument0 Phenomenon8)
    (calibrate instrument0 Planet10)
    (calibrate instrument0 Planet11)
    (calibrate instrument0 Planet5)
    (calibrate instrument0 Star0)
    (calibrate instrument0 Star14)
    (calibrate instrument0 Star2)
    (calibrate instrument0 Star3)
    (calibrate instrument0 Star4)
    (calibrate instrument0 Star9)
    (calibrate instrument1 GroundStation1)
    (calibrate instrument1 Phenomenon12)
    (calibrate instrument1 Phenomenon13)
    (calibrate instrument1 Phenomenon6)
    (calibrate instrument1 Phenomenon7)
    (calibrate instrument1 Phenomenon8)
    (calibrate instrument1 Planet10)
    (calibrate instrument1 Planet11)
    (calibrate instrument1 Planet5)
    (calibrate instrument1 Star0)
    (calibrate instrument1 Star14)
    (calibrate instrument1 Star2)
    (calibrate instrument1 Star3)
    (calibrate instrument1 Star4)
    (calibrate instrument1 Star9)
    (calibrate instrument10 GroundStation1)
    (calibrate instrument10 Phenomenon12)
    (calibrate instrument10 Phenomenon13)
    (calibrate instrument10 Phenomenon6)
    (calibrate instrument10 Phenomenon7)
    (calibrate instrument10 Phenomenon8)
    (calibrate instrument10 Planet10)
    (calibrate instrument10 Planet11)
    (calibrate instrument10 Planet5)
    (calibrate instrument10 Star0)
    (calibrate instrument10 Star14)
    (calibrate instrument10 Star2)
    (calibrate instrument10 Star3)
    (calibrate instrument10 Star4)
    (calibrate instrument10 Star9)
    (calibrate instrument2 GroundStation1)
    (calibrate instrument2 Phenomenon12)
    (calibrate instrument2 Phenomenon13)
    (calibrate instrument2 Phenomenon6)
    (calibrate instrument2 Phenomenon7)
    (calibrate instrument2 Phenomenon8)
    (calibrate instrument2 Planet10)
    (calibrate instrument2 Planet11)
    (calibrate instrument2 Planet5)
    (calibrate instrument2 Star0)
    (calibrate instrument2 Star14)
    (calibrate instrument2 Star2)
    (calibrate instrument2 Star3)
    (calibrate instrument2 Star4)
    (calibrate instrument2 Star9)
    (calibrate instrument3 GroundStation1)
    (calibrate instrument3 Phenomenon12)
    (calibrate instrument3 Phenomenon13)
    (calibrate instrument3 Phenomenon6)
    (calibrate instrument3 Phenomenon7)
    (calibrate instrument3 Phenomenon8)
    (calibrate instrument3 Planet10)
    (calibrate instrument3 Planet11)
    (calibrate instrument3 Planet5)
    (calibrate instrument3 Star0)
    (calibrate instrument3 Star14)
    (calibrate instrument3 Star2)
    (calibrate instrument3 Star3)
    (calibrate instrument3 Star4)
    (calibrate instrument3 Star9)
    (calibrate instrument4 GroundStation1)
    (calibrate instrument4 Phenomenon12)
    (calibrate instrument4 Phenomenon13)
    (calibrate instrument4 Phenomenon6)
    (calibrate instrument4 Phenomenon7)
    (calibrate instrument4 Phenomenon8)
    (calibrate instrument4 Planet10)
    (calibrate instrument4 Planet11)
    (calibrate instrument4 Planet5)
    (calibrate instrument4 Star0)
    (calibrate instrument4 Star14)
    (calibrate instrument4 Star2)
    (calibrate instrument4 Star3)
    (calibrate instrument4 Star4)
    (calibrate instrument4 Star9)
    (calibrate instrument5 GroundStation1)
    (calibrate instrument5 Phenomenon12)
    (calibrate instrument5 Phenomenon13)
    (calibrate instrument5 Phenomenon6)
    (calibrate instrument5 Phenomenon7)
    (calibrate instrument5 Phenomenon8)
    (calibrate instrument5 Planet10)
    (calibrate instrument5 Planet11)
    (calibrate instrument5 Planet5)
    (calibrate instrument5 Star0)
    (calibrate instrument5 Star14)
    (calibrate instrument5 Star2)
    (calibrate instrument5 Star3)
    (calibrate instrument5 Star4)
    (calibrate instrument5 Star9)
    (calibrate instrument6 GroundStation1)
    (calibrate instrument6 Phenomenon12)
    (calibrate instrument6 Phenomenon13)
    (calibrate instrument6 Phenomenon6)
    (calibrate instrument6 Phenomenon7)
    (calibrate instrument6 Phenomenon8)
    (calibrate instrument6 Planet10)
    (calibrate instrument6 Planet11)
    (calibrate instrument6 Planet5)
    (calibrate instrument6 Star0)
    (calibrate instrument6 Star14)
    (calibrate instrument6 Star2)
    (calibrate instrument6 Star3)
    (calibrate instrument6 Star4)
    (calibrate instrument6 Star9)
    (calibrate instrument7 GroundStation1)
    (calibrate instrument7 Phenomenon12)
    (calibrate instrument7 Phenomenon13)
    (calibrate instrument7 Phenomenon6)
    (calibrate instrument7 Phenomenon7)
    (calibrate instrument7 Phenomenon8)
    (calibrate instrument7 Planet10)
    (calibrate instrument7 Planet11)
    (calibrate instrument7 Planet5)
    (calibrate instrument7 Star0)
    (calibrate instrument7 Star14)
    (calibrate instrument7 Star2)
    (calibrate instrument7 Star3)
    (calibrate instrument7 Star4)
    (calibrate instrument7 Star9)
    (calibrate instrument8 GroundStation1)
    (calibrate instrument8 Phenomenon12)
    (calibrate instrument8 Phenomenon13)
    (calibrate instrument8 Phenomenon6)
    (calibrate instrument8 Phenomenon7)
    (calibrate instrument8 Phenomenon8)
    (calibrate instrument8 Planet10)
    (calibrate instrument8 Planet11)
    (calibrate instrument8 Planet5)
    (calibrate instrument8 Star0)
    (calibrate instrument8 Star14)
    (calibrate instrument8 Star2)
    (calibrate instrument8 Star3)
    (calibrate instrument8 Star4)
    (calibrate instrument8 Star9)
    (calibrate instrument9 GroundStation1)
    (calibrate instrument9 Phenomenon12)
    (calibrate instrument9 Phenomenon13)
    (calibrate instrument9 Phenomenon6)
    (calibrate instrument9 Phenomenon7)
    (calibrate instrument9 Phenomenon8)
    (calibrate instrument9 Planet10)
    (calibrate instrument9 Planet11)
    (calibrate instrument9 Planet5)
    (calibrate instrument9 Star0)
    (calibrate instrument9 Star14)
    (calibrate instrument9 Star2)
    (calibrate instrument9 Star3)
    (calibrate instrument9 Star4)
    (calibrate instrument9 Star9)
    (take_image instrument0 GroundStation1 image2)
    (take_image instrument0 GroundStation1 image3)
    (take_image instrument0 GroundStation1 image4)
    (take_image instrument0 GroundStation1 infrared1)
    (take_image instrument0 GroundStation1 spectrograph0)
    (take_image instrument0 Phenomenon12 image2)
    (take_image instrument0 Phenomenon12 image3)
    (take_image instrument0 Phenomenon12 image4)
    (take_image instrument0 Phenomenon12 infrared1)
    (take_image instrument0 Phenomenon12 spectrograph0)
    (take_image instrument0 Phenomenon13 image2)
    (take_image instrument0 Phenomenon13 image3)
    (take_image instrument0 Phenomenon13 image4)
    (take_image instrument0 Phenomenon13 infrared1)
    (take_image instrument0 Phenomenon13 spectrograph0)
    (take_image instrument0 Phenomenon6 image2)
    (take_image instrument0 Phenomenon6 image3)
    (take_image instrument0 Phenomenon6 image4)
    (take_image instrument0 Phenomenon6 infrared1)
    (take_image instrument0 Phenomenon6 spectrograph0)
    (take_image instrument0 Phenomenon7 image2)
    (take_image instrument0 Phenomenon7 image3)
    (take_image instrument0 Phenomenon7 image4)
    (take_image instrument0 Phenomenon7 infrared1)
    (take_image instrument0 Phenomenon7 spectrograph0)
    (take_image instrument0 Phenomenon8 image2)
    (take_image instrument0 Phenomenon8 image3)
    (take_image instrument0 Phenomenon8 image4)
    (take_image instrument0 Phenomenon8 infrared1)
    (take_image instrument0 Phenomenon8 spectrograph0)
    (take_image instrument0 Planet10 image2)
    (take_image instrument0 Planet10 image3)
    (take_image instrument0 Planet10 image4)
    (take_image instrument0 Planet10 infrared1)
    (take_image instrument0 Planet10 spectrograph0)
    (take_image instrument0 Planet11 image2)
    (take_image instrument0 Planet11 image3)
    (take_image instrument0 Planet11 image4)
    (take_image instrument0 Planet11 infrared1)
    (take_image instrument0 Planet11 spectrograph0)
    (take_image instrument0 Planet5 image2)
    (take_image instrument0 Planet5 image3)
    (take_image instrument0 Planet5 image4)
    (take_image instrument0 Planet5 infrared1)
    (take_image instrument0 Planet5 spectrograph0)
    (take_image instrument0 Star0 image2)
    (take_image instrument0 Star0 image3)
    (take_image instrument0 Star0 image4)
    (take_image instrument0 Star0 infrared1)
    (take_image instrument0 Star0 spectrograph0)
    (take_image instrument0 Star14 image2)
    (take_image instrument0 Star14 image3)
    (take_image instrument0 Star14 image4)
    (take_image instrument0 Star14 infrared1)
    (take_image instrument0 Star14 spectrograph0)
    (take_image instrument0 Star2 image2)
    (take_image instrument0 Star2 image3)
    (take_image instrument0 Star2 image4)
    (take_image instrument0 Star2 infrared1)
    (take_image instrument0 Star2 spectrograph0)
    (take_image instrument0 Star3 image2)
    (take_image instrument0 Star3 image3)
    (take_image instrument0 Star3 image4)
    (take_image instrument0 Star3 infrared1)
    (take_image instrument0 Star3 spectrograph0)
    (take_image instrument0 Star4 image2)
    (take_image instrument0 Star4 image3)
    (take_image instrument0 Star4 image4)
    (take_image instrument0 Star4 infrared1)
    (take_image instrument0 Star4 spectrograph0)
    (take_image instrument0 Star9 image2)
    (take_image instrument0 Star9 image3)
    (take_image instrument0 Star9 image4)
    (take_image instrument0 Star9 infrared1)
    (take_image instrument0 Star9 spectrograph0)
    (take_image instrument1 GroundStation1 image2)
    (take_image instrument1 GroundStation1 image3)
    (take_image instrument1 GroundStation1 image4)
    (take_image instrument1 GroundStation1 infrared1)
    (take_image instrument1 GroundStation1 spectrograph0)
    (take_image instrument1 Phenomenon12 image2)
    (take_image instrument1 Phenomenon12 image3)
    (take_image instrument1 Phenomenon12 image4)
    (take_image instrument1 Phenomenon12 infrared1)
    (take_image instrument1 Phenomenon12 spectrograph0)
    (take_image instrument1 Phenomenon13 image2)
    (take_image instrument1 Phenomenon13 image3)
    (take_image instrument1 Phenomenon13 image4)
    (take_image instrument1 Phenomenon13 infrared1)
    (take_image instrument1 Phenomenon13 spectrograph0)
    (take_image instrument1 Phenomenon6 image2)
    (take_image instrument1 Phenomenon6 image3)
    (take_image instrument1 Phenomenon6 image4)
    (take_image instrument1 Phenomenon6 infrared1)
    (take_image instrument1 Phenomenon6 spectrograph0)
    (take_image instrument1 Phenomenon7 image2)
    (take_image instrument1 Phenomenon7 image3)
    (take_image instrument1 Phenomenon7 image4)
    (take_image instrument1 Phenomenon7 infrared1)
    (take_image instrument1 Phenomenon7 spectrograph0)
    (take_image instrument1 Phenomenon8 image2)
    (take_image instrument1 Phenomenon8 image3)
    (take_image instrument1 Phenomenon8 image4)
    (take_image instrument1 Phenomenon8 infrared1)
    (take_image instrument1 Phenomenon8 spectrograph0)
    (take_image instrument1 Planet10 image2)
    (take_image instrument1 Planet10 image3)
    (take_image instrument1 Planet10 image4)
    (take_image instrument1 Planet10 infrared1)
    (take_image instrument1 Planet10 spectrograph0)
    (take_image instrument1 Planet11 image2)
    (take_image instrument1 Planet11 image3)
    (take_image instrument1 Planet11 image4)
    (take_image instrument1 Planet11 infrared1)
    (take_image instrument1 Planet11 spectrograph0)
    (take_image instrument1 Planet5 image2)
    (take_image instrument1 Planet5 image3)
    (take_image instrument1 Planet5 image4)
    (take_image instrument1 Planet5 infrared1)
    (take_image instrument1 Planet5 spectrograph0)
    (take_image instrument1 Star0 image2)
    (take_image instrument1 Star0 image3)
    (take_image instrument1 Star0 image4)
    (take_image instrument1 Star0 infrared1)
    (take_image instrument1 Star0 spectrograph0)
    (take_image instrument1 Star14 image2)
    (take_image instrument1 Star14 image3)
    (take_image instrument1 Star14 image4)
    (take_image instrument1 Star14 infrared1)
    (take_image instrument1 Star14 spectrograph0)
    (take_image instrument1 Star2 image2)
    (take_image instrument1 Star2 image3)
    (take_image instrument1 Star2 image4)
    (take_image instrument1 Star2 infrared1)
    (take_image instrument1 Star2 spectrograph0)
    (take_image instrument1 Star3 image2)
    (take_image instrument1 Star3 image3)
    (take_image instrument1 Star3 image4)
    (take_image instrument1 Star3 infrared1)
    (take_image instrument1 Star3 spectrograph0)
    (take_image instrument1 Star4 image2)
    (take_image instrument1 Star4 image3)
    (take_image instrument1 Star4 image4)
    (take_image instrument1 Star4 infrared1)
    (take_image instrument1 Star4 spectrograph0)
    (take_image instrument1 Star9 image2)
    (take_image instrument1 Star9 image3)
    (take_image instrument1 Star9 image4)
    (take_image instrument1 Star9 infrared1)
    (take_image instrument1 Star9 spectrograph0)
    (take_image instrument10 GroundStation1 image2)
    (take_image instrument10 GroundStation1 image3)
    (take_image instrument10 GroundStation1 image4)
    (take_image instrument10 GroundStation1 infrared1)
    (take_image instrument10 GroundStation1 spectrograph0)
    (take_image instrument10 Phenomenon12 image2)
    (take_image instrument10 Phenomenon12 image3)
    (take_image instrument10 Phenomenon12 image4)
    (take_image instrument10 Phenomenon12 infrared1)
    (take_image instrument10 Phenomenon12 spectrograph0)
    (take_image instrument10 Phenomenon13 image2)
    (take_image instrument10 Phenomenon13 image3)
    (take_image instrument10 Phenomenon13 image4)
    (take_image instrument10 Phenomenon13 infrared1)
    (take_image instrument10 Phenomenon13 spectrograph0)
    (take_image instrument10 Phenomenon6 image2)
    (take_image instrument10 Phenomenon6 image3)
    (take_image instrument10 Phenomenon6 image4)
    (take_image instrument10 Phenomenon6 infrared1)
    (take_image instrument10 Phenomenon6 spectrograph0)
    (take_image instrument10 Phenomenon7 image2)
    (take_image instrument10 Phenomenon7 image3)
    (take_image instrument10 Phenomenon7 image4)
    (take_image instrument10 Phenomenon7 infrared1)
    (take_image instrument10 Phenomenon7 spectrograph0)
    (take_image instrument10 Phenomenon8 image2)
    (take_image instrument10 Phenomenon8 image3)
    (take_image instrument10 Phenomenon8 image4)
    (take_image instrument10 Phenomenon8 infrared1)
    (take_image instrument10 Phenomenon8 spectrograph0)
    (take_image instrument10 Planet10 image2)
    (take_image instrument10 Planet10 image3)
    (take_image instrument10 Planet10 image4)
    (take_image instrument10 Planet10 infrared1)
    (take_image instrument10 Planet10 spectrograph0)
    (take_image instrument10 Planet11 image2)
    (take_image instrument10 Planet11 image3)
    (take_image instrument10 Planet11 image4)
    (take_image instrument10 Planet11 infrared1)
    (take_image instrument10 Planet11 spectrograph0)
    (take_image instrument10 Planet5 image2)
    (take_image instrument10 Planet5 image3)
    (take_image instrument10 Planet5 image4)
    (take_image instrument10 Planet5 infrared1)
    (take_image instrument10 Planet5 spectrograph0)
    (take_image instrument10 Star0 image2)
    (take_image instrument10 Star0 image3)
    (take_image instrument10 Star0 image4)
    (take_image instrument10 Star0 infrared1)
    (take_image instrument10 Star0 spectrograph0)
    (take_image instrument10 Star14 image2)
    (take_image instrument10 Star14 image3)
    (take_image instrument10 Star14 image4)
    (take_image instrument10 Star14 infrared1)
    (take_image instrument10 Star14 spectrograph0)
    (take_image instrument10 Star2 image2)
    (take_image instrument10 Star2 image3)
    (take_image instrument10 Star2 image4)
    (take_image instrument10 Star2 infrared1)
    (take_image instrument10 Star2 spectrograph0)
    (take_image instrument10 Star3 image2)
    (take_image instrument10 Star3 image3)
    (take_image instrument10 Star3 image4)
    (take_image instrument10 Star3 infrared1)
    (take_image instrument10 Star3 spectrograph0)
    (take_image instrument10 Star4 image2)
    (take_image instrument10 Star4 image3)
    (take_image instrument10 Star4 image4)
    (take_image instrument10 Star4 infrared1)
    (take_image instrument10 Star4 spectrograph0)
    (take_image instrument10 Star9 image2)
    (take_image instrument10 Star9 image3)
    (take_image instrument10 Star9 image4)
    (take_image instrument10 Star9 infrared1)
    (take_image instrument10 Star9 spectrograph0)
    (take_image instrument2 GroundStation1 image2)
    (take_image instrument2 GroundStation1 image3)
    (take_image instrument2 GroundStation1 image4)
    (take_image instrument2 GroundStation1 infrared1)
    (take_image instrument2 GroundStation1 spectrograph0)
    (take_image instrument2 Phenomenon12 image2)
    (take_image instrument2 Phenomenon12 image3)
    (take_image instrument2 Phenomenon12 image4)
    (take_image instrument2 Phenomenon12 infrared1)
    (take_image instrument2 Phenomenon12 spectrograph0)
    (take_image instrument2 Phenomenon13 image2)
    (take_image instrument2 Phenomenon13 image3)
    (take_image instrument2 Phenomenon13 image4)
    (take_image instrument2 Phenomenon13 infrared1)
    (take_image instrument2 Phenomenon13 spectrograph0)
    (take_image instrument2 Phenomenon6 image2)
    (take_image instrument2 Phenomenon6 image3)
    (take_image instrument2 Phenomenon6 image4)
    (take_image instrument2 Phenomenon6 infrared1)
    (take_image instrument2 Phenomenon6 spectrograph0)
    (take_image instrument2 Phenomenon7 image2)
    (take_image instrument2 Phenomenon7 image3)
    (take_image instrument2 Phenomenon7 image4)
    (take_image instrument2 Phenomenon7 infrared1)
    (take_image instrument2 Phenomenon7 spectrograph0)
    (take_image instrument2 Phenomenon8 image2)
    (take_image instrument2 Phenomenon8 image3)
    (take_image instrument2 Phenomenon8 image4)
    (take_image instrument2 Phenomenon8 infrared1)
    (take_image instrument2 Phenomenon8 spectrograph0)
    (take_image instrument2 Planet10 image2)
    (take_image instrument2 Planet10 image3)
    (take_image instrument2 Planet10 image4)
    (take_image instrument2 Planet10 infrared1)
    (take_image instrument2 Planet10 spectrograph0)
    (take_image instrument2 Planet11 image2)
    (take_image instrument2 Planet11 image3)
    (take_image instrument2 Planet11 image4)
    (take_image instrument2 Planet11 infrared1)
    (take_image instrument2 Planet11 spectrograph0)
    (take_image instrument2 Planet5 image2)
    (take_image instrument2 Planet5 image3)
    (take_image instrument2 Planet5 image4)
    (take_image instrument2 Planet5 infrared1)
    (take_image instrument2 Planet5 spectrograph0)
    (take_image instrument2 Star0 image2)
    (take_image instrument2 Star0 image3)
    (take_image instrument2 Star0 image4)
    (take_image instrument2 Star0 infrared1)
    (take_image instrument2 Star0 spectrograph0)
    (take_image instrument2 Star14 image2)
    (take_image instrument2 Star14 image3)
    (take_image instrument2 Star14 image4)
    (take_image instrument2 Star14 infrared1)
    (take_image instrument2 Star14 spectrograph0)
    (take_image instrument2 Star2 image2)
    (take_image instrument2 Star2 image3)
    (take_image instrument2 Star2 image4)
    (take_image instrument2 Star2 infrared1)
    (take_image instrument2 Star2 spectrograph0)
    (take_image instrument2 Star3 image2)
    (take_image instrument2 Star3 image3)
    (take_image instrument2 Star3 image4)
    (take_image instrument2 Star3 infrared1)
    (take_image instrument2 Star3 spectrograph0)
    (take_image instrument2 Star4 image2)
    (take_image instrument2 Star4 image3)
    (take_image instrument2 Star4 image4)
    (take_image instrument2 Star4 infrared1)
    (take_image instrument2 Star4 spectrograph0)
    (take_image instrument2 Star9 image2)
    (take_image instrument2 Star9 image3)
    (take_image instrument2 Star9 image4)
    (take_image instrument2 Star9 infrared1)
    (take_image instrument2 Star9 spectrograph0)
    (take_image instrument3 GroundStation1 image2)
    (take_image instrument3 GroundStation1 image3)
    (take_image instrument3 GroundStation1 image4)
    (take_image instrument3 GroundStation1 infrared1)
    (take_image instrument3 GroundStation1 spectrograph0)
    (take_image instrument3 Phenomenon12 image2)
    (take_image instrument3 Phenomenon12 image3)
    (take_image instrument3 Phenomenon12 image4)
    (take_image instrument3 Phenomenon12 infrared1)
    (take_image instrument3 Phenomenon12 spectrograph0)
    (take_image instrument3 Phenomenon13 image2)
    (take_image instrument3 Phenomenon13 image3)
    (take_image instrument3 Phenomenon13 image4)
    (take_image instrument3 Phenomenon13 infrared1)
    (take_image instrument3 Phenomenon13 spectrograph0)
    (take_image instrument3 Phenomenon6 image2)
    (take_image instrument3 Phenomenon6 image3)
    (take_image instrument3 Phenomenon6 image4)
    (take_image instrument3 Phenomenon6 infrared1)
    (take_image instrument3 Phenomenon6 spectrograph0)
    (take_image instrument3 Phenomenon7 image2)
    (take_image instrument3 Phenomenon7 image3)
    (take_image instrument3 Phenomenon7 image4)
    (take_image instrument3 Phenomenon7 infrared1)
    (take_image instrument3 Phenomenon7 spectrograph0)
    (take_image instrument3 Phenomenon8 image2)
    (take_image instrument3 Phenomenon8 image3)
    (take_image instrument3 Phenomenon8 image4)
    (take_image instrument3 Phenomenon8 infrared1)
    (take_image instrument3 Phenomenon8 spectrograph0)
    (take_image instrument3 Planet10 image2)
    (take_image instrument3 Planet10 image3)
    (take_image instrument3 Planet10 image4)
    (take_image instrument3 Planet10 infrared1)
    (take_image instrument3 Planet10 spectrograph0)
    (take_image instrument3 Planet11 image2)
    (take_image instrument3 Planet11 image3)
    (take_image instrument3 Planet11 image4)
    (take_image instrument3 Planet11 infrared1)
    (take_image instrument3 Planet11 spectrograph0)
    (take_image instrument3 Planet5 image2)
    (take_image instrument3 Planet5 image3)
    (take_image instrument3 Planet5 image4)
    (take_image instrument3 Planet5 infrared1)
    (take_image instrument3 Planet5 spectrograph0)
    (take_image instrument3 Star0 image2)
    (take_image instrument3 Star0 image3)
    (take_image instrument3 Star0 image4)
    (take_image instrument3 Star0 infrared1)
    (take_image instrument3 Star0 spectrograph0)
    (take_image instrument3 Star14 image2)
    (take_image instrument3 Star14 image3)
    (take_image instrument3 Star14 image4)
    (take_image instrument3 Star14 infrared1)
    (take_image instrument3 Star14 spectrograph0)
    (take_image instrument3 Star2 image2)
    (take_image instrument3 Star2 image3)
    (take_image instrument3 Star2 image4)
    (take_image instrument3 Star2 infrared1)
    (take_image instrument3 Star2 spectrograph0)
    (take_image instrument3 Star3 image2)
    (take_image instrument3 Star3 image3)
    (take_image instrument3 Star3 image4)
    (take_image instrument3 Star3 infrared1)
    (take_image instrument3 Star3 spectrograph0)
    (take_image instrument3 Star4 image2)
    (take_image instrument3 Star4 image3)
    (take_image instrument3 Star4 image4)
    (take_image instrument3 Star4 infrared1)
    (take_image instrument3 Star4 spectrograph0)
    (take_image instrument3 Star9 image2)
    (take_image instrument3 Star9 image3)
    (take_image instrument3 Star9 image4)
    (take_image instrument3 Star9 infrared1)
    (take_image instrument3 Star9 spectrograph0)
    (take_image instrument4 GroundStation1 image2)
    (take_image instrument4 GroundStation1 image3)
    (take_image instrument4 GroundStation1 image4)
    (take_image instrument4 GroundStation1 infrared1)
    (take_image instrument4 GroundStation1 spectrograph0)
    (take_image instrument4 Phenomenon12 image2)
    (take_image instrument4 Phenomenon12 image3)
    (take_image instrument4 Phenomenon12 image4)
    (take_image instrument4 Phenomenon12 infrared1)
    (take_image instrument4 Phenomenon12 spectrograph0)
    (take_image instrument4 Phenomenon13 image2)
    (take_image instrument4 Phenomenon13 image3)
    (take_image instrument4 Phenomenon13 image4)
    (take_image instrument4 Phenomenon13 infrared1)
    (take_image instrument4 Phenomenon13 spectrograph0)
    (take_image instrument4 Phenomenon6 image2)
    (take_image instrument4 Phenomenon6 image3)
    (take_image instrument4 Phenomenon6 image4)
    (take_image instrument4 Phenomenon6 infrared1)
    (take_image instrument4 Phenomenon6 spectrograph0)
    (take_image instrument4 Phenomenon7 image2)
    (take_image instrument4 Phenomenon7 image3)
    (take_image instrument4 Phenomenon7 image4)
    (take_image instrument4 Phenomenon7 infrared1)
    (take_image instrument4 Phenomenon7 spectrograph0)
    (take_image instrument4 Phenomenon8 image2)
    (take_image instrument4 Phenomenon8 image3)
    (take_image instrument4 Phenomenon8 image4)
    (take_image instrument4 Phenomenon8 infrared1)
    (take_image instrument4 Phenomenon8 spectrograph0)
    (take_image instrument4 Planet10 image2)
    (take_image instrument4 Planet10 image3)
    (take_image instrument4 Planet10 image4)
    (take_image instrument4 Planet10 infrared1)
    (take_image instrument4 Planet10 spectrograph0)
    (take_image instrument4 Planet11 image2)
    (take_image instrument4 Planet11 image3)
    (take_image instrument4 Planet11 image4)
    (take_image instrument4 Planet11 infrared1)
    (take_image instrument4 Planet11 spectrograph0)
    (take_image instrument4 Planet5 image2)
    (take_image instrument4 Planet5 image3)
    (take_image instrument4 Planet5 image4)
    (take_image instrument4 Planet5 infrared1)
    (take_image instrument4 Planet5 spectrograph0)
    (take_image instrument4 Star0 image2)
    (take_image instrument4 Star0 image3)
    (take_image instrument4 Star0 image4)
    (take_image instrument4 Star0 infrared1)
    (take_image instrument4 Star0 spectrograph0)
    (take_image instrument4 Star14 image2)
    (take_image instrument4 Star14 image3)
    (take_image instrument4 Star14 image4)
    (take_image instrument4 Star14 infrared1)
    (take_image instrument4 Star14 spectrograph0)
    (take_image instrument4 Star2 image2)
    (take_image instrument4 Star2 image3)
    (take_image instrument4 Star2 image4)
    (take_image instrument4 Star2 infrared1)
    (take_image instrument4 Star2 spectrograph0)
    (take_image instrument4 Star3 image2)
    (take_image instrument4 Star3 image3)
    (take_image instrument4 Star3 image4)
    (take_image instrument4 Star3 infrared1)
    (take_image instrument4 Star3 spectrograph0)
    (take_image instrument4 Star4 image2)
    (take_image instrument4 Star4 image3)
    (take_image instrument4 Star4 image4)
    (take_image instrument4 Star4 infrared1)
    (take_image instrument4 Star4 spectrograph0)
    (take_image instrument4 Star9 image2)
    (take_image instrument4 Star9 image3)
    (take_image instrument4 Star9 image4)
    (take_image instrument4 Star9 infrared1)
    (take_image instrument4 Star9 spectrograph0)
    (take_image instrument5 GroundStation1 image2)
    (take_image instrument5 GroundStation1 image3)
    (take_image instrument5 GroundStation1 image4)
    (take_image instrument5 GroundStation1 infrared1)
    (take_image instrument5 GroundStation1 spectrograph0)
    (take_image instrument5 Phenomenon12 image2)
    (take_image instrument5 Phenomenon12 image3)
    (take_image instrument5 Phenomenon12 image4)
    (take_image instrument5 Phenomenon12 infrared1)
    (take_image instrument5 Phenomenon12 spectrograph0)
    (take_image instrument5 Phenomenon13 image2)
    (take_image instrument5 Phenomenon13 image3)
    (take_image instrument5 Phenomenon13 image4)
    (take_image instrument5 Phenomenon13 infrared1)
    (take_image instrument5 Phenomenon13 spectrograph0)
    (take_image instrument5 Phenomenon6 image2)
    (take_image instrument5 Phenomenon6 image3)
    (take_image instrument5 Phenomenon6 image4)
    (take_image instrument5 Phenomenon6 infrared1)
    (take_image instrument5 Phenomenon6 spectrograph0)
    (take_image instrument5 Phenomenon7 image2)
    (take_image instrument5 Phenomenon7 image3)
    (take_image instrument5 Phenomenon7 image4)
    (take_image instrument5 Phenomenon7 infrared1)
    (take_image instrument5 Phenomenon7 spectrograph0)
    (take_image instrument5 Phenomenon8 image2)
    (take_image instrument5 Phenomenon8 image3)
    (take_image instrument5 Phenomenon8 image4)
    (take_image instrument5 Phenomenon8 infrared1)
    (take_image instrument5 Phenomenon8 spectrograph0)
    (take_image instrument5 Planet10 image2)
    (take_image instrument5 Planet10 image3)
    (take_image instrument5 Planet10 image4)
    (take_image instrument5 Planet10 infrared1)
    (take_image instrument5 Planet10 spectrograph0)
    (take_image instrument5 Planet11 image2)
    (take_image instrument5 Planet11 image3)
    (take_image instrument5 Planet11 image4)
    (take_image instrument5 Planet11 infrared1)
    (take_image instrument5 Planet11 spectrograph0)
    (take_image instrument5 Planet5 image2)
    (take_image instrument5 Planet5 image3)
    (take_image instrument5 Planet5 image4)
    (take_image instrument5 Planet5 infrared1)
    (take_image instrument5 Planet5 spectrograph0)
    (take_image instrument5 Star0 image2)
    (take_image instrument5 Star0 image3)
    (take_image instrument5 Star0 image4)
    (take_image instrument5 Star0 infrared1)
    (take_image instrument5 Star0 spectrograph0)
    (take_image instrument5 Star14 image2)
    (take_image instrument5 Star14 image3)
    (take_image instrument5 Star14 image4)
    (take_image instrument5 Star14 infrared1)
    (take_image instrument5 Star14 spectrograph0)
    (take_image instrument5 Star2 image2)
    (take_image instrument5 Star2 image3)
    (take_image instrument5 Star2 image4)
    (take_image instrument5 Star2 infrared1)
    (take_image instrument5 Star2 spectrograph0)
    (take_image instrument5 Star3 image2)
    (take_image instrument5 Star3 image3)
    (take_image instrument5 Star3 image4)
    (take_image instrument5 Star3 infrared1)
    (take_image instrument5 Star3 spectrograph0)
    (take_image instrument5 Star4 image2)
    (take_image instrument5 Star4 image3)
    (take_image instrument5 Star4 image4)
    (take_image instrument5 Star4 infrared1)
    (take_image instrument5 Star4 spectrograph0)
    (take_image instrument5 Star9 image2)
    (take_image instrument5 Star9 image3)
    (take_image instrument5 Star9 image4)
    (take_image instrument5 Star9 infrared1)
    (take_image instrument5 Star9 spectrograph0)
    (take_image instrument6 GroundStation1 image2)
    (take_image instrument6 GroundStation1 image3)
    (take_image instrument6 GroundStation1 image4)
    (take_image instrument6 GroundStation1 infrared1)
    (take_image instrument6 GroundStation1 spectrograph0)
    (take_image instrument6 Phenomenon12 image2)
    (take_image instrument6 Phenomenon12 image3)
    (take_image instrument6 Phenomenon12 image4)
    (take_image instrument6 Phenomenon12 infrared1)
    (take_image instrument6 Phenomenon12 spectrograph0)
    (take_image instrument6 Phenomenon13 image2)
    (take_image instrument6 Phenomenon13 image3)
    (take_image instrument6 Phenomenon13 image4)
    (take_image instrument6 Phenomenon13 infrared1)
    (take_image instrument6 Phenomenon13 spectrograph0)
    (take_image instrument6 Phenomenon6 image2)
    (take_image instrument6 Phenomenon6 image3)
    (take_image instrument6 Phenomenon6 image4)
    (take_image instrument6 Phenomenon6 infrared1)
    (take_image instrument6 Phenomenon6 spectrograph0)
    (take_image instrument6 Phenomenon7 image2)
    (take_image instrument6 Phenomenon7 image3)
    (take_image instrument6 Phenomenon7 image4)
    (take_image instrument6 Phenomenon7 infrared1)
    (take_image instrument6 Phenomenon7 spectrograph0)
    (take_image instrument6 Phenomenon8 image2)
    (take_image instrument6 Phenomenon8 image3)
    (take_image instrument6 Phenomenon8 image4)
    (take_image instrument6 Phenomenon8 infrared1)
    (take_image instrument6 Phenomenon8 spectrograph0)
    (take_image instrument6 Planet10 image2)
    (take_image instrument6 Planet10 image3)
    (take_image instrument6 Planet10 image4)
    (take_image instrument6 Planet10 infrared1)
    (take_image instrument6 Planet10 spectrograph0)
    (take_image instrument6 Planet11 image2)
    (take_image instrument6 Planet11 image3)
    (take_image instrument6 Planet11 image4)
    (take_image instrument6 Planet11 infrared1)
    (take_image instrument6 Planet11 spectrograph0)
    (take_image instrument6 Planet5 image2)
    (take_image instrument6 Planet5 image3)
    (take_image instrument6 Planet5 image4)
    (take_image instrument6 Planet5 infrared1)
    (take_image instrument6 Planet5 spectrograph0)
    (take_image instrument6 Star0 image2)
    (take_image instrument6 Star0 image3)
    (take_image instrument6 Star0 image4)
    (take_image instrument6 Star0 infrared1)
    (take_image instrument6 Star0 spectrograph0)
    (take_image instrument6 Star14 image2)
    (take_image instrument6 Star14 image3)
    (take_image instrument6 Star14 image4)
    (take_image instrument6 Star14 infrared1)
    (take_image instrument6 Star14 spectrograph0)
    (take_image instrument6 Star2 image2)
    (take_image instrument6 Star2 image3)
    (take_image instrument6 Star2 image4)
    (take_image instrument6 Star2 infrared1)
    (take_image instrument6 Star2 spectrograph0)
    (take_image instrument6 Star3 image2)
    (take_image instrument6 Star3 image3)
    (take_image instrument6 Star3 image4)
    (take_image instrument6 Star3 infrared1)
    (take_image instrument6 Star3 spectrograph0)
    (take_image instrument6 Star4 image2)
    (take_image instrument6 Star4 image3)
    (take_image instrument6 Star4 image4)
    (take_image instrument6 Star4 infrared1)
    (take_image instrument6 Star4 spectrograph0)
    (take_image instrument6 Star9 image2)
    (take_image instrument6 Star9 image3)
    (take_image instrument6 Star9 image4)
    (take_image instrument6 Star9 infrared1)
    (take_image instrument6 Star9 spectrograph0)
    (take_image instrument7 GroundStation1 image2)
    (take_image instrument7 GroundStation1 image3)
    (take_image instrument7 GroundStation1 image4)
    (take_image instrument7 GroundStation1 infrared1)
    (take_image instrument7 GroundStation1 spectrograph0)
    (take_image instrument7 Phenomenon12 image2)
    (take_image instrument7 Phenomenon12 image3)
    (take_image instrument7 Phenomenon12 image4)
    (take_image instrument7 Phenomenon12 infrared1)
    (take_image instrument7 Phenomenon12 spectrograph0)
    (take_image instrument7 Phenomenon13 image2)
    (take_image instrument7 Phenomenon13 image3)
    (take_image instrument7 Phenomenon13 image4)
    (take_image instrument7 Phenomenon13 infrared1)
    (take_image instrument7 Phenomenon13 spectrograph0)
    (take_image instrument7 Phenomenon6 image2)
    (take_image instrument7 Phenomenon6 image3)
    (take_image instrument7 Phenomenon6 image4)
    (take_image instrument7 Phenomenon6 infrared1)
    (take_image instrument7 Phenomenon6 spectrograph0)
    (take_image instrument7 Phenomenon7 image2)
    (take_image instrument7 Phenomenon7 image3)
    (take_image instrument7 Phenomenon7 image4)
    (take_image instrument7 Phenomenon7 infrared1)
    (take_image instrument7 Phenomenon7 spectrograph0)
    (take_image instrument7 Phenomenon8 image2)
    (take_image instrument7 Phenomenon8 image3)
    (take_image instrument7 Phenomenon8 image4)
    (take_image instrument7 Phenomenon8 infrared1)
    (take_image instrument7 Phenomenon8 spectrograph0)
    (take_image instrument7 Planet10 image2)
    (take_image instrument7 Planet10 image3)
    (take_image instrument7 Planet10 image4)
    (take_image instrument7 Planet10 infrared1)
    (take_image instrument7 Planet10 spectrograph0)
    (take_image instrument7 Planet11 image2)
    (take_image instrument7 Planet11 image3)
    (take_image instrument7 Planet11 image4)
    (take_image instrument7 Planet11 infrared1)
    (take_image instrument7 Planet11 spectrograph0)
    (take_image instrument7 Planet5 image2)
    (take_image instrument7 Planet5 image3)
    (take_image instrument7 Planet5 image4)
    (take_image instrument7 Planet5 infrared1)
    (take_image instrument7 Planet5 spectrograph0)
    (take_image instrument7 Star0 image2)
    (take_image instrument7 Star0 image3)
    (take_image instrument7 Star0 image4)
    (take_image instrument7 Star0 infrared1)
    (take_image instrument7 Star0 spectrograph0)
    (take_image instrument7 Star14 image2)
    (take_image instrument7 Star14 image3)
    (take_image instrument7 Star14 image4)
    (take_image instrument7 Star14 infrared1)
    (take_image instrument7 Star14 spectrograph0)
    (take_image instrument7 Star2 image2)
    (take_image instrument7 Star2 image3)
    (take_image instrument7 Star2 image4)
    (take_image instrument7 Star2 infrared1)
    (take_image instrument7 Star2 spectrograph0)
    (take_image instrument7 Star3 image2)
    (take_image instrument7 Star3 image3)
    (take_image instrument7 Star3 image4)
    (take_image instrument7 Star3 infrared1)
    (take_image instrument7 Star3 spectrograph0)
    (take_image instrument7 Star4 image2)
    (take_image instrument7 Star4 image3)
    (take_image instrument7 Star4 image4)
    (take_image instrument7 Star4 infrared1)
    (take_image instrument7 Star4 spectrograph0)
    (take_image instrument7 Star9 image2)
    (take_image instrument7 Star9 image3)
    (take_image instrument7 Star9 image4)
    (take_image instrument7 Star9 infrared1)
    (take_image instrument7 Star9 spectrograph0)
    (take_image instrument8 GroundStation1 image2)
    (take_image instrument8 GroundStation1 image3)
    (take_image instrument8 GroundStation1 image4)
    (take_image instrument8 GroundStation1 infrared1)
    (take_image instrument8 GroundStation1 spectrograph0)
    (take_image instrument8 Phenomenon12 image2)
    (take_image instrument8 Phenomenon12 image3)
    (take_image instrument8 Phenomenon12 image4)
    (take_image instrument8 Phenomenon12 infrared1)
    (take_image instrument8 Phenomenon12 spectrograph0)
    (take_image instrument8 Phenomenon13 image2)
    (take_image instrument8 Phenomenon13 image3)
    (take_image instrument8 Phenomenon13 image4)
    (take_image instrument8 Phenomenon13 infrared1)
    (take_image instrument8 Phenomenon13 spectrograph0)
    (take_image instrument8 Phenomenon6 image2)
    (take_image instrument8 Phenomenon6 image3)
    (take_image instrument8 Phenomenon6 image4)
    (take_image instrument8 Phenomenon6 infrared1)
    (take_image instrument8 Phenomenon6 spectrograph0)
    (take_image instrument8 Phenomenon7 image2)
    (take_image instrument8 Phenomenon7 image3)
    (take_image instrument8 Phenomenon7 image4)
    (take_image instrument8 Phenomenon7 infrared1)
    (take_image instrument8 Phenomenon7 spectrograph0)
    (take_image instrument8 Phenomenon8 image2)
    (take_image instrument8 Phenomenon8 image3)
    (take_image instrument8 Phenomenon8 image4)
    (take_image instrument8 Phenomenon8 infrared1)
    (take_image instrument8 Phenomenon8 spectrograph0)
    (take_image instrument8 Planet10 image2)
    (take_image instrument8 Planet10 image3)
    (take_image instrument8 Planet10 image4)
    (take_image instrument8 Planet10 infrared1)
    (take_image instrument8 Planet10 spectrograph0)
    (take_image instrument8 Planet11 image2)
    (take_image instrument8 Planet11 image3)
    (take_image instrument8 Planet11 image4)
    (take_image instrument8 Planet11 infrared1)
    (take_image instrument8 Planet11 spectrograph0)
    (take_image instrument8 Planet5 image2)
    (take_image instrument8 Planet5 image3)
    (take_image instrument8 Planet5 image4)
    (take_image instrument8 Planet5 infrared1)
    (take_image instrument8 Planet5 spectrograph0)
    (take_image instrument8 Star0 image2)
    (take_image instrument8 Star0 image3)
    (take_image instrument8 Star0 image4)
    (take_image instrument8 Star0 infrared1)
    (take_image instrument8 Star0 spectrograph0)
    (take_image instrument8 Star14 image2)
    (take_image instrument8 Star14 image3)
    (take_image instrument8 Star14 image4)
    (take_image instrument8 Star14 infrared1)
    (take_image instrument8 Star14 spectrograph0)
    (take_image instrument8 Star2 image2)
    (take_image instrument8 Star2 image3)
    (take_image instrument8 Star2 image4)
    (take_image instrument8 Star2 infrared1)
    (take_image instrument8 Star2 spectrograph0)
    (take_image instrument8 Star3 image2)
    (take_image instrument8 Star3 image3)
    (take_image instrument8 Star3 image4)
    (take_image instrument8 Star3 infrared1)
    (take_image instrument8 Star3 spectrograph0)
    (take_image instrument8 Star4 image2)
    (take_image instrument8 Star4 image3)
    (take_image instrument8 Star4 image4)
    (take_image instrument8 Star4 infrared1)
    (take_image instrument8 Star4 spectrograph0)
    (take_image instrument8 Star9 image2)
    (take_image instrument8 Star9 image3)
    (take_image instrument8 Star9 image4)
    (take_image instrument8 Star9 infrared1)
    (take_image instrument8 Star9 spectrograph0)
    (take_image instrument9 GroundStation1 image2)
    (take_image instrument9 GroundStation1 image3)
    (take_image instrument9 GroundStation1 image4)
    (take_image instrument9 GroundStation1 infrared1)
    (take_image instrument9 GroundStation1 spectrograph0)
    (take_image instrument9 Phenomenon12 image2)
    (take_image instrument9 Phenomenon12 image3)
    (take_image instrument9 Phenomenon12 image4)
    (take_image instrument9 Phenomenon12 infrared1)
    (take_image instrument9 Phenomenon12 spectrograph0)
    (take_image instrument9 Phenomenon13 image2)
    (take_image instrument9 Phenomenon13 image3)
    (take_image instrument9 Phenomenon13 image4)
    (take_image instrument9 Phenomenon13 infrared1)
    (take_image instrument9 Phenomenon13 spectrograph0)
    (take_image instrument9 Phenomenon6 image2)
    (take_image instrument9 Phenomenon6 image3)
    (take_image instrument9 Phenomenon6 image4)
    (take_image instrument9 Phenomenon6 infrared1)
    (take_image instrument9 Phenomenon6 spectrograph0)
    (take_image instrument9 Phenomenon7 image2)
    (take_image instrument9 Phenomenon7 image3)
    (take_image instrument9 Phenomenon7 image4)
    (take_image instrument9 Phenomenon7 infrared1)
    (take_image instrument9 Phenomenon7 spectrograph0)
    (take_image instrument9 Phenomenon8 image2)
    (take_image instrument9 Phenomenon8 image3)
    (take_image instrument9 Phenomenon8 image4)
    (take_image instrument9 Phenomenon8 infrared1)
    (take_image instrument9 Phenomenon8 spectrograph0)
    (take_image instrument9 Planet10 image2)
    (take_image instrument9 Planet10 image3)
    (take_image instrument9 Planet10 image4)
    (take_image instrument9 Planet10 infrared1)
    (take_image instrument9 Planet10 spectrograph0)
    (take_image instrument9 Planet11 image2)
    (take_image instrument9 Planet11 image3)
    (take_image instrument9 Planet11 image4)
    (take_image instrument9 Planet11 infrared1)
    (take_image instrument9 Planet11 spectrograph0)
    (take_image instrument9 Planet5 image2)
    (take_image instrument9 Planet5 image3)
    (take_image instrument9 Planet5 image4)
    (take_image instrument9 Planet5 infrared1)
    (take_image instrument9 Planet5 spectrograph0)
    (take_image instrument9 Star0 image2)
    (take_image instrument9 Star0 image3)
    (take_image instrument9 Star0 image4)
    (take_image instrument9 Star0 infrared1)
    (take_image instrument9 Star0 spectrograph0)
    (take_image instrument9 Star14 image2)
    (take_image instrument9 Star14 image3)
    (take_image instrument9 Star14 image4)
    (take_image instrument9 Star14 infrared1)
    (take_image instrument9 Star14 spectrograph0)
    (take_image instrument9 Star2 image2)
    (take_image instrument9 Star2 image3)
    (take_image instrument9 Star2 image4)
    (take_image instrument9 Star2 infrared1)
    (take_image instrument9 Star2 spectrograph0)
    (take_image instrument9 Star3 image2)
    (take_image instrument9 Star3 image3)
    (take_image instrument9 Star3 image4)
    (take_image instrument9 Star3 infrared1)
    (take_image instrument9 Star3 spectrograph0)
    (take_image instrument9 Star4 image2)
    (take_image instrument9 Star4 image3)
    (take_image instrument9 Star4 image4)
    (take_image instrument9 Star4 infrared1)
    (take_image instrument9 Star4 spectrograph0)
    (take_image instrument9 Star9 image2)
    (take_image instrument9 Star9 image3)
    (take_image instrument9 Star9 image4)
    (take_image instrument9 Star9 infrared1)
    (take_image instrument9 Star9 spectrograph0)
    )
(:goal (and
	(pointing satellite0 Phenomenon7)
	(pointing satellite3 Star9)
	(pointing satellite4 Planet5)
	(have_image Planet5 image2)
	(have_image Phenomenon6 image3)
	(have_image Phenomenon7 infrared1)
	(have_image Phenomenon8 image2)
	(have_image Star9 image3)
	(have_image Planet10 image4)
	(have_image Planet11 spectrograph0)
	(have_image Phenomenon12 image3)
	(have_image Phenomenon13 spectrograph0)
	(have_image Star14 image4)
))

)
