; Problem taken from https://github.com/AI-Planning/classical-domains

(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0
	instrument0
	instrument1
	satellite1
	instrument2
	instrument3
	satellite2
	instrument4
	instrument5
	satellite3
	instrument6
	instrument7
	satellite4
	instrument8
	instrument9
	instrument10
	infrared0
	spectrograph1
	infrared3
	image4
	image2
	Star1
	GroundStation3
	Star4
	Star2
	Star0
	Planet5
	Star6
	Star7
	Phenomenon8
	Planet9
	Planet10
	Star11
	Star12
	Phenomenon13
	Phenomenon14
	Star15
	Star16
)
(:init
	(satellite satellite0)
	(instrument instrument0)
	(supports instrument0 image4)
	(calibration_target instrument0 Star1)
	(instrument instrument1)
	(supports instrument1 infrared0)
	(supports instrument1 spectrograph1)
	(calibration_target instrument1 GroundStation3)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star0)
	(satellite satellite1)
	(instrument instrument2)
	(supports instrument2 infrared0)
	(supports instrument2 image2)
	(calibration_target instrument2 GroundStation3)
	(instrument instrument3)
	(supports instrument3 infrared3)
	(supports instrument3 infrared0)
	(calibration_target instrument3 Star4)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star4)
	(satellite satellite2)
	(instrument instrument4)
	(supports instrument4 spectrograph1)
	(supports instrument4 image4)
	(supports instrument4 infrared0)
	(calibration_target instrument4 Star2)
	(instrument instrument5)
	(supports instrument5 image2)
	(supports instrument5 infrared0)
	(supports instrument5 infrared3)
	(calibration_target instrument5 Star0)
	(on_board instrument4 satellite2)
	(on_board instrument5 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star1)
	(satellite satellite3)
	(instrument instrument6)
	(supports instrument6 infrared0)
	(supports instrument6 infrared3)
	(calibration_target instrument6 GroundStation3)
	(instrument instrument7)
	(supports instrument7 image4)
	(supports instrument7 spectrograph1)
	(supports instrument7 infrared3)
	(calibration_target instrument7 Star4)
	(on_board instrument6 satellite3)
	(on_board instrument7 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation3)
	(satellite satellite4)
	(instrument instrument8)
	(supports instrument8 spectrograph1)
	(supports instrument8 image4)
	(calibration_target instrument8 Star4)
	(instrument instrument9)
	(supports instrument9 infrared3)
	(calibration_target instrument9 Star2)
	(instrument instrument10)
	(supports instrument10 image2)
	(supports instrument10 image4)
	(calibration_target instrument10 Star0)
	(on_board instrument8 satellite4)
	(on_board instrument9 satellite4)
	(on_board instrument10 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Planet10)
	(mode infrared0)
	(mode spectrograph1)
	(mode infrared3)
	(mode image4)
	(mode image2)
	(direction Star1)
	(direction GroundStation3)
	(direction Star4)
	(direction Star2)
	(direction Star0)
	(direction Planet5)
	(direction Star6)
	(direction Star7)
	(direction Phenomenon8)
	(direction Planet9)
	(direction Planet10)
	(direction Star11)
	(direction Star12)
	(direction Phenomenon13)
	(direction Phenomenon14)
	(direction Star15)
	(direction Star16)

    ; action literals
    (turn_to satellite0 GroundStation3)
    (turn_to satellite0 Phenomenon13)
    (turn_to satellite0 Phenomenon14)
    (turn_to satellite0 Phenomenon8)
    (turn_to satellite0 Planet10)
    (turn_to satellite0 Planet5)
    (turn_to satellite0 Planet9)
    (turn_to satellite0 Star0)
    (turn_to satellite0 Star1)
    (turn_to satellite0 Star11)
    (turn_to satellite0 Star12)
    (turn_to satellite0 Star15)
    (turn_to satellite0 Star16)
    (turn_to satellite0 Star2)
    (turn_to satellite0 Star4)
    (turn_to satellite0 Star6)
    (turn_to satellite0 Star7)
    (turn_to satellite1 GroundStation3)
    (turn_to satellite1 Phenomenon13)
    (turn_to satellite1 Phenomenon14)
    (turn_to satellite1 Phenomenon8)
    (turn_to satellite1 Planet10)
    (turn_to satellite1 Planet5)
    (turn_to satellite1 Planet9)
    (turn_to satellite1 Star0)
    (turn_to satellite1 Star1)
    (turn_to satellite1 Star11)
    (turn_to satellite1 Star12)
    (turn_to satellite1 Star15)
    (turn_to satellite1 Star16)
    (turn_to satellite1 Star2)
    (turn_to satellite1 Star4)
    (turn_to satellite1 Star6)
    (turn_to satellite1 Star7)
    (turn_to satellite2 GroundStation3)
    (turn_to satellite2 Phenomenon13)
    (turn_to satellite2 Phenomenon14)
    (turn_to satellite2 Phenomenon8)
    (turn_to satellite2 Planet10)
    (turn_to satellite2 Planet5)
    (turn_to satellite2 Planet9)
    (turn_to satellite2 Star0)
    (turn_to satellite2 Star1)
    (turn_to satellite2 Star11)
    (turn_to satellite2 Star12)
    (turn_to satellite2 Star15)
    (turn_to satellite2 Star16)
    (turn_to satellite2 Star2)
    (turn_to satellite2 Star4)
    (turn_to satellite2 Star6)
    (turn_to satellite2 Star7)
    (turn_to satellite3 GroundStation3)
    (turn_to satellite3 Phenomenon13)
    (turn_to satellite3 Phenomenon14)
    (turn_to satellite3 Phenomenon8)
    (turn_to satellite3 Planet10)
    (turn_to satellite3 Planet5)
    (turn_to satellite3 Planet9)
    (turn_to satellite3 Star0)
    (turn_to satellite3 Star1)
    (turn_to satellite3 Star11)
    (turn_to satellite3 Star12)
    (turn_to satellite3 Star15)
    (turn_to satellite3 Star16)
    (turn_to satellite3 Star2)
    (turn_to satellite3 Star4)
    (turn_to satellite3 Star6)
    (turn_to satellite3 Star7)
    (turn_to satellite4 GroundStation3)
    (turn_to satellite4 Phenomenon13)
    (turn_to satellite4 Phenomenon14)
    (turn_to satellite4 Phenomenon8)
    (turn_to satellite4 Planet10)
    (turn_to satellite4 Planet5)
    (turn_to satellite4 Planet9)
    (turn_to satellite4 Star0)
    (turn_to satellite4 Star1)
    (turn_to satellite4 Star11)
    (turn_to satellite4 Star12)
    (turn_to satellite4 Star15)
    (turn_to satellite4 Star16)
    (turn_to satellite4 Star2)
    (turn_to satellite4 Star4)
    (turn_to satellite4 Star6)
    (turn_to satellite4 Star7)
    (switch_on instrument0)
    (switch_off instrument0)
    (switch_on instrument1)
    (switch_off instrument1)
    (switch_on instrument10)
    (switch_off instrument10)
    (switch_on instrument2)
    (switch_off instrument2)
    (switch_on instrument3)
    (switch_off instrument3)
    (switch_on instrument4)
    (switch_off instrument4)
    (switch_on instrument5)
    (switch_off instrument5)
    (switch_on instrument6)
    (switch_off instrument6)
    (switch_on instrument7)
    (switch_off instrument7)
    (switch_on instrument8)
    (switch_off instrument8)
    (switch_on instrument9)
    (switch_off instrument9)
    (calibrate instrument0 GroundStation3)
    (calibrate instrument0 Phenomenon13)
    (calibrate instrument0 Phenomenon14)
    (calibrate instrument0 Phenomenon8)
    (calibrate instrument0 Planet10)
    (calibrate instrument0 Planet5)
    (calibrate instrument0 Planet9)
    (calibrate instrument0 Star0)
    (calibrate instrument0 Star1)
    (calibrate instrument0 Star11)
    (calibrate instrument0 Star12)
    (calibrate instrument0 Star15)
    (calibrate instrument0 Star16)
    (calibrate instrument0 Star2)
    (calibrate instrument0 Star4)
    (calibrate instrument0 Star6)
    (calibrate instrument0 Star7)
    (calibrate instrument1 GroundStation3)
    (calibrate instrument1 Phenomenon13)
    (calibrate instrument1 Phenomenon14)
    (calibrate instrument1 Phenomenon8)
    (calibrate instrument1 Planet10)
    (calibrate instrument1 Planet5)
    (calibrate instrument1 Planet9)
    (calibrate instrument1 Star0)
    (calibrate instrument1 Star1)
    (calibrate instrument1 Star11)
    (calibrate instrument1 Star12)
    (calibrate instrument1 Star15)
    (calibrate instrument1 Star16)
    (calibrate instrument1 Star2)
    (calibrate instrument1 Star4)
    (calibrate instrument1 Star6)
    (calibrate instrument1 Star7)
    (calibrate instrument10 GroundStation3)
    (calibrate instrument10 Phenomenon13)
    (calibrate instrument10 Phenomenon14)
    (calibrate instrument10 Phenomenon8)
    (calibrate instrument10 Planet10)
    (calibrate instrument10 Planet5)
    (calibrate instrument10 Planet9)
    (calibrate instrument10 Star0)
    (calibrate instrument10 Star1)
    (calibrate instrument10 Star11)
    (calibrate instrument10 Star12)
    (calibrate instrument10 Star15)
    (calibrate instrument10 Star16)
    (calibrate instrument10 Star2)
    (calibrate instrument10 Star4)
    (calibrate instrument10 Star6)
    (calibrate instrument10 Star7)
    (calibrate instrument2 GroundStation3)
    (calibrate instrument2 Phenomenon13)
    (calibrate instrument2 Phenomenon14)
    (calibrate instrument2 Phenomenon8)
    (calibrate instrument2 Planet10)
    (calibrate instrument2 Planet5)
    (calibrate instrument2 Planet9)
    (calibrate instrument2 Star0)
    (calibrate instrument2 Star1)
    (calibrate instrument2 Star11)
    (calibrate instrument2 Star12)
    (calibrate instrument2 Star15)
    (calibrate instrument2 Star16)
    (calibrate instrument2 Star2)
    (calibrate instrument2 Star4)
    (calibrate instrument2 Star6)
    (calibrate instrument2 Star7)
    (calibrate instrument3 GroundStation3)
    (calibrate instrument3 Phenomenon13)
    (calibrate instrument3 Phenomenon14)
    (calibrate instrument3 Phenomenon8)
    (calibrate instrument3 Planet10)
    (calibrate instrument3 Planet5)
    (calibrate instrument3 Planet9)
    (calibrate instrument3 Star0)
    (calibrate instrument3 Star1)
    (calibrate instrument3 Star11)
    (calibrate instrument3 Star12)
    (calibrate instrument3 Star15)
    (calibrate instrument3 Star16)
    (calibrate instrument3 Star2)
    (calibrate instrument3 Star4)
    (calibrate instrument3 Star6)
    (calibrate instrument3 Star7)
    (calibrate instrument4 GroundStation3)
    (calibrate instrument4 Phenomenon13)
    (calibrate instrument4 Phenomenon14)
    (calibrate instrument4 Phenomenon8)
    (calibrate instrument4 Planet10)
    (calibrate instrument4 Planet5)
    (calibrate instrument4 Planet9)
    (calibrate instrument4 Star0)
    (calibrate instrument4 Star1)
    (calibrate instrument4 Star11)
    (calibrate instrument4 Star12)
    (calibrate instrument4 Star15)
    (calibrate instrument4 Star16)
    (calibrate instrument4 Star2)
    (calibrate instrument4 Star4)
    (calibrate instrument4 Star6)
    (calibrate instrument4 Star7)
    (calibrate instrument5 GroundStation3)
    (calibrate instrument5 Phenomenon13)
    (calibrate instrument5 Phenomenon14)
    (calibrate instrument5 Phenomenon8)
    (calibrate instrument5 Planet10)
    (calibrate instrument5 Planet5)
    (calibrate instrument5 Planet9)
    (calibrate instrument5 Star0)
    (calibrate instrument5 Star1)
    (calibrate instrument5 Star11)
    (calibrate instrument5 Star12)
    (calibrate instrument5 Star15)
    (calibrate instrument5 Star16)
    (calibrate instrument5 Star2)
    (calibrate instrument5 Star4)
    (calibrate instrument5 Star6)
    (calibrate instrument5 Star7)
    (calibrate instrument6 GroundStation3)
    (calibrate instrument6 Phenomenon13)
    (calibrate instrument6 Phenomenon14)
    (calibrate instrument6 Phenomenon8)
    (calibrate instrument6 Planet10)
    (calibrate instrument6 Planet5)
    (calibrate instrument6 Planet9)
    (calibrate instrument6 Star0)
    (calibrate instrument6 Star1)
    (calibrate instrument6 Star11)
    (calibrate instrument6 Star12)
    (calibrate instrument6 Star15)
    (calibrate instrument6 Star16)
    (calibrate instrument6 Star2)
    (calibrate instrument6 Star4)
    (calibrate instrument6 Star6)
    (calibrate instrument6 Star7)
    (calibrate instrument7 GroundStation3)
    (calibrate instrument7 Phenomenon13)
    (calibrate instrument7 Phenomenon14)
    (calibrate instrument7 Phenomenon8)
    (calibrate instrument7 Planet10)
    (calibrate instrument7 Planet5)
    (calibrate instrument7 Planet9)
    (calibrate instrument7 Star0)
    (calibrate instrument7 Star1)
    (calibrate instrument7 Star11)
    (calibrate instrument7 Star12)
    (calibrate instrument7 Star15)
    (calibrate instrument7 Star16)
    (calibrate instrument7 Star2)
    (calibrate instrument7 Star4)
    (calibrate instrument7 Star6)
    (calibrate instrument7 Star7)
    (calibrate instrument8 GroundStation3)
    (calibrate instrument8 Phenomenon13)
    (calibrate instrument8 Phenomenon14)
    (calibrate instrument8 Phenomenon8)
    (calibrate instrument8 Planet10)
    (calibrate instrument8 Planet5)
    (calibrate instrument8 Planet9)
    (calibrate instrument8 Star0)
    (calibrate instrument8 Star1)
    (calibrate instrument8 Star11)
    (calibrate instrument8 Star12)
    (calibrate instrument8 Star15)
    (calibrate instrument8 Star16)
    (calibrate instrument8 Star2)
    (calibrate instrument8 Star4)
    (calibrate instrument8 Star6)
    (calibrate instrument8 Star7)
    (calibrate instrument9 GroundStation3)
    (calibrate instrument9 Phenomenon13)
    (calibrate instrument9 Phenomenon14)
    (calibrate instrument9 Phenomenon8)
    (calibrate instrument9 Planet10)
    (calibrate instrument9 Planet5)
    (calibrate instrument9 Planet9)
    (calibrate instrument9 Star0)
    (calibrate instrument9 Star1)
    (calibrate instrument9 Star11)
    (calibrate instrument9 Star12)
    (calibrate instrument9 Star15)
    (calibrate instrument9 Star16)
    (calibrate instrument9 Star2)
    (calibrate instrument9 Star4)
    (calibrate instrument9 Star6)
    (calibrate instrument9 Star7)
    (take_image instrument0 GroundStation3 image2)
    (take_image instrument0 GroundStation3 image4)
    (take_image instrument0 GroundStation3 infrared0)
    (take_image instrument0 GroundStation3 infrared3)
    (take_image instrument0 GroundStation3 spectrograph1)
    (take_image instrument0 Phenomenon13 image2)
    (take_image instrument0 Phenomenon13 image4)
    (take_image instrument0 Phenomenon13 infrared0)
    (take_image instrument0 Phenomenon13 infrared3)
    (take_image instrument0 Phenomenon13 spectrograph1)
    (take_image instrument0 Phenomenon14 image2)
    (take_image instrument0 Phenomenon14 image4)
    (take_image instrument0 Phenomenon14 infrared0)
    (take_image instrument0 Phenomenon14 infrared3)
    (take_image instrument0 Phenomenon14 spectrograph1)
    (take_image instrument0 Phenomenon8 image2)
    (take_image instrument0 Phenomenon8 image4)
    (take_image instrument0 Phenomenon8 infrared0)
    (take_image instrument0 Phenomenon8 infrared3)
    (take_image instrument0 Phenomenon8 spectrograph1)
    (take_image instrument0 Planet10 image2)
    (take_image instrument0 Planet10 image4)
    (take_image instrument0 Planet10 infrared0)
    (take_image instrument0 Planet10 infrared3)
    (take_image instrument0 Planet10 spectrograph1)
    (take_image instrument0 Planet5 image2)
    (take_image instrument0 Planet5 image4)
    (take_image instrument0 Planet5 infrared0)
    (take_image instrument0 Planet5 infrared3)
    (take_image instrument0 Planet5 spectrograph1)
    (take_image instrument0 Planet9 image2)
    (take_image instrument0 Planet9 image4)
    (take_image instrument0 Planet9 infrared0)
    (take_image instrument0 Planet9 infrared3)
    (take_image instrument0 Planet9 spectrograph1)
    (take_image instrument0 Star0 image2)
    (take_image instrument0 Star0 image4)
    (take_image instrument0 Star0 infrared0)
    (take_image instrument0 Star0 infrared3)
    (take_image instrument0 Star0 spectrograph1)
    (take_image instrument0 Star1 image2)
    (take_image instrument0 Star1 image4)
    (take_image instrument0 Star1 infrared0)
    (take_image instrument0 Star1 infrared3)
    (take_image instrument0 Star1 spectrograph1)
    (take_image instrument0 Star11 image2)
    (take_image instrument0 Star11 image4)
    (take_image instrument0 Star11 infrared0)
    (take_image instrument0 Star11 infrared3)
    (take_image instrument0 Star11 spectrograph1)
    (take_image instrument0 Star12 image2)
    (take_image instrument0 Star12 image4)
    (take_image instrument0 Star12 infrared0)
    (take_image instrument0 Star12 infrared3)
    (take_image instrument0 Star12 spectrograph1)
    (take_image instrument0 Star15 image2)
    (take_image instrument0 Star15 image4)
    (take_image instrument0 Star15 infrared0)
    (take_image instrument0 Star15 infrared3)
    (take_image instrument0 Star15 spectrograph1)
    (take_image instrument0 Star16 image2)
    (take_image instrument0 Star16 image4)
    (take_image instrument0 Star16 infrared0)
    (take_image instrument0 Star16 infrared3)
    (take_image instrument0 Star16 spectrograph1)
    (take_image instrument0 Star2 image2)
    (take_image instrument0 Star2 image4)
    (take_image instrument0 Star2 infrared0)
    (take_image instrument0 Star2 infrared3)
    (take_image instrument0 Star2 spectrograph1)
    (take_image instrument0 Star4 image2)
    (take_image instrument0 Star4 image4)
    (take_image instrument0 Star4 infrared0)
    (take_image instrument0 Star4 infrared3)
    (take_image instrument0 Star4 spectrograph1)
    (take_image instrument0 Star6 image2)
    (take_image instrument0 Star6 image4)
    (take_image instrument0 Star6 infrared0)
    (take_image instrument0 Star6 infrared3)
    (take_image instrument0 Star6 spectrograph1)
    (take_image instrument0 Star7 image2)
    (take_image instrument0 Star7 image4)
    (take_image instrument0 Star7 infrared0)
    (take_image instrument0 Star7 infrared3)
    (take_image instrument0 Star7 spectrograph1)
    (take_image instrument1 GroundStation3 image2)
    (take_image instrument1 GroundStation3 image4)
    (take_image instrument1 GroundStation3 infrared0)
    (take_image instrument1 GroundStation3 infrared3)
    (take_image instrument1 GroundStation3 spectrograph1)
    (take_image instrument1 Phenomenon13 image2)
    (take_image instrument1 Phenomenon13 image4)
    (take_image instrument1 Phenomenon13 infrared0)
    (take_image instrument1 Phenomenon13 infrared3)
    (take_image instrument1 Phenomenon13 spectrograph1)
    (take_image instrument1 Phenomenon14 image2)
    (take_image instrument1 Phenomenon14 image4)
    (take_image instrument1 Phenomenon14 infrared0)
    (take_image instrument1 Phenomenon14 infrared3)
    (take_image instrument1 Phenomenon14 spectrograph1)
    (take_image instrument1 Phenomenon8 image2)
    (take_image instrument1 Phenomenon8 image4)
    (take_image instrument1 Phenomenon8 infrared0)
    (take_image instrument1 Phenomenon8 infrared3)
    (take_image instrument1 Phenomenon8 spectrograph1)
    (take_image instrument1 Planet10 image2)
    (take_image instrument1 Planet10 image4)
    (take_image instrument1 Planet10 infrared0)
    (take_image instrument1 Planet10 infrared3)
    (take_image instrument1 Planet10 spectrograph1)
    (take_image instrument1 Planet5 image2)
    (take_image instrument1 Planet5 image4)
    (take_image instrument1 Planet5 infrared0)
    (take_image instrument1 Planet5 infrared3)
    (take_image instrument1 Planet5 spectrograph1)
    (take_image instrument1 Planet9 image2)
    (take_image instrument1 Planet9 image4)
    (take_image instrument1 Planet9 infrared0)
    (take_image instrument1 Planet9 infrared3)
    (take_image instrument1 Planet9 spectrograph1)
    (take_image instrument1 Star0 image2)
    (take_image instrument1 Star0 image4)
    (take_image instrument1 Star0 infrared0)
    (take_image instrument1 Star0 infrared3)
    (take_image instrument1 Star0 spectrograph1)
    (take_image instrument1 Star1 image2)
    (take_image instrument1 Star1 image4)
    (take_image instrument1 Star1 infrared0)
    (take_image instrument1 Star1 infrared3)
    (take_image instrument1 Star1 spectrograph1)
    (take_image instrument1 Star11 image2)
    (take_image instrument1 Star11 image4)
    (take_image instrument1 Star11 infrared0)
    (take_image instrument1 Star11 infrared3)
    (take_image instrument1 Star11 spectrograph1)
    (take_image instrument1 Star12 image2)
    (take_image instrument1 Star12 image4)
    (take_image instrument1 Star12 infrared0)
    (take_image instrument1 Star12 infrared3)
    (take_image instrument1 Star12 spectrograph1)
    (take_image instrument1 Star15 image2)
    (take_image instrument1 Star15 image4)
    (take_image instrument1 Star15 infrared0)
    (take_image instrument1 Star15 infrared3)
    (take_image instrument1 Star15 spectrograph1)
    (take_image instrument1 Star16 image2)
    (take_image instrument1 Star16 image4)
    (take_image instrument1 Star16 infrared0)
    (take_image instrument1 Star16 infrared3)
    (take_image instrument1 Star16 spectrograph1)
    (take_image instrument1 Star2 image2)
    (take_image instrument1 Star2 image4)
    (take_image instrument1 Star2 infrared0)
    (take_image instrument1 Star2 infrared3)
    (take_image instrument1 Star2 spectrograph1)
    (take_image instrument1 Star4 image2)
    (take_image instrument1 Star4 image4)
    (take_image instrument1 Star4 infrared0)
    (take_image instrument1 Star4 infrared3)
    (take_image instrument1 Star4 spectrograph1)
    (take_image instrument1 Star6 image2)
    (take_image instrument1 Star6 image4)
    (take_image instrument1 Star6 infrared0)
    (take_image instrument1 Star6 infrared3)
    (take_image instrument1 Star6 spectrograph1)
    (take_image instrument1 Star7 image2)
    (take_image instrument1 Star7 image4)
    (take_image instrument1 Star7 infrared0)
    (take_image instrument1 Star7 infrared3)
    (take_image instrument1 Star7 spectrograph1)
    (take_image instrument10 GroundStation3 image2)
    (take_image instrument10 GroundStation3 image4)
    (take_image instrument10 GroundStation3 infrared0)
    (take_image instrument10 GroundStation3 infrared3)
    (take_image instrument10 GroundStation3 spectrograph1)
    (take_image instrument10 Phenomenon13 image2)
    (take_image instrument10 Phenomenon13 image4)
    (take_image instrument10 Phenomenon13 infrared0)
    (take_image instrument10 Phenomenon13 infrared3)
    (take_image instrument10 Phenomenon13 spectrograph1)
    (take_image instrument10 Phenomenon14 image2)
    (take_image instrument10 Phenomenon14 image4)
    (take_image instrument10 Phenomenon14 infrared0)
    (take_image instrument10 Phenomenon14 infrared3)
    (take_image instrument10 Phenomenon14 spectrograph1)
    (take_image instrument10 Phenomenon8 image2)
    (take_image instrument10 Phenomenon8 image4)
    (take_image instrument10 Phenomenon8 infrared0)
    (take_image instrument10 Phenomenon8 infrared3)
    (take_image instrument10 Phenomenon8 spectrograph1)
    (take_image instrument10 Planet10 image2)
    (take_image instrument10 Planet10 image4)
    (take_image instrument10 Planet10 infrared0)
    (take_image instrument10 Planet10 infrared3)
    (take_image instrument10 Planet10 spectrograph1)
    (take_image instrument10 Planet5 image2)
    (take_image instrument10 Planet5 image4)
    (take_image instrument10 Planet5 infrared0)
    (take_image instrument10 Planet5 infrared3)
    (take_image instrument10 Planet5 spectrograph1)
    (take_image instrument10 Planet9 image2)
    (take_image instrument10 Planet9 image4)
    (take_image instrument10 Planet9 infrared0)
    (take_image instrument10 Planet9 infrared3)
    (take_image instrument10 Planet9 spectrograph1)
    (take_image instrument10 Star0 image2)
    (take_image instrument10 Star0 image4)
    (take_image instrument10 Star0 infrared0)
    (take_image instrument10 Star0 infrared3)
    (take_image instrument10 Star0 spectrograph1)
    (take_image instrument10 Star1 image2)
    (take_image instrument10 Star1 image4)
    (take_image instrument10 Star1 infrared0)
    (take_image instrument10 Star1 infrared3)
    (take_image instrument10 Star1 spectrograph1)
    (take_image instrument10 Star11 image2)
    (take_image instrument10 Star11 image4)
    (take_image instrument10 Star11 infrared0)
    (take_image instrument10 Star11 infrared3)
    (take_image instrument10 Star11 spectrograph1)
    (take_image instrument10 Star12 image2)
    (take_image instrument10 Star12 image4)
    (take_image instrument10 Star12 infrared0)
    (take_image instrument10 Star12 infrared3)
    (take_image instrument10 Star12 spectrograph1)
    (take_image instrument10 Star15 image2)
    (take_image instrument10 Star15 image4)
    (take_image instrument10 Star15 infrared0)
    (take_image instrument10 Star15 infrared3)
    (take_image instrument10 Star15 spectrograph1)
    (take_image instrument10 Star16 image2)
    (take_image instrument10 Star16 image4)
    (take_image instrument10 Star16 infrared0)
    (take_image instrument10 Star16 infrared3)
    (take_image instrument10 Star16 spectrograph1)
    (take_image instrument10 Star2 image2)
    (take_image instrument10 Star2 image4)
    (take_image instrument10 Star2 infrared0)
    (take_image instrument10 Star2 infrared3)
    (take_image instrument10 Star2 spectrograph1)
    (take_image instrument10 Star4 image2)
    (take_image instrument10 Star4 image4)
    (take_image instrument10 Star4 infrared0)
    (take_image instrument10 Star4 infrared3)
    (take_image instrument10 Star4 spectrograph1)
    (take_image instrument10 Star6 image2)
    (take_image instrument10 Star6 image4)
    (take_image instrument10 Star6 infrared0)
    (take_image instrument10 Star6 infrared3)
    (take_image instrument10 Star6 spectrograph1)
    (take_image instrument10 Star7 image2)
    (take_image instrument10 Star7 image4)
    (take_image instrument10 Star7 infrared0)
    (take_image instrument10 Star7 infrared3)
    (take_image instrument10 Star7 spectrograph1)
    (take_image instrument2 GroundStation3 image2)
    (take_image instrument2 GroundStation3 image4)
    (take_image instrument2 GroundStation3 infrared0)
    (take_image instrument2 GroundStation3 infrared3)
    (take_image instrument2 GroundStation3 spectrograph1)
    (take_image instrument2 Phenomenon13 image2)
    (take_image instrument2 Phenomenon13 image4)
    (take_image instrument2 Phenomenon13 infrared0)
    (take_image instrument2 Phenomenon13 infrared3)
    (take_image instrument2 Phenomenon13 spectrograph1)
    (take_image instrument2 Phenomenon14 image2)
    (take_image instrument2 Phenomenon14 image4)
    (take_image instrument2 Phenomenon14 infrared0)
    (take_image instrument2 Phenomenon14 infrared3)
    (take_image instrument2 Phenomenon14 spectrograph1)
    (take_image instrument2 Phenomenon8 image2)
    (take_image instrument2 Phenomenon8 image4)
    (take_image instrument2 Phenomenon8 infrared0)
    (take_image instrument2 Phenomenon8 infrared3)
    (take_image instrument2 Phenomenon8 spectrograph1)
    (take_image instrument2 Planet10 image2)
    (take_image instrument2 Planet10 image4)
    (take_image instrument2 Planet10 infrared0)
    (take_image instrument2 Planet10 infrared3)
    (take_image instrument2 Planet10 spectrograph1)
    (take_image instrument2 Planet5 image2)
    (take_image instrument2 Planet5 image4)
    (take_image instrument2 Planet5 infrared0)
    (take_image instrument2 Planet5 infrared3)
    (take_image instrument2 Planet5 spectrograph1)
    (take_image instrument2 Planet9 image2)
    (take_image instrument2 Planet9 image4)
    (take_image instrument2 Planet9 infrared0)
    (take_image instrument2 Planet9 infrared3)
    (take_image instrument2 Planet9 spectrograph1)
    (take_image instrument2 Star0 image2)
    (take_image instrument2 Star0 image4)
    (take_image instrument2 Star0 infrared0)
    (take_image instrument2 Star0 infrared3)
    (take_image instrument2 Star0 spectrograph1)
    (take_image instrument2 Star1 image2)
    (take_image instrument2 Star1 image4)
    (take_image instrument2 Star1 infrared0)
    (take_image instrument2 Star1 infrared3)
    (take_image instrument2 Star1 spectrograph1)
    (take_image instrument2 Star11 image2)
    (take_image instrument2 Star11 image4)
    (take_image instrument2 Star11 infrared0)
    (take_image instrument2 Star11 infrared3)
    (take_image instrument2 Star11 spectrograph1)
    (take_image instrument2 Star12 image2)
    (take_image instrument2 Star12 image4)
    (take_image instrument2 Star12 infrared0)
    (take_image instrument2 Star12 infrared3)
    (take_image instrument2 Star12 spectrograph1)
    (take_image instrument2 Star15 image2)
    (take_image instrument2 Star15 image4)
    (take_image instrument2 Star15 infrared0)
    (take_image instrument2 Star15 infrared3)
    (take_image instrument2 Star15 spectrograph1)
    (take_image instrument2 Star16 image2)
    (take_image instrument2 Star16 image4)
    (take_image instrument2 Star16 infrared0)
    (take_image instrument2 Star16 infrared3)
    (take_image instrument2 Star16 spectrograph1)
    (take_image instrument2 Star2 image2)
    (take_image instrument2 Star2 image4)
    (take_image instrument2 Star2 infrared0)
    (take_image instrument2 Star2 infrared3)
    (take_image instrument2 Star2 spectrograph1)
    (take_image instrument2 Star4 image2)
    (take_image instrument2 Star4 image4)
    (take_image instrument2 Star4 infrared0)
    (take_image instrument2 Star4 infrared3)
    (take_image instrument2 Star4 spectrograph1)
    (take_image instrument2 Star6 image2)
    (take_image instrument2 Star6 image4)
    (take_image instrument2 Star6 infrared0)
    (take_image instrument2 Star6 infrared3)
    (take_image instrument2 Star6 spectrograph1)
    (take_image instrument2 Star7 image2)
    (take_image instrument2 Star7 image4)
    (take_image instrument2 Star7 infrared0)
    (take_image instrument2 Star7 infrared3)
    (take_image instrument2 Star7 spectrograph1)
    (take_image instrument3 GroundStation3 image2)
    (take_image instrument3 GroundStation3 image4)
    (take_image instrument3 GroundStation3 infrared0)
    (take_image instrument3 GroundStation3 infrared3)
    (take_image instrument3 GroundStation3 spectrograph1)
    (take_image instrument3 Phenomenon13 image2)
    (take_image instrument3 Phenomenon13 image4)
    (take_image instrument3 Phenomenon13 infrared0)
    (take_image instrument3 Phenomenon13 infrared3)
    (take_image instrument3 Phenomenon13 spectrograph1)
    (take_image instrument3 Phenomenon14 image2)
    (take_image instrument3 Phenomenon14 image4)
    (take_image instrument3 Phenomenon14 infrared0)
    (take_image instrument3 Phenomenon14 infrared3)
    (take_image instrument3 Phenomenon14 spectrograph1)
    (take_image instrument3 Phenomenon8 image2)
    (take_image instrument3 Phenomenon8 image4)
    (take_image instrument3 Phenomenon8 infrared0)
    (take_image instrument3 Phenomenon8 infrared3)
    (take_image instrument3 Phenomenon8 spectrograph1)
    (take_image instrument3 Planet10 image2)
    (take_image instrument3 Planet10 image4)
    (take_image instrument3 Planet10 infrared0)
    (take_image instrument3 Planet10 infrared3)
    (take_image instrument3 Planet10 spectrograph1)
    (take_image instrument3 Planet5 image2)
    (take_image instrument3 Planet5 image4)
    (take_image instrument3 Planet5 infrared0)
    (take_image instrument3 Planet5 infrared3)
    (take_image instrument3 Planet5 spectrograph1)
    (take_image instrument3 Planet9 image2)
    (take_image instrument3 Planet9 image4)
    (take_image instrument3 Planet9 infrared0)
    (take_image instrument3 Planet9 infrared3)
    (take_image instrument3 Planet9 spectrograph1)
    (take_image instrument3 Star0 image2)
    (take_image instrument3 Star0 image4)
    (take_image instrument3 Star0 infrared0)
    (take_image instrument3 Star0 infrared3)
    (take_image instrument3 Star0 spectrograph1)
    (take_image instrument3 Star1 image2)
    (take_image instrument3 Star1 image4)
    (take_image instrument3 Star1 infrared0)
    (take_image instrument3 Star1 infrared3)
    (take_image instrument3 Star1 spectrograph1)
    (take_image instrument3 Star11 image2)
    (take_image instrument3 Star11 image4)
    (take_image instrument3 Star11 infrared0)
    (take_image instrument3 Star11 infrared3)
    (take_image instrument3 Star11 spectrograph1)
    (take_image instrument3 Star12 image2)
    (take_image instrument3 Star12 image4)
    (take_image instrument3 Star12 infrared0)
    (take_image instrument3 Star12 infrared3)
    (take_image instrument3 Star12 spectrograph1)
    (take_image instrument3 Star15 image2)
    (take_image instrument3 Star15 image4)
    (take_image instrument3 Star15 infrared0)
    (take_image instrument3 Star15 infrared3)
    (take_image instrument3 Star15 spectrograph1)
    (take_image instrument3 Star16 image2)
    (take_image instrument3 Star16 image4)
    (take_image instrument3 Star16 infrared0)
    (take_image instrument3 Star16 infrared3)
    (take_image instrument3 Star16 spectrograph1)
    (take_image instrument3 Star2 image2)
    (take_image instrument3 Star2 image4)
    (take_image instrument3 Star2 infrared0)
    (take_image instrument3 Star2 infrared3)
    (take_image instrument3 Star2 spectrograph1)
    (take_image instrument3 Star4 image2)
    (take_image instrument3 Star4 image4)
    (take_image instrument3 Star4 infrared0)
    (take_image instrument3 Star4 infrared3)
    (take_image instrument3 Star4 spectrograph1)
    (take_image instrument3 Star6 image2)
    (take_image instrument3 Star6 image4)
    (take_image instrument3 Star6 infrared0)
    (take_image instrument3 Star6 infrared3)
    (take_image instrument3 Star6 spectrograph1)
    (take_image instrument3 Star7 image2)
    (take_image instrument3 Star7 image4)
    (take_image instrument3 Star7 infrared0)
    (take_image instrument3 Star7 infrared3)
    (take_image instrument3 Star7 spectrograph1)
    (take_image instrument4 GroundStation3 image2)
    (take_image instrument4 GroundStation3 image4)
    (take_image instrument4 GroundStation3 infrared0)
    (take_image instrument4 GroundStation3 infrared3)
    (take_image instrument4 GroundStation3 spectrograph1)
    (take_image instrument4 Phenomenon13 image2)
    (take_image instrument4 Phenomenon13 image4)
    (take_image instrument4 Phenomenon13 infrared0)
    (take_image instrument4 Phenomenon13 infrared3)
    (take_image instrument4 Phenomenon13 spectrograph1)
    (take_image instrument4 Phenomenon14 image2)
    (take_image instrument4 Phenomenon14 image4)
    (take_image instrument4 Phenomenon14 infrared0)
    (take_image instrument4 Phenomenon14 infrared3)
    (take_image instrument4 Phenomenon14 spectrograph1)
    (take_image instrument4 Phenomenon8 image2)
    (take_image instrument4 Phenomenon8 image4)
    (take_image instrument4 Phenomenon8 infrared0)
    (take_image instrument4 Phenomenon8 infrared3)
    (take_image instrument4 Phenomenon8 spectrograph1)
    (take_image instrument4 Planet10 image2)
    (take_image instrument4 Planet10 image4)
    (take_image instrument4 Planet10 infrared0)
    (take_image instrument4 Planet10 infrared3)
    (take_image instrument4 Planet10 spectrograph1)
    (take_image instrument4 Planet5 image2)
    (take_image instrument4 Planet5 image4)
    (take_image instrument4 Planet5 infrared0)
    (take_image instrument4 Planet5 infrared3)
    (take_image instrument4 Planet5 spectrograph1)
    (take_image instrument4 Planet9 image2)
    (take_image instrument4 Planet9 image4)
    (take_image instrument4 Planet9 infrared0)
    (take_image instrument4 Planet9 infrared3)
    (take_image instrument4 Planet9 spectrograph1)
    (take_image instrument4 Star0 image2)
    (take_image instrument4 Star0 image4)
    (take_image instrument4 Star0 infrared0)
    (take_image instrument4 Star0 infrared3)
    (take_image instrument4 Star0 spectrograph1)
    (take_image instrument4 Star1 image2)
    (take_image instrument4 Star1 image4)
    (take_image instrument4 Star1 infrared0)
    (take_image instrument4 Star1 infrared3)
    (take_image instrument4 Star1 spectrograph1)
    (take_image instrument4 Star11 image2)
    (take_image instrument4 Star11 image4)
    (take_image instrument4 Star11 infrared0)
    (take_image instrument4 Star11 infrared3)
    (take_image instrument4 Star11 spectrograph1)
    (take_image instrument4 Star12 image2)
    (take_image instrument4 Star12 image4)
    (take_image instrument4 Star12 infrared0)
    (take_image instrument4 Star12 infrared3)
    (take_image instrument4 Star12 spectrograph1)
    (take_image instrument4 Star15 image2)
    (take_image instrument4 Star15 image4)
    (take_image instrument4 Star15 infrared0)
    (take_image instrument4 Star15 infrared3)
    (take_image instrument4 Star15 spectrograph1)
    (take_image instrument4 Star16 image2)
    (take_image instrument4 Star16 image4)
    (take_image instrument4 Star16 infrared0)
    (take_image instrument4 Star16 infrared3)
    (take_image instrument4 Star16 spectrograph1)
    (take_image instrument4 Star2 image2)
    (take_image instrument4 Star2 image4)
    (take_image instrument4 Star2 infrared0)
    (take_image instrument4 Star2 infrared3)
    (take_image instrument4 Star2 spectrograph1)
    (take_image instrument4 Star4 image2)
    (take_image instrument4 Star4 image4)
    (take_image instrument4 Star4 infrared0)
    (take_image instrument4 Star4 infrared3)
    (take_image instrument4 Star4 spectrograph1)
    (take_image instrument4 Star6 image2)
    (take_image instrument4 Star6 image4)
    (take_image instrument4 Star6 infrared0)
    (take_image instrument4 Star6 infrared3)
    (take_image instrument4 Star6 spectrograph1)
    (take_image instrument4 Star7 image2)
    (take_image instrument4 Star7 image4)
    (take_image instrument4 Star7 infrared0)
    (take_image instrument4 Star7 infrared3)
    (take_image instrument4 Star7 spectrograph1)
    (take_image instrument5 GroundStation3 image2)
    (take_image instrument5 GroundStation3 image4)
    (take_image instrument5 GroundStation3 infrared0)
    (take_image instrument5 GroundStation3 infrared3)
    (take_image instrument5 GroundStation3 spectrograph1)
    (take_image instrument5 Phenomenon13 image2)
    (take_image instrument5 Phenomenon13 image4)
    (take_image instrument5 Phenomenon13 infrared0)
    (take_image instrument5 Phenomenon13 infrared3)
    (take_image instrument5 Phenomenon13 spectrograph1)
    (take_image instrument5 Phenomenon14 image2)
    (take_image instrument5 Phenomenon14 image4)
    (take_image instrument5 Phenomenon14 infrared0)
    (take_image instrument5 Phenomenon14 infrared3)
    (take_image instrument5 Phenomenon14 spectrograph1)
    (take_image instrument5 Phenomenon8 image2)
    (take_image instrument5 Phenomenon8 image4)
    (take_image instrument5 Phenomenon8 infrared0)
    (take_image instrument5 Phenomenon8 infrared3)
    (take_image instrument5 Phenomenon8 spectrograph1)
    (take_image instrument5 Planet10 image2)
    (take_image instrument5 Planet10 image4)
    (take_image instrument5 Planet10 infrared0)
    (take_image instrument5 Planet10 infrared3)
    (take_image instrument5 Planet10 spectrograph1)
    (take_image instrument5 Planet5 image2)
    (take_image instrument5 Planet5 image4)
    (take_image instrument5 Planet5 infrared0)
    (take_image instrument5 Planet5 infrared3)
    (take_image instrument5 Planet5 spectrograph1)
    (take_image instrument5 Planet9 image2)
    (take_image instrument5 Planet9 image4)
    (take_image instrument5 Planet9 infrared0)
    (take_image instrument5 Planet9 infrared3)
    (take_image instrument5 Planet9 spectrograph1)
    (take_image instrument5 Star0 image2)
    (take_image instrument5 Star0 image4)
    (take_image instrument5 Star0 infrared0)
    (take_image instrument5 Star0 infrared3)
    (take_image instrument5 Star0 spectrograph1)
    (take_image instrument5 Star1 image2)
    (take_image instrument5 Star1 image4)
    (take_image instrument5 Star1 infrared0)
    (take_image instrument5 Star1 infrared3)
    (take_image instrument5 Star1 spectrograph1)
    (take_image instrument5 Star11 image2)
    (take_image instrument5 Star11 image4)
    (take_image instrument5 Star11 infrared0)
    (take_image instrument5 Star11 infrared3)
    (take_image instrument5 Star11 spectrograph1)
    (take_image instrument5 Star12 image2)
    (take_image instrument5 Star12 image4)
    (take_image instrument5 Star12 infrared0)
    (take_image instrument5 Star12 infrared3)
    (take_image instrument5 Star12 spectrograph1)
    (take_image instrument5 Star15 image2)
    (take_image instrument5 Star15 image4)
    (take_image instrument5 Star15 infrared0)
    (take_image instrument5 Star15 infrared3)
    (take_image instrument5 Star15 spectrograph1)
    (take_image instrument5 Star16 image2)
    (take_image instrument5 Star16 image4)
    (take_image instrument5 Star16 infrared0)
    (take_image instrument5 Star16 infrared3)
    (take_image instrument5 Star16 spectrograph1)
    (take_image instrument5 Star2 image2)
    (take_image instrument5 Star2 image4)
    (take_image instrument5 Star2 infrared0)
    (take_image instrument5 Star2 infrared3)
    (take_image instrument5 Star2 spectrograph1)
    (take_image instrument5 Star4 image2)
    (take_image instrument5 Star4 image4)
    (take_image instrument5 Star4 infrared0)
    (take_image instrument5 Star4 infrared3)
    (take_image instrument5 Star4 spectrograph1)
    (take_image instrument5 Star6 image2)
    (take_image instrument5 Star6 image4)
    (take_image instrument5 Star6 infrared0)
    (take_image instrument5 Star6 infrared3)
    (take_image instrument5 Star6 spectrograph1)
    (take_image instrument5 Star7 image2)
    (take_image instrument5 Star7 image4)
    (take_image instrument5 Star7 infrared0)
    (take_image instrument5 Star7 infrared3)
    (take_image instrument5 Star7 spectrograph1)
    (take_image instrument6 GroundStation3 image2)
    (take_image instrument6 GroundStation3 image4)
    (take_image instrument6 GroundStation3 infrared0)
    (take_image instrument6 GroundStation3 infrared3)
    (take_image instrument6 GroundStation3 spectrograph1)
    (take_image instrument6 Phenomenon13 image2)
    (take_image instrument6 Phenomenon13 image4)
    (take_image instrument6 Phenomenon13 infrared0)
    (take_image instrument6 Phenomenon13 infrared3)
    (take_image instrument6 Phenomenon13 spectrograph1)
    (take_image instrument6 Phenomenon14 image2)
    (take_image instrument6 Phenomenon14 image4)
    (take_image instrument6 Phenomenon14 infrared0)
    (take_image instrument6 Phenomenon14 infrared3)
    (take_image instrument6 Phenomenon14 spectrograph1)
    (take_image instrument6 Phenomenon8 image2)
    (take_image instrument6 Phenomenon8 image4)
    (take_image instrument6 Phenomenon8 infrared0)
    (take_image instrument6 Phenomenon8 infrared3)
    (take_image instrument6 Phenomenon8 spectrograph1)
    (take_image instrument6 Planet10 image2)
    (take_image instrument6 Planet10 image4)
    (take_image instrument6 Planet10 infrared0)
    (take_image instrument6 Planet10 infrared3)
    (take_image instrument6 Planet10 spectrograph1)
    (take_image instrument6 Planet5 image2)
    (take_image instrument6 Planet5 image4)
    (take_image instrument6 Planet5 infrared0)
    (take_image instrument6 Planet5 infrared3)
    (take_image instrument6 Planet5 spectrograph1)
    (take_image instrument6 Planet9 image2)
    (take_image instrument6 Planet9 image4)
    (take_image instrument6 Planet9 infrared0)
    (take_image instrument6 Planet9 infrared3)
    (take_image instrument6 Planet9 spectrograph1)
    (take_image instrument6 Star0 image2)
    (take_image instrument6 Star0 image4)
    (take_image instrument6 Star0 infrared0)
    (take_image instrument6 Star0 infrared3)
    (take_image instrument6 Star0 spectrograph1)
    (take_image instrument6 Star1 image2)
    (take_image instrument6 Star1 image4)
    (take_image instrument6 Star1 infrared0)
    (take_image instrument6 Star1 infrared3)
    (take_image instrument6 Star1 spectrograph1)
    (take_image instrument6 Star11 image2)
    (take_image instrument6 Star11 image4)
    (take_image instrument6 Star11 infrared0)
    (take_image instrument6 Star11 infrared3)
    (take_image instrument6 Star11 spectrograph1)
    (take_image instrument6 Star12 image2)
    (take_image instrument6 Star12 image4)
    (take_image instrument6 Star12 infrared0)
    (take_image instrument6 Star12 infrared3)
    (take_image instrument6 Star12 spectrograph1)
    (take_image instrument6 Star15 image2)
    (take_image instrument6 Star15 image4)
    (take_image instrument6 Star15 infrared0)
    (take_image instrument6 Star15 infrared3)
    (take_image instrument6 Star15 spectrograph1)
    (take_image instrument6 Star16 image2)
    (take_image instrument6 Star16 image4)
    (take_image instrument6 Star16 infrared0)
    (take_image instrument6 Star16 infrared3)
    (take_image instrument6 Star16 spectrograph1)
    (take_image instrument6 Star2 image2)
    (take_image instrument6 Star2 image4)
    (take_image instrument6 Star2 infrared0)
    (take_image instrument6 Star2 infrared3)
    (take_image instrument6 Star2 spectrograph1)
    (take_image instrument6 Star4 image2)
    (take_image instrument6 Star4 image4)
    (take_image instrument6 Star4 infrared0)
    (take_image instrument6 Star4 infrared3)
    (take_image instrument6 Star4 spectrograph1)
    (take_image instrument6 Star6 image2)
    (take_image instrument6 Star6 image4)
    (take_image instrument6 Star6 infrared0)
    (take_image instrument6 Star6 infrared3)
    (take_image instrument6 Star6 spectrograph1)
    (take_image instrument6 Star7 image2)
    (take_image instrument6 Star7 image4)
    (take_image instrument6 Star7 infrared0)
    (take_image instrument6 Star7 infrared3)
    (take_image instrument6 Star7 spectrograph1)
    (take_image instrument7 GroundStation3 image2)
    (take_image instrument7 GroundStation3 image4)
    (take_image instrument7 GroundStation3 infrared0)
    (take_image instrument7 GroundStation3 infrared3)
    (take_image instrument7 GroundStation3 spectrograph1)
    (take_image instrument7 Phenomenon13 image2)
    (take_image instrument7 Phenomenon13 image4)
    (take_image instrument7 Phenomenon13 infrared0)
    (take_image instrument7 Phenomenon13 infrared3)
    (take_image instrument7 Phenomenon13 spectrograph1)
    (take_image instrument7 Phenomenon14 image2)
    (take_image instrument7 Phenomenon14 image4)
    (take_image instrument7 Phenomenon14 infrared0)
    (take_image instrument7 Phenomenon14 infrared3)
    (take_image instrument7 Phenomenon14 spectrograph1)
    (take_image instrument7 Phenomenon8 image2)
    (take_image instrument7 Phenomenon8 image4)
    (take_image instrument7 Phenomenon8 infrared0)
    (take_image instrument7 Phenomenon8 infrared3)
    (take_image instrument7 Phenomenon8 spectrograph1)
    (take_image instrument7 Planet10 image2)
    (take_image instrument7 Planet10 image4)
    (take_image instrument7 Planet10 infrared0)
    (take_image instrument7 Planet10 infrared3)
    (take_image instrument7 Planet10 spectrograph1)
    (take_image instrument7 Planet5 image2)
    (take_image instrument7 Planet5 image4)
    (take_image instrument7 Planet5 infrared0)
    (take_image instrument7 Planet5 infrared3)
    (take_image instrument7 Planet5 spectrograph1)
    (take_image instrument7 Planet9 image2)
    (take_image instrument7 Planet9 image4)
    (take_image instrument7 Planet9 infrared0)
    (take_image instrument7 Planet9 infrared3)
    (take_image instrument7 Planet9 spectrograph1)
    (take_image instrument7 Star0 image2)
    (take_image instrument7 Star0 image4)
    (take_image instrument7 Star0 infrared0)
    (take_image instrument7 Star0 infrared3)
    (take_image instrument7 Star0 spectrograph1)
    (take_image instrument7 Star1 image2)
    (take_image instrument7 Star1 image4)
    (take_image instrument7 Star1 infrared0)
    (take_image instrument7 Star1 infrared3)
    (take_image instrument7 Star1 spectrograph1)
    (take_image instrument7 Star11 image2)
    (take_image instrument7 Star11 image4)
    (take_image instrument7 Star11 infrared0)
    (take_image instrument7 Star11 infrared3)
    (take_image instrument7 Star11 spectrograph1)
    (take_image instrument7 Star12 image2)
    (take_image instrument7 Star12 image4)
    (take_image instrument7 Star12 infrared0)
    (take_image instrument7 Star12 infrared3)
    (take_image instrument7 Star12 spectrograph1)
    (take_image instrument7 Star15 image2)
    (take_image instrument7 Star15 image4)
    (take_image instrument7 Star15 infrared0)
    (take_image instrument7 Star15 infrared3)
    (take_image instrument7 Star15 spectrograph1)
    (take_image instrument7 Star16 image2)
    (take_image instrument7 Star16 image4)
    (take_image instrument7 Star16 infrared0)
    (take_image instrument7 Star16 infrared3)
    (take_image instrument7 Star16 spectrograph1)
    (take_image instrument7 Star2 image2)
    (take_image instrument7 Star2 image4)
    (take_image instrument7 Star2 infrared0)
    (take_image instrument7 Star2 infrared3)
    (take_image instrument7 Star2 spectrograph1)
    (take_image instrument7 Star4 image2)
    (take_image instrument7 Star4 image4)
    (take_image instrument7 Star4 infrared0)
    (take_image instrument7 Star4 infrared3)
    (take_image instrument7 Star4 spectrograph1)
    (take_image instrument7 Star6 image2)
    (take_image instrument7 Star6 image4)
    (take_image instrument7 Star6 infrared0)
    (take_image instrument7 Star6 infrared3)
    (take_image instrument7 Star6 spectrograph1)
    (take_image instrument7 Star7 image2)
    (take_image instrument7 Star7 image4)
    (take_image instrument7 Star7 infrared0)
    (take_image instrument7 Star7 infrared3)
    (take_image instrument7 Star7 spectrograph1)
    (take_image instrument8 GroundStation3 image2)
    (take_image instrument8 GroundStation3 image4)
    (take_image instrument8 GroundStation3 infrared0)
    (take_image instrument8 GroundStation3 infrared3)
    (take_image instrument8 GroundStation3 spectrograph1)
    (take_image instrument8 Phenomenon13 image2)
    (take_image instrument8 Phenomenon13 image4)
    (take_image instrument8 Phenomenon13 infrared0)
    (take_image instrument8 Phenomenon13 infrared3)
    (take_image instrument8 Phenomenon13 spectrograph1)
    (take_image instrument8 Phenomenon14 image2)
    (take_image instrument8 Phenomenon14 image4)
    (take_image instrument8 Phenomenon14 infrared0)
    (take_image instrument8 Phenomenon14 infrared3)
    (take_image instrument8 Phenomenon14 spectrograph1)
    (take_image instrument8 Phenomenon8 image2)
    (take_image instrument8 Phenomenon8 image4)
    (take_image instrument8 Phenomenon8 infrared0)
    (take_image instrument8 Phenomenon8 infrared3)
    (take_image instrument8 Phenomenon8 spectrograph1)
    (take_image instrument8 Planet10 image2)
    (take_image instrument8 Planet10 image4)
    (take_image instrument8 Planet10 infrared0)
    (take_image instrument8 Planet10 infrared3)
    (take_image instrument8 Planet10 spectrograph1)
    (take_image instrument8 Planet5 image2)
    (take_image instrument8 Planet5 image4)
    (take_image instrument8 Planet5 infrared0)
    (take_image instrument8 Planet5 infrared3)
    (take_image instrument8 Planet5 spectrograph1)
    (take_image instrument8 Planet9 image2)
    (take_image instrument8 Planet9 image4)
    (take_image instrument8 Planet9 infrared0)
    (take_image instrument8 Planet9 infrared3)
    (take_image instrument8 Planet9 spectrograph1)
    (take_image instrument8 Star0 image2)
    (take_image instrument8 Star0 image4)
    (take_image instrument8 Star0 infrared0)
    (take_image instrument8 Star0 infrared3)
    (take_image instrument8 Star0 spectrograph1)
    (take_image instrument8 Star1 image2)
    (take_image instrument8 Star1 image4)
    (take_image instrument8 Star1 infrared0)
    (take_image instrument8 Star1 infrared3)
    (take_image instrument8 Star1 spectrograph1)
    (take_image instrument8 Star11 image2)
    (take_image instrument8 Star11 image4)
    (take_image instrument8 Star11 infrared0)
    (take_image instrument8 Star11 infrared3)
    (take_image instrument8 Star11 spectrograph1)
    (take_image instrument8 Star12 image2)
    (take_image instrument8 Star12 image4)
    (take_image instrument8 Star12 infrared0)
    (take_image instrument8 Star12 infrared3)
    (take_image instrument8 Star12 spectrograph1)
    (take_image instrument8 Star15 image2)
    (take_image instrument8 Star15 image4)
    (take_image instrument8 Star15 infrared0)
    (take_image instrument8 Star15 infrared3)
    (take_image instrument8 Star15 spectrograph1)
    (take_image instrument8 Star16 image2)
    (take_image instrument8 Star16 image4)
    (take_image instrument8 Star16 infrared0)
    (take_image instrument8 Star16 infrared3)
    (take_image instrument8 Star16 spectrograph1)
    (take_image instrument8 Star2 image2)
    (take_image instrument8 Star2 image4)
    (take_image instrument8 Star2 infrared0)
    (take_image instrument8 Star2 infrared3)
    (take_image instrument8 Star2 spectrograph1)
    (take_image instrument8 Star4 image2)
    (take_image instrument8 Star4 image4)
    (take_image instrument8 Star4 infrared0)
    (take_image instrument8 Star4 infrared3)
    (take_image instrument8 Star4 spectrograph1)
    (take_image instrument8 Star6 image2)
    (take_image instrument8 Star6 image4)
    (take_image instrument8 Star6 infrared0)
    (take_image instrument8 Star6 infrared3)
    (take_image instrument8 Star6 spectrograph1)
    (take_image instrument8 Star7 image2)
    (take_image instrument8 Star7 image4)
    (take_image instrument8 Star7 infrared0)
    (take_image instrument8 Star7 infrared3)
    (take_image instrument8 Star7 spectrograph1)
    (take_image instrument9 GroundStation3 image2)
    (take_image instrument9 GroundStation3 image4)
    (take_image instrument9 GroundStation3 infrared0)
    (take_image instrument9 GroundStation3 infrared3)
    (take_image instrument9 GroundStation3 spectrograph1)
    (take_image instrument9 Phenomenon13 image2)
    (take_image instrument9 Phenomenon13 image4)
    (take_image instrument9 Phenomenon13 infrared0)
    (take_image instrument9 Phenomenon13 infrared3)
    (take_image instrument9 Phenomenon13 spectrograph1)
    (take_image instrument9 Phenomenon14 image2)
    (take_image instrument9 Phenomenon14 image4)
    (take_image instrument9 Phenomenon14 infrared0)
    (take_image instrument9 Phenomenon14 infrared3)
    (take_image instrument9 Phenomenon14 spectrograph1)
    (take_image instrument9 Phenomenon8 image2)
    (take_image instrument9 Phenomenon8 image4)
    (take_image instrument9 Phenomenon8 infrared0)
    (take_image instrument9 Phenomenon8 infrared3)
    (take_image instrument9 Phenomenon8 spectrograph1)
    (take_image instrument9 Planet10 image2)
    (take_image instrument9 Planet10 image4)
    (take_image instrument9 Planet10 infrared0)
    (take_image instrument9 Planet10 infrared3)
    (take_image instrument9 Planet10 spectrograph1)
    (take_image instrument9 Planet5 image2)
    (take_image instrument9 Planet5 image4)
    (take_image instrument9 Planet5 infrared0)
    (take_image instrument9 Planet5 infrared3)
    (take_image instrument9 Planet5 spectrograph1)
    (take_image instrument9 Planet9 image2)
    (take_image instrument9 Planet9 image4)
    (take_image instrument9 Planet9 infrared0)
    (take_image instrument9 Planet9 infrared3)
    (take_image instrument9 Planet9 spectrograph1)
    (take_image instrument9 Star0 image2)
    (take_image instrument9 Star0 image4)
    (take_image instrument9 Star0 infrared0)
    (take_image instrument9 Star0 infrared3)
    (take_image instrument9 Star0 spectrograph1)
    (take_image instrument9 Star1 image2)
    (take_image instrument9 Star1 image4)
    (take_image instrument9 Star1 infrared0)
    (take_image instrument9 Star1 infrared3)
    (take_image instrument9 Star1 spectrograph1)
    (take_image instrument9 Star11 image2)
    (take_image instrument9 Star11 image4)
    (take_image instrument9 Star11 infrared0)
    (take_image instrument9 Star11 infrared3)
    (take_image instrument9 Star11 spectrograph1)
    (take_image instrument9 Star12 image2)
    (take_image instrument9 Star12 image4)
    (take_image instrument9 Star12 infrared0)
    (take_image instrument9 Star12 infrared3)
    (take_image instrument9 Star12 spectrograph1)
    (take_image instrument9 Star15 image2)
    (take_image instrument9 Star15 image4)
    (take_image instrument9 Star15 infrared0)
    (take_image instrument9 Star15 infrared3)
    (take_image instrument9 Star15 spectrograph1)
    (take_image instrument9 Star16 image2)
    (take_image instrument9 Star16 image4)
    (take_image instrument9 Star16 infrared0)
    (take_image instrument9 Star16 infrared3)
    (take_image instrument9 Star16 spectrograph1)
    (take_image instrument9 Star2 image2)
    (take_image instrument9 Star2 image4)
    (take_image instrument9 Star2 infrared0)
    (take_image instrument9 Star2 infrared3)
    (take_image instrument9 Star2 spectrograph1)
    (take_image instrument9 Star4 image2)
    (take_image instrument9 Star4 image4)
    (take_image instrument9 Star4 infrared0)
    (take_image instrument9 Star4 infrared3)
    (take_image instrument9 Star4 spectrograph1)
    (take_image instrument9 Star6 image2)
    (take_image instrument9 Star6 image4)
    (take_image instrument9 Star6 infrared0)
    (take_image instrument9 Star6 infrared3)
    (take_image instrument9 Star6 spectrograph1)
    (take_image instrument9 Star7 image2)
    (take_image instrument9 Star7 image4)
    (take_image instrument9 Star7 infrared0)
    (take_image instrument9 Star7 infrared3)
    (take_image instrument9 Star7 spectrograph1)
    )
(:goal (and
	(pointing satellite4 Planet9)
	(have_image Planet5 image4)
	(have_image Star6 infrared3)
	(have_image Star7 image4)
	(have_image Phenomenon8 image4)
	(have_image Planet9 infrared0)
	(have_image Planet10 infrared3)
	(have_image Star12 image4)
	(have_image Phenomenon13 image4)
	(have_image Phenomenon14 spectrograph1)
	(have_image Star15 spectrograph1)
	(have_image Star16 image2)
))

)
