; Problem taken from https://github.com/AI-Planning/classical-domains

(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0
	instrument0
	satellite1
	instrument1
	instrument2
	instrument3
	satellite2
	instrument4
	thermograph2
	spectrograph0
	infrared1
	infrared3
	GroundStation3
	Star1
	Star2
	Star0
	Planet4
	Planet5
	Star6
	Star7
	Phenomenon8
	Star9
	Star10
)
(:init
	(satellite satellite0)
	(instrument instrument0)
	(supports instrument0 infrared1)
	(supports instrument0 spectrograph0)
	(calibration_target instrument0 Star1)
	(on_board instrument0 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Phenomenon8)
	(satellite satellite1)
	(instrument instrument1)
	(supports instrument1 infrared3)
	(calibration_target instrument1 Star2)
	(instrument instrument2)
	(supports instrument2 infrared1)
	(supports instrument2 infrared3)
	(supports instrument2 thermograph2)
	(calibration_target instrument2 Star2)
	(instrument instrument3)
	(supports instrument3 infrared1)
	(supports instrument3 infrared3)
	(supports instrument3 spectrograph0)
	(calibration_target instrument3 Star2)
	(on_board instrument1 satellite1)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star6)
	(satellite satellite2)
	(instrument instrument4)
	(supports instrument4 infrared3)
	(calibration_target instrument4 Star0)
	(on_board instrument4 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star6)
	(mode thermograph2)
	(mode spectrograph0)
	(mode infrared1)
	(mode infrared3)
	(direction GroundStation3)
	(direction Star1)
	(direction Star2)
	(direction Star0)
	(direction Planet4)
	(direction Planet5)
	(direction Star6)
	(direction Star7)
	(direction Phenomenon8)
	(direction Star9)
	(direction Star10)

    ; action literals
    (turn_to satellite0 GroundStation3)
    (turn_to satellite0 Phenomenon8)
    (turn_to satellite0 Planet4)
    (turn_to satellite0 Planet5)
    (turn_to satellite0 Star0)
    (turn_to satellite0 Star1)
    (turn_to satellite0 Star10)
    (turn_to satellite0 Star2)
    (turn_to satellite0 Star6)
    (turn_to satellite0 Star7)
    (turn_to satellite0 Star9)
    (turn_to satellite1 GroundStation3)
    (turn_to satellite1 Phenomenon8)
    (turn_to satellite1 Planet4)
    (turn_to satellite1 Planet5)
    (turn_to satellite1 Star0)
    (turn_to satellite1 Star1)
    (turn_to satellite1 Star10)
    (turn_to satellite1 Star2)
    (turn_to satellite1 Star6)
    (turn_to satellite1 Star7)
    (turn_to satellite1 Star9)
    (turn_to satellite2 GroundStation3)
    (turn_to satellite2 Phenomenon8)
    (turn_to satellite2 Planet4)
    (turn_to satellite2 Planet5)
    (turn_to satellite2 Star0)
    (turn_to satellite2 Star1)
    (turn_to satellite2 Star10)
    (turn_to satellite2 Star2)
    (turn_to satellite2 Star6)
    (turn_to satellite2 Star7)
    (turn_to satellite2 Star9)
    (switch_on instrument0)
    (switch_off instrument0)
    (switch_on instrument1)
    (switch_off instrument1)
    (switch_on instrument2)
    (switch_off instrument2)
    (switch_on instrument3)
    (switch_off instrument3)
    (switch_on instrument4)
    (switch_off instrument4)
    (calibrate instrument0 GroundStation3)
    (calibrate instrument0 Phenomenon8)
    (calibrate instrument0 Planet4)
    (calibrate instrument0 Planet5)
    (calibrate instrument0 Star0)
    (calibrate instrument0 Star1)
    (calibrate instrument0 Star10)
    (calibrate instrument0 Star2)
    (calibrate instrument0 Star6)
    (calibrate instrument0 Star7)
    (calibrate instrument0 Star9)
    (calibrate instrument1 GroundStation3)
    (calibrate instrument1 Phenomenon8)
    (calibrate instrument1 Planet4)
    (calibrate instrument1 Planet5)
    (calibrate instrument1 Star0)
    (calibrate instrument1 Star1)
    (calibrate instrument1 Star10)
    (calibrate instrument1 Star2)
    (calibrate instrument1 Star6)
    (calibrate instrument1 Star7)
    (calibrate instrument1 Star9)
    (calibrate instrument2 GroundStation3)
    (calibrate instrument2 Phenomenon8)
    (calibrate instrument2 Planet4)
    (calibrate instrument2 Planet5)
    (calibrate instrument2 Star0)
    (calibrate instrument2 Star1)
    (calibrate instrument2 Star10)
    (calibrate instrument2 Star2)
    (calibrate instrument2 Star6)
    (calibrate instrument2 Star7)
    (calibrate instrument2 Star9)
    (calibrate instrument3 GroundStation3)
    (calibrate instrument3 Phenomenon8)
    (calibrate instrument3 Planet4)
    (calibrate instrument3 Planet5)
    (calibrate instrument3 Star0)
    (calibrate instrument3 Star1)
    (calibrate instrument3 Star10)
    (calibrate instrument3 Star2)
    (calibrate instrument3 Star6)
    (calibrate instrument3 Star7)
    (calibrate instrument3 Star9)
    (calibrate instrument4 GroundStation3)
    (calibrate instrument4 Phenomenon8)
    (calibrate instrument4 Planet4)
    (calibrate instrument4 Planet5)
    (calibrate instrument4 Star0)
    (calibrate instrument4 Star1)
    (calibrate instrument4 Star10)
    (calibrate instrument4 Star2)
    (calibrate instrument4 Star6)
    (calibrate instrument4 Star7)
    (calibrate instrument4 Star9)
    (take_image instrument0 GroundStation3 infrared1)
    (take_image instrument0 GroundStation3 infrared3)
    (take_image instrument0 GroundStation3 spectrograph0)
    (take_image instrument0 GroundStation3 thermograph2)
    (take_image instrument0 Phenomenon8 infrared1)
    (take_image instrument0 Phenomenon8 infrared3)
    (take_image instrument0 Phenomenon8 spectrograph0)
    (take_image instrument0 Phenomenon8 thermograph2)
    (take_image instrument0 Planet4 infrared1)
    (take_image instrument0 Planet4 infrared3)
    (take_image instrument0 Planet4 spectrograph0)
    (take_image instrument0 Planet4 thermograph2)
    (take_image instrument0 Planet5 infrared1)
    (take_image instrument0 Planet5 infrared3)
    (take_image instrument0 Planet5 spectrograph0)
    (take_image instrument0 Planet5 thermograph2)
    (take_image instrument0 Star0 infrared1)
    (take_image instrument0 Star0 infrared3)
    (take_image instrument0 Star0 spectrograph0)
    (take_image instrument0 Star0 thermograph2)
    (take_image instrument0 Star1 infrared1)
    (take_image instrument0 Star1 infrared3)
    (take_image instrument0 Star1 spectrograph0)
    (take_image instrument0 Star1 thermograph2)
    (take_image instrument0 Star10 infrared1)
    (take_image instrument0 Star10 infrared3)
    (take_image instrument0 Star10 spectrograph0)
    (take_image instrument0 Star10 thermograph2)
    (take_image instrument0 Star2 infrared1)
    (take_image instrument0 Star2 infrared3)
    (take_image instrument0 Star2 spectrograph0)
    (take_image instrument0 Star2 thermograph2)
    (take_image instrument0 Star6 infrared1)
    (take_image instrument0 Star6 infrared3)
    (take_image instrument0 Star6 spectrograph0)
    (take_image instrument0 Star6 thermograph2)
    (take_image instrument0 Star7 infrared1)
    (take_image instrument0 Star7 infrared3)
    (take_image instrument0 Star7 spectrograph0)
    (take_image instrument0 Star7 thermograph2)
    (take_image instrument0 Star9 infrared1)
    (take_image instrument0 Star9 infrared3)
    (take_image instrument0 Star9 spectrograph0)
    (take_image instrument0 Star9 thermograph2)
    (take_image instrument1 GroundStation3 infrared1)
    (take_image instrument1 GroundStation3 infrared3)
    (take_image instrument1 GroundStation3 spectrograph0)
    (take_image instrument1 GroundStation3 thermograph2)
    (take_image instrument1 Phenomenon8 infrared1)
    (take_image instrument1 Phenomenon8 infrared3)
    (take_image instrument1 Phenomenon8 spectrograph0)
    (take_image instrument1 Phenomenon8 thermograph2)
    (take_image instrument1 Planet4 infrared1)
    (take_image instrument1 Planet4 infrared3)
    (take_image instrument1 Planet4 spectrograph0)
    (take_image instrument1 Planet4 thermograph2)
    (take_image instrument1 Planet5 infrared1)
    (take_image instrument1 Planet5 infrared3)
    (take_image instrument1 Planet5 spectrograph0)
    (take_image instrument1 Planet5 thermograph2)
    (take_image instrument1 Star0 infrared1)
    (take_image instrument1 Star0 infrared3)
    (take_image instrument1 Star0 spectrograph0)
    (take_image instrument1 Star0 thermograph2)
    (take_image instrument1 Star1 infrared1)
    (take_image instrument1 Star1 infrared3)
    (take_image instrument1 Star1 spectrograph0)
    (take_image instrument1 Star1 thermograph2)
    (take_image instrument1 Star10 infrared1)
    (take_image instrument1 Star10 infrared3)
    (take_image instrument1 Star10 spectrograph0)
    (take_image instrument1 Star10 thermograph2)
    (take_image instrument1 Star2 infrared1)
    (take_image instrument1 Star2 infrared3)
    (take_image instrument1 Star2 spectrograph0)
    (take_image instrument1 Star2 thermograph2)
    (take_image instrument1 Star6 infrared1)
    (take_image instrument1 Star6 infrared3)
    (take_image instrument1 Star6 spectrograph0)
    (take_image instrument1 Star6 thermograph2)
    (take_image instrument1 Star7 infrared1)
    (take_image instrument1 Star7 infrared3)
    (take_image instrument1 Star7 spectrograph0)
    (take_image instrument1 Star7 thermograph2)
    (take_image instrument1 Star9 infrared1)
    (take_image instrument1 Star9 infrared3)
    (take_image instrument1 Star9 spectrograph0)
    (take_image instrument1 Star9 thermograph2)
    (take_image instrument2 GroundStation3 infrared1)
    (take_image instrument2 GroundStation3 infrared3)
    (take_image instrument2 GroundStation3 spectrograph0)
    (take_image instrument2 GroundStation3 thermograph2)
    (take_image instrument2 Phenomenon8 infrared1)
    (take_image instrument2 Phenomenon8 infrared3)
    (take_image instrument2 Phenomenon8 spectrograph0)
    (take_image instrument2 Phenomenon8 thermograph2)
    (take_image instrument2 Planet4 infrared1)
    (take_image instrument2 Planet4 infrared3)
    (take_image instrument2 Planet4 spectrograph0)
    (take_image instrument2 Planet4 thermograph2)
    (take_image instrument2 Planet5 infrared1)
    (take_image instrument2 Planet5 infrared3)
    (take_image instrument2 Planet5 spectrograph0)
    (take_image instrument2 Planet5 thermograph2)
    (take_image instrument2 Star0 infrared1)
    (take_image instrument2 Star0 infrared3)
    (take_image instrument2 Star0 spectrograph0)
    (take_image instrument2 Star0 thermograph2)
    (take_image instrument2 Star1 infrared1)
    (take_image instrument2 Star1 infrared3)
    (take_image instrument2 Star1 spectrograph0)
    (take_image instrument2 Star1 thermograph2)
    (take_image instrument2 Star10 infrared1)
    (take_image instrument2 Star10 infrared3)
    (take_image instrument2 Star10 spectrograph0)
    (take_image instrument2 Star10 thermograph2)
    (take_image instrument2 Star2 infrared1)
    (take_image instrument2 Star2 infrared3)
    (take_image instrument2 Star2 spectrograph0)
    (take_image instrument2 Star2 thermograph2)
    (take_image instrument2 Star6 infrared1)
    (take_image instrument2 Star6 infrared3)
    (take_image instrument2 Star6 spectrograph0)
    (take_image instrument2 Star6 thermograph2)
    (take_image instrument2 Star7 infrared1)
    (take_image instrument2 Star7 infrared3)
    (take_image instrument2 Star7 spectrograph0)
    (take_image instrument2 Star7 thermograph2)
    (take_image instrument2 Star9 infrared1)
    (take_image instrument2 Star9 infrared3)
    (take_image instrument2 Star9 spectrograph0)
    (take_image instrument2 Star9 thermograph2)
    (take_image instrument3 GroundStation3 infrared1)
    (take_image instrument3 GroundStation3 infrared3)
    (take_image instrument3 GroundStation3 spectrograph0)
    (take_image instrument3 GroundStation3 thermograph2)
    (take_image instrument3 Phenomenon8 infrared1)
    (take_image instrument3 Phenomenon8 infrared3)
    (take_image instrument3 Phenomenon8 spectrograph0)
    (take_image instrument3 Phenomenon8 thermograph2)
    (take_image instrument3 Planet4 infrared1)
    (take_image instrument3 Planet4 infrared3)
    (take_image instrument3 Planet4 spectrograph0)
    (take_image instrument3 Planet4 thermograph2)
    (take_image instrument3 Planet5 infrared1)
    (take_image instrument3 Planet5 infrared3)
    (take_image instrument3 Planet5 spectrograph0)
    (take_image instrument3 Planet5 thermograph2)
    (take_image instrument3 Star0 infrared1)
    (take_image instrument3 Star0 infrared3)
    (take_image instrument3 Star0 spectrograph0)
    (take_image instrument3 Star0 thermograph2)
    (take_image instrument3 Star1 infrared1)
    (take_image instrument3 Star1 infrared3)
    (take_image instrument3 Star1 spectrograph0)
    (take_image instrument3 Star1 thermograph2)
    (take_image instrument3 Star10 infrared1)
    (take_image instrument3 Star10 infrared3)
    (take_image instrument3 Star10 spectrograph0)
    (take_image instrument3 Star10 thermograph2)
    (take_image instrument3 Star2 infrared1)
    (take_image instrument3 Star2 infrared3)
    (take_image instrument3 Star2 spectrograph0)
    (take_image instrument3 Star2 thermograph2)
    (take_image instrument3 Star6 infrared1)
    (take_image instrument3 Star6 infrared3)
    (take_image instrument3 Star6 spectrograph0)
    (take_image instrument3 Star6 thermograph2)
    (take_image instrument3 Star7 infrared1)
    (take_image instrument3 Star7 infrared3)
    (take_image instrument3 Star7 spectrograph0)
    (take_image instrument3 Star7 thermograph2)
    (take_image instrument3 Star9 infrared1)
    (take_image instrument3 Star9 infrared3)
    (take_image instrument3 Star9 spectrograph0)
    (take_image instrument3 Star9 thermograph2)
    (take_image instrument4 GroundStation3 infrared1)
    (take_image instrument4 GroundStation3 infrared3)
    (take_image instrument4 GroundStation3 spectrograph0)
    (take_image instrument4 GroundStation3 thermograph2)
    (take_image instrument4 Phenomenon8 infrared1)
    (take_image instrument4 Phenomenon8 infrared3)
    (take_image instrument4 Phenomenon8 spectrograph0)
    (take_image instrument4 Phenomenon8 thermograph2)
    (take_image instrument4 Planet4 infrared1)
    (take_image instrument4 Planet4 infrared3)
    (take_image instrument4 Planet4 spectrograph0)
    (take_image instrument4 Planet4 thermograph2)
    (take_image instrument4 Planet5 infrared1)
    (take_image instrument4 Planet5 infrared3)
    (take_image instrument4 Planet5 spectrograph0)
    (take_image instrument4 Planet5 thermograph2)
    (take_image instrument4 Star0 infrared1)
    (take_image instrument4 Star0 infrared3)
    (take_image instrument4 Star0 spectrograph0)
    (take_image instrument4 Star0 thermograph2)
    (take_image instrument4 Star1 infrared1)
    (take_image instrument4 Star1 infrared3)
    (take_image instrument4 Star1 spectrograph0)
    (take_image instrument4 Star1 thermograph2)
    (take_image instrument4 Star10 infrared1)
    (take_image instrument4 Star10 infrared3)
    (take_image instrument4 Star10 spectrograph0)
    (take_image instrument4 Star10 thermograph2)
    (take_image instrument4 Star2 infrared1)
    (take_image instrument4 Star2 infrared3)
    (take_image instrument4 Star2 spectrograph0)
    (take_image instrument4 Star2 thermograph2)
    (take_image instrument4 Star6 infrared1)
    (take_image instrument4 Star6 infrared3)
    (take_image instrument4 Star6 spectrograph0)
    (take_image instrument4 Star6 thermograph2)
    (take_image instrument4 Star7 infrared1)
    (take_image instrument4 Star7 infrared3)
    (take_image instrument4 Star7 spectrograph0)
    (take_image instrument4 Star7 thermograph2)
    (take_image instrument4 Star9 infrared1)
    (take_image instrument4 Star9 infrared3)
    (take_image instrument4 Star9 spectrograph0)
    (take_image instrument4 Star9 thermograph2)
    )
(:goal (and
	(have_image Planet4 thermograph2)
	(have_image Planet5 spectrograph0)
	(have_image Star6 thermograph2)
	(have_image Star7 infrared3)
	(have_image Phenomenon8 spectrograph0)
	(have_image Star9 infrared1)
	(have_image Star10 infrared3)
))

)
