; Problem taken from https://github.com/AI-Planning/classical-domains

(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0
	instrument0
	instrument1
	satellite1
	instrument2
	satellite2
	instrument3
	instrument4
	satellite3
	instrument5
	satellite4
	instrument6
	instrument7
	instrument8
	image4
	thermograph1
	thermograph0
	thermograph2
	image3
	GroundStation2
	Star1
	Star4
	Star0
	GroundStation3
	Phenomenon5
	Planet6
	Planet7
	Planet8
	Planet9
	Planet10
	Planet11
	Phenomenon12
	Planet13
	Star14
	Planet15
	Planet16
	Planet17
	Phenomenon18
	Star19
	Planet20
	Star21
	Star22
	Planet23
	Planet24
	Planet25
	Star26
	Phenomenon27
	Planet28
	Planet29
)
(:init
	(satellite satellite0)
	(instrument instrument0)
	(supports instrument0 image4)
	(calibration_target instrument0 GroundStation3)
	(instrument instrument1)
	(supports instrument1 thermograph1)
	(supports instrument1 image4)
	(calibration_target instrument1 GroundStation3)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star19)
	(satellite satellite1)
	(instrument instrument2)
	(supports instrument2 thermograph0)
	(supports instrument2 image4)
	(supports instrument2 thermograph2)
	(calibration_target instrument2 GroundStation3)
	(on_board instrument2 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Planet17)
	(satellite satellite2)
	(instrument instrument3)
	(supports instrument3 image4)
	(supports instrument3 image3)
	(calibration_target instrument3 Star1)
	(instrument instrument4)
	(supports instrument4 image3)
	(calibration_target instrument4 GroundStation3)
	(on_board instrument3 satellite2)
	(on_board instrument4 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Planet7)
	(satellite satellite3)
	(instrument instrument5)
	(supports instrument5 thermograph1)
	(supports instrument5 image4)
	(calibration_target instrument5 GroundStation3)
	(on_board instrument5 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star4)
	(satellite satellite4)
	(instrument instrument6)
	(supports instrument6 image3)
	(supports instrument6 thermograph1)
	(supports instrument6 thermograph0)
	(calibration_target instrument6 Star4)
	(instrument instrument7)
	(supports instrument7 thermograph2)
	(supports instrument7 thermograph0)
	(calibration_target instrument7 Star0)
	(instrument instrument8)
	(supports instrument8 image3)
	(supports instrument8 thermograph2)
	(calibration_target instrument8 GroundStation3)
	(on_board instrument6 satellite4)
	(on_board instrument7 satellite4)
	(on_board instrument8 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Phenomenon5)
	(mode image4)
	(mode thermograph1)
	(mode thermograph0)
	(mode thermograph2)
	(mode image3)
	(direction GroundStation2)
	(direction Star1)
	(direction Star4)
	(direction Star0)
	(direction GroundStation3)
	(direction Phenomenon5)
	(direction Planet6)
	(direction Planet7)
	(direction Planet8)
	(direction Planet9)
	(direction Planet10)
	(direction Planet11)
	(direction Phenomenon12)
	(direction Planet13)
	(direction Star14)
	(direction Planet15)
	(direction Planet16)
	(direction Planet17)
	(direction Phenomenon18)
	(direction Star19)
	(direction Planet20)
	(direction Star21)
	(direction Star22)
	(direction Planet23)
	(direction Planet24)
	(direction Planet25)
	(direction Star26)
	(direction Phenomenon27)
	(direction Planet28)
	(direction Planet29)

    ; action literals
    (turn_to satellite0 GroundStation2)
    (turn_to satellite0 GroundStation3)
    (turn_to satellite0 Phenomenon12)
    (turn_to satellite0 Phenomenon18)
    (turn_to satellite0 Phenomenon27)
    (turn_to satellite0 Phenomenon5)
    (turn_to satellite0 Planet10)
    (turn_to satellite0 Planet11)
    (turn_to satellite0 Planet13)
    (turn_to satellite0 Planet15)
    (turn_to satellite0 Planet16)
    (turn_to satellite0 Planet17)
    (turn_to satellite0 Planet20)
    (turn_to satellite0 Planet23)
    (turn_to satellite0 Planet24)
    (turn_to satellite0 Planet25)
    (turn_to satellite0 Planet28)
    (turn_to satellite0 Planet29)
    (turn_to satellite0 Planet6)
    (turn_to satellite0 Planet7)
    (turn_to satellite0 Planet8)
    (turn_to satellite0 Planet9)
    (turn_to satellite0 Star0)
    (turn_to satellite0 Star1)
    (turn_to satellite0 Star14)
    (turn_to satellite0 Star19)
    (turn_to satellite0 Star21)
    (turn_to satellite0 Star22)
    (turn_to satellite0 Star26)
    (turn_to satellite0 Star4)
    (turn_to satellite1 GroundStation2)
    (turn_to satellite1 GroundStation3)
    (turn_to satellite1 Phenomenon12)
    (turn_to satellite1 Phenomenon18)
    (turn_to satellite1 Phenomenon27)
    (turn_to satellite1 Phenomenon5)
    (turn_to satellite1 Planet10)
    (turn_to satellite1 Planet11)
    (turn_to satellite1 Planet13)
    (turn_to satellite1 Planet15)
    (turn_to satellite1 Planet16)
    (turn_to satellite1 Planet17)
    (turn_to satellite1 Planet20)
    (turn_to satellite1 Planet23)
    (turn_to satellite1 Planet24)
    (turn_to satellite1 Planet25)
    (turn_to satellite1 Planet28)
    (turn_to satellite1 Planet29)
    (turn_to satellite1 Planet6)
    (turn_to satellite1 Planet7)
    (turn_to satellite1 Planet8)
    (turn_to satellite1 Planet9)
    (turn_to satellite1 Star0)
    (turn_to satellite1 Star1)
    (turn_to satellite1 Star14)
    (turn_to satellite1 Star19)
    (turn_to satellite1 Star21)
    (turn_to satellite1 Star22)
    (turn_to satellite1 Star26)
    (turn_to satellite1 Star4)
    (turn_to satellite2 GroundStation2)
    (turn_to satellite2 GroundStation3)
    (turn_to satellite2 Phenomenon12)
    (turn_to satellite2 Phenomenon18)
    (turn_to satellite2 Phenomenon27)
    (turn_to satellite2 Phenomenon5)
    (turn_to satellite2 Planet10)
    (turn_to satellite2 Planet11)
    (turn_to satellite2 Planet13)
    (turn_to satellite2 Planet15)
    (turn_to satellite2 Planet16)
    (turn_to satellite2 Planet17)
    (turn_to satellite2 Planet20)
    (turn_to satellite2 Planet23)
    (turn_to satellite2 Planet24)
    (turn_to satellite2 Planet25)
    (turn_to satellite2 Planet28)
    (turn_to satellite2 Planet29)
    (turn_to satellite2 Planet6)
    (turn_to satellite2 Planet7)
    (turn_to satellite2 Planet8)
    (turn_to satellite2 Planet9)
    (turn_to satellite2 Star0)
    (turn_to satellite2 Star1)
    (turn_to satellite2 Star14)
    (turn_to satellite2 Star19)
    (turn_to satellite2 Star21)
    (turn_to satellite2 Star22)
    (turn_to satellite2 Star26)
    (turn_to satellite2 Star4)
    (turn_to satellite3 GroundStation2)
    (turn_to satellite3 GroundStation3)
    (turn_to satellite3 Phenomenon12)
    (turn_to satellite3 Phenomenon18)
    (turn_to satellite3 Phenomenon27)
    (turn_to satellite3 Phenomenon5)
    (turn_to satellite3 Planet10)
    (turn_to satellite3 Planet11)
    (turn_to satellite3 Planet13)
    (turn_to satellite3 Planet15)
    (turn_to satellite3 Planet16)
    (turn_to satellite3 Planet17)
    (turn_to satellite3 Planet20)
    (turn_to satellite3 Planet23)
    (turn_to satellite3 Planet24)
    (turn_to satellite3 Planet25)
    (turn_to satellite3 Planet28)
    (turn_to satellite3 Planet29)
    (turn_to satellite3 Planet6)
    (turn_to satellite3 Planet7)
    (turn_to satellite3 Planet8)
    (turn_to satellite3 Planet9)
    (turn_to satellite3 Star0)
    (turn_to satellite3 Star1)
    (turn_to satellite3 Star14)
    (turn_to satellite3 Star19)
    (turn_to satellite3 Star21)
    (turn_to satellite3 Star22)
    (turn_to satellite3 Star26)
    (turn_to satellite3 Star4)
    (turn_to satellite4 GroundStation2)
    (turn_to satellite4 GroundStation3)
    (turn_to satellite4 Phenomenon12)
    (turn_to satellite4 Phenomenon18)
    (turn_to satellite4 Phenomenon27)
    (turn_to satellite4 Phenomenon5)
    (turn_to satellite4 Planet10)
    (turn_to satellite4 Planet11)
    (turn_to satellite4 Planet13)
    (turn_to satellite4 Planet15)
    (turn_to satellite4 Planet16)
    (turn_to satellite4 Planet17)
    (turn_to satellite4 Planet20)
    (turn_to satellite4 Planet23)
    (turn_to satellite4 Planet24)
    (turn_to satellite4 Planet25)
    (turn_to satellite4 Planet28)
    (turn_to satellite4 Planet29)
    (turn_to satellite4 Planet6)
    (turn_to satellite4 Planet7)
    (turn_to satellite4 Planet8)
    (turn_to satellite4 Planet9)
    (turn_to satellite4 Star0)
    (turn_to satellite4 Star1)
    (turn_to satellite4 Star14)
    (turn_to satellite4 Star19)
    (turn_to satellite4 Star21)
    (turn_to satellite4 Star22)
    (turn_to satellite4 Star26)
    (turn_to satellite4 Star4)
    (switch_on instrument0)
    (switch_off instrument0)
    (switch_on instrument1)
    (switch_off instrument1)
    (switch_on instrument2)
    (switch_off instrument2)
    (switch_on instrument3)
    (switch_off instrument3)
    (switch_on instrument4)
    (switch_off instrument4)
    (switch_on instrument5)
    (switch_off instrument5)
    (switch_on instrument6)
    (switch_off instrument6)
    (switch_on instrument7)
    (switch_off instrument7)
    (switch_on instrument8)
    (switch_off instrument8)
    (calibrate instrument0 GroundStation2)
    (calibrate instrument0 GroundStation3)
    (calibrate instrument0 Phenomenon12)
    (calibrate instrument0 Phenomenon18)
    (calibrate instrument0 Phenomenon27)
    (calibrate instrument0 Phenomenon5)
    (calibrate instrument0 Planet10)
    (calibrate instrument0 Planet11)
    (calibrate instrument0 Planet13)
    (calibrate instrument0 Planet15)
    (calibrate instrument0 Planet16)
    (calibrate instrument0 Planet17)
    (calibrate instrument0 Planet20)
    (calibrate instrument0 Planet23)
    (calibrate instrument0 Planet24)
    (calibrate instrument0 Planet25)
    (calibrate instrument0 Planet28)
    (calibrate instrument0 Planet29)
    (calibrate instrument0 Planet6)
    (calibrate instrument0 Planet7)
    (calibrate instrument0 Planet8)
    (calibrate instrument0 Planet9)
    (calibrate instrument0 Star0)
    (calibrate instrument0 Star1)
    (calibrate instrument0 Star14)
    (calibrate instrument0 Star19)
    (calibrate instrument0 Star21)
    (calibrate instrument0 Star22)
    (calibrate instrument0 Star26)
    (calibrate instrument0 Star4)
    (calibrate instrument1 GroundStation2)
    (calibrate instrument1 GroundStation3)
    (calibrate instrument1 Phenomenon12)
    (calibrate instrument1 Phenomenon18)
    (calibrate instrument1 Phenomenon27)
    (calibrate instrument1 Phenomenon5)
    (calibrate instrument1 Planet10)
    (calibrate instrument1 Planet11)
    (calibrate instrument1 Planet13)
    (calibrate instrument1 Planet15)
    (calibrate instrument1 Planet16)
    (calibrate instrument1 Planet17)
    (calibrate instrument1 Planet20)
    (calibrate instrument1 Planet23)
    (calibrate instrument1 Planet24)
    (calibrate instrument1 Planet25)
    (calibrate instrument1 Planet28)
    (calibrate instrument1 Planet29)
    (calibrate instrument1 Planet6)
    (calibrate instrument1 Planet7)
    (calibrate instrument1 Planet8)
    (calibrate instrument1 Planet9)
    (calibrate instrument1 Star0)
    (calibrate instrument1 Star1)
    (calibrate instrument1 Star14)
    (calibrate instrument1 Star19)
    (calibrate instrument1 Star21)
    (calibrate instrument1 Star22)
    (calibrate instrument1 Star26)
    (calibrate instrument1 Star4)
    (calibrate instrument2 GroundStation2)
    (calibrate instrument2 GroundStation3)
    (calibrate instrument2 Phenomenon12)
    (calibrate instrument2 Phenomenon18)
    (calibrate instrument2 Phenomenon27)
    (calibrate instrument2 Phenomenon5)
    (calibrate instrument2 Planet10)
    (calibrate instrument2 Planet11)
    (calibrate instrument2 Planet13)
    (calibrate instrument2 Planet15)
    (calibrate instrument2 Planet16)
    (calibrate instrument2 Planet17)
    (calibrate instrument2 Planet20)
    (calibrate instrument2 Planet23)
    (calibrate instrument2 Planet24)
    (calibrate instrument2 Planet25)
    (calibrate instrument2 Planet28)
    (calibrate instrument2 Planet29)
    (calibrate instrument2 Planet6)
    (calibrate instrument2 Planet7)
    (calibrate instrument2 Planet8)
    (calibrate instrument2 Planet9)
    (calibrate instrument2 Star0)
    (calibrate instrument2 Star1)
    (calibrate instrument2 Star14)
    (calibrate instrument2 Star19)
    (calibrate instrument2 Star21)
    (calibrate instrument2 Star22)
    (calibrate instrument2 Star26)
    (calibrate instrument2 Star4)
    (calibrate instrument3 GroundStation2)
    (calibrate instrument3 GroundStation3)
    (calibrate instrument3 Phenomenon12)
    (calibrate instrument3 Phenomenon18)
    (calibrate instrument3 Phenomenon27)
    (calibrate instrument3 Phenomenon5)
    (calibrate instrument3 Planet10)
    (calibrate instrument3 Planet11)
    (calibrate instrument3 Planet13)
    (calibrate instrument3 Planet15)
    (calibrate instrument3 Planet16)
    (calibrate instrument3 Planet17)
    (calibrate instrument3 Planet20)
    (calibrate instrument3 Planet23)
    (calibrate instrument3 Planet24)
    (calibrate instrument3 Planet25)
    (calibrate instrument3 Planet28)
    (calibrate instrument3 Planet29)
    (calibrate instrument3 Planet6)
    (calibrate instrument3 Planet7)
    (calibrate instrument3 Planet8)
    (calibrate instrument3 Planet9)
    (calibrate instrument3 Star0)
    (calibrate instrument3 Star1)
    (calibrate instrument3 Star14)
    (calibrate instrument3 Star19)
    (calibrate instrument3 Star21)
    (calibrate instrument3 Star22)
    (calibrate instrument3 Star26)
    (calibrate instrument3 Star4)
    (calibrate instrument4 GroundStation2)
    (calibrate instrument4 GroundStation3)
    (calibrate instrument4 Phenomenon12)
    (calibrate instrument4 Phenomenon18)
    (calibrate instrument4 Phenomenon27)
    (calibrate instrument4 Phenomenon5)
    (calibrate instrument4 Planet10)
    (calibrate instrument4 Planet11)
    (calibrate instrument4 Planet13)
    (calibrate instrument4 Planet15)
    (calibrate instrument4 Planet16)
    (calibrate instrument4 Planet17)
    (calibrate instrument4 Planet20)
    (calibrate instrument4 Planet23)
    (calibrate instrument4 Planet24)
    (calibrate instrument4 Planet25)
    (calibrate instrument4 Planet28)
    (calibrate instrument4 Planet29)
    (calibrate instrument4 Planet6)
    (calibrate instrument4 Planet7)
    (calibrate instrument4 Planet8)
    (calibrate instrument4 Planet9)
    (calibrate instrument4 Star0)
    (calibrate instrument4 Star1)
    (calibrate instrument4 Star14)
    (calibrate instrument4 Star19)
    (calibrate instrument4 Star21)
    (calibrate instrument4 Star22)
    (calibrate instrument4 Star26)
    (calibrate instrument4 Star4)
    (calibrate instrument5 GroundStation2)
    (calibrate instrument5 GroundStation3)
    (calibrate instrument5 Phenomenon12)
    (calibrate instrument5 Phenomenon18)
    (calibrate instrument5 Phenomenon27)
    (calibrate instrument5 Phenomenon5)
    (calibrate instrument5 Planet10)
    (calibrate instrument5 Planet11)
    (calibrate instrument5 Planet13)
    (calibrate instrument5 Planet15)
    (calibrate instrument5 Planet16)
    (calibrate instrument5 Planet17)
    (calibrate instrument5 Planet20)
    (calibrate instrument5 Planet23)
    (calibrate instrument5 Planet24)
    (calibrate instrument5 Planet25)
    (calibrate instrument5 Planet28)
    (calibrate instrument5 Planet29)
    (calibrate instrument5 Planet6)
    (calibrate instrument5 Planet7)
    (calibrate instrument5 Planet8)
    (calibrate instrument5 Planet9)
    (calibrate instrument5 Star0)
    (calibrate instrument5 Star1)
    (calibrate instrument5 Star14)
    (calibrate instrument5 Star19)
    (calibrate instrument5 Star21)
    (calibrate instrument5 Star22)
    (calibrate instrument5 Star26)
    (calibrate instrument5 Star4)
    (calibrate instrument6 GroundStation2)
    (calibrate instrument6 GroundStation3)
    (calibrate instrument6 Phenomenon12)
    (calibrate instrument6 Phenomenon18)
    (calibrate instrument6 Phenomenon27)
    (calibrate instrument6 Phenomenon5)
    (calibrate instrument6 Planet10)
    (calibrate instrument6 Planet11)
    (calibrate instrument6 Planet13)
    (calibrate instrument6 Planet15)
    (calibrate instrument6 Planet16)
    (calibrate instrument6 Planet17)
    (calibrate instrument6 Planet20)
    (calibrate instrument6 Planet23)
    (calibrate instrument6 Planet24)
    (calibrate instrument6 Planet25)
    (calibrate instrument6 Planet28)
    (calibrate instrument6 Planet29)
    (calibrate instrument6 Planet6)
    (calibrate instrument6 Planet7)
    (calibrate instrument6 Planet8)
    (calibrate instrument6 Planet9)
    (calibrate instrument6 Star0)
    (calibrate instrument6 Star1)
    (calibrate instrument6 Star14)
    (calibrate instrument6 Star19)
    (calibrate instrument6 Star21)
    (calibrate instrument6 Star22)
    (calibrate instrument6 Star26)
    (calibrate instrument6 Star4)
    (calibrate instrument7 GroundStation2)
    (calibrate instrument7 GroundStation3)
    (calibrate instrument7 Phenomenon12)
    (calibrate instrument7 Phenomenon18)
    (calibrate instrument7 Phenomenon27)
    (calibrate instrument7 Phenomenon5)
    (calibrate instrument7 Planet10)
    (calibrate instrument7 Planet11)
    (calibrate instrument7 Planet13)
    (calibrate instrument7 Planet15)
    (calibrate instrument7 Planet16)
    (calibrate instrument7 Planet17)
    (calibrate instrument7 Planet20)
    (calibrate instrument7 Planet23)
    (calibrate instrument7 Planet24)
    (calibrate instrument7 Planet25)
    (calibrate instrument7 Planet28)
    (calibrate instrument7 Planet29)
    (calibrate instrument7 Planet6)
    (calibrate instrument7 Planet7)
    (calibrate instrument7 Planet8)
    (calibrate instrument7 Planet9)
    (calibrate instrument7 Star0)
    (calibrate instrument7 Star1)
    (calibrate instrument7 Star14)
    (calibrate instrument7 Star19)
    (calibrate instrument7 Star21)
    (calibrate instrument7 Star22)
    (calibrate instrument7 Star26)
    (calibrate instrument7 Star4)
    (calibrate instrument8 GroundStation2)
    (calibrate instrument8 GroundStation3)
    (calibrate instrument8 Phenomenon12)
    (calibrate instrument8 Phenomenon18)
    (calibrate instrument8 Phenomenon27)
    (calibrate instrument8 Phenomenon5)
    (calibrate instrument8 Planet10)
    (calibrate instrument8 Planet11)
    (calibrate instrument8 Planet13)
    (calibrate instrument8 Planet15)
    (calibrate instrument8 Planet16)
    (calibrate instrument8 Planet17)
    (calibrate instrument8 Planet20)
    (calibrate instrument8 Planet23)
    (calibrate instrument8 Planet24)
    (calibrate instrument8 Planet25)
    (calibrate instrument8 Planet28)
    (calibrate instrument8 Planet29)
    (calibrate instrument8 Planet6)
    (calibrate instrument8 Planet7)
    (calibrate instrument8 Planet8)
    (calibrate instrument8 Planet9)
    (calibrate instrument8 Star0)
    (calibrate instrument8 Star1)
    (calibrate instrument8 Star14)
    (calibrate instrument8 Star19)
    (calibrate instrument8 Star21)
    (calibrate instrument8 Star22)
    (calibrate instrument8 Star26)
    (calibrate instrument8 Star4)
    (take_image instrument0 GroundStation2 image3)
    (take_image instrument0 GroundStation2 image4)
    (take_image instrument0 GroundStation2 thermograph0)
    (take_image instrument0 GroundStation2 thermograph1)
    (take_image instrument0 GroundStation2 thermograph2)
    (take_image instrument0 GroundStation3 image3)
    (take_image instrument0 GroundStation3 image4)
    (take_image instrument0 GroundStation3 thermograph0)
    (take_image instrument0 GroundStation3 thermograph1)
    (take_image instrument0 GroundStation3 thermograph2)
    (take_image instrument0 Phenomenon12 image3)
    (take_image instrument0 Phenomenon12 image4)
    (take_image instrument0 Phenomenon12 thermograph0)
    (take_image instrument0 Phenomenon12 thermograph1)
    (take_image instrument0 Phenomenon12 thermograph2)
    (take_image instrument0 Phenomenon18 image3)
    (take_image instrument0 Phenomenon18 image4)
    (take_image instrument0 Phenomenon18 thermograph0)
    (take_image instrument0 Phenomenon18 thermograph1)
    (take_image instrument0 Phenomenon18 thermograph2)
    (take_image instrument0 Phenomenon27 image3)
    (take_image instrument0 Phenomenon27 image4)
    (take_image instrument0 Phenomenon27 thermograph0)
    (take_image instrument0 Phenomenon27 thermograph1)
    (take_image instrument0 Phenomenon27 thermograph2)
    (take_image instrument0 Phenomenon5 image3)
    (take_image instrument0 Phenomenon5 image4)
    (take_image instrument0 Phenomenon5 thermograph0)
    (take_image instrument0 Phenomenon5 thermograph1)
    (take_image instrument0 Phenomenon5 thermograph2)
    (take_image instrument0 Planet10 image3)
    (take_image instrument0 Planet10 image4)
    (take_image instrument0 Planet10 thermograph0)
    (take_image instrument0 Planet10 thermograph1)
    (take_image instrument0 Planet10 thermograph2)
    (take_image instrument0 Planet11 image3)
    (take_image instrument0 Planet11 image4)
    (take_image instrument0 Planet11 thermograph0)
    (take_image instrument0 Planet11 thermograph1)
    (take_image instrument0 Planet11 thermograph2)
    (take_image instrument0 Planet13 image3)
    (take_image instrument0 Planet13 image4)
    (take_image instrument0 Planet13 thermograph0)
    (take_image instrument0 Planet13 thermograph1)
    (take_image instrument0 Planet13 thermograph2)
    (take_image instrument0 Planet15 image3)
    (take_image instrument0 Planet15 image4)
    (take_image instrument0 Planet15 thermograph0)
    (take_image instrument0 Planet15 thermograph1)
    (take_image instrument0 Planet15 thermograph2)
    (take_image instrument0 Planet16 image3)
    (take_image instrument0 Planet16 image4)
    (take_image instrument0 Planet16 thermograph0)
    (take_image instrument0 Planet16 thermograph1)
    (take_image instrument0 Planet16 thermograph2)
    (take_image instrument0 Planet17 image3)
    (take_image instrument0 Planet17 image4)
    (take_image instrument0 Planet17 thermograph0)
    (take_image instrument0 Planet17 thermograph1)
    (take_image instrument0 Planet17 thermograph2)
    (take_image instrument0 Planet20 image3)
    (take_image instrument0 Planet20 image4)
    (take_image instrument0 Planet20 thermograph0)
    (take_image instrument0 Planet20 thermograph1)
    (take_image instrument0 Planet20 thermograph2)
    (take_image instrument0 Planet23 image3)
    (take_image instrument0 Planet23 image4)
    (take_image instrument0 Planet23 thermograph0)
    (take_image instrument0 Planet23 thermograph1)
    (take_image instrument0 Planet23 thermograph2)
    (take_image instrument0 Planet24 image3)
    (take_image instrument0 Planet24 image4)
    (take_image instrument0 Planet24 thermograph0)
    (take_image instrument0 Planet24 thermograph1)
    (take_image instrument0 Planet24 thermograph2)
    (take_image instrument0 Planet25 image3)
    (take_image instrument0 Planet25 image4)
    (take_image instrument0 Planet25 thermograph0)
    (take_image instrument0 Planet25 thermograph1)
    (take_image instrument0 Planet25 thermograph2)
    (take_image instrument0 Planet28 image3)
    (take_image instrument0 Planet28 image4)
    (take_image instrument0 Planet28 thermograph0)
    (take_image instrument0 Planet28 thermograph1)
    (take_image instrument0 Planet28 thermograph2)
    (take_image instrument0 Planet29 image3)
    (take_image instrument0 Planet29 image4)
    (take_image instrument0 Planet29 thermograph0)
    (take_image instrument0 Planet29 thermograph1)
    (take_image instrument0 Planet29 thermograph2)
    (take_image instrument0 Planet6 image3)
    (take_image instrument0 Planet6 image4)
    (take_image instrument0 Planet6 thermograph0)
    (take_image instrument0 Planet6 thermograph1)
    (take_image instrument0 Planet6 thermograph2)
    (take_image instrument0 Planet7 image3)
    (take_image instrument0 Planet7 image4)
    (take_image instrument0 Planet7 thermograph0)
    (take_image instrument0 Planet7 thermograph1)
    (take_image instrument0 Planet7 thermograph2)
    (take_image instrument0 Planet8 image3)
    (take_image instrument0 Planet8 image4)
    (take_image instrument0 Planet8 thermograph0)
    (take_image instrument0 Planet8 thermograph1)
    (take_image instrument0 Planet8 thermograph2)
    (take_image instrument0 Planet9 image3)
    (take_image instrument0 Planet9 image4)
    (take_image instrument0 Planet9 thermograph0)
    (take_image instrument0 Planet9 thermograph1)
    (take_image instrument0 Planet9 thermograph2)
    (take_image instrument0 Star0 image3)
    (take_image instrument0 Star0 image4)
    (take_image instrument0 Star0 thermograph0)
    (take_image instrument0 Star0 thermograph1)
    (take_image instrument0 Star0 thermograph2)
    (take_image instrument0 Star1 image3)
    (take_image instrument0 Star1 image4)
    (take_image instrument0 Star1 thermograph0)
    (take_image instrument0 Star1 thermograph1)
    (take_image instrument0 Star1 thermograph2)
    (take_image instrument0 Star14 image3)
    (take_image instrument0 Star14 image4)
    (take_image instrument0 Star14 thermograph0)
    (take_image instrument0 Star14 thermograph1)
    (take_image instrument0 Star14 thermograph2)
    (take_image instrument0 Star19 image3)
    (take_image instrument0 Star19 image4)
    (take_image instrument0 Star19 thermograph0)
    (take_image instrument0 Star19 thermograph1)
    (take_image instrument0 Star19 thermograph2)
    (take_image instrument0 Star21 image3)
    (take_image instrument0 Star21 image4)
    (take_image instrument0 Star21 thermograph0)
    (take_image instrument0 Star21 thermograph1)
    (take_image instrument0 Star21 thermograph2)
    (take_image instrument0 Star22 image3)
    (take_image instrument0 Star22 image4)
    (take_image instrument0 Star22 thermograph0)
    (take_image instrument0 Star22 thermograph1)
    (take_image instrument0 Star22 thermograph2)
    (take_image instrument0 Star26 image3)
    (take_image instrument0 Star26 image4)
    (take_image instrument0 Star26 thermograph0)
    (take_image instrument0 Star26 thermograph1)
    (take_image instrument0 Star26 thermograph2)
    (take_image instrument0 Star4 image3)
    (take_image instrument0 Star4 image4)
    (take_image instrument0 Star4 thermograph0)
    (take_image instrument0 Star4 thermograph1)
    (take_image instrument0 Star4 thermograph2)
    (take_image instrument1 GroundStation2 image3)
    (take_image instrument1 GroundStation2 image4)
    (take_image instrument1 GroundStation2 thermograph0)
    (take_image instrument1 GroundStation2 thermograph1)
    (take_image instrument1 GroundStation2 thermograph2)
    (take_image instrument1 GroundStation3 image3)
    (take_image instrument1 GroundStation3 image4)
    (take_image instrument1 GroundStation3 thermograph0)
    (take_image instrument1 GroundStation3 thermograph1)
    (take_image instrument1 GroundStation3 thermograph2)
    (take_image instrument1 Phenomenon12 image3)
    (take_image instrument1 Phenomenon12 image4)
    (take_image instrument1 Phenomenon12 thermograph0)
    (take_image instrument1 Phenomenon12 thermograph1)
    (take_image instrument1 Phenomenon12 thermograph2)
    (take_image instrument1 Phenomenon18 image3)
    (take_image instrument1 Phenomenon18 image4)
    (take_image instrument1 Phenomenon18 thermograph0)
    (take_image instrument1 Phenomenon18 thermograph1)
    (take_image instrument1 Phenomenon18 thermograph2)
    (take_image instrument1 Phenomenon27 image3)
    (take_image instrument1 Phenomenon27 image4)
    (take_image instrument1 Phenomenon27 thermograph0)
    (take_image instrument1 Phenomenon27 thermograph1)
    (take_image instrument1 Phenomenon27 thermograph2)
    (take_image instrument1 Phenomenon5 image3)
    (take_image instrument1 Phenomenon5 image4)
    (take_image instrument1 Phenomenon5 thermograph0)
    (take_image instrument1 Phenomenon5 thermograph1)
    (take_image instrument1 Phenomenon5 thermograph2)
    (take_image instrument1 Planet10 image3)
    (take_image instrument1 Planet10 image4)
    (take_image instrument1 Planet10 thermograph0)
    (take_image instrument1 Planet10 thermograph1)
    (take_image instrument1 Planet10 thermograph2)
    (take_image instrument1 Planet11 image3)
    (take_image instrument1 Planet11 image4)
    (take_image instrument1 Planet11 thermograph0)
    (take_image instrument1 Planet11 thermograph1)
    (take_image instrument1 Planet11 thermograph2)
    (take_image instrument1 Planet13 image3)
    (take_image instrument1 Planet13 image4)
    (take_image instrument1 Planet13 thermograph0)
    (take_image instrument1 Planet13 thermograph1)
    (take_image instrument1 Planet13 thermograph2)
    (take_image instrument1 Planet15 image3)
    (take_image instrument1 Planet15 image4)
    (take_image instrument1 Planet15 thermograph0)
    (take_image instrument1 Planet15 thermograph1)
    (take_image instrument1 Planet15 thermograph2)
    (take_image instrument1 Planet16 image3)
    (take_image instrument1 Planet16 image4)
    (take_image instrument1 Planet16 thermograph0)
    (take_image instrument1 Planet16 thermograph1)
    (take_image instrument1 Planet16 thermograph2)
    (take_image instrument1 Planet17 image3)
    (take_image instrument1 Planet17 image4)
    (take_image instrument1 Planet17 thermograph0)
    (take_image instrument1 Planet17 thermograph1)
    (take_image instrument1 Planet17 thermograph2)
    (take_image instrument1 Planet20 image3)
    (take_image instrument1 Planet20 image4)
    (take_image instrument1 Planet20 thermograph0)
    (take_image instrument1 Planet20 thermograph1)
    (take_image instrument1 Planet20 thermograph2)
    (take_image instrument1 Planet23 image3)
    (take_image instrument1 Planet23 image4)
    (take_image instrument1 Planet23 thermograph0)
    (take_image instrument1 Planet23 thermograph1)
    (take_image instrument1 Planet23 thermograph2)
    (take_image instrument1 Planet24 image3)
    (take_image instrument1 Planet24 image4)
    (take_image instrument1 Planet24 thermograph0)
    (take_image instrument1 Planet24 thermograph1)
    (take_image instrument1 Planet24 thermograph2)
    (take_image instrument1 Planet25 image3)
    (take_image instrument1 Planet25 image4)
    (take_image instrument1 Planet25 thermograph0)
    (take_image instrument1 Planet25 thermograph1)
    (take_image instrument1 Planet25 thermograph2)
    (take_image instrument1 Planet28 image3)
    (take_image instrument1 Planet28 image4)
    (take_image instrument1 Planet28 thermograph0)
    (take_image instrument1 Planet28 thermograph1)
    (take_image instrument1 Planet28 thermograph2)
    (take_image instrument1 Planet29 image3)
    (take_image instrument1 Planet29 image4)
    (take_image instrument1 Planet29 thermograph0)
    (take_image instrument1 Planet29 thermograph1)
    (take_image instrument1 Planet29 thermograph2)
    (take_image instrument1 Planet6 image3)
    (take_image instrument1 Planet6 image4)
    (take_image instrument1 Planet6 thermograph0)
    (take_image instrument1 Planet6 thermograph1)
    (take_image instrument1 Planet6 thermograph2)
    (take_image instrument1 Planet7 image3)
    (take_image instrument1 Planet7 image4)
    (take_image instrument1 Planet7 thermograph0)
    (take_image instrument1 Planet7 thermograph1)
    (take_image instrument1 Planet7 thermograph2)
    (take_image instrument1 Planet8 image3)
    (take_image instrument1 Planet8 image4)
    (take_image instrument1 Planet8 thermograph0)
    (take_image instrument1 Planet8 thermograph1)
    (take_image instrument1 Planet8 thermograph2)
    (take_image instrument1 Planet9 image3)
    (take_image instrument1 Planet9 image4)
    (take_image instrument1 Planet9 thermograph0)
    (take_image instrument1 Planet9 thermograph1)
    (take_image instrument1 Planet9 thermograph2)
    (take_image instrument1 Star0 image3)
    (take_image instrument1 Star0 image4)
    (take_image instrument1 Star0 thermograph0)
    (take_image instrument1 Star0 thermograph1)
    (take_image instrument1 Star0 thermograph2)
    (take_image instrument1 Star1 image3)
    (take_image instrument1 Star1 image4)
    (take_image instrument1 Star1 thermograph0)
    (take_image instrument1 Star1 thermograph1)
    (take_image instrument1 Star1 thermograph2)
    (take_image instrument1 Star14 image3)
    (take_image instrument1 Star14 image4)
    (take_image instrument1 Star14 thermograph0)
    (take_image instrument1 Star14 thermograph1)
    (take_image instrument1 Star14 thermograph2)
    (take_image instrument1 Star19 image3)
    (take_image instrument1 Star19 image4)
    (take_image instrument1 Star19 thermograph0)
    (take_image instrument1 Star19 thermograph1)
    (take_image instrument1 Star19 thermograph2)
    (take_image instrument1 Star21 image3)
    (take_image instrument1 Star21 image4)
    (take_image instrument1 Star21 thermograph0)
    (take_image instrument1 Star21 thermograph1)
    (take_image instrument1 Star21 thermograph2)
    (take_image instrument1 Star22 image3)
    (take_image instrument1 Star22 image4)
    (take_image instrument1 Star22 thermograph0)
    (take_image instrument1 Star22 thermograph1)
    (take_image instrument1 Star22 thermograph2)
    (take_image instrument1 Star26 image3)
    (take_image instrument1 Star26 image4)
    (take_image instrument1 Star26 thermograph0)
    (take_image instrument1 Star26 thermograph1)
    (take_image instrument1 Star26 thermograph2)
    (take_image instrument1 Star4 image3)
    (take_image instrument1 Star4 image4)
    (take_image instrument1 Star4 thermograph0)
    (take_image instrument1 Star4 thermograph1)
    (take_image instrument1 Star4 thermograph2)
    (take_image instrument2 GroundStation2 image3)
    (take_image instrument2 GroundStation2 image4)
    (take_image instrument2 GroundStation2 thermograph0)
    (take_image instrument2 GroundStation2 thermograph1)
    (take_image instrument2 GroundStation2 thermograph2)
    (take_image instrument2 GroundStation3 image3)
    (take_image instrument2 GroundStation3 image4)
    (take_image instrument2 GroundStation3 thermograph0)
    (take_image instrument2 GroundStation3 thermograph1)
    (take_image instrument2 GroundStation3 thermograph2)
    (take_image instrument2 Phenomenon12 image3)
    (take_image instrument2 Phenomenon12 image4)
    (take_image instrument2 Phenomenon12 thermograph0)
    (take_image instrument2 Phenomenon12 thermograph1)
    (take_image instrument2 Phenomenon12 thermograph2)
    (take_image instrument2 Phenomenon18 image3)
    (take_image instrument2 Phenomenon18 image4)
    (take_image instrument2 Phenomenon18 thermograph0)
    (take_image instrument2 Phenomenon18 thermograph1)
    (take_image instrument2 Phenomenon18 thermograph2)
    (take_image instrument2 Phenomenon27 image3)
    (take_image instrument2 Phenomenon27 image4)
    (take_image instrument2 Phenomenon27 thermograph0)
    (take_image instrument2 Phenomenon27 thermograph1)
    (take_image instrument2 Phenomenon27 thermograph2)
    (take_image instrument2 Phenomenon5 image3)
    (take_image instrument2 Phenomenon5 image4)
    (take_image instrument2 Phenomenon5 thermograph0)
    (take_image instrument2 Phenomenon5 thermograph1)
    (take_image instrument2 Phenomenon5 thermograph2)
    (take_image instrument2 Planet10 image3)
    (take_image instrument2 Planet10 image4)
    (take_image instrument2 Planet10 thermograph0)
    (take_image instrument2 Planet10 thermograph1)
    (take_image instrument2 Planet10 thermograph2)
    (take_image instrument2 Planet11 image3)
    (take_image instrument2 Planet11 image4)
    (take_image instrument2 Planet11 thermograph0)
    (take_image instrument2 Planet11 thermograph1)
    (take_image instrument2 Planet11 thermograph2)
    (take_image instrument2 Planet13 image3)
    (take_image instrument2 Planet13 image4)
    (take_image instrument2 Planet13 thermograph0)
    (take_image instrument2 Planet13 thermograph1)
    (take_image instrument2 Planet13 thermograph2)
    (take_image instrument2 Planet15 image3)
    (take_image instrument2 Planet15 image4)
    (take_image instrument2 Planet15 thermograph0)
    (take_image instrument2 Planet15 thermograph1)
    (take_image instrument2 Planet15 thermograph2)
    (take_image instrument2 Planet16 image3)
    (take_image instrument2 Planet16 image4)
    (take_image instrument2 Planet16 thermograph0)
    (take_image instrument2 Planet16 thermograph1)
    (take_image instrument2 Planet16 thermograph2)
    (take_image instrument2 Planet17 image3)
    (take_image instrument2 Planet17 image4)
    (take_image instrument2 Planet17 thermograph0)
    (take_image instrument2 Planet17 thermograph1)
    (take_image instrument2 Planet17 thermograph2)
    (take_image instrument2 Planet20 image3)
    (take_image instrument2 Planet20 image4)
    (take_image instrument2 Planet20 thermograph0)
    (take_image instrument2 Planet20 thermograph1)
    (take_image instrument2 Planet20 thermograph2)
    (take_image instrument2 Planet23 image3)
    (take_image instrument2 Planet23 image4)
    (take_image instrument2 Planet23 thermograph0)
    (take_image instrument2 Planet23 thermograph1)
    (take_image instrument2 Planet23 thermograph2)
    (take_image instrument2 Planet24 image3)
    (take_image instrument2 Planet24 image4)
    (take_image instrument2 Planet24 thermograph0)
    (take_image instrument2 Planet24 thermograph1)
    (take_image instrument2 Planet24 thermograph2)
    (take_image instrument2 Planet25 image3)
    (take_image instrument2 Planet25 image4)
    (take_image instrument2 Planet25 thermograph0)
    (take_image instrument2 Planet25 thermograph1)
    (take_image instrument2 Planet25 thermograph2)
    (take_image instrument2 Planet28 image3)
    (take_image instrument2 Planet28 image4)
    (take_image instrument2 Planet28 thermograph0)
    (take_image instrument2 Planet28 thermograph1)
    (take_image instrument2 Planet28 thermograph2)
    (take_image instrument2 Planet29 image3)
    (take_image instrument2 Planet29 image4)
    (take_image instrument2 Planet29 thermograph0)
    (take_image instrument2 Planet29 thermograph1)
    (take_image instrument2 Planet29 thermograph2)
    (take_image instrument2 Planet6 image3)
    (take_image instrument2 Planet6 image4)
    (take_image instrument2 Planet6 thermograph0)
    (take_image instrument2 Planet6 thermograph1)
    (take_image instrument2 Planet6 thermograph2)
    (take_image instrument2 Planet7 image3)
    (take_image instrument2 Planet7 image4)
    (take_image instrument2 Planet7 thermograph0)
    (take_image instrument2 Planet7 thermograph1)
    (take_image instrument2 Planet7 thermograph2)
    (take_image instrument2 Planet8 image3)
    (take_image instrument2 Planet8 image4)
    (take_image instrument2 Planet8 thermograph0)
    (take_image instrument2 Planet8 thermograph1)
    (take_image instrument2 Planet8 thermograph2)
    (take_image instrument2 Planet9 image3)
    (take_image instrument2 Planet9 image4)
    (take_image instrument2 Planet9 thermograph0)
    (take_image instrument2 Planet9 thermograph1)
    (take_image instrument2 Planet9 thermograph2)
    (take_image instrument2 Star0 image3)
    (take_image instrument2 Star0 image4)
    (take_image instrument2 Star0 thermograph0)
    (take_image instrument2 Star0 thermograph1)
    (take_image instrument2 Star0 thermograph2)
    (take_image instrument2 Star1 image3)
    (take_image instrument2 Star1 image4)
    (take_image instrument2 Star1 thermograph0)
    (take_image instrument2 Star1 thermograph1)
    (take_image instrument2 Star1 thermograph2)
    (take_image instrument2 Star14 image3)
    (take_image instrument2 Star14 image4)
    (take_image instrument2 Star14 thermograph0)
    (take_image instrument2 Star14 thermograph1)
    (take_image instrument2 Star14 thermograph2)
    (take_image instrument2 Star19 image3)
    (take_image instrument2 Star19 image4)
    (take_image instrument2 Star19 thermograph0)
    (take_image instrument2 Star19 thermograph1)
    (take_image instrument2 Star19 thermograph2)
    (take_image instrument2 Star21 image3)
    (take_image instrument2 Star21 image4)
    (take_image instrument2 Star21 thermograph0)
    (take_image instrument2 Star21 thermograph1)
    (take_image instrument2 Star21 thermograph2)
    (take_image instrument2 Star22 image3)
    (take_image instrument2 Star22 image4)
    (take_image instrument2 Star22 thermograph0)
    (take_image instrument2 Star22 thermograph1)
    (take_image instrument2 Star22 thermograph2)
    (take_image instrument2 Star26 image3)
    (take_image instrument2 Star26 image4)
    (take_image instrument2 Star26 thermograph0)
    (take_image instrument2 Star26 thermograph1)
    (take_image instrument2 Star26 thermograph2)
    (take_image instrument2 Star4 image3)
    (take_image instrument2 Star4 image4)
    (take_image instrument2 Star4 thermograph0)
    (take_image instrument2 Star4 thermograph1)
    (take_image instrument2 Star4 thermograph2)
    (take_image instrument3 GroundStation2 image3)
    (take_image instrument3 GroundStation2 image4)
    (take_image instrument3 GroundStation2 thermograph0)
    (take_image instrument3 GroundStation2 thermograph1)
    (take_image instrument3 GroundStation2 thermograph2)
    (take_image instrument3 GroundStation3 image3)
    (take_image instrument3 GroundStation3 image4)
    (take_image instrument3 GroundStation3 thermograph0)
    (take_image instrument3 GroundStation3 thermograph1)
    (take_image instrument3 GroundStation3 thermograph2)
    (take_image instrument3 Phenomenon12 image3)
    (take_image instrument3 Phenomenon12 image4)
    (take_image instrument3 Phenomenon12 thermograph0)
    (take_image instrument3 Phenomenon12 thermograph1)
    (take_image instrument3 Phenomenon12 thermograph2)
    (take_image instrument3 Phenomenon18 image3)
    (take_image instrument3 Phenomenon18 image4)
    (take_image instrument3 Phenomenon18 thermograph0)
    (take_image instrument3 Phenomenon18 thermograph1)
    (take_image instrument3 Phenomenon18 thermograph2)
    (take_image instrument3 Phenomenon27 image3)
    (take_image instrument3 Phenomenon27 image4)
    (take_image instrument3 Phenomenon27 thermograph0)
    (take_image instrument3 Phenomenon27 thermograph1)
    (take_image instrument3 Phenomenon27 thermograph2)
    (take_image instrument3 Phenomenon5 image3)
    (take_image instrument3 Phenomenon5 image4)
    (take_image instrument3 Phenomenon5 thermograph0)
    (take_image instrument3 Phenomenon5 thermograph1)
    (take_image instrument3 Phenomenon5 thermograph2)
    (take_image instrument3 Planet10 image3)
    (take_image instrument3 Planet10 image4)
    (take_image instrument3 Planet10 thermograph0)
    (take_image instrument3 Planet10 thermograph1)
    (take_image instrument3 Planet10 thermograph2)
    (take_image instrument3 Planet11 image3)
    (take_image instrument3 Planet11 image4)
    (take_image instrument3 Planet11 thermograph0)
    (take_image instrument3 Planet11 thermograph1)
    (take_image instrument3 Planet11 thermograph2)
    (take_image instrument3 Planet13 image3)
    (take_image instrument3 Planet13 image4)
    (take_image instrument3 Planet13 thermograph0)
    (take_image instrument3 Planet13 thermograph1)
    (take_image instrument3 Planet13 thermograph2)
    (take_image instrument3 Planet15 image3)
    (take_image instrument3 Planet15 image4)
    (take_image instrument3 Planet15 thermograph0)
    (take_image instrument3 Planet15 thermograph1)
    (take_image instrument3 Planet15 thermograph2)
    (take_image instrument3 Planet16 image3)
    (take_image instrument3 Planet16 image4)
    (take_image instrument3 Planet16 thermograph0)
    (take_image instrument3 Planet16 thermograph1)
    (take_image instrument3 Planet16 thermograph2)
    (take_image instrument3 Planet17 image3)
    (take_image instrument3 Planet17 image4)
    (take_image instrument3 Planet17 thermograph0)
    (take_image instrument3 Planet17 thermograph1)
    (take_image instrument3 Planet17 thermograph2)
    (take_image instrument3 Planet20 image3)
    (take_image instrument3 Planet20 image4)
    (take_image instrument3 Planet20 thermograph0)
    (take_image instrument3 Planet20 thermograph1)
    (take_image instrument3 Planet20 thermograph2)
    (take_image instrument3 Planet23 image3)
    (take_image instrument3 Planet23 image4)
    (take_image instrument3 Planet23 thermograph0)
    (take_image instrument3 Planet23 thermograph1)
    (take_image instrument3 Planet23 thermograph2)
    (take_image instrument3 Planet24 image3)
    (take_image instrument3 Planet24 image4)
    (take_image instrument3 Planet24 thermograph0)
    (take_image instrument3 Planet24 thermograph1)
    (take_image instrument3 Planet24 thermograph2)
    (take_image instrument3 Planet25 image3)
    (take_image instrument3 Planet25 image4)
    (take_image instrument3 Planet25 thermograph0)
    (take_image instrument3 Planet25 thermograph1)
    (take_image instrument3 Planet25 thermograph2)
    (take_image instrument3 Planet28 image3)
    (take_image instrument3 Planet28 image4)
    (take_image instrument3 Planet28 thermograph0)
    (take_image instrument3 Planet28 thermograph1)
    (take_image instrument3 Planet28 thermograph2)
    (take_image instrument3 Planet29 image3)
    (take_image instrument3 Planet29 image4)
    (take_image instrument3 Planet29 thermograph0)
    (take_image instrument3 Planet29 thermograph1)
    (take_image instrument3 Planet29 thermograph2)
    (take_image instrument3 Planet6 image3)
    (take_image instrument3 Planet6 image4)
    (take_image instrument3 Planet6 thermograph0)
    (take_image instrument3 Planet6 thermograph1)
    (take_image instrument3 Planet6 thermograph2)
    (take_image instrument3 Planet7 image3)
    (take_image instrument3 Planet7 image4)
    (take_image instrument3 Planet7 thermograph0)
    (take_image instrument3 Planet7 thermograph1)
    (take_image instrument3 Planet7 thermograph2)
    (take_image instrument3 Planet8 image3)
    (take_image instrument3 Planet8 image4)
    (take_image instrument3 Planet8 thermograph0)
    (take_image instrument3 Planet8 thermograph1)
    (take_image instrument3 Planet8 thermograph2)
    (take_image instrument3 Planet9 image3)
    (take_image instrument3 Planet9 image4)
    (take_image instrument3 Planet9 thermograph0)
    (take_image instrument3 Planet9 thermograph1)
    (take_image instrument3 Planet9 thermograph2)
    (take_image instrument3 Star0 image3)
    (take_image instrument3 Star0 image4)
    (take_image instrument3 Star0 thermograph0)
    (take_image instrument3 Star0 thermograph1)
    (take_image instrument3 Star0 thermograph2)
    (take_image instrument3 Star1 image3)
    (take_image instrument3 Star1 image4)
    (take_image instrument3 Star1 thermograph0)
    (take_image instrument3 Star1 thermograph1)
    (take_image instrument3 Star1 thermograph2)
    (take_image instrument3 Star14 image3)
    (take_image instrument3 Star14 image4)
    (take_image instrument3 Star14 thermograph0)
    (take_image instrument3 Star14 thermograph1)
    (take_image instrument3 Star14 thermograph2)
    (take_image instrument3 Star19 image3)
    (take_image instrument3 Star19 image4)
    (take_image instrument3 Star19 thermograph0)
    (take_image instrument3 Star19 thermograph1)
    (take_image instrument3 Star19 thermograph2)
    (take_image instrument3 Star21 image3)
    (take_image instrument3 Star21 image4)
    (take_image instrument3 Star21 thermograph0)
    (take_image instrument3 Star21 thermograph1)
    (take_image instrument3 Star21 thermograph2)
    (take_image instrument3 Star22 image3)
    (take_image instrument3 Star22 image4)
    (take_image instrument3 Star22 thermograph0)
    (take_image instrument3 Star22 thermograph1)
    (take_image instrument3 Star22 thermograph2)
    (take_image instrument3 Star26 image3)
    (take_image instrument3 Star26 image4)
    (take_image instrument3 Star26 thermograph0)
    (take_image instrument3 Star26 thermograph1)
    (take_image instrument3 Star26 thermograph2)
    (take_image instrument3 Star4 image3)
    (take_image instrument3 Star4 image4)
    (take_image instrument3 Star4 thermograph0)
    (take_image instrument3 Star4 thermograph1)
    (take_image instrument3 Star4 thermograph2)
    (take_image instrument4 GroundStation2 image3)
    (take_image instrument4 GroundStation2 image4)
    (take_image instrument4 GroundStation2 thermograph0)
    (take_image instrument4 GroundStation2 thermograph1)
    (take_image instrument4 GroundStation2 thermograph2)
    (take_image instrument4 GroundStation3 image3)
    (take_image instrument4 GroundStation3 image4)
    (take_image instrument4 GroundStation3 thermograph0)
    (take_image instrument4 GroundStation3 thermograph1)
    (take_image instrument4 GroundStation3 thermograph2)
    (take_image instrument4 Phenomenon12 image3)
    (take_image instrument4 Phenomenon12 image4)
    (take_image instrument4 Phenomenon12 thermograph0)
    (take_image instrument4 Phenomenon12 thermograph1)
    (take_image instrument4 Phenomenon12 thermograph2)
    (take_image instrument4 Phenomenon18 image3)
    (take_image instrument4 Phenomenon18 image4)
    (take_image instrument4 Phenomenon18 thermograph0)
    (take_image instrument4 Phenomenon18 thermograph1)
    (take_image instrument4 Phenomenon18 thermograph2)
    (take_image instrument4 Phenomenon27 image3)
    (take_image instrument4 Phenomenon27 image4)
    (take_image instrument4 Phenomenon27 thermograph0)
    (take_image instrument4 Phenomenon27 thermograph1)
    (take_image instrument4 Phenomenon27 thermograph2)
    (take_image instrument4 Phenomenon5 image3)
    (take_image instrument4 Phenomenon5 image4)
    (take_image instrument4 Phenomenon5 thermograph0)
    (take_image instrument4 Phenomenon5 thermograph1)
    (take_image instrument4 Phenomenon5 thermograph2)
    (take_image instrument4 Planet10 image3)
    (take_image instrument4 Planet10 image4)
    (take_image instrument4 Planet10 thermograph0)
    (take_image instrument4 Planet10 thermograph1)
    (take_image instrument4 Planet10 thermograph2)
    (take_image instrument4 Planet11 image3)
    (take_image instrument4 Planet11 image4)
    (take_image instrument4 Planet11 thermograph0)
    (take_image instrument4 Planet11 thermograph1)
    (take_image instrument4 Planet11 thermograph2)
    (take_image instrument4 Planet13 image3)
    (take_image instrument4 Planet13 image4)
    (take_image instrument4 Planet13 thermograph0)
    (take_image instrument4 Planet13 thermograph1)
    (take_image instrument4 Planet13 thermograph2)
    (take_image instrument4 Planet15 image3)
    (take_image instrument4 Planet15 image4)
    (take_image instrument4 Planet15 thermograph0)
    (take_image instrument4 Planet15 thermograph1)
    (take_image instrument4 Planet15 thermograph2)
    (take_image instrument4 Planet16 image3)
    (take_image instrument4 Planet16 image4)
    (take_image instrument4 Planet16 thermograph0)
    (take_image instrument4 Planet16 thermograph1)
    (take_image instrument4 Planet16 thermograph2)
    (take_image instrument4 Planet17 image3)
    (take_image instrument4 Planet17 image4)
    (take_image instrument4 Planet17 thermograph0)
    (take_image instrument4 Planet17 thermograph1)
    (take_image instrument4 Planet17 thermograph2)
    (take_image instrument4 Planet20 image3)
    (take_image instrument4 Planet20 image4)
    (take_image instrument4 Planet20 thermograph0)
    (take_image instrument4 Planet20 thermograph1)
    (take_image instrument4 Planet20 thermograph2)
    (take_image instrument4 Planet23 image3)
    (take_image instrument4 Planet23 image4)
    (take_image instrument4 Planet23 thermograph0)
    (take_image instrument4 Planet23 thermograph1)
    (take_image instrument4 Planet23 thermograph2)
    (take_image instrument4 Planet24 image3)
    (take_image instrument4 Planet24 image4)
    (take_image instrument4 Planet24 thermograph0)
    (take_image instrument4 Planet24 thermograph1)
    (take_image instrument4 Planet24 thermograph2)
    (take_image instrument4 Planet25 image3)
    (take_image instrument4 Planet25 image4)
    (take_image instrument4 Planet25 thermograph0)
    (take_image instrument4 Planet25 thermograph1)
    (take_image instrument4 Planet25 thermograph2)
    (take_image instrument4 Planet28 image3)
    (take_image instrument4 Planet28 image4)
    (take_image instrument4 Planet28 thermograph0)
    (take_image instrument4 Planet28 thermograph1)
    (take_image instrument4 Planet28 thermograph2)
    (take_image instrument4 Planet29 image3)
    (take_image instrument4 Planet29 image4)
    (take_image instrument4 Planet29 thermograph0)
    (take_image instrument4 Planet29 thermograph1)
    (take_image instrument4 Planet29 thermograph2)
    (take_image instrument4 Planet6 image3)
    (take_image instrument4 Planet6 image4)
    (take_image instrument4 Planet6 thermograph0)
    (take_image instrument4 Planet6 thermograph1)
    (take_image instrument4 Planet6 thermograph2)
    (take_image instrument4 Planet7 image3)
    (take_image instrument4 Planet7 image4)
    (take_image instrument4 Planet7 thermograph0)
    (take_image instrument4 Planet7 thermograph1)
    (take_image instrument4 Planet7 thermograph2)
    (take_image instrument4 Planet8 image3)
    (take_image instrument4 Planet8 image4)
    (take_image instrument4 Planet8 thermograph0)
    (take_image instrument4 Planet8 thermograph1)
    (take_image instrument4 Planet8 thermograph2)
    (take_image instrument4 Planet9 image3)
    (take_image instrument4 Planet9 image4)
    (take_image instrument4 Planet9 thermograph0)
    (take_image instrument4 Planet9 thermograph1)
    (take_image instrument4 Planet9 thermograph2)
    (take_image instrument4 Star0 image3)
    (take_image instrument4 Star0 image4)
    (take_image instrument4 Star0 thermograph0)
    (take_image instrument4 Star0 thermograph1)
    (take_image instrument4 Star0 thermograph2)
    (take_image instrument4 Star1 image3)
    (take_image instrument4 Star1 image4)
    (take_image instrument4 Star1 thermograph0)
    (take_image instrument4 Star1 thermograph1)
    (take_image instrument4 Star1 thermograph2)
    (take_image instrument4 Star14 image3)
    (take_image instrument4 Star14 image4)
    (take_image instrument4 Star14 thermograph0)
    (take_image instrument4 Star14 thermograph1)
    (take_image instrument4 Star14 thermograph2)
    (take_image instrument4 Star19 image3)
    (take_image instrument4 Star19 image4)
    (take_image instrument4 Star19 thermograph0)
    (take_image instrument4 Star19 thermograph1)
    (take_image instrument4 Star19 thermograph2)
    (take_image instrument4 Star21 image3)
    (take_image instrument4 Star21 image4)
    (take_image instrument4 Star21 thermograph0)
    (take_image instrument4 Star21 thermograph1)
    (take_image instrument4 Star21 thermograph2)
    (take_image instrument4 Star22 image3)
    (take_image instrument4 Star22 image4)
    (take_image instrument4 Star22 thermograph0)
    (take_image instrument4 Star22 thermograph1)
    (take_image instrument4 Star22 thermograph2)
    (take_image instrument4 Star26 image3)
    (take_image instrument4 Star26 image4)
    (take_image instrument4 Star26 thermograph0)
    (take_image instrument4 Star26 thermograph1)
    (take_image instrument4 Star26 thermograph2)
    (take_image instrument4 Star4 image3)
    (take_image instrument4 Star4 image4)
    (take_image instrument4 Star4 thermograph0)
    (take_image instrument4 Star4 thermograph1)
    (take_image instrument4 Star4 thermograph2)
    (take_image instrument5 GroundStation2 image3)
    (take_image instrument5 GroundStation2 image4)
    (take_image instrument5 GroundStation2 thermograph0)
    (take_image instrument5 GroundStation2 thermograph1)
    (take_image instrument5 GroundStation2 thermograph2)
    (take_image instrument5 GroundStation3 image3)
    (take_image instrument5 GroundStation3 image4)
    (take_image instrument5 GroundStation3 thermograph0)
    (take_image instrument5 GroundStation3 thermograph1)
    (take_image instrument5 GroundStation3 thermograph2)
    (take_image instrument5 Phenomenon12 image3)
    (take_image instrument5 Phenomenon12 image4)
    (take_image instrument5 Phenomenon12 thermograph0)
    (take_image instrument5 Phenomenon12 thermograph1)
    (take_image instrument5 Phenomenon12 thermograph2)
    (take_image instrument5 Phenomenon18 image3)
    (take_image instrument5 Phenomenon18 image4)
    (take_image instrument5 Phenomenon18 thermograph0)
    (take_image instrument5 Phenomenon18 thermograph1)
    (take_image instrument5 Phenomenon18 thermograph2)
    (take_image instrument5 Phenomenon27 image3)
    (take_image instrument5 Phenomenon27 image4)
    (take_image instrument5 Phenomenon27 thermograph0)
    (take_image instrument5 Phenomenon27 thermograph1)
    (take_image instrument5 Phenomenon27 thermograph2)
    (take_image instrument5 Phenomenon5 image3)
    (take_image instrument5 Phenomenon5 image4)
    (take_image instrument5 Phenomenon5 thermograph0)
    (take_image instrument5 Phenomenon5 thermograph1)
    (take_image instrument5 Phenomenon5 thermograph2)
    (take_image instrument5 Planet10 image3)
    (take_image instrument5 Planet10 image4)
    (take_image instrument5 Planet10 thermograph0)
    (take_image instrument5 Planet10 thermograph1)
    (take_image instrument5 Planet10 thermograph2)
    (take_image instrument5 Planet11 image3)
    (take_image instrument5 Planet11 image4)
    (take_image instrument5 Planet11 thermograph0)
    (take_image instrument5 Planet11 thermograph1)
    (take_image instrument5 Planet11 thermograph2)
    (take_image instrument5 Planet13 image3)
    (take_image instrument5 Planet13 image4)
    (take_image instrument5 Planet13 thermograph0)
    (take_image instrument5 Planet13 thermograph1)
    (take_image instrument5 Planet13 thermograph2)
    (take_image instrument5 Planet15 image3)
    (take_image instrument5 Planet15 image4)
    (take_image instrument5 Planet15 thermograph0)
    (take_image instrument5 Planet15 thermograph1)
    (take_image instrument5 Planet15 thermograph2)
    (take_image instrument5 Planet16 image3)
    (take_image instrument5 Planet16 image4)
    (take_image instrument5 Planet16 thermograph0)
    (take_image instrument5 Planet16 thermograph1)
    (take_image instrument5 Planet16 thermograph2)
    (take_image instrument5 Planet17 image3)
    (take_image instrument5 Planet17 image4)
    (take_image instrument5 Planet17 thermograph0)
    (take_image instrument5 Planet17 thermograph1)
    (take_image instrument5 Planet17 thermograph2)
    (take_image instrument5 Planet20 image3)
    (take_image instrument5 Planet20 image4)
    (take_image instrument5 Planet20 thermograph0)
    (take_image instrument5 Planet20 thermograph1)
    (take_image instrument5 Planet20 thermograph2)
    (take_image instrument5 Planet23 image3)
    (take_image instrument5 Planet23 image4)
    (take_image instrument5 Planet23 thermograph0)
    (take_image instrument5 Planet23 thermograph1)
    (take_image instrument5 Planet23 thermograph2)
    (take_image instrument5 Planet24 image3)
    (take_image instrument5 Planet24 image4)
    (take_image instrument5 Planet24 thermograph0)
    (take_image instrument5 Planet24 thermograph1)
    (take_image instrument5 Planet24 thermograph2)
    (take_image instrument5 Planet25 image3)
    (take_image instrument5 Planet25 image4)
    (take_image instrument5 Planet25 thermograph0)
    (take_image instrument5 Planet25 thermograph1)
    (take_image instrument5 Planet25 thermograph2)
    (take_image instrument5 Planet28 image3)
    (take_image instrument5 Planet28 image4)
    (take_image instrument5 Planet28 thermograph0)
    (take_image instrument5 Planet28 thermograph1)
    (take_image instrument5 Planet28 thermograph2)
    (take_image instrument5 Planet29 image3)
    (take_image instrument5 Planet29 image4)
    (take_image instrument5 Planet29 thermograph0)
    (take_image instrument5 Planet29 thermograph1)
    (take_image instrument5 Planet29 thermograph2)
    (take_image instrument5 Planet6 image3)
    (take_image instrument5 Planet6 image4)
    (take_image instrument5 Planet6 thermograph0)
    (take_image instrument5 Planet6 thermograph1)
    (take_image instrument5 Planet6 thermograph2)
    (take_image instrument5 Planet7 image3)
    (take_image instrument5 Planet7 image4)
    (take_image instrument5 Planet7 thermograph0)
    (take_image instrument5 Planet7 thermograph1)
    (take_image instrument5 Planet7 thermograph2)
    (take_image instrument5 Planet8 image3)
    (take_image instrument5 Planet8 image4)
    (take_image instrument5 Planet8 thermograph0)
    (take_image instrument5 Planet8 thermograph1)
    (take_image instrument5 Planet8 thermograph2)
    (take_image instrument5 Planet9 image3)
    (take_image instrument5 Planet9 image4)
    (take_image instrument5 Planet9 thermograph0)
    (take_image instrument5 Planet9 thermograph1)
    (take_image instrument5 Planet9 thermograph2)
    (take_image instrument5 Star0 image3)
    (take_image instrument5 Star0 image4)
    (take_image instrument5 Star0 thermograph0)
    (take_image instrument5 Star0 thermograph1)
    (take_image instrument5 Star0 thermograph2)
    (take_image instrument5 Star1 image3)
    (take_image instrument5 Star1 image4)
    (take_image instrument5 Star1 thermograph0)
    (take_image instrument5 Star1 thermograph1)
    (take_image instrument5 Star1 thermograph2)
    (take_image instrument5 Star14 image3)
    (take_image instrument5 Star14 image4)
    (take_image instrument5 Star14 thermograph0)
    (take_image instrument5 Star14 thermograph1)
    (take_image instrument5 Star14 thermograph2)
    (take_image instrument5 Star19 image3)
    (take_image instrument5 Star19 image4)
    (take_image instrument5 Star19 thermograph0)
    (take_image instrument5 Star19 thermograph1)
    (take_image instrument5 Star19 thermograph2)
    (take_image instrument5 Star21 image3)
    (take_image instrument5 Star21 image4)
    (take_image instrument5 Star21 thermograph0)
    (take_image instrument5 Star21 thermograph1)
    (take_image instrument5 Star21 thermograph2)
    (take_image instrument5 Star22 image3)
    (take_image instrument5 Star22 image4)
    (take_image instrument5 Star22 thermograph0)
    (take_image instrument5 Star22 thermograph1)
    (take_image instrument5 Star22 thermograph2)
    (take_image instrument5 Star26 image3)
    (take_image instrument5 Star26 image4)
    (take_image instrument5 Star26 thermograph0)
    (take_image instrument5 Star26 thermograph1)
    (take_image instrument5 Star26 thermograph2)
    (take_image instrument5 Star4 image3)
    (take_image instrument5 Star4 image4)
    (take_image instrument5 Star4 thermograph0)
    (take_image instrument5 Star4 thermograph1)
    (take_image instrument5 Star4 thermograph2)
    (take_image instrument6 GroundStation2 image3)
    (take_image instrument6 GroundStation2 image4)
    (take_image instrument6 GroundStation2 thermograph0)
    (take_image instrument6 GroundStation2 thermograph1)
    (take_image instrument6 GroundStation2 thermograph2)
    (take_image instrument6 GroundStation3 image3)
    (take_image instrument6 GroundStation3 image4)
    (take_image instrument6 GroundStation3 thermograph0)
    (take_image instrument6 GroundStation3 thermograph1)
    (take_image instrument6 GroundStation3 thermograph2)
    (take_image instrument6 Phenomenon12 image3)
    (take_image instrument6 Phenomenon12 image4)
    (take_image instrument6 Phenomenon12 thermograph0)
    (take_image instrument6 Phenomenon12 thermograph1)
    (take_image instrument6 Phenomenon12 thermograph2)
    (take_image instrument6 Phenomenon18 image3)
    (take_image instrument6 Phenomenon18 image4)
    (take_image instrument6 Phenomenon18 thermograph0)
    (take_image instrument6 Phenomenon18 thermograph1)
    (take_image instrument6 Phenomenon18 thermograph2)
    (take_image instrument6 Phenomenon27 image3)
    (take_image instrument6 Phenomenon27 image4)
    (take_image instrument6 Phenomenon27 thermograph0)
    (take_image instrument6 Phenomenon27 thermograph1)
    (take_image instrument6 Phenomenon27 thermograph2)
    (take_image instrument6 Phenomenon5 image3)
    (take_image instrument6 Phenomenon5 image4)
    (take_image instrument6 Phenomenon5 thermograph0)
    (take_image instrument6 Phenomenon5 thermograph1)
    (take_image instrument6 Phenomenon5 thermograph2)
    (take_image instrument6 Planet10 image3)
    (take_image instrument6 Planet10 image4)
    (take_image instrument6 Planet10 thermograph0)
    (take_image instrument6 Planet10 thermograph1)
    (take_image instrument6 Planet10 thermograph2)
    (take_image instrument6 Planet11 image3)
    (take_image instrument6 Planet11 image4)
    (take_image instrument6 Planet11 thermograph0)
    (take_image instrument6 Planet11 thermograph1)
    (take_image instrument6 Planet11 thermograph2)
    (take_image instrument6 Planet13 image3)
    (take_image instrument6 Planet13 image4)
    (take_image instrument6 Planet13 thermograph0)
    (take_image instrument6 Planet13 thermograph1)
    (take_image instrument6 Planet13 thermograph2)
    (take_image instrument6 Planet15 image3)
    (take_image instrument6 Planet15 image4)
    (take_image instrument6 Planet15 thermograph0)
    (take_image instrument6 Planet15 thermograph1)
    (take_image instrument6 Planet15 thermograph2)
    (take_image instrument6 Planet16 image3)
    (take_image instrument6 Planet16 image4)
    (take_image instrument6 Planet16 thermograph0)
    (take_image instrument6 Planet16 thermograph1)
    (take_image instrument6 Planet16 thermograph2)
    (take_image instrument6 Planet17 image3)
    (take_image instrument6 Planet17 image4)
    (take_image instrument6 Planet17 thermograph0)
    (take_image instrument6 Planet17 thermograph1)
    (take_image instrument6 Planet17 thermograph2)
    (take_image instrument6 Planet20 image3)
    (take_image instrument6 Planet20 image4)
    (take_image instrument6 Planet20 thermograph0)
    (take_image instrument6 Planet20 thermograph1)
    (take_image instrument6 Planet20 thermograph2)
    (take_image instrument6 Planet23 image3)
    (take_image instrument6 Planet23 image4)
    (take_image instrument6 Planet23 thermograph0)
    (take_image instrument6 Planet23 thermograph1)
    (take_image instrument6 Planet23 thermograph2)
    (take_image instrument6 Planet24 image3)
    (take_image instrument6 Planet24 image4)
    (take_image instrument6 Planet24 thermograph0)
    (take_image instrument6 Planet24 thermograph1)
    (take_image instrument6 Planet24 thermograph2)
    (take_image instrument6 Planet25 image3)
    (take_image instrument6 Planet25 image4)
    (take_image instrument6 Planet25 thermograph0)
    (take_image instrument6 Planet25 thermograph1)
    (take_image instrument6 Planet25 thermograph2)
    (take_image instrument6 Planet28 image3)
    (take_image instrument6 Planet28 image4)
    (take_image instrument6 Planet28 thermograph0)
    (take_image instrument6 Planet28 thermograph1)
    (take_image instrument6 Planet28 thermograph2)
    (take_image instrument6 Planet29 image3)
    (take_image instrument6 Planet29 image4)
    (take_image instrument6 Planet29 thermograph0)
    (take_image instrument6 Planet29 thermograph1)
    (take_image instrument6 Planet29 thermograph2)
    (take_image instrument6 Planet6 image3)
    (take_image instrument6 Planet6 image4)
    (take_image instrument6 Planet6 thermograph0)
    (take_image instrument6 Planet6 thermograph1)
    (take_image instrument6 Planet6 thermograph2)
    (take_image instrument6 Planet7 image3)
    (take_image instrument6 Planet7 image4)
    (take_image instrument6 Planet7 thermograph0)
    (take_image instrument6 Planet7 thermograph1)
    (take_image instrument6 Planet7 thermograph2)
    (take_image instrument6 Planet8 image3)
    (take_image instrument6 Planet8 image4)
    (take_image instrument6 Planet8 thermograph0)
    (take_image instrument6 Planet8 thermograph1)
    (take_image instrument6 Planet8 thermograph2)
    (take_image instrument6 Planet9 image3)
    (take_image instrument6 Planet9 image4)
    (take_image instrument6 Planet9 thermograph0)
    (take_image instrument6 Planet9 thermograph1)
    (take_image instrument6 Planet9 thermograph2)
    (take_image instrument6 Star0 image3)
    (take_image instrument6 Star0 image4)
    (take_image instrument6 Star0 thermograph0)
    (take_image instrument6 Star0 thermograph1)
    (take_image instrument6 Star0 thermograph2)
    (take_image instrument6 Star1 image3)
    (take_image instrument6 Star1 image4)
    (take_image instrument6 Star1 thermograph0)
    (take_image instrument6 Star1 thermograph1)
    (take_image instrument6 Star1 thermograph2)
    (take_image instrument6 Star14 image3)
    (take_image instrument6 Star14 image4)
    (take_image instrument6 Star14 thermograph0)
    (take_image instrument6 Star14 thermograph1)
    (take_image instrument6 Star14 thermograph2)
    (take_image instrument6 Star19 image3)
    (take_image instrument6 Star19 image4)
    (take_image instrument6 Star19 thermograph0)
    (take_image instrument6 Star19 thermograph1)
    (take_image instrument6 Star19 thermograph2)
    (take_image instrument6 Star21 image3)
    (take_image instrument6 Star21 image4)
    (take_image instrument6 Star21 thermograph0)
    (take_image instrument6 Star21 thermograph1)
    (take_image instrument6 Star21 thermograph2)
    (take_image instrument6 Star22 image3)
    (take_image instrument6 Star22 image4)
    (take_image instrument6 Star22 thermograph0)
    (take_image instrument6 Star22 thermograph1)
    (take_image instrument6 Star22 thermograph2)
    (take_image instrument6 Star26 image3)
    (take_image instrument6 Star26 image4)
    (take_image instrument6 Star26 thermograph0)
    (take_image instrument6 Star26 thermograph1)
    (take_image instrument6 Star26 thermograph2)
    (take_image instrument6 Star4 image3)
    (take_image instrument6 Star4 image4)
    (take_image instrument6 Star4 thermograph0)
    (take_image instrument6 Star4 thermograph1)
    (take_image instrument6 Star4 thermograph2)
    (take_image instrument7 GroundStation2 image3)
    (take_image instrument7 GroundStation2 image4)
    (take_image instrument7 GroundStation2 thermograph0)
    (take_image instrument7 GroundStation2 thermograph1)
    (take_image instrument7 GroundStation2 thermograph2)
    (take_image instrument7 GroundStation3 image3)
    (take_image instrument7 GroundStation3 image4)
    (take_image instrument7 GroundStation3 thermograph0)
    (take_image instrument7 GroundStation3 thermograph1)
    (take_image instrument7 GroundStation3 thermograph2)
    (take_image instrument7 Phenomenon12 image3)
    (take_image instrument7 Phenomenon12 image4)
    (take_image instrument7 Phenomenon12 thermograph0)
    (take_image instrument7 Phenomenon12 thermograph1)
    (take_image instrument7 Phenomenon12 thermograph2)
    (take_image instrument7 Phenomenon18 image3)
    (take_image instrument7 Phenomenon18 image4)
    (take_image instrument7 Phenomenon18 thermograph0)
    (take_image instrument7 Phenomenon18 thermograph1)
    (take_image instrument7 Phenomenon18 thermograph2)
    (take_image instrument7 Phenomenon27 image3)
    (take_image instrument7 Phenomenon27 image4)
    (take_image instrument7 Phenomenon27 thermograph0)
    (take_image instrument7 Phenomenon27 thermograph1)
    (take_image instrument7 Phenomenon27 thermograph2)
    (take_image instrument7 Phenomenon5 image3)
    (take_image instrument7 Phenomenon5 image4)
    (take_image instrument7 Phenomenon5 thermograph0)
    (take_image instrument7 Phenomenon5 thermograph1)
    (take_image instrument7 Phenomenon5 thermograph2)
    (take_image instrument7 Planet10 image3)
    (take_image instrument7 Planet10 image4)
    (take_image instrument7 Planet10 thermograph0)
    (take_image instrument7 Planet10 thermograph1)
    (take_image instrument7 Planet10 thermograph2)
    (take_image instrument7 Planet11 image3)
    (take_image instrument7 Planet11 image4)
    (take_image instrument7 Planet11 thermograph0)
    (take_image instrument7 Planet11 thermograph1)
    (take_image instrument7 Planet11 thermograph2)
    (take_image instrument7 Planet13 image3)
    (take_image instrument7 Planet13 image4)
    (take_image instrument7 Planet13 thermograph0)
    (take_image instrument7 Planet13 thermograph1)
    (take_image instrument7 Planet13 thermograph2)
    (take_image instrument7 Planet15 image3)
    (take_image instrument7 Planet15 image4)
    (take_image instrument7 Planet15 thermograph0)
    (take_image instrument7 Planet15 thermograph1)
    (take_image instrument7 Planet15 thermograph2)
    (take_image instrument7 Planet16 image3)
    (take_image instrument7 Planet16 image4)
    (take_image instrument7 Planet16 thermograph0)
    (take_image instrument7 Planet16 thermograph1)
    (take_image instrument7 Planet16 thermograph2)
    (take_image instrument7 Planet17 image3)
    (take_image instrument7 Planet17 image4)
    (take_image instrument7 Planet17 thermograph0)
    (take_image instrument7 Planet17 thermograph1)
    (take_image instrument7 Planet17 thermograph2)
    (take_image instrument7 Planet20 image3)
    (take_image instrument7 Planet20 image4)
    (take_image instrument7 Planet20 thermograph0)
    (take_image instrument7 Planet20 thermograph1)
    (take_image instrument7 Planet20 thermograph2)
    (take_image instrument7 Planet23 image3)
    (take_image instrument7 Planet23 image4)
    (take_image instrument7 Planet23 thermograph0)
    (take_image instrument7 Planet23 thermograph1)
    (take_image instrument7 Planet23 thermograph2)
    (take_image instrument7 Planet24 image3)
    (take_image instrument7 Planet24 image4)
    (take_image instrument7 Planet24 thermograph0)
    (take_image instrument7 Planet24 thermograph1)
    (take_image instrument7 Planet24 thermograph2)
    (take_image instrument7 Planet25 image3)
    (take_image instrument7 Planet25 image4)
    (take_image instrument7 Planet25 thermograph0)
    (take_image instrument7 Planet25 thermograph1)
    (take_image instrument7 Planet25 thermograph2)
    (take_image instrument7 Planet28 image3)
    (take_image instrument7 Planet28 image4)
    (take_image instrument7 Planet28 thermograph0)
    (take_image instrument7 Planet28 thermograph1)
    (take_image instrument7 Planet28 thermograph2)
    (take_image instrument7 Planet29 image3)
    (take_image instrument7 Planet29 image4)
    (take_image instrument7 Planet29 thermograph0)
    (take_image instrument7 Planet29 thermograph1)
    (take_image instrument7 Planet29 thermograph2)
    (take_image instrument7 Planet6 image3)
    (take_image instrument7 Planet6 image4)
    (take_image instrument7 Planet6 thermograph0)
    (take_image instrument7 Planet6 thermograph1)
    (take_image instrument7 Planet6 thermograph2)
    (take_image instrument7 Planet7 image3)
    (take_image instrument7 Planet7 image4)
    (take_image instrument7 Planet7 thermograph0)
    (take_image instrument7 Planet7 thermograph1)
    (take_image instrument7 Planet7 thermograph2)
    (take_image instrument7 Planet8 image3)
    (take_image instrument7 Planet8 image4)
    (take_image instrument7 Planet8 thermograph0)
    (take_image instrument7 Planet8 thermograph1)
    (take_image instrument7 Planet8 thermograph2)
    (take_image instrument7 Planet9 image3)
    (take_image instrument7 Planet9 image4)
    (take_image instrument7 Planet9 thermograph0)
    (take_image instrument7 Planet9 thermograph1)
    (take_image instrument7 Planet9 thermograph2)
    (take_image instrument7 Star0 image3)
    (take_image instrument7 Star0 image4)
    (take_image instrument7 Star0 thermograph0)
    (take_image instrument7 Star0 thermograph1)
    (take_image instrument7 Star0 thermograph2)
    (take_image instrument7 Star1 image3)
    (take_image instrument7 Star1 image4)
    (take_image instrument7 Star1 thermograph0)
    (take_image instrument7 Star1 thermograph1)
    (take_image instrument7 Star1 thermograph2)
    (take_image instrument7 Star14 image3)
    (take_image instrument7 Star14 image4)
    (take_image instrument7 Star14 thermograph0)
    (take_image instrument7 Star14 thermograph1)
    (take_image instrument7 Star14 thermograph2)
    (take_image instrument7 Star19 image3)
    (take_image instrument7 Star19 image4)
    (take_image instrument7 Star19 thermograph0)
    (take_image instrument7 Star19 thermograph1)
    (take_image instrument7 Star19 thermograph2)
    (take_image instrument7 Star21 image3)
    (take_image instrument7 Star21 image4)
    (take_image instrument7 Star21 thermograph0)
    (take_image instrument7 Star21 thermograph1)
    (take_image instrument7 Star21 thermograph2)
    (take_image instrument7 Star22 image3)
    (take_image instrument7 Star22 image4)
    (take_image instrument7 Star22 thermograph0)
    (take_image instrument7 Star22 thermograph1)
    (take_image instrument7 Star22 thermograph2)
    (take_image instrument7 Star26 image3)
    (take_image instrument7 Star26 image4)
    (take_image instrument7 Star26 thermograph0)
    (take_image instrument7 Star26 thermograph1)
    (take_image instrument7 Star26 thermograph2)
    (take_image instrument7 Star4 image3)
    (take_image instrument7 Star4 image4)
    (take_image instrument7 Star4 thermograph0)
    (take_image instrument7 Star4 thermograph1)
    (take_image instrument7 Star4 thermograph2)
    (take_image instrument8 GroundStation2 image3)
    (take_image instrument8 GroundStation2 image4)
    (take_image instrument8 GroundStation2 thermograph0)
    (take_image instrument8 GroundStation2 thermograph1)
    (take_image instrument8 GroundStation2 thermograph2)
    (take_image instrument8 GroundStation3 image3)
    (take_image instrument8 GroundStation3 image4)
    (take_image instrument8 GroundStation3 thermograph0)
    (take_image instrument8 GroundStation3 thermograph1)
    (take_image instrument8 GroundStation3 thermograph2)
    (take_image instrument8 Phenomenon12 image3)
    (take_image instrument8 Phenomenon12 image4)
    (take_image instrument8 Phenomenon12 thermograph0)
    (take_image instrument8 Phenomenon12 thermograph1)
    (take_image instrument8 Phenomenon12 thermograph2)
    (take_image instrument8 Phenomenon18 image3)
    (take_image instrument8 Phenomenon18 image4)
    (take_image instrument8 Phenomenon18 thermograph0)
    (take_image instrument8 Phenomenon18 thermograph1)
    (take_image instrument8 Phenomenon18 thermograph2)
    (take_image instrument8 Phenomenon27 image3)
    (take_image instrument8 Phenomenon27 image4)
    (take_image instrument8 Phenomenon27 thermograph0)
    (take_image instrument8 Phenomenon27 thermograph1)
    (take_image instrument8 Phenomenon27 thermograph2)
    (take_image instrument8 Phenomenon5 image3)
    (take_image instrument8 Phenomenon5 image4)
    (take_image instrument8 Phenomenon5 thermograph0)
    (take_image instrument8 Phenomenon5 thermograph1)
    (take_image instrument8 Phenomenon5 thermograph2)
    (take_image instrument8 Planet10 image3)
    (take_image instrument8 Planet10 image4)
    (take_image instrument8 Planet10 thermograph0)
    (take_image instrument8 Planet10 thermograph1)
    (take_image instrument8 Planet10 thermograph2)
    (take_image instrument8 Planet11 image3)
    (take_image instrument8 Planet11 image4)
    (take_image instrument8 Planet11 thermograph0)
    (take_image instrument8 Planet11 thermograph1)
    (take_image instrument8 Planet11 thermograph2)
    (take_image instrument8 Planet13 image3)
    (take_image instrument8 Planet13 image4)
    (take_image instrument8 Planet13 thermograph0)
    (take_image instrument8 Planet13 thermograph1)
    (take_image instrument8 Planet13 thermograph2)
    (take_image instrument8 Planet15 image3)
    (take_image instrument8 Planet15 image4)
    (take_image instrument8 Planet15 thermograph0)
    (take_image instrument8 Planet15 thermograph1)
    (take_image instrument8 Planet15 thermograph2)
    (take_image instrument8 Planet16 image3)
    (take_image instrument8 Planet16 image4)
    (take_image instrument8 Planet16 thermograph0)
    (take_image instrument8 Planet16 thermograph1)
    (take_image instrument8 Planet16 thermograph2)
    (take_image instrument8 Planet17 image3)
    (take_image instrument8 Planet17 image4)
    (take_image instrument8 Planet17 thermograph0)
    (take_image instrument8 Planet17 thermograph1)
    (take_image instrument8 Planet17 thermograph2)
    (take_image instrument8 Planet20 image3)
    (take_image instrument8 Planet20 image4)
    (take_image instrument8 Planet20 thermograph0)
    (take_image instrument8 Planet20 thermograph1)
    (take_image instrument8 Planet20 thermograph2)
    (take_image instrument8 Planet23 image3)
    (take_image instrument8 Planet23 image4)
    (take_image instrument8 Planet23 thermograph0)
    (take_image instrument8 Planet23 thermograph1)
    (take_image instrument8 Planet23 thermograph2)
    (take_image instrument8 Planet24 image3)
    (take_image instrument8 Planet24 image4)
    (take_image instrument8 Planet24 thermograph0)
    (take_image instrument8 Planet24 thermograph1)
    (take_image instrument8 Planet24 thermograph2)
    (take_image instrument8 Planet25 image3)
    (take_image instrument8 Planet25 image4)
    (take_image instrument8 Planet25 thermograph0)
    (take_image instrument8 Planet25 thermograph1)
    (take_image instrument8 Planet25 thermograph2)
    (take_image instrument8 Planet28 image3)
    (take_image instrument8 Planet28 image4)
    (take_image instrument8 Planet28 thermograph0)
    (take_image instrument8 Planet28 thermograph1)
    (take_image instrument8 Planet28 thermograph2)
    (take_image instrument8 Planet29 image3)
    (take_image instrument8 Planet29 image4)
    (take_image instrument8 Planet29 thermograph0)
    (take_image instrument8 Planet29 thermograph1)
    (take_image instrument8 Planet29 thermograph2)
    (take_image instrument8 Planet6 image3)
    (take_image instrument8 Planet6 image4)
    (take_image instrument8 Planet6 thermograph0)
    (take_image instrument8 Planet6 thermograph1)
    (take_image instrument8 Planet6 thermograph2)
    (take_image instrument8 Planet7 image3)
    (take_image instrument8 Planet7 image4)
    (take_image instrument8 Planet7 thermograph0)
    (take_image instrument8 Planet7 thermograph1)
    (take_image instrument8 Planet7 thermograph2)
    (take_image instrument8 Planet8 image3)
    (take_image instrument8 Planet8 image4)
    (take_image instrument8 Planet8 thermograph0)
    (take_image instrument8 Planet8 thermograph1)
    (take_image instrument8 Planet8 thermograph2)
    (take_image instrument8 Planet9 image3)
    (take_image instrument8 Planet9 image4)
    (take_image instrument8 Planet9 thermograph0)
    (take_image instrument8 Planet9 thermograph1)
    (take_image instrument8 Planet9 thermograph2)
    (take_image instrument8 Star0 image3)
    (take_image instrument8 Star0 image4)
    (take_image instrument8 Star0 thermograph0)
    (take_image instrument8 Star0 thermograph1)
    (take_image instrument8 Star0 thermograph2)
    (take_image instrument8 Star1 image3)
    (take_image instrument8 Star1 image4)
    (take_image instrument8 Star1 thermograph0)
    (take_image instrument8 Star1 thermograph1)
    (take_image instrument8 Star1 thermograph2)
    (take_image instrument8 Star14 image3)
    (take_image instrument8 Star14 image4)
    (take_image instrument8 Star14 thermograph0)
    (take_image instrument8 Star14 thermograph1)
    (take_image instrument8 Star14 thermograph2)
    (take_image instrument8 Star19 image3)
    (take_image instrument8 Star19 image4)
    (take_image instrument8 Star19 thermograph0)
    (take_image instrument8 Star19 thermograph1)
    (take_image instrument8 Star19 thermograph2)
    (take_image instrument8 Star21 image3)
    (take_image instrument8 Star21 image4)
    (take_image instrument8 Star21 thermograph0)
    (take_image instrument8 Star21 thermograph1)
    (take_image instrument8 Star21 thermograph2)
    (take_image instrument8 Star22 image3)
    (take_image instrument8 Star22 image4)
    (take_image instrument8 Star22 thermograph0)
    (take_image instrument8 Star22 thermograph1)
    (take_image instrument8 Star22 thermograph2)
    (take_image instrument8 Star26 image3)
    (take_image instrument8 Star26 image4)
    (take_image instrument8 Star26 thermograph0)
    (take_image instrument8 Star26 thermograph1)
    (take_image instrument8 Star26 thermograph2)
    (take_image instrument8 Star4 image3)
    (take_image instrument8 Star4 image4)
    (take_image instrument8 Star4 thermograph0)
    (take_image instrument8 Star4 thermograph1)
    (take_image instrument8 Star4 thermograph2)
    )
(:goal (and
	(pointing satellite1 Phenomenon5)
	(pointing satellite2 Planet11)
	(pointing satellite4 Planet11)
	(have_image Phenomenon5 thermograph1)
	(have_image Planet6 image4)
	(have_image Planet7 image3)
	(have_image Planet8 image3)
	(have_image Planet9 thermograph0)
	(have_image Planet10 thermograph1)
	(have_image Planet11 thermograph2)
	(have_image Phenomenon12 image3)
	(have_image Planet13 thermograph1)
	(have_image Star14 image3)
	(have_image Planet15 thermograph0)
	(have_image Planet16 image3)
	(have_image Planet17 image4)
	(have_image Phenomenon18 image3)
	(have_image Star19 thermograph0)
	(have_image Star21 thermograph1)
	(have_image Star22 image4)
	(have_image Planet23 thermograph1)
	(have_image Planet24 thermograph2)
	(have_image Planet25 thermograph1)
	(have_image Star26 thermograph0)
	(have_image Phenomenon27 thermograph1)
	(have_image Planet28 thermograph2)
	(have_image Planet29 thermograph0)
))

)
