; Problem taken from https://github.com/AI-Planning/classical-domains

(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0
	instrument0
	instrument1
	instrument2
	satellite1
	instrument3
	instrument4
	instrument5
	satellite2
	instrument6
	instrument7
	instrument8
	thermograph0
	image2
	spectrograph1
	GroundStation2
	GroundStation1
	GroundStation0
	Star3
	Star4
	Phenomenon5
	Phenomenon6
	Star7
	Phenomenon8
	Planet9
)
(:init
	(satellite satellite0)
	(instrument instrument0)
	(supports instrument0 image2)
	(supports instrument0 thermograph0)
	(supports instrument0 spectrograph1)
	(calibration_target instrument0 GroundStation2)
	(instrument instrument1)
	(supports instrument1 thermograph0)
	(supports instrument1 spectrograph1)
	(supports instrument1 image2)
	(calibration_target instrument1 GroundStation1)
	(instrument instrument2)
	(supports instrument2 image2)
	(calibration_target instrument2 GroundStation0)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Phenomenon8)
	(satellite satellite1)
	(instrument instrument3)
	(supports instrument3 spectrograph1)
	(supports instrument3 thermograph0)
	(calibration_target instrument3 GroundStation0)
	(instrument instrument4)
	(supports instrument4 image2)
	(supports instrument4 spectrograph1)
	(calibration_target instrument4 GroundStation2)
	(instrument instrument5)
	(supports instrument5 image2)
	(supports instrument5 spectrograph1)
	(supports instrument5 thermograph0)
	(calibration_target instrument5 GroundStation1)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation2)
	(satellite satellite2)
	(instrument instrument6)
	(supports instrument6 image2)
	(calibration_target instrument6 GroundStation1)
	(instrument instrument7)
	(supports instrument7 image2)
	(supports instrument7 thermograph0)
	(calibration_target instrument7 GroundStation1)
	(instrument instrument8)
	(supports instrument8 spectrograph1)
	(supports instrument8 image2)
	(supports instrument8 thermograph0)
	(calibration_target instrument8 GroundStation0)
	(on_board instrument6 satellite2)
	(on_board instrument7 satellite2)
	(on_board instrument8 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Phenomenon5)
	(mode thermograph0)
	(mode image2)
	(mode spectrograph1)
	(direction GroundStation2)
	(direction GroundStation1)
	(direction GroundStation0)
	(direction Star3)
	(direction Star4)
	(direction Phenomenon5)
	(direction Phenomenon6)
	(direction Star7)
	(direction Phenomenon8)
	(direction Planet9)

    ; action literals
    (turn_to satellite0 GroundStation0)
    (turn_to satellite0 GroundStation1)
    (turn_to satellite0 GroundStation2)
    (turn_to satellite0 Phenomenon5)
    (turn_to satellite0 Phenomenon6)
    (turn_to satellite0 Phenomenon8)
    (turn_to satellite0 Planet9)
    (turn_to satellite0 Star3)
    (turn_to satellite0 Star4)
    (turn_to satellite0 Star7)
    (turn_to satellite1 GroundStation0)
    (turn_to satellite1 GroundStation1)
    (turn_to satellite1 GroundStation2)
    (turn_to satellite1 Phenomenon5)
    (turn_to satellite1 Phenomenon6)
    (turn_to satellite1 Phenomenon8)
    (turn_to satellite1 Planet9)
    (turn_to satellite1 Star3)
    (turn_to satellite1 Star4)
    (turn_to satellite1 Star7)
    (turn_to satellite2 GroundStation0)
    (turn_to satellite2 GroundStation1)
    (turn_to satellite2 GroundStation2)
    (turn_to satellite2 Phenomenon5)
    (turn_to satellite2 Phenomenon6)
    (turn_to satellite2 Phenomenon8)
    (turn_to satellite2 Planet9)
    (turn_to satellite2 Star3)
    (turn_to satellite2 Star4)
    (turn_to satellite2 Star7)
    (switch_on instrument0)
    (switch_off instrument0)
    (switch_on instrument1)
    (switch_off instrument1)
    (switch_on instrument2)
    (switch_off instrument2)
    (switch_on instrument3)
    (switch_off instrument3)
    (switch_on instrument4)
    (switch_off instrument4)
    (switch_on instrument5)
    (switch_off instrument5)
    (switch_on instrument6)
    (switch_off instrument6)
    (switch_on instrument7)
    (switch_off instrument7)
    (switch_on instrument8)
    (switch_off instrument8)
    (calibrate instrument0 GroundStation0)
    (calibrate instrument0 GroundStation1)
    (calibrate instrument0 GroundStation2)
    (calibrate instrument0 Phenomenon5)
    (calibrate instrument0 Phenomenon6)
    (calibrate instrument0 Phenomenon8)
    (calibrate instrument0 Planet9)
    (calibrate instrument0 Star3)
    (calibrate instrument0 Star4)
    (calibrate instrument0 Star7)
    (calibrate instrument1 GroundStation0)
    (calibrate instrument1 GroundStation1)
    (calibrate instrument1 GroundStation2)
    (calibrate instrument1 Phenomenon5)
    (calibrate instrument1 Phenomenon6)
    (calibrate instrument1 Phenomenon8)
    (calibrate instrument1 Planet9)
    (calibrate instrument1 Star3)
    (calibrate instrument1 Star4)
    (calibrate instrument1 Star7)
    (calibrate instrument2 GroundStation0)
    (calibrate instrument2 GroundStation1)
    (calibrate instrument2 GroundStation2)
    (calibrate instrument2 Phenomenon5)
    (calibrate instrument2 Phenomenon6)
    (calibrate instrument2 Phenomenon8)
    (calibrate instrument2 Planet9)
    (calibrate instrument2 Star3)
    (calibrate instrument2 Star4)
    (calibrate instrument2 Star7)
    (calibrate instrument3 GroundStation0)
    (calibrate instrument3 GroundStation1)
    (calibrate instrument3 GroundStation2)
    (calibrate instrument3 Phenomenon5)
    (calibrate instrument3 Phenomenon6)
    (calibrate instrument3 Phenomenon8)
    (calibrate instrument3 Planet9)
    (calibrate instrument3 Star3)
    (calibrate instrument3 Star4)
    (calibrate instrument3 Star7)
    (calibrate instrument4 GroundStation0)
    (calibrate instrument4 GroundStation1)
    (calibrate instrument4 GroundStation2)
    (calibrate instrument4 Phenomenon5)
    (calibrate instrument4 Phenomenon6)
    (calibrate instrument4 Phenomenon8)
    (calibrate instrument4 Planet9)
    (calibrate instrument4 Star3)
    (calibrate instrument4 Star4)
    (calibrate instrument4 Star7)
    (calibrate instrument5 GroundStation0)
    (calibrate instrument5 GroundStation1)
    (calibrate instrument5 GroundStation2)
    (calibrate instrument5 Phenomenon5)
    (calibrate instrument5 Phenomenon6)
    (calibrate instrument5 Phenomenon8)
    (calibrate instrument5 Planet9)
    (calibrate instrument5 Star3)
    (calibrate instrument5 Star4)
    (calibrate instrument5 Star7)
    (calibrate instrument6 GroundStation0)
    (calibrate instrument6 GroundStation1)
    (calibrate instrument6 GroundStation2)
    (calibrate instrument6 Phenomenon5)
    (calibrate instrument6 Phenomenon6)
    (calibrate instrument6 Phenomenon8)
    (calibrate instrument6 Planet9)
    (calibrate instrument6 Star3)
    (calibrate instrument6 Star4)
    (calibrate instrument6 Star7)
    (calibrate instrument7 GroundStation0)
    (calibrate instrument7 GroundStation1)
    (calibrate instrument7 GroundStation2)
    (calibrate instrument7 Phenomenon5)
    (calibrate instrument7 Phenomenon6)
    (calibrate instrument7 Phenomenon8)
    (calibrate instrument7 Planet9)
    (calibrate instrument7 Star3)
    (calibrate instrument7 Star4)
    (calibrate instrument7 Star7)
    (calibrate instrument8 GroundStation0)
    (calibrate instrument8 GroundStation1)
    (calibrate instrument8 GroundStation2)
    (calibrate instrument8 Phenomenon5)
    (calibrate instrument8 Phenomenon6)
    (calibrate instrument8 Phenomenon8)
    (calibrate instrument8 Planet9)
    (calibrate instrument8 Star3)
    (calibrate instrument8 Star4)
    (calibrate instrument8 Star7)
    (take_image instrument0 GroundStation0 image2)
    (take_image instrument0 GroundStation0 spectrograph1)
    (take_image instrument0 GroundStation0 thermograph0)
    (take_image instrument0 GroundStation1 image2)
    (take_image instrument0 GroundStation1 spectrograph1)
    (take_image instrument0 GroundStation1 thermograph0)
    (take_image instrument0 GroundStation2 image2)
    (take_image instrument0 GroundStation2 spectrograph1)
    (take_image instrument0 GroundStation2 thermograph0)
    (take_image instrument0 Phenomenon5 image2)
    (take_image instrument0 Phenomenon5 spectrograph1)
    (take_image instrument0 Phenomenon5 thermograph0)
    (take_image instrument0 Phenomenon6 image2)
    (take_image instrument0 Phenomenon6 spectrograph1)
    (take_image instrument0 Phenomenon6 thermograph0)
    (take_image instrument0 Phenomenon8 image2)
    (take_image instrument0 Phenomenon8 spectrograph1)
    (take_image instrument0 Phenomenon8 thermograph0)
    (take_image instrument0 Planet9 image2)
    (take_image instrument0 Planet9 spectrograph1)
    (take_image instrument0 Planet9 thermograph0)
    (take_image instrument0 Star3 image2)
    (take_image instrument0 Star3 spectrograph1)
    (take_image instrument0 Star3 thermograph0)
    (take_image instrument0 Star4 image2)
    (take_image instrument0 Star4 spectrograph1)
    (take_image instrument0 Star4 thermograph0)
    (take_image instrument0 Star7 image2)
    (take_image instrument0 Star7 spectrograph1)
    (take_image instrument0 Star7 thermograph0)
    (take_image instrument1 GroundStation0 image2)
    (take_image instrument1 GroundStation0 spectrograph1)
    (take_image instrument1 GroundStation0 thermograph0)
    (take_image instrument1 GroundStation1 image2)
    (take_image instrument1 GroundStation1 spectrograph1)
    (take_image instrument1 GroundStation1 thermograph0)
    (take_image instrument1 GroundStation2 image2)
    (take_image instrument1 GroundStation2 spectrograph1)
    (take_image instrument1 GroundStation2 thermograph0)
    (take_image instrument1 Phenomenon5 image2)
    (take_image instrument1 Phenomenon5 spectrograph1)
    (take_image instrument1 Phenomenon5 thermograph0)
    (take_image instrument1 Phenomenon6 image2)
    (take_image instrument1 Phenomenon6 spectrograph1)
    (take_image instrument1 Phenomenon6 thermograph0)
    (take_image instrument1 Phenomenon8 image2)
    (take_image instrument1 Phenomenon8 spectrograph1)
    (take_image instrument1 Phenomenon8 thermograph0)
    (take_image instrument1 Planet9 image2)
    (take_image instrument1 Planet9 spectrograph1)
    (take_image instrument1 Planet9 thermograph0)
    (take_image instrument1 Star3 image2)
    (take_image instrument1 Star3 spectrograph1)
    (take_image instrument1 Star3 thermograph0)
    (take_image instrument1 Star4 image2)
    (take_image instrument1 Star4 spectrograph1)
    (take_image instrument1 Star4 thermograph0)
    (take_image instrument1 Star7 image2)
    (take_image instrument1 Star7 spectrograph1)
    (take_image instrument1 Star7 thermograph0)
    (take_image instrument2 GroundStation0 image2)
    (take_image instrument2 GroundStation0 spectrograph1)
    (take_image instrument2 GroundStation0 thermograph0)
    (take_image instrument2 GroundStation1 image2)
    (take_image instrument2 GroundStation1 spectrograph1)
    (take_image instrument2 GroundStation1 thermograph0)
    (take_image instrument2 GroundStation2 image2)
    (take_image instrument2 GroundStation2 spectrograph1)
    (take_image instrument2 GroundStation2 thermograph0)
    (take_image instrument2 Phenomenon5 image2)
    (take_image instrument2 Phenomenon5 spectrograph1)
    (take_image instrument2 Phenomenon5 thermograph0)
    (take_image instrument2 Phenomenon6 image2)
    (take_image instrument2 Phenomenon6 spectrograph1)
    (take_image instrument2 Phenomenon6 thermograph0)
    (take_image instrument2 Phenomenon8 image2)
    (take_image instrument2 Phenomenon8 spectrograph1)
    (take_image instrument2 Phenomenon8 thermograph0)
    (take_image instrument2 Planet9 image2)
    (take_image instrument2 Planet9 spectrograph1)
    (take_image instrument2 Planet9 thermograph0)
    (take_image instrument2 Star3 image2)
    (take_image instrument2 Star3 spectrograph1)
    (take_image instrument2 Star3 thermograph0)
    (take_image instrument2 Star4 image2)
    (take_image instrument2 Star4 spectrograph1)
    (take_image instrument2 Star4 thermograph0)
    (take_image instrument2 Star7 image2)
    (take_image instrument2 Star7 spectrograph1)
    (take_image instrument2 Star7 thermograph0)
    (take_image instrument3 GroundStation0 image2)
    (take_image instrument3 GroundStation0 spectrograph1)
    (take_image instrument3 GroundStation0 thermograph0)
    (take_image instrument3 GroundStation1 image2)
    (take_image instrument3 GroundStation1 spectrograph1)
    (take_image instrument3 GroundStation1 thermograph0)
    (take_image instrument3 GroundStation2 image2)
    (take_image instrument3 GroundStation2 spectrograph1)
    (take_image instrument3 GroundStation2 thermograph0)
    (take_image instrument3 Phenomenon5 image2)
    (take_image instrument3 Phenomenon5 spectrograph1)
    (take_image instrument3 Phenomenon5 thermograph0)
    (take_image instrument3 Phenomenon6 image2)
    (take_image instrument3 Phenomenon6 spectrograph1)
    (take_image instrument3 Phenomenon6 thermograph0)
    (take_image instrument3 Phenomenon8 image2)
    (take_image instrument3 Phenomenon8 spectrograph1)
    (take_image instrument3 Phenomenon8 thermograph0)
    (take_image instrument3 Planet9 image2)
    (take_image instrument3 Planet9 spectrograph1)
    (take_image instrument3 Planet9 thermograph0)
    (take_image instrument3 Star3 image2)
    (take_image instrument3 Star3 spectrograph1)
    (take_image instrument3 Star3 thermograph0)
    (take_image instrument3 Star4 image2)
    (take_image instrument3 Star4 spectrograph1)
    (take_image instrument3 Star4 thermograph0)
    (take_image instrument3 Star7 image2)
    (take_image instrument3 Star7 spectrograph1)
    (take_image instrument3 Star7 thermograph0)
    (take_image instrument4 GroundStation0 image2)
    (take_image instrument4 GroundStation0 spectrograph1)
    (take_image instrument4 GroundStation0 thermograph0)
    (take_image instrument4 GroundStation1 image2)
    (take_image instrument4 GroundStation1 spectrograph1)
    (take_image instrument4 GroundStation1 thermograph0)
    (take_image instrument4 GroundStation2 image2)
    (take_image instrument4 GroundStation2 spectrograph1)
    (take_image instrument4 GroundStation2 thermograph0)
    (take_image instrument4 Phenomenon5 image2)
    (take_image instrument4 Phenomenon5 spectrograph1)
    (take_image instrument4 Phenomenon5 thermograph0)
    (take_image instrument4 Phenomenon6 image2)
    (take_image instrument4 Phenomenon6 spectrograph1)
    (take_image instrument4 Phenomenon6 thermograph0)
    (take_image instrument4 Phenomenon8 image2)
    (take_image instrument4 Phenomenon8 spectrograph1)
    (take_image instrument4 Phenomenon8 thermograph0)
    (take_image instrument4 Planet9 image2)
    (take_image instrument4 Planet9 spectrograph1)
    (take_image instrument4 Planet9 thermograph0)
    (take_image instrument4 Star3 image2)
    (take_image instrument4 Star3 spectrograph1)
    (take_image instrument4 Star3 thermograph0)
    (take_image instrument4 Star4 image2)
    (take_image instrument4 Star4 spectrograph1)
    (take_image instrument4 Star4 thermograph0)
    (take_image instrument4 Star7 image2)
    (take_image instrument4 Star7 spectrograph1)
    (take_image instrument4 Star7 thermograph0)
    (take_image instrument5 GroundStation0 image2)
    (take_image instrument5 GroundStation0 spectrograph1)
    (take_image instrument5 GroundStation0 thermograph0)
    (take_image instrument5 GroundStation1 image2)
    (take_image instrument5 GroundStation1 spectrograph1)
    (take_image instrument5 GroundStation1 thermograph0)
    (take_image instrument5 GroundStation2 image2)
    (take_image instrument5 GroundStation2 spectrograph1)
    (take_image instrument5 GroundStation2 thermograph0)
    (take_image instrument5 Phenomenon5 image2)
    (take_image instrument5 Phenomenon5 spectrograph1)
    (take_image instrument5 Phenomenon5 thermograph0)
    (take_image instrument5 Phenomenon6 image2)
    (take_image instrument5 Phenomenon6 spectrograph1)
    (take_image instrument5 Phenomenon6 thermograph0)
    (take_image instrument5 Phenomenon8 image2)
    (take_image instrument5 Phenomenon8 spectrograph1)
    (take_image instrument5 Phenomenon8 thermograph0)
    (take_image instrument5 Planet9 image2)
    (take_image instrument5 Planet9 spectrograph1)
    (take_image instrument5 Planet9 thermograph0)
    (take_image instrument5 Star3 image2)
    (take_image instrument5 Star3 spectrograph1)
    (take_image instrument5 Star3 thermograph0)
    (take_image instrument5 Star4 image2)
    (take_image instrument5 Star4 spectrograph1)
    (take_image instrument5 Star4 thermograph0)
    (take_image instrument5 Star7 image2)
    (take_image instrument5 Star7 spectrograph1)
    (take_image instrument5 Star7 thermograph0)
    (take_image instrument6 GroundStation0 image2)
    (take_image instrument6 GroundStation0 spectrograph1)
    (take_image instrument6 GroundStation0 thermograph0)
    (take_image instrument6 GroundStation1 image2)
    (take_image instrument6 GroundStation1 spectrograph1)
    (take_image instrument6 GroundStation1 thermograph0)
    (take_image instrument6 GroundStation2 image2)
    (take_image instrument6 GroundStation2 spectrograph1)
    (take_image instrument6 GroundStation2 thermograph0)
    (take_image instrument6 Phenomenon5 image2)
    (take_image instrument6 Phenomenon5 spectrograph1)
    (take_image instrument6 Phenomenon5 thermograph0)
    (take_image instrument6 Phenomenon6 image2)
    (take_image instrument6 Phenomenon6 spectrograph1)
    (take_image instrument6 Phenomenon6 thermograph0)
    (take_image instrument6 Phenomenon8 image2)
    (take_image instrument6 Phenomenon8 spectrograph1)
    (take_image instrument6 Phenomenon8 thermograph0)
    (take_image instrument6 Planet9 image2)
    (take_image instrument6 Planet9 spectrograph1)
    (take_image instrument6 Planet9 thermograph0)
    (take_image instrument6 Star3 image2)
    (take_image instrument6 Star3 spectrograph1)
    (take_image instrument6 Star3 thermograph0)
    (take_image instrument6 Star4 image2)
    (take_image instrument6 Star4 spectrograph1)
    (take_image instrument6 Star4 thermograph0)
    (take_image instrument6 Star7 image2)
    (take_image instrument6 Star7 spectrograph1)
    (take_image instrument6 Star7 thermograph0)
    (take_image instrument7 GroundStation0 image2)
    (take_image instrument7 GroundStation0 spectrograph1)
    (take_image instrument7 GroundStation0 thermograph0)
    (take_image instrument7 GroundStation1 image2)
    (take_image instrument7 GroundStation1 spectrograph1)
    (take_image instrument7 GroundStation1 thermograph0)
    (take_image instrument7 GroundStation2 image2)
    (take_image instrument7 GroundStation2 spectrograph1)
    (take_image instrument7 GroundStation2 thermograph0)
    (take_image instrument7 Phenomenon5 image2)
    (take_image instrument7 Phenomenon5 spectrograph1)
    (take_image instrument7 Phenomenon5 thermograph0)
    (take_image instrument7 Phenomenon6 image2)
    (take_image instrument7 Phenomenon6 spectrograph1)
    (take_image instrument7 Phenomenon6 thermograph0)
    (take_image instrument7 Phenomenon8 image2)
    (take_image instrument7 Phenomenon8 spectrograph1)
    (take_image instrument7 Phenomenon8 thermograph0)
    (take_image instrument7 Planet9 image2)
    (take_image instrument7 Planet9 spectrograph1)
    (take_image instrument7 Planet9 thermograph0)
    (take_image instrument7 Star3 image2)
    (take_image instrument7 Star3 spectrograph1)
    (take_image instrument7 Star3 thermograph0)
    (take_image instrument7 Star4 image2)
    (take_image instrument7 Star4 spectrograph1)
    (take_image instrument7 Star4 thermograph0)
    (take_image instrument7 Star7 image2)
    (take_image instrument7 Star7 spectrograph1)
    (take_image instrument7 Star7 thermograph0)
    (take_image instrument8 GroundStation0 image2)
    (take_image instrument8 GroundStation0 spectrograph1)
    (take_image instrument8 GroundStation0 thermograph0)
    (take_image instrument8 GroundStation1 image2)
    (take_image instrument8 GroundStation1 spectrograph1)
    (take_image instrument8 GroundStation1 thermograph0)
    (take_image instrument8 GroundStation2 image2)
    (take_image instrument8 GroundStation2 spectrograph1)
    (take_image instrument8 GroundStation2 thermograph0)
    (take_image instrument8 Phenomenon5 image2)
    (take_image instrument8 Phenomenon5 spectrograph1)
    (take_image instrument8 Phenomenon5 thermograph0)
    (take_image instrument8 Phenomenon6 image2)
    (take_image instrument8 Phenomenon6 spectrograph1)
    (take_image instrument8 Phenomenon6 thermograph0)
    (take_image instrument8 Phenomenon8 image2)
    (take_image instrument8 Phenomenon8 spectrograph1)
    (take_image instrument8 Phenomenon8 thermograph0)
    (take_image instrument8 Planet9 image2)
    (take_image instrument8 Planet9 spectrograph1)
    (take_image instrument8 Planet9 thermograph0)
    (take_image instrument8 Star3 image2)
    (take_image instrument8 Star3 spectrograph1)
    (take_image instrument8 Star3 thermograph0)
    (take_image instrument8 Star4 image2)
    (take_image instrument8 Star4 spectrograph1)
    (take_image instrument8 Star4 thermograph0)
    (take_image instrument8 Star7 image2)
    (take_image instrument8 Star7 spectrograph1)
    (take_image instrument8 Star7 thermograph0)
    )
(:goal (and
	(pointing satellite0 Phenomenon5)
	(pointing satellite1 GroundStation2)
	(have_image Star3 thermograph0)
	(have_image Phenomenon5 image2)
	(have_image Phenomenon6 image2)
	(have_image Star7 thermograph0)
	(have_image Phenomenon8 image2)
	(have_image Planet9 spectrograph1)
))

)
