; Problem taken from https://github.com/AI-Planning/classical-domains

(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0
	instrument0
	instrument1
	instrument2
	satellite1
	instrument3
	instrument4
	instrument5
	satellite2
	instrument6
	instrument7
	satellite3
	instrument8
	instrument9
	thermograph2
	image0
	thermograph1
	spectrograph3
	Star2
	GroundStation1
	Star0
	Star3
	Star4
	Phenomenon5
	Star6
	Star7
	Phenomenon8
	Phenomenon9
	Star10
	Planet11
	Phenomenon12
	Phenomenon13
	Phenomenon14
)
(:init
	(satellite satellite0)
	(instrument instrument0)
	(supports instrument0 thermograph1)
	(supports instrument0 image0)
	(calibration_target instrument0 Star3)
	(instrument instrument1)
	(supports instrument1 spectrograph3)
	(supports instrument1 thermograph2)
	(supports instrument1 thermograph1)
	(calibration_target instrument1 Star2)
	(instrument instrument2)
	(supports instrument2 spectrograph3)
	(calibration_target instrument2 Star4)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Phenomenon14)
	(satellite satellite1)
	(instrument instrument3)
	(supports instrument3 thermograph2)
	(supports instrument3 image0)
	(calibration_target instrument3 GroundStation1)
	(instrument instrument4)
	(supports instrument4 thermograph1)
	(calibration_target instrument4 Star4)
	(instrument instrument5)
	(supports instrument5 thermograph2)
	(supports instrument5 thermograph1)
	(supports instrument5 spectrograph3)
	(calibration_target instrument5 Star0)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star4)
	(satellite satellite2)
	(instrument instrument6)
	(supports instrument6 thermograph1)
	(supports instrument6 thermograph2)
	(calibration_target instrument6 Star3)
	(instrument instrument7)
	(supports instrument7 thermograph2)
	(supports instrument7 thermograph1)
	(supports instrument7 image0)
	(calibration_target instrument7 Star0)
	(on_board instrument6 satellite2)
	(on_board instrument7 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star6)
	(satellite satellite3)
	(instrument instrument8)
	(supports instrument8 image0)
	(calibration_target instrument8 Star3)
	(instrument instrument9)
	(supports instrument9 spectrograph3)
	(supports instrument9 thermograph1)
	(supports instrument9 image0)
	(calibration_target instrument9 Star4)
	(on_board instrument8 satellite3)
	(on_board instrument9 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Phenomenon5)
	(mode thermograph2)
	(mode image0)
	(mode thermograph1)
	(mode spectrograph3)
	(direction Star2)
	(direction GroundStation1)
	(direction Star0)
	(direction Star3)
	(direction Star4)
	(direction Phenomenon5)
	(direction Star6)
	(direction Star7)
	(direction Phenomenon8)
	(direction Phenomenon9)
	(direction Star10)
	(direction Planet11)
	(direction Phenomenon12)
	(direction Phenomenon13)
	(direction Phenomenon14)

    ; action literals
    (turn_to satellite0 GroundStation1)
    (turn_to satellite0 Phenomenon12)
    (turn_to satellite0 Phenomenon13)
    (turn_to satellite0 Phenomenon14)
    (turn_to satellite0 Phenomenon5)
    (turn_to satellite0 Phenomenon8)
    (turn_to satellite0 Phenomenon9)
    (turn_to satellite0 Planet11)
    (turn_to satellite0 Star0)
    (turn_to satellite0 Star10)
    (turn_to satellite0 Star2)
    (turn_to satellite0 Star3)
    (turn_to satellite0 Star4)
    (turn_to satellite0 Star6)
    (turn_to satellite0 Star7)
    (turn_to satellite1 GroundStation1)
    (turn_to satellite1 Phenomenon12)
    (turn_to satellite1 Phenomenon13)
    (turn_to satellite1 Phenomenon14)
    (turn_to satellite1 Phenomenon5)
    (turn_to satellite1 Phenomenon8)
    (turn_to satellite1 Phenomenon9)
    (turn_to satellite1 Planet11)
    (turn_to satellite1 Star0)
    (turn_to satellite1 Star10)
    (turn_to satellite1 Star2)
    (turn_to satellite1 Star3)
    (turn_to satellite1 Star4)
    (turn_to satellite1 Star6)
    (turn_to satellite1 Star7)
    (turn_to satellite2 GroundStation1)
    (turn_to satellite2 Phenomenon12)
    (turn_to satellite2 Phenomenon13)
    (turn_to satellite2 Phenomenon14)
    (turn_to satellite2 Phenomenon5)
    (turn_to satellite2 Phenomenon8)
    (turn_to satellite2 Phenomenon9)
    (turn_to satellite2 Planet11)
    (turn_to satellite2 Star0)
    (turn_to satellite2 Star10)
    (turn_to satellite2 Star2)
    (turn_to satellite2 Star3)
    (turn_to satellite2 Star4)
    (turn_to satellite2 Star6)
    (turn_to satellite2 Star7)
    (turn_to satellite3 GroundStation1)
    (turn_to satellite3 Phenomenon12)
    (turn_to satellite3 Phenomenon13)
    (turn_to satellite3 Phenomenon14)
    (turn_to satellite3 Phenomenon5)
    (turn_to satellite3 Phenomenon8)
    (turn_to satellite3 Phenomenon9)
    (turn_to satellite3 Planet11)
    (turn_to satellite3 Star0)
    (turn_to satellite3 Star10)
    (turn_to satellite3 Star2)
    (turn_to satellite3 Star3)
    (turn_to satellite3 Star4)
    (turn_to satellite3 Star6)
    (turn_to satellite3 Star7)
    (switch_on instrument0)
    (switch_off instrument0)
    (switch_on instrument1)
    (switch_off instrument1)
    (switch_on instrument2)
    (switch_off instrument2)
    (switch_on instrument3)
    (switch_off instrument3)
    (switch_on instrument4)
    (switch_off instrument4)
    (switch_on instrument5)
    (switch_off instrument5)
    (switch_on instrument6)
    (switch_off instrument6)
    (switch_on instrument7)
    (switch_off instrument7)
    (switch_on instrument8)
    (switch_off instrument8)
    (switch_on instrument9)
    (switch_off instrument9)
    (calibrate instrument0 GroundStation1)
    (calibrate instrument0 Phenomenon12)
    (calibrate instrument0 Phenomenon13)
    (calibrate instrument0 Phenomenon14)
    (calibrate instrument0 Phenomenon5)
    (calibrate instrument0 Phenomenon8)
    (calibrate instrument0 Phenomenon9)
    (calibrate instrument0 Planet11)
    (calibrate instrument0 Star0)
    (calibrate instrument0 Star10)
    (calibrate instrument0 Star2)
    (calibrate instrument0 Star3)
    (calibrate instrument0 Star4)
    (calibrate instrument0 Star6)
    (calibrate instrument0 Star7)
    (calibrate instrument1 GroundStation1)
    (calibrate instrument1 Phenomenon12)
    (calibrate instrument1 Phenomenon13)
    (calibrate instrument1 Phenomenon14)
    (calibrate instrument1 Phenomenon5)
    (calibrate instrument1 Phenomenon8)
    (calibrate instrument1 Phenomenon9)
    (calibrate instrument1 Planet11)
    (calibrate instrument1 Star0)
    (calibrate instrument1 Star10)
    (calibrate instrument1 Star2)
    (calibrate instrument1 Star3)
    (calibrate instrument1 Star4)
    (calibrate instrument1 Star6)
    (calibrate instrument1 Star7)
    (calibrate instrument2 GroundStation1)
    (calibrate instrument2 Phenomenon12)
    (calibrate instrument2 Phenomenon13)
    (calibrate instrument2 Phenomenon14)
    (calibrate instrument2 Phenomenon5)
    (calibrate instrument2 Phenomenon8)
    (calibrate instrument2 Phenomenon9)
    (calibrate instrument2 Planet11)
    (calibrate instrument2 Star0)
    (calibrate instrument2 Star10)
    (calibrate instrument2 Star2)
    (calibrate instrument2 Star3)
    (calibrate instrument2 Star4)
    (calibrate instrument2 Star6)
    (calibrate instrument2 Star7)
    (calibrate instrument3 GroundStation1)
    (calibrate instrument3 Phenomenon12)
    (calibrate instrument3 Phenomenon13)
    (calibrate instrument3 Phenomenon14)
    (calibrate instrument3 Phenomenon5)
    (calibrate instrument3 Phenomenon8)
    (calibrate instrument3 Phenomenon9)
    (calibrate instrument3 Planet11)
    (calibrate instrument3 Star0)
    (calibrate instrument3 Star10)
    (calibrate instrument3 Star2)
    (calibrate instrument3 Star3)
    (calibrate instrument3 Star4)
    (calibrate instrument3 Star6)
    (calibrate instrument3 Star7)
    (calibrate instrument4 GroundStation1)
    (calibrate instrument4 Phenomenon12)
    (calibrate instrument4 Phenomenon13)
    (calibrate instrument4 Phenomenon14)
    (calibrate instrument4 Phenomenon5)
    (calibrate instrument4 Phenomenon8)
    (calibrate instrument4 Phenomenon9)
    (calibrate instrument4 Planet11)
    (calibrate instrument4 Star0)
    (calibrate instrument4 Star10)
    (calibrate instrument4 Star2)
    (calibrate instrument4 Star3)
    (calibrate instrument4 Star4)
    (calibrate instrument4 Star6)
    (calibrate instrument4 Star7)
    (calibrate instrument5 GroundStation1)
    (calibrate instrument5 Phenomenon12)
    (calibrate instrument5 Phenomenon13)
    (calibrate instrument5 Phenomenon14)
    (calibrate instrument5 Phenomenon5)
    (calibrate instrument5 Phenomenon8)
    (calibrate instrument5 Phenomenon9)
    (calibrate instrument5 Planet11)
    (calibrate instrument5 Star0)
    (calibrate instrument5 Star10)
    (calibrate instrument5 Star2)
    (calibrate instrument5 Star3)
    (calibrate instrument5 Star4)
    (calibrate instrument5 Star6)
    (calibrate instrument5 Star7)
    (calibrate instrument6 GroundStation1)
    (calibrate instrument6 Phenomenon12)
    (calibrate instrument6 Phenomenon13)
    (calibrate instrument6 Phenomenon14)
    (calibrate instrument6 Phenomenon5)
    (calibrate instrument6 Phenomenon8)
    (calibrate instrument6 Phenomenon9)
    (calibrate instrument6 Planet11)
    (calibrate instrument6 Star0)
    (calibrate instrument6 Star10)
    (calibrate instrument6 Star2)
    (calibrate instrument6 Star3)
    (calibrate instrument6 Star4)
    (calibrate instrument6 Star6)
    (calibrate instrument6 Star7)
    (calibrate instrument7 GroundStation1)
    (calibrate instrument7 Phenomenon12)
    (calibrate instrument7 Phenomenon13)
    (calibrate instrument7 Phenomenon14)
    (calibrate instrument7 Phenomenon5)
    (calibrate instrument7 Phenomenon8)
    (calibrate instrument7 Phenomenon9)
    (calibrate instrument7 Planet11)
    (calibrate instrument7 Star0)
    (calibrate instrument7 Star10)
    (calibrate instrument7 Star2)
    (calibrate instrument7 Star3)
    (calibrate instrument7 Star4)
    (calibrate instrument7 Star6)
    (calibrate instrument7 Star7)
    (calibrate instrument8 GroundStation1)
    (calibrate instrument8 Phenomenon12)
    (calibrate instrument8 Phenomenon13)
    (calibrate instrument8 Phenomenon14)
    (calibrate instrument8 Phenomenon5)
    (calibrate instrument8 Phenomenon8)
    (calibrate instrument8 Phenomenon9)
    (calibrate instrument8 Planet11)
    (calibrate instrument8 Star0)
    (calibrate instrument8 Star10)
    (calibrate instrument8 Star2)
    (calibrate instrument8 Star3)
    (calibrate instrument8 Star4)
    (calibrate instrument8 Star6)
    (calibrate instrument8 Star7)
    (calibrate instrument9 GroundStation1)
    (calibrate instrument9 Phenomenon12)
    (calibrate instrument9 Phenomenon13)
    (calibrate instrument9 Phenomenon14)
    (calibrate instrument9 Phenomenon5)
    (calibrate instrument9 Phenomenon8)
    (calibrate instrument9 Phenomenon9)
    (calibrate instrument9 Planet11)
    (calibrate instrument9 Star0)
    (calibrate instrument9 Star10)
    (calibrate instrument9 Star2)
    (calibrate instrument9 Star3)
    (calibrate instrument9 Star4)
    (calibrate instrument9 Star6)
    (calibrate instrument9 Star7)
    (take_image instrument0 GroundStation1 image0)
    (take_image instrument0 GroundStation1 spectrograph3)
    (take_image instrument0 GroundStation1 thermograph1)
    (take_image instrument0 GroundStation1 thermograph2)
    (take_image instrument0 Phenomenon12 image0)
    (take_image instrument0 Phenomenon12 spectrograph3)
    (take_image instrument0 Phenomenon12 thermograph1)
    (take_image instrument0 Phenomenon12 thermograph2)
    (take_image instrument0 Phenomenon13 image0)
    (take_image instrument0 Phenomenon13 spectrograph3)
    (take_image instrument0 Phenomenon13 thermograph1)
    (take_image instrument0 Phenomenon13 thermograph2)
    (take_image instrument0 Phenomenon14 image0)
    (take_image instrument0 Phenomenon14 spectrograph3)
    (take_image instrument0 Phenomenon14 thermograph1)
    (take_image instrument0 Phenomenon14 thermograph2)
    (take_image instrument0 Phenomenon5 image0)
    (take_image instrument0 Phenomenon5 spectrograph3)
    (take_image instrument0 Phenomenon5 thermograph1)
    (take_image instrument0 Phenomenon5 thermograph2)
    (take_image instrument0 Phenomenon8 image0)
    (take_image instrument0 Phenomenon8 spectrograph3)
    (take_image instrument0 Phenomenon8 thermograph1)
    (take_image instrument0 Phenomenon8 thermograph2)
    (take_image instrument0 Phenomenon9 image0)
    (take_image instrument0 Phenomenon9 spectrograph3)
    (take_image instrument0 Phenomenon9 thermograph1)
    (take_image instrument0 Phenomenon9 thermograph2)
    (take_image instrument0 Planet11 image0)
    (take_image instrument0 Planet11 spectrograph3)
    (take_image instrument0 Planet11 thermograph1)
    (take_image instrument0 Planet11 thermograph2)
    (take_image instrument0 Star0 image0)
    (take_image instrument0 Star0 spectrograph3)
    (take_image instrument0 Star0 thermograph1)
    (take_image instrument0 Star0 thermograph2)
    (take_image instrument0 Star10 image0)
    (take_image instrument0 Star10 spectrograph3)
    (take_image instrument0 Star10 thermograph1)
    (take_image instrument0 Star10 thermograph2)
    (take_image instrument0 Star2 image0)
    (take_image instrument0 Star2 spectrograph3)
    (take_image instrument0 Star2 thermograph1)
    (take_image instrument0 Star2 thermograph2)
    (take_image instrument0 Star3 image0)
    (take_image instrument0 Star3 spectrograph3)
    (take_image instrument0 Star3 thermograph1)
    (take_image instrument0 Star3 thermograph2)
    (take_image instrument0 Star4 image0)
    (take_image instrument0 Star4 spectrograph3)
    (take_image instrument0 Star4 thermograph1)
    (take_image instrument0 Star4 thermograph2)
    (take_image instrument0 Star6 image0)
    (take_image instrument0 Star6 spectrograph3)
    (take_image instrument0 Star6 thermograph1)
    (take_image instrument0 Star6 thermograph2)
    (take_image instrument0 Star7 image0)
    (take_image instrument0 Star7 spectrograph3)
    (take_image instrument0 Star7 thermograph1)
    (take_image instrument0 Star7 thermograph2)
    (take_image instrument1 GroundStation1 image0)
    (take_image instrument1 GroundStation1 spectrograph3)
    (take_image instrument1 GroundStation1 thermograph1)
    (take_image instrument1 GroundStation1 thermograph2)
    (take_image instrument1 Phenomenon12 image0)
    (take_image instrument1 Phenomenon12 spectrograph3)
    (take_image instrument1 Phenomenon12 thermograph1)
    (take_image instrument1 Phenomenon12 thermograph2)
    (take_image instrument1 Phenomenon13 image0)
    (take_image instrument1 Phenomenon13 spectrograph3)
    (take_image instrument1 Phenomenon13 thermograph1)
    (take_image instrument1 Phenomenon13 thermograph2)
    (take_image instrument1 Phenomenon14 image0)
    (take_image instrument1 Phenomenon14 spectrograph3)
    (take_image instrument1 Phenomenon14 thermograph1)
    (take_image instrument1 Phenomenon14 thermograph2)
    (take_image instrument1 Phenomenon5 image0)
    (take_image instrument1 Phenomenon5 spectrograph3)
    (take_image instrument1 Phenomenon5 thermograph1)
    (take_image instrument1 Phenomenon5 thermograph2)
    (take_image instrument1 Phenomenon8 image0)
    (take_image instrument1 Phenomenon8 spectrograph3)
    (take_image instrument1 Phenomenon8 thermograph1)
    (take_image instrument1 Phenomenon8 thermograph2)
    (take_image instrument1 Phenomenon9 image0)
    (take_image instrument1 Phenomenon9 spectrograph3)
    (take_image instrument1 Phenomenon9 thermograph1)
    (take_image instrument1 Phenomenon9 thermograph2)
    (take_image instrument1 Planet11 image0)
    (take_image instrument1 Planet11 spectrograph3)
    (take_image instrument1 Planet11 thermograph1)
    (take_image instrument1 Planet11 thermograph2)
    (take_image instrument1 Star0 image0)
    (take_image instrument1 Star0 spectrograph3)
    (take_image instrument1 Star0 thermograph1)
    (take_image instrument1 Star0 thermograph2)
    (take_image instrument1 Star10 image0)
    (take_image instrument1 Star10 spectrograph3)
    (take_image instrument1 Star10 thermograph1)
    (take_image instrument1 Star10 thermograph2)
    (take_image instrument1 Star2 image0)
    (take_image instrument1 Star2 spectrograph3)
    (take_image instrument1 Star2 thermograph1)
    (take_image instrument1 Star2 thermograph2)
    (take_image instrument1 Star3 image0)
    (take_image instrument1 Star3 spectrograph3)
    (take_image instrument1 Star3 thermograph1)
    (take_image instrument1 Star3 thermograph2)
    (take_image instrument1 Star4 image0)
    (take_image instrument1 Star4 spectrograph3)
    (take_image instrument1 Star4 thermograph1)
    (take_image instrument1 Star4 thermograph2)
    (take_image instrument1 Star6 image0)
    (take_image instrument1 Star6 spectrograph3)
    (take_image instrument1 Star6 thermograph1)
    (take_image instrument1 Star6 thermograph2)
    (take_image instrument1 Star7 image0)
    (take_image instrument1 Star7 spectrograph3)
    (take_image instrument1 Star7 thermograph1)
    (take_image instrument1 Star7 thermograph2)
    (take_image instrument2 GroundStation1 image0)
    (take_image instrument2 GroundStation1 spectrograph3)
    (take_image instrument2 GroundStation1 thermograph1)
    (take_image instrument2 GroundStation1 thermograph2)
    (take_image instrument2 Phenomenon12 image0)
    (take_image instrument2 Phenomenon12 spectrograph3)
    (take_image instrument2 Phenomenon12 thermograph1)
    (take_image instrument2 Phenomenon12 thermograph2)
    (take_image instrument2 Phenomenon13 image0)
    (take_image instrument2 Phenomenon13 spectrograph3)
    (take_image instrument2 Phenomenon13 thermograph1)
    (take_image instrument2 Phenomenon13 thermograph2)
    (take_image instrument2 Phenomenon14 image0)
    (take_image instrument2 Phenomenon14 spectrograph3)
    (take_image instrument2 Phenomenon14 thermograph1)
    (take_image instrument2 Phenomenon14 thermograph2)
    (take_image instrument2 Phenomenon5 image0)
    (take_image instrument2 Phenomenon5 spectrograph3)
    (take_image instrument2 Phenomenon5 thermograph1)
    (take_image instrument2 Phenomenon5 thermograph2)
    (take_image instrument2 Phenomenon8 image0)
    (take_image instrument2 Phenomenon8 spectrograph3)
    (take_image instrument2 Phenomenon8 thermograph1)
    (take_image instrument2 Phenomenon8 thermograph2)
    (take_image instrument2 Phenomenon9 image0)
    (take_image instrument2 Phenomenon9 spectrograph3)
    (take_image instrument2 Phenomenon9 thermograph1)
    (take_image instrument2 Phenomenon9 thermograph2)
    (take_image instrument2 Planet11 image0)
    (take_image instrument2 Planet11 spectrograph3)
    (take_image instrument2 Planet11 thermograph1)
    (take_image instrument2 Planet11 thermograph2)
    (take_image instrument2 Star0 image0)
    (take_image instrument2 Star0 spectrograph3)
    (take_image instrument2 Star0 thermograph1)
    (take_image instrument2 Star0 thermograph2)
    (take_image instrument2 Star10 image0)
    (take_image instrument2 Star10 spectrograph3)
    (take_image instrument2 Star10 thermograph1)
    (take_image instrument2 Star10 thermograph2)
    (take_image instrument2 Star2 image0)
    (take_image instrument2 Star2 spectrograph3)
    (take_image instrument2 Star2 thermograph1)
    (take_image instrument2 Star2 thermograph2)
    (take_image instrument2 Star3 image0)
    (take_image instrument2 Star3 spectrograph3)
    (take_image instrument2 Star3 thermograph1)
    (take_image instrument2 Star3 thermograph2)
    (take_image instrument2 Star4 image0)
    (take_image instrument2 Star4 spectrograph3)
    (take_image instrument2 Star4 thermograph1)
    (take_image instrument2 Star4 thermograph2)
    (take_image instrument2 Star6 image0)
    (take_image instrument2 Star6 spectrograph3)
    (take_image instrument2 Star6 thermograph1)
    (take_image instrument2 Star6 thermograph2)
    (take_image instrument2 Star7 image0)
    (take_image instrument2 Star7 spectrograph3)
    (take_image instrument2 Star7 thermograph1)
    (take_image instrument2 Star7 thermograph2)
    (take_image instrument3 GroundStation1 image0)
    (take_image instrument3 GroundStation1 spectrograph3)
    (take_image instrument3 GroundStation1 thermograph1)
    (take_image instrument3 GroundStation1 thermograph2)
    (take_image instrument3 Phenomenon12 image0)
    (take_image instrument3 Phenomenon12 spectrograph3)
    (take_image instrument3 Phenomenon12 thermograph1)
    (take_image instrument3 Phenomenon12 thermograph2)
    (take_image instrument3 Phenomenon13 image0)
    (take_image instrument3 Phenomenon13 spectrograph3)
    (take_image instrument3 Phenomenon13 thermograph1)
    (take_image instrument3 Phenomenon13 thermograph2)
    (take_image instrument3 Phenomenon14 image0)
    (take_image instrument3 Phenomenon14 spectrograph3)
    (take_image instrument3 Phenomenon14 thermograph1)
    (take_image instrument3 Phenomenon14 thermograph2)
    (take_image instrument3 Phenomenon5 image0)
    (take_image instrument3 Phenomenon5 spectrograph3)
    (take_image instrument3 Phenomenon5 thermograph1)
    (take_image instrument3 Phenomenon5 thermograph2)
    (take_image instrument3 Phenomenon8 image0)
    (take_image instrument3 Phenomenon8 spectrograph3)
    (take_image instrument3 Phenomenon8 thermograph1)
    (take_image instrument3 Phenomenon8 thermograph2)
    (take_image instrument3 Phenomenon9 image0)
    (take_image instrument3 Phenomenon9 spectrograph3)
    (take_image instrument3 Phenomenon9 thermograph1)
    (take_image instrument3 Phenomenon9 thermograph2)
    (take_image instrument3 Planet11 image0)
    (take_image instrument3 Planet11 spectrograph3)
    (take_image instrument3 Planet11 thermograph1)
    (take_image instrument3 Planet11 thermograph2)
    (take_image instrument3 Star0 image0)
    (take_image instrument3 Star0 spectrograph3)
    (take_image instrument3 Star0 thermograph1)
    (take_image instrument3 Star0 thermograph2)
    (take_image instrument3 Star10 image0)
    (take_image instrument3 Star10 spectrograph3)
    (take_image instrument3 Star10 thermograph1)
    (take_image instrument3 Star10 thermograph2)
    (take_image instrument3 Star2 image0)
    (take_image instrument3 Star2 spectrograph3)
    (take_image instrument3 Star2 thermograph1)
    (take_image instrument3 Star2 thermograph2)
    (take_image instrument3 Star3 image0)
    (take_image instrument3 Star3 spectrograph3)
    (take_image instrument3 Star3 thermograph1)
    (take_image instrument3 Star3 thermograph2)
    (take_image instrument3 Star4 image0)
    (take_image instrument3 Star4 spectrograph3)
    (take_image instrument3 Star4 thermograph1)
    (take_image instrument3 Star4 thermograph2)
    (take_image instrument3 Star6 image0)
    (take_image instrument3 Star6 spectrograph3)
    (take_image instrument3 Star6 thermograph1)
    (take_image instrument3 Star6 thermograph2)
    (take_image instrument3 Star7 image0)
    (take_image instrument3 Star7 spectrograph3)
    (take_image instrument3 Star7 thermograph1)
    (take_image instrument3 Star7 thermograph2)
    (take_image instrument4 GroundStation1 image0)
    (take_image instrument4 GroundStation1 spectrograph3)
    (take_image instrument4 GroundStation1 thermograph1)
    (take_image instrument4 GroundStation1 thermograph2)
    (take_image instrument4 Phenomenon12 image0)
    (take_image instrument4 Phenomenon12 spectrograph3)
    (take_image instrument4 Phenomenon12 thermograph1)
    (take_image instrument4 Phenomenon12 thermograph2)
    (take_image instrument4 Phenomenon13 image0)
    (take_image instrument4 Phenomenon13 spectrograph3)
    (take_image instrument4 Phenomenon13 thermograph1)
    (take_image instrument4 Phenomenon13 thermograph2)
    (take_image instrument4 Phenomenon14 image0)
    (take_image instrument4 Phenomenon14 spectrograph3)
    (take_image instrument4 Phenomenon14 thermograph1)
    (take_image instrument4 Phenomenon14 thermograph2)
    (take_image instrument4 Phenomenon5 image0)
    (take_image instrument4 Phenomenon5 spectrograph3)
    (take_image instrument4 Phenomenon5 thermograph1)
    (take_image instrument4 Phenomenon5 thermograph2)
    (take_image instrument4 Phenomenon8 image0)
    (take_image instrument4 Phenomenon8 spectrograph3)
    (take_image instrument4 Phenomenon8 thermograph1)
    (take_image instrument4 Phenomenon8 thermograph2)
    (take_image instrument4 Phenomenon9 image0)
    (take_image instrument4 Phenomenon9 spectrograph3)
    (take_image instrument4 Phenomenon9 thermograph1)
    (take_image instrument4 Phenomenon9 thermograph2)
    (take_image instrument4 Planet11 image0)
    (take_image instrument4 Planet11 spectrograph3)
    (take_image instrument4 Planet11 thermograph1)
    (take_image instrument4 Planet11 thermograph2)
    (take_image instrument4 Star0 image0)
    (take_image instrument4 Star0 spectrograph3)
    (take_image instrument4 Star0 thermograph1)
    (take_image instrument4 Star0 thermograph2)
    (take_image instrument4 Star10 image0)
    (take_image instrument4 Star10 spectrograph3)
    (take_image instrument4 Star10 thermograph1)
    (take_image instrument4 Star10 thermograph2)
    (take_image instrument4 Star2 image0)
    (take_image instrument4 Star2 spectrograph3)
    (take_image instrument4 Star2 thermograph1)
    (take_image instrument4 Star2 thermograph2)
    (take_image instrument4 Star3 image0)
    (take_image instrument4 Star3 spectrograph3)
    (take_image instrument4 Star3 thermograph1)
    (take_image instrument4 Star3 thermograph2)
    (take_image instrument4 Star4 image0)
    (take_image instrument4 Star4 spectrograph3)
    (take_image instrument4 Star4 thermograph1)
    (take_image instrument4 Star4 thermograph2)
    (take_image instrument4 Star6 image0)
    (take_image instrument4 Star6 spectrograph3)
    (take_image instrument4 Star6 thermograph1)
    (take_image instrument4 Star6 thermograph2)
    (take_image instrument4 Star7 image0)
    (take_image instrument4 Star7 spectrograph3)
    (take_image instrument4 Star7 thermograph1)
    (take_image instrument4 Star7 thermograph2)
    (take_image instrument5 GroundStation1 image0)
    (take_image instrument5 GroundStation1 spectrograph3)
    (take_image instrument5 GroundStation1 thermograph1)
    (take_image instrument5 GroundStation1 thermograph2)
    (take_image instrument5 Phenomenon12 image0)
    (take_image instrument5 Phenomenon12 spectrograph3)
    (take_image instrument5 Phenomenon12 thermograph1)
    (take_image instrument5 Phenomenon12 thermograph2)
    (take_image instrument5 Phenomenon13 image0)
    (take_image instrument5 Phenomenon13 spectrograph3)
    (take_image instrument5 Phenomenon13 thermograph1)
    (take_image instrument5 Phenomenon13 thermograph2)
    (take_image instrument5 Phenomenon14 image0)
    (take_image instrument5 Phenomenon14 spectrograph3)
    (take_image instrument5 Phenomenon14 thermograph1)
    (take_image instrument5 Phenomenon14 thermograph2)
    (take_image instrument5 Phenomenon5 image0)
    (take_image instrument5 Phenomenon5 spectrograph3)
    (take_image instrument5 Phenomenon5 thermograph1)
    (take_image instrument5 Phenomenon5 thermograph2)
    (take_image instrument5 Phenomenon8 image0)
    (take_image instrument5 Phenomenon8 spectrograph3)
    (take_image instrument5 Phenomenon8 thermograph1)
    (take_image instrument5 Phenomenon8 thermograph2)
    (take_image instrument5 Phenomenon9 image0)
    (take_image instrument5 Phenomenon9 spectrograph3)
    (take_image instrument5 Phenomenon9 thermograph1)
    (take_image instrument5 Phenomenon9 thermograph2)
    (take_image instrument5 Planet11 image0)
    (take_image instrument5 Planet11 spectrograph3)
    (take_image instrument5 Planet11 thermograph1)
    (take_image instrument5 Planet11 thermograph2)
    (take_image instrument5 Star0 image0)
    (take_image instrument5 Star0 spectrograph3)
    (take_image instrument5 Star0 thermograph1)
    (take_image instrument5 Star0 thermograph2)
    (take_image instrument5 Star10 image0)
    (take_image instrument5 Star10 spectrograph3)
    (take_image instrument5 Star10 thermograph1)
    (take_image instrument5 Star10 thermograph2)
    (take_image instrument5 Star2 image0)
    (take_image instrument5 Star2 spectrograph3)
    (take_image instrument5 Star2 thermograph1)
    (take_image instrument5 Star2 thermograph2)
    (take_image instrument5 Star3 image0)
    (take_image instrument5 Star3 spectrograph3)
    (take_image instrument5 Star3 thermograph1)
    (take_image instrument5 Star3 thermograph2)
    (take_image instrument5 Star4 image0)
    (take_image instrument5 Star4 spectrograph3)
    (take_image instrument5 Star4 thermograph1)
    (take_image instrument5 Star4 thermograph2)
    (take_image instrument5 Star6 image0)
    (take_image instrument5 Star6 spectrograph3)
    (take_image instrument5 Star6 thermograph1)
    (take_image instrument5 Star6 thermograph2)
    (take_image instrument5 Star7 image0)
    (take_image instrument5 Star7 spectrograph3)
    (take_image instrument5 Star7 thermograph1)
    (take_image instrument5 Star7 thermograph2)
    (take_image instrument6 GroundStation1 image0)
    (take_image instrument6 GroundStation1 spectrograph3)
    (take_image instrument6 GroundStation1 thermograph1)
    (take_image instrument6 GroundStation1 thermograph2)
    (take_image instrument6 Phenomenon12 image0)
    (take_image instrument6 Phenomenon12 spectrograph3)
    (take_image instrument6 Phenomenon12 thermograph1)
    (take_image instrument6 Phenomenon12 thermograph2)
    (take_image instrument6 Phenomenon13 image0)
    (take_image instrument6 Phenomenon13 spectrograph3)
    (take_image instrument6 Phenomenon13 thermograph1)
    (take_image instrument6 Phenomenon13 thermograph2)
    (take_image instrument6 Phenomenon14 image0)
    (take_image instrument6 Phenomenon14 spectrograph3)
    (take_image instrument6 Phenomenon14 thermograph1)
    (take_image instrument6 Phenomenon14 thermograph2)
    (take_image instrument6 Phenomenon5 image0)
    (take_image instrument6 Phenomenon5 spectrograph3)
    (take_image instrument6 Phenomenon5 thermograph1)
    (take_image instrument6 Phenomenon5 thermograph2)
    (take_image instrument6 Phenomenon8 image0)
    (take_image instrument6 Phenomenon8 spectrograph3)
    (take_image instrument6 Phenomenon8 thermograph1)
    (take_image instrument6 Phenomenon8 thermograph2)
    (take_image instrument6 Phenomenon9 image0)
    (take_image instrument6 Phenomenon9 spectrograph3)
    (take_image instrument6 Phenomenon9 thermograph1)
    (take_image instrument6 Phenomenon9 thermograph2)
    (take_image instrument6 Planet11 image0)
    (take_image instrument6 Planet11 spectrograph3)
    (take_image instrument6 Planet11 thermograph1)
    (take_image instrument6 Planet11 thermograph2)
    (take_image instrument6 Star0 image0)
    (take_image instrument6 Star0 spectrograph3)
    (take_image instrument6 Star0 thermograph1)
    (take_image instrument6 Star0 thermograph2)
    (take_image instrument6 Star10 image0)
    (take_image instrument6 Star10 spectrograph3)
    (take_image instrument6 Star10 thermograph1)
    (take_image instrument6 Star10 thermograph2)
    (take_image instrument6 Star2 image0)
    (take_image instrument6 Star2 spectrograph3)
    (take_image instrument6 Star2 thermograph1)
    (take_image instrument6 Star2 thermograph2)
    (take_image instrument6 Star3 image0)
    (take_image instrument6 Star3 spectrograph3)
    (take_image instrument6 Star3 thermograph1)
    (take_image instrument6 Star3 thermograph2)
    (take_image instrument6 Star4 image0)
    (take_image instrument6 Star4 spectrograph3)
    (take_image instrument6 Star4 thermograph1)
    (take_image instrument6 Star4 thermograph2)
    (take_image instrument6 Star6 image0)
    (take_image instrument6 Star6 spectrograph3)
    (take_image instrument6 Star6 thermograph1)
    (take_image instrument6 Star6 thermograph2)
    (take_image instrument6 Star7 image0)
    (take_image instrument6 Star7 spectrograph3)
    (take_image instrument6 Star7 thermograph1)
    (take_image instrument6 Star7 thermograph2)
    (take_image instrument7 GroundStation1 image0)
    (take_image instrument7 GroundStation1 spectrograph3)
    (take_image instrument7 GroundStation1 thermograph1)
    (take_image instrument7 GroundStation1 thermograph2)
    (take_image instrument7 Phenomenon12 image0)
    (take_image instrument7 Phenomenon12 spectrograph3)
    (take_image instrument7 Phenomenon12 thermograph1)
    (take_image instrument7 Phenomenon12 thermograph2)
    (take_image instrument7 Phenomenon13 image0)
    (take_image instrument7 Phenomenon13 spectrograph3)
    (take_image instrument7 Phenomenon13 thermograph1)
    (take_image instrument7 Phenomenon13 thermograph2)
    (take_image instrument7 Phenomenon14 image0)
    (take_image instrument7 Phenomenon14 spectrograph3)
    (take_image instrument7 Phenomenon14 thermograph1)
    (take_image instrument7 Phenomenon14 thermograph2)
    (take_image instrument7 Phenomenon5 image0)
    (take_image instrument7 Phenomenon5 spectrograph3)
    (take_image instrument7 Phenomenon5 thermograph1)
    (take_image instrument7 Phenomenon5 thermograph2)
    (take_image instrument7 Phenomenon8 image0)
    (take_image instrument7 Phenomenon8 spectrograph3)
    (take_image instrument7 Phenomenon8 thermograph1)
    (take_image instrument7 Phenomenon8 thermograph2)
    (take_image instrument7 Phenomenon9 image0)
    (take_image instrument7 Phenomenon9 spectrograph3)
    (take_image instrument7 Phenomenon9 thermograph1)
    (take_image instrument7 Phenomenon9 thermograph2)
    (take_image instrument7 Planet11 image0)
    (take_image instrument7 Planet11 spectrograph3)
    (take_image instrument7 Planet11 thermograph1)
    (take_image instrument7 Planet11 thermograph2)
    (take_image instrument7 Star0 image0)
    (take_image instrument7 Star0 spectrograph3)
    (take_image instrument7 Star0 thermograph1)
    (take_image instrument7 Star0 thermograph2)
    (take_image instrument7 Star10 image0)
    (take_image instrument7 Star10 spectrograph3)
    (take_image instrument7 Star10 thermograph1)
    (take_image instrument7 Star10 thermograph2)
    (take_image instrument7 Star2 image0)
    (take_image instrument7 Star2 spectrograph3)
    (take_image instrument7 Star2 thermograph1)
    (take_image instrument7 Star2 thermograph2)
    (take_image instrument7 Star3 image0)
    (take_image instrument7 Star3 spectrograph3)
    (take_image instrument7 Star3 thermograph1)
    (take_image instrument7 Star3 thermograph2)
    (take_image instrument7 Star4 image0)
    (take_image instrument7 Star4 spectrograph3)
    (take_image instrument7 Star4 thermograph1)
    (take_image instrument7 Star4 thermograph2)
    (take_image instrument7 Star6 image0)
    (take_image instrument7 Star6 spectrograph3)
    (take_image instrument7 Star6 thermograph1)
    (take_image instrument7 Star6 thermograph2)
    (take_image instrument7 Star7 image0)
    (take_image instrument7 Star7 spectrograph3)
    (take_image instrument7 Star7 thermograph1)
    (take_image instrument7 Star7 thermograph2)
    (take_image instrument8 GroundStation1 image0)
    (take_image instrument8 GroundStation1 spectrograph3)
    (take_image instrument8 GroundStation1 thermograph1)
    (take_image instrument8 GroundStation1 thermograph2)
    (take_image instrument8 Phenomenon12 image0)
    (take_image instrument8 Phenomenon12 spectrograph3)
    (take_image instrument8 Phenomenon12 thermograph1)
    (take_image instrument8 Phenomenon12 thermograph2)
    (take_image instrument8 Phenomenon13 image0)
    (take_image instrument8 Phenomenon13 spectrograph3)
    (take_image instrument8 Phenomenon13 thermograph1)
    (take_image instrument8 Phenomenon13 thermograph2)
    (take_image instrument8 Phenomenon14 image0)
    (take_image instrument8 Phenomenon14 spectrograph3)
    (take_image instrument8 Phenomenon14 thermograph1)
    (take_image instrument8 Phenomenon14 thermograph2)
    (take_image instrument8 Phenomenon5 image0)
    (take_image instrument8 Phenomenon5 spectrograph3)
    (take_image instrument8 Phenomenon5 thermograph1)
    (take_image instrument8 Phenomenon5 thermograph2)
    (take_image instrument8 Phenomenon8 image0)
    (take_image instrument8 Phenomenon8 spectrograph3)
    (take_image instrument8 Phenomenon8 thermograph1)
    (take_image instrument8 Phenomenon8 thermograph2)
    (take_image instrument8 Phenomenon9 image0)
    (take_image instrument8 Phenomenon9 spectrograph3)
    (take_image instrument8 Phenomenon9 thermograph1)
    (take_image instrument8 Phenomenon9 thermograph2)
    (take_image instrument8 Planet11 image0)
    (take_image instrument8 Planet11 spectrograph3)
    (take_image instrument8 Planet11 thermograph1)
    (take_image instrument8 Planet11 thermograph2)
    (take_image instrument8 Star0 image0)
    (take_image instrument8 Star0 spectrograph3)
    (take_image instrument8 Star0 thermograph1)
    (take_image instrument8 Star0 thermograph2)
    (take_image instrument8 Star10 image0)
    (take_image instrument8 Star10 spectrograph3)
    (take_image instrument8 Star10 thermograph1)
    (take_image instrument8 Star10 thermograph2)
    (take_image instrument8 Star2 image0)
    (take_image instrument8 Star2 spectrograph3)
    (take_image instrument8 Star2 thermograph1)
    (take_image instrument8 Star2 thermograph2)
    (take_image instrument8 Star3 image0)
    (take_image instrument8 Star3 spectrograph3)
    (take_image instrument8 Star3 thermograph1)
    (take_image instrument8 Star3 thermograph2)
    (take_image instrument8 Star4 image0)
    (take_image instrument8 Star4 spectrograph3)
    (take_image instrument8 Star4 thermograph1)
    (take_image instrument8 Star4 thermograph2)
    (take_image instrument8 Star6 image0)
    (take_image instrument8 Star6 spectrograph3)
    (take_image instrument8 Star6 thermograph1)
    (take_image instrument8 Star6 thermograph2)
    (take_image instrument8 Star7 image0)
    (take_image instrument8 Star7 spectrograph3)
    (take_image instrument8 Star7 thermograph1)
    (take_image instrument8 Star7 thermograph2)
    (take_image instrument9 GroundStation1 image0)
    (take_image instrument9 GroundStation1 spectrograph3)
    (take_image instrument9 GroundStation1 thermograph1)
    (take_image instrument9 GroundStation1 thermograph2)
    (take_image instrument9 Phenomenon12 image0)
    (take_image instrument9 Phenomenon12 spectrograph3)
    (take_image instrument9 Phenomenon12 thermograph1)
    (take_image instrument9 Phenomenon12 thermograph2)
    (take_image instrument9 Phenomenon13 image0)
    (take_image instrument9 Phenomenon13 spectrograph3)
    (take_image instrument9 Phenomenon13 thermograph1)
    (take_image instrument9 Phenomenon13 thermograph2)
    (take_image instrument9 Phenomenon14 image0)
    (take_image instrument9 Phenomenon14 spectrograph3)
    (take_image instrument9 Phenomenon14 thermograph1)
    (take_image instrument9 Phenomenon14 thermograph2)
    (take_image instrument9 Phenomenon5 image0)
    (take_image instrument9 Phenomenon5 spectrograph3)
    (take_image instrument9 Phenomenon5 thermograph1)
    (take_image instrument9 Phenomenon5 thermograph2)
    (take_image instrument9 Phenomenon8 image0)
    (take_image instrument9 Phenomenon8 spectrograph3)
    (take_image instrument9 Phenomenon8 thermograph1)
    (take_image instrument9 Phenomenon8 thermograph2)
    (take_image instrument9 Phenomenon9 image0)
    (take_image instrument9 Phenomenon9 spectrograph3)
    (take_image instrument9 Phenomenon9 thermograph1)
    (take_image instrument9 Phenomenon9 thermograph2)
    (take_image instrument9 Planet11 image0)
    (take_image instrument9 Planet11 spectrograph3)
    (take_image instrument9 Planet11 thermograph1)
    (take_image instrument9 Planet11 thermograph2)
    (take_image instrument9 Star0 image0)
    (take_image instrument9 Star0 spectrograph3)
    (take_image instrument9 Star0 thermograph1)
    (take_image instrument9 Star0 thermograph2)
    (take_image instrument9 Star10 image0)
    (take_image instrument9 Star10 spectrograph3)
    (take_image instrument9 Star10 thermograph1)
    (take_image instrument9 Star10 thermograph2)
    (take_image instrument9 Star2 image0)
    (take_image instrument9 Star2 spectrograph3)
    (take_image instrument9 Star2 thermograph1)
    (take_image instrument9 Star2 thermograph2)
    (take_image instrument9 Star3 image0)
    (take_image instrument9 Star3 spectrograph3)
    (take_image instrument9 Star3 thermograph1)
    (take_image instrument9 Star3 thermograph2)
    (take_image instrument9 Star4 image0)
    (take_image instrument9 Star4 spectrograph3)
    (take_image instrument9 Star4 thermograph1)
    (take_image instrument9 Star4 thermograph2)
    (take_image instrument9 Star6 image0)
    (take_image instrument9 Star6 spectrograph3)
    (take_image instrument9 Star6 thermograph1)
    (take_image instrument9 Star6 thermograph2)
    (take_image instrument9 Star7 image0)
    (take_image instrument9 Star7 spectrograph3)
    (take_image instrument9 Star7 thermograph1)
    (take_image instrument9 Star7 thermograph2)
    )
(:goal (and
	(have_image Phenomenon5 thermograph1)
	(have_image Star6 thermograph1)
	(have_image Star7 spectrograph3)
	(have_image Phenomenon8 image0)
	(have_image Phenomenon9 image0)
	(have_image Star10 spectrograph3)
	(have_image Planet11 thermograph2)
	(have_image Phenomenon12 image0)
	(have_image Phenomenon13 thermograph1)
	(have_image Phenomenon14 thermograph2)
))

)
