; Problem taken from https://github.com/AI-Planning/classical-domains

(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0
	instrument0
	instrument1
	infrared0
	infrared1
	image2
	GroundStation1
	Star0
	GroundStation2
	Planet3
	Planet4
	Phenomenon5
	Phenomenon6
	Star7
)
(:init
	(satellite satellite0)
	(instrument instrument0)
	(supports instrument0 infrared1)
	(supports instrument0 infrared0)
	(calibration_target instrument0 Star0)
	(instrument instrument1)
	(supports instrument1 image2)
	(supports instrument1 infrared1)
	(supports instrument1 infrared0)
	(calibration_target instrument1 GroundStation2)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Planet4)
	(mode infrared0)
	(mode infrared1)
	(mode image2)
	(direction GroundStation1)
	(direction Star0)
	(direction GroundStation2)
	(direction Planet3)
	(direction Planet4)
	(direction Phenomenon5)
	(direction Phenomenon6)
	(direction Star7)

    ; action literals
    (turn_to satellite0 GroundStation1)
    (turn_to satellite0 GroundStation2)
    (turn_to satellite0 Phenomenon5)
    (turn_to satellite0 Phenomenon6)
    (turn_to satellite0 Planet3)
    (turn_to satellite0 Planet4)
    (turn_to satellite0 Star0)
    (turn_to satellite0 Star7)
    (switch_on instrument0)
    (switch_off instrument0)
    (switch_on instrument1)
    (switch_off instrument1)
    (calibrate instrument0 GroundStation1)
    (calibrate instrument0 GroundStation2)
    (calibrate instrument0 Phenomenon5)
    (calibrate instrument0 Phenomenon6)
    (calibrate instrument0 Planet3)
    (calibrate instrument0 Planet4)
    (calibrate instrument0 Star0)
    (calibrate instrument0 Star7)
    (calibrate instrument1 GroundStation1)
    (calibrate instrument1 GroundStation2)
    (calibrate instrument1 Phenomenon5)
    (calibrate instrument1 Phenomenon6)
    (calibrate instrument1 Planet3)
    (calibrate instrument1 Planet4)
    (calibrate instrument1 Star0)
    (calibrate instrument1 Star7)
    (take_image instrument0 GroundStation1 image2)
    (take_image instrument0 GroundStation1 infrared0)
    (take_image instrument0 GroundStation1 infrared1)
    (take_image instrument0 GroundStation2 image2)
    (take_image instrument0 GroundStation2 infrared0)
    (take_image instrument0 GroundStation2 infrared1)
    (take_image instrument0 Phenomenon5 image2)
    (take_image instrument0 Phenomenon5 infrared0)
    (take_image instrument0 Phenomenon5 infrared1)
    (take_image instrument0 Phenomenon6 image2)
    (take_image instrument0 Phenomenon6 infrared0)
    (take_image instrument0 Phenomenon6 infrared1)
    (take_image instrument0 Planet3 image2)
    (take_image instrument0 Planet3 infrared0)
    (take_image instrument0 Planet3 infrared1)
    (take_image instrument0 Planet4 image2)
    (take_image instrument0 Planet4 infrared0)
    (take_image instrument0 Planet4 infrared1)
    (take_image instrument0 Star0 image2)
    (take_image instrument0 Star0 infrared0)
    (take_image instrument0 Star0 infrared1)
    (take_image instrument0 Star7 image2)
    (take_image instrument0 Star7 infrared0)
    (take_image instrument0 Star7 infrared1)
    (take_image instrument1 GroundStation1 image2)
    (take_image instrument1 GroundStation1 infrared0)
    (take_image instrument1 GroundStation1 infrared1)
    (take_image instrument1 GroundStation2 image2)
    (take_image instrument1 GroundStation2 infrared0)
    (take_image instrument1 GroundStation2 infrared1)
    (take_image instrument1 Phenomenon5 image2)
    (take_image instrument1 Phenomenon5 infrared0)
    (take_image instrument1 Phenomenon5 infrared1)
    (take_image instrument1 Phenomenon6 image2)
    (take_image instrument1 Phenomenon6 infrared0)
    (take_image instrument1 Phenomenon6 infrared1)
    (take_image instrument1 Planet3 image2)
    (take_image instrument1 Planet3 infrared0)
    (take_image instrument1 Planet3 infrared1)
    (take_image instrument1 Planet4 image2)
    (take_image instrument1 Planet4 infrared0)
    (take_image instrument1 Planet4 infrared1)
    (take_image instrument1 Star0 image2)
    (take_image instrument1 Star0 infrared0)
    (take_image instrument1 Star0 infrared1)
    (take_image instrument1 Star7 image2)
    (take_image instrument1 Star7 infrared0)
    (take_image instrument1 Star7 infrared1)
    )
(:goal (and
	(have_image Planet3 infrared0)
	(have_image Planet4 infrared0)
	(have_image Phenomenon5 image2)
	(have_image Phenomenon6 infrared0)
	(have_image Star7 infrared0)
))

)
