; Problem taken from https://github.com/AI-Planning/classical-domains

(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0
	instrument0
	satellite1
	instrument1
	instrument2
	infrared0
	infrared1
	thermograph2
	GroundStation1
	Star0
	Star2
	Planet3
	Star4
	Planet5
	Star6
	Star7
	Phenomenon8
	Phenomenon9
)
(:init
	(satellite satellite0)
	(instrument instrument0)
	(supports instrument0 thermograph2)
	(supports instrument0 infrared0)
	(calibration_target instrument0 Star0)
	(on_board instrument0 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star6)
	(satellite satellite1)
	(instrument instrument1)
	(supports instrument1 infrared0)
	(supports instrument1 thermograph2)
	(supports instrument1 infrared1)
	(calibration_target instrument1 Star2)
	(instrument instrument2)
	(supports instrument2 thermograph2)
	(supports instrument2 infrared1)
	(calibration_target instrument2 Star2)
	(on_board instrument1 satellite1)
	(on_board instrument2 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star0)
	(mode infrared0)
	(mode infrared1)
	(mode thermograph2)
	(direction GroundStation1)
	(direction Star0)
	(direction Star2)
	(direction Planet3)
	(direction Star4)
	(direction Planet5)
	(direction Star6)
	(direction Star7)
	(direction Phenomenon8)
	(direction Phenomenon9)

    ; action literals
    (turn_to satellite0 GroundStation1)
    (turn_to satellite0 Phenomenon8)
    (turn_to satellite0 Phenomenon9)
    (turn_to satellite0 Planet3)
    (turn_to satellite0 Planet5)
    (turn_to satellite0 Star0)
    (turn_to satellite0 Star2)
    (turn_to satellite0 Star4)
    (turn_to satellite0 Star6)
    (turn_to satellite0 Star7)
    (turn_to satellite1 GroundStation1)
    (turn_to satellite1 Phenomenon8)
    (turn_to satellite1 Phenomenon9)
    (turn_to satellite1 Planet3)
    (turn_to satellite1 Planet5)
    (turn_to satellite1 Star0)
    (turn_to satellite1 Star2)
    (turn_to satellite1 Star4)
    (turn_to satellite1 Star6)
    (turn_to satellite1 Star7)
    (switch_on instrument0)
    (switch_off instrument0)
    (switch_on instrument1)
    (switch_off instrument1)
    (switch_on instrument2)
    (switch_off instrument2)
    (calibrate instrument0 GroundStation1)
    (calibrate instrument0 Phenomenon8)
    (calibrate instrument0 Phenomenon9)
    (calibrate instrument0 Planet3)
    (calibrate instrument0 Planet5)
    (calibrate instrument0 Star0)
    (calibrate instrument0 Star2)
    (calibrate instrument0 Star4)
    (calibrate instrument0 Star6)
    (calibrate instrument0 Star7)
    (calibrate instrument1 GroundStation1)
    (calibrate instrument1 Phenomenon8)
    (calibrate instrument1 Phenomenon9)
    (calibrate instrument1 Planet3)
    (calibrate instrument1 Planet5)
    (calibrate instrument1 Star0)
    (calibrate instrument1 Star2)
    (calibrate instrument1 Star4)
    (calibrate instrument1 Star6)
    (calibrate instrument1 Star7)
    (calibrate instrument2 GroundStation1)
    (calibrate instrument2 Phenomenon8)
    (calibrate instrument2 Phenomenon9)
    (calibrate instrument2 Planet3)
    (calibrate instrument2 Planet5)
    (calibrate instrument2 Star0)
    (calibrate instrument2 Star2)
    (calibrate instrument2 Star4)
    (calibrate instrument2 Star6)
    (calibrate instrument2 Star7)
    (take_image instrument0 GroundStation1 infrared0)
    (take_image instrument0 GroundStation1 infrared1)
    (take_image instrument0 GroundStation1 thermograph2)
    (take_image instrument0 Phenomenon8 infrared0)
    (take_image instrument0 Phenomenon8 infrared1)
    (take_image instrument0 Phenomenon8 thermograph2)
    (take_image instrument0 Phenomenon9 infrared0)
    (take_image instrument0 Phenomenon9 infrared1)
    (take_image instrument0 Phenomenon9 thermograph2)
    (take_image instrument0 Planet3 infrared0)
    (take_image instrument0 Planet3 infrared1)
    (take_image instrument0 Planet3 thermograph2)
    (take_image instrument0 Planet5 infrared0)
    (take_image instrument0 Planet5 infrared1)
    (take_image instrument0 Planet5 thermograph2)
    (take_image instrument0 Star0 infrared0)
    (take_image instrument0 Star0 infrared1)
    (take_image instrument0 Star0 thermograph2)
    (take_image instrument0 Star2 infrared0)
    (take_image instrument0 Star2 infrared1)
    (take_image instrument0 Star2 thermograph2)
    (take_image instrument0 Star4 infrared0)
    (take_image instrument0 Star4 infrared1)
    (take_image instrument0 Star4 thermograph2)
    (take_image instrument0 Star6 infrared0)
    (take_image instrument0 Star6 infrared1)
    (take_image instrument0 Star6 thermograph2)
    (take_image instrument0 Star7 infrared0)
    (take_image instrument0 Star7 infrared1)
    (take_image instrument0 Star7 thermograph2)
    (take_image instrument1 GroundStation1 infrared0)
    (take_image instrument1 GroundStation1 infrared1)
    (take_image instrument1 GroundStation1 thermograph2)
    (take_image instrument1 Phenomenon8 infrared0)
    (take_image instrument1 Phenomenon8 infrared1)
    (take_image instrument1 Phenomenon8 thermograph2)
    (take_image instrument1 Phenomenon9 infrared0)
    (take_image instrument1 Phenomenon9 infrared1)
    (take_image instrument1 Phenomenon9 thermograph2)
    (take_image instrument1 Planet3 infrared0)
    (take_image instrument1 Planet3 infrared1)
    (take_image instrument1 Planet3 thermograph2)
    (take_image instrument1 Planet5 infrared0)
    (take_image instrument1 Planet5 infrared1)
    (take_image instrument1 Planet5 thermograph2)
    (take_image instrument1 Star0 infrared0)
    (take_image instrument1 Star0 infrared1)
    (take_image instrument1 Star0 thermograph2)
    (take_image instrument1 Star2 infrared0)
    (take_image instrument1 Star2 infrared1)
    (take_image instrument1 Star2 thermograph2)
    (take_image instrument1 Star4 infrared0)
    (take_image instrument1 Star4 infrared1)
    (take_image instrument1 Star4 thermograph2)
    (take_image instrument1 Star6 infrared0)
    (take_image instrument1 Star6 infrared1)
    (take_image instrument1 Star6 thermograph2)
    (take_image instrument1 Star7 infrared0)
    (take_image instrument1 Star7 infrared1)
    (take_image instrument1 Star7 thermograph2)
    (take_image instrument2 GroundStation1 infrared0)
    (take_image instrument2 GroundStation1 infrared1)
    (take_image instrument2 GroundStation1 thermograph2)
    (take_image instrument2 Phenomenon8 infrared0)
    (take_image instrument2 Phenomenon8 infrared1)
    (take_image instrument2 Phenomenon8 thermograph2)
    (take_image instrument2 Phenomenon9 infrared0)
    (take_image instrument2 Phenomenon9 infrared1)
    (take_image instrument2 Phenomenon9 thermograph2)
    (take_image instrument2 Planet3 infrared0)
    (take_image instrument2 Planet3 infrared1)
    (take_image instrument2 Planet3 thermograph2)
    (take_image instrument2 Planet5 infrared0)
    (take_image instrument2 Planet5 infrared1)
    (take_image instrument2 Planet5 thermograph2)
    (take_image instrument2 Star0 infrared0)
    (take_image instrument2 Star0 infrared1)
    (take_image instrument2 Star0 thermograph2)
    (take_image instrument2 Star2 infrared0)
    (take_image instrument2 Star2 infrared1)
    (take_image instrument2 Star2 thermograph2)
    (take_image instrument2 Star4 infrared0)
    (take_image instrument2 Star4 infrared1)
    (take_image instrument2 Star4 thermograph2)
    (take_image instrument2 Star6 infrared0)
    (take_image instrument2 Star6 infrared1)
    (take_image instrument2 Star6 thermograph2)
    (take_image instrument2 Star7 infrared0)
    (take_image instrument2 Star7 infrared1)
    (take_image instrument2 Star7 thermograph2)
    )
(:goal (and
	(pointing satellite1 Planet5)
	(have_image Planet3 infrared1)
	(have_image Star4 infrared1)
	(have_image Planet5 thermograph2)
	(have_image Star6 infrared1)
	(have_image Star7 infrared0)
	(have_image Phenomenon8 thermograph2)
	(have_image Phenomenon9 infrared0)
))

)
