; Problem taken from https://github.com/AI-Planning/classical-domains

(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0
	instrument0
	satellite1
	instrument1
	instrument2
	instrument3
	satellite2
	instrument4
	instrument5
	instrument6
	satellite3
	instrument7
	satellite4
	instrument8
	thermograph2
	image3
	infrared1
	spectrograph4
	infrared0
	Star1
	Star4
	Star0
	GroundStation3
	Star2
	Star5
	Planet6
	Phenomenon7
	Star8
	Phenomenon9
	Star10
	Star11
	Star12
	Planet13
	Planet14
	Phenomenon15
	Planet16
	Star17
	Star18
	Planet19
)
(:init
	(satellite satellite0)
	(instrument instrument0)
	(supports instrument0 spectrograph4)
	(calibration_target instrument0 Star0)
	(on_board instrument0 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star8)
	(satellite satellite1)
	(instrument instrument1)
	(supports instrument1 infrared0)
	(supports instrument1 infrared1)
	(calibration_target instrument1 GroundStation3)
	(instrument instrument2)
	(supports instrument2 infrared1)
	(supports instrument2 infrared0)
	(calibration_target instrument2 Star2)
	(instrument instrument3)
	(supports instrument3 spectrograph4)
	(supports instrument3 infrared1)
	(supports instrument3 thermograph2)
	(calibration_target instrument3 Star0)
	(on_board instrument1 satellite1)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation3)
	(satellite satellite2)
	(instrument instrument4)
	(supports instrument4 infrared1)
	(supports instrument4 image3)
	(supports instrument4 infrared0)
	(calibration_target instrument4 Star2)
	(instrument instrument5)
	(supports instrument5 thermograph2)
	(supports instrument5 spectrograph4)
	(calibration_target instrument5 Star0)
	(instrument instrument6)
	(supports instrument6 infrared0)
	(calibration_target instrument6 GroundStation3)
	(on_board instrument4 satellite2)
	(on_board instrument5 satellite2)
	(on_board instrument6 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star4)
	(satellite satellite3)
	(instrument instrument7)
	(supports instrument7 image3)
	(calibration_target instrument7 Star2)
	(on_board instrument7 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Phenomenon9)
	(satellite satellite4)
	(instrument instrument8)
	(supports instrument8 infrared0)
	(supports instrument8 spectrograph4)
	(supports instrument8 infrared1)
	(calibration_target instrument8 Star2)
	(on_board instrument8 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Phenomenon9)
	(mode thermograph2)
	(mode image3)
	(mode infrared1)
	(mode spectrograph4)
	(mode infrared0)
	(direction Star1)
	(direction Star4)
	(direction Star0)
	(direction GroundStation3)
	(direction Star2)
	(direction Star5)
	(direction Planet6)
	(direction Phenomenon7)
	(direction Star8)
	(direction Phenomenon9)
	(direction Star10)
	(direction Star11)
	(direction Star12)
	(direction Planet13)
	(direction Planet14)
	(direction Phenomenon15)
	(direction Planet16)
	(direction Star17)
	(direction Star18)
	(direction Planet19)

    ; action literals
    (turn_to satellite0 GroundStation3)
    (turn_to satellite0 Phenomenon15)
    (turn_to satellite0 Phenomenon7)
    (turn_to satellite0 Phenomenon9)
    (turn_to satellite0 Planet13)
    (turn_to satellite0 Planet14)
    (turn_to satellite0 Planet16)
    (turn_to satellite0 Planet19)
    (turn_to satellite0 Planet6)
    (turn_to satellite0 Star0)
    (turn_to satellite0 Star1)
    (turn_to satellite0 Star10)
    (turn_to satellite0 Star11)
    (turn_to satellite0 Star12)
    (turn_to satellite0 Star17)
    (turn_to satellite0 Star18)
    (turn_to satellite0 Star2)
    (turn_to satellite0 Star4)
    (turn_to satellite0 Star5)
    (turn_to satellite0 Star8)
    (turn_to satellite1 GroundStation3)
    (turn_to satellite1 Phenomenon15)
    (turn_to satellite1 Phenomenon7)
    (turn_to satellite1 Phenomenon9)
    (turn_to satellite1 Planet13)
    (turn_to satellite1 Planet14)
    (turn_to satellite1 Planet16)
    (turn_to satellite1 Planet19)
    (turn_to satellite1 Planet6)
    (turn_to satellite1 Star0)
    (turn_to satellite1 Star1)
    (turn_to satellite1 Star10)
    (turn_to satellite1 Star11)
    (turn_to satellite1 Star12)
    (turn_to satellite1 Star17)
    (turn_to satellite1 Star18)
    (turn_to satellite1 Star2)
    (turn_to satellite1 Star4)
    (turn_to satellite1 Star5)
    (turn_to satellite1 Star8)
    (turn_to satellite2 GroundStation3)
    (turn_to satellite2 Phenomenon15)
    (turn_to satellite2 Phenomenon7)
    (turn_to satellite2 Phenomenon9)
    (turn_to satellite2 Planet13)
    (turn_to satellite2 Planet14)
    (turn_to satellite2 Planet16)
    (turn_to satellite2 Planet19)
    (turn_to satellite2 Planet6)
    (turn_to satellite2 Star0)
    (turn_to satellite2 Star1)
    (turn_to satellite2 Star10)
    (turn_to satellite2 Star11)
    (turn_to satellite2 Star12)
    (turn_to satellite2 Star17)
    (turn_to satellite2 Star18)
    (turn_to satellite2 Star2)
    (turn_to satellite2 Star4)
    (turn_to satellite2 Star5)
    (turn_to satellite2 Star8)
    (turn_to satellite3 GroundStation3)
    (turn_to satellite3 Phenomenon15)
    (turn_to satellite3 Phenomenon7)
    (turn_to satellite3 Phenomenon9)
    (turn_to satellite3 Planet13)
    (turn_to satellite3 Planet14)
    (turn_to satellite3 Planet16)
    (turn_to satellite3 Planet19)
    (turn_to satellite3 Planet6)
    (turn_to satellite3 Star0)
    (turn_to satellite3 Star1)
    (turn_to satellite3 Star10)
    (turn_to satellite3 Star11)
    (turn_to satellite3 Star12)
    (turn_to satellite3 Star17)
    (turn_to satellite3 Star18)
    (turn_to satellite3 Star2)
    (turn_to satellite3 Star4)
    (turn_to satellite3 Star5)
    (turn_to satellite3 Star8)
    (turn_to satellite4 GroundStation3)
    (turn_to satellite4 Phenomenon15)
    (turn_to satellite4 Phenomenon7)
    (turn_to satellite4 Phenomenon9)
    (turn_to satellite4 Planet13)
    (turn_to satellite4 Planet14)
    (turn_to satellite4 Planet16)
    (turn_to satellite4 Planet19)
    (turn_to satellite4 Planet6)
    (turn_to satellite4 Star0)
    (turn_to satellite4 Star1)
    (turn_to satellite4 Star10)
    (turn_to satellite4 Star11)
    (turn_to satellite4 Star12)
    (turn_to satellite4 Star17)
    (turn_to satellite4 Star18)
    (turn_to satellite4 Star2)
    (turn_to satellite4 Star4)
    (turn_to satellite4 Star5)
    (turn_to satellite4 Star8)
    (switch_on instrument0)
    (switch_off instrument0)
    (switch_on instrument1)
    (switch_off instrument1)
    (switch_on instrument2)
    (switch_off instrument2)
    (switch_on instrument3)
    (switch_off instrument3)
    (switch_on instrument4)
    (switch_off instrument4)
    (switch_on instrument5)
    (switch_off instrument5)
    (switch_on instrument6)
    (switch_off instrument6)
    (switch_on instrument7)
    (switch_off instrument7)
    (switch_on instrument8)
    (switch_off instrument8)
    (calibrate instrument0 GroundStation3)
    (calibrate instrument0 Phenomenon15)
    (calibrate instrument0 Phenomenon7)
    (calibrate instrument0 Phenomenon9)
    (calibrate instrument0 Planet13)
    (calibrate instrument0 Planet14)
    (calibrate instrument0 Planet16)
    (calibrate instrument0 Planet19)
    (calibrate instrument0 Planet6)
    (calibrate instrument0 Star0)
    (calibrate instrument0 Star1)
    (calibrate instrument0 Star10)
    (calibrate instrument0 Star11)
    (calibrate instrument0 Star12)
    (calibrate instrument0 Star17)
    (calibrate instrument0 Star18)
    (calibrate instrument0 Star2)
    (calibrate instrument0 Star4)
    (calibrate instrument0 Star5)
    (calibrate instrument0 Star8)
    (calibrate instrument1 GroundStation3)
    (calibrate instrument1 Phenomenon15)
    (calibrate instrument1 Phenomenon7)
    (calibrate instrument1 Phenomenon9)
    (calibrate instrument1 Planet13)
    (calibrate instrument1 Planet14)
    (calibrate instrument1 Planet16)
    (calibrate instrument1 Planet19)
    (calibrate instrument1 Planet6)
    (calibrate instrument1 Star0)
    (calibrate instrument1 Star1)
    (calibrate instrument1 Star10)
    (calibrate instrument1 Star11)
    (calibrate instrument1 Star12)
    (calibrate instrument1 Star17)
    (calibrate instrument1 Star18)
    (calibrate instrument1 Star2)
    (calibrate instrument1 Star4)
    (calibrate instrument1 Star5)
    (calibrate instrument1 Star8)
    (calibrate instrument2 GroundStation3)
    (calibrate instrument2 Phenomenon15)
    (calibrate instrument2 Phenomenon7)
    (calibrate instrument2 Phenomenon9)
    (calibrate instrument2 Planet13)
    (calibrate instrument2 Planet14)
    (calibrate instrument2 Planet16)
    (calibrate instrument2 Planet19)
    (calibrate instrument2 Planet6)
    (calibrate instrument2 Star0)
    (calibrate instrument2 Star1)
    (calibrate instrument2 Star10)
    (calibrate instrument2 Star11)
    (calibrate instrument2 Star12)
    (calibrate instrument2 Star17)
    (calibrate instrument2 Star18)
    (calibrate instrument2 Star2)
    (calibrate instrument2 Star4)
    (calibrate instrument2 Star5)
    (calibrate instrument2 Star8)
    (calibrate instrument3 GroundStation3)
    (calibrate instrument3 Phenomenon15)
    (calibrate instrument3 Phenomenon7)
    (calibrate instrument3 Phenomenon9)
    (calibrate instrument3 Planet13)
    (calibrate instrument3 Planet14)
    (calibrate instrument3 Planet16)
    (calibrate instrument3 Planet19)
    (calibrate instrument3 Planet6)
    (calibrate instrument3 Star0)
    (calibrate instrument3 Star1)
    (calibrate instrument3 Star10)
    (calibrate instrument3 Star11)
    (calibrate instrument3 Star12)
    (calibrate instrument3 Star17)
    (calibrate instrument3 Star18)
    (calibrate instrument3 Star2)
    (calibrate instrument3 Star4)
    (calibrate instrument3 Star5)
    (calibrate instrument3 Star8)
    (calibrate instrument4 GroundStation3)
    (calibrate instrument4 Phenomenon15)
    (calibrate instrument4 Phenomenon7)
    (calibrate instrument4 Phenomenon9)
    (calibrate instrument4 Planet13)
    (calibrate instrument4 Planet14)
    (calibrate instrument4 Planet16)
    (calibrate instrument4 Planet19)
    (calibrate instrument4 Planet6)
    (calibrate instrument4 Star0)
    (calibrate instrument4 Star1)
    (calibrate instrument4 Star10)
    (calibrate instrument4 Star11)
    (calibrate instrument4 Star12)
    (calibrate instrument4 Star17)
    (calibrate instrument4 Star18)
    (calibrate instrument4 Star2)
    (calibrate instrument4 Star4)
    (calibrate instrument4 Star5)
    (calibrate instrument4 Star8)
    (calibrate instrument5 GroundStation3)
    (calibrate instrument5 Phenomenon15)
    (calibrate instrument5 Phenomenon7)
    (calibrate instrument5 Phenomenon9)
    (calibrate instrument5 Planet13)
    (calibrate instrument5 Planet14)
    (calibrate instrument5 Planet16)
    (calibrate instrument5 Planet19)
    (calibrate instrument5 Planet6)
    (calibrate instrument5 Star0)
    (calibrate instrument5 Star1)
    (calibrate instrument5 Star10)
    (calibrate instrument5 Star11)
    (calibrate instrument5 Star12)
    (calibrate instrument5 Star17)
    (calibrate instrument5 Star18)
    (calibrate instrument5 Star2)
    (calibrate instrument5 Star4)
    (calibrate instrument5 Star5)
    (calibrate instrument5 Star8)
    (calibrate instrument6 GroundStation3)
    (calibrate instrument6 Phenomenon15)
    (calibrate instrument6 Phenomenon7)
    (calibrate instrument6 Phenomenon9)
    (calibrate instrument6 Planet13)
    (calibrate instrument6 Planet14)
    (calibrate instrument6 Planet16)
    (calibrate instrument6 Planet19)
    (calibrate instrument6 Planet6)
    (calibrate instrument6 Star0)
    (calibrate instrument6 Star1)
    (calibrate instrument6 Star10)
    (calibrate instrument6 Star11)
    (calibrate instrument6 Star12)
    (calibrate instrument6 Star17)
    (calibrate instrument6 Star18)
    (calibrate instrument6 Star2)
    (calibrate instrument6 Star4)
    (calibrate instrument6 Star5)
    (calibrate instrument6 Star8)
    (calibrate instrument7 GroundStation3)
    (calibrate instrument7 Phenomenon15)
    (calibrate instrument7 Phenomenon7)
    (calibrate instrument7 Phenomenon9)
    (calibrate instrument7 Planet13)
    (calibrate instrument7 Planet14)
    (calibrate instrument7 Planet16)
    (calibrate instrument7 Planet19)
    (calibrate instrument7 Planet6)
    (calibrate instrument7 Star0)
    (calibrate instrument7 Star1)
    (calibrate instrument7 Star10)
    (calibrate instrument7 Star11)
    (calibrate instrument7 Star12)
    (calibrate instrument7 Star17)
    (calibrate instrument7 Star18)
    (calibrate instrument7 Star2)
    (calibrate instrument7 Star4)
    (calibrate instrument7 Star5)
    (calibrate instrument7 Star8)
    (calibrate instrument8 GroundStation3)
    (calibrate instrument8 Phenomenon15)
    (calibrate instrument8 Phenomenon7)
    (calibrate instrument8 Phenomenon9)
    (calibrate instrument8 Planet13)
    (calibrate instrument8 Planet14)
    (calibrate instrument8 Planet16)
    (calibrate instrument8 Planet19)
    (calibrate instrument8 Planet6)
    (calibrate instrument8 Star0)
    (calibrate instrument8 Star1)
    (calibrate instrument8 Star10)
    (calibrate instrument8 Star11)
    (calibrate instrument8 Star12)
    (calibrate instrument8 Star17)
    (calibrate instrument8 Star18)
    (calibrate instrument8 Star2)
    (calibrate instrument8 Star4)
    (calibrate instrument8 Star5)
    (calibrate instrument8 Star8)
    (take_image instrument0 GroundStation3 image3)
    (take_image instrument0 GroundStation3 infrared0)
    (take_image instrument0 GroundStation3 infrared1)
    (take_image instrument0 GroundStation3 spectrograph4)
    (take_image instrument0 GroundStation3 thermograph2)
    (take_image instrument0 Phenomenon15 image3)
    (take_image instrument0 Phenomenon15 infrared0)
    (take_image instrument0 Phenomenon15 infrared1)
    (take_image instrument0 Phenomenon15 spectrograph4)
    (take_image instrument0 Phenomenon15 thermograph2)
    (take_image instrument0 Phenomenon7 image3)
    (take_image instrument0 Phenomenon7 infrared0)
    (take_image instrument0 Phenomenon7 infrared1)
    (take_image instrument0 Phenomenon7 spectrograph4)
    (take_image instrument0 Phenomenon7 thermograph2)
    (take_image instrument0 Phenomenon9 image3)
    (take_image instrument0 Phenomenon9 infrared0)
    (take_image instrument0 Phenomenon9 infrared1)
    (take_image instrument0 Phenomenon9 spectrograph4)
    (take_image instrument0 Phenomenon9 thermograph2)
    (take_image instrument0 Planet13 image3)
    (take_image instrument0 Planet13 infrared0)
    (take_image instrument0 Planet13 infrared1)
    (take_image instrument0 Planet13 spectrograph4)
    (take_image instrument0 Planet13 thermograph2)
    (take_image instrument0 Planet14 image3)
    (take_image instrument0 Planet14 infrared0)
    (take_image instrument0 Planet14 infrared1)
    (take_image instrument0 Planet14 spectrograph4)
    (take_image instrument0 Planet14 thermograph2)
    (take_image instrument0 Planet16 image3)
    (take_image instrument0 Planet16 infrared0)
    (take_image instrument0 Planet16 infrared1)
    (take_image instrument0 Planet16 spectrograph4)
    (take_image instrument0 Planet16 thermograph2)
    (take_image instrument0 Planet19 image3)
    (take_image instrument0 Planet19 infrared0)
    (take_image instrument0 Planet19 infrared1)
    (take_image instrument0 Planet19 spectrograph4)
    (take_image instrument0 Planet19 thermograph2)
    (take_image instrument0 Planet6 image3)
    (take_image instrument0 Planet6 infrared0)
    (take_image instrument0 Planet6 infrared1)
    (take_image instrument0 Planet6 spectrograph4)
    (take_image instrument0 Planet6 thermograph2)
    (take_image instrument0 Star0 image3)
    (take_image instrument0 Star0 infrared0)
    (take_image instrument0 Star0 infrared1)
    (take_image instrument0 Star0 spectrograph4)
    (take_image instrument0 Star0 thermograph2)
    (take_image instrument0 Star1 image3)
    (take_image instrument0 Star1 infrared0)
    (take_image instrument0 Star1 infrared1)
    (take_image instrument0 Star1 spectrograph4)
    (take_image instrument0 Star1 thermograph2)
    (take_image instrument0 Star10 image3)
    (take_image instrument0 Star10 infrared0)
    (take_image instrument0 Star10 infrared1)
    (take_image instrument0 Star10 spectrograph4)
    (take_image instrument0 Star10 thermograph2)
    (take_image instrument0 Star11 image3)
    (take_image instrument0 Star11 infrared0)
    (take_image instrument0 Star11 infrared1)
    (take_image instrument0 Star11 spectrograph4)
    (take_image instrument0 Star11 thermograph2)
    (take_image instrument0 Star12 image3)
    (take_image instrument0 Star12 infrared0)
    (take_image instrument0 Star12 infrared1)
    (take_image instrument0 Star12 spectrograph4)
    (take_image instrument0 Star12 thermograph2)
    (take_image instrument0 Star17 image3)
    (take_image instrument0 Star17 infrared0)
    (take_image instrument0 Star17 infrared1)
    (take_image instrument0 Star17 spectrograph4)
    (take_image instrument0 Star17 thermograph2)
    (take_image instrument0 Star18 image3)
    (take_image instrument0 Star18 infrared0)
    (take_image instrument0 Star18 infrared1)
    (take_image instrument0 Star18 spectrograph4)
    (take_image instrument0 Star18 thermograph2)
    (take_image instrument0 Star2 image3)
    (take_image instrument0 Star2 infrared0)
    (take_image instrument0 Star2 infrared1)
    (take_image instrument0 Star2 spectrograph4)
    (take_image instrument0 Star2 thermograph2)
    (take_image instrument0 Star4 image3)
    (take_image instrument0 Star4 infrared0)
    (take_image instrument0 Star4 infrared1)
    (take_image instrument0 Star4 spectrograph4)
    (take_image instrument0 Star4 thermograph2)
    (take_image instrument0 Star5 image3)
    (take_image instrument0 Star5 infrared0)
    (take_image instrument0 Star5 infrared1)
    (take_image instrument0 Star5 spectrograph4)
    (take_image instrument0 Star5 thermograph2)
    (take_image instrument0 Star8 image3)
    (take_image instrument0 Star8 infrared0)
    (take_image instrument0 Star8 infrared1)
    (take_image instrument0 Star8 spectrograph4)
    (take_image instrument0 Star8 thermograph2)
    (take_image instrument1 GroundStation3 image3)
    (take_image instrument1 GroundStation3 infrared0)
    (take_image instrument1 GroundStation3 infrared1)
    (take_image instrument1 GroundStation3 spectrograph4)
    (take_image instrument1 GroundStation3 thermograph2)
    (take_image instrument1 Phenomenon15 image3)
    (take_image instrument1 Phenomenon15 infrared0)
    (take_image instrument1 Phenomenon15 infrared1)
    (take_image instrument1 Phenomenon15 spectrograph4)
    (take_image instrument1 Phenomenon15 thermograph2)
    (take_image instrument1 Phenomenon7 image3)
    (take_image instrument1 Phenomenon7 infrared0)
    (take_image instrument1 Phenomenon7 infrared1)
    (take_image instrument1 Phenomenon7 spectrograph4)
    (take_image instrument1 Phenomenon7 thermograph2)
    (take_image instrument1 Phenomenon9 image3)
    (take_image instrument1 Phenomenon9 infrared0)
    (take_image instrument1 Phenomenon9 infrared1)
    (take_image instrument1 Phenomenon9 spectrograph4)
    (take_image instrument1 Phenomenon9 thermograph2)
    (take_image instrument1 Planet13 image3)
    (take_image instrument1 Planet13 infrared0)
    (take_image instrument1 Planet13 infrared1)
    (take_image instrument1 Planet13 spectrograph4)
    (take_image instrument1 Planet13 thermograph2)
    (take_image instrument1 Planet14 image3)
    (take_image instrument1 Planet14 infrared0)
    (take_image instrument1 Planet14 infrared1)
    (take_image instrument1 Planet14 spectrograph4)
    (take_image instrument1 Planet14 thermograph2)
    (take_image instrument1 Planet16 image3)
    (take_image instrument1 Planet16 infrared0)
    (take_image instrument1 Planet16 infrared1)
    (take_image instrument1 Planet16 spectrograph4)
    (take_image instrument1 Planet16 thermograph2)
    (take_image instrument1 Planet19 image3)
    (take_image instrument1 Planet19 infrared0)
    (take_image instrument1 Planet19 infrared1)
    (take_image instrument1 Planet19 spectrograph4)
    (take_image instrument1 Planet19 thermograph2)
    (take_image instrument1 Planet6 image3)
    (take_image instrument1 Planet6 infrared0)
    (take_image instrument1 Planet6 infrared1)
    (take_image instrument1 Planet6 spectrograph4)
    (take_image instrument1 Planet6 thermograph2)
    (take_image instrument1 Star0 image3)
    (take_image instrument1 Star0 infrared0)
    (take_image instrument1 Star0 infrared1)
    (take_image instrument1 Star0 spectrograph4)
    (take_image instrument1 Star0 thermograph2)
    (take_image instrument1 Star1 image3)
    (take_image instrument1 Star1 infrared0)
    (take_image instrument1 Star1 infrared1)
    (take_image instrument1 Star1 spectrograph4)
    (take_image instrument1 Star1 thermograph2)
    (take_image instrument1 Star10 image3)
    (take_image instrument1 Star10 infrared0)
    (take_image instrument1 Star10 infrared1)
    (take_image instrument1 Star10 spectrograph4)
    (take_image instrument1 Star10 thermograph2)
    (take_image instrument1 Star11 image3)
    (take_image instrument1 Star11 infrared0)
    (take_image instrument1 Star11 infrared1)
    (take_image instrument1 Star11 spectrograph4)
    (take_image instrument1 Star11 thermograph2)
    (take_image instrument1 Star12 image3)
    (take_image instrument1 Star12 infrared0)
    (take_image instrument1 Star12 infrared1)
    (take_image instrument1 Star12 spectrograph4)
    (take_image instrument1 Star12 thermograph2)
    (take_image instrument1 Star17 image3)
    (take_image instrument1 Star17 infrared0)
    (take_image instrument1 Star17 infrared1)
    (take_image instrument1 Star17 spectrograph4)
    (take_image instrument1 Star17 thermograph2)
    (take_image instrument1 Star18 image3)
    (take_image instrument1 Star18 infrared0)
    (take_image instrument1 Star18 infrared1)
    (take_image instrument1 Star18 spectrograph4)
    (take_image instrument1 Star18 thermograph2)
    (take_image instrument1 Star2 image3)
    (take_image instrument1 Star2 infrared0)
    (take_image instrument1 Star2 infrared1)
    (take_image instrument1 Star2 spectrograph4)
    (take_image instrument1 Star2 thermograph2)
    (take_image instrument1 Star4 image3)
    (take_image instrument1 Star4 infrared0)
    (take_image instrument1 Star4 infrared1)
    (take_image instrument1 Star4 spectrograph4)
    (take_image instrument1 Star4 thermograph2)
    (take_image instrument1 Star5 image3)
    (take_image instrument1 Star5 infrared0)
    (take_image instrument1 Star5 infrared1)
    (take_image instrument1 Star5 spectrograph4)
    (take_image instrument1 Star5 thermograph2)
    (take_image instrument1 Star8 image3)
    (take_image instrument1 Star8 infrared0)
    (take_image instrument1 Star8 infrared1)
    (take_image instrument1 Star8 spectrograph4)
    (take_image instrument1 Star8 thermograph2)
    (take_image instrument2 GroundStation3 image3)
    (take_image instrument2 GroundStation3 infrared0)
    (take_image instrument2 GroundStation3 infrared1)
    (take_image instrument2 GroundStation3 spectrograph4)
    (take_image instrument2 GroundStation3 thermograph2)
    (take_image instrument2 Phenomenon15 image3)
    (take_image instrument2 Phenomenon15 infrared0)
    (take_image instrument2 Phenomenon15 infrared1)
    (take_image instrument2 Phenomenon15 spectrograph4)
    (take_image instrument2 Phenomenon15 thermograph2)
    (take_image instrument2 Phenomenon7 image3)
    (take_image instrument2 Phenomenon7 infrared0)
    (take_image instrument2 Phenomenon7 infrared1)
    (take_image instrument2 Phenomenon7 spectrograph4)
    (take_image instrument2 Phenomenon7 thermograph2)
    (take_image instrument2 Phenomenon9 image3)
    (take_image instrument2 Phenomenon9 infrared0)
    (take_image instrument2 Phenomenon9 infrared1)
    (take_image instrument2 Phenomenon9 spectrograph4)
    (take_image instrument2 Phenomenon9 thermograph2)
    (take_image instrument2 Planet13 image3)
    (take_image instrument2 Planet13 infrared0)
    (take_image instrument2 Planet13 infrared1)
    (take_image instrument2 Planet13 spectrograph4)
    (take_image instrument2 Planet13 thermograph2)
    (take_image instrument2 Planet14 image3)
    (take_image instrument2 Planet14 infrared0)
    (take_image instrument2 Planet14 infrared1)
    (take_image instrument2 Planet14 spectrograph4)
    (take_image instrument2 Planet14 thermograph2)
    (take_image instrument2 Planet16 image3)
    (take_image instrument2 Planet16 infrared0)
    (take_image instrument2 Planet16 infrared1)
    (take_image instrument2 Planet16 spectrograph4)
    (take_image instrument2 Planet16 thermograph2)
    (take_image instrument2 Planet19 image3)
    (take_image instrument2 Planet19 infrared0)
    (take_image instrument2 Planet19 infrared1)
    (take_image instrument2 Planet19 spectrograph4)
    (take_image instrument2 Planet19 thermograph2)
    (take_image instrument2 Planet6 image3)
    (take_image instrument2 Planet6 infrared0)
    (take_image instrument2 Planet6 infrared1)
    (take_image instrument2 Planet6 spectrograph4)
    (take_image instrument2 Planet6 thermograph2)
    (take_image instrument2 Star0 image3)
    (take_image instrument2 Star0 infrared0)
    (take_image instrument2 Star0 infrared1)
    (take_image instrument2 Star0 spectrograph4)
    (take_image instrument2 Star0 thermograph2)
    (take_image instrument2 Star1 image3)
    (take_image instrument2 Star1 infrared0)
    (take_image instrument2 Star1 infrared1)
    (take_image instrument2 Star1 spectrograph4)
    (take_image instrument2 Star1 thermograph2)
    (take_image instrument2 Star10 image3)
    (take_image instrument2 Star10 infrared0)
    (take_image instrument2 Star10 infrared1)
    (take_image instrument2 Star10 spectrograph4)
    (take_image instrument2 Star10 thermograph2)
    (take_image instrument2 Star11 image3)
    (take_image instrument2 Star11 infrared0)
    (take_image instrument2 Star11 infrared1)
    (take_image instrument2 Star11 spectrograph4)
    (take_image instrument2 Star11 thermograph2)
    (take_image instrument2 Star12 image3)
    (take_image instrument2 Star12 infrared0)
    (take_image instrument2 Star12 infrared1)
    (take_image instrument2 Star12 spectrograph4)
    (take_image instrument2 Star12 thermograph2)
    (take_image instrument2 Star17 image3)
    (take_image instrument2 Star17 infrared0)
    (take_image instrument2 Star17 infrared1)
    (take_image instrument2 Star17 spectrograph4)
    (take_image instrument2 Star17 thermograph2)
    (take_image instrument2 Star18 image3)
    (take_image instrument2 Star18 infrared0)
    (take_image instrument2 Star18 infrared1)
    (take_image instrument2 Star18 spectrograph4)
    (take_image instrument2 Star18 thermograph2)
    (take_image instrument2 Star2 image3)
    (take_image instrument2 Star2 infrared0)
    (take_image instrument2 Star2 infrared1)
    (take_image instrument2 Star2 spectrograph4)
    (take_image instrument2 Star2 thermograph2)
    (take_image instrument2 Star4 image3)
    (take_image instrument2 Star4 infrared0)
    (take_image instrument2 Star4 infrared1)
    (take_image instrument2 Star4 spectrograph4)
    (take_image instrument2 Star4 thermograph2)
    (take_image instrument2 Star5 image3)
    (take_image instrument2 Star5 infrared0)
    (take_image instrument2 Star5 infrared1)
    (take_image instrument2 Star5 spectrograph4)
    (take_image instrument2 Star5 thermograph2)
    (take_image instrument2 Star8 image3)
    (take_image instrument2 Star8 infrared0)
    (take_image instrument2 Star8 infrared1)
    (take_image instrument2 Star8 spectrograph4)
    (take_image instrument2 Star8 thermograph2)
    (take_image instrument3 GroundStation3 image3)
    (take_image instrument3 GroundStation3 infrared0)
    (take_image instrument3 GroundStation3 infrared1)
    (take_image instrument3 GroundStation3 spectrograph4)
    (take_image instrument3 GroundStation3 thermograph2)
    (take_image instrument3 Phenomenon15 image3)
    (take_image instrument3 Phenomenon15 infrared0)
    (take_image instrument3 Phenomenon15 infrared1)
    (take_image instrument3 Phenomenon15 spectrograph4)
    (take_image instrument3 Phenomenon15 thermograph2)
    (take_image instrument3 Phenomenon7 image3)
    (take_image instrument3 Phenomenon7 infrared0)
    (take_image instrument3 Phenomenon7 infrared1)
    (take_image instrument3 Phenomenon7 spectrograph4)
    (take_image instrument3 Phenomenon7 thermograph2)
    (take_image instrument3 Phenomenon9 image3)
    (take_image instrument3 Phenomenon9 infrared0)
    (take_image instrument3 Phenomenon9 infrared1)
    (take_image instrument3 Phenomenon9 spectrograph4)
    (take_image instrument3 Phenomenon9 thermograph2)
    (take_image instrument3 Planet13 image3)
    (take_image instrument3 Planet13 infrared0)
    (take_image instrument3 Planet13 infrared1)
    (take_image instrument3 Planet13 spectrograph4)
    (take_image instrument3 Planet13 thermograph2)
    (take_image instrument3 Planet14 image3)
    (take_image instrument3 Planet14 infrared0)
    (take_image instrument3 Planet14 infrared1)
    (take_image instrument3 Planet14 spectrograph4)
    (take_image instrument3 Planet14 thermograph2)
    (take_image instrument3 Planet16 image3)
    (take_image instrument3 Planet16 infrared0)
    (take_image instrument3 Planet16 infrared1)
    (take_image instrument3 Planet16 spectrograph4)
    (take_image instrument3 Planet16 thermograph2)
    (take_image instrument3 Planet19 image3)
    (take_image instrument3 Planet19 infrared0)
    (take_image instrument3 Planet19 infrared1)
    (take_image instrument3 Planet19 spectrograph4)
    (take_image instrument3 Planet19 thermograph2)
    (take_image instrument3 Planet6 image3)
    (take_image instrument3 Planet6 infrared0)
    (take_image instrument3 Planet6 infrared1)
    (take_image instrument3 Planet6 spectrograph4)
    (take_image instrument3 Planet6 thermograph2)
    (take_image instrument3 Star0 image3)
    (take_image instrument3 Star0 infrared0)
    (take_image instrument3 Star0 infrared1)
    (take_image instrument3 Star0 spectrograph4)
    (take_image instrument3 Star0 thermograph2)
    (take_image instrument3 Star1 image3)
    (take_image instrument3 Star1 infrared0)
    (take_image instrument3 Star1 infrared1)
    (take_image instrument3 Star1 spectrograph4)
    (take_image instrument3 Star1 thermograph2)
    (take_image instrument3 Star10 image3)
    (take_image instrument3 Star10 infrared0)
    (take_image instrument3 Star10 infrared1)
    (take_image instrument3 Star10 spectrograph4)
    (take_image instrument3 Star10 thermograph2)
    (take_image instrument3 Star11 image3)
    (take_image instrument3 Star11 infrared0)
    (take_image instrument3 Star11 infrared1)
    (take_image instrument3 Star11 spectrograph4)
    (take_image instrument3 Star11 thermograph2)
    (take_image instrument3 Star12 image3)
    (take_image instrument3 Star12 infrared0)
    (take_image instrument3 Star12 infrared1)
    (take_image instrument3 Star12 spectrograph4)
    (take_image instrument3 Star12 thermograph2)
    (take_image instrument3 Star17 image3)
    (take_image instrument3 Star17 infrared0)
    (take_image instrument3 Star17 infrared1)
    (take_image instrument3 Star17 spectrograph4)
    (take_image instrument3 Star17 thermograph2)
    (take_image instrument3 Star18 image3)
    (take_image instrument3 Star18 infrared0)
    (take_image instrument3 Star18 infrared1)
    (take_image instrument3 Star18 spectrograph4)
    (take_image instrument3 Star18 thermograph2)
    (take_image instrument3 Star2 image3)
    (take_image instrument3 Star2 infrared0)
    (take_image instrument3 Star2 infrared1)
    (take_image instrument3 Star2 spectrograph4)
    (take_image instrument3 Star2 thermograph2)
    (take_image instrument3 Star4 image3)
    (take_image instrument3 Star4 infrared0)
    (take_image instrument3 Star4 infrared1)
    (take_image instrument3 Star4 spectrograph4)
    (take_image instrument3 Star4 thermograph2)
    (take_image instrument3 Star5 image3)
    (take_image instrument3 Star5 infrared0)
    (take_image instrument3 Star5 infrared1)
    (take_image instrument3 Star5 spectrograph4)
    (take_image instrument3 Star5 thermograph2)
    (take_image instrument3 Star8 image3)
    (take_image instrument3 Star8 infrared0)
    (take_image instrument3 Star8 infrared1)
    (take_image instrument3 Star8 spectrograph4)
    (take_image instrument3 Star8 thermograph2)
    (take_image instrument4 GroundStation3 image3)
    (take_image instrument4 GroundStation3 infrared0)
    (take_image instrument4 GroundStation3 infrared1)
    (take_image instrument4 GroundStation3 spectrograph4)
    (take_image instrument4 GroundStation3 thermograph2)
    (take_image instrument4 Phenomenon15 image3)
    (take_image instrument4 Phenomenon15 infrared0)
    (take_image instrument4 Phenomenon15 infrared1)
    (take_image instrument4 Phenomenon15 spectrograph4)
    (take_image instrument4 Phenomenon15 thermograph2)
    (take_image instrument4 Phenomenon7 image3)
    (take_image instrument4 Phenomenon7 infrared0)
    (take_image instrument4 Phenomenon7 infrared1)
    (take_image instrument4 Phenomenon7 spectrograph4)
    (take_image instrument4 Phenomenon7 thermograph2)
    (take_image instrument4 Phenomenon9 image3)
    (take_image instrument4 Phenomenon9 infrared0)
    (take_image instrument4 Phenomenon9 infrared1)
    (take_image instrument4 Phenomenon9 spectrograph4)
    (take_image instrument4 Phenomenon9 thermograph2)
    (take_image instrument4 Planet13 image3)
    (take_image instrument4 Planet13 infrared0)
    (take_image instrument4 Planet13 infrared1)
    (take_image instrument4 Planet13 spectrograph4)
    (take_image instrument4 Planet13 thermograph2)
    (take_image instrument4 Planet14 image3)
    (take_image instrument4 Planet14 infrared0)
    (take_image instrument4 Planet14 infrared1)
    (take_image instrument4 Planet14 spectrograph4)
    (take_image instrument4 Planet14 thermograph2)
    (take_image instrument4 Planet16 image3)
    (take_image instrument4 Planet16 infrared0)
    (take_image instrument4 Planet16 infrared1)
    (take_image instrument4 Planet16 spectrograph4)
    (take_image instrument4 Planet16 thermograph2)
    (take_image instrument4 Planet19 image3)
    (take_image instrument4 Planet19 infrared0)
    (take_image instrument4 Planet19 infrared1)
    (take_image instrument4 Planet19 spectrograph4)
    (take_image instrument4 Planet19 thermograph2)
    (take_image instrument4 Planet6 image3)
    (take_image instrument4 Planet6 infrared0)
    (take_image instrument4 Planet6 infrared1)
    (take_image instrument4 Planet6 spectrograph4)
    (take_image instrument4 Planet6 thermograph2)
    (take_image instrument4 Star0 image3)
    (take_image instrument4 Star0 infrared0)
    (take_image instrument4 Star0 infrared1)
    (take_image instrument4 Star0 spectrograph4)
    (take_image instrument4 Star0 thermograph2)
    (take_image instrument4 Star1 image3)
    (take_image instrument4 Star1 infrared0)
    (take_image instrument4 Star1 infrared1)
    (take_image instrument4 Star1 spectrograph4)
    (take_image instrument4 Star1 thermograph2)
    (take_image instrument4 Star10 image3)
    (take_image instrument4 Star10 infrared0)
    (take_image instrument4 Star10 infrared1)
    (take_image instrument4 Star10 spectrograph4)
    (take_image instrument4 Star10 thermograph2)
    (take_image instrument4 Star11 image3)
    (take_image instrument4 Star11 infrared0)
    (take_image instrument4 Star11 infrared1)
    (take_image instrument4 Star11 spectrograph4)
    (take_image instrument4 Star11 thermograph2)
    (take_image instrument4 Star12 image3)
    (take_image instrument4 Star12 infrared0)
    (take_image instrument4 Star12 infrared1)
    (take_image instrument4 Star12 spectrograph4)
    (take_image instrument4 Star12 thermograph2)
    (take_image instrument4 Star17 image3)
    (take_image instrument4 Star17 infrared0)
    (take_image instrument4 Star17 infrared1)
    (take_image instrument4 Star17 spectrograph4)
    (take_image instrument4 Star17 thermograph2)
    (take_image instrument4 Star18 image3)
    (take_image instrument4 Star18 infrared0)
    (take_image instrument4 Star18 infrared1)
    (take_image instrument4 Star18 spectrograph4)
    (take_image instrument4 Star18 thermograph2)
    (take_image instrument4 Star2 image3)
    (take_image instrument4 Star2 infrared0)
    (take_image instrument4 Star2 infrared1)
    (take_image instrument4 Star2 spectrograph4)
    (take_image instrument4 Star2 thermograph2)
    (take_image instrument4 Star4 image3)
    (take_image instrument4 Star4 infrared0)
    (take_image instrument4 Star4 infrared1)
    (take_image instrument4 Star4 spectrograph4)
    (take_image instrument4 Star4 thermograph2)
    (take_image instrument4 Star5 image3)
    (take_image instrument4 Star5 infrared0)
    (take_image instrument4 Star5 infrared1)
    (take_image instrument4 Star5 spectrograph4)
    (take_image instrument4 Star5 thermograph2)
    (take_image instrument4 Star8 image3)
    (take_image instrument4 Star8 infrared0)
    (take_image instrument4 Star8 infrared1)
    (take_image instrument4 Star8 spectrograph4)
    (take_image instrument4 Star8 thermograph2)
    (take_image instrument5 GroundStation3 image3)
    (take_image instrument5 GroundStation3 infrared0)
    (take_image instrument5 GroundStation3 infrared1)
    (take_image instrument5 GroundStation3 spectrograph4)
    (take_image instrument5 GroundStation3 thermograph2)
    (take_image instrument5 Phenomenon15 image3)
    (take_image instrument5 Phenomenon15 infrared0)
    (take_image instrument5 Phenomenon15 infrared1)
    (take_image instrument5 Phenomenon15 spectrograph4)
    (take_image instrument5 Phenomenon15 thermograph2)
    (take_image instrument5 Phenomenon7 image3)
    (take_image instrument5 Phenomenon7 infrared0)
    (take_image instrument5 Phenomenon7 infrared1)
    (take_image instrument5 Phenomenon7 spectrograph4)
    (take_image instrument5 Phenomenon7 thermograph2)
    (take_image instrument5 Phenomenon9 image3)
    (take_image instrument5 Phenomenon9 infrared0)
    (take_image instrument5 Phenomenon9 infrared1)
    (take_image instrument5 Phenomenon9 spectrograph4)
    (take_image instrument5 Phenomenon9 thermograph2)
    (take_image instrument5 Planet13 image3)
    (take_image instrument5 Planet13 infrared0)
    (take_image instrument5 Planet13 infrared1)
    (take_image instrument5 Planet13 spectrograph4)
    (take_image instrument5 Planet13 thermograph2)
    (take_image instrument5 Planet14 image3)
    (take_image instrument5 Planet14 infrared0)
    (take_image instrument5 Planet14 infrared1)
    (take_image instrument5 Planet14 spectrograph4)
    (take_image instrument5 Planet14 thermograph2)
    (take_image instrument5 Planet16 image3)
    (take_image instrument5 Planet16 infrared0)
    (take_image instrument5 Planet16 infrared1)
    (take_image instrument5 Planet16 spectrograph4)
    (take_image instrument5 Planet16 thermograph2)
    (take_image instrument5 Planet19 image3)
    (take_image instrument5 Planet19 infrared0)
    (take_image instrument5 Planet19 infrared1)
    (take_image instrument5 Planet19 spectrograph4)
    (take_image instrument5 Planet19 thermograph2)
    (take_image instrument5 Planet6 image3)
    (take_image instrument5 Planet6 infrared0)
    (take_image instrument5 Planet6 infrared1)
    (take_image instrument5 Planet6 spectrograph4)
    (take_image instrument5 Planet6 thermograph2)
    (take_image instrument5 Star0 image3)
    (take_image instrument5 Star0 infrared0)
    (take_image instrument5 Star0 infrared1)
    (take_image instrument5 Star0 spectrograph4)
    (take_image instrument5 Star0 thermograph2)
    (take_image instrument5 Star1 image3)
    (take_image instrument5 Star1 infrared0)
    (take_image instrument5 Star1 infrared1)
    (take_image instrument5 Star1 spectrograph4)
    (take_image instrument5 Star1 thermograph2)
    (take_image instrument5 Star10 image3)
    (take_image instrument5 Star10 infrared0)
    (take_image instrument5 Star10 infrared1)
    (take_image instrument5 Star10 spectrograph4)
    (take_image instrument5 Star10 thermograph2)
    (take_image instrument5 Star11 image3)
    (take_image instrument5 Star11 infrared0)
    (take_image instrument5 Star11 infrared1)
    (take_image instrument5 Star11 spectrograph4)
    (take_image instrument5 Star11 thermograph2)
    (take_image instrument5 Star12 image3)
    (take_image instrument5 Star12 infrared0)
    (take_image instrument5 Star12 infrared1)
    (take_image instrument5 Star12 spectrograph4)
    (take_image instrument5 Star12 thermograph2)
    (take_image instrument5 Star17 image3)
    (take_image instrument5 Star17 infrared0)
    (take_image instrument5 Star17 infrared1)
    (take_image instrument5 Star17 spectrograph4)
    (take_image instrument5 Star17 thermograph2)
    (take_image instrument5 Star18 image3)
    (take_image instrument5 Star18 infrared0)
    (take_image instrument5 Star18 infrared1)
    (take_image instrument5 Star18 spectrograph4)
    (take_image instrument5 Star18 thermograph2)
    (take_image instrument5 Star2 image3)
    (take_image instrument5 Star2 infrared0)
    (take_image instrument5 Star2 infrared1)
    (take_image instrument5 Star2 spectrograph4)
    (take_image instrument5 Star2 thermograph2)
    (take_image instrument5 Star4 image3)
    (take_image instrument5 Star4 infrared0)
    (take_image instrument5 Star4 infrared1)
    (take_image instrument5 Star4 spectrograph4)
    (take_image instrument5 Star4 thermograph2)
    (take_image instrument5 Star5 image3)
    (take_image instrument5 Star5 infrared0)
    (take_image instrument5 Star5 infrared1)
    (take_image instrument5 Star5 spectrograph4)
    (take_image instrument5 Star5 thermograph2)
    (take_image instrument5 Star8 image3)
    (take_image instrument5 Star8 infrared0)
    (take_image instrument5 Star8 infrared1)
    (take_image instrument5 Star8 spectrograph4)
    (take_image instrument5 Star8 thermograph2)
    (take_image instrument6 GroundStation3 image3)
    (take_image instrument6 GroundStation3 infrared0)
    (take_image instrument6 GroundStation3 infrared1)
    (take_image instrument6 GroundStation3 spectrograph4)
    (take_image instrument6 GroundStation3 thermograph2)
    (take_image instrument6 Phenomenon15 image3)
    (take_image instrument6 Phenomenon15 infrared0)
    (take_image instrument6 Phenomenon15 infrared1)
    (take_image instrument6 Phenomenon15 spectrograph4)
    (take_image instrument6 Phenomenon15 thermograph2)
    (take_image instrument6 Phenomenon7 image3)
    (take_image instrument6 Phenomenon7 infrared0)
    (take_image instrument6 Phenomenon7 infrared1)
    (take_image instrument6 Phenomenon7 spectrograph4)
    (take_image instrument6 Phenomenon7 thermograph2)
    (take_image instrument6 Phenomenon9 image3)
    (take_image instrument6 Phenomenon9 infrared0)
    (take_image instrument6 Phenomenon9 infrared1)
    (take_image instrument6 Phenomenon9 spectrograph4)
    (take_image instrument6 Phenomenon9 thermograph2)
    (take_image instrument6 Planet13 image3)
    (take_image instrument6 Planet13 infrared0)
    (take_image instrument6 Planet13 infrared1)
    (take_image instrument6 Planet13 spectrograph4)
    (take_image instrument6 Planet13 thermograph2)
    (take_image instrument6 Planet14 image3)
    (take_image instrument6 Planet14 infrared0)
    (take_image instrument6 Planet14 infrared1)
    (take_image instrument6 Planet14 spectrograph4)
    (take_image instrument6 Planet14 thermograph2)
    (take_image instrument6 Planet16 image3)
    (take_image instrument6 Planet16 infrared0)
    (take_image instrument6 Planet16 infrared1)
    (take_image instrument6 Planet16 spectrograph4)
    (take_image instrument6 Planet16 thermograph2)
    (take_image instrument6 Planet19 image3)
    (take_image instrument6 Planet19 infrared0)
    (take_image instrument6 Planet19 infrared1)
    (take_image instrument6 Planet19 spectrograph4)
    (take_image instrument6 Planet19 thermograph2)
    (take_image instrument6 Planet6 image3)
    (take_image instrument6 Planet6 infrared0)
    (take_image instrument6 Planet6 infrared1)
    (take_image instrument6 Planet6 spectrograph4)
    (take_image instrument6 Planet6 thermograph2)
    (take_image instrument6 Star0 image3)
    (take_image instrument6 Star0 infrared0)
    (take_image instrument6 Star0 infrared1)
    (take_image instrument6 Star0 spectrograph4)
    (take_image instrument6 Star0 thermograph2)
    (take_image instrument6 Star1 image3)
    (take_image instrument6 Star1 infrared0)
    (take_image instrument6 Star1 infrared1)
    (take_image instrument6 Star1 spectrograph4)
    (take_image instrument6 Star1 thermograph2)
    (take_image instrument6 Star10 image3)
    (take_image instrument6 Star10 infrared0)
    (take_image instrument6 Star10 infrared1)
    (take_image instrument6 Star10 spectrograph4)
    (take_image instrument6 Star10 thermograph2)
    (take_image instrument6 Star11 image3)
    (take_image instrument6 Star11 infrared0)
    (take_image instrument6 Star11 infrared1)
    (take_image instrument6 Star11 spectrograph4)
    (take_image instrument6 Star11 thermograph2)
    (take_image instrument6 Star12 image3)
    (take_image instrument6 Star12 infrared0)
    (take_image instrument6 Star12 infrared1)
    (take_image instrument6 Star12 spectrograph4)
    (take_image instrument6 Star12 thermograph2)
    (take_image instrument6 Star17 image3)
    (take_image instrument6 Star17 infrared0)
    (take_image instrument6 Star17 infrared1)
    (take_image instrument6 Star17 spectrograph4)
    (take_image instrument6 Star17 thermograph2)
    (take_image instrument6 Star18 image3)
    (take_image instrument6 Star18 infrared0)
    (take_image instrument6 Star18 infrared1)
    (take_image instrument6 Star18 spectrograph4)
    (take_image instrument6 Star18 thermograph2)
    (take_image instrument6 Star2 image3)
    (take_image instrument6 Star2 infrared0)
    (take_image instrument6 Star2 infrared1)
    (take_image instrument6 Star2 spectrograph4)
    (take_image instrument6 Star2 thermograph2)
    (take_image instrument6 Star4 image3)
    (take_image instrument6 Star4 infrared0)
    (take_image instrument6 Star4 infrared1)
    (take_image instrument6 Star4 spectrograph4)
    (take_image instrument6 Star4 thermograph2)
    (take_image instrument6 Star5 image3)
    (take_image instrument6 Star5 infrared0)
    (take_image instrument6 Star5 infrared1)
    (take_image instrument6 Star5 spectrograph4)
    (take_image instrument6 Star5 thermograph2)
    (take_image instrument6 Star8 image3)
    (take_image instrument6 Star8 infrared0)
    (take_image instrument6 Star8 infrared1)
    (take_image instrument6 Star8 spectrograph4)
    (take_image instrument6 Star8 thermograph2)
    (take_image instrument7 GroundStation3 image3)
    (take_image instrument7 GroundStation3 infrared0)
    (take_image instrument7 GroundStation3 infrared1)
    (take_image instrument7 GroundStation3 spectrograph4)
    (take_image instrument7 GroundStation3 thermograph2)
    (take_image instrument7 Phenomenon15 image3)
    (take_image instrument7 Phenomenon15 infrared0)
    (take_image instrument7 Phenomenon15 infrared1)
    (take_image instrument7 Phenomenon15 spectrograph4)
    (take_image instrument7 Phenomenon15 thermograph2)
    (take_image instrument7 Phenomenon7 image3)
    (take_image instrument7 Phenomenon7 infrared0)
    (take_image instrument7 Phenomenon7 infrared1)
    (take_image instrument7 Phenomenon7 spectrograph4)
    (take_image instrument7 Phenomenon7 thermograph2)
    (take_image instrument7 Phenomenon9 image3)
    (take_image instrument7 Phenomenon9 infrared0)
    (take_image instrument7 Phenomenon9 infrared1)
    (take_image instrument7 Phenomenon9 spectrograph4)
    (take_image instrument7 Phenomenon9 thermograph2)
    (take_image instrument7 Planet13 image3)
    (take_image instrument7 Planet13 infrared0)
    (take_image instrument7 Planet13 infrared1)
    (take_image instrument7 Planet13 spectrograph4)
    (take_image instrument7 Planet13 thermograph2)
    (take_image instrument7 Planet14 image3)
    (take_image instrument7 Planet14 infrared0)
    (take_image instrument7 Planet14 infrared1)
    (take_image instrument7 Planet14 spectrograph4)
    (take_image instrument7 Planet14 thermograph2)
    (take_image instrument7 Planet16 image3)
    (take_image instrument7 Planet16 infrared0)
    (take_image instrument7 Planet16 infrared1)
    (take_image instrument7 Planet16 spectrograph4)
    (take_image instrument7 Planet16 thermograph2)
    (take_image instrument7 Planet19 image3)
    (take_image instrument7 Planet19 infrared0)
    (take_image instrument7 Planet19 infrared1)
    (take_image instrument7 Planet19 spectrograph4)
    (take_image instrument7 Planet19 thermograph2)
    (take_image instrument7 Planet6 image3)
    (take_image instrument7 Planet6 infrared0)
    (take_image instrument7 Planet6 infrared1)
    (take_image instrument7 Planet6 spectrograph4)
    (take_image instrument7 Planet6 thermograph2)
    (take_image instrument7 Star0 image3)
    (take_image instrument7 Star0 infrared0)
    (take_image instrument7 Star0 infrared1)
    (take_image instrument7 Star0 spectrograph4)
    (take_image instrument7 Star0 thermograph2)
    (take_image instrument7 Star1 image3)
    (take_image instrument7 Star1 infrared0)
    (take_image instrument7 Star1 infrared1)
    (take_image instrument7 Star1 spectrograph4)
    (take_image instrument7 Star1 thermograph2)
    (take_image instrument7 Star10 image3)
    (take_image instrument7 Star10 infrared0)
    (take_image instrument7 Star10 infrared1)
    (take_image instrument7 Star10 spectrograph4)
    (take_image instrument7 Star10 thermograph2)
    (take_image instrument7 Star11 image3)
    (take_image instrument7 Star11 infrared0)
    (take_image instrument7 Star11 infrared1)
    (take_image instrument7 Star11 spectrograph4)
    (take_image instrument7 Star11 thermograph2)
    (take_image instrument7 Star12 image3)
    (take_image instrument7 Star12 infrared0)
    (take_image instrument7 Star12 infrared1)
    (take_image instrument7 Star12 spectrograph4)
    (take_image instrument7 Star12 thermograph2)
    (take_image instrument7 Star17 image3)
    (take_image instrument7 Star17 infrared0)
    (take_image instrument7 Star17 infrared1)
    (take_image instrument7 Star17 spectrograph4)
    (take_image instrument7 Star17 thermograph2)
    (take_image instrument7 Star18 image3)
    (take_image instrument7 Star18 infrared0)
    (take_image instrument7 Star18 infrared1)
    (take_image instrument7 Star18 spectrograph4)
    (take_image instrument7 Star18 thermograph2)
    (take_image instrument7 Star2 image3)
    (take_image instrument7 Star2 infrared0)
    (take_image instrument7 Star2 infrared1)
    (take_image instrument7 Star2 spectrograph4)
    (take_image instrument7 Star2 thermograph2)
    (take_image instrument7 Star4 image3)
    (take_image instrument7 Star4 infrared0)
    (take_image instrument7 Star4 infrared1)
    (take_image instrument7 Star4 spectrograph4)
    (take_image instrument7 Star4 thermograph2)
    (take_image instrument7 Star5 image3)
    (take_image instrument7 Star5 infrared0)
    (take_image instrument7 Star5 infrared1)
    (take_image instrument7 Star5 spectrograph4)
    (take_image instrument7 Star5 thermograph2)
    (take_image instrument7 Star8 image3)
    (take_image instrument7 Star8 infrared0)
    (take_image instrument7 Star8 infrared1)
    (take_image instrument7 Star8 spectrograph4)
    (take_image instrument7 Star8 thermograph2)
    (take_image instrument8 GroundStation3 image3)
    (take_image instrument8 GroundStation3 infrared0)
    (take_image instrument8 GroundStation3 infrared1)
    (take_image instrument8 GroundStation3 spectrograph4)
    (take_image instrument8 GroundStation3 thermograph2)
    (take_image instrument8 Phenomenon15 image3)
    (take_image instrument8 Phenomenon15 infrared0)
    (take_image instrument8 Phenomenon15 infrared1)
    (take_image instrument8 Phenomenon15 spectrograph4)
    (take_image instrument8 Phenomenon15 thermograph2)
    (take_image instrument8 Phenomenon7 image3)
    (take_image instrument8 Phenomenon7 infrared0)
    (take_image instrument8 Phenomenon7 infrared1)
    (take_image instrument8 Phenomenon7 spectrograph4)
    (take_image instrument8 Phenomenon7 thermograph2)
    (take_image instrument8 Phenomenon9 image3)
    (take_image instrument8 Phenomenon9 infrared0)
    (take_image instrument8 Phenomenon9 infrared1)
    (take_image instrument8 Phenomenon9 spectrograph4)
    (take_image instrument8 Phenomenon9 thermograph2)
    (take_image instrument8 Planet13 image3)
    (take_image instrument8 Planet13 infrared0)
    (take_image instrument8 Planet13 infrared1)
    (take_image instrument8 Planet13 spectrograph4)
    (take_image instrument8 Planet13 thermograph2)
    (take_image instrument8 Planet14 image3)
    (take_image instrument8 Planet14 infrared0)
    (take_image instrument8 Planet14 infrared1)
    (take_image instrument8 Planet14 spectrograph4)
    (take_image instrument8 Planet14 thermograph2)
    (take_image instrument8 Planet16 image3)
    (take_image instrument8 Planet16 infrared0)
    (take_image instrument8 Planet16 infrared1)
    (take_image instrument8 Planet16 spectrograph4)
    (take_image instrument8 Planet16 thermograph2)
    (take_image instrument8 Planet19 image3)
    (take_image instrument8 Planet19 infrared0)
    (take_image instrument8 Planet19 infrared1)
    (take_image instrument8 Planet19 spectrograph4)
    (take_image instrument8 Planet19 thermograph2)
    (take_image instrument8 Planet6 image3)
    (take_image instrument8 Planet6 infrared0)
    (take_image instrument8 Planet6 infrared1)
    (take_image instrument8 Planet6 spectrograph4)
    (take_image instrument8 Planet6 thermograph2)
    (take_image instrument8 Star0 image3)
    (take_image instrument8 Star0 infrared0)
    (take_image instrument8 Star0 infrared1)
    (take_image instrument8 Star0 spectrograph4)
    (take_image instrument8 Star0 thermograph2)
    (take_image instrument8 Star1 image3)
    (take_image instrument8 Star1 infrared0)
    (take_image instrument8 Star1 infrared1)
    (take_image instrument8 Star1 spectrograph4)
    (take_image instrument8 Star1 thermograph2)
    (take_image instrument8 Star10 image3)
    (take_image instrument8 Star10 infrared0)
    (take_image instrument8 Star10 infrared1)
    (take_image instrument8 Star10 spectrograph4)
    (take_image instrument8 Star10 thermograph2)
    (take_image instrument8 Star11 image3)
    (take_image instrument8 Star11 infrared0)
    (take_image instrument8 Star11 infrared1)
    (take_image instrument8 Star11 spectrograph4)
    (take_image instrument8 Star11 thermograph2)
    (take_image instrument8 Star12 image3)
    (take_image instrument8 Star12 infrared0)
    (take_image instrument8 Star12 infrared1)
    (take_image instrument8 Star12 spectrograph4)
    (take_image instrument8 Star12 thermograph2)
    (take_image instrument8 Star17 image3)
    (take_image instrument8 Star17 infrared0)
    (take_image instrument8 Star17 infrared1)
    (take_image instrument8 Star17 spectrograph4)
    (take_image instrument8 Star17 thermograph2)
    (take_image instrument8 Star18 image3)
    (take_image instrument8 Star18 infrared0)
    (take_image instrument8 Star18 infrared1)
    (take_image instrument8 Star18 spectrograph4)
    (take_image instrument8 Star18 thermograph2)
    (take_image instrument8 Star2 image3)
    (take_image instrument8 Star2 infrared0)
    (take_image instrument8 Star2 infrared1)
    (take_image instrument8 Star2 spectrograph4)
    (take_image instrument8 Star2 thermograph2)
    (take_image instrument8 Star4 image3)
    (take_image instrument8 Star4 infrared0)
    (take_image instrument8 Star4 infrared1)
    (take_image instrument8 Star4 spectrograph4)
    (take_image instrument8 Star4 thermograph2)
    (take_image instrument8 Star5 image3)
    (take_image instrument8 Star5 infrared0)
    (take_image instrument8 Star5 infrared1)
    (take_image instrument8 Star5 spectrograph4)
    (take_image instrument8 Star5 thermograph2)
    (take_image instrument8 Star8 image3)
    (take_image instrument8 Star8 infrared0)
    (take_image instrument8 Star8 infrared1)
    (take_image instrument8 Star8 spectrograph4)
    (take_image instrument8 Star8 thermograph2)
    )
(:goal (and
	(pointing satellite0 Phenomenon9)
	(pointing satellite1 Star4)
	(pointing satellite4 Star11)
	(have_image Star5 image3)
	(have_image Planet6 infrared1)
	(have_image Phenomenon7 infrared1)
	(have_image Star8 image3)
	(have_image Star10 thermograph2)
	(have_image Star11 infrared1)
	(have_image Planet13 spectrograph4)
	(have_image Planet14 thermograph2)
	(have_image Phenomenon15 infrared0)
	(have_image Planet16 image3)
	(have_image Star17 infrared0)
))

)
