(define (problem strips-gripper-x-8)
   (:domain gripper-strips)
   (:objects rooma roomb ball18 ball17 ball16 ball15 ball14 ball13
             ball12 ball11 ball10 ball9 ball8 ball7 ball6 ball5 ball4 ball3
             ball2 ball1 left right)
   (:init (room rooma)
          (room roomb)
          (ball ball18)
          (ball ball17)
          (ball ball16)
          (ball ball15)
          (ball ball14)
          (ball ball13)
          (ball ball12)
          (ball ball11)
          (ball ball10)
          (ball ball9)
          (ball ball8)
          (ball ball7)
          (ball ball6)
          (ball ball5)
          (ball ball4)
          (ball ball3)
          (ball ball2)
          (ball ball1)
          (at-robby rooma)
          (free left)
          (free right)
          (at ball18 rooma)
          (at ball17 rooma)
          (at ball16 rooma)
          (at ball15 rooma)
          (at ball14 rooma)
          (at ball13 rooma)
          (at ball12 rooma)
          (at ball11 rooma)
          (at ball10 rooma)
          (at ball9 rooma)
          (at ball8 rooma)
          (at ball7 rooma)
          (at ball6 rooma)
          (at ball5 rooma)
          (at ball4 rooma)
          (at ball3 rooma)
          (at ball2 rooma)
          (at ball1 rooma)
          (gripper left)
          (gripper right)
    ; action literals
    (move rooma)
    (move roomb)
    (pick ball1 left)
    (pick ball1 right)
    (pick ball10 left)
    (pick ball10 right)
    (pick ball11 left)
    (pick ball11 right)
    (pick ball12 left)
    (pick ball12 right)
    (pick ball13 left)
    (pick ball13 right)
    (pick ball14 left)
    (pick ball14 right)
    (pick ball15 left)
    (pick ball15 right)
    (pick ball16 left)
    (pick ball16 right)
    (pick ball17 left)
    (pick ball17 right)
    (pick ball18 left)
    (pick ball18 right)
    (pick ball2 left)
    (pick ball2 right)
    (pick ball3 left)
    (pick ball3 right)
    (pick ball4 left)
    (pick ball4 right)
    (pick ball5 left)
    (pick ball5 right)
    (pick ball6 left)
    (pick ball6 right)
    (pick ball7 left)
    (pick ball7 right)
    (pick ball8 left)
    (pick ball8 right)
    (pick ball9 left)
    (pick ball9 right)
    (drop ball1 left)
    (drop ball1 right)
    (drop ball10 left)
    (drop ball10 right)
    (drop ball11 left)
    (drop ball11 right)
    (drop ball12 left)
    (drop ball12 right)
    (drop ball13 left)
    (drop ball13 right)
    (drop ball14 left)
    (drop ball14 right)
    (drop ball15 left)
    (drop ball15 right)
    (drop ball16 left)
    (drop ball16 right)
    (drop ball17 left)
    (drop ball17 right)
    (drop ball18 left)
    (drop ball18 right)
    (drop ball2 left)
    (drop ball2 right)
    (drop ball3 left)
    (drop ball3 right)
    (drop ball4 left)
    (drop ball4 right)
    (drop ball5 left)
    (drop ball5 right)
    (drop ball6 left)
    (drop ball6 right)
    (drop ball7 left)
    (drop ball7 right)
    (drop ball8 left)
    (drop ball8 right)
    (drop ball9 left)
    (drop ball9 right)
    )
   (:goal (and (at ball18 roomb)
               (at ball17 roomb)
               (at ball16 roomb)
               (at ball15 roomb)
               (at ball14 roomb)
               (at ball13 roomb)
               (at ball12 roomb)
               (at ball11 roomb)
               (at ball10 roomb)
               (at ball9 roomb)
               (at ball8 roomb)
               (at ball7 roomb)
               (at ball6 roomb)
               (at ball5 roomb)
               (at ball4 roomb)
               (at ball3 roomb)
               (at ball2 roomb)
               (at ball1 roomb))))
