(define (problem strips-gripper-x-2)
   (:domain gripper-strips)
   (:objects rooma roomb ball6 ball5 ball4 ball3 ball2 ball1 left right)
   (:init (room rooma)
          (room roomb)
          (ball ball6)
          (ball ball5)
          (ball ball4)
          (ball ball3)
          (ball ball2)
          (ball ball1)
          (at-robby rooma)
          (free left)
          (free right)
          (at ball6 rooma)
          (at ball5 rooma)
          (at ball4 rooma)
          (at ball3 rooma)
          (at ball2 rooma)
          (at ball1 rooma)
          (gripper left)
          (gripper right)
    ; action literals
    (move rooma)
    (move roomb)
    (pick ball1 left)
    (pick ball1 right)
    (pick ball2 left)
    (pick ball2 right)
    (pick ball3 left)
    (pick ball3 right)
    (pick ball4 left)
    (pick ball4 right)
    (pick ball5 left)
    (pick ball5 right)
    (pick ball6 left)
    (pick ball6 right)
    (drop ball1 left)
    (drop ball1 right)
    (drop ball2 left)
    (drop ball2 right)
    (drop ball3 left)
    (drop ball3 right)
    (drop ball4 left)
    (drop ball4 right)
    (drop ball5 left)
    (drop ball5 right)
    (drop ball6 left)
    (drop ball6 right)
    )
   (:goal (and (at ball6 roomb)
               (at ball5 roomb)
               (at ball4 roomb)
               (at ball3 roomb)
               (at ball2 roomb)
               (at ball1 roomb))))
