(pick-up d robot)
(stack d c robot)
(pick-up b robot)
(stack b a robot)
(unstack d c robot)
(put-down d robot)
(pick-up c robot)
(stack c b robot)
(pick-up d robot)
(stack d c robot)
; cost = 10 (unit cost)
