(define (problem hanoi3)
  (:domain hanoi)
  (:objects peg1 peg2 d1 d2)
  (:init
   (smaller peg1 d1)
   (smaller peg1 d2)
   (smaller peg2 d1)
   (smaller peg2 d2)
   (smaller d2 d1)
   (clear d1)
   (clear d2)
   (on d1 peg1)
   (on d2 peg2)
   (move d1 d2)
   (move d1 peg1)
   (move d1 peg2)
   (move d2 d1)
   (move d2 peg1)
   (move d2 peg2)
   (peg_top peg1 d1)
   (top peg1 d1)
   (peg_top peg2 d2)
   (top peg2 d2)
   (top d1 d1)
   (top d2 d2)
  )
  (:goal (and (on d1 d2)))
  )
