; Problem taken from https://github.com/AI-Planning/classical-domains

(define (problem TPP)
(:domain TPP-Propositional)
(:objects
	goods1 goods2 goods3 goods4 goods5 - goods
	truck1 truck2 - truck
	market1 market2 - market
	depot1 - depot
	level0 level1 - level)

(:init
	(next level1 level0)
	(ready-to-load goods1 market1 level0)
	(ready-to-load goods1 market2 level0)
	(ready-to-load goods2 market1 level0)
	(ready-to-load goods2 market2 level0)
	(ready-to-load goods3 market1 level0)
	(ready-to-load goods3 market2 level0)
	(ready-to-load goods4 market1 level0)
	(ready-to-load goods4 market2 level0)
	(ready-to-load goods5 market1 level0)
	(ready-to-load goods5 market2 level0)
	(stored goods1 level0)
	(stored goods2 level0)
	(stored goods3 level0)
	(stored goods4 level0)
	(stored goods5 level0)
	(loaded goods1 truck1 level0)
	(loaded goods1 truck2 level0)
	(loaded goods2 truck1 level0)
	(loaded goods2 truck2 level0)
	(loaded goods3 truck1 level0)
	(loaded goods3 truck2 level0)
	(loaded goods4 truck1 level0)
	(loaded goods4 truck2 level0)
	(loaded goods5 truck1 level0)
	(loaded goods5 truck2 level0)
	(on-sale goods1 market1 level1)
	(on-sale goods2 market1 level1)
	(on-sale goods3 market1 level1)
	(on-sale goods4 market1 level1)
	(on-sale goods5 market1 level1)
	(on-sale goods1 market2 level0)
	(on-sale goods2 market2 level0)
	(on-sale goods3 market2 level0)
	(on-sale goods4 market2 level0)
	(on-sale goods5 market2 level0)
	(at truck1 depot1)
	(at truck2 depot1)
    ; action literals
    (drive truck1 depot1)
    (drive truck1 market1)
    (drive truck1 market2)
    (drive truck2 depot1)
    (drive truck2 market1)
    (drive truck2 market2)
    (load goods1 truck1)
    (unload goods1 truck1)
    (load goods1 truck2)
    (unload goods1 truck2)
    (load goods2 truck1)
    (unload goods2 truck1)
    (load goods2 truck2)
    (unload goods2 truck2)
    (load goods3 truck1)
    (unload goods3 truck1)
    (load goods3 truck2)
    (unload goods3 truck2)
    (load goods4 truck1)
    (unload goods4 truck1)
    (load goods4 truck2)
    (unload goods4 truck2)
    (load goods5 truck1)
    (unload goods5 truck1)
    (load goods5 truck2)
    (unload goods5 truck2)
    (buy truck1 goods1)
    (buy truck1 goods2)
    (buy truck1 goods3)
    (buy truck1 goods4)
    (buy truck1 goods5)
    (buy truck2 goods1)
    (buy truck2 goods2)
    (buy truck2 goods3)
    (buy truck2 goods4)
    (buy truck2 goods5)
    )

(:goal (and
	(stored goods1 level1)
	(stored goods2 level1)
	(stored goods3 level1)
	(stored goods4 level1)
	(stored goods5 level1)))

)
