; Problem taken from https://github.com/AI-Planning/classical-domains

(define (problem TPP)
(:domain TPP-Propositional)
(:objects
	goods1 goods2 goods3 goods4 goods5 goods6 goods7 goods8 goods9 goods10 goods11 goods12 - goods
	truck1 truck2 truck3 truck4 truck5 truck6 - truck
	market1 market2 market3 market4 market5 market6 - market
	depot1 depot2 depot3 - depot
	level0 level1 level2 level3 level4 level5 - level)

(:init
	(next level1 level0)
	(next level2 level1)
	(next level3 level2)
	(next level4 level3)
	(next level5 level4)
	(ready-to-load goods1 market1 level0)
	(ready-to-load goods1 market2 level0)
	(ready-to-load goods1 market3 level0)
	(ready-to-load goods1 market4 level0)
	(ready-to-load goods1 market5 level0)
	(ready-to-load goods1 market6 level0)
	(ready-to-load goods2 market1 level0)
	(ready-to-load goods2 market2 level0)
	(ready-to-load goods2 market3 level0)
	(ready-to-load goods2 market4 level0)
	(ready-to-load goods2 market5 level0)
	(ready-to-load goods2 market6 level0)
	(ready-to-load goods3 market1 level0)
	(ready-to-load goods3 market2 level0)
	(ready-to-load goods3 market3 level0)
	(ready-to-load goods3 market4 level0)
	(ready-to-load goods3 market5 level0)
	(ready-to-load goods3 market6 level0)
	(ready-to-load goods4 market1 level0)
	(ready-to-load goods4 market2 level0)
	(ready-to-load goods4 market3 level0)
	(ready-to-load goods4 market4 level0)
	(ready-to-load goods4 market5 level0)
	(ready-to-load goods4 market6 level0)
	(ready-to-load goods5 market1 level0)
	(ready-to-load goods5 market2 level0)
	(ready-to-load goods5 market3 level0)
	(ready-to-load goods5 market4 level0)
	(ready-to-load goods5 market5 level0)
	(ready-to-load goods5 market6 level0)
	(ready-to-load goods6 market1 level0)
	(ready-to-load goods6 market2 level0)
	(ready-to-load goods6 market3 level0)
	(ready-to-load goods6 market4 level0)
	(ready-to-load goods6 market5 level0)
	(ready-to-load goods6 market6 level0)
	(ready-to-load goods7 market1 level0)
	(ready-to-load goods7 market2 level0)
	(ready-to-load goods7 market3 level0)
	(ready-to-load goods7 market4 level0)
	(ready-to-load goods7 market5 level0)
	(ready-to-load goods7 market6 level0)
	(ready-to-load goods8 market1 level0)
	(ready-to-load goods8 market2 level0)
	(ready-to-load goods8 market3 level0)
	(ready-to-load goods8 market4 level0)
	(ready-to-load goods8 market5 level0)
	(ready-to-load goods8 market6 level0)
	(ready-to-load goods9 market1 level0)
	(ready-to-load goods9 market2 level0)
	(ready-to-load goods9 market3 level0)
	(ready-to-load goods9 market4 level0)
	(ready-to-load goods9 market5 level0)
	(ready-to-load goods9 market6 level0)
	(ready-to-load goods10 market1 level0)
	(ready-to-load goods10 market2 level0)
	(ready-to-load goods10 market3 level0)
	(ready-to-load goods10 market4 level0)
	(ready-to-load goods10 market5 level0)
	(ready-to-load goods10 market6 level0)
	(ready-to-load goods11 market1 level0)
	(ready-to-load goods11 market2 level0)
	(ready-to-load goods11 market3 level0)
	(ready-to-load goods11 market4 level0)
	(ready-to-load goods11 market5 level0)
	(ready-to-load goods11 market6 level0)
	(ready-to-load goods12 market1 level0)
	(ready-to-load goods12 market2 level0)
	(ready-to-load goods12 market3 level0)
	(ready-to-load goods12 market4 level0)
	(ready-to-load goods12 market5 level0)
	(ready-to-load goods12 market6 level0)
	(stored goods1 level0)
	(stored goods2 level0)
	(stored goods3 level0)
	(stored goods4 level0)
	(stored goods5 level0)
	(stored goods6 level0)
	(stored goods7 level0)
	(stored goods8 level0)
	(stored goods9 level0)
	(stored goods10 level0)
	(stored goods11 level0)
	(stored goods12 level0)
	(loaded goods1 truck1 level0)
	(loaded goods1 truck2 level0)
	(loaded goods1 truck3 level0)
	(loaded goods1 truck4 level0)
	(loaded goods1 truck5 level0)
	(loaded goods1 truck6 level0)
	(loaded goods2 truck1 level0)
	(loaded goods2 truck2 level0)
	(loaded goods2 truck3 level0)
	(loaded goods2 truck4 level0)
	(loaded goods2 truck5 level0)
	(loaded goods2 truck6 level0)
	(loaded goods3 truck1 level0)
	(loaded goods3 truck2 level0)
	(loaded goods3 truck3 level0)
	(loaded goods3 truck4 level0)
	(loaded goods3 truck5 level0)
	(loaded goods3 truck6 level0)
	(loaded goods4 truck1 level0)
	(loaded goods4 truck2 level0)
	(loaded goods4 truck3 level0)
	(loaded goods4 truck4 level0)
	(loaded goods4 truck5 level0)
	(loaded goods4 truck6 level0)
	(loaded goods5 truck1 level0)
	(loaded goods5 truck2 level0)
	(loaded goods5 truck3 level0)
	(loaded goods5 truck4 level0)
	(loaded goods5 truck5 level0)
	(loaded goods5 truck6 level0)
	(loaded goods6 truck1 level0)
	(loaded goods6 truck2 level0)
	(loaded goods6 truck3 level0)
	(loaded goods6 truck4 level0)
	(loaded goods6 truck5 level0)
	(loaded goods6 truck6 level0)
	(loaded goods7 truck1 level0)
	(loaded goods7 truck2 level0)
	(loaded goods7 truck3 level0)
	(loaded goods7 truck4 level0)
	(loaded goods7 truck5 level0)
	(loaded goods7 truck6 level0)
	(loaded goods8 truck1 level0)
	(loaded goods8 truck2 level0)
	(loaded goods8 truck3 level0)
	(loaded goods8 truck4 level0)
	(loaded goods8 truck5 level0)
	(loaded goods8 truck6 level0)
	(loaded goods9 truck1 level0)
	(loaded goods9 truck2 level0)
	(loaded goods9 truck3 level0)
	(loaded goods9 truck4 level0)
	(loaded goods9 truck5 level0)
	(loaded goods9 truck6 level0)
	(loaded goods10 truck1 level0)
	(loaded goods10 truck2 level0)
	(loaded goods10 truck3 level0)
	(loaded goods10 truck4 level0)
	(loaded goods10 truck5 level0)
	(loaded goods10 truck6 level0)
	(loaded goods11 truck1 level0)
	(loaded goods11 truck2 level0)
	(loaded goods11 truck3 level0)
	(loaded goods11 truck4 level0)
	(loaded goods11 truck5 level0)
	(loaded goods11 truck6 level0)
	(loaded goods12 truck1 level0)
	(loaded goods12 truck2 level0)
	(loaded goods12 truck3 level0)
	(loaded goods12 truck4 level0)
	(loaded goods12 truck5 level0)
	(loaded goods12 truck6 level0)
	(on-sale goods1 market1 level1)
	(on-sale goods2 market1 level1)
	(on-sale goods3 market1 level0)
	(on-sale goods4 market1 level2)
	(on-sale goods5 market1 level0)
	(on-sale goods6 market1 level0)
	(on-sale goods7 market1 level2)
	(on-sale goods8 market1 level2)
	(on-sale goods9 market1 level2)
	(on-sale goods10 market1 level0)
	(on-sale goods11 market1 level0)
	(on-sale goods12 market1 level1)
	(on-sale goods1 market2 level2)
	(on-sale goods2 market2 level2)
	(on-sale goods3 market2 level2)
	(on-sale goods4 market2 level2)
	(on-sale goods5 market2 level2)
	(on-sale goods6 market2 level2)
	(on-sale goods7 market2 level1)
	(on-sale goods8 market2 level1)
	(on-sale goods9 market2 level1)
	(on-sale goods10 market2 level2)
	(on-sale goods11 market2 level2)
	(on-sale goods12 market2 level2)
	(on-sale goods1 market3 level0)
	(on-sale goods2 market3 level0)
	(on-sale goods3 market3 level2)
	(on-sale goods4 market3 level1)
	(on-sale goods5 market3 level2)
	(on-sale goods6 market3 level1)
	(on-sale goods7 market3 level2)
	(on-sale goods8 market3 level0)
	(on-sale goods9 market3 level0)
	(on-sale goods10 market3 level1)
	(on-sale goods11 market3 level0)
	(on-sale goods12 market3 level0)
	(on-sale goods1 market4 level1)
	(on-sale goods2 market4 level0)
	(on-sale goods3 market4 level0)
	(on-sale goods4 market4 level0)
	(on-sale goods5 market4 level0)
	(on-sale goods6 market4 level0)
	(on-sale goods7 market4 level0)
	(on-sale goods8 market4 level2)
	(on-sale goods9 market4 level2)
	(on-sale goods10 market4 level2)
	(on-sale goods11 market4 level0)
	(on-sale goods12 market4 level0)
	(on-sale goods1 market5 level0)
	(on-sale goods2 market5 level0)
	(on-sale goods3 market5 level1)
	(on-sale goods4 market5 level0)
	(on-sale goods5 market5 level1)
	(on-sale goods6 market5 level1)
	(on-sale goods7 market5 level0)
	(on-sale goods8 market5 level0)
	(on-sale goods9 market5 level0)
	(on-sale goods10 market5 level0)
	(on-sale goods11 market5 level0)
	(on-sale goods12 market5 level2)
	(on-sale goods1 market6 level0)
	(on-sale goods2 market6 level0)
	(on-sale goods3 market6 level0)
	(on-sale goods4 market6 level0)
	(on-sale goods5 market6 level0)
	(on-sale goods6 market6 level0)
	(on-sale goods7 market6 level0)
	(on-sale goods8 market6 level0)
	(on-sale goods9 market6 level0)
	(on-sale goods10 market6 level0)
	(on-sale goods11 market6 level1)
	(on-sale goods12 market6 level0)
	(at truck1 depot2)
	(at truck2 depot1)
	(at truck3 depot2)
	(at truck4 depot2)
	(at truck5 depot1)
	(at truck6 depot1)
    ; action literals
    (drive truck1 depot1)
    (drive truck1 depot2)
    (drive truck1 depot3)
    (drive truck1 market1)
    (drive truck1 market2)
    (drive truck1 market3)
    (drive truck1 market4)
    (drive truck1 market5)
    (drive truck1 market6)
    (drive truck2 depot1)
    (drive truck2 depot2)
    (drive truck2 depot3)
    (drive truck2 market1)
    (drive truck2 market2)
    (drive truck2 market3)
    (drive truck2 market4)
    (drive truck2 market5)
    (drive truck2 market6)
    (drive truck3 depot1)
    (drive truck3 depot2)
    (drive truck3 depot3)
    (drive truck3 market1)
    (drive truck3 market2)
    (drive truck3 market3)
    (drive truck3 market4)
    (drive truck3 market5)
    (drive truck3 market6)
    (drive truck4 depot1)
    (drive truck4 depot2)
    (drive truck4 depot3)
    (drive truck4 market1)
    (drive truck4 market2)
    (drive truck4 market3)
    (drive truck4 market4)
    (drive truck4 market5)
    (drive truck4 market6)
    (drive truck5 depot1)
    (drive truck5 depot2)
    (drive truck5 depot3)
    (drive truck5 market1)
    (drive truck5 market2)
    (drive truck5 market3)
    (drive truck5 market4)
    (drive truck5 market5)
    (drive truck5 market6)
    (drive truck6 depot1)
    (drive truck6 depot2)
    (drive truck6 depot3)
    (drive truck6 market1)
    (drive truck6 market2)
    (drive truck6 market3)
    (drive truck6 market4)
    (drive truck6 market5)
    (drive truck6 market6)
    (load goods1 truck1)
    (unload goods1 truck1)
    (load goods1 truck2)
    (unload goods1 truck2)
    (load goods1 truck3)
    (unload goods1 truck3)
    (load goods1 truck4)
    (unload goods1 truck4)
    (load goods1 truck5)
    (unload goods1 truck5)
    (load goods1 truck6)
    (unload goods1 truck6)
    (load goods2 truck1)
    (unload goods2 truck1)
    (load goods2 truck2)
    (unload goods2 truck2)
    (load goods2 truck3)
    (unload goods2 truck3)
    (load goods2 truck4)
    (unload goods2 truck4)
    (load goods2 truck5)
    (unload goods2 truck5)
    (load goods2 truck6)
    (unload goods2 truck6)
    (load goods3 truck1)
    (unload goods3 truck1)
    (load goods3 truck2)
    (unload goods3 truck2)
    (load goods3 truck3)
    (unload goods3 truck3)
    (load goods3 truck4)
    (unload goods3 truck4)
    (load goods3 truck5)
    (unload goods3 truck5)
    (load goods3 truck6)
    (unload goods3 truck6)
    (load goods4 truck1)
    (unload goods4 truck1)
    (load goods4 truck2)
    (unload goods4 truck2)
    (load goods4 truck3)
    (unload goods4 truck3)
    (load goods4 truck4)
    (unload goods4 truck4)
    (load goods4 truck5)
    (unload goods4 truck5)
    (load goods4 truck6)
    (unload goods4 truck6)
    (load goods5 truck1)
    (unload goods5 truck1)
    (load goods5 truck2)
    (unload goods5 truck2)
    (load goods5 truck3)
    (unload goods5 truck3)
    (load goods5 truck4)
    (unload goods5 truck4)
    (load goods5 truck5)
    (unload goods5 truck5)
    (load goods5 truck6)
    (unload goods5 truck6)
    (load goods6 truck1)
    (unload goods6 truck1)
    (load goods6 truck2)
    (unload goods6 truck2)
    (load goods6 truck3)
    (unload goods6 truck3)
    (load goods6 truck4)
    (unload goods6 truck4)
    (load goods6 truck5)
    (unload goods6 truck5)
    (load goods6 truck6)
    (unload goods6 truck6)
    (load goods7 truck1)
    (unload goods7 truck1)
    (load goods7 truck2)
    (unload goods7 truck2)
    (load goods7 truck3)
    (unload goods7 truck3)
    (load goods7 truck4)
    (unload goods7 truck4)
    (load goods7 truck5)
    (unload goods7 truck5)
    (load goods7 truck6)
    (unload goods7 truck6)
    (load goods8 truck1)
    (unload goods8 truck1)
    (load goods8 truck2)
    (unload goods8 truck2)
    (load goods8 truck3)
    (unload goods8 truck3)
    (load goods8 truck4)
    (unload goods8 truck4)
    (load goods8 truck5)
    (unload goods8 truck5)
    (load goods8 truck6)
    (unload goods8 truck6)
    (load goods9 truck1)
    (unload goods9 truck1)
    (load goods9 truck2)
    (unload goods9 truck2)
    (load goods9 truck3)
    (unload goods9 truck3)
    (load goods9 truck4)
    (unload goods9 truck4)
    (load goods9 truck5)
    (unload goods9 truck5)
    (load goods9 truck6)
    (unload goods9 truck6)
    (load goods10 truck1)
    (unload goods10 truck1)
    (load goods10 truck2)
    (unload goods10 truck2)
    (load goods10 truck3)
    (unload goods10 truck3)
    (load goods10 truck4)
    (unload goods10 truck4)
    (load goods10 truck5)
    (unload goods10 truck5)
    (load goods10 truck6)
    (unload goods10 truck6)
    (load goods11 truck1)
    (unload goods11 truck1)
    (load goods11 truck2)
    (unload goods11 truck2)
    (load goods11 truck3)
    (unload goods11 truck3)
    (load goods11 truck4)
    (unload goods11 truck4)
    (load goods11 truck5)
    (unload goods11 truck5)
    (load goods11 truck6)
    (unload goods11 truck6)
    (load goods12 truck1)
    (unload goods12 truck1)
    (load goods12 truck2)
    (unload goods12 truck2)
    (load goods12 truck3)
    (unload goods12 truck3)
    (load goods12 truck4)
    (unload goods12 truck4)
    (load goods12 truck5)
    (unload goods12 truck5)
    (load goods12 truck6)
    (unload goods12 truck6)
    (buy truck1 goods1)
    (buy truck1 goods2)
    (buy truck1 goods3)
    (buy truck1 goods4)
    (buy truck1 goods5)
    (buy truck1 goods6)
    (buy truck1 goods7)
    (buy truck1 goods8)
    (buy truck1 goods9)
    (buy truck1 goods10)
    (buy truck1 goods11)
    (buy truck1 goods12)
    (buy truck2 goods1)
    (buy truck2 goods2)
    (buy truck2 goods3)
    (buy truck2 goods4)
    (buy truck2 goods5)
    (buy truck2 goods6)
    (buy truck2 goods7)
    (buy truck2 goods8)
    (buy truck2 goods9)
    (buy truck2 goods10)
    (buy truck2 goods11)
    (buy truck2 goods12)
    (buy truck3 goods1)
    (buy truck3 goods2)
    (buy truck3 goods3)
    (buy truck3 goods4)
    (buy truck3 goods5)
    (buy truck3 goods6)
    (buy truck3 goods7)
    (buy truck3 goods8)
    (buy truck3 goods9)
    (buy truck3 goods10)
    (buy truck3 goods11)
    (buy truck3 goods12)
    (buy truck4 goods1)
    (buy truck4 goods2)
    (buy truck4 goods3)
    (buy truck4 goods4)
    (buy truck4 goods5)
    (buy truck4 goods6)
    (buy truck4 goods7)
    (buy truck4 goods8)
    (buy truck4 goods9)
    (buy truck4 goods10)
    (buy truck4 goods11)
    (buy truck4 goods12)
    (buy truck5 goods1)
    (buy truck5 goods2)
    (buy truck5 goods3)
    (buy truck5 goods4)
    (buy truck5 goods5)
    (buy truck5 goods6)
    (buy truck5 goods7)
    (buy truck5 goods8)
    (buy truck5 goods9)
    (buy truck5 goods10)
    (buy truck5 goods11)
    (buy truck5 goods12)
    (buy truck6 goods1)
    (buy truck6 goods2)
    (buy truck6 goods3)
    (buy truck6 goods4)
    (buy truck6 goods5)
    (buy truck6 goods6)
    (buy truck6 goods7)
    (buy truck6 goods8)
    (buy truck6 goods9)
    (buy truck6 goods10)
    (buy truck6 goods11)
    (buy truck6 goods12)
    )

(:goal (and
	(stored goods1 level3)
	(stored goods2 level3)
	(stored goods3 level5)
	(stored goods4 level1)
	(stored goods5 level4)
	(stored goods6 level4)
	(stored goods7 level1)
	(stored goods8 level1)
	(stored goods9 level1)
	(stored goods10 level1)
	(stored goods11 level2)
	(stored goods12 level1)))

)
