; Problem taken from https://github.com/AI-Planning/classical-domains

(define (problem TPP)
(:domain TPP-Propositional)
(:objects
	goods1 goods2 goods3 goods4 goods5 goods6 goods7 goods8 goods9 - goods
	truck1 truck2 truck3 - truck
	market1 market2 market3 - market
	depot1 - depot
	level0 level1 level2 - level)

(:init
	(next level1 level0)
	(next level2 level1)
	(ready-to-load goods1 market1 level0)
	(ready-to-load goods1 market2 level0)
	(ready-to-load goods1 market3 level0)
	(ready-to-load goods2 market1 level0)
	(ready-to-load goods2 market2 level0)
	(ready-to-load goods2 market3 level0)
	(ready-to-load goods3 market1 level0)
	(ready-to-load goods3 market2 level0)
	(ready-to-load goods3 market3 level0)
	(ready-to-load goods4 market1 level0)
	(ready-to-load goods4 market2 level0)
	(ready-to-load goods4 market3 level0)
	(ready-to-load goods5 market1 level0)
	(ready-to-load goods5 market2 level0)
	(ready-to-load goods5 market3 level0)
	(ready-to-load goods6 market1 level0)
	(ready-to-load goods6 market2 level0)
	(ready-to-load goods6 market3 level0)
	(ready-to-load goods7 market1 level0)
	(ready-to-load goods7 market2 level0)
	(ready-to-load goods7 market3 level0)
	(ready-to-load goods8 market1 level0)
	(ready-to-load goods8 market2 level0)
	(ready-to-load goods8 market3 level0)
	(ready-to-load goods9 market1 level0)
	(ready-to-load goods9 market2 level0)
	(ready-to-load goods9 market3 level0)
	(stored goods1 level0)
	(stored goods2 level0)
	(stored goods3 level0)
	(stored goods4 level0)
	(stored goods5 level0)
	(stored goods6 level0)
	(stored goods7 level0)
	(stored goods8 level0)
	(stored goods9 level0)
	(loaded goods1 truck1 level0)
	(loaded goods1 truck2 level0)
	(loaded goods1 truck3 level0)
	(loaded goods2 truck1 level0)
	(loaded goods2 truck2 level0)
	(loaded goods2 truck3 level0)
	(loaded goods3 truck1 level0)
	(loaded goods3 truck2 level0)
	(loaded goods3 truck3 level0)
	(loaded goods4 truck1 level0)
	(loaded goods4 truck2 level0)
	(loaded goods4 truck3 level0)
	(loaded goods5 truck1 level0)
	(loaded goods5 truck2 level0)
	(loaded goods5 truck3 level0)
	(loaded goods6 truck1 level0)
	(loaded goods6 truck2 level0)
	(loaded goods6 truck3 level0)
	(loaded goods7 truck1 level0)
	(loaded goods7 truck2 level0)
	(loaded goods7 truck3 level0)
	(loaded goods8 truck1 level0)
	(loaded goods8 truck2 level0)
	(loaded goods8 truck3 level0)
	(loaded goods9 truck1 level0)
	(loaded goods9 truck2 level0)
	(loaded goods9 truck3 level0)
	(on-sale goods1 market1 level1)
	(on-sale goods2 market1 level0)
	(on-sale goods3 market1 level1)
	(on-sale goods4 market1 level1)
	(on-sale goods5 market1 level2)
	(on-sale goods6 market1 level0)
	(on-sale goods7 market1 level2)
	(on-sale goods8 market1 level0)
	(on-sale goods9 market1 level0)
	(on-sale goods1 market2 level1)
	(on-sale goods2 market2 level2)
	(on-sale goods3 market2 level1)
	(on-sale goods4 market2 level1)
	(on-sale goods5 market2 level0)
	(on-sale goods6 market2 level1)
	(on-sale goods7 market2 level0)
	(on-sale goods8 market2 level2)
	(on-sale goods9 market2 level1)
	(on-sale goods1 market3 level0)
	(on-sale goods2 market3 level0)
	(on-sale goods3 market3 level0)
	(on-sale goods4 market3 level0)
	(on-sale goods5 market3 level0)
	(on-sale goods6 market3 level0)
	(on-sale goods7 market3 level0)
	(on-sale goods8 market3 level0)
	(on-sale goods9 market3 level0)
	(at truck1 depot1)
	(at truck2 depot1)
	(at truck3 depot1)
    ; action literals
    (drive truck1 depot1)
    (drive truck1 market1)
    (drive truck1 market2)
    (drive truck1 market3)
    (drive truck2 depot1)
    (drive truck2 market1)
    (drive truck2 market2)
    (drive truck2 market3)
    (drive truck3 depot1)
    (drive truck3 market1)
    (drive truck3 market2)
    (drive truck3 market3)
    (load goods1 truck1)
    (unload goods1 truck1)
    (load goods1 truck2)
    (unload goods1 truck2)
    (load goods1 truck3)
    (unload goods1 truck3)
    (load goods2 truck1)
    (unload goods2 truck1)
    (load goods2 truck2)
    (unload goods2 truck2)
    (load goods2 truck3)
    (unload goods2 truck3)
    (load goods3 truck1)
    (unload goods3 truck1)
    (load goods3 truck2)
    (unload goods3 truck2)
    (load goods3 truck3)
    (unload goods3 truck3)
    (load goods4 truck1)
    (unload goods4 truck1)
    (load goods4 truck2)
    (unload goods4 truck2)
    (load goods4 truck3)
    (unload goods4 truck3)
    (load goods5 truck1)
    (unload goods5 truck1)
    (load goods5 truck2)
    (unload goods5 truck2)
    (load goods5 truck3)
    (unload goods5 truck3)
    (load goods6 truck1)
    (unload goods6 truck1)
    (load goods6 truck2)
    (unload goods6 truck2)
    (load goods6 truck3)
    (unload goods6 truck3)
    (load goods7 truck1)
    (unload goods7 truck1)
    (load goods7 truck2)
    (unload goods7 truck2)
    (load goods7 truck3)
    (unload goods7 truck3)
    (load goods8 truck1)
    (unload goods8 truck1)
    (load goods8 truck2)
    (unload goods8 truck2)
    (load goods8 truck3)
    (unload goods8 truck3)
    (load goods9 truck1)
    (unload goods9 truck1)
    (load goods9 truck2)
    (unload goods9 truck2)
    (load goods9 truck3)
    (unload goods9 truck3)
    (buy truck1 goods1)
    (buy truck1 goods2)
    (buy truck1 goods3)
    (buy truck1 goods4)
    (buy truck1 goods5)
    (buy truck1 goods6)
    (buy truck1 goods7)
    (buy truck1 goods8)
    (buy truck1 goods9)
    (buy truck2 goods1)
    (buy truck2 goods2)
    (buy truck2 goods3)
    (buy truck2 goods4)
    (buy truck2 goods5)
    (buy truck2 goods6)
    (buy truck2 goods7)
    (buy truck2 goods8)
    (buy truck2 goods9)
    (buy truck3 goods1)
    (buy truck3 goods2)
    (buy truck3 goods3)
    (buy truck3 goods4)
    (buy truck3 goods5)
    (buy truck3 goods6)
    (buy truck3 goods7)
    (buy truck3 goods8)
    (buy truck3 goods9)
    )

(:goal (and
	(stored goods1 level1)
	(stored goods2 level2)
	(stored goods3 level2)
	(stored goods4 level2)
	(stored goods5 level2)
	(stored goods6 level1)
	(stored goods7 level1)
	(stored goods8 level2)
	(stored goods9 level1)))

)
