(define (problem baking)
    (:domain baking)

    (:objects
      oven-0 oven-1 oven-2 oven-3 oven-4 - oven
      egg-0 egg-1 egg-2 egg-3 egg-4 - ingredient
      flour-0 flour-1 flour-2 - ingredient
      pan-0 pan-1 pan-2 - pan
      new-0 new-1 new-2 new-3 new-4 - ingredient
      soap-0 - soap
      soap-1 - soap
    )

    (:init
    (isegg egg-0)
    (isegg egg-1)
    (isegg egg-2)
    (isegg egg-3)
    (isegg egg-4)
    (isflour flour-0)
    (isflour flour-1)
    (isflour flour-2)
    (hypothetical new-0)
    (hypothetical new-1)
    (hypothetical new-2)
    (hypothetical new-3)
    (hypothetical new-4)
    (panisclean pan-0)
    (panisclean pan-1)
    (panisclean pan-2)

    ; action literals

    (putegginpan egg-0 pan-0)
    (putegginpan egg-0 pan-1)
    (putegginpan egg-0 pan-2)
    (putegginpan egg-1 pan-0)
    (putegginpan egg-1 pan-1)
    (putegginpan egg-1 pan-2)
    (putegginpan egg-2 pan-0)
    (putegginpan egg-2 pan-1)
    (putegginpan egg-2 pan-2)
    (putegginpan egg-3 pan-0)
    (putegginpan egg-3 pan-1)
    (putegginpan egg-3 pan-2)
    (putegginpan egg-4 pan-0)
    (putegginpan egg-4 pan-1)
    (putegginpan egg-4 pan-2)
    (putflourinpan flour-0 pan-0)
    (putflourinpan flour-0 pan-1)
    (putflourinpan flour-0 pan-2)
    (putflourinpan flour-1 pan-0)
    (putflourinpan flour-1 pan-1)
    (putflourinpan flour-1 pan-2)
    (putflourinpan flour-2 pan-0)
    (putflourinpan flour-2 pan-1)
    (putflourinpan flour-2 pan-2)
    (mix pan-0)
    (mix pan-1)
    (mix pan-2)
    (putpaninoven pan-0 oven-0)
    (putpaninoven pan-0 oven-1)
    (putpaninoven pan-0 oven-2)
    (putpaninoven pan-0 oven-3)
    (putpaninoven pan-0 oven-4)
    (putpaninoven pan-1 oven-0)
    (putpaninoven pan-1 oven-1)
    (putpaninoven pan-1 oven-2)
    (putpaninoven pan-1 oven-3)
    (putpaninoven pan-1 oven-4)
    (putpaninoven pan-2 oven-0)
    (putpaninoven pan-2 oven-1)
    (putpaninoven pan-2 oven-2)
    (putpaninoven pan-2 oven-3)
    (putpaninoven pan-2 oven-4)
    (removepanfromoven pan-0)
    (removepanfromoven pan-1)
    (removepanfromoven pan-2)
    (bakecake new-0 oven-0)
    (bakecake new-0 oven-1)
    (bakecake new-0 oven-2)
    (bakecake new-0 oven-3)
    (bakecake new-0 oven-4)
    (bakecake new-1 oven-0)
    (bakecake new-1 oven-1)
    (bakecake new-1 oven-2)
    (bakecake new-1 oven-3)
    (bakecake new-1 oven-4)
    (bakecake new-2 oven-0)
    (bakecake new-2 oven-1)
    (bakecake new-2 oven-2)
    (bakecake new-2 oven-3)
    (bakecake new-2 oven-4)
    (bakecake new-3 oven-0)
    (bakecake new-3 oven-1)
    (bakecake new-3 oven-2)
    (bakecake new-3 oven-3)
    (bakecake new-3 oven-4)
    (bakecake new-4 oven-0)
    (bakecake new-4 oven-1)
    (bakecake new-4 oven-2)
    (bakecake new-4 oven-3)
    (bakecake new-4 oven-4)
    (bakesouffle new-0 oven-0)
    (bakesouffle new-0 oven-1)
    (bakesouffle new-0 oven-2)
    (bakesouffle new-0 oven-3)
    (bakesouffle new-0 oven-4)
    (bakesouffle new-1 oven-0)
    (bakesouffle new-1 oven-1)
    (bakesouffle new-1 oven-2)
    (bakesouffle new-1 oven-3)
    (bakesouffle new-1 oven-4)
    (bakesouffle new-2 oven-0)
    (bakesouffle new-2 oven-1)
    (bakesouffle new-2 oven-2)
    (bakesouffle new-2 oven-3)
    (bakesouffle new-2 oven-4)
    (bakesouffle new-3 oven-0)
    (bakesouffle new-3 oven-1)
    (bakesouffle new-3 oven-2)
    (bakesouffle new-3 oven-3)
    (bakesouffle new-3 oven-4)
    (bakesouffle new-4 oven-0)
    (bakesouffle new-4 oven-1)
    (bakesouffle new-4 oven-2)
    (bakesouffle new-4 oven-3)
    (bakesouffle new-4 oven-4)
    (cleanpan pan-0 soap-0)
    (cleanpan pan-1 soap-0)
    (cleanpan pan-2 soap-0)
    (cleanpan pan-0 soap-1)
    (cleanpan pan-1 soap-1)
    (cleanpan pan-2 soap-1)
    )

    (:goal         (and (iscake new-0) (iscake new-1) (iscake new-2) (issouffle new-3) (issouffle new-4)))
)
