; Problem taken from https://github.com/AI-Planning/classical-domains

(define (problem ZTRAVEL-5-10)
(:domain zeno-travel)
(:objects
	plane1
	plane2
	plane3
	plane4
	plane5
	person1
	person2
	person3
	person4
	person5
	person6
	person7
	person8
	person9
	person10
	city0
	city1
	city2
	city3
	city4
	city5
	city6
	city7
	city8
	city9
	fl0
	fl1
	fl2
	fl3
	fl4
	fl5
	fl6
	)
(:init
	(at plane1 city5)
	(aircraft plane1)
	(fuel-level plane1 fl2)
	(at plane2 city2)
	(aircraft plane2)
	(fuel-level plane2 fl6)
	(at plane3 city4)
	(aircraft plane3)
	(fuel-level plane3 fl6)
	(at plane4 city8)
	(aircraft plane4)
	(fuel-level plane4 fl3)
	(at plane5 city9)
	(aircraft plane5)
	(fuel-level plane5 fl4)
	(at person1 city9)
	(person person1)
	(at person2 city1)
	(person person2)
	(at person3 city0)
	(person person3)
	(at person4 city9)
	(person person4)
	(at person5 city6)
	(person person5)
	(at person6 city0)
	(person person6)
	(at person7 city7)
	(person person7)
	(at person8 city6)
	(person person8)
	(at person9 city4)
	(person person9)
	(at person10 city7)
	(person person10)
	(city city0)
	(city city1)
	(city city2)
	(city city3)
	(city city4)
	(city city5)
	(city city6)
	(city city7)
	(city city8)
	(city city9)
	(next fl0 fl1)
	(next fl1 fl2)
	(next fl2 fl3)
	(next fl3 fl4)
	(next fl4 fl5)
	(next fl5 fl6)
	(flevel fl0)
	(flevel fl1)
	(flevel fl2)
	(flevel fl3)
	(flevel fl4)
	(flevel fl5)
	(flevel fl6)

    ; action literals
    (board person1 plane1)
    (debark person1 plane1)
    (board person1 plane2)
    (debark person1 plane2)
    (board person1 plane3)
    (debark person1 plane3)
    (board person1 plane4)
    (debark person1 plane4)
    (board person1 plane5)
    (debark person1 plane5)
    (board person10 plane1)
    (debark person10 plane1)
    (board person10 plane2)
    (debark person10 plane2)
    (board person10 plane3)
    (debark person10 plane3)
    (board person10 plane4)
    (debark person10 plane4)
    (board person10 plane5)
    (debark person10 plane5)
    (board person2 plane1)
    (debark person2 plane1)
    (board person2 plane2)
    (debark person2 plane2)
    (board person2 plane3)
    (debark person2 plane3)
    (board person2 plane4)
    (debark person2 plane4)
    (board person2 plane5)
    (debark person2 plane5)
    (board person3 plane1)
    (debark person3 plane1)
    (board person3 plane2)
    (debark person3 plane2)
    (board person3 plane3)
    (debark person3 plane3)
    (board person3 plane4)
    (debark person3 plane4)
    (board person3 plane5)
    (debark person3 plane5)
    (board person4 plane1)
    (debark person4 plane1)
    (board person4 plane2)
    (debark person4 plane2)
    (board person4 plane3)
    (debark person4 plane3)
    (board person4 plane4)
    (debark person4 plane4)
    (board person4 plane5)
    (debark person4 plane5)
    (board person5 plane1)
    (debark person5 plane1)
    (board person5 plane2)
    (debark person5 plane2)
    (board person5 plane3)
    (debark person5 plane3)
    (board person5 plane4)
    (debark person5 plane4)
    (board person5 plane5)
    (debark person5 plane5)
    (board person6 plane1)
    (debark person6 plane1)
    (board person6 plane2)
    (debark person6 plane2)
    (board person6 plane3)
    (debark person6 plane3)
    (board person6 plane4)
    (debark person6 plane4)
    (board person6 plane5)
    (debark person6 plane5)
    (board person7 plane1)
    (debark person7 plane1)
    (board person7 plane2)
    (debark person7 plane2)
    (board person7 plane3)
    (debark person7 plane3)
    (board person7 plane4)
    (debark person7 plane4)
    (board person7 plane5)
    (debark person7 plane5)
    (board person8 plane1)
    (debark person8 plane1)
    (board person8 plane2)
    (debark person8 plane2)
    (board person8 plane3)
    (debark person8 plane3)
    (board person8 plane4)
    (debark person8 plane4)
    (board person8 plane5)
    (debark person8 plane5)
    (board person9 plane1)
    (debark person9 plane1)
    (board person9 plane2)
    (debark person9 plane2)
    (board person9 plane3)
    (debark person9 plane3)
    (board person9 plane4)
    (debark person9 plane4)
    (board person9 plane5)
    (debark person9 plane5)
    (fly plane1 city0)
    (fly plane1 city1)
    (fly plane1 city2)
    (fly plane1 city3)
    (fly plane1 city4)
    (fly plane1 city5)
    (fly plane1 city6)
    (fly plane1 city7)
    (fly plane1 city8)
    (fly plane1 city9)
    (fly plane2 city0)
    (fly plane2 city1)
    (fly plane2 city2)
    (fly plane2 city3)
    (fly plane2 city4)
    (fly plane2 city5)
    (fly plane2 city6)
    (fly plane2 city7)
    (fly plane2 city8)
    (fly plane2 city9)
    (fly plane3 city0)
    (fly plane3 city1)
    (fly plane3 city2)
    (fly plane3 city3)
    (fly plane3 city4)
    (fly plane3 city5)
    (fly plane3 city6)
    (fly plane3 city7)
    (fly plane3 city8)
    (fly plane3 city9)
    (fly plane4 city0)
    (fly plane4 city1)
    (fly plane4 city2)
    (fly plane4 city3)
    (fly plane4 city4)
    (fly plane4 city5)
    (fly plane4 city6)
    (fly plane4 city7)
    (fly plane4 city8)
    (fly plane4 city9)
    (fly plane5 city0)
    (fly plane5 city1)
    (fly plane5 city2)
    (fly plane5 city3)
    (fly plane5 city4)
    (fly plane5 city5)
    (fly plane5 city6)
    (fly plane5 city7)
    (fly plane5 city8)
    (fly plane5 city9)
    (refuel plane1)
    (refuel plane2)
    (refuel plane3)
    (refuel plane4)
    (refuel plane5)
    )
(:goal (and
	(at plane2 city3)
	(at plane4 city5)
	(at plane5 city8)
	(at person2 city8)
	(at person3 city2)
	(at person4 city7)
	(at person5 city1)
	(at person6 city6)
	(at person7 city5)
	(at person8 city1)
	(at person9 city5)
	(at person10 city9)
	))

)
