(define (problem NEEDLE_SORTING_3)
    (:domain NEEDLE_SORTING)
    (:objects
        red_needle_1 red_needle_2 red_needle_3 red_needle_4 red_needle_5
        green_needle_1 green_needle_2 green_needle_3 green_needle_4 green_needle_5
        blue_needle_1 blue_needle_2 blue_needle_3 blue_needle_4 blue_needle_5
        red_goal blue_goal green_goal
        resting_position
    )

    (:init
        (robot-at resting_position)
        (handempty)
        (needle red_needle_1)
        (needle red_needle_2)
        (needle red_needle_3)
        (needle red_needle_4)
        (needle red_needle_5)
        (needle green_needle_1)
        (needle green_needle_2)
        (needle green_needle_3)
        (needle green_needle_4)
        (needle green_needle_5)
        (needle blue_needle_1)
        (needle blue_needle_2)
        (needle blue_needle_3)
        (needle blue_needle_4)
        (needle blue_needle_5)
        (needle-at red_needle_1 red_needle_1)
        (needle-at red_needle_2 red_needle_2)
        (needle-at red_needle_3 red_needle_3)
        (needle-at red_needle_4 red_needle_4)
        (needle-at red_needle_5 red_needle_5)
        (needle-at green_needle_1 green_needle_1)
        (needle-at green_needle_2 green_needle_2)
        (needle-at green_needle_3 green_needle_3)
        (needle-at green_needle_4 green_needle_4)
        (needle-at green_needle_5 green_needle_5)
        (needle-at blue_needle_1 blue_needle_1)
        (needle-at blue_needle_2 blue_needle_2)
        (needle-at blue_needle_3 blue_needle_3)
        (needle-at blue_needle_4 blue_needle_4)
        (needle-at blue_needle_5 blue_needle_5)
    )
    (:goal (and
            (needle-at red_needle_1 red_goal)
            (needle-at red_needle_2 red_goal)
            (needle-at red_needle_3 red_goal)
            (needle-at red_needle_4 red_goal)
            (needle-at red_needle_5 red_goal)
            (needle-at green_needle_1 green_goal)
            (needle-at green_needle_2 green_goal)
            (needle-at green_needle_3 green_goal)
            (needle-at green_needle_4 green_goal)
            (needle-at green_needle_5 green_goal)
            (needle-at blue_needle_1 blue_goal)
            (needle-at blue_needle_2 blue_goal)
            (needle-at blue_needle_3 blue_goal)
            (needle-at blue_needle_4 blue_goal)
            (needle-at blue_needle_5 blue_goal)
        )
    )
)
