(define (problem NEEDLE_SORTING_13)
    (:domain NEEDLE_SORTING)
    (:objects
        red_needle_1 red_needle_2 red_needle_3 red_needle_4 green_needle_1 green_needle_2 green_needle_3 green_needle_4 blue_needle_1 blue_needle_2 blue_needle_3 blue_needle_4 yellow_needle_1 yellow_needle_2 yellow_needle_3 yellow_needle_4 orange_needle_1 orange_needle_2 orange_needle_3 orange_needle_4 purple_needle_1 purple_needle_2 purple_needle_3 purple_needle_4 pink_needle_1 pink_needle_2 pink_needle_3 pink_needle_4 cyan_needle_1 cyan_needle_2 cyan_needle_3 cyan_needle_4 magenta_needle_1 magenta_needle_2 magenta_needle_3 magenta_needle_4
        red_goal green_goal blue_goal yellow_goal orange_goal purple_goal pink_goal cyan_goal magenta_goal
        resting_position
    )
    (:init
        (robot-at resting_position)
        (handempty)
        (needle red_needle_1)
        (needle red_needle_2)
        (needle red_needle_3)
        (needle red_needle_4)
        (needle green_needle_1)
        (needle green_needle_2)
        (needle green_needle_3)
        (needle green_needle_4)
        (needle blue_needle_1)
        (needle blue_needle_2)
        (needle blue_needle_3)
        (needle blue_needle_4)
        (needle yellow_needle_1)
        (needle yellow_needle_2)
        (needle yellow_needle_3)
        (needle yellow_needle_4)
        (needle orange_needle_1)
        (needle orange_needle_2)
        (needle orange_needle_3)
        (needle orange_needle_4)
        (needle purple_needle_1)
        (needle purple_needle_2)
        (needle purple_needle_3)
        (needle purple_needle_4)
        (needle pink_needle_1)
        (needle pink_needle_2)
        (needle pink_needle_3)
        (needle pink_needle_4)
        (needle cyan_needle_1)
        (needle cyan_needle_2)
        (needle cyan_needle_3)
        (needle cyan_needle_4)
        (needle magenta_needle_1)
        (needle magenta_needle_2)
        (needle magenta_needle_3)
        (needle magenta_needle_4)
        (needle-at red_needle_1 red_needle_1)
        (needle-at red_needle_2 red_needle_2)
        (needle-at red_needle_3 red_needle_3)
        (needle-at red_needle_4 red_needle_4)
        (needle-at green_needle_1 green_needle_1)
        (needle-at green_needle_2 green_needle_2)
        (needle-at green_needle_3 green_needle_3)
        (needle-at green_needle_4 green_needle_4)
        (needle-at blue_needle_1 blue_needle_1)
        (needle-at blue_needle_2 blue_needle_2)
        (needle-at blue_needle_3 blue_needle_3)
        (needle-at blue_needle_4 blue_needle_4)
        (needle-at yellow_needle_1 yellow_needle_1)
        (needle-at yellow_needle_2 yellow_needle_2)
        (needle-at yellow_needle_3 yellow_needle_3)
        (needle-at yellow_needle_4 yellow_needle_4)
        (needle-at orange_needle_1 orange_needle_1)
        (needle-at orange_needle_2 orange_needle_2)
        (needle-at orange_needle_3 orange_needle_3)
        (needle-at orange_needle_4 orange_needle_4)
        (needle-at purple_needle_1 purple_needle_1)
        (needle-at purple_needle_2 purple_needle_2)
        (needle-at purple_needle_3 purple_needle_3)
        (needle-at purple_needle_4 purple_needle_4)
        (needle-at pink_needle_1 pink_needle_1)
        (needle-at pink_needle_2 pink_needle_2)
        (needle-at pink_needle_3 pink_needle_3)
        (needle-at pink_needle_4 pink_needle_4)
        (needle-at cyan_needle_1 cyan_needle_1)
        (needle-at cyan_needle_2 cyan_needle_2)
        (needle-at cyan_needle_3 cyan_needle_3)
        (needle-at cyan_needle_4 cyan_needle_4)
        (needle-at magenta_needle_1 magenta_needle_1)
        (needle-at magenta_needle_2 magenta_needle_2)
        (needle-at magenta_needle_3 magenta_needle_3)
        (needle-at magenta_needle_4 magenta_needle_4)
    )
    (:goal         (and (needle-at red_needle_1 red_goal) (needle-at red_needle_2 red_goal) (needle-at red_needle_3 red_goal) (needle-at red_needle_4 red_goal) (needle-at green_needle_1 green_goal) (needle-at green_needle_2 green_goal) (needle-at green_needle_3 green_goal) (needle-at green_needle_4 green_goal) (needle-at blue_needle_1 blue_goal) (needle-at blue_needle_2 blue_goal) (needle-at blue_needle_3 blue_goal) (needle-at blue_needle_4 blue_goal) (needle-at yellow_needle_1 yellow_goal) (needle-at yellow_needle_2 yellow_goal) (needle-at yellow_needle_3 yellow_goal) (needle-at yellow_needle_4 yellow_goal) (needle-at orange_needle_1 orange_goal) (needle-at orange_needle_2 orange_goal) (needle-at orange_needle_3 orange_goal) (needle-at orange_needle_4 orange_goal) (needle-at purple_needle_1 purple_goal) (needle-at purple_needle_2 purple_goal) (needle-at purple_needle_3 purple_goal) (needle-at purple_needle_4 purple_goal) (needle-at pink_needle_1 pink_goal) (needle-at pink_needle_2 pink_goal) (needle-at pink_needle_3 pink_goal) (needle-at pink_needle_4 pink_goal) (needle-at cyan_needle_1 cyan_goal) (needle-at cyan_needle_2 cyan_goal) (needle-at cyan_needle_3 cyan_goal) (needle-at cyan_needle_4 cyan_goal) (needle-at magenta_needle_1 magenta_goal) (needle-at magenta_needle_2 magenta_goal) (needle-at magenta_needle_3 magenta_goal) (needle-at magenta_needle_4 magenta_goal)))
)
