(define (problem depotprob1818) (:domain Depot)
(:objects
	depot0 - Depot
	distributor0 distributor1 - Distributor
	truck0 truck1 - Truck
	pallet0 pallet1 pallet2 - Pallet
	crate0 crate1 - Crate
	hoist0 hoist1 hoist2 - Hoist)
(:init
	(at pallet0 depot0)
	(clear crate1)
	(at pallet1 distributor0)
	(clear crate0)
	(at pallet2 distributor1)
	(clear pallet2)
	(at truck0 distributor1)
	(at truck1 depot0)
	(at hoist0 depot0)
	(available hoist0)
	(at hoist1 distributor0)
	(available hoist1)
	(at hoist2 distributor1)
	(available hoist2)
	(at crate0 distributor0)
	(on crate0 pallet1)
	(at crate1 depot0)
	(on crate1 pallet0)

    ; action literals
    (drive truck0 depot0)
    (drive truck0 distributor0)
    (drive truck0 distributor1)
    (drive truck1 depot0)
    (drive truck1 distributor0)
    (drive truck1 distributor1)
    (lift hoist0 crate0)
    (lift hoist0 crate1)
    (lift hoist1 crate0)
    (lift hoist1 crate1)
    (lift hoist2 crate0)
    (lift hoist2 crate1)
    (drop hoist0 crate0)
    (drop hoist0 crate1)
    (drop hoist1 crate0)
    (drop hoist1 crate1)
    (drop hoist2 crate0)
    (drop hoist2 crate1)
    (load hoist0 crate0 truck0)
    (load hoist0 crate0 truck1)
    (load hoist0 crate1 truck0)
    (load hoist0 crate1 truck1)
    (load hoist1 crate0 truck0)
    (load hoist1 crate0 truck1)
    (load hoist1 crate1 truck0)
    (load hoist1 crate1 truck1)
    (load hoist2 crate0 truck0)
    (load hoist2 crate0 truck1)
    (load hoist2 crate1 truck0)
    (load hoist2 crate1 truck1)
    (unload hoist0 crate0 truck0)
    (unload hoist0 crate0 truck1)
    (unload hoist0 crate1 truck0)
    (unload hoist0 crate1 truck1)
    (unload hoist1 crate0 truck0)
    (unload hoist1 crate0 truck1)
    (unload hoist1 crate1 truck0)
    (unload hoist1 crate1 truck1)
    (unload hoist2 crate0 truck0)
    (unload hoist2 crate0 truck1)
    (unload hoist2 crate1 truck0)
    (unload hoist2 crate1 truck1)
    )

(:goal (and
		(on crate0 pallet2)
		(on crate1 pallet1)
	)
))
