(define (problem depotprob5451) (:domain Depot)
(:objects
	depot0 - Depot
	distributor0 distributor1 - Distributor
	truck0 truck1 - Truck
	pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 - Pallet
	crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 crate8 crate9 crate10 crate11 crate12 crate13 crate14 - Crate
	hoist0 hoist1 hoist2 - Hoist)
(:init
	(at pallet0 depot0)
	(clear crate2)
	(at pallet1 distributor0)
	(clear crate14)
	(at pallet2 distributor1)
	(clear crate13)
	(at pallet3 distributor1)
	(clear crate10)
	(at pallet4 distributor0)
	(clear crate12)
	(at pallet5 depot0)
	(clear crate8)
	(at truck0 distributor0)
	(at truck1 distributor0)
	(at hoist0 depot0)
	(available hoist0)
	(at hoist1 distributor0)
	(available hoist1)
	(at hoist2 distributor1)
	(available hoist2)
	(at crate0 distributor1)
	(on crate0 pallet2)
	(at crate1 depot0)
	(on crate1 pallet0)
	(at crate2 depot0)
	(on crate2 crate1)
	(at crate3 distributor0)
	(on crate3 pallet1)
	(at crate4 distributor1)
	(on crate4 crate0)
	(at crate5 distributor1)
	(on crate5 pallet3)
	(at crate6 distributor0)
	(on crate6 crate3)
	(at crate7 distributor0)
	(on crate7 crate6)
	(at crate8 depot0)
	(on crate8 pallet5)
	(at crate9 distributor0)
	(on crate9 crate7)
	(at crate10 distributor1)
	(on crate10 crate5)
	(at crate11 distributor0)
	(on crate11 pallet4)
	(at crate12 distributor0)
	(on crate12 crate11)
	(at crate13 distributor1)
	(on crate13 crate4)
	(at crate14 distributor0)
	(on crate14 crate9)

    ; action literals
    (drive truck0 depot0)
    (drive truck0 distributor0)
    (drive truck0 distributor1)
    (drive truck1 depot0)
    (drive truck1 distributor0)
    (drive truck1 distributor1)
    (lift hoist0 crate0)
    (lift hoist0 crate1)
    (lift hoist0 crate2)
    (lift hoist0 crate3)
    (lift hoist0 crate4)
    (lift hoist0 crate5)
    (lift hoist0 crate6)
    (lift hoist0 crate7)
    (lift hoist0 crate8)
    (lift hoist0 crate9)
    (lift hoist0 crate10)
    (lift hoist0 crate11)
    (lift hoist0 crate12)
    (lift hoist0 crate13)
    (lift hoist0 crate14)
    (lift hoist1 crate0)
    (lift hoist1 crate1)
    (lift hoist1 crate2)
    (lift hoist1 crate3)
    (lift hoist1 crate4)
    (lift hoist1 crate5)
    (lift hoist1 crate6)
    (lift hoist1 crate7)
    (lift hoist1 crate8)
    (lift hoist1 crate9)
    (lift hoist1 crate10)
    (lift hoist1 crate11)
    (lift hoist1 crate12)
    (lift hoist1 crate13)
    (lift hoist1 crate14)
    (lift hoist2 crate0)
    (lift hoist2 crate1)
    (lift hoist2 crate2)
    (lift hoist2 crate3)
    (lift hoist2 crate4)
    (lift hoist2 crate5)
    (lift hoist2 crate6)
    (lift hoist2 crate7)
    (lift hoist2 crate8)
    (lift hoist2 crate9)
    (lift hoist2 crate10)
    (lift hoist2 crate11)
    (lift hoist2 crate12)
    (lift hoist2 crate13)
    (lift hoist2 crate14)
    (drop hoist0 crate0)
    (drop hoist0 crate1)
    (drop hoist0 crate2)
    (drop hoist0 crate3)
    (drop hoist0 crate4)
    (drop hoist0 crate5)
    (drop hoist0 crate6)
    (drop hoist0 crate7)
    (drop hoist0 crate8)
    (drop hoist0 crate9)
    (drop hoist0 crate10)
    (drop hoist0 crate11)
    (drop hoist0 crate12)
    (drop hoist0 crate13)
    (drop hoist0 crate14)
    (drop hoist1 crate0)
    (drop hoist1 crate1)
    (drop hoist1 crate2)
    (drop hoist1 crate3)
    (drop hoist1 crate4)
    (drop hoist1 crate5)
    (drop hoist1 crate6)
    (drop hoist1 crate7)
    (drop hoist1 crate8)
    (drop hoist1 crate9)
    (drop hoist1 crate10)
    (drop hoist1 crate11)
    (drop hoist1 crate12)
    (drop hoist1 crate13)
    (drop hoist1 crate14)
    (drop hoist2 crate0)
    (drop hoist2 crate1)
    (drop hoist2 crate2)
    (drop hoist2 crate3)
    (drop hoist2 crate4)
    (drop hoist2 crate5)
    (drop hoist2 crate6)
    (drop hoist2 crate7)
    (drop hoist2 crate8)
    (drop hoist2 crate9)
    (drop hoist2 crate10)
    (drop hoist2 crate11)
    (drop hoist2 crate12)
    (drop hoist2 crate13)
    (drop hoist2 crate14)
    (load hoist0 crate0 truck0)
    (load hoist0 crate0 truck1)
    (load hoist0 crate1 truck0)
    (load hoist0 crate1 truck1)
    (load hoist0 crate2 truck0)
    (load hoist0 crate2 truck1)
    (load hoist0 crate3 truck0)
    (load hoist0 crate3 truck1)
    (load hoist0 crate4 truck0)
    (load hoist0 crate4 truck1)
    (load hoist0 crate5 truck0)
    (load hoist0 crate5 truck1)
    (load hoist0 crate6 truck0)
    (load hoist0 crate6 truck1)
    (load hoist0 crate7 truck0)
    (load hoist0 crate7 truck1)
    (load hoist0 crate8 truck0)
    (load hoist0 crate8 truck1)
    (load hoist0 crate9 truck0)
    (load hoist0 crate9 truck1)
    (load hoist0 crate10 truck0)
    (load hoist0 crate10 truck1)
    (load hoist0 crate11 truck0)
    (load hoist0 crate11 truck1)
    (load hoist0 crate12 truck0)
    (load hoist0 crate12 truck1)
    (load hoist0 crate13 truck0)
    (load hoist0 crate13 truck1)
    (load hoist0 crate14 truck0)
    (load hoist0 crate14 truck1)
    (load hoist1 crate0 truck0)
    (load hoist1 crate0 truck1)
    (load hoist1 crate1 truck0)
    (load hoist1 crate1 truck1)
    (load hoist1 crate2 truck0)
    (load hoist1 crate2 truck1)
    (load hoist1 crate3 truck0)
    (load hoist1 crate3 truck1)
    (load hoist1 crate4 truck0)
    (load hoist1 crate4 truck1)
    (load hoist1 crate5 truck0)
    (load hoist1 crate5 truck1)
    (load hoist1 crate6 truck0)
    (load hoist1 crate6 truck1)
    (load hoist1 crate7 truck0)
    (load hoist1 crate7 truck1)
    (load hoist1 crate8 truck0)
    (load hoist1 crate8 truck1)
    (load hoist1 crate9 truck0)
    (load hoist1 crate9 truck1)
    (load hoist1 crate10 truck0)
    (load hoist1 crate10 truck1)
    (load hoist1 crate11 truck0)
    (load hoist1 crate11 truck1)
    (load hoist1 crate12 truck0)
    (load hoist1 crate12 truck1)
    (load hoist1 crate13 truck0)
    (load hoist1 crate13 truck1)
    (load hoist1 crate14 truck0)
    (load hoist1 crate14 truck1)
    (load hoist2 crate0 truck0)
    (load hoist2 crate0 truck1)
    (load hoist2 crate1 truck0)
    (load hoist2 crate1 truck1)
    (load hoist2 crate2 truck0)
    (load hoist2 crate2 truck1)
    (load hoist2 crate3 truck0)
    (load hoist2 crate3 truck1)
    (load hoist2 crate4 truck0)
    (load hoist2 crate4 truck1)
    (load hoist2 crate5 truck0)
    (load hoist2 crate5 truck1)
    (load hoist2 crate6 truck0)
    (load hoist2 crate6 truck1)
    (load hoist2 crate7 truck0)
    (load hoist2 crate7 truck1)
    (load hoist2 crate8 truck0)
    (load hoist2 crate8 truck1)
    (load hoist2 crate9 truck0)
    (load hoist2 crate9 truck1)
    (load hoist2 crate10 truck0)
    (load hoist2 crate10 truck1)
    (load hoist2 crate11 truck0)
    (load hoist2 crate11 truck1)
    (load hoist2 crate12 truck0)
    (load hoist2 crate12 truck1)
    (load hoist2 crate13 truck0)
    (load hoist2 crate13 truck1)
    (load hoist2 crate14 truck0)
    (load hoist2 crate14 truck1)
    (unload hoist0 crate0 truck0)
    (unload hoist0 crate0 truck1)
    (unload hoist0 crate1 truck0)
    (unload hoist0 crate1 truck1)
    (unload hoist0 crate2 truck0)
    (unload hoist0 crate2 truck1)
    (unload hoist0 crate3 truck0)
    (unload hoist0 crate3 truck1)
    (unload hoist0 crate4 truck0)
    (unload hoist0 crate4 truck1)
    (unload hoist0 crate5 truck0)
    (unload hoist0 crate5 truck1)
    (unload hoist0 crate6 truck0)
    (unload hoist0 crate6 truck1)
    (unload hoist0 crate7 truck0)
    (unload hoist0 crate7 truck1)
    (unload hoist0 crate8 truck0)
    (unload hoist0 crate8 truck1)
    (unload hoist0 crate9 truck0)
    (unload hoist0 crate9 truck1)
    (unload hoist0 crate10 truck0)
    (unload hoist0 crate10 truck1)
    (unload hoist0 crate11 truck0)
    (unload hoist0 crate11 truck1)
    (unload hoist0 crate12 truck0)
    (unload hoist0 crate12 truck1)
    (unload hoist0 crate13 truck0)
    (unload hoist0 crate13 truck1)
    (unload hoist0 crate14 truck0)
    (unload hoist0 crate14 truck1)
    (unload hoist1 crate0 truck0)
    (unload hoist1 crate0 truck1)
    (unload hoist1 crate1 truck0)
    (unload hoist1 crate1 truck1)
    (unload hoist1 crate2 truck0)
    (unload hoist1 crate2 truck1)
    (unload hoist1 crate3 truck0)
    (unload hoist1 crate3 truck1)
    (unload hoist1 crate4 truck0)
    (unload hoist1 crate4 truck1)
    (unload hoist1 crate5 truck0)
    (unload hoist1 crate5 truck1)
    (unload hoist1 crate6 truck0)
    (unload hoist1 crate6 truck1)
    (unload hoist1 crate7 truck0)
    (unload hoist1 crate7 truck1)
    (unload hoist1 crate8 truck0)
    (unload hoist1 crate8 truck1)
    (unload hoist1 crate9 truck0)
    (unload hoist1 crate9 truck1)
    (unload hoist1 crate10 truck0)
    (unload hoist1 crate10 truck1)
    (unload hoist1 crate11 truck0)
    (unload hoist1 crate11 truck1)
    (unload hoist1 crate12 truck0)
    (unload hoist1 crate12 truck1)
    (unload hoist1 crate13 truck0)
    (unload hoist1 crate13 truck1)
    (unload hoist1 crate14 truck0)
    (unload hoist1 crate14 truck1)
    (unload hoist2 crate0 truck0)
    (unload hoist2 crate0 truck1)
    (unload hoist2 crate1 truck0)
    (unload hoist2 crate1 truck1)
    (unload hoist2 crate2 truck0)
    (unload hoist2 crate2 truck1)
    (unload hoist2 crate3 truck0)
    (unload hoist2 crate3 truck1)
    (unload hoist2 crate4 truck0)
    (unload hoist2 crate4 truck1)
    (unload hoist2 crate5 truck0)
    (unload hoist2 crate5 truck1)
    (unload hoist2 crate6 truck0)
    (unload hoist2 crate6 truck1)
    (unload hoist2 crate7 truck0)
    (unload hoist2 crate7 truck1)
    (unload hoist2 crate8 truck0)
    (unload hoist2 crate8 truck1)
    (unload hoist2 crate9 truck0)
    (unload hoist2 crate9 truck1)
    (unload hoist2 crate10 truck0)
    (unload hoist2 crate10 truck1)
    (unload hoist2 crate11 truck0)
    (unload hoist2 crate11 truck1)
    (unload hoist2 crate12 truck0)
    (unload hoist2 crate12 truck1)
    (unload hoist2 crate13 truck0)
    (unload hoist2 crate13 truck1)
    (unload hoist2 crate14 truck0)
    (unload hoist2 crate14 truck1)
    )

(:goal (and
		(on crate0 crate5)
		(on crate1 crate2)
		(on crate2 crate10)
		(on crate3 pallet0)
		(on crate4 crate6)
		(on crate5 pallet5)
		(on crate6 pallet4)
		(on crate9 crate1)
		(on crate10 pallet2)
		(on crate11 pallet1)
		(on crate12 crate14)
		(on crate13 crate3)
		(on crate14 pallet3)
	)
))
