(define (problem ferry-l5-c8) (:domain ferry)
  (:objects
        c0 c1 c2 c3 c4 c5 c6 c7 - obj
        ferry - ferry
        l0 l1 l2 l3 l4 - obj
  )
  (:init
    ;; Problem-relevant predicates
    (at c0 l0)
    (at c1 l1)
    (at c2 l2)
    (at c3 l3)
    (at c4 l4)
    (at c5 l0)
    (at c6 l1)
    (at c7 l2)
    (at-ferry l0)
    (car c0)
    (car c1)
    (car c2)
    (car c3)
    (car c4)
    (car c5)
    (car c6)
    (car c7)
    (empty-ferry ferry)
    (location l0)
    (location l1)
    (location l2)
    (location l3)
    (location l4)
    (not-eq l0 l1)
    (not-eq l0 l2)
    (not-eq l0 l3)
    (not-eq l0 l4)
    (not-eq l1 l0)
    (not-eq l1 l2)
    (not-eq l1 l3)
    (not-eq l1 l4)
    (not-eq l2 l0)
    (not-eq l2 l1)
    (not-eq l2 l3)
    (not-eq l2 l4)
    (not-eq l3 l0)
    (not-eq l3 l1)
    (not-eq l3 l2)
    (not-eq l3 l4)
    (not-eq l4 l0)
    (not-eq l4 l1)
    (not-eq l4 l2)
    (not-eq l4 l3)

    ;; Action predicates (board, debark, sail)
    (board c0)
    (board c1)
    (board c2)
    (board c3)
    (board c4)
    (board c5)
    (board c6)
    (board c7)
    (board l0)
    (board l1)
    (board l2)
    (board l3)
    (board l4)
    (debark c0)
    (debark c1)
    (debark c2)
    (debark c3)
    (debark c4)
    (debark c5)
    (debark c6)
    (debark c7)
    (debark l0)
    (debark l1)
    (debark l2)
    (debark l3)
    (debark l4)
    (sail c0)
    (sail c1)
    (sail c2)
    (sail c3)
    (sail c4)
    (sail c5)
    (sail c6)
    (sail c7)
    (sail l0)
    (sail l1)
    (sail l2)
    (sail l3)
    (sail l4)
  )
  (:goal         (and (at c0 l1) (at c1 l2) (at c2 l3) (at c3 l4) (at c4 l1) (at c5 l2) (at c6 l3) (at c7 l4)))
)
