(define (problem mixed-f9-p8-u0-v0-g0-a0-n0-a0-b0-n0-f0-r0) (:domain miconic)
  (:objects
        f0 f1 f2 f3 f4 f5 f6 f7 f8 - floor
        p0 p1 p2 p3 p4 p5 p6 p7 - passenger
  )
  (:init
    ;; Problem-relevant predicates
    (lift-at f0)
    (origin p0 f0)
    (destin p0 f1)
    (origin p1 f1)
    (destin p1 f2)
    (origin p2 f2)
    (destin p2 f3)
    (origin p3 f3)
    (destin p3 f4)
    (origin p4 f4)
    (destin p4 f5)
    (origin p5 f5)
    (destin p5 f6)
    (origin p6 f6)
    (destin p6 f7)
    (origin p7 f7)
    (destin p7 f8)

    (above f0 f1)
    (above f1 f2)
    (above f2 f3)
    (above f3 f4)
    (above f4 f5)
    (above f5 f6)
    (above f6 f7)
    (above f7 f8)

    ;; Grounded action predicates
    (up)
    (down)
    (board p0)
    (depart p0)
    (board p1)
    (depart p1)
    (board p2)
    (depart p2)
    (board p3)
    (depart p3)
    (board p4)
    (depart p4)
    (board p5)
    (depart p5)
    (board p6)
    (depart p6)
    (board p7)
    (depart p7)
  )
  (:goal
	(and
	(served p0)
	(served p1)
	(served p2)
	(served p3)
	(served p4)
	(served p5)
	(served p6)
	(served p7)))
)
