; Problem taken from https://github.com/AI-Planning/classical-domains

(define (problem DLOG-5-5-25)
	(:domain driverlog)
	(:objects
	driver1
	driver2
	driver3
	driver4
	driver5
	truck1
	truck2
	truck3
	truck4
	truck5
	package1
	package2
	package3
	package4
	package5
	package6
	package7
	package8
	package9
	package10
	package11
	package12
	package13
	package14
	package15
	package16
	package17
	package18
	package19
	package20
	package21
	package22
	package23
	package24
	package25
	s0
	s1
	s2
	s3
	s4
	s5
	s6
	s7
	s8
	s9
	s10
	s11
	s12
	s13
	s14
	s15
	s16
	s17
	s18
	s19
	)
	(:init
	(at driver1 s3)
	(driver driver1)
	(at driver2 s11)
	(driver driver2)
	(at driver3 s8)
	(driver driver3)
	(at driver4 s12)
	(driver driver4)
	(at driver5 s3)
	(driver driver5)
	(at truck1 s4)
	(empty truck1)
	(truck truck1)
	(at truck2 s8)
	(empty truck2)
	(truck truck2)
	(at truck3 s19)
	(empty truck3)
	(truck truck3)
	(at truck4 s0)
	(empty truck4)
	(truck truck4)
	(at truck5 s6)
	(empty truck5)
	(truck truck5)
	(at package1 s19)
	(obj package1)
	(at package2 s17)
	(obj package2)
	(at package3 s4)
	(obj package3)
	(at package4 s10)
	(obj package4)
	(at package5 s5)
	(obj package5)
	(at package6 s18)
	(obj package6)
	(at package7 s7)
	(obj package7)
	(at package8 s17)
	(obj package8)
	(at package9 s9)
	(obj package9)
	(at package10 s2)
	(obj package10)
	(at package11 s15)
	(obj package11)
	(at package12 s5)
	(obj package12)
	(at package13 s8)
	(obj package13)
	(at package14 s5)
	(obj package14)
	(at package15 s9)
	(obj package15)
	(at package16 s19)
	(obj package16)
	(at package17 s12)
	(obj package17)
	(at package18 s16)
	(obj package18)
	(at package19 s11)
	(obj package19)
	(at package20 s9)
	(obj package20)
	(at package21 s4)
	(obj package21)
	(at package22 s18)
	(obj package22)
	(at package23 s2)
	(obj package23)
	(at package24 s6)
	(obj package24)
	(at package25 s1)
	(obj package25)
	(location s0)
	(location s1)
	(location s2)
	(location s3)
	(location s4)
	(location s5)
	(location s6)
	(location s7)
	(location s8)
	(location s9)
	(location s10)
	(location s11)
	(location s12)
	(location s13)
	(location s14)
	(location s15)
	(location s16)
	(location s17)
	(location s18)
	(location s19)

    ; action literals
    (load-truck truck1 package1)
    (load-truck truck1 package10)
    (load-truck truck1 package11)
    (load-truck truck1 package12)
    (load-truck truck1 package13)
    (load-truck truck1 package14)
    (load-truck truck1 package15)
    (load-truck truck1 package16)
    (load-truck truck1 package17)
    (load-truck truck1 package18)
    (load-truck truck1 package19)
    (load-truck truck1 package2)
    (load-truck truck1 package20)
    (load-truck truck1 package21)
    (load-truck truck1 package22)
    (load-truck truck1 package23)
    (load-truck truck1 package24)
    (load-truck truck1 package25)
    (load-truck truck1 package3)
    (load-truck truck1 package4)
    (load-truck truck1 package5)
    (load-truck truck1 package6)
    (load-truck truck1 package7)
    (load-truck truck1 package8)
    (load-truck truck1 package9)
    (load-truck truck2 package1)
    (load-truck truck2 package10)
    (load-truck truck2 package11)
    (load-truck truck2 package12)
    (load-truck truck2 package13)
    (load-truck truck2 package14)
    (load-truck truck2 package15)
    (load-truck truck2 package16)
    (load-truck truck2 package17)
    (load-truck truck2 package18)
    (load-truck truck2 package19)
    (load-truck truck2 package2)
    (load-truck truck2 package20)
    (load-truck truck2 package21)
    (load-truck truck2 package22)
    (load-truck truck2 package23)
    (load-truck truck2 package24)
    (load-truck truck2 package25)
    (load-truck truck2 package3)
    (load-truck truck2 package4)
    (load-truck truck2 package5)
    (load-truck truck2 package6)
    (load-truck truck2 package7)
    (load-truck truck2 package8)
    (load-truck truck2 package9)
    (load-truck truck3 package1)
    (load-truck truck3 package10)
    (load-truck truck3 package11)
    (load-truck truck3 package12)
    (load-truck truck3 package13)
    (load-truck truck3 package14)
    (load-truck truck3 package15)
    (load-truck truck3 package16)
    (load-truck truck3 package17)
    (load-truck truck3 package18)
    (load-truck truck3 package19)
    (load-truck truck3 package2)
    (load-truck truck3 package20)
    (load-truck truck3 package21)
    (load-truck truck3 package22)
    (load-truck truck3 package23)
    (load-truck truck3 package24)
    (load-truck truck3 package25)
    (load-truck truck3 package3)
    (load-truck truck3 package4)
    (load-truck truck3 package5)
    (load-truck truck3 package6)
    (load-truck truck3 package7)
    (load-truck truck3 package8)
    (load-truck truck3 package9)
    (load-truck truck4 package1)
    (load-truck truck4 package10)
    (load-truck truck4 package11)
    (load-truck truck4 package12)
    (load-truck truck4 package13)
    (load-truck truck4 package14)
    (load-truck truck4 package15)
    (load-truck truck4 package16)
    (load-truck truck4 package17)
    (load-truck truck4 package18)
    (load-truck truck4 package19)
    (load-truck truck4 package2)
    (load-truck truck4 package20)
    (load-truck truck4 package21)
    (load-truck truck4 package22)
    (load-truck truck4 package23)
    (load-truck truck4 package24)
    (load-truck truck4 package25)
    (load-truck truck4 package3)
    (load-truck truck4 package4)
    (load-truck truck4 package5)
    (load-truck truck4 package6)
    (load-truck truck4 package7)
    (load-truck truck4 package8)
    (load-truck truck4 package9)
    (load-truck truck5 package1)
    (load-truck truck5 package10)
    (load-truck truck5 package11)
    (load-truck truck5 package12)
    (load-truck truck5 package13)
    (load-truck truck5 package14)
    (load-truck truck5 package15)
    (load-truck truck5 package16)
    (load-truck truck5 package17)
    (load-truck truck5 package18)
    (load-truck truck5 package19)
    (load-truck truck5 package2)
    (load-truck truck5 package20)
    (load-truck truck5 package21)
    (load-truck truck5 package22)
    (load-truck truck5 package23)
    (load-truck truck5 package24)
    (load-truck truck5 package25)
    (load-truck truck5 package3)
    (load-truck truck5 package4)
    (load-truck truck5 package5)
    (load-truck truck5 package6)
    (load-truck truck5 package7)
    (load-truck truck5 package8)
    (load-truck truck5 package9)
    (unload-truck package1 truck1)
    (unload-truck package1 truck2)
    (unload-truck package1 truck3)
    (unload-truck package1 truck4)
    (unload-truck package1 truck5)
    (unload-truck package10 truck1)
    (unload-truck package10 truck2)
    (unload-truck package10 truck3)
    (unload-truck package10 truck4)
    (unload-truck package10 truck5)
    (unload-truck package11 truck1)
    (unload-truck package11 truck2)
    (unload-truck package11 truck3)
    (unload-truck package11 truck4)
    (unload-truck package11 truck5)
    (unload-truck package12 truck1)
    (unload-truck package12 truck2)
    (unload-truck package12 truck3)
    (unload-truck package12 truck4)
    (unload-truck package12 truck5)
    (unload-truck package13 truck1)
    (unload-truck package13 truck2)
    (unload-truck package13 truck3)
    (unload-truck package13 truck4)
    (unload-truck package13 truck5)
    (unload-truck package14 truck1)
    (unload-truck package14 truck2)
    (unload-truck package14 truck3)
    (unload-truck package14 truck4)
    (unload-truck package14 truck5)
    (unload-truck package15 truck1)
    (unload-truck package15 truck2)
    (unload-truck package15 truck3)
    (unload-truck package15 truck4)
    (unload-truck package15 truck5)
    (unload-truck package16 truck1)
    (unload-truck package16 truck2)
    (unload-truck package16 truck3)
    (unload-truck package16 truck4)
    (unload-truck package16 truck5)
    (unload-truck package17 truck1)
    (unload-truck package17 truck2)
    (unload-truck package17 truck3)
    (unload-truck package17 truck4)
    (unload-truck package17 truck5)
    (unload-truck package18 truck1)
    (unload-truck package18 truck2)
    (unload-truck package18 truck3)
    (unload-truck package18 truck4)
    (unload-truck package18 truck5)
    (unload-truck package19 truck1)
    (unload-truck package19 truck2)
    (unload-truck package19 truck3)
    (unload-truck package19 truck4)
    (unload-truck package19 truck5)
    (unload-truck package2 truck1)
    (unload-truck package2 truck2)
    (unload-truck package2 truck3)
    (unload-truck package2 truck4)
    (unload-truck package2 truck5)
    (unload-truck package20 truck1)
    (unload-truck package20 truck2)
    (unload-truck package20 truck3)
    (unload-truck package20 truck4)
    (unload-truck package20 truck5)
    (unload-truck package21 truck1)
    (unload-truck package21 truck2)
    (unload-truck package21 truck3)
    (unload-truck package21 truck4)
    (unload-truck package21 truck5)
    (unload-truck package22 truck1)
    (unload-truck package22 truck2)
    (unload-truck package22 truck3)
    (unload-truck package22 truck4)
    (unload-truck package22 truck5)
    (unload-truck package23 truck1)
    (unload-truck package23 truck2)
    (unload-truck package23 truck3)
    (unload-truck package23 truck4)
    (unload-truck package23 truck5)
    (unload-truck package24 truck1)
    (unload-truck package24 truck2)
    (unload-truck package24 truck3)
    (unload-truck package24 truck4)
    (unload-truck package24 truck5)
    (unload-truck package25 truck1)
    (unload-truck package25 truck2)
    (unload-truck package25 truck3)
    (unload-truck package25 truck4)
    (unload-truck package25 truck5)
    (unload-truck package3 truck1)
    (unload-truck package3 truck2)
    (unload-truck package3 truck3)
    (unload-truck package3 truck4)
    (unload-truck package3 truck5)
    (unload-truck package4 truck1)
    (unload-truck package4 truck2)
    (unload-truck package4 truck3)
    (unload-truck package4 truck4)
    (unload-truck package4 truck5)
    (unload-truck package5 truck1)
    (unload-truck package5 truck2)
    (unload-truck package5 truck3)
    (unload-truck package5 truck4)
    (unload-truck package5 truck5)
    (unload-truck package6 truck1)
    (unload-truck package6 truck2)
    (unload-truck package6 truck3)
    (unload-truck package6 truck4)
    (unload-truck package6 truck5)
    (unload-truck package7 truck1)
    (unload-truck package7 truck2)
    (unload-truck package7 truck3)
    (unload-truck package7 truck4)
    (unload-truck package7 truck5)
    (unload-truck package8 truck1)
    (unload-truck package8 truck2)
    (unload-truck package8 truck3)
    (unload-truck package8 truck4)
    (unload-truck package8 truck5)
    (unload-truck package9 truck1)
    (unload-truck package9 truck2)
    (unload-truck package9 truck3)
    (unload-truck package9 truck4)
    (unload-truck package9 truck5)
    (board-truck driver1 truck1)
    (board-truck driver1 truck2)
    (board-truck driver1 truck3)
    (board-truck driver1 truck4)
    (board-truck driver1 truck5)
    (board-truck driver2 truck1)
    (board-truck driver2 truck2)
    (board-truck driver2 truck3)
    (board-truck driver2 truck4)
    (board-truck driver2 truck5)
    (board-truck driver3 truck1)
    (board-truck driver3 truck2)
    (board-truck driver3 truck3)
    (board-truck driver3 truck4)
    (board-truck driver3 truck5)
    (board-truck driver4 truck1)
    (board-truck driver4 truck2)
    (board-truck driver4 truck3)
    (board-truck driver4 truck4)
    (board-truck driver4 truck5)
    (board-truck driver5 truck1)
    (board-truck driver5 truck2)
    (board-truck driver5 truck3)
    (board-truck driver5 truck4)
    (board-truck driver5 truck5)
    (disembark-truck driver1 truck1)
    (disembark-truck driver1 truck2)
    (disembark-truck driver1 truck3)
    (disembark-truck driver1 truck4)
    (disembark-truck driver1 truck5)
    (disembark-truck driver2 truck1)
    (disembark-truck driver2 truck2)
    (disembark-truck driver2 truck3)
    (disembark-truck driver2 truck4)
    (disembark-truck driver2 truck5)
    (disembark-truck driver3 truck1)
    (disembark-truck driver3 truck2)
    (disembark-truck driver3 truck3)
    (disembark-truck driver3 truck4)
    (disembark-truck driver3 truck5)
    (disembark-truck driver4 truck1)
    (disembark-truck driver4 truck2)
    (disembark-truck driver4 truck3)
    (disembark-truck driver4 truck4)
    (disembark-truck driver4 truck5)
    (disembark-truck driver5 truck1)
    (disembark-truck driver5 truck2)
    (disembark-truck driver5 truck3)
    (disembark-truck driver5 truck4)
    (disembark-truck driver5 truck5)
    (drive-truck truck1 s0)
    (drive-truck truck1 s1)
    (drive-truck truck1 s10)
    (drive-truck truck1 s11)
    (drive-truck truck1 s12)
    (drive-truck truck1 s13)
    (drive-truck truck1 s14)
    (drive-truck truck1 s15)
    (drive-truck truck1 s16)
    (drive-truck truck1 s17)
    (drive-truck truck1 s18)
    (drive-truck truck1 s19)
    (drive-truck truck1 s2)
    (drive-truck truck1 s3)
    (drive-truck truck1 s4)
    (drive-truck truck1 s5)
    (drive-truck truck1 s6)
    (drive-truck truck1 s7)
    (drive-truck truck1 s8)
    (drive-truck truck1 s9)
    (drive-truck truck2 s0)
    (drive-truck truck2 s1)
    (drive-truck truck2 s10)
    (drive-truck truck2 s11)
    (drive-truck truck2 s12)
    (drive-truck truck2 s13)
    (drive-truck truck2 s14)
    (drive-truck truck2 s15)
    (drive-truck truck2 s16)
    (drive-truck truck2 s17)
    (drive-truck truck2 s18)
    (drive-truck truck2 s19)
    (drive-truck truck2 s2)
    (drive-truck truck2 s3)
    (drive-truck truck2 s4)
    (drive-truck truck2 s5)
    (drive-truck truck2 s6)
    (drive-truck truck2 s7)
    (drive-truck truck2 s8)
    (drive-truck truck2 s9)
    (drive-truck truck3 s0)
    (drive-truck truck3 s1)
    (drive-truck truck3 s10)
    (drive-truck truck3 s11)
    (drive-truck truck3 s12)
    (drive-truck truck3 s13)
    (drive-truck truck3 s14)
    (drive-truck truck3 s15)
    (drive-truck truck3 s16)
    (drive-truck truck3 s17)
    (drive-truck truck3 s18)
    (drive-truck truck3 s19)
    (drive-truck truck3 s2)
    (drive-truck truck3 s3)
    (drive-truck truck3 s4)
    (drive-truck truck3 s5)
    (drive-truck truck3 s6)
    (drive-truck truck3 s7)
    (drive-truck truck3 s8)
    (drive-truck truck3 s9)
    (drive-truck truck4 s0)
    (drive-truck truck4 s1)
    (drive-truck truck4 s10)
    (drive-truck truck4 s11)
    (drive-truck truck4 s12)
    (drive-truck truck4 s13)
    (drive-truck truck4 s14)
    (drive-truck truck4 s15)
    (drive-truck truck4 s16)
    (drive-truck truck4 s17)
    (drive-truck truck4 s18)
    (drive-truck truck4 s19)
    (drive-truck truck4 s2)
    (drive-truck truck4 s3)
    (drive-truck truck4 s4)
    (drive-truck truck4 s5)
    (drive-truck truck4 s6)
    (drive-truck truck4 s7)
    (drive-truck truck4 s8)
    (drive-truck truck4 s9)
    (drive-truck truck5 s0)
    (drive-truck truck5 s1)
    (drive-truck truck5 s10)
    (drive-truck truck5 s11)
    (drive-truck truck5 s12)
    (drive-truck truck5 s13)
    (drive-truck truck5 s14)
    (drive-truck truck5 s15)
    (drive-truck truck5 s16)
    (drive-truck truck5 s17)
    (drive-truck truck5 s18)
    (drive-truck truck5 s19)
    (drive-truck truck5 s2)
    (drive-truck truck5 s3)
    (drive-truck truck5 s4)
    (drive-truck truck5 s5)
    (drive-truck truck5 s6)
    (drive-truck truck5 s7)
    (drive-truck truck5 s8)
    (drive-truck truck5 s9)
    (walk driver1 s0)
    (walk driver1 s1)
    (walk driver1 s10)
    (walk driver1 s11)
    (walk driver1 s12)
    (walk driver1 s13)
    (walk driver1 s14)
    (walk driver1 s15)
    (walk driver1 s16)
    (walk driver1 s17)
    (walk driver1 s18)
    (walk driver1 s19)
    (walk driver1 s2)
    (walk driver1 s3)
    (walk driver1 s4)
    (walk driver1 s5)
    (walk driver1 s6)
    (walk driver1 s7)
    (walk driver1 s8)
    (walk driver1 s9)
    (walk driver2 s0)
    (walk driver2 s1)
    (walk driver2 s10)
    (walk driver2 s11)
    (walk driver2 s12)
    (walk driver2 s13)
    (walk driver2 s14)
    (walk driver2 s15)
    (walk driver2 s16)
    (walk driver2 s17)
    (walk driver2 s18)
    (walk driver2 s19)
    (walk driver2 s2)
    (walk driver2 s3)
    (walk driver2 s4)
    (walk driver2 s5)
    (walk driver2 s6)
    (walk driver2 s7)
    (walk driver2 s8)
    (walk driver2 s9)
    (walk driver3 s0)
    (walk driver3 s1)
    (walk driver3 s10)
    (walk driver3 s11)
    (walk driver3 s12)
    (walk driver3 s13)
    (walk driver3 s14)
    (walk driver3 s15)
    (walk driver3 s16)
    (walk driver3 s17)
    (walk driver3 s18)
    (walk driver3 s19)
    (walk driver3 s2)
    (walk driver3 s3)
    (walk driver3 s4)
    (walk driver3 s5)
    (walk driver3 s6)
    (walk driver3 s7)
    (walk driver3 s8)
    (walk driver3 s9)
    (walk driver4 s0)
    (walk driver4 s1)
    (walk driver4 s10)
    (walk driver4 s11)
    (walk driver4 s12)
    (walk driver4 s13)
    (walk driver4 s14)
    (walk driver4 s15)
    (walk driver4 s16)
    (walk driver4 s17)
    (walk driver4 s18)
    (walk driver4 s19)
    (walk driver4 s2)
    (walk driver4 s3)
    (walk driver4 s4)
    (walk driver4 s5)
    (walk driver4 s6)
    (walk driver4 s7)
    (walk driver4 s8)
    (walk driver4 s9)
    (walk driver5 s0)
    (walk driver5 s1)
    (walk driver5 s10)
    (walk driver5 s11)
    (walk driver5 s12)
    (walk driver5 s13)
    (walk driver5 s14)
    (walk driver5 s15)
    (walk driver5 s16)
    (walk driver5 s17)
    (walk driver5 s18)
    (walk driver5 s19)
    (walk driver5 s2)
    (walk driver5 s3)
    (walk driver5 s4)
    (walk driver5 s5)
    (walk driver5 s6)
    (walk driver5 s7)
    (walk driver5 s8)
    (walk driver5 s9)
    )
	(:goal (and
	(at driver1 s16)
	(at driver2 s13)
	(at driver4 s7)
	(at driver5 s5)
	(at truck1 s2)
	(at truck2 s11)
	(at truck3 s10)
	(at truck4 s3)
	(at truck5 s16)
	(at package1 s19)
	(at package2 s10)
	(at package3 s19)
	(at package4 s11)
	(at package5 s14)
	(at package6 s18)
	(at package7 s7)
	(at package8 s6)
	(at package9 s7)
	(at package10 s14)
	(at package11 s13)
	(at package12 s11)
	(at package13 s15)
	(at package14 s6)
	(at package15 s11)
	(at package16 s10)
	(at package17 s17)
	(at package18 s15)
	(at package19 s4)
	(at package20 s7)
	(at package21 s3)
	(at package22 s8)
	(at package23 s17)
	(at package24 s2)
	(at package25 s12)
	))


)
