; Problem taken from https://github.com/AI-Planning/classical-domains

(define (problem DLOG-3-3-6)
	(:domain driverlog)
	(:objects
	driver1
	driver2
	driver3
	truck1
	truck2
	truck3
	package1
	package2
	package3
	package4
	package5
	package6
	s0
	s1
	s2
	s3
	s4
	s5
	s6
	s7
	s8
	s9
	)
	(:init
	(at driver1 s9)
	(driver driver1)
	(at driver2 s2)
	(driver driver2)
	(at driver3 s2)
	(driver driver3)
	(at truck1 s2)
	(empty truck1)
	(truck truck1)
	(at truck2 s1)
	(empty truck2)
	(truck truck2)
	(at truck3 s8)
	(empty truck3)
	(truck truck3)
	(at package1 s5)
	(obj package1)
	(at package2 s5)
	(obj package2)
	(at package3 s9)
	(obj package3)
	(at package4 s3)
	(obj package4)
	(at package5 s1)
	(obj package5)
	(at package6 s4)
	(obj package6)
	(location s0)
	(location s1)
	(location s2)
	(location s3)
	(location s4)
	(location s5)
	(location s6)
	(location s7)
	(location s8)
	(location s9)

    ; action literals
    (load-truck truck1 package1)
    (load-truck truck1 package2)
    (load-truck truck1 package3)
    (load-truck truck1 package4)
    (load-truck truck1 package5)
    (load-truck truck1 package6)
    (load-truck truck2 package1)
    (load-truck truck2 package2)
    (load-truck truck2 package3)
    (load-truck truck2 package4)
    (load-truck truck2 package5)
    (load-truck truck2 package6)
    (load-truck truck3 package1)
    (load-truck truck3 package2)
    (load-truck truck3 package3)
    (load-truck truck3 package4)
    (load-truck truck3 package5)
    (load-truck truck3 package6)
    (unload-truck package1 truck1)
    (unload-truck package1 truck2)
    (unload-truck package1 truck3)
    (unload-truck package2 truck1)
    (unload-truck package2 truck2)
    (unload-truck package2 truck3)
    (unload-truck package3 truck1)
    (unload-truck package3 truck2)
    (unload-truck package3 truck3)
    (unload-truck package4 truck1)
    (unload-truck package4 truck2)
    (unload-truck package4 truck3)
    (unload-truck package5 truck1)
    (unload-truck package5 truck2)
    (unload-truck package5 truck3)
    (unload-truck package6 truck1)
    (unload-truck package6 truck2)
    (unload-truck package6 truck3)
    (board-truck driver1 truck1)
    (board-truck driver1 truck2)
    (board-truck driver1 truck3)
    (board-truck driver2 truck1)
    (board-truck driver2 truck2)
    (board-truck driver2 truck3)
    (board-truck driver3 truck1)
    (board-truck driver3 truck2)
    (board-truck driver3 truck3)
    (disembark-truck driver1 truck1)
    (disembark-truck driver1 truck2)
    (disembark-truck driver1 truck3)
    (disembark-truck driver2 truck1)
    (disembark-truck driver2 truck2)
    (disembark-truck driver2 truck3)
    (disembark-truck driver3 truck1)
    (disembark-truck driver3 truck2)
    (disembark-truck driver3 truck3)
    (drive-truck truck1 s0)
    (drive-truck truck1 s1)
    (drive-truck truck1 s2)
    (drive-truck truck1 s3)
    (drive-truck truck1 s4)
    (drive-truck truck1 s5)
    (drive-truck truck1 s6)
    (drive-truck truck1 s7)
    (drive-truck truck1 s8)
    (drive-truck truck1 s9)
    (drive-truck truck2 s0)
    (drive-truck truck2 s1)
    (drive-truck truck2 s2)
    (drive-truck truck2 s3)
    (drive-truck truck2 s4)
    (drive-truck truck2 s5)
    (drive-truck truck2 s6)
    (drive-truck truck2 s7)
    (drive-truck truck2 s8)
    (drive-truck truck2 s9)
    (drive-truck truck3 s0)
    (drive-truck truck3 s1)
    (drive-truck truck3 s2)
    (drive-truck truck3 s3)
    (drive-truck truck3 s4)
    (drive-truck truck3 s5)
    (drive-truck truck3 s6)
    (drive-truck truck3 s7)
    (drive-truck truck3 s8)
    (drive-truck truck3 s9)
    (walk driver1 s0)
    (walk driver1 s1)
    (walk driver1 s2)
    (walk driver1 s3)
    (walk driver1 s4)
    (walk driver1 s5)
    (walk driver1 s6)
    (walk driver1 s7)
    (walk driver1 s8)
    (walk driver1 s9)
    (walk driver2 s0)
    (walk driver2 s1)
    (walk driver2 s2)
    (walk driver2 s3)
    (walk driver2 s4)
    (walk driver2 s5)
    (walk driver2 s6)
    (walk driver2 s7)
    (walk driver2 s8)
    (walk driver2 s9)
    (walk driver3 s0)
    (walk driver3 s1)
    (walk driver3 s2)
    (walk driver3 s3)
    (walk driver3 s4)
    (walk driver3 s5)
    (walk driver3 s6)
    (walk driver3 s7)
    (walk driver3 s8)
    (walk driver3 s9)
    )
	(:goal (and
	(at driver3 s1)
	(at truck1 s6)
	(at truck3 s3)
	(at package1 s0)
	(at package2 s0)
	(at package3 s4)
	(at package4 s4)
	(at package5 s3)
	(at package6 s5)
	))


)
