; Problem taken from https://github.com/AI-Planning/classical-domains

(define (problem DLOG-5-5-10)
	(:domain driverlog)
	(:objects
	driver1
	driver2
	driver3
	driver4
	driver5
	truck1
	truck2
	truck3
	truck4
	truck5
	package1
	package2
	package3
	package4
	package5
	package6
	package7
	package8
	package9
	package10
	s0
	s1
	s2
	s3
	s4
	s5
	s6
	s7
	s8
	s9
	s10
	s11
	s12
	s13
	s14
	)
	(:init
	(at driver1 s14)
	(driver driver1)
	(at driver2 s1)
	(driver driver2)
	(at driver3 s0)
	(driver driver3)
	(at driver4 s10)
	(driver driver4)
	(at driver5 s12)
	(driver driver5)
	(at truck1 s7)
	(empty truck1)
	(truck truck1)
	(at truck2 s1)
	(empty truck2)
	(truck truck2)
	(at truck3 s2)
	(empty truck3)
	(truck truck3)
	(at truck4 s13)
	(empty truck4)
	(truck truck4)
	(at truck5 s3)
	(empty truck5)
	(truck truck5)
	(at package1 s0)
	(obj package1)
	(at package2 s14)
	(obj package2)
	(at package3 s4)
	(obj package3)
	(at package4 s3)
	(obj package4)
	(at package5 s11)
	(obj package5)
	(at package6 s7)
	(obj package6)
	(at package7 s12)
	(obj package7)
	(at package8 s8)
	(obj package8)
	(at package9 s2)
	(obj package9)
	(at package10 s7)
	(obj package10)
	(location s0)
	(location s1)
	(location s2)
	(location s3)
	(location s4)
	(location s5)
	(location s6)
	(location s7)
	(location s8)
	(location s9)
	(location s10)
	(location s11)
	(location s12)
	(location s13)
	(location s14)

    ; action literals
    (load-truck truck1 package1)
    (load-truck truck1 package10)
    (load-truck truck1 package2)
    (load-truck truck1 package3)
    (load-truck truck1 package4)
    (load-truck truck1 package5)
    (load-truck truck1 package6)
    (load-truck truck1 package7)
    (load-truck truck1 package8)
    (load-truck truck1 package9)
    (load-truck truck2 package1)
    (load-truck truck2 package10)
    (load-truck truck2 package2)
    (load-truck truck2 package3)
    (load-truck truck2 package4)
    (load-truck truck2 package5)
    (load-truck truck2 package6)
    (load-truck truck2 package7)
    (load-truck truck2 package8)
    (load-truck truck2 package9)
    (load-truck truck3 package1)
    (load-truck truck3 package10)
    (load-truck truck3 package2)
    (load-truck truck3 package3)
    (load-truck truck3 package4)
    (load-truck truck3 package5)
    (load-truck truck3 package6)
    (load-truck truck3 package7)
    (load-truck truck3 package8)
    (load-truck truck3 package9)
    (load-truck truck4 package1)
    (load-truck truck4 package10)
    (load-truck truck4 package2)
    (load-truck truck4 package3)
    (load-truck truck4 package4)
    (load-truck truck4 package5)
    (load-truck truck4 package6)
    (load-truck truck4 package7)
    (load-truck truck4 package8)
    (load-truck truck4 package9)
    (load-truck truck5 package1)
    (load-truck truck5 package10)
    (load-truck truck5 package2)
    (load-truck truck5 package3)
    (load-truck truck5 package4)
    (load-truck truck5 package5)
    (load-truck truck5 package6)
    (load-truck truck5 package7)
    (load-truck truck5 package8)
    (load-truck truck5 package9)
    (unload-truck package1 truck1)
    (unload-truck package1 truck2)
    (unload-truck package1 truck3)
    (unload-truck package1 truck4)
    (unload-truck package1 truck5)
    (unload-truck package10 truck1)
    (unload-truck package10 truck2)
    (unload-truck package10 truck3)
    (unload-truck package10 truck4)
    (unload-truck package10 truck5)
    (unload-truck package2 truck1)
    (unload-truck package2 truck2)
    (unload-truck package2 truck3)
    (unload-truck package2 truck4)
    (unload-truck package2 truck5)
    (unload-truck package3 truck1)
    (unload-truck package3 truck2)
    (unload-truck package3 truck3)
    (unload-truck package3 truck4)
    (unload-truck package3 truck5)
    (unload-truck package4 truck1)
    (unload-truck package4 truck2)
    (unload-truck package4 truck3)
    (unload-truck package4 truck4)
    (unload-truck package4 truck5)
    (unload-truck package5 truck1)
    (unload-truck package5 truck2)
    (unload-truck package5 truck3)
    (unload-truck package5 truck4)
    (unload-truck package5 truck5)
    (unload-truck package6 truck1)
    (unload-truck package6 truck2)
    (unload-truck package6 truck3)
    (unload-truck package6 truck4)
    (unload-truck package6 truck5)
    (unload-truck package7 truck1)
    (unload-truck package7 truck2)
    (unload-truck package7 truck3)
    (unload-truck package7 truck4)
    (unload-truck package7 truck5)
    (unload-truck package8 truck1)
    (unload-truck package8 truck2)
    (unload-truck package8 truck3)
    (unload-truck package8 truck4)
    (unload-truck package8 truck5)
    (unload-truck package9 truck1)
    (unload-truck package9 truck2)
    (unload-truck package9 truck3)
    (unload-truck package9 truck4)
    (unload-truck package9 truck5)
    (board-truck driver1 truck1)
    (board-truck driver1 truck2)
    (board-truck driver1 truck3)
    (board-truck driver1 truck4)
    (board-truck driver1 truck5)
    (board-truck driver2 truck1)
    (board-truck driver2 truck2)
    (board-truck driver2 truck3)
    (board-truck driver2 truck4)
    (board-truck driver2 truck5)
    (board-truck driver3 truck1)
    (board-truck driver3 truck2)
    (board-truck driver3 truck3)
    (board-truck driver3 truck4)
    (board-truck driver3 truck5)
    (board-truck driver4 truck1)
    (board-truck driver4 truck2)
    (board-truck driver4 truck3)
    (board-truck driver4 truck4)
    (board-truck driver4 truck5)
    (board-truck driver5 truck1)
    (board-truck driver5 truck2)
    (board-truck driver5 truck3)
    (board-truck driver5 truck4)
    (board-truck driver5 truck5)
    (disembark-truck driver1 truck1)
    (disembark-truck driver1 truck2)
    (disembark-truck driver1 truck3)
    (disembark-truck driver1 truck4)
    (disembark-truck driver1 truck5)
    (disembark-truck driver2 truck1)
    (disembark-truck driver2 truck2)
    (disembark-truck driver2 truck3)
    (disembark-truck driver2 truck4)
    (disembark-truck driver2 truck5)
    (disembark-truck driver3 truck1)
    (disembark-truck driver3 truck2)
    (disembark-truck driver3 truck3)
    (disembark-truck driver3 truck4)
    (disembark-truck driver3 truck5)
    (disembark-truck driver4 truck1)
    (disembark-truck driver4 truck2)
    (disembark-truck driver4 truck3)
    (disembark-truck driver4 truck4)
    (disembark-truck driver4 truck5)
    (disembark-truck driver5 truck1)
    (disembark-truck driver5 truck2)
    (disembark-truck driver5 truck3)
    (disembark-truck driver5 truck4)
    (disembark-truck driver5 truck5)
    (drive-truck truck1 s0)
    (drive-truck truck1 s1)
    (drive-truck truck1 s10)
    (drive-truck truck1 s11)
    (drive-truck truck1 s12)
    (drive-truck truck1 s13)
    (drive-truck truck1 s14)
    (drive-truck truck1 s2)
    (drive-truck truck1 s3)
    (drive-truck truck1 s4)
    (drive-truck truck1 s5)
    (drive-truck truck1 s6)
    (drive-truck truck1 s7)
    (drive-truck truck1 s8)
    (drive-truck truck1 s9)
    (drive-truck truck2 s0)
    (drive-truck truck2 s1)
    (drive-truck truck2 s10)
    (drive-truck truck2 s11)
    (drive-truck truck2 s12)
    (drive-truck truck2 s13)
    (drive-truck truck2 s14)
    (drive-truck truck2 s2)
    (drive-truck truck2 s3)
    (drive-truck truck2 s4)
    (drive-truck truck2 s5)
    (drive-truck truck2 s6)
    (drive-truck truck2 s7)
    (drive-truck truck2 s8)
    (drive-truck truck2 s9)
    (drive-truck truck3 s0)
    (drive-truck truck3 s1)
    (drive-truck truck3 s10)
    (drive-truck truck3 s11)
    (drive-truck truck3 s12)
    (drive-truck truck3 s13)
    (drive-truck truck3 s14)
    (drive-truck truck3 s2)
    (drive-truck truck3 s3)
    (drive-truck truck3 s4)
    (drive-truck truck3 s5)
    (drive-truck truck3 s6)
    (drive-truck truck3 s7)
    (drive-truck truck3 s8)
    (drive-truck truck3 s9)
    (drive-truck truck4 s0)
    (drive-truck truck4 s1)
    (drive-truck truck4 s10)
    (drive-truck truck4 s11)
    (drive-truck truck4 s12)
    (drive-truck truck4 s13)
    (drive-truck truck4 s14)
    (drive-truck truck4 s2)
    (drive-truck truck4 s3)
    (drive-truck truck4 s4)
    (drive-truck truck4 s5)
    (drive-truck truck4 s6)
    (drive-truck truck4 s7)
    (drive-truck truck4 s8)
    (drive-truck truck4 s9)
    (drive-truck truck5 s0)
    (drive-truck truck5 s1)
    (drive-truck truck5 s10)
    (drive-truck truck5 s11)
    (drive-truck truck5 s12)
    (drive-truck truck5 s13)
    (drive-truck truck5 s14)
    (drive-truck truck5 s2)
    (drive-truck truck5 s3)
    (drive-truck truck5 s4)
    (drive-truck truck5 s5)
    (drive-truck truck5 s6)
    (drive-truck truck5 s7)
    (drive-truck truck5 s8)
    (drive-truck truck5 s9)
    (walk driver1 s0)
    (walk driver1 s1)
    (walk driver1 s10)
    (walk driver1 s11)
    (walk driver1 s12)
    (walk driver1 s13)
    (walk driver1 s14)
    (walk driver1 s2)
    (walk driver1 s3)
    (walk driver1 s4)
    (walk driver1 s5)
    (walk driver1 s6)
    (walk driver1 s7)
    (walk driver1 s8)
    (walk driver1 s9)
    (walk driver2 s0)
    (walk driver2 s1)
    (walk driver2 s10)
    (walk driver2 s11)
    (walk driver2 s12)
    (walk driver2 s13)
    (walk driver2 s14)
    (walk driver2 s2)
    (walk driver2 s3)
    (walk driver2 s4)
    (walk driver2 s5)
    (walk driver2 s6)
    (walk driver2 s7)
    (walk driver2 s8)
    (walk driver2 s9)
    (walk driver3 s0)
    (walk driver3 s1)
    (walk driver3 s10)
    (walk driver3 s11)
    (walk driver3 s12)
    (walk driver3 s13)
    (walk driver3 s14)
    (walk driver3 s2)
    (walk driver3 s3)
    (walk driver3 s4)
    (walk driver3 s5)
    (walk driver3 s6)
    (walk driver3 s7)
    (walk driver3 s8)
    (walk driver3 s9)
    (walk driver4 s0)
    (walk driver4 s1)
    (walk driver4 s10)
    (walk driver4 s11)
    (walk driver4 s12)
    (walk driver4 s13)
    (walk driver4 s14)
    (walk driver4 s2)
    (walk driver4 s3)
    (walk driver4 s4)
    (walk driver4 s5)
    (walk driver4 s6)
    (walk driver4 s7)
    (walk driver4 s8)
    (walk driver4 s9)
    (walk driver5 s0)
    (walk driver5 s1)
    (walk driver5 s10)
    (walk driver5 s11)
    (walk driver5 s12)
    (walk driver5 s13)
    (walk driver5 s14)
    (walk driver5 s2)
    (walk driver5 s3)
    (walk driver5 s4)
    (walk driver5 s5)
    (walk driver5 s6)
    (walk driver5 s7)
    (walk driver5 s8)
    (walk driver5 s9)
    )
	(:goal (and
	(at driver1 s12)
	(at driver2 s11)
	(at driver3 s11)
	(at driver4 s12)
	(at driver5 s11)
	(at truck1 s5)
	(at truck2 s6)
	(at truck3 s8)
	(at truck4 s12)
	(at truck5 s14)
	(at package1 s13)
	(at package2 s0)
	(at package4 s11)
	(at package5 s9)
	(at package6 s2)
	(at package7 s3)
	(at package8 s6)
	(at package9 s4)
	(at package10 s8)
	))


)
