; Problem taken from https://github.com/AI-Planning/classical-domains

(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0
	instrument0
	instrument1
	instrument2
	satellite1
	instrument3
	satellite2
	instrument4
	instrument5
	instrument6
	satellite3
	instrument7
	instrument8
	satellite4
	instrument9
	instrument10
	satellite5
	instrument11
	thermograph4
	image1
	thermograph3
	image2
	thermograph0
	GroundStation3
	GroundStation4
	GroundStation2
	GroundStation0
	GroundStation1
	Phenomenon5
	Phenomenon6
	Phenomenon7
	Planet8
	Star9
	Star10
	Phenomenon11
	Phenomenon12
	Phenomenon13
	Star14
	Planet15
	Planet16
	Planet17
	Phenomenon18
	Star19
	Star20
	Planet21
	Star22
	Planet23
	Star24
)
(:init
	(satellite satellite0)
	(instrument instrument0)
	(supports instrument0 thermograph0)
	(supports instrument0 image1)
	(calibration_target instrument0 GroundStation2)
	(instrument instrument1)
	(supports instrument1 image2)
	(supports instrument1 thermograph3)
	(calibration_target instrument1 GroundStation0)
	(instrument instrument2)
	(supports instrument2 image1)
	(supports instrument2 thermograph3)
	(supports instrument2 thermograph4)
	(calibration_target instrument2 GroundStation2)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Phenomenon12)
	(satellite satellite1)
	(instrument instrument3)
	(supports instrument3 thermograph0)
	(supports instrument3 thermograph4)
	(supports instrument3 image2)
	(calibration_target instrument3 GroundStation2)
	(on_board instrument3 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation1)
	(satellite satellite2)
	(instrument instrument4)
	(supports instrument4 thermograph4)
	(supports instrument4 image1)
	(supports instrument4 thermograph0)
	(calibration_target instrument4 GroundStation1)
	(instrument instrument5)
	(supports instrument5 thermograph4)
	(calibration_target instrument5 GroundStation4)
	(instrument instrument6)
	(supports instrument6 thermograph3)
	(supports instrument6 image1)
	(calibration_target instrument6 GroundStation0)
	(on_board instrument4 satellite2)
	(on_board instrument5 satellite2)
	(on_board instrument6 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation2)
	(satellite satellite3)
	(instrument instrument7)
	(supports instrument7 image2)
	(supports instrument7 thermograph3)
	(calibration_target instrument7 GroundStation4)
	(instrument instrument8)
	(supports instrument8 thermograph4)
	(supports instrument8 thermograph0)
	(calibration_target instrument8 GroundStation2)
	(on_board instrument7 satellite3)
	(on_board instrument8 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation4)
	(satellite satellite4)
	(instrument instrument9)
	(supports instrument9 thermograph0)
	(supports instrument9 image2)
	(supports instrument9 image1)
	(calibration_target instrument9 GroundStation2)
	(instrument instrument10)
	(supports instrument10 thermograph3)
	(supports instrument10 image1)
	(calibration_target instrument10 GroundStation0)
	(on_board instrument9 satellite4)
	(on_board instrument10 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Planet15)
	(satellite satellite5)
	(instrument instrument11)
	(supports instrument11 thermograph0)
	(supports instrument11 image2)
	(calibration_target instrument11 GroundStation1)
	(on_board instrument11 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Phenomenon11)
	(mode thermograph4)
	(mode image1)
	(mode thermograph3)
	(mode image2)
	(mode thermograph0)
	(direction GroundStation3)
	(direction GroundStation4)
	(direction GroundStation2)
	(direction GroundStation0)
	(direction GroundStation1)
	(direction Phenomenon5)
	(direction Phenomenon6)
	(direction Phenomenon7)
	(direction Planet8)
	(direction Star9)
	(direction Star10)
	(direction Phenomenon11)
	(direction Phenomenon12)
	(direction Phenomenon13)
	(direction Star14)
	(direction Planet15)
	(direction Planet16)
	(direction Planet17)
	(direction Phenomenon18)
	(direction Star19)
	(direction Star20)
	(direction Planet21)
	(direction Star22)
	(direction Planet23)
	(direction Star24)

    ; action literals
    (turn_to satellite0 GroundStation0)
    (turn_to satellite0 GroundStation1)
    (turn_to satellite0 GroundStation2)
    (turn_to satellite0 GroundStation3)
    (turn_to satellite0 GroundStation4)
    (turn_to satellite0 Phenomenon11)
    (turn_to satellite0 Phenomenon12)
    (turn_to satellite0 Phenomenon13)
    (turn_to satellite0 Phenomenon18)
    (turn_to satellite0 Phenomenon5)
    (turn_to satellite0 Phenomenon6)
    (turn_to satellite0 Phenomenon7)
    (turn_to satellite0 Planet15)
    (turn_to satellite0 Planet16)
    (turn_to satellite0 Planet17)
    (turn_to satellite0 Planet21)
    (turn_to satellite0 Planet23)
    (turn_to satellite0 Planet8)
    (turn_to satellite0 Star10)
    (turn_to satellite0 Star14)
    (turn_to satellite0 Star19)
    (turn_to satellite0 Star20)
    (turn_to satellite0 Star22)
    (turn_to satellite0 Star24)
    (turn_to satellite0 Star9)
    (turn_to satellite1 GroundStation0)
    (turn_to satellite1 GroundStation1)
    (turn_to satellite1 GroundStation2)
    (turn_to satellite1 GroundStation3)
    (turn_to satellite1 GroundStation4)
    (turn_to satellite1 Phenomenon11)
    (turn_to satellite1 Phenomenon12)
    (turn_to satellite1 Phenomenon13)
    (turn_to satellite1 Phenomenon18)
    (turn_to satellite1 Phenomenon5)
    (turn_to satellite1 Phenomenon6)
    (turn_to satellite1 Phenomenon7)
    (turn_to satellite1 Planet15)
    (turn_to satellite1 Planet16)
    (turn_to satellite1 Planet17)
    (turn_to satellite1 Planet21)
    (turn_to satellite1 Planet23)
    (turn_to satellite1 Planet8)
    (turn_to satellite1 Star10)
    (turn_to satellite1 Star14)
    (turn_to satellite1 Star19)
    (turn_to satellite1 Star20)
    (turn_to satellite1 Star22)
    (turn_to satellite1 Star24)
    (turn_to satellite1 Star9)
    (turn_to satellite2 GroundStation0)
    (turn_to satellite2 GroundStation1)
    (turn_to satellite2 GroundStation2)
    (turn_to satellite2 GroundStation3)
    (turn_to satellite2 GroundStation4)
    (turn_to satellite2 Phenomenon11)
    (turn_to satellite2 Phenomenon12)
    (turn_to satellite2 Phenomenon13)
    (turn_to satellite2 Phenomenon18)
    (turn_to satellite2 Phenomenon5)
    (turn_to satellite2 Phenomenon6)
    (turn_to satellite2 Phenomenon7)
    (turn_to satellite2 Planet15)
    (turn_to satellite2 Planet16)
    (turn_to satellite2 Planet17)
    (turn_to satellite2 Planet21)
    (turn_to satellite2 Planet23)
    (turn_to satellite2 Planet8)
    (turn_to satellite2 Star10)
    (turn_to satellite2 Star14)
    (turn_to satellite2 Star19)
    (turn_to satellite2 Star20)
    (turn_to satellite2 Star22)
    (turn_to satellite2 Star24)
    (turn_to satellite2 Star9)
    (turn_to satellite3 GroundStation0)
    (turn_to satellite3 GroundStation1)
    (turn_to satellite3 GroundStation2)
    (turn_to satellite3 GroundStation3)
    (turn_to satellite3 GroundStation4)
    (turn_to satellite3 Phenomenon11)
    (turn_to satellite3 Phenomenon12)
    (turn_to satellite3 Phenomenon13)
    (turn_to satellite3 Phenomenon18)
    (turn_to satellite3 Phenomenon5)
    (turn_to satellite3 Phenomenon6)
    (turn_to satellite3 Phenomenon7)
    (turn_to satellite3 Planet15)
    (turn_to satellite3 Planet16)
    (turn_to satellite3 Planet17)
    (turn_to satellite3 Planet21)
    (turn_to satellite3 Planet23)
    (turn_to satellite3 Planet8)
    (turn_to satellite3 Star10)
    (turn_to satellite3 Star14)
    (turn_to satellite3 Star19)
    (turn_to satellite3 Star20)
    (turn_to satellite3 Star22)
    (turn_to satellite3 Star24)
    (turn_to satellite3 Star9)
    (turn_to satellite4 GroundStation0)
    (turn_to satellite4 GroundStation1)
    (turn_to satellite4 GroundStation2)
    (turn_to satellite4 GroundStation3)
    (turn_to satellite4 GroundStation4)
    (turn_to satellite4 Phenomenon11)
    (turn_to satellite4 Phenomenon12)
    (turn_to satellite4 Phenomenon13)
    (turn_to satellite4 Phenomenon18)
    (turn_to satellite4 Phenomenon5)
    (turn_to satellite4 Phenomenon6)
    (turn_to satellite4 Phenomenon7)
    (turn_to satellite4 Planet15)
    (turn_to satellite4 Planet16)
    (turn_to satellite4 Planet17)
    (turn_to satellite4 Planet21)
    (turn_to satellite4 Planet23)
    (turn_to satellite4 Planet8)
    (turn_to satellite4 Star10)
    (turn_to satellite4 Star14)
    (turn_to satellite4 Star19)
    (turn_to satellite4 Star20)
    (turn_to satellite4 Star22)
    (turn_to satellite4 Star24)
    (turn_to satellite4 Star9)
    (turn_to satellite5 GroundStation0)
    (turn_to satellite5 GroundStation1)
    (turn_to satellite5 GroundStation2)
    (turn_to satellite5 GroundStation3)
    (turn_to satellite5 GroundStation4)
    (turn_to satellite5 Phenomenon11)
    (turn_to satellite5 Phenomenon12)
    (turn_to satellite5 Phenomenon13)
    (turn_to satellite5 Phenomenon18)
    (turn_to satellite5 Phenomenon5)
    (turn_to satellite5 Phenomenon6)
    (turn_to satellite5 Phenomenon7)
    (turn_to satellite5 Planet15)
    (turn_to satellite5 Planet16)
    (turn_to satellite5 Planet17)
    (turn_to satellite5 Planet21)
    (turn_to satellite5 Planet23)
    (turn_to satellite5 Planet8)
    (turn_to satellite5 Star10)
    (turn_to satellite5 Star14)
    (turn_to satellite5 Star19)
    (turn_to satellite5 Star20)
    (turn_to satellite5 Star22)
    (turn_to satellite5 Star24)
    (turn_to satellite5 Star9)
    (switch_on instrument0)
    (switch_off instrument0)
    (switch_on instrument1)
    (switch_off instrument1)
    (switch_on instrument10)
    (switch_off instrument10)
    (switch_on instrument11)
    (switch_off instrument11)
    (switch_on instrument2)
    (switch_off instrument2)
    (switch_on instrument3)
    (switch_off instrument3)
    (switch_on instrument4)
    (switch_off instrument4)
    (switch_on instrument5)
    (switch_off instrument5)
    (switch_on instrument6)
    (switch_off instrument6)
    (switch_on instrument7)
    (switch_off instrument7)
    (switch_on instrument8)
    (switch_off instrument8)
    (switch_on instrument9)
    (switch_off instrument9)
    (calibrate instrument0 GroundStation0)
    (calibrate instrument0 GroundStation1)
    (calibrate instrument0 GroundStation2)
    (calibrate instrument0 GroundStation3)
    (calibrate instrument0 GroundStation4)
    (calibrate instrument0 Phenomenon11)
    (calibrate instrument0 Phenomenon12)
    (calibrate instrument0 Phenomenon13)
    (calibrate instrument0 Phenomenon18)
    (calibrate instrument0 Phenomenon5)
    (calibrate instrument0 Phenomenon6)
    (calibrate instrument0 Phenomenon7)
    (calibrate instrument0 Planet15)
    (calibrate instrument0 Planet16)
    (calibrate instrument0 Planet17)
    (calibrate instrument0 Planet21)
    (calibrate instrument0 Planet23)
    (calibrate instrument0 Planet8)
    (calibrate instrument0 Star10)
    (calibrate instrument0 Star14)
    (calibrate instrument0 Star19)
    (calibrate instrument0 Star20)
    (calibrate instrument0 Star22)
    (calibrate instrument0 Star24)
    (calibrate instrument0 Star9)
    (calibrate instrument1 GroundStation0)
    (calibrate instrument1 GroundStation1)
    (calibrate instrument1 GroundStation2)
    (calibrate instrument1 GroundStation3)
    (calibrate instrument1 GroundStation4)
    (calibrate instrument1 Phenomenon11)
    (calibrate instrument1 Phenomenon12)
    (calibrate instrument1 Phenomenon13)
    (calibrate instrument1 Phenomenon18)
    (calibrate instrument1 Phenomenon5)
    (calibrate instrument1 Phenomenon6)
    (calibrate instrument1 Phenomenon7)
    (calibrate instrument1 Planet15)
    (calibrate instrument1 Planet16)
    (calibrate instrument1 Planet17)
    (calibrate instrument1 Planet21)
    (calibrate instrument1 Planet23)
    (calibrate instrument1 Planet8)
    (calibrate instrument1 Star10)
    (calibrate instrument1 Star14)
    (calibrate instrument1 Star19)
    (calibrate instrument1 Star20)
    (calibrate instrument1 Star22)
    (calibrate instrument1 Star24)
    (calibrate instrument1 Star9)
    (calibrate instrument10 GroundStation0)
    (calibrate instrument10 GroundStation1)
    (calibrate instrument10 GroundStation2)
    (calibrate instrument10 GroundStation3)
    (calibrate instrument10 GroundStation4)
    (calibrate instrument10 Phenomenon11)
    (calibrate instrument10 Phenomenon12)
    (calibrate instrument10 Phenomenon13)
    (calibrate instrument10 Phenomenon18)
    (calibrate instrument10 Phenomenon5)
    (calibrate instrument10 Phenomenon6)
    (calibrate instrument10 Phenomenon7)
    (calibrate instrument10 Planet15)
    (calibrate instrument10 Planet16)
    (calibrate instrument10 Planet17)
    (calibrate instrument10 Planet21)
    (calibrate instrument10 Planet23)
    (calibrate instrument10 Planet8)
    (calibrate instrument10 Star10)
    (calibrate instrument10 Star14)
    (calibrate instrument10 Star19)
    (calibrate instrument10 Star20)
    (calibrate instrument10 Star22)
    (calibrate instrument10 Star24)
    (calibrate instrument10 Star9)
    (calibrate instrument11 GroundStation0)
    (calibrate instrument11 GroundStation1)
    (calibrate instrument11 GroundStation2)
    (calibrate instrument11 GroundStation3)
    (calibrate instrument11 GroundStation4)
    (calibrate instrument11 Phenomenon11)
    (calibrate instrument11 Phenomenon12)
    (calibrate instrument11 Phenomenon13)
    (calibrate instrument11 Phenomenon18)
    (calibrate instrument11 Phenomenon5)
    (calibrate instrument11 Phenomenon6)
    (calibrate instrument11 Phenomenon7)
    (calibrate instrument11 Planet15)
    (calibrate instrument11 Planet16)
    (calibrate instrument11 Planet17)
    (calibrate instrument11 Planet21)
    (calibrate instrument11 Planet23)
    (calibrate instrument11 Planet8)
    (calibrate instrument11 Star10)
    (calibrate instrument11 Star14)
    (calibrate instrument11 Star19)
    (calibrate instrument11 Star20)
    (calibrate instrument11 Star22)
    (calibrate instrument11 Star24)
    (calibrate instrument11 Star9)
    (calibrate instrument2 GroundStation0)
    (calibrate instrument2 GroundStation1)
    (calibrate instrument2 GroundStation2)
    (calibrate instrument2 GroundStation3)
    (calibrate instrument2 GroundStation4)
    (calibrate instrument2 Phenomenon11)
    (calibrate instrument2 Phenomenon12)
    (calibrate instrument2 Phenomenon13)
    (calibrate instrument2 Phenomenon18)
    (calibrate instrument2 Phenomenon5)
    (calibrate instrument2 Phenomenon6)
    (calibrate instrument2 Phenomenon7)
    (calibrate instrument2 Planet15)
    (calibrate instrument2 Planet16)
    (calibrate instrument2 Planet17)
    (calibrate instrument2 Planet21)
    (calibrate instrument2 Planet23)
    (calibrate instrument2 Planet8)
    (calibrate instrument2 Star10)
    (calibrate instrument2 Star14)
    (calibrate instrument2 Star19)
    (calibrate instrument2 Star20)
    (calibrate instrument2 Star22)
    (calibrate instrument2 Star24)
    (calibrate instrument2 Star9)
    (calibrate instrument3 GroundStation0)
    (calibrate instrument3 GroundStation1)
    (calibrate instrument3 GroundStation2)
    (calibrate instrument3 GroundStation3)
    (calibrate instrument3 GroundStation4)
    (calibrate instrument3 Phenomenon11)
    (calibrate instrument3 Phenomenon12)
    (calibrate instrument3 Phenomenon13)
    (calibrate instrument3 Phenomenon18)
    (calibrate instrument3 Phenomenon5)
    (calibrate instrument3 Phenomenon6)
    (calibrate instrument3 Phenomenon7)
    (calibrate instrument3 Planet15)
    (calibrate instrument3 Planet16)
    (calibrate instrument3 Planet17)
    (calibrate instrument3 Planet21)
    (calibrate instrument3 Planet23)
    (calibrate instrument3 Planet8)
    (calibrate instrument3 Star10)
    (calibrate instrument3 Star14)
    (calibrate instrument3 Star19)
    (calibrate instrument3 Star20)
    (calibrate instrument3 Star22)
    (calibrate instrument3 Star24)
    (calibrate instrument3 Star9)
    (calibrate instrument4 GroundStation0)
    (calibrate instrument4 GroundStation1)
    (calibrate instrument4 GroundStation2)
    (calibrate instrument4 GroundStation3)
    (calibrate instrument4 GroundStation4)
    (calibrate instrument4 Phenomenon11)
    (calibrate instrument4 Phenomenon12)
    (calibrate instrument4 Phenomenon13)
    (calibrate instrument4 Phenomenon18)
    (calibrate instrument4 Phenomenon5)
    (calibrate instrument4 Phenomenon6)
    (calibrate instrument4 Phenomenon7)
    (calibrate instrument4 Planet15)
    (calibrate instrument4 Planet16)
    (calibrate instrument4 Planet17)
    (calibrate instrument4 Planet21)
    (calibrate instrument4 Planet23)
    (calibrate instrument4 Planet8)
    (calibrate instrument4 Star10)
    (calibrate instrument4 Star14)
    (calibrate instrument4 Star19)
    (calibrate instrument4 Star20)
    (calibrate instrument4 Star22)
    (calibrate instrument4 Star24)
    (calibrate instrument4 Star9)
    (calibrate instrument5 GroundStation0)
    (calibrate instrument5 GroundStation1)
    (calibrate instrument5 GroundStation2)
    (calibrate instrument5 GroundStation3)
    (calibrate instrument5 GroundStation4)
    (calibrate instrument5 Phenomenon11)
    (calibrate instrument5 Phenomenon12)
    (calibrate instrument5 Phenomenon13)
    (calibrate instrument5 Phenomenon18)
    (calibrate instrument5 Phenomenon5)
    (calibrate instrument5 Phenomenon6)
    (calibrate instrument5 Phenomenon7)
    (calibrate instrument5 Planet15)
    (calibrate instrument5 Planet16)
    (calibrate instrument5 Planet17)
    (calibrate instrument5 Planet21)
    (calibrate instrument5 Planet23)
    (calibrate instrument5 Planet8)
    (calibrate instrument5 Star10)
    (calibrate instrument5 Star14)
    (calibrate instrument5 Star19)
    (calibrate instrument5 Star20)
    (calibrate instrument5 Star22)
    (calibrate instrument5 Star24)
    (calibrate instrument5 Star9)
    (calibrate instrument6 GroundStation0)
    (calibrate instrument6 GroundStation1)
    (calibrate instrument6 GroundStation2)
    (calibrate instrument6 GroundStation3)
    (calibrate instrument6 GroundStation4)
    (calibrate instrument6 Phenomenon11)
    (calibrate instrument6 Phenomenon12)
    (calibrate instrument6 Phenomenon13)
    (calibrate instrument6 Phenomenon18)
    (calibrate instrument6 Phenomenon5)
    (calibrate instrument6 Phenomenon6)
    (calibrate instrument6 Phenomenon7)
    (calibrate instrument6 Planet15)
    (calibrate instrument6 Planet16)
    (calibrate instrument6 Planet17)
    (calibrate instrument6 Planet21)
    (calibrate instrument6 Planet23)
    (calibrate instrument6 Planet8)
    (calibrate instrument6 Star10)
    (calibrate instrument6 Star14)
    (calibrate instrument6 Star19)
    (calibrate instrument6 Star20)
    (calibrate instrument6 Star22)
    (calibrate instrument6 Star24)
    (calibrate instrument6 Star9)
    (calibrate instrument7 GroundStation0)
    (calibrate instrument7 GroundStation1)
    (calibrate instrument7 GroundStation2)
    (calibrate instrument7 GroundStation3)
    (calibrate instrument7 GroundStation4)
    (calibrate instrument7 Phenomenon11)
    (calibrate instrument7 Phenomenon12)
    (calibrate instrument7 Phenomenon13)
    (calibrate instrument7 Phenomenon18)
    (calibrate instrument7 Phenomenon5)
    (calibrate instrument7 Phenomenon6)
    (calibrate instrument7 Phenomenon7)
    (calibrate instrument7 Planet15)
    (calibrate instrument7 Planet16)
    (calibrate instrument7 Planet17)
    (calibrate instrument7 Planet21)
    (calibrate instrument7 Planet23)
    (calibrate instrument7 Planet8)
    (calibrate instrument7 Star10)
    (calibrate instrument7 Star14)
    (calibrate instrument7 Star19)
    (calibrate instrument7 Star20)
    (calibrate instrument7 Star22)
    (calibrate instrument7 Star24)
    (calibrate instrument7 Star9)
    (calibrate instrument8 GroundStation0)
    (calibrate instrument8 GroundStation1)
    (calibrate instrument8 GroundStation2)
    (calibrate instrument8 GroundStation3)
    (calibrate instrument8 GroundStation4)
    (calibrate instrument8 Phenomenon11)
    (calibrate instrument8 Phenomenon12)
    (calibrate instrument8 Phenomenon13)
    (calibrate instrument8 Phenomenon18)
    (calibrate instrument8 Phenomenon5)
    (calibrate instrument8 Phenomenon6)
    (calibrate instrument8 Phenomenon7)
    (calibrate instrument8 Planet15)
    (calibrate instrument8 Planet16)
    (calibrate instrument8 Planet17)
    (calibrate instrument8 Planet21)
    (calibrate instrument8 Planet23)
    (calibrate instrument8 Planet8)
    (calibrate instrument8 Star10)
    (calibrate instrument8 Star14)
    (calibrate instrument8 Star19)
    (calibrate instrument8 Star20)
    (calibrate instrument8 Star22)
    (calibrate instrument8 Star24)
    (calibrate instrument8 Star9)
    (calibrate instrument9 GroundStation0)
    (calibrate instrument9 GroundStation1)
    (calibrate instrument9 GroundStation2)
    (calibrate instrument9 GroundStation3)
    (calibrate instrument9 GroundStation4)
    (calibrate instrument9 Phenomenon11)
    (calibrate instrument9 Phenomenon12)
    (calibrate instrument9 Phenomenon13)
    (calibrate instrument9 Phenomenon18)
    (calibrate instrument9 Phenomenon5)
    (calibrate instrument9 Phenomenon6)
    (calibrate instrument9 Phenomenon7)
    (calibrate instrument9 Planet15)
    (calibrate instrument9 Planet16)
    (calibrate instrument9 Planet17)
    (calibrate instrument9 Planet21)
    (calibrate instrument9 Planet23)
    (calibrate instrument9 Planet8)
    (calibrate instrument9 Star10)
    (calibrate instrument9 Star14)
    (calibrate instrument9 Star19)
    (calibrate instrument9 Star20)
    (calibrate instrument9 Star22)
    (calibrate instrument9 Star24)
    (calibrate instrument9 Star9)
    (take_image instrument0 GroundStation0 image1)
    (take_image instrument0 GroundStation0 image2)
    (take_image instrument0 GroundStation0 thermograph0)
    (take_image instrument0 GroundStation0 thermograph3)
    (take_image instrument0 GroundStation0 thermograph4)
    (take_image instrument0 GroundStation1 image1)
    (take_image instrument0 GroundStation1 image2)
    (take_image instrument0 GroundStation1 thermograph0)
    (take_image instrument0 GroundStation1 thermograph3)
    (take_image instrument0 GroundStation1 thermograph4)
    (take_image instrument0 GroundStation2 image1)
    (take_image instrument0 GroundStation2 image2)
    (take_image instrument0 GroundStation2 thermograph0)
    (take_image instrument0 GroundStation2 thermograph3)
    (take_image instrument0 GroundStation2 thermograph4)
    (take_image instrument0 GroundStation3 image1)
    (take_image instrument0 GroundStation3 image2)
    (take_image instrument0 GroundStation3 thermograph0)
    (take_image instrument0 GroundStation3 thermograph3)
    (take_image instrument0 GroundStation3 thermograph4)
    (take_image instrument0 GroundStation4 image1)
    (take_image instrument0 GroundStation4 image2)
    (take_image instrument0 GroundStation4 thermograph0)
    (take_image instrument0 GroundStation4 thermograph3)
    (take_image instrument0 GroundStation4 thermograph4)
    (take_image instrument0 Phenomenon11 image1)
    (take_image instrument0 Phenomenon11 image2)
    (take_image instrument0 Phenomenon11 thermograph0)
    (take_image instrument0 Phenomenon11 thermograph3)
    (take_image instrument0 Phenomenon11 thermograph4)
    (take_image instrument0 Phenomenon12 image1)
    (take_image instrument0 Phenomenon12 image2)
    (take_image instrument0 Phenomenon12 thermograph0)
    (take_image instrument0 Phenomenon12 thermograph3)
    (take_image instrument0 Phenomenon12 thermograph4)
    (take_image instrument0 Phenomenon13 image1)
    (take_image instrument0 Phenomenon13 image2)
    (take_image instrument0 Phenomenon13 thermograph0)
    (take_image instrument0 Phenomenon13 thermograph3)
    (take_image instrument0 Phenomenon13 thermograph4)
    (take_image instrument0 Phenomenon18 image1)
    (take_image instrument0 Phenomenon18 image2)
    (take_image instrument0 Phenomenon18 thermograph0)
    (take_image instrument0 Phenomenon18 thermograph3)
    (take_image instrument0 Phenomenon18 thermograph4)
    (take_image instrument0 Phenomenon5 image1)
    (take_image instrument0 Phenomenon5 image2)
    (take_image instrument0 Phenomenon5 thermograph0)
    (take_image instrument0 Phenomenon5 thermograph3)
    (take_image instrument0 Phenomenon5 thermograph4)
    (take_image instrument0 Phenomenon6 image1)
    (take_image instrument0 Phenomenon6 image2)
    (take_image instrument0 Phenomenon6 thermograph0)
    (take_image instrument0 Phenomenon6 thermograph3)
    (take_image instrument0 Phenomenon6 thermograph4)
    (take_image instrument0 Phenomenon7 image1)
    (take_image instrument0 Phenomenon7 image2)
    (take_image instrument0 Phenomenon7 thermograph0)
    (take_image instrument0 Phenomenon7 thermograph3)
    (take_image instrument0 Phenomenon7 thermograph4)
    (take_image instrument0 Planet15 image1)
    (take_image instrument0 Planet15 image2)
    (take_image instrument0 Planet15 thermograph0)
    (take_image instrument0 Planet15 thermograph3)
    (take_image instrument0 Planet15 thermograph4)
    (take_image instrument0 Planet16 image1)
    (take_image instrument0 Planet16 image2)
    (take_image instrument0 Planet16 thermograph0)
    (take_image instrument0 Planet16 thermograph3)
    (take_image instrument0 Planet16 thermograph4)
    (take_image instrument0 Planet17 image1)
    (take_image instrument0 Planet17 image2)
    (take_image instrument0 Planet17 thermograph0)
    (take_image instrument0 Planet17 thermograph3)
    (take_image instrument0 Planet17 thermograph4)
    (take_image instrument0 Planet21 image1)
    (take_image instrument0 Planet21 image2)
    (take_image instrument0 Planet21 thermograph0)
    (take_image instrument0 Planet21 thermograph3)
    (take_image instrument0 Planet21 thermograph4)
    (take_image instrument0 Planet23 image1)
    (take_image instrument0 Planet23 image2)
    (take_image instrument0 Planet23 thermograph0)
    (take_image instrument0 Planet23 thermograph3)
    (take_image instrument0 Planet23 thermograph4)
    (take_image instrument0 Planet8 image1)
    (take_image instrument0 Planet8 image2)
    (take_image instrument0 Planet8 thermograph0)
    (take_image instrument0 Planet8 thermograph3)
    (take_image instrument0 Planet8 thermograph4)
    (take_image instrument0 Star10 image1)
    (take_image instrument0 Star10 image2)
    (take_image instrument0 Star10 thermograph0)
    (take_image instrument0 Star10 thermograph3)
    (take_image instrument0 Star10 thermograph4)
    (take_image instrument0 Star14 image1)
    (take_image instrument0 Star14 image2)
    (take_image instrument0 Star14 thermograph0)
    (take_image instrument0 Star14 thermograph3)
    (take_image instrument0 Star14 thermograph4)
    (take_image instrument0 Star19 image1)
    (take_image instrument0 Star19 image2)
    (take_image instrument0 Star19 thermograph0)
    (take_image instrument0 Star19 thermograph3)
    (take_image instrument0 Star19 thermograph4)
    (take_image instrument0 Star20 image1)
    (take_image instrument0 Star20 image2)
    (take_image instrument0 Star20 thermograph0)
    (take_image instrument0 Star20 thermograph3)
    (take_image instrument0 Star20 thermograph4)
    (take_image instrument0 Star22 image1)
    (take_image instrument0 Star22 image2)
    (take_image instrument0 Star22 thermograph0)
    (take_image instrument0 Star22 thermograph3)
    (take_image instrument0 Star22 thermograph4)
    (take_image instrument0 Star24 image1)
    (take_image instrument0 Star24 image2)
    (take_image instrument0 Star24 thermograph0)
    (take_image instrument0 Star24 thermograph3)
    (take_image instrument0 Star24 thermograph4)
    (take_image instrument0 Star9 image1)
    (take_image instrument0 Star9 image2)
    (take_image instrument0 Star9 thermograph0)
    (take_image instrument0 Star9 thermograph3)
    (take_image instrument0 Star9 thermograph4)
    (take_image instrument1 GroundStation0 image1)
    (take_image instrument1 GroundStation0 image2)
    (take_image instrument1 GroundStation0 thermograph0)
    (take_image instrument1 GroundStation0 thermograph3)
    (take_image instrument1 GroundStation0 thermograph4)
    (take_image instrument1 GroundStation1 image1)
    (take_image instrument1 GroundStation1 image2)
    (take_image instrument1 GroundStation1 thermograph0)
    (take_image instrument1 GroundStation1 thermograph3)
    (take_image instrument1 GroundStation1 thermograph4)
    (take_image instrument1 GroundStation2 image1)
    (take_image instrument1 GroundStation2 image2)
    (take_image instrument1 GroundStation2 thermograph0)
    (take_image instrument1 GroundStation2 thermograph3)
    (take_image instrument1 GroundStation2 thermograph4)
    (take_image instrument1 GroundStation3 image1)
    (take_image instrument1 GroundStation3 image2)
    (take_image instrument1 GroundStation3 thermograph0)
    (take_image instrument1 GroundStation3 thermograph3)
    (take_image instrument1 GroundStation3 thermograph4)
    (take_image instrument1 GroundStation4 image1)
    (take_image instrument1 GroundStation4 image2)
    (take_image instrument1 GroundStation4 thermograph0)
    (take_image instrument1 GroundStation4 thermograph3)
    (take_image instrument1 GroundStation4 thermograph4)
    (take_image instrument1 Phenomenon11 image1)
    (take_image instrument1 Phenomenon11 image2)
    (take_image instrument1 Phenomenon11 thermograph0)
    (take_image instrument1 Phenomenon11 thermograph3)
    (take_image instrument1 Phenomenon11 thermograph4)
    (take_image instrument1 Phenomenon12 image1)
    (take_image instrument1 Phenomenon12 image2)
    (take_image instrument1 Phenomenon12 thermograph0)
    (take_image instrument1 Phenomenon12 thermograph3)
    (take_image instrument1 Phenomenon12 thermograph4)
    (take_image instrument1 Phenomenon13 image1)
    (take_image instrument1 Phenomenon13 image2)
    (take_image instrument1 Phenomenon13 thermograph0)
    (take_image instrument1 Phenomenon13 thermograph3)
    (take_image instrument1 Phenomenon13 thermograph4)
    (take_image instrument1 Phenomenon18 image1)
    (take_image instrument1 Phenomenon18 image2)
    (take_image instrument1 Phenomenon18 thermograph0)
    (take_image instrument1 Phenomenon18 thermograph3)
    (take_image instrument1 Phenomenon18 thermograph4)
    (take_image instrument1 Phenomenon5 image1)
    (take_image instrument1 Phenomenon5 image2)
    (take_image instrument1 Phenomenon5 thermograph0)
    (take_image instrument1 Phenomenon5 thermograph3)
    (take_image instrument1 Phenomenon5 thermograph4)
    (take_image instrument1 Phenomenon6 image1)
    (take_image instrument1 Phenomenon6 image2)
    (take_image instrument1 Phenomenon6 thermograph0)
    (take_image instrument1 Phenomenon6 thermograph3)
    (take_image instrument1 Phenomenon6 thermograph4)
    (take_image instrument1 Phenomenon7 image1)
    (take_image instrument1 Phenomenon7 image2)
    (take_image instrument1 Phenomenon7 thermograph0)
    (take_image instrument1 Phenomenon7 thermograph3)
    (take_image instrument1 Phenomenon7 thermograph4)
    (take_image instrument1 Planet15 image1)
    (take_image instrument1 Planet15 image2)
    (take_image instrument1 Planet15 thermograph0)
    (take_image instrument1 Planet15 thermograph3)
    (take_image instrument1 Planet15 thermograph4)
    (take_image instrument1 Planet16 image1)
    (take_image instrument1 Planet16 image2)
    (take_image instrument1 Planet16 thermograph0)
    (take_image instrument1 Planet16 thermograph3)
    (take_image instrument1 Planet16 thermograph4)
    (take_image instrument1 Planet17 image1)
    (take_image instrument1 Planet17 image2)
    (take_image instrument1 Planet17 thermograph0)
    (take_image instrument1 Planet17 thermograph3)
    (take_image instrument1 Planet17 thermograph4)
    (take_image instrument1 Planet21 image1)
    (take_image instrument1 Planet21 image2)
    (take_image instrument1 Planet21 thermograph0)
    (take_image instrument1 Planet21 thermograph3)
    (take_image instrument1 Planet21 thermograph4)
    (take_image instrument1 Planet23 image1)
    (take_image instrument1 Planet23 image2)
    (take_image instrument1 Planet23 thermograph0)
    (take_image instrument1 Planet23 thermograph3)
    (take_image instrument1 Planet23 thermograph4)
    (take_image instrument1 Planet8 image1)
    (take_image instrument1 Planet8 image2)
    (take_image instrument1 Planet8 thermograph0)
    (take_image instrument1 Planet8 thermograph3)
    (take_image instrument1 Planet8 thermograph4)
    (take_image instrument1 Star10 image1)
    (take_image instrument1 Star10 image2)
    (take_image instrument1 Star10 thermograph0)
    (take_image instrument1 Star10 thermograph3)
    (take_image instrument1 Star10 thermograph4)
    (take_image instrument1 Star14 image1)
    (take_image instrument1 Star14 image2)
    (take_image instrument1 Star14 thermograph0)
    (take_image instrument1 Star14 thermograph3)
    (take_image instrument1 Star14 thermograph4)
    (take_image instrument1 Star19 image1)
    (take_image instrument1 Star19 image2)
    (take_image instrument1 Star19 thermograph0)
    (take_image instrument1 Star19 thermograph3)
    (take_image instrument1 Star19 thermograph4)
    (take_image instrument1 Star20 image1)
    (take_image instrument1 Star20 image2)
    (take_image instrument1 Star20 thermograph0)
    (take_image instrument1 Star20 thermograph3)
    (take_image instrument1 Star20 thermograph4)
    (take_image instrument1 Star22 image1)
    (take_image instrument1 Star22 image2)
    (take_image instrument1 Star22 thermograph0)
    (take_image instrument1 Star22 thermograph3)
    (take_image instrument1 Star22 thermograph4)
    (take_image instrument1 Star24 image1)
    (take_image instrument1 Star24 image2)
    (take_image instrument1 Star24 thermograph0)
    (take_image instrument1 Star24 thermograph3)
    (take_image instrument1 Star24 thermograph4)
    (take_image instrument1 Star9 image1)
    (take_image instrument1 Star9 image2)
    (take_image instrument1 Star9 thermograph0)
    (take_image instrument1 Star9 thermograph3)
    (take_image instrument1 Star9 thermograph4)
    (take_image instrument10 GroundStation0 image1)
    (take_image instrument10 GroundStation0 image2)
    (take_image instrument10 GroundStation0 thermograph0)
    (take_image instrument10 GroundStation0 thermograph3)
    (take_image instrument10 GroundStation0 thermograph4)
    (take_image instrument10 GroundStation1 image1)
    (take_image instrument10 GroundStation1 image2)
    (take_image instrument10 GroundStation1 thermograph0)
    (take_image instrument10 GroundStation1 thermograph3)
    (take_image instrument10 GroundStation1 thermograph4)
    (take_image instrument10 GroundStation2 image1)
    (take_image instrument10 GroundStation2 image2)
    (take_image instrument10 GroundStation2 thermograph0)
    (take_image instrument10 GroundStation2 thermograph3)
    (take_image instrument10 GroundStation2 thermograph4)
    (take_image instrument10 GroundStation3 image1)
    (take_image instrument10 GroundStation3 image2)
    (take_image instrument10 GroundStation3 thermograph0)
    (take_image instrument10 GroundStation3 thermograph3)
    (take_image instrument10 GroundStation3 thermograph4)
    (take_image instrument10 GroundStation4 image1)
    (take_image instrument10 GroundStation4 image2)
    (take_image instrument10 GroundStation4 thermograph0)
    (take_image instrument10 GroundStation4 thermograph3)
    (take_image instrument10 GroundStation4 thermograph4)
    (take_image instrument10 Phenomenon11 image1)
    (take_image instrument10 Phenomenon11 image2)
    (take_image instrument10 Phenomenon11 thermograph0)
    (take_image instrument10 Phenomenon11 thermograph3)
    (take_image instrument10 Phenomenon11 thermograph4)
    (take_image instrument10 Phenomenon12 image1)
    (take_image instrument10 Phenomenon12 image2)
    (take_image instrument10 Phenomenon12 thermograph0)
    (take_image instrument10 Phenomenon12 thermograph3)
    (take_image instrument10 Phenomenon12 thermograph4)
    (take_image instrument10 Phenomenon13 image1)
    (take_image instrument10 Phenomenon13 image2)
    (take_image instrument10 Phenomenon13 thermograph0)
    (take_image instrument10 Phenomenon13 thermograph3)
    (take_image instrument10 Phenomenon13 thermograph4)
    (take_image instrument10 Phenomenon18 image1)
    (take_image instrument10 Phenomenon18 image2)
    (take_image instrument10 Phenomenon18 thermograph0)
    (take_image instrument10 Phenomenon18 thermograph3)
    (take_image instrument10 Phenomenon18 thermograph4)
    (take_image instrument10 Phenomenon5 image1)
    (take_image instrument10 Phenomenon5 image2)
    (take_image instrument10 Phenomenon5 thermograph0)
    (take_image instrument10 Phenomenon5 thermograph3)
    (take_image instrument10 Phenomenon5 thermograph4)
    (take_image instrument10 Phenomenon6 image1)
    (take_image instrument10 Phenomenon6 image2)
    (take_image instrument10 Phenomenon6 thermograph0)
    (take_image instrument10 Phenomenon6 thermograph3)
    (take_image instrument10 Phenomenon6 thermograph4)
    (take_image instrument10 Phenomenon7 image1)
    (take_image instrument10 Phenomenon7 image2)
    (take_image instrument10 Phenomenon7 thermograph0)
    (take_image instrument10 Phenomenon7 thermograph3)
    (take_image instrument10 Phenomenon7 thermograph4)
    (take_image instrument10 Planet15 image1)
    (take_image instrument10 Planet15 image2)
    (take_image instrument10 Planet15 thermograph0)
    (take_image instrument10 Planet15 thermograph3)
    (take_image instrument10 Planet15 thermograph4)
    (take_image instrument10 Planet16 image1)
    (take_image instrument10 Planet16 image2)
    (take_image instrument10 Planet16 thermograph0)
    (take_image instrument10 Planet16 thermograph3)
    (take_image instrument10 Planet16 thermograph4)
    (take_image instrument10 Planet17 image1)
    (take_image instrument10 Planet17 image2)
    (take_image instrument10 Planet17 thermograph0)
    (take_image instrument10 Planet17 thermograph3)
    (take_image instrument10 Planet17 thermograph4)
    (take_image instrument10 Planet21 image1)
    (take_image instrument10 Planet21 image2)
    (take_image instrument10 Planet21 thermograph0)
    (take_image instrument10 Planet21 thermograph3)
    (take_image instrument10 Planet21 thermograph4)
    (take_image instrument10 Planet23 image1)
    (take_image instrument10 Planet23 image2)
    (take_image instrument10 Planet23 thermograph0)
    (take_image instrument10 Planet23 thermograph3)
    (take_image instrument10 Planet23 thermograph4)
    (take_image instrument10 Planet8 image1)
    (take_image instrument10 Planet8 image2)
    (take_image instrument10 Planet8 thermograph0)
    (take_image instrument10 Planet8 thermograph3)
    (take_image instrument10 Planet8 thermograph4)
    (take_image instrument10 Star10 image1)
    (take_image instrument10 Star10 image2)
    (take_image instrument10 Star10 thermograph0)
    (take_image instrument10 Star10 thermograph3)
    (take_image instrument10 Star10 thermograph4)
    (take_image instrument10 Star14 image1)
    (take_image instrument10 Star14 image2)
    (take_image instrument10 Star14 thermograph0)
    (take_image instrument10 Star14 thermograph3)
    (take_image instrument10 Star14 thermograph4)
    (take_image instrument10 Star19 image1)
    (take_image instrument10 Star19 image2)
    (take_image instrument10 Star19 thermograph0)
    (take_image instrument10 Star19 thermograph3)
    (take_image instrument10 Star19 thermograph4)
    (take_image instrument10 Star20 image1)
    (take_image instrument10 Star20 image2)
    (take_image instrument10 Star20 thermograph0)
    (take_image instrument10 Star20 thermograph3)
    (take_image instrument10 Star20 thermograph4)
    (take_image instrument10 Star22 image1)
    (take_image instrument10 Star22 image2)
    (take_image instrument10 Star22 thermograph0)
    (take_image instrument10 Star22 thermograph3)
    (take_image instrument10 Star22 thermograph4)
    (take_image instrument10 Star24 image1)
    (take_image instrument10 Star24 image2)
    (take_image instrument10 Star24 thermograph0)
    (take_image instrument10 Star24 thermograph3)
    (take_image instrument10 Star24 thermograph4)
    (take_image instrument10 Star9 image1)
    (take_image instrument10 Star9 image2)
    (take_image instrument10 Star9 thermograph0)
    (take_image instrument10 Star9 thermograph3)
    (take_image instrument10 Star9 thermograph4)
    (take_image instrument11 GroundStation0 image1)
    (take_image instrument11 GroundStation0 image2)
    (take_image instrument11 GroundStation0 thermograph0)
    (take_image instrument11 GroundStation0 thermograph3)
    (take_image instrument11 GroundStation0 thermograph4)
    (take_image instrument11 GroundStation1 image1)
    (take_image instrument11 GroundStation1 image2)
    (take_image instrument11 GroundStation1 thermograph0)
    (take_image instrument11 GroundStation1 thermograph3)
    (take_image instrument11 GroundStation1 thermograph4)
    (take_image instrument11 GroundStation2 image1)
    (take_image instrument11 GroundStation2 image2)
    (take_image instrument11 GroundStation2 thermograph0)
    (take_image instrument11 GroundStation2 thermograph3)
    (take_image instrument11 GroundStation2 thermograph4)
    (take_image instrument11 GroundStation3 image1)
    (take_image instrument11 GroundStation3 image2)
    (take_image instrument11 GroundStation3 thermograph0)
    (take_image instrument11 GroundStation3 thermograph3)
    (take_image instrument11 GroundStation3 thermograph4)
    (take_image instrument11 GroundStation4 image1)
    (take_image instrument11 GroundStation4 image2)
    (take_image instrument11 GroundStation4 thermograph0)
    (take_image instrument11 GroundStation4 thermograph3)
    (take_image instrument11 GroundStation4 thermograph4)
    (take_image instrument11 Phenomenon11 image1)
    (take_image instrument11 Phenomenon11 image2)
    (take_image instrument11 Phenomenon11 thermograph0)
    (take_image instrument11 Phenomenon11 thermograph3)
    (take_image instrument11 Phenomenon11 thermograph4)
    (take_image instrument11 Phenomenon12 image1)
    (take_image instrument11 Phenomenon12 image2)
    (take_image instrument11 Phenomenon12 thermograph0)
    (take_image instrument11 Phenomenon12 thermograph3)
    (take_image instrument11 Phenomenon12 thermograph4)
    (take_image instrument11 Phenomenon13 image1)
    (take_image instrument11 Phenomenon13 image2)
    (take_image instrument11 Phenomenon13 thermograph0)
    (take_image instrument11 Phenomenon13 thermograph3)
    (take_image instrument11 Phenomenon13 thermograph4)
    (take_image instrument11 Phenomenon18 image1)
    (take_image instrument11 Phenomenon18 image2)
    (take_image instrument11 Phenomenon18 thermograph0)
    (take_image instrument11 Phenomenon18 thermograph3)
    (take_image instrument11 Phenomenon18 thermograph4)
    (take_image instrument11 Phenomenon5 image1)
    (take_image instrument11 Phenomenon5 image2)
    (take_image instrument11 Phenomenon5 thermograph0)
    (take_image instrument11 Phenomenon5 thermograph3)
    (take_image instrument11 Phenomenon5 thermograph4)
    (take_image instrument11 Phenomenon6 image1)
    (take_image instrument11 Phenomenon6 image2)
    (take_image instrument11 Phenomenon6 thermograph0)
    (take_image instrument11 Phenomenon6 thermograph3)
    (take_image instrument11 Phenomenon6 thermograph4)
    (take_image instrument11 Phenomenon7 image1)
    (take_image instrument11 Phenomenon7 image2)
    (take_image instrument11 Phenomenon7 thermograph0)
    (take_image instrument11 Phenomenon7 thermograph3)
    (take_image instrument11 Phenomenon7 thermograph4)
    (take_image instrument11 Planet15 image1)
    (take_image instrument11 Planet15 image2)
    (take_image instrument11 Planet15 thermograph0)
    (take_image instrument11 Planet15 thermograph3)
    (take_image instrument11 Planet15 thermograph4)
    (take_image instrument11 Planet16 image1)
    (take_image instrument11 Planet16 image2)
    (take_image instrument11 Planet16 thermograph0)
    (take_image instrument11 Planet16 thermograph3)
    (take_image instrument11 Planet16 thermograph4)
    (take_image instrument11 Planet17 image1)
    (take_image instrument11 Planet17 image2)
    (take_image instrument11 Planet17 thermograph0)
    (take_image instrument11 Planet17 thermograph3)
    (take_image instrument11 Planet17 thermograph4)
    (take_image instrument11 Planet21 image1)
    (take_image instrument11 Planet21 image2)
    (take_image instrument11 Planet21 thermograph0)
    (take_image instrument11 Planet21 thermograph3)
    (take_image instrument11 Planet21 thermograph4)
    (take_image instrument11 Planet23 image1)
    (take_image instrument11 Planet23 image2)
    (take_image instrument11 Planet23 thermograph0)
    (take_image instrument11 Planet23 thermograph3)
    (take_image instrument11 Planet23 thermograph4)
    (take_image instrument11 Planet8 image1)
    (take_image instrument11 Planet8 image2)
    (take_image instrument11 Planet8 thermograph0)
    (take_image instrument11 Planet8 thermograph3)
    (take_image instrument11 Planet8 thermograph4)
    (take_image instrument11 Star10 image1)
    (take_image instrument11 Star10 image2)
    (take_image instrument11 Star10 thermograph0)
    (take_image instrument11 Star10 thermograph3)
    (take_image instrument11 Star10 thermograph4)
    (take_image instrument11 Star14 image1)
    (take_image instrument11 Star14 image2)
    (take_image instrument11 Star14 thermograph0)
    (take_image instrument11 Star14 thermograph3)
    (take_image instrument11 Star14 thermograph4)
    (take_image instrument11 Star19 image1)
    (take_image instrument11 Star19 image2)
    (take_image instrument11 Star19 thermograph0)
    (take_image instrument11 Star19 thermograph3)
    (take_image instrument11 Star19 thermograph4)
    (take_image instrument11 Star20 image1)
    (take_image instrument11 Star20 image2)
    (take_image instrument11 Star20 thermograph0)
    (take_image instrument11 Star20 thermograph3)
    (take_image instrument11 Star20 thermograph4)
    (take_image instrument11 Star22 image1)
    (take_image instrument11 Star22 image2)
    (take_image instrument11 Star22 thermograph0)
    (take_image instrument11 Star22 thermograph3)
    (take_image instrument11 Star22 thermograph4)
    (take_image instrument11 Star24 image1)
    (take_image instrument11 Star24 image2)
    (take_image instrument11 Star24 thermograph0)
    (take_image instrument11 Star24 thermograph3)
    (take_image instrument11 Star24 thermograph4)
    (take_image instrument11 Star9 image1)
    (take_image instrument11 Star9 image2)
    (take_image instrument11 Star9 thermograph0)
    (take_image instrument11 Star9 thermograph3)
    (take_image instrument11 Star9 thermograph4)
    (take_image instrument2 GroundStation0 image1)
    (take_image instrument2 GroundStation0 image2)
    (take_image instrument2 GroundStation0 thermograph0)
    (take_image instrument2 GroundStation0 thermograph3)
    (take_image instrument2 GroundStation0 thermograph4)
    (take_image instrument2 GroundStation1 image1)
    (take_image instrument2 GroundStation1 image2)
    (take_image instrument2 GroundStation1 thermograph0)
    (take_image instrument2 GroundStation1 thermograph3)
    (take_image instrument2 GroundStation1 thermograph4)
    (take_image instrument2 GroundStation2 image1)
    (take_image instrument2 GroundStation2 image2)
    (take_image instrument2 GroundStation2 thermograph0)
    (take_image instrument2 GroundStation2 thermograph3)
    (take_image instrument2 GroundStation2 thermograph4)
    (take_image instrument2 GroundStation3 image1)
    (take_image instrument2 GroundStation3 image2)
    (take_image instrument2 GroundStation3 thermograph0)
    (take_image instrument2 GroundStation3 thermograph3)
    (take_image instrument2 GroundStation3 thermograph4)
    (take_image instrument2 GroundStation4 image1)
    (take_image instrument2 GroundStation4 image2)
    (take_image instrument2 GroundStation4 thermograph0)
    (take_image instrument2 GroundStation4 thermograph3)
    (take_image instrument2 GroundStation4 thermograph4)
    (take_image instrument2 Phenomenon11 image1)
    (take_image instrument2 Phenomenon11 image2)
    (take_image instrument2 Phenomenon11 thermograph0)
    (take_image instrument2 Phenomenon11 thermograph3)
    (take_image instrument2 Phenomenon11 thermograph4)
    (take_image instrument2 Phenomenon12 image1)
    (take_image instrument2 Phenomenon12 image2)
    (take_image instrument2 Phenomenon12 thermograph0)
    (take_image instrument2 Phenomenon12 thermograph3)
    (take_image instrument2 Phenomenon12 thermograph4)
    (take_image instrument2 Phenomenon13 image1)
    (take_image instrument2 Phenomenon13 image2)
    (take_image instrument2 Phenomenon13 thermograph0)
    (take_image instrument2 Phenomenon13 thermograph3)
    (take_image instrument2 Phenomenon13 thermograph4)
    (take_image instrument2 Phenomenon18 image1)
    (take_image instrument2 Phenomenon18 image2)
    (take_image instrument2 Phenomenon18 thermograph0)
    (take_image instrument2 Phenomenon18 thermograph3)
    (take_image instrument2 Phenomenon18 thermograph4)
    (take_image instrument2 Phenomenon5 image1)
    (take_image instrument2 Phenomenon5 image2)
    (take_image instrument2 Phenomenon5 thermograph0)
    (take_image instrument2 Phenomenon5 thermograph3)
    (take_image instrument2 Phenomenon5 thermograph4)
    (take_image instrument2 Phenomenon6 image1)
    (take_image instrument2 Phenomenon6 image2)
    (take_image instrument2 Phenomenon6 thermograph0)
    (take_image instrument2 Phenomenon6 thermograph3)
    (take_image instrument2 Phenomenon6 thermograph4)
    (take_image instrument2 Phenomenon7 image1)
    (take_image instrument2 Phenomenon7 image2)
    (take_image instrument2 Phenomenon7 thermograph0)
    (take_image instrument2 Phenomenon7 thermograph3)
    (take_image instrument2 Phenomenon7 thermograph4)
    (take_image instrument2 Planet15 image1)
    (take_image instrument2 Planet15 image2)
    (take_image instrument2 Planet15 thermograph0)
    (take_image instrument2 Planet15 thermograph3)
    (take_image instrument2 Planet15 thermograph4)
    (take_image instrument2 Planet16 image1)
    (take_image instrument2 Planet16 image2)
    (take_image instrument2 Planet16 thermograph0)
    (take_image instrument2 Planet16 thermograph3)
    (take_image instrument2 Planet16 thermograph4)
    (take_image instrument2 Planet17 image1)
    (take_image instrument2 Planet17 image2)
    (take_image instrument2 Planet17 thermograph0)
    (take_image instrument2 Planet17 thermograph3)
    (take_image instrument2 Planet17 thermograph4)
    (take_image instrument2 Planet21 image1)
    (take_image instrument2 Planet21 image2)
    (take_image instrument2 Planet21 thermograph0)
    (take_image instrument2 Planet21 thermograph3)
    (take_image instrument2 Planet21 thermograph4)
    (take_image instrument2 Planet23 image1)
    (take_image instrument2 Planet23 image2)
    (take_image instrument2 Planet23 thermograph0)
    (take_image instrument2 Planet23 thermograph3)
    (take_image instrument2 Planet23 thermograph4)
    (take_image instrument2 Planet8 image1)
    (take_image instrument2 Planet8 image2)
    (take_image instrument2 Planet8 thermograph0)
    (take_image instrument2 Planet8 thermograph3)
    (take_image instrument2 Planet8 thermograph4)
    (take_image instrument2 Star10 image1)
    (take_image instrument2 Star10 image2)
    (take_image instrument2 Star10 thermograph0)
    (take_image instrument2 Star10 thermograph3)
    (take_image instrument2 Star10 thermograph4)
    (take_image instrument2 Star14 image1)
    (take_image instrument2 Star14 image2)
    (take_image instrument2 Star14 thermograph0)
    (take_image instrument2 Star14 thermograph3)
    (take_image instrument2 Star14 thermograph4)
    (take_image instrument2 Star19 image1)
    (take_image instrument2 Star19 image2)
    (take_image instrument2 Star19 thermograph0)
    (take_image instrument2 Star19 thermograph3)
    (take_image instrument2 Star19 thermograph4)
    (take_image instrument2 Star20 image1)
    (take_image instrument2 Star20 image2)
    (take_image instrument2 Star20 thermograph0)
    (take_image instrument2 Star20 thermograph3)
    (take_image instrument2 Star20 thermograph4)
    (take_image instrument2 Star22 image1)
    (take_image instrument2 Star22 image2)
    (take_image instrument2 Star22 thermograph0)
    (take_image instrument2 Star22 thermograph3)
    (take_image instrument2 Star22 thermograph4)
    (take_image instrument2 Star24 image1)
    (take_image instrument2 Star24 image2)
    (take_image instrument2 Star24 thermograph0)
    (take_image instrument2 Star24 thermograph3)
    (take_image instrument2 Star24 thermograph4)
    (take_image instrument2 Star9 image1)
    (take_image instrument2 Star9 image2)
    (take_image instrument2 Star9 thermograph0)
    (take_image instrument2 Star9 thermograph3)
    (take_image instrument2 Star9 thermograph4)
    (take_image instrument3 GroundStation0 image1)
    (take_image instrument3 GroundStation0 image2)
    (take_image instrument3 GroundStation0 thermograph0)
    (take_image instrument3 GroundStation0 thermograph3)
    (take_image instrument3 GroundStation0 thermograph4)
    (take_image instrument3 GroundStation1 image1)
    (take_image instrument3 GroundStation1 image2)
    (take_image instrument3 GroundStation1 thermograph0)
    (take_image instrument3 GroundStation1 thermograph3)
    (take_image instrument3 GroundStation1 thermograph4)
    (take_image instrument3 GroundStation2 image1)
    (take_image instrument3 GroundStation2 image2)
    (take_image instrument3 GroundStation2 thermograph0)
    (take_image instrument3 GroundStation2 thermograph3)
    (take_image instrument3 GroundStation2 thermograph4)
    (take_image instrument3 GroundStation3 image1)
    (take_image instrument3 GroundStation3 image2)
    (take_image instrument3 GroundStation3 thermograph0)
    (take_image instrument3 GroundStation3 thermograph3)
    (take_image instrument3 GroundStation3 thermograph4)
    (take_image instrument3 GroundStation4 image1)
    (take_image instrument3 GroundStation4 image2)
    (take_image instrument3 GroundStation4 thermograph0)
    (take_image instrument3 GroundStation4 thermograph3)
    (take_image instrument3 GroundStation4 thermograph4)
    (take_image instrument3 Phenomenon11 image1)
    (take_image instrument3 Phenomenon11 image2)
    (take_image instrument3 Phenomenon11 thermograph0)
    (take_image instrument3 Phenomenon11 thermograph3)
    (take_image instrument3 Phenomenon11 thermograph4)
    (take_image instrument3 Phenomenon12 image1)
    (take_image instrument3 Phenomenon12 image2)
    (take_image instrument3 Phenomenon12 thermograph0)
    (take_image instrument3 Phenomenon12 thermograph3)
    (take_image instrument3 Phenomenon12 thermograph4)
    (take_image instrument3 Phenomenon13 image1)
    (take_image instrument3 Phenomenon13 image2)
    (take_image instrument3 Phenomenon13 thermograph0)
    (take_image instrument3 Phenomenon13 thermograph3)
    (take_image instrument3 Phenomenon13 thermograph4)
    (take_image instrument3 Phenomenon18 image1)
    (take_image instrument3 Phenomenon18 image2)
    (take_image instrument3 Phenomenon18 thermograph0)
    (take_image instrument3 Phenomenon18 thermograph3)
    (take_image instrument3 Phenomenon18 thermograph4)
    (take_image instrument3 Phenomenon5 image1)
    (take_image instrument3 Phenomenon5 image2)
    (take_image instrument3 Phenomenon5 thermograph0)
    (take_image instrument3 Phenomenon5 thermograph3)
    (take_image instrument3 Phenomenon5 thermograph4)
    (take_image instrument3 Phenomenon6 image1)
    (take_image instrument3 Phenomenon6 image2)
    (take_image instrument3 Phenomenon6 thermograph0)
    (take_image instrument3 Phenomenon6 thermograph3)
    (take_image instrument3 Phenomenon6 thermograph4)
    (take_image instrument3 Phenomenon7 image1)
    (take_image instrument3 Phenomenon7 image2)
    (take_image instrument3 Phenomenon7 thermograph0)
    (take_image instrument3 Phenomenon7 thermograph3)
    (take_image instrument3 Phenomenon7 thermograph4)
    (take_image instrument3 Planet15 image1)
    (take_image instrument3 Planet15 image2)
    (take_image instrument3 Planet15 thermograph0)
    (take_image instrument3 Planet15 thermograph3)
    (take_image instrument3 Planet15 thermograph4)
    (take_image instrument3 Planet16 image1)
    (take_image instrument3 Planet16 image2)
    (take_image instrument3 Planet16 thermograph0)
    (take_image instrument3 Planet16 thermograph3)
    (take_image instrument3 Planet16 thermograph4)
    (take_image instrument3 Planet17 image1)
    (take_image instrument3 Planet17 image2)
    (take_image instrument3 Planet17 thermograph0)
    (take_image instrument3 Planet17 thermograph3)
    (take_image instrument3 Planet17 thermograph4)
    (take_image instrument3 Planet21 image1)
    (take_image instrument3 Planet21 image2)
    (take_image instrument3 Planet21 thermograph0)
    (take_image instrument3 Planet21 thermograph3)
    (take_image instrument3 Planet21 thermograph4)
    (take_image instrument3 Planet23 image1)
    (take_image instrument3 Planet23 image2)
    (take_image instrument3 Planet23 thermograph0)
    (take_image instrument3 Planet23 thermograph3)
    (take_image instrument3 Planet23 thermograph4)
    (take_image instrument3 Planet8 image1)
    (take_image instrument3 Planet8 image2)
    (take_image instrument3 Planet8 thermograph0)
    (take_image instrument3 Planet8 thermograph3)
    (take_image instrument3 Planet8 thermograph4)
    (take_image instrument3 Star10 image1)
    (take_image instrument3 Star10 image2)
    (take_image instrument3 Star10 thermograph0)
    (take_image instrument3 Star10 thermograph3)
    (take_image instrument3 Star10 thermograph4)
    (take_image instrument3 Star14 image1)
    (take_image instrument3 Star14 image2)
    (take_image instrument3 Star14 thermograph0)
    (take_image instrument3 Star14 thermograph3)
    (take_image instrument3 Star14 thermograph4)
    (take_image instrument3 Star19 image1)
    (take_image instrument3 Star19 image2)
    (take_image instrument3 Star19 thermograph0)
    (take_image instrument3 Star19 thermograph3)
    (take_image instrument3 Star19 thermograph4)
    (take_image instrument3 Star20 image1)
    (take_image instrument3 Star20 image2)
    (take_image instrument3 Star20 thermograph0)
    (take_image instrument3 Star20 thermograph3)
    (take_image instrument3 Star20 thermograph4)
    (take_image instrument3 Star22 image1)
    (take_image instrument3 Star22 image2)
    (take_image instrument3 Star22 thermograph0)
    (take_image instrument3 Star22 thermograph3)
    (take_image instrument3 Star22 thermograph4)
    (take_image instrument3 Star24 image1)
    (take_image instrument3 Star24 image2)
    (take_image instrument3 Star24 thermograph0)
    (take_image instrument3 Star24 thermograph3)
    (take_image instrument3 Star24 thermograph4)
    (take_image instrument3 Star9 image1)
    (take_image instrument3 Star9 image2)
    (take_image instrument3 Star9 thermograph0)
    (take_image instrument3 Star9 thermograph3)
    (take_image instrument3 Star9 thermograph4)
    (take_image instrument4 GroundStation0 image1)
    (take_image instrument4 GroundStation0 image2)
    (take_image instrument4 GroundStation0 thermograph0)
    (take_image instrument4 GroundStation0 thermograph3)
    (take_image instrument4 GroundStation0 thermograph4)
    (take_image instrument4 GroundStation1 image1)
    (take_image instrument4 GroundStation1 image2)
    (take_image instrument4 GroundStation1 thermograph0)
    (take_image instrument4 GroundStation1 thermograph3)
    (take_image instrument4 GroundStation1 thermograph4)
    (take_image instrument4 GroundStation2 image1)
    (take_image instrument4 GroundStation2 image2)
    (take_image instrument4 GroundStation2 thermograph0)
    (take_image instrument4 GroundStation2 thermograph3)
    (take_image instrument4 GroundStation2 thermograph4)
    (take_image instrument4 GroundStation3 image1)
    (take_image instrument4 GroundStation3 image2)
    (take_image instrument4 GroundStation3 thermograph0)
    (take_image instrument4 GroundStation3 thermograph3)
    (take_image instrument4 GroundStation3 thermograph4)
    (take_image instrument4 GroundStation4 image1)
    (take_image instrument4 GroundStation4 image2)
    (take_image instrument4 GroundStation4 thermograph0)
    (take_image instrument4 GroundStation4 thermograph3)
    (take_image instrument4 GroundStation4 thermograph4)
    (take_image instrument4 Phenomenon11 image1)
    (take_image instrument4 Phenomenon11 image2)
    (take_image instrument4 Phenomenon11 thermograph0)
    (take_image instrument4 Phenomenon11 thermograph3)
    (take_image instrument4 Phenomenon11 thermograph4)
    (take_image instrument4 Phenomenon12 image1)
    (take_image instrument4 Phenomenon12 image2)
    (take_image instrument4 Phenomenon12 thermograph0)
    (take_image instrument4 Phenomenon12 thermograph3)
    (take_image instrument4 Phenomenon12 thermograph4)
    (take_image instrument4 Phenomenon13 image1)
    (take_image instrument4 Phenomenon13 image2)
    (take_image instrument4 Phenomenon13 thermograph0)
    (take_image instrument4 Phenomenon13 thermograph3)
    (take_image instrument4 Phenomenon13 thermograph4)
    (take_image instrument4 Phenomenon18 image1)
    (take_image instrument4 Phenomenon18 image2)
    (take_image instrument4 Phenomenon18 thermograph0)
    (take_image instrument4 Phenomenon18 thermograph3)
    (take_image instrument4 Phenomenon18 thermograph4)
    (take_image instrument4 Phenomenon5 image1)
    (take_image instrument4 Phenomenon5 image2)
    (take_image instrument4 Phenomenon5 thermograph0)
    (take_image instrument4 Phenomenon5 thermograph3)
    (take_image instrument4 Phenomenon5 thermograph4)
    (take_image instrument4 Phenomenon6 image1)
    (take_image instrument4 Phenomenon6 image2)
    (take_image instrument4 Phenomenon6 thermograph0)
    (take_image instrument4 Phenomenon6 thermograph3)
    (take_image instrument4 Phenomenon6 thermograph4)
    (take_image instrument4 Phenomenon7 image1)
    (take_image instrument4 Phenomenon7 image2)
    (take_image instrument4 Phenomenon7 thermograph0)
    (take_image instrument4 Phenomenon7 thermograph3)
    (take_image instrument4 Phenomenon7 thermograph4)
    (take_image instrument4 Planet15 image1)
    (take_image instrument4 Planet15 image2)
    (take_image instrument4 Planet15 thermograph0)
    (take_image instrument4 Planet15 thermograph3)
    (take_image instrument4 Planet15 thermograph4)
    (take_image instrument4 Planet16 image1)
    (take_image instrument4 Planet16 image2)
    (take_image instrument4 Planet16 thermograph0)
    (take_image instrument4 Planet16 thermograph3)
    (take_image instrument4 Planet16 thermograph4)
    (take_image instrument4 Planet17 image1)
    (take_image instrument4 Planet17 image2)
    (take_image instrument4 Planet17 thermograph0)
    (take_image instrument4 Planet17 thermograph3)
    (take_image instrument4 Planet17 thermograph4)
    (take_image instrument4 Planet21 image1)
    (take_image instrument4 Planet21 image2)
    (take_image instrument4 Planet21 thermograph0)
    (take_image instrument4 Planet21 thermograph3)
    (take_image instrument4 Planet21 thermograph4)
    (take_image instrument4 Planet23 image1)
    (take_image instrument4 Planet23 image2)
    (take_image instrument4 Planet23 thermograph0)
    (take_image instrument4 Planet23 thermograph3)
    (take_image instrument4 Planet23 thermograph4)
    (take_image instrument4 Planet8 image1)
    (take_image instrument4 Planet8 image2)
    (take_image instrument4 Planet8 thermograph0)
    (take_image instrument4 Planet8 thermograph3)
    (take_image instrument4 Planet8 thermograph4)
    (take_image instrument4 Star10 image1)
    (take_image instrument4 Star10 image2)
    (take_image instrument4 Star10 thermograph0)
    (take_image instrument4 Star10 thermograph3)
    (take_image instrument4 Star10 thermograph4)
    (take_image instrument4 Star14 image1)
    (take_image instrument4 Star14 image2)
    (take_image instrument4 Star14 thermograph0)
    (take_image instrument4 Star14 thermograph3)
    (take_image instrument4 Star14 thermograph4)
    (take_image instrument4 Star19 image1)
    (take_image instrument4 Star19 image2)
    (take_image instrument4 Star19 thermograph0)
    (take_image instrument4 Star19 thermograph3)
    (take_image instrument4 Star19 thermograph4)
    (take_image instrument4 Star20 image1)
    (take_image instrument4 Star20 image2)
    (take_image instrument4 Star20 thermograph0)
    (take_image instrument4 Star20 thermograph3)
    (take_image instrument4 Star20 thermograph4)
    (take_image instrument4 Star22 image1)
    (take_image instrument4 Star22 image2)
    (take_image instrument4 Star22 thermograph0)
    (take_image instrument4 Star22 thermograph3)
    (take_image instrument4 Star22 thermograph4)
    (take_image instrument4 Star24 image1)
    (take_image instrument4 Star24 image2)
    (take_image instrument4 Star24 thermograph0)
    (take_image instrument4 Star24 thermograph3)
    (take_image instrument4 Star24 thermograph4)
    (take_image instrument4 Star9 image1)
    (take_image instrument4 Star9 image2)
    (take_image instrument4 Star9 thermograph0)
    (take_image instrument4 Star9 thermograph3)
    (take_image instrument4 Star9 thermograph4)
    (take_image instrument5 GroundStation0 image1)
    (take_image instrument5 GroundStation0 image2)
    (take_image instrument5 GroundStation0 thermograph0)
    (take_image instrument5 GroundStation0 thermograph3)
    (take_image instrument5 GroundStation0 thermograph4)
    (take_image instrument5 GroundStation1 image1)
    (take_image instrument5 GroundStation1 image2)
    (take_image instrument5 GroundStation1 thermograph0)
    (take_image instrument5 GroundStation1 thermograph3)
    (take_image instrument5 GroundStation1 thermograph4)
    (take_image instrument5 GroundStation2 image1)
    (take_image instrument5 GroundStation2 image2)
    (take_image instrument5 GroundStation2 thermograph0)
    (take_image instrument5 GroundStation2 thermograph3)
    (take_image instrument5 GroundStation2 thermograph4)
    (take_image instrument5 GroundStation3 image1)
    (take_image instrument5 GroundStation3 image2)
    (take_image instrument5 GroundStation3 thermograph0)
    (take_image instrument5 GroundStation3 thermograph3)
    (take_image instrument5 GroundStation3 thermograph4)
    (take_image instrument5 GroundStation4 image1)
    (take_image instrument5 GroundStation4 image2)
    (take_image instrument5 GroundStation4 thermograph0)
    (take_image instrument5 GroundStation4 thermograph3)
    (take_image instrument5 GroundStation4 thermograph4)
    (take_image instrument5 Phenomenon11 image1)
    (take_image instrument5 Phenomenon11 image2)
    (take_image instrument5 Phenomenon11 thermograph0)
    (take_image instrument5 Phenomenon11 thermograph3)
    (take_image instrument5 Phenomenon11 thermograph4)
    (take_image instrument5 Phenomenon12 image1)
    (take_image instrument5 Phenomenon12 image2)
    (take_image instrument5 Phenomenon12 thermograph0)
    (take_image instrument5 Phenomenon12 thermograph3)
    (take_image instrument5 Phenomenon12 thermograph4)
    (take_image instrument5 Phenomenon13 image1)
    (take_image instrument5 Phenomenon13 image2)
    (take_image instrument5 Phenomenon13 thermograph0)
    (take_image instrument5 Phenomenon13 thermograph3)
    (take_image instrument5 Phenomenon13 thermograph4)
    (take_image instrument5 Phenomenon18 image1)
    (take_image instrument5 Phenomenon18 image2)
    (take_image instrument5 Phenomenon18 thermograph0)
    (take_image instrument5 Phenomenon18 thermograph3)
    (take_image instrument5 Phenomenon18 thermograph4)
    (take_image instrument5 Phenomenon5 image1)
    (take_image instrument5 Phenomenon5 image2)
    (take_image instrument5 Phenomenon5 thermograph0)
    (take_image instrument5 Phenomenon5 thermograph3)
    (take_image instrument5 Phenomenon5 thermograph4)
    (take_image instrument5 Phenomenon6 image1)
    (take_image instrument5 Phenomenon6 image2)
    (take_image instrument5 Phenomenon6 thermograph0)
    (take_image instrument5 Phenomenon6 thermograph3)
    (take_image instrument5 Phenomenon6 thermograph4)
    (take_image instrument5 Phenomenon7 image1)
    (take_image instrument5 Phenomenon7 image2)
    (take_image instrument5 Phenomenon7 thermograph0)
    (take_image instrument5 Phenomenon7 thermograph3)
    (take_image instrument5 Phenomenon7 thermograph4)
    (take_image instrument5 Planet15 image1)
    (take_image instrument5 Planet15 image2)
    (take_image instrument5 Planet15 thermograph0)
    (take_image instrument5 Planet15 thermograph3)
    (take_image instrument5 Planet15 thermograph4)
    (take_image instrument5 Planet16 image1)
    (take_image instrument5 Planet16 image2)
    (take_image instrument5 Planet16 thermograph0)
    (take_image instrument5 Planet16 thermograph3)
    (take_image instrument5 Planet16 thermograph4)
    (take_image instrument5 Planet17 image1)
    (take_image instrument5 Planet17 image2)
    (take_image instrument5 Planet17 thermograph0)
    (take_image instrument5 Planet17 thermograph3)
    (take_image instrument5 Planet17 thermograph4)
    (take_image instrument5 Planet21 image1)
    (take_image instrument5 Planet21 image2)
    (take_image instrument5 Planet21 thermograph0)
    (take_image instrument5 Planet21 thermograph3)
    (take_image instrument5 Planet21 thermograph4)
    (take_image instrument5 Planet23 image1)
    (take_image instrument5 Planet23 image2)
    (take_image instrument5 Planet23 thermograph0)
    (take_image instrument5 Planet23 thermograph3)
    (take_image instrument5 Planet23 thermograph4)
    (take_image instrument5 Planet8 image1)
    (take_image instrument5 Planet8 image2)
    (take_image instrument5 Planet8 thermograph0)
    (take_image instrument5 Planet8 thermograph3)
    (take_image instrument5 Planet8 thermograph4)
    (take_image instrument5 Star10 image1)
    (take_image instrument5 Star10 image2)
    (take_image instrument5 Star10 thermograph0)
    (take_image instrument5 Star10 thermograph3)
    (take_image instrument5 Star10 thermograph4)
    (take_image instrument5 Star14 image1)
    (take_image instrument5 Star14 image2)
    (take_image instrument5 Star14 thermograph0)
    (take_image instrument5 Star14 thermograph3)
    (take_image instrument5 Star14 thermograph4)
    (take_image instrument5 Star19 image1)
    (take_image instrument5 Star19 image2)
    (take_image instrument5 Star19 thermograph0)
    (take_image instrument5 Star19 thermograph3)
    (take_image instrument5 Star19 thermograph4)
    (take_image instrument5 Star20 image1)
    (take_image instrument5 Star20 image2)
    (take_image instrument5 Star20 thermograph0)
    (take_image instrument5 Star20 thermograph3)
    (take_image instrument5 Star20 thermograph4)
    (take_image instrument5 Star22 image1)
    (take_image instrument5 Star22 image2)
    (take_image instrument5 Star22 thermograph0)
    (take_image instrument5 Star22 thermograph3)
    (take_image instrument5 Star22 thermograph4)
    (take_image instrument5 Star24 image1)
    (take_image instrument5 Star24 image2)
    (take_image instrument5 Star24 thermograph0)
    (take_image instrument5 Star24 thermograph3)
    (take_image instrument5 Star24 thermograph4)
    (take_image instrument5 Star9 image1)
    (take_image instrument5 Star9 image2)
    (take_image instrument5 Star9 thermograph0)
    (take_image instrument5 Star9 thermograph3)
    (take_image instrument5 Star9 thermograph4)
    (take_image instrument6 GroundStation0 image1)
    (take_image instrument6 GroundStation0 image2)
    (take_image instrument6 GroundStation0 thermograph0)
    (take_image instrument6 GroundStation0 thermograph3)
    (take_image instrument6 GroundStation0 thermograph4)
    (take_image instrument6 GroundStation1 image1)
    (take_image instrument6 GroundStation1 image2)
    (take_image instrument6 GroundStation1 thermograph0)
    (take_image instrument6 GroundStation1 thermograph3)
    (take_image instrument6 GroundStation1 thermograph4)
    (take_image instrument6 GroundStation2 image1)
    (take_image instrument6 GroundStation2 image2)
    (take_image instrument6 GroundStation2 thermograph0)
    (take_image instrument6 GroundStation2 thermograph3)
    (take_image instrument6 GroundStation2 thermograph4)
    (take_image instrument6 GroundStation3 image1)
    (take_image instrument6 GroundStation3 image2)
    (take_image instrument6 GroundStation3 thermograph0)
    (take_image instrument6 GroundStation3 thermograph3)
    (take_image instrument6 GroundStation3 thermograph4)
    (take_image instrument6 GroundStation4 image1)
    (take_image instrument6 GroundStation4 image2)
    (take_image instrument6 GroundStation4 thermograph0)
    (take_image instrument6 GroundStation4 thermograph3)
    (take_image instrument6 GroundStation4 thermograph4)
    (take_image instrument6 Phenomenon11 image1)
    (take_image instrument6 Phenomenon11 image2)
    (take_image instrument6 Phenomenon11 thermograph0)
    (take_image instrument6 Phenomenon11 thermograph3)
    (take_image instrument6 Phenomenon11 thermograph4)
    (take_image instrument6 Phenomenon12 image1)
    (take_image instrument6 Phenomenon12 image2)
    (take_image instrument6 Phenomenon12 thermograph0)
    (take_image instrument6 Phenomenon12 thermograph3)
    (take_image instrument6 Phenomenon12 thermograph4)
    (take_image instrument6 Phenomenon13 image1)
    (take_image instrument6 Phenomenon13 image2)
    (take_image instrument6 Phenomenon13 thermograph0)
    (take_image instrument6 Phenomenon13 thermograph3)
    (take_image instrument6 Phenomenon13 thermograph4)
    (take_image instrument6 Phenomenon18 image1)
    (take_image instrument6 Phenomenon18 image2)
    (take_image instrument6 Phenomenon18 thermograph0)
    (take_image instrument6 Phenomenon18 thermograph3)
    (take_image instrument6 Phenomenon18 thermograph4)
    (take_image instrument6 Phenomenon5 image1)
    (take_image instrument6 Phenomenon5 image2)
    (take_image instrument6 Phenomenon5 thermograph0)
    (take_image instrument6 Phenomenon5 thermograph3)
    (take_image instrument6 Phenomenon5 thermograph4)
    (take_image instrument6 Phenomenon6 image1)
    (take_image instrument6 Phenomenon6 image2)
    (take_image instrument6 Phenomenon6 thermograph0)
    (take_image instrument6 Phenomenon6 thermograph3)
    (take_image instrument6 Phenomenon6 thermograph4)
    (take_image instrument6 Phenomenon7 image1)
    (take_image instrument6 Phenomenon7 image2)
    (take_image instrument6 Phenomenon7 thermograph0)
    (take_image instrument6 Phenomenon7 thermograph3)
    (take_image instrument6 Phenomenon7 thermograph4)
    (take_image instrument6 Planet15 image1)
    (take_image instrument6 Planet15 image2)
    (take_image instrument6 Planet15 thermograph0)
    (take_image instrument6 Planet15 thermograph3)
    (take_image instrument6 Planet15 thermograph4)
    (take_image instrument6 Planet16 image1)
    (take_image instrument6 Planet16 image2)
    (take_image instrument6 Planet16 thermograph0)
    (take_image instrument6 Planet16 thermograph3)
    (take_image instrument6 Planet16 thermograph4)
    (take_image instrument6 Planet17 image1)
    (take_image instrument6 Planet17 image2)
    (take_image instrument6 Planet17 thermograph0)
    (take_image instrument6 Planet17 thermograph3)
    (take_image instrument6 Planet17 thermograph4)
    (take_image instrument6 Planet21 image1)
    (take_image instrument6 Planet21 image2)
    (take_image instrument6 Planet21 thermograph0)
    (take_image instrument6 Planet21 thermograph3)
    (take_image instrument6 Planet21 thermograph4)
    (take_image instrument6 Planet23 image1)
    (take_image instrument6 Planet23 image2)
    (take_image instrument6 Planet23 thermograph0)
    (take_image instrument6 Planet23 thermograph3)
    (take_image instrument6 Planet23 thermograph4)
    (take_image instrument6 Planet8 image1)
    (take_image instrument6 Planet8 image2)
    (take_image instrument6 Planet8 thermograph0)
    (take_image instrument6 Planet8 thermograph3)
    (take_image instrument6 Planet8 thermograph4)
    (take_image instrument6 Star10 image1)
    (take_image instrument6 Star10 image2)
    (take_image instrument6 Star10 thermograph0)
    (take_image instrument6 Star10 thermograph3)
    (take_image instrument6 Star10 thermograph4)
    (take_image instrument6 Star14 image1)
    (take_image instrument6 Star14 image2)
    (take_image instrument6 Star14 thermograph0)
    (take_image instrument6 Star14 thermograph3)
    (take_image instrument6 Star14 thermograph4)
    (take_image instrument6 Star19 image1)
    (take_image instrument6 Star19 image2)
    (take_image instrument6 Star19 thermograph0)
    (take_image instrument6 Star19 thermograph3)
    (take_image instrument6 Star19 thermograph4)
    (take_image instrument6 Star20 image1)
    (take_image instrument6 Star20 image2)
    (take_image instrument6 Star20 thermograph0)
    (take_image instrument6 Star20 thermograph3)
    (take_image instrument6 Star20 thermograph4)
    (take_image instrument6 Star22 image1)
    (take_image instrument6 Star22 image2)
    (take_image instrument6 Star22 thermograph0)
    (take_image instrument6 Star22 thermograph3)
    (take_image instrument6 Star22 thermograph4)
    (take_image instrument6 Star24 image1)
    (take_image instrument6 Star24 image2)
    (take_image instrument6 Star24 thermograph0)
    (take_image instrument6 Star24 thermograph3)
    (take_image instrument6 Star24 thermograph4)
    (take_image instrument6 Star9 image1)
    (take_image instrument6 Star9 image2)
    (take_image instrument6 Star9 thermograph0)
    (take_image instrument6 Star9 thermograph3)
    (take_image instrument6 Star9 thermograph4)
    (take_image instrument7 GroundStation0 image1)
    (take_image instrument7 GroundStation0 image2)
    (take_image instrument7 GroundStation0 thermograph0)
    (take_image instrument7 GroundStation0 thermograph3)
    (take_image instrument7 GroundStation0 thermograph4)
    (take_image instrument7 GroundStation1 image1)
    (take_image instrument7 GroundStation1 image2)
    (take_image instrument7 GroundStation1 thermograph0)
    (take_image instrument7 GroundStation1 thermograph3)
    (take_image instrument7 GroundStation1 thermograph4)
    (take_image instrument7 GroundStation2 image1)
    (take_image instrument7 GroundStation2 image2)
    (take_image instrument7 GroundStation2 thermograph0)
    (take_image instrument7 GroundStation2 thermograph3)
    (take_image instrument7 GroundStation2 thermograph4)
    (take_image instrument7 GroundStation3 image1)
    (take_image instrument7 GroundStation3 image2)
    (take_image instrument7 GroundStation3 thermograph0)
    (take_image instrument7 GroundStation3 thermograph3)
    (take_image instrument7 GroundStation3 thermograph4)
    (take_image instrument7 GroundStation4 image1)
    (take_image instrument7 GroundStation4 image2)
    (take_image instrument7 GroundStation4 thermograph0)
    (take_image instrument7 GroundStation4 thermograph3)
    (take_image instrument7 GroundStation4 thermograph4)
    (take_image instrument7 Phenomenon11 image1)
    (take_image instrument7 Phenomenon11 image2)
    (take_image instrument7 Phenomenon11 thermograph0)
    (take_image instrument7 Phenomenon11 thermograph3)
    (take_image instrument7 Phenomenon11 thermograph4)
    (take_image instrument7 Phenomenon12 image1)
    (take_image instrument7 Phenomenon12 image2)
    (take_image instrument7 Phenomenon12 thermograph0)
    (take_image instrument7 Phenomenon12 thermograph3)
    (take_image instrument7 Phenomenon12 thermograph4)
    (take_image instrument7 Phenomenon13 image1)
    (take_image instrument7 Phenomenon13 image2)
    (take_image instrument7 Phenomenon13 thermograph0)
    (take_image instrument7 Phenomenon13 thermograph3)
    (take_image instrument7 Phenomenon13 thermograph4)
    (take_image instrument7 Phenomenon18 image1)
    (take_image instrument7 Phenomenon18 image2)
    (take_image instrument7 Phenomenon18 thermograph0)
    (take_image instrument7 Phenomenon18 thermograph3)
    (take_image instrument7 Phenomenon18 thermograph4)
    (take_image instrument7 Phenomenon5 image1)
    (take_image instrument7 Phenomenon5 image2)
    (take_image instrument7 Phenomenon5 thermograph0)
    (take_image instrument7 Phenomenon5 thermograph3)
    (take_image instrument7 Phenomenon5 thermograph4)
    (take_image instrument7 Phenomenon6 image1)
    (take_image instrument7 Phenomenon6 image2)
    (take_image instrument7 Phenomenon6 thermograph0)
    (take_image instrument7 Phenomenon6 thermograph3)
    (take_image instrument7 Phenomenon6 thermograph4)
    (take_image instrument7 Phenomenon7 image1)
    (take_image instrument7 Phenomenon7 image2)
    (take_image instrument7 Phenomenon7 thermograph0)
    (take_image instrument7 Phenomenon7 thermograph3)
    (take_image instrument7 Phenomenon7 thermograph4)
    (take_image instrument7 Planet15 image1)
    (take_image instrument7 Planet15 image2)
    (take_image instrument7 Planet15 thermograph0)
    (take_image instrument7 Planet15 thermograph3)
    (take_image instrument7 Planet15 thermograph4)
    (take_image instrument7 Planet16 image1)
    (take_image instrument7 Planet16 image2)
    (take_image instrument7 Planet16 thermograph0)
    (take_image instrument7 Planet16 thermograph3)
    (take_image instrument7 Planet16 thermograph4)
    (take_image instrument7 Planet17 image1)
    (take_image instrument7 Planet17 image2)
    (take_image instrument7 Planet17 thermograph0)
    (take_image instrument7 Planet17 thermograph3)
    (take_image instrument7 Planet17 thermograph4)
    (take_image instrument7 Planet21 image1)
    (take_image instrument7 Planet21 image2)
    (take_image instrument7 Planet21 thermograph0)
    (take_image instrument7 Planet21 thermograph3)
    (take_image instrument7 Planet21 thermograph4)
    (take_image instrument7 Planet23 image1)
    (take_image instrument7 Planet23 image2)
    (take_image instrument7 Planet23 thermograph0)
    (take_image instrument7 Planet23 thermograph3)
    (take_image instrument7 Planet23 thermograph4)
    (take_image instrument7 Planet8 image1)
    (take_image instrument7 Planet8 image2)
    (take_image instrument7 Planet8 thermograph0)
    (take_image instrument7 Planet8 thermograph3)
    (take_image instrument7 Planet8 thermograph4)
    (take_image instrument7 Star10 image1)
    (take_image instrument7 Star10 image2)
    (take_image instrument7 Star10 thermograph0)
    (take_image instrument7 Star10 thermograph3)
    (take_image instrument7 Star10 thermograph4)
    (take_image instrument7 Star14 image1)
    (take_image instrument7 Star14 image2)
    (take_image instrument7 Star14 thermograph0)
    (take_image instrument7 Star14 thermograph3)
    (take_image instrument7 Star14 thermograph4)
    (take_image instrument7 Star19 image1)
    (take_image instrument7 Star19 image2)
    (take_image instrument7 Star19 thermograph0)
    (take_image instrument7 Star19 thermograph3)
    (take_image instrument7 Star19 thermograph4)
    (take_image instrument7 Star20 image1)
    (take_image instrument7 Star20 image2)
    (take_image instrument7 Star20 thermograph0)
    (take_image instrument7 Star20 thermograph3)
    (take_image instrument7 Star20 thermograph4)
    (take_image instrument7 Star22 image1)
    (take_image instrument7 Star22 image2)
    (take_image instrument7 Star22 thermograph0)
    (take_image instrument7 Star22 thermograph3)
    (take_image instrument7 Star22 thermograph4)
    (take_image instrument7 Star24 image1)
    (take_image instrument7 Star24 image2)
    (take_image instrument7 Star24 thermograph0)
    (take_image instrument7 Star24 thermograph3)
    (take_image instrument7 Star24 thermograph4)
    (take_image instrument7 Star9 image1)
    (take_image instrument7 Star9 image2)
    (take_image instrument7 Star9 thermograph0)
    (take_image instrument7 Star9 thermograph3)
    (take_image instrument7 Star9 thermograph4)
    (take_image instrument8 GroundStation0 image1)
    (take_image instrument8 GroundStation0 image2)
    (take_image instrument8 GroundStation0 thermograph0)
    (take_image instrument8 GroundStation0 thermograph3)
    (take_image instrument8 GroundStation0 thermograph4)
    (take_image instrument8 GroundStation1 image1)
    (take_image instrument8 GroundStation1 image2)
    (take_image instrument8 GroundStation1 thermograph0)
    (take_image instrument8 GroundStation1 thermograph3)
    (take_image instrument8 GroundStation1 thermograph4)
    (take_image instrument8 GroundStation2 image1)
    (take_image instrument8 GroundStation2 image2)
    (take_image instrument8 GroundStation2 thermograph0)
    (take_image instrument8 GroundStation2 thermograph3)
    (take_image instrument8 GroundStation2 thermograph4)
    (take_image instrument8 GroundStation3 image1)
    (take_image instrument8 GroundStation3 image2)
    (take_image instrument8 GroundStation3 thermograph0)
    (take_image instrument8 GroundStation3 thermograph3)
    (take_image instrument8 GroundStation3 thermograph4)
    (take_image instrument8 GroundStation4 image1)
    (take_image instrument8 GroundStation4 image2)
    (take_image instrument8 GroundStation4 thermograph0)
    (take_image instrument8 GroundStation4 thermograph3)
    (take_image instrument8 GroundStation4 thermograph4)
    (take_image instrument8 Phenomenon11 image1)
    (take_image instrument8 Phenomenon11 image2)
    (take_image instrument8 Phenomenon11 thermograph0)
    (take_image instrument8 Phenomenon11 thermograph3)
    (take_image instrument8 Phenomenon11 thermograph4)
    (take_image instrument8 Phenomenon12 image1)
    (take_image instrument8 Phenomenon12 image2)
    (take_image instrument8 Phenomenon12 thermograph0)
    (take_image instrument8 Phenomenon12 thermograph3)
    (take_image instrument8 Phenomenon12 thermograph4)
    (take_image instrument8 Phenomenon13 image1)
    (take_image instrument8 Phenomenon13 image2)
    (take_image instrument8 Phenomenon13 thermograph0)
    (take_image instrument8 Phenomenon13 thermograph3)
    (take_image instrument8 Phenomenon13 thermograph4)
    (take_image instrument8 Phenomenon18 image1)
    (take_image instrument8 Phenomenon18 image2)
    (take_image instrument8 Phenomenon18 thermograph0)
    (take_image instrument8 Phenomenon18 thermograph3)
    (take_image instrument8 Phenomenon18 thermograph4)
    (take_image instrument8 Phenomenon5 image1)
    (take_image instrument8 Phenomenon5 image2)
    (take_image instrument8 Phenomenon5 thermograph0)
    (take_image instrument8 Phenomenon5 thermograph3)
    (take_image instrument8 Phenomenon5 thermograph4)
    (take_image instrument8 Phenomenon6 image1)
    (take_image instrument8 Phenomenon6 image2)
    (take_image instrument8 Phenomenon6 thermograph0)
    (take_image instrument8 Phenomenon6 thermograph3)
    (take_image instrument8 Phenomenon6 thermograph4)
    (take_image instrument8 Phenomenon7 image1)
    (take_image instrument8 Phenomenon7 image2)
    (take_image instrument8 Phenomenon7 thermograph0)
    (take_image instrument8 Phenomenon7 thermograph3)
    (take_image instrument8 Phenomenon7 thermograph4)
    (take_image instrument8 Planet15 image1)
    (take_image instrument8 Planet15 image2)
    (take_image instrument8 Planet15 thermograph0)
    (take_image instrument8 Planet15 thermograph3)
    (take_image instrument8 Planet15 thermograph4)
    (take_image instrument8 Planet16 image1)
    (take_image instrument8 Planet16 image2)
    (take_image instrument8 Planet16 thermograph0)
    (take_image instrument8 Planet16 thermograph3)
    (take_image instrument8 Planet16 thermograph4)
    (take_image instrument8 Planet17 image1)
    (take_image instrument8 Planet17 image2)
    (take_image instrument8 Planet17 thermograph0)
    (take_image instrument8 Planet17 thermograph3)
    (take_image instrument8 Planet17 thermograph4)
    (take_image instrument8 Planet21 image1)
    (take_image instrument8 Planet21 image2)
    (take_image instrument8 Planet21 thermograph0)
    (take_image instrument8 Planet21 thermograph3)
    (take_image instrument8 Planet21 thermograph4)
    (take_image instrument8 Planet23 image1)
    (take_image instrument8 Planet23 image2)
    (take_image instrument8 Planet23 thermograph0)
    (take_image instrument8 Planet23 thermograph3)
    (take_image instrument8 Planet23 thermograph4)
    (take_image instrument8 Planet8 image1)
    (take_image instrument8 Planet8 image2)
    (take_image instrument8 Planet8 thermograph0)
    (take_image instrument8 Planet8 thermograph3)
    (take_image instrument8 Planet8 thermograph4)
    (take_image instrument8 Star10 image1)
    (take_image instrument8 Star10 image2)
    (take_image instrument8 Star10 thermograph0)
    (take_image instrument8 Star10 thermograph3)
    (take_image instrument8 Star10 thermograph4)
    (take_image instrument8 Star14 image1)
    (take_image instrument8 Star14 image2)
    (take_image instrument8 Star14 thermograph0)
    (take_image instrument8 Star14 thermograph3)
    (take_image instrument8 Star14 thermograph4)
    (take_image instrument8 Star19 image1)
    (take_image instrument8 Star19 image2)
    (take_image instrument8 Star19 thermograph0)
    (take_image instrument8 Star19 thermograph3)
    (take_image instrument8 Star19 thermograph4)
    (take_image instrument8 Star20 image1)
    (take_image instrument8 Star20 image2)
    (take_image instrument8 Star20 thermograph0)
    (take_image instrument8 Star20 thermograph3)
    (take_image instrument8 Star20 thermograph4)
    (take_image instrument8 Star22 image1)
    (take_image instrument8 Star22 image2)
    (take_image instrument8 Star22 thermograph0)
    (take_image instrument8 Star22 thermograph3)
    (take_image instrument8 Star22 thermograph4)
    (take_image instrument8 Star24 image1)
    (take_image instrument8 Star24 image2)
    (take_image instrument8 Star24 thermograph0)
    (take_image instrument8 Star24 thermograph3)
    (take_image instrument8 Star24 thermograph4)
    (take_image instrument8 Star9 image1)
    (take_image instrument8 Star9 image2)
    (take_image instrument8 Star9 thermograph0)
    (take_image instrument8 Star9 thermograph3)
    (take_image instrument8 Star9 thermograph4)
    (take_image instrument9 GroundStation0 image1)
    (take_image instrument9 GroundStation0 image2)
    (take_image instrument9 GroundStation0 thermograph0)
    (take_image instrument9 GroundStation0 thermograph3)
    (take_image instrument9 GroundStation0 thermograph4)
    (take_image instrument9 GroundStation1 image1)
    (take_image instrument9 GroundStation1 image2)
    (take_image instrument9 GroundStation1 thermograph0)
    (take_image instrument9 GroundStation1 thermograph3)
    (take_image instrument9 GroundStation1 thermograph4)
    (take_image instrument9 GroundStation2 image1)
    (take_image instrument9 GroundStation2 image2)
    (take_image instrument9 GroundStation2 thermograph0)
    (take_image instrument9 GroundStation2 thermograph3)
    (take_image instrument9 GroundStation2 thermograph4)
    (take_image instrument9 GroundStation3 image1)
    (take_image instrument9 GroundStation3 image2)
    (take_image instrument9 GroundStation3 thermograph0)
    (take_image instrument9 GroundStation3 thermograph3)
    (take_image instrument9 GroundStation3 thermograph4)
    (take_image instrument9 GroundStation4 image1)
    (take_image instrument9 GroundStation4 image2)
    (take_image instrument9 GroundStation4 thermograph0)
    (take_image instrument9 GroundStation4 thermograph3)
    (take_image instrument9 GroundStation4 thermograph4)
    (take_image instrument9 Phenomenon11 image1)
    (take_image instrument9 Phenomenon11 image2)
    (take_image instrument9 Phenomenon11 thermograph0)
    (take_image instrument9 Phenomenon11 thermograph3)
    (take_image instrument9 Phenomenon11 thermograph4)
    (take_image instrument9 Phenomenon12 image1)
    (take_image instrument9 Phenomenon12 image2)
    (take_image instrument9 Phenomenon12 thermograph0)
    (take_image instrument9 Phenomenon12 thermograph3)
    (take_image instrument9 Phenomenon12 thermograph4)
    (take_image instrument9 Phenomenon13 image1)
    (take_image instrument9 Phenomenon13 image2)
    (take_image instrument9 Phenomenon13 thermograph0)
    (take_image instrument9 Phenomenon13 thermograph3)
    (take_image instrument9 Phenomenon13 thermograph4)
    (take_image instrument9 Phenomenon18 image1)
    (take_image instrument9 Phenomenon18 image2)
    (take_image instrument9 Phenomenon18 thermograph0)
    (take_image instrument9 Phenomenon18 thermograph3)
    (take_image instrument9 Phenomenon18 thermograph4)
    (take_image instrument9 Phenomenon5 image1)
    (take_image instrument9 Phenomenon5 image2)
    (take_image instrument9 Phenomenon5 thermograph0)
    (take_image instrument9 Phenomenon5 thermograph3)
    (take_image instrument9 Phenomenon5 thermograph4)
    (take_image instrument9 Phenomenon6 image1)
    (take_image instrument9 Phenomenon6 image2)
    (take_image instrument9 Phenomenon6 thermograph0)
    (take_image instrument9 Phenomenon6 thermograph3)
    (take_image instrument9 Phenomenon6 thermograph4)
    (take_image instrument9 Phenomenon7 image1)
    (take_image instrument9 Phenomenon7 image2)
    (take_image instrument9 Phenomenon7 thermograph0)
    (take_image instrument9 Phenomenon7 thermograph3)
    (take_image instrument9 Phenomenon7 thermograph4)
    (take_image instrument9 Planet15 image1)
    (take_image instrument9 Planet15 image2)
    (take_image instrument9 Planet15 thermograph0)
    (take_image instrument9 Planet15 thermograph3)
    (take_image instrument9 Planet15 thermograph4)
    (take_image instrument9 Planet16 image1)
    (take_image instrument9 Planet16 image2)
    (take_image instrument9 Planet16 thermograph0)
    (take_image instrument9 Planet16 thermograph3)
    (take_image instrument9 Planet16 thermograph4)
    (take_image instrument9 Planet17 image1)
    (take_image instrument9 Planet17 image2)
    (take_image instrument9 Planet17 thermograph0)
    (take_image instrument9 Planet17 thermograph3)
    (take_image instrument9 Planet17 thermograph4)
    (take_image instrument9 Planet21 image1)
    (take_image instrument9 Planet21 image2)
    (take_image instrument9 Planet21 thermograph0)
    (take_image instrument9 Planet21 thermograph3)
    (take_image instrument9 Planet21 thermograph4)
    (take_image instrument9 Planet23 image1)
    (take_image instrument9 Planet23 image2)
    (take_image instrument9 Planet23 thermograph0)
    (take_image instrument9 Planet23 thermograph3)
    (take_image instrument9 Planet23 thermograph4)
    (take_image instrument9 Planet8 image1)
    (take_image instrument9 Planet8 image2)
    (take_image instrument9 Planet8 thermograph0)
    (take_image instrument9 Planet8 thermograph3)
    (take_image instrument9 Planet8 thermograph4)
    (take_image instrument9 Star10 image1)
    (take_image instrument9 Star10 image2)
    (take_image instrument9 Star10 thermograph0)
    (take_image instrument9 Star10 thermograph3)
    (take_image instrument9 Star10 thermograph4)
    (take_image instrument9 Star14 image1)
    (take_image instrument9 Star14 image2)
    (take_image instrument9 Star14 thermograph0)
    (take_image instrument9 Star14 thermograph3)
    (take_image instrument9 Star14 thermograph4)
    (take_image instrument9 Star19 image1)
    (take_image instrument9 Star19 image2)
    (take_image instrument9 Star19 thermograph0)
    (take_image instrument9 Star19 thermograph3)
    (take_image instrument9 Star19 thermograph4)
    (take_image instrument9 Star20 image1)
    (take_image instrument9 Star20 image2)
    (take_image instrument9 Star20 thermograph0)
    (take_image instrument9 Star20 thermograph3)
    (take_image instrument9 Star20 thermograph4)
    (take_image instrument9 Star22 image1)
    (take_image instrument9 Star22 image2)
    (take_image instrument9 Star22 thermograph0)
    (take_image instrument9 Star22 thermograph3)
    (take_image instrument9 Star22 thermograph4)
    (take_image instrument9 Star24 image1)
    (take_image instrument9 Star24 image2)
    (take_image instrument9 Star24 thermograph0)
    (take_image instrument9 Star24 thermograph3)
    (take_image instrument9 Star24 thermograph4)
    (take_image instrument9 Star9 image1)
    (take_image instrument9 Star9 image2)
    (take_image instrument9 Star9 thermograph0)
    (take_image instrument9 Star9 thermograph3)
    (take_image instrument9 Star9 thermograph4)
    )
(:goal (and
	(pointing satellite0 Planet21)
	(pointing satellite2 Star14)
	(pointing satellite5 Planet17)
	(have_image Phenomenon5 image1)
	(have_image Phenomenon7 thermograph0)
	(have_image Planet8 image2)
	(have_image Star9 thermograph0)
	(have_image Star10 thermograph3)
	(have_image Phenomenon12 thermograph0)
	(have_image Phenomenon13 image1)
	(have_image Star14 thermograph4)
	(have_image Planet15 image2)
	(have_image Planet17 image2)
	(have_image Phenomenon18 image1)
	(have_image Star19 thermograph4)
	(have_image Star20 thermograph4)
	(have_image Planet21 thermograph0)
	(have_image Star22 thermograph3)
	(have_image Planet23 image1)
))

)
