; Problem taken from https://github.com/AI-Planning/classical-domains

(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0
	instrument0
	instrument1
	instrument2
	satellite1
	instrument3
	instrument4
	satellite2
	instrument5
	satellite3
	instrument6
	satellite4
	instrument7
	instrument8
	instrument9
	thermograph2
	infrared0
	infrared1
	spectrograph4
	infrared3
	Star0
	Star3
	GroundStation1
	Star2
	Star4
	Planet5
	Phenomenon6
	Star7
	Planet8
	Star9
	Planet10
	Planet11
	Star12
	Phenomenon13
	Star14
	Star15
	Planet16
	Phenomenon17
	Star18
	Star19
	Planet20
	Phenomenon21
	Star22
	Star23
	Phenomenon24
)
(:init
	(satellite satellite0)
	(instrument instrument0)
	(supports instrument0 infrared1)
	(supports instrument0 spectrograph4)
	(calibration_target instrument0 Star0)
	(instrument instrument1)
	(supports instrument1 infrared1)
	(supports instrument1 infrared0)
	(calibration_target instrument1 Star2)
	(instrument instrument2)
	(supports instrument2 infrared1)
	(supports instrument2 infrared0)
	(calibration_target instrument2 Star3)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Planet16)
	(satellite satellite1)
	(instrument instrument3)
	(supports instrument3 infrared0)
	(supports instrument3 spectrograph4)
	(calibration_target instrument3 Star4)
	(instrument instrument4)
	(supports instrument4 infrared0)
	(supports instrument4 infrared3)
	(supports instrument4 thermograph2)
	(calibration_target instrument4 Star4)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star4)
	(satellite satellite2)
	(instrument instrument5)
	(supports instrument5 infrared1)
	(calibration_target instrument5 GroundStation1)
	(on_board instrument5 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star15)
	(satellite satellite3)
	(instrument instrument6)
	(supports instrument6 infrared1)
	(calibration_target instrument6 Star4)
	(on_board instrument6 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Phenomenon6)
	(satellite satellite4)
	(instrument instrument7)
	(supports instrument7 infrared1)
	(supports instrument7 infrared3)
	(calibration_target instrument7 Star2)
	(instrument instrument8)
	(supports instrument8 infrared0)
	(supports instrument8 infrared3)
	(supports instrument8 spectrograph4)
	(calibration_target instrument8 Star2)
	(instrument instrument9)
	(supports instrument9 infrared3)
	(supports instrument9 spectrograph4)
	(supports instrument9 infrared1)
	(calibration_target instrument9 Star4)
	(on_board instrument7 satellite4)
	(on_board instrument8 satellite4)
	(on_board instrument9 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star14)
	(mode thermograph2)
	(mode infrared0)
	(mode infrared1)
	(mode spectrograph4)
	(mode infrared3)
	(direction Star0)
	(direction Star3)
	(direction GroundStation1)
	(direction Star2)
	(direction Star4)
	(direction Planet5)
	(direction Phenomenon6)
	(direction Star7)
	(direction Planet8)
	(direction Star9)
	(direction Planet10)
	(direction Planet11)
	(direction Star12)
	(direction Phenomenon13)
	(direction Star14)
	(direction Star15)
	(direction Planet16)
	(direction Phenomenon17)
	(direction Star18)
	(direction Star19)
	(direction Planet20)
	(direction Phenomenon21)
	(direction Star22)
	(direction Star23)
	(direction Phenomenon24)

    ; action literals
    (turn_to satellite0 GroundStation1)
    (turn_to satellite0 Phenomenon13)
    (turn_to satellite0 Phenomenon17)
    (turn_to satellite0 Phenomenon21)
    (turn_to satellite0 Phenomenon24)
    (turn_to satellite0 Phenomenon6)
    (turn_to satellite0 Planet10)
    (turn_to satellite0 Planet11)
    (turn_to satellite0 Planet16)
    (turn_to satellite0 Planet20)
    (turn_to satellite0 Planet5)
    (turn_to satellite0 Planet8)
    (turn_to satellite0 Star0)
    (turn_to satellite0 Star12)
    (turn_to satellite0 Star14)
    (turn_to satellite0 Star15)
    (turn_to satellite0 Star18)
    (turn_to satellite0 Star19)
    (turn_to satellite0 Star2)
    (turn_to satellite0 Star22)
    (turn_to satellite0 Star23)
    (turn_to satellite0 Star3)
    (turn_to satellite0 Star4)
    (turn_to satellite0 Star7)
    (turn_to satellite0 Star9)
    (turn_to satellite1 GroundStation1)
    (turn_to satellite1 Phenomenon13)
    (turn_to satellite1 Phenomenon17)
    (turn_to satellite1 Phenomenon21)
    (turn_to satellite1 Phenomenon24)
    (turn_to satellite1 Phenomenon6)
    (turn_to satellite1 Planet10)
    (turn_to satellite1 Planet11)
    (turn_to satellite1 Planet16)
    (turn_to satellite1 Planet20)
    (turn_to satellite1 Planet5)
    (turn_to satellite1 Planet8)
    (turn_to satellite1 Star0)
    (turn_to satellite1 Star12)
    (turn_to satellite1 Star14)
    (turn_to satellite1 Star15)
    (turn_to satellite1 Star18)
    (turn_to satellite1 Star19)
    (turn_to satellite1 Star2)
    (turn_to satellite1 Star22)
    (turn_to satellite1 Star23)
    (turn_to satellite1 Star3)
    (turn_to satellite1 Star4)
    (turn_to satellite1 Star7)
    (turn_to satellite1 Star9)
    (turn_to satellite2 GroundStation1)
    (turn_to satellite2 Phenomenon13)
    (turn_to satellite2 Phenomenon17)
    (turn_to satellite2 Phenomenon21)
    (turn_to satellite2 Phenomenon24)
    (turn_to satellite2 Phenomenon6)
    (turn_to satellite2 Planet10)
    (turn_to satellite2 Planet11)
    (turn_to satellite2 Planet16)
    (turn_to satellite2 Planet20)
    (turn_to satellite2 Planet5)
    (turn_to satellite2 Planet8)
    (turn_to satellite2 Star0)
    (turn_to satellite2 Star12)
    (turn_to satellite2 Star14)
    (turn_to satellite2 Star15)
    (turn_to satellite2 Star18)
    (turn_to satellite2 Star19)
    (turn_to satellite2 Star2)
    (turn_to satellite2 Star22)
    (turn_to satellite2 Star23)
    (turn_to satellite2 Star3)
    (turn_to satellite2 Star4)
    (turn_to satellite2 Star7)
    (turn_to satellite2 Star9)
    (turn_to satellite3 GroundStation1)
    (turn_to satellite3 Phenomenon13)
    (turn_to satellite3 Phenomenon17)
    (turn_to satellite3 Phenomenon21)
    (turn_to satellite3 Phenomenon24)
    (turn_to satellite3 Phenomenon6)
    (turn_to satellite3 Planet10)
    (turn_to satellite3 Planet11)
    (turn_to satellite3 Planet16)
    (turn_to satellite3 Planet20)
    (turn_to satellite3 Planet5)
    (turn_to satellite3 Planet8)
    (turn_to satellite3 Star0)
    (turn_to satellite3 Star12)
    (turn_to satellite3 Star14)
    (turn_to satellite3 Star15)
    (turn_to satellite3 Star18)
    (turn_to satellite3 Star19)
    (turn_to satellite3 Star2)
    (turn_to satellite3 Star22)
    (turn_to satellite3 Star23)
    (turn_to satellite3 Star3)
    (turn_to satellite3 Star4)
    (turn_to satellite3 Star7)
    (turn_to satellite3 Star9)
    (turn_to satellite4 GroundStation1)
    (turn_to satellite4 Phenomenon13)
    (turn_to satellite4 Phenomenon17)
    (turn_to satellite4 Phenomenon21)
    (turn_to satellite4 Phenomenon24)
    (turn_to satellite4 Phenomenon6)
    (turn_to satellite4 Planet10)
    (turn_to satellite4 Planet11)
    (turn_to satellite4 Planet16)
    (turn_to satellite4 Planet20)
    (turn_to satellite4 Planet5)
    (turn_to satellite4 Planet8)
    (turn_to satellite4 Star0)
    (turn_to satellite4 Star12)
    (turn_to satellite4 Star14)
    (turn_to satellite4 Star15)
    (turn_to satellite4 Star18)
    (turn_to satellite4 Star19)
    (turn_to satellite4 Star2)
    (turn_to satellite4 Star22)
    (turn_to satellite4 Star23)
    (turn_to satellite4 Star3)
    (turn_to satellite4 Star4)
    (turn_to satellite4 Star7)
    (turn_to satellite4 Star9)
    (switch_on instrument0)
    (switch_off instrument0)
    (switch_on instrument1)
    (switch_off instrument1)
    (switch_on instrument2)
    (switch_off instrument2)
    (switch_on instrument3)
    (switch_off instrument3)
    (switch_on instrument4)
    (switch_off instrument4)
    (switch_on instrument5)
    (switch_off instrument5)
    (switch_on instrument6)
    (switch_off instrument6)
    (switch_on instrument7)
    (switch_off instrument7)
    (switch_on instrument8)
    (switch_off instrument8)
    (switch_on instrument9)
    (switch_off instrument9)
    (calibrate instrument0 GroundStation1)
    (calibrate instrument0 Phenomenon13)
    (calibrate instrument0 Phenomenon17)
    (calibrate instrument0 Phenomenon21)
    (calibrate instrument0 Phenomenon24)
    (calibrate instrument0 Phenomenon6)
    (calibrate instrument0 Planet10)
    (calibrate instrument0 Planet11)
    (calibrate instrument0 Planet16)
    (calibrate instrument0 Planet20)
    (calibrate instrument0 Planet5)
    (calibrate instrument0 Planet8)
    (calibrate instrument0 Star0)
    (calibrate instrument0 Star12)
    (calibrate instrument0 Star14)
    (calibrate instrument0 Star15)
    (calibrate instrument0 Star18)
    (calibrate instrument0 Star19)
    (calibrate instrument0 Star2)
    (calibrate instrument0 Star22)
    (calibrate instrument0 Star23)
    (calibrate instrument0 Star3)
    (calibrate instrument0 Star4)
    (calibrate instrument0 Star7)
    (calibrate instrument0 Star9)
    (calibrate instrument1 GroundStation1)
    (calibrate instrument1 Phenomenon13)
    (calibrate instrument1 Phenomenon17)
    (calibrate instrument1 Phenomenon21)
    (calibrate instrument1 Phenomenon24)
    (calibrate instrument1 Phenomenon6)
    (calibrate instrument1 Planet10)
    (calibrate instrument1 Planet11)
    (calibrate instrument1 Planet16)
    (calibrate instrument1 Planet20)
    (calibrate instrument1 Planet5)
    (calibrate instrument1 Planet8)
    (calibrate instrument1 Star0)
    (calibrate instrument1 Star12)
    (calibrate instrument1 Star14)
    (calibrate instrument1 Star15)
    (calibrate instrument1 Star18)
    (calibrate instrument1 Star19)
    (calibrate instrument1 Star2)
    (calibrate instrument1 Star22)
    (calibrate instrument1 Star23)
    (calibrate instrument1 Star3)
    (calibrate instrument1 Star4)
    (calibrate instrument1 Star7)
    (calibrate instrument1 Star9)
    (calibrate instrument2 GroundStation1)
    (calibrate instrument2 Phenomenon13)
    (calibrate instrument2 Phenomenon17)
    (calibrate instrument2 Phenomenon21)
    (calibrate instrument2 Phenomenon24)
    (calibrate instrument2 Phenomenon6)
    (calibrate instrument2 Planet10)
    (calibrate instrument2 Planet11)
    (calibrate instrument2 Planet16)
    (calibrate instrument2 Planet20)
    (calibrate instrument2 Planet5)
    (calibrate instrument2 Planet8)
    (calibrate instrument2 Star0)
    (calibrate instrument2 Star12)
    (calibrate instrument2 Star14)
    (calibrate instrument2 Star15)
    (calibrate instrument2 Star18)
    (calibrate instrument2 Star19)
    (calibrate instrument2 Star2)
    (calibrate instrument2 Star22)
    (calibrate instrument2 Star23)
    (calibrate instrument2 Star3)
    (calibrate instrument2 Star4)
    (calibrate instrument2 Star7)
    (calibrate instrument2 Star9)
    (calibrate instrument3 GroundStation1)
    (calibrate instrument3 Phenomenon13)
    (calibrate instrument3 Phenomenon17)
    (calibrate instrument3 Phenomenon21)
    (calibrate instrument3 Phenomenon24)
    (calibrate instrument3 Phenomenon6)
    (calibrate instrument3 Planet10)
    (calibrate instrument3 Planet11)
    (calibrate instrument3 Planet16)
    (calibrate instrument3 Planet20)
    (calibrate instrument3 Planet5)
    (calibrate instrument3 Planet8)
    (calibrate instrument3 Star0)
    (calibrate instrument3 Star12)
    (calibrate instrument3 Star14)
    (calibrate instrument3 Star15)
    (calibrate instrument3 Star18)
    (calibrate instrument3 Star19)
    (calibrate instrument3 Star2)
    (calibrate instrument3 Star22)
    (calibrate instrument3 Star23)
    (calibrate instrument3 Star3)
    (calibrate instrument3 Star4)
    (calibrate instrument3 Star7)
    (calibrate instrument3 Star9)
    (calibrate instrument4 GroundStation1)
    (calibrate instrument4 Phenomenon13)
    (calibrate instrument4 Phenomenon17)
    (calibrate instrument4 Phenomenon21)
    (calibrate instrument4 Phenomenon24)
    (calibrate instrument4 Phenomenon6)
    (calibrate instrument4 Planet10)
    (calibrate instrument4 Planet11)
    (calibrate instrument4 Planet16)
    (calibrate instrument4 Planet20)
    (calibrate instrument4 Planet5)
    (calibrate instrument4 Planet8)
    (calibrate instrument4 Star0)
    (calibrate instrument4 Star12)
    (calibrate instrument4 Star14)
    (calibrate instrument4 Star15)
    (calibrate instrument4 Star18)
    (calibrate instrument4 Star19)
    (calibrate instrument4 Star2)
    (calibrate instrument4 Star22)
    (calibrate instrument4 Star23)
    (calibrate instrument4 Star3)
    (calibrate instrument4 Star4)
    (calibrate instrument4 Star7)
    (calibrate instrument4 Star9)
    (calibrate instrument5 GroundStation1)
    (calibrate instrument5 Phenomenon13)
    (calibrate instrument5 Phenomenon17)
    (calibrate instrument5 Phenomenon21)
    (calibrate instrument5 Phenomenon24)
    (calibrate instrument5 Phenomenon6)
    (calibrate instrument5 Planet10)
    (calibrate instrument5 Planet11)
    (calibrate instrument5 Planet16)
    (calibrate instrument5 Planet20)
    (calibrate instrument5 Planet5)
    (calibrate instrument5 Planet8)
    (calibrate instrument5 Star0)
    (calibrate instrument5 Star12)
    (calibrate instrument5 Star14)
    (calibrate instrument5 Star15)
    (calibrate instrument5 Star18)
    (calibrate instrument5 Star19)
    (calibrate instrument5 Star2)
    (calibrate instrument5 Star22)
    (calibrate instrument5 Star23)
    (calibrate instrument5 Star3)
    (calibrate instrument5 Star4)
    (calibrate instrument5 Star7)
    (calibrate instrument5 Star9)
    (calibrate instrument6 GroundStation1)
    (calibrate instrument6 Phenomenon13)
    (calibrate instrument6 Phenomenon17)
    (calibrate instrument6 Phenomenon21)
    (calibrate instrument6 Phenomenon24)
    (calibrate instrument6 Phenomenon6)
    (calibrate instrument6 Planet10)
    (calibrate instrument6 Planet11)
    (calibrate instrument6 Planet16)
    (calibrate instrument6 Planet20)
    (calibrate instrument6 Planet5)
    (calibrate instrument6 Planet8)
    (calibrate instrument6 Star0)
    (calibrate instrument6 Star12)
    (calibrate instrument6 Star14)
    (calibrate instrument6 Star15)
    (calibrate instrument6 Star18)
    (calibrate instrument6 Star19)
    (calibrate instrument6 Star2)
    (calibrate instrument6 Star22)
    (calibrate instrument6 Star23)
    (calibrate instrument6 Star3)
    (calibrate instrument6 Star4)
    (calibrate instrument6 Star7)
    (calibrate instrument6 Star9)
    (calibrate instrument7 GroundStation1)
    (calibrate instrument7 Phenomenon13)
    (calibrate instrument7 Phenomenon17)
    (calibrate instrument7 Phenomenon21)
    (calibrate instrument7 Phenomenon24)
    (calibrate instrument7 Phenomenon6)
    (calibrate instrument7 Planet10)
    (calibrate instrument7 Planet11)
    (calibrate instrument7 Planet16)
    (calibrate instrument7 Planet20)
    (calibrate instrument7 Planet5)
    (calibrate instrument7 Planet8)
    (calibrate instrument7 Star0)
    (calibrate instrument7 Star12)
    (calibrate instrument7 Star14)
    (calibrate instrument7 Star15)
    (calibrate instrument7 Star18)
    (calibrate instrument7 Star19)
    (calibrate instrument7 Star2)
    (calibrate instrument7 Star22)
    (calibrate instrument7 Star23)
    (calibrate instrument7 Star3)
    (calibrate instrument7 Star4)
    (calibrate instrument7 Star7)
    (calibrate instrument7 Star9)
    (calibrate instrument8 GroundStation1)
    (calibrate instrument8 Phenomenon13)
    (calibrate instrument8 Phenomenon17)
    (calibrate instrument8 Phenomenon21)
    (calibrate instrument8 Phenomenon24)
    (calibrate instrument8 Phenomenon6)
    (calibrate instrument8 Planet10)
    (calibrate instrument8 Planet11)
    (calibrate instrument8 Planet16)
    (calibrate instrument8 Planet20)
    (calibrate instrument8 Planet5)
    (calibrate instrument8 Planet8)
    (calibrate instrument8 Star0)
    (calibrate instrument8 Star12)
    (calibrate instrument8 Star14)
    (calibrate instrument8 Star15)
    (calibrate instrument8 Star18)
    (calibrate instrument8 Star19)
    (calibrate instrument8 Star2)
    (calibrate instrument8 Star22)
    (calibrate instrument8 Star23)
    (calibrate instrument8 Star3)
    (calibrate instrument8 Star4)
    (calibrate instrument8 Star7)
    (calibrate instrument8 Star9)
    (calibrate instrument9 GroundStation1)
    (calibrate instrument9 Phenomenon13)
    (calibrate instrument9 Phenomenon17)
    (calibrate instrument9 Phenomenon21)
    (calibrate instrument9 Phenomenon24)
    (calibrate instrument9 Phenomenon6)
    (calibrate instrument9 Planet10)
    (calibrate instrument9 Planet11)
    (calibrate instrument9 Planet16)
    (calibrate instrument9 Planet20)
    (calibrate instrument9 Planet5)
    (calibrate instrument9 Planet8)
    (calibrate instrument9 Star0)
    (calibrate instrument9 Star12)
    (calibrate instrument9 Star14)
    (calibrate instrument9 Star15)
    (calibrate instrument9 Star18)
    (calibrate instrument9 Star19)
    (calibrate instrument9 Star2)
    (calibrate instrument9 Star22)
    (calibrate instrument9 Star23)
    (calibrate instrument9 Star3)
    (calibrate instrument9 Star4)
    (calibrate instrument9 Star7)
    (calibrate instrument9 Star9)
    (take_image instrument0 GroundStation1 infrared0)
    (take_image instrument0 GroundStation1 infrared1)
    (take_image instrument0 GroundStation1 infrared3)
    (take_image instrument0 GroundStation1 spectrograph4)
    (take_image instrument0 GroundStation1 thermograph2)
    (take_image instrument0 Phenomenon13 infrared0)
    (take_image instrument0 Phenomenon13 infrared1)
    (take_image instrument0 Phenomenon13 infrared3)
    (take_image instrument0 Phenomenon13 spectrograph4)
    (take_image instrument0 Phenomenon13 thermograph2)
    (take_image instrument0 Phenomenon17 infrared0)
    (take_image instrument0 Phenomenon17 infrared1)
    (take_image instrument0 Phenomenon17 infrared3)
    (take_image instrument0 Phenomenon17 spectrograph4)
    (take_image instrument0 Phenomenon17 thermograph2)
    (take_image instrument0 Phenomenon21 infrared0)
    (take_image instrument0 Phenomenon21 infrared1)
    (take_image instrument0 Phenomenon21 infrared3)
    (take_image instrument0 Phenomenon21 spectrograph4)
    (take_image instrument0 Phenomenon21 thermograph2)
    (take_image instrument0 Phenomenon24 infrared0)
    (take_image instrument0 Phenomenon24 infrared1)
    (take_image instrument0 Phenomenon24 infrared3)
    (take_image instrument0 Phenomenon24 spectrograph4)
    (take_image instrument0 Phenomenon24 thermograph2)
    (take_image instrument0 Phenomenon6 infrared0)
    (take_image instrument0 Phenomenon6 infrared1)
    (take_image instrument0 Phenomenon6 infrared3)
    (take_image instrument0 Phenomenon6 spectrograph4)
    (take_image instrument0 Phenomenon6 thermograph2)
    (take_image instrument0 Planet10 infrared0)
    (take_image instrument0 Planet10 infrared1)
    (take_image instrument0 Planet10 infrared3)
    (take_image instrument0 Planet10 spectrograph4)
    (take_image instrument0 Planet10 thermograph2)
    (take_image instrument0 Planet11 infrared0)
    (take_image instrument0 Planet11 infrared1)
    (take_image instrument0 Planet11 infrared3)
    (take_image instrument0 Planet11 spectrograph4)
    (take_image instrument0 Planet11 thermograph2)
    (take_image instrument0 Planet16 infrared0)
    (take_image instrument0 Planet16 infrared1)
    (take_image instrument0 Planet16 infrared3)
    (take_image instrument0 Planet16 spectrograph4)
    (take_image instrument0 Planet16 thermograph2)
    (take_image instrument0 Planet20 infrared0)
    (take_image instrument0 Planet20 infrared1)
    (take_image instrument0 Planet20 infrared3)
    (take_image instrument0 Planet20 spectrograph4)
    (take_image instrument0 Planet20 thermograph2)
    (take_image instrument0 Planet5 infrared0)
    (take_image instrument0 Planet5 infrared1)
    (take_image instrument0 Planet5 infrared3)
    (take_image instrument0 Planet5 spectrograph4)
    (take_image instrument0 Planet5 thermograph2)
    (take_image instrument0 Planet8 infrared0)
    (take_image instrument0 Planet8 infrared1)
    (take_image instrument0 Planet8 infrared3)
    (take_image instrument0 Planet8 spectrograph4)
    (take_image instrument0 Planet8 thermograph2)
    (take_image instrument0 Star0 infrared0)
    (take_image instrument0 Star0 infrared1)
    (take_image instrument0 Star0 infrared3)
    (take_image instrument0 Star0 spectrograph4)
    (take_image instrument0 Star0 thermograph2)
    (take_image instrument0 Star12 infrared0)
    (take_image instrument0 Star12 infrared1)
    (take_image instrument0 Star12 infrared3)
    (take_image instrument0 Star12 spectrograph4)
    (take_image instrument0 Star12 thermograph2)
    (take_image instrument0 Star14 infrared0)
    (take_image instrument0 Star14 infrared1)
    (take_image instrument0 Star14 infrared3)
    (take_image instrument0 Star14 spectrograph4)
    (take_image instrument0 Star14 thermograph2)
    (take_image instrument0 Star15 infrared0)
    (take_image instrument0 Star15 infrared1)
    (take_image instrument0 Star15 infrared3)
    (take_image instrument0 Star15 spectrograph4)
    (take_image instrument0 Star15 thermograph2)
    (take_image instrument0 Star18 infrared0)
    (take_image instrument0 Star18 infrared1)
    (take_image instrument0 Star18 infrared3)
    (take_image instrument0 Star18 spectrograph4)
    (take_image instrument0 Star18 thermograph2)
    (take_image instrument0 Star19 infrared0)
    (take_image instrument0 Star19 infrared1)
    (take_image instrument0 Star19 infrared3)
    (take_image instrument0 Star19 spectrograph4)
    (take_image instrument0 Star19 thermograph2)
    (take_image instrument0 Star2 infrared0)
    (take_image instrument0 Star2 infrared1)
    (take_image instrument0 Star2 infrared3)
    (take_image instrument0 Star2 spectrograph4)
    (take_image instrument0 Star2 thermograph2)
    (take_image instrument0 Star22 infrared0)
    (take_image instrument0 Star22 infrared1)
    (take_image instrument0 Star22 infrared3)
    (take_image instrument0 Star22 spectrograph4)
    (take_image instrument0 Star22 thermograph2)
    (take_image instrument0 Star23 infrared0)
    (take_image instrument0 Star23 infrared1)
    (take_image instrument0 Star23 infrared3)
    (take_image instrument0 Star23 spectrograph4)
    (take_image instrument0 Star23 thermograph2)
    (take_image instrument0 Star3 infrared0)
    (take_image instrument0 Star3 infrared1)
    (take_image instrument0 Star3 infrared3)
    (take_image instrument0 Star3 spectrograph4)
    (take_image instrument0 Star3 thermograph2)
    (take_image instrument0 Star4 infrared0)
    (take_image instrument0 Star4 infrared1)
    (take_image instrument0 Star4 infrared3)
    (take_image instrument0 Star4 spectrograph4)
    (take_image instrument0 Star4 thermograph2)
    (take_image instrument0 Star7 infrared0)
    (take_image instrument0 Star7 infrared1)
    (take_image instrument0 Star7 infrared3)
    (take_image instrument0 Star7 spectrograph4)
    (take_image instrument0 Star7 thermograph2)
    (take_image instrument0 Star9 infrared0)
    (take_image instrument0 Star9 infrared1)
    (take_image instrument0 Star9 infrared3)
    (take_image instrument0 Star9 spectrograph4)
    (take_image instrument0 Star9 thermograph2)
    (take_image instrument1 GroundStation1 infrared0)
    (take_image instrument1 GroundStation1 infrared1)
    (take_image instrument1 GroundStation1 infrared3)
    (take_image instrument1 GroundStation1 spectrograph4)
    (take_image instrument1 GroundStation1 thermograph2)
    (take_image instrument1 Phenomenon13 infrared0)
    (take_image instrument1 Phenomenon13 infrared1)
    (take_image instrument1 Phenomenon13 infrared3)
    (take_image instrument1 Phenomenon13 spectrograph4)
    (take_image instrument1 Phenomenon13 thermograph2)
    (take_image instrument1 Phenomenon17 infrared0)
    (take_image instrument1 Phenomenon17 infrared1)
    (take_image instrument1 Phenomenon17 infrared3)
    (take_image instrument1 Phenomenon17 spectrograph4)
    (take_image instrument1 Phenomenon17 thermograph2)
    (take_image instrument1 Phenomenon21 infrared0)
    (take_image instrument1 Phenomenon21 infrared1)
    (take_image instrument1 Phenomenon21 infrared3)
    (take_image instrument1 Phenomenon21 spectrograph4)
    (take_image instrument1 Phenomenon21 thermograph2)
    (take_image instrument1 Phenomenon24 infrared0)
    (take_image instrument1 Phenomenon24 infrared1)
    (take_image instrument1 Phenomenon24 infrared3)
    (take_image instrument1 Phenomenon24 spectrograph4)
    (take_image instrument1 Phenomenon24 thermograph2)
    (take_image instrument1 Phenomenon6 infrared0)
    (take_image instrument1 Phenomenon6 infrared1)
    (take_image instrument1 Phenomenon6 infrared3)
    (take_image instrument1 Phenomenon6 spectrograph4)
    (take_image instrument1 Phenomenon6 thermograph2)
    (take_image instrument1 Planet10 infrared0)
    (take_image instrument1 Planet10 infrared1)
    (take_image instrument1 Planet10 infrared3)
    (take_image instrument1 Planet10 spectrograph4)
    (take_image instrument1 Planet10 thermograph2)
    (take_image instrument1 Planet11 infrared0)
    (take_image instrument1 Planet11 infrared1)
    (take_image instrument1 Planet11 infrared3)
    (take_image instrument1 Planet11 spectrograph4)
    (take_image instrument1 Planet11 thermograph2)
    (take_image instrument1 Planet16 infrared0)
    (take_image instrument1 Planet16 infrared1)
    (take_image instrument1 Planet16 infrared3)
    (take_image instrument1 Planet16 spectrograph4)
    (take_image instrument1 Planet16 thermograph2)
    (take_image instrument1 Planet20 infrared0)
    (take_image instrument1 Planet20 infrared1)
    (take_image instrument1 Planet20 infrared3)
    (take_image instrument1 Planet20 spectrograph4)
    (take_image instrument1 Planet20 thermograph2)
    (take_image instrument1 Planet5 infrared0)
    (take_image instrument1 Planet5 infrared1)
    (take_image instrument1 Planet5 infrared3)
    (take_image instrument1 Planet5 spectrograph4)
    (take_image instrument1 Planet5 thermograph2)
    (take_image instrument1 Planet8 infrared0)
    (take_image instrument1 Planet8 infrared1)
    (take_image instrument1 Planet8 infrared3)
    (take_image instrument1 Planet8 spectrograph4)
    (take_image instrument1 Planet8 thermograph2)
    (take_image instrument1 Star0 infrared0)
    (take_image instrument1 Star0 infrared1)
    (take_image instrument1 Star0 infrared3)
    (take_image instrument1 Star0 spectrograph4)
    (take_image instrument1 Star0 thermograph2)
    (take_image instrument1 Star12 infrared0)
    (take_image instrument1 Star12 infrared1)
    (take_image instrument1 Star12 infrared3)
    (take_image instrument1 Star12 spectrograph4)
    (take_image instrument1 Star12 thermograph2)
    (take_image instrument1 Star14 infrared0)
    (take_image instrument1 Star14 infrared1)
    (take_image instrument1 Star14 infrared3)
    (take_image instrument1 Star14 spectrograph4)
    (take_image instrument1 Star14 thermograph2)
    (take_image instrument1 Star15 infrared0)
    (take_image instrument1 Star15 infrared1)
    (take_image instrument1 Star15 infrared3)
    (take_image instrument1 Star15 spectrograph4)
    (take_image instrument1 Star15 thermograph2)
    (take_image instrument1 Star18 infrared0)
    (take_image instrument1 Star18 infrared1)
    (take_image instrument1 Star18 infrared3)
    (take_image instrument1 Star18 spectrograph4)
    (take_image instrument1 Star18 thermograph2)
    (take_image instrument1 Star19 infrared0)
    (take_image instrument1 Star19 infrared1)
    (take_image instrument1 Star19 infrared3)
    (take_image instrument1 Star19 spectrograph4)
    (take_image instrument1 Star19 thermograph2)
    (take_image instrument1 Star2 infrared0)
    (take_image instrument1 Star2 infrared1)
    (take_image instrument1 Star2 infrared3)
    (take_image instrument1 Star2 spectrograph4)
    (take_image instrument1 Star2 thermograph2)
    (take_image instrument1 Star22 infrared0)
    (take_image instrument1 Star22 infrared1)
    (take_image instrument1 Star22 infrared3)
    (take_image instrument1 Star22 spectrograph4)
    (take_image instrument1 Star22 thermograph2)
    (take_image instrument1 Star23 infrared0)
    (take_image instrument1 Star23 infrared1)
    (take_image instrument1 Star23 infrared3)
    (take_image instrument1 Star23 spectrograph4)
    (take_image instrument1 Star23 thermograph2)
    (take_image instrument1 Star3 infrared0)
    (take_image instrument1 Star3 infrared1)
    (take_image instrument1 Star3 infrared3)
    (take_image instrument1 Star3 spectrograph4)
    (take_image instrument1 Star3 thermograph2)
    (take_image instrument1 Star4 infrared0)
    (take_image instrument1 Star4 infrared1)
    (take_image instrument1 Star4 infrared3)
    (take_image instrument1 Star4 spectrograph4)
    (take_image instrument1 Star4 thermograph2)
    (take_image instrument1 Star7 infrared0)
    (take_image instrument1 Star7 infrared1)
    (take_image instrument1 Star7 infrared3)
    (take_image instrument1 Star7 spectrograph4)
    (take_image instrument1 Star7 thermograph2)
    (take_image instrument1 Star9 infrared0)
    (take_image instrument1 Star9 infrared1)
    (take_image instrument1 Star9 infrared3)
    (take_image instrument1 Star9 spectrograph4)
    (take_image instrument1 Star9 thermograph2)
    (take_image instrument2 GroundStation1 infrared0)
    (take_image instrument2 GroundStation1 infrared1)
    (take_image instrument2 GroundStation1 infrared3)
    (take_image instrument2 GroundStation1 spectrograph4)
    (take_image instrument2 GroundStation1 thermograph2)
    (take_image instrument2 Phenomenon13 infrared0)
    (take_image instrument2 Phenomenon13 infrared1)
    (take_image instrument2 Phenomenon13 infrared3)
    (take_image instrument2 Phenomenon13 spectrograph4)
    (take_image instrument2 Phenomenon13 thermograph2)
    (take_image instrument2 Phenomenon17 infrared0)
    (take_image instrument2 Phenomenon17 infrared1)
    (take_image instrument2 Phenomenon17 infrared3)
    (take_image instrument2 Phenomenon17 spectrograph4)
    (take_image instrument2 Phenomenon17 thermograph2)
    (take_image instrument2 Phenomenon21 infrared0)
    (take_image instrument2 Phenomenon21 infrared1)
    (take_image instrument2 Phenomenon21 infrared3)
    (take_image instrument2 Phenomenon21 spectrograph4)
    (take_image instrument2 Phenomenon21 thermograph2)
    (take_image instrument2 Phenomenon24 infrared0)
    (take_image instrument2 Phenomenon24 infrared1)
    (take_image instrument2 Phenomenon24 infrared3)
    (take_image instrument2 Phenomenon24 spectrograph4)
    (take_image instrument2 Phenomenon24 thermograph2)
    (take_image instrument2 Phenomenon6 infrared0)
    (take_image instrument2 Phenomenon6 infrared1)
    (take_image instrument2 Phenomenon6 infrared3)
    (take_image instrument2 Phenomenon6 spectrograph4)
    (take_image instrument2 Phenomenon6 thermograph2)
    (take_image instrument2 Planet10 infrared0)
    (take_image instrument2 Planet10 infrared1)
    (take_image instrument2 Planet10 infrared3)
    (take_image instrument2 Planet10 spectrograph4)
    (take_image instrument2 Planet10 thermograph2)
    (take_image instrument2 Planet11 infrared0)
    (take_image instrument2 Planet11 infrared1)
    (take_image instrument2 Planet11 infrared3)
    (take_image instrument2 Planet11 spectrograph4)
    (take_image instrument2 Planet11 thermograph2)
    (take_image instrument2 Planet16 infrared0)
    (take_image instrument2 Planet16 infrared1)
    (take_image instrument2 Planet16 infrared3)
    (take_image instrument2 Planet16 spectrograph4)
    (take_image instrument2 Planet16 thermograph2)
    (take_image instrument2 Planet20 infrared0)
    (take_image instrument2 Planet20 infrared1)
    (take_image instrument2 Planet20 infrared3)
    (take_image instrument2 Planet20 spectrograph4)
    (take_image instrument2 Planet20 thermograph2)
    (take_image instrument2 Planet5 infrared0)
    (take_image instrument2 Planet5 infrared1)
    (take_image instrument2 Planet5 infrared3)
    (take_image instrument2 Planet5 spectrograph4)
    (take_image instrument2 Planet5 thermograph2)
    (take_image instrument2 Planet8 infrared0)
    (take_image instrument2 Planet8 infrared1)
    (take_image instrument2 Planet8 infrared3)
    (take_image instrument2 Planet8 spectrograph4)
    (take_image instrument2 Planet8 thermograph2)
    (take_image instrument2 Star0 infrared0)
    (take_image instrument2 Star0 infrared1)
    (take_image instrument2 Star0 infrared3)
    (take_image instrument2 Star0 spectrograph4)
    (take_image instrument2 Star0 thermograph2)
    (take_image instrument2 Star12 infrared0)
    (take_image instrument2 Star12 infrared1)
    (take_image instrument2 Star12 infrared3)
    (take_image instrument2 Star12 spectrograph4)
    (take_image instrument2 Star12 thermograph2)
    (take_image instrument2 Star14 infrared0)
    (take_image instrument2 Star14 infrared1)
    (take_image instrument2 Star14 infrared3)
    (take_image instrument2 Star14 spectrograph4)
    (take_image instrument2 Star14 thermograph2)
    (take_image instrument2 Star15 infrared0)
    (take_image instrument2 Star15 infrared1)
    (take_image instrument2 Star15 infrared3)
    (take_image instrument2 Star15 spectrograph4)
    (take_image instrument2 Star15 thermograph2)
    (take_image instrument2 Star18 infrared0)
    (take_image instrument2 Star18 infrared1)
    (take_image instrument2 Star18 infrared3)
    (take_image instrument2 Star18 spectrograph4)
    (take_image instrument2 Star18 thermograph2)
    (take_image instrument2 Star19 infrared0)
    (take_image instrument2 Star19 infrared1)
    (take_image instrument2 Star19 infrared3)
    (take_image instrument2 Star19 spectrograph4)
    (take_image instrument2 Star19 thermograph2)
    (take_image instrument2 Star2 infrared0)
    (take_image instrument2 Star2 infrared1)
    (take_image instrument2 Star2 infrared3)
    (take_image instrument2 Star2 spectrograph4)
    (take_image instrument2 Star2 thermograph2)
    (take_image instrument2 Star22 infrared0)
    (take_image instrument2 Star22 infrared1)
    (take_image instrument2 Star22 infrared3)
    (take_image instrument2 Star22 spectrograph4)
    (take_image instrument2 Star22 thermograph2)
    (take_image instrument2 Star23 infrared0)
    (take_image instrument2 Star23 infrared1)
    (take_image instrument2 Star23 infrared3)
    (take_image instrument2 Star23 spectrograph4)
    (take_image instrument2 Star23 thermograph2)
    (take_image instrument2 Star3 infrared0)
    (take_image instrument2 Star3 infrared1)
    (take_image instrument2 Star3 infrared3)
    (take_image instrument2 Star3 spectrograph4)
    (take_image instrument2 Star3 thermograph2)
    (take_image instrument2 Star4 infrared0)
    (take_image instrument2 Star4 infrared1)
    (take_image instrument2 Star4 infrared3)
    (take_image instrument2 Star4 spectrograph4)
    (take_image instrument2 Star4 thermograph2)
    (take_image instrument2 Star7 infrared0)
    (take_image instrument2 Star7 infrared1)
    (take_image instrument2 Star7 infrared3)
    (take_image instrument2 Star7 spectrograph4)
    (take_image instrument2 Star7 thermograph2)
    (take_image instrument2 Star9 infrared0)
    (take_image instrument2 Star9 infrared1)
    (take_image instrument2 Star9 infrared3)
    (take_image instrument2 Star9 spectrograph4)
    (take_image instrument2 Star9 thermograph2)
    (take_image instrument3 GroundStation1 infrared0)
    (take_image instrument3 GroundStation1 infrared1)
    (take_image instrument3 GroundStation1 infrared3)
    (take_image instrument3 GroundStation1 spectrograph4)
    (take_image instrument3 GroundStation1 thermograph2)
    (take_image instrument3 Phenomenon13 infrared0)
    (take_image instrument3 Phenomenon13 infrared1)
    (take_image instrument3 Phenomenon13 infrared3)
    (take_image instrument3 Phenomenon13 spectrograph4)
    (take_image instrument3 Phenomenon13 thermograph2)
    (take_image instrument3 Phenomenon17 infrared0)
    (take_image instrument3 Phenomenon17 infrared1)
    (take_image instrument3 Phenomenon17 infrared3)
    (take_image instrument3 Phenomenon17 spectrograph4)
    (take_image instrument3 Phenomenon17 thermograph2)
    (take_image instrument3 Phenomenon21 infrared0)
    (take_image instrument3 Phenomenon21 infrared1)
    (take_image instrument3 Phenomenon21 infrared3)
    (take_image instrument3 Phenomenon21 spectrograph4)
    (take_image instrument3 Phenomenon21 thermograph2)
    (take_image instrument3 Phenomenon24 infrared0)
    (take_image instrument3 Phenomenon24 infrared1)
    (take_image instrument3 Phenomenon24 infrared3)
    (take_image instrument3 Phenomenon24 spectrograph4)
    (take_image instrument3 Phenomenon24 thermograph2)
    (take_image instrument3 Phenomenon6 infrared0)
    (take_image instrument3 Phenomenon6 infrared1)
    (take_image instrument3 Phenomenon6 infrared3)
    (take_image instrument3 Phenomenon6 spectrograph4)
    (take_image instrument3 Phenomenon6 thermograph2)
    (take_image instrument3 Planet10 infrared0)
    (take_image instrument3 Planet10 infrared1)
    (take_image instrument3 Planet10 infrared3)
    (take_image instrument3 Planet10 spectrograph4)
    (take_image instrument3 Planet10 thermograph2)
    (take_image instrument3 Planet11 infrared0)
    (take_image instrument3 Planet11 infrared1)
    (take_image instrument3 Planet11 infrared3)
    (take_image instrument3 Planet11 spectrograph4)
    (take_image instrument3 Planet11 thermograph2)
    (take_image instrument3 Planet16 infrared0)
    (take_image instrument3 Planet16 infrared1)
    (take_image instrument3 Planet16 infrared3)
    (take_image instrument3 Planet16 spectrograph4)
    (take_image instrument3 Planet16 thermograph2)
    (take_image instrument3 Planet20 infrared0)
    (take_image instrument3 Planet20 infrared1)
    (take_image instrument3 Planet20 infrared3)
    (take_image instrument3 Planet20 spectrograph4)
    (take_image instrument3 Planet20 thermograph2)
    (take_image instrument3 Planet5 infrared0)
    (take_image instrument3 Planet5 infrared1)
    (take_image instrument3 Planet5 infrared3)
    (take_image instrument3 Planet5 spectrograph4)
    (take_image instrument3 Planet5 thermograph2)
    (take_image instrument3 Planet8 infrared0)
    (take_image instrument3 Planet8 infrared1)
    (take_image instrument3 Planet8 infrared3)
    (take_image instrument3 Planet8 spectrograph4)
    (take_image instrument3 Planet8 thermograph2)
    (take_image instrument3 Star0 infrared0)
    (take_image instrument3 Star0 infrared1)
    (take_image instrument3 Star0 infrared3)
    (take_image instrument3 Star0 spectrograph4)
    (take_image instrument3 Star0 thermograph2)
    (take_image instrument3 Star12 infrared0)
    (take_image instrument3 Star12 infrared1)
    (take_image instrument3 Star12 infrared3)
    (take_image instrument3 Star12 spectrograph4)
    (take_image instrument3 Star12 thermograph2)
    (take_image instrument3 Star14 infrared0)
    (take_image instrument3 Star14 infrared1)
    (take_image instrument3 Star14 infrared3)
    (take_image instrument3 Star14 spectrograph4)
    (take_image instrument3 Star14 thermograph2)
    (take_image instrument3 Star15 infrared0)
    (take_image instrument3 Star15 infrared1)
    (take_image instrument3 Star15 infrared3)
    (take_image instrument3 Star15 spectrograph4)
    (take_image instrument3 Star15 thermograph2)
    (take_image instrument3 Star18 infrared0)
    (take_image instrument3 Star18 infrared1)
    (take_image instrument3 Star18 infrared3)
    (take_image instrument3 Star18 spectrograph4)
    (take_image instrument3 Star18 thermograph2)
    (take_image instrument3 Star19 infrared0)
    (take_image instrument3 Star19 infrared1)
    (take_image instrument3 Star19 infrared3)
    (take_image instrument3 Star19 spectrograph4)
    (take_image instrument3 Star19 thermograph2)
    (take_image instrument3 Star2 infrared0)
    (take_image instrument3 Star2 infrared1)
    (take_image instrument3 Star2 infrared3)
    (take_image instrument3 Star2 spectrograph4)
    (take_image instrument3 Star2 thermograph2)
    (take_image instrument3 Star22 infrared0)
    (take_image instrument3 Star22 infrared1)
    (take_image instrument3 Star22 infrared3)
    (take_image instrument3 Star22 spectrograph4)
    (take_image instrument3 Star22 thermograph2)
    (take_image instrument3 Star23 infrared0)
    (take_image instrument3 Star23 infrared1)
    (take_image instrument3 Star23 infrared3)
    (take_image instrument3 Star23 spectrograph4)
    (take_image instrument3 Star23 thermograph2)
    (take_image instrument3 Star3 infrared0)
    (take_image instrument3 Star3 infrared1)
    (take_image instrument3 Star3 infrared3)
    (take_image instrument3 Star3 spectrograph4)
    (take_image instrument3 Star3 thermograph2)
    (take_image instrument3 Star4 infrared0)
    (take_image instrument3 Star4 infrared1)
    (take_image instrument3 Star4 infrared3)
    (take_image instrument3 Star4 spectrograph4)
    (take_image instrument3 Star4 thermograph2)
    (take_image instrument3 Star7 infrared0)
    (take_image instrument3 Star7 infrared1)
    (take_image instrument3 Star7 infrared3)
    (take_image instrument3 Star7 spectrograph4)
    (take_image instrument3 Star7 thermograph2)
    (take_image instrument3 Star9 infrared0)
    (take_image instrument3 Star9 infrared1)
    (take_image instrument3 Star9 infrared3)
    (take_image instrument3 Star9 spectrograph4)
    (take_image instrument3 Star9 thermograph2)
    (take_image instrument4 GroundStation1 infrared0)
    (take_image instrument4 GroundStation1 infrared1)
    (take_image instrument4 GroundStation1 infrared3)
    (take_image instrument4 GroundStation1 spectrograph4)
    (take_image instrument4 GroundStation1 thermograph2)
    (take_image instrument4 Phenomenon13 infrared0)
    (take_image instrument4 Phenomenon13 infrared1)
    (take_image instrument4 Phenomenon13 infrared3)
    (take_image instrument4 Phenomenon13 spectrograph4)
    (take_image instrument4 Phenomenon13 thermograph2)
    (take_image instrument4 Phenomenon17 infrared0)
    (take_image instrument4 Phenomenon17 infrared1)
    (take_image instrument4 Phenomenon17 infrared3)
    (take_image instrument4 Phenomenon17 spectrograph4)
    (take_image instrument4 Phenomenon17 thermograph2)
    (take_image instrument4 Phenomenon21 infrared0)
    (take_image instrument4 Phenomenon21 infrared1)
    (take_image instrument4 Phenomenon21 infrared3)
    (take_image instrument4 Phenomenon21 spectrograph4)
    (take_image instrument4 Phenomenon21 thermograph2)
    (take_image instrument4 Phenomenon24 infrared0)
    (take_image instrument4 Phenomenon24 infrared1)
    (take_image instrument4 Phenomenon24 infrared3)
    (take_image instrument4 Phenomenon24 spectrograph4)
    (take_image instrument4 Phenomenon24 thermograph2)
    (take_image instrument4 Phenomenon6 infrared0)
    (take_image instrument4 Phenomenon6 infrared1)
    (take_image instrument4 Phenomenon6 infrared3)
    (take_image instrument4 Phenomenon6 spectrograph4)
    (take_image instrument4 Phenomenon6 thermograph2)
    (take_image instrument4 Planet10 infrared0)
    (take_image instrument4 Planet10 infrared1)
    (take_image instrument4 Planet10 infrared3)
    (take_image instrument4 Planet10 spectrograph4)
    (take_image instrument4 Planet10 thermograph2)
    (take_image instrument4 Planet11 infrared0)
    (take_image instrument4 Planet11 infrared1)
    (take_image instrument4 Planet11 infrared3)
    (take_image instrument4 Planet11 spectrograph4)
    (take_image instrument4 Planet11 thermograph2)
    (take_image instrument4 Planet16 infrared0)
    (take_image instrument4 Planet16 infrared1)
    (take_image instrument4 Planet16 infrared3)
    (take_image instrument4 Planet16 spectrograph4)
    (take_image instrument4 Planet16 thermograph2)
    (take_image instrument4 Planet20 infrared0)
    (take_image instrument4 Planet20 infrared1)
    (take_image instrument4 Planet20 infrared3)
    (take_image instrument4 Planet20 spectrograph4)
    (take_image instrument4 Planet20 thermograph2)
    (take_image instrument4 Planet5 infrared0)
    (take_image instrument4 Planet5 infrared1)
    (take_image instrument4 Planet5 infrared3)
    (take_image instrument4 Planet5 spectrograph4)
    (take_image instrument4 Planet5 thermograph2)
    (take_image instrument4 Planet8 infrared0)
    (take_image instrument4 Planet8 infrared1)
    (take_image instrument4 Planet8 infrared3)
    (take_image instrument4 Planet8 spectrograph4)
    (take_image instrument4 Planet8 thermograph2)
    (take_image instrument4 Star0 infrared0)
    (take_image instrument4 Star0 infrared1)
    (take_image instrument4 Star0 infrared3)
    (take_image instrument4 Star0 spectrograph4)
    (take_image instrument4 Star0 thermograph2)
    (take_image instrument4 Star12 infrared0)
    (take_image instrument4 Star12 infrared1)
    (take_image instrument4 Star12 infrared3)
    (take_image instrument4 Star12 spectrograph4)
    (take_image instrument4 Star12 thermograph2)
    (take_image instrument4 Star14 infrared0)
    (take_image instrument4 Star14 infrared1)
    (take_image instrument4 Star14 infrared3)
    (take_image instrument4 Star14 spectrograph4)
    (take_image instrument4 Star14 thermograph2)
    (take_image instrument4 Star15 infrared0)
    (take_image instrument4 Star15 infrared1)
    (take_image instrument4 Star15 infrared3)
    (take_image instrument4 Star15 spectrograph4)
    (take_image instrument4 Star15 thermograph2)
    (take_image instrument4 Star18 infrared0)
    (take_image instrument4 Star18 infrared1)
    (take_image instrument4 Star18 infrared3)
    (take_image instrument4 Star18 spectrograph4)
    (take_image instrument4 Star18 thermograph2)
    (take_image instrument4 Star19 infrared0)
    (take_image instrument4 Star19 infrared1)
    (take_image instrument4 Star19 infrared3)
    (take_image instrument4 Star19 spectrograph4)
    (take_image instrument4 Star19 thermograph2)
    (take_image instrument4 Star2 infrared0)
    (take_image instrument4 Star2 infrared1)
    (take_image instrument4 Star2 infrared3)
    (take_image instrument4 Star2 spectrograph4)
    (take_image instrument4 Star2 thermograph2)
    (take_image instrument4 Star22 infrared0)
    (take_image instrument4 Star22 infrared1)
    (take_image instrument4 Star22 infrared3)
    (take_image instrument4 Star22 spectrograph4)
    (take_image instrument4 Star22 thermograph2)
    (take_image instrument4 Star23 infrared0)
    (take_image instrument4 Star23 infrared1)
    (take_image instrument4 Star23 infrared3)
    (take_image instrument4 Star23 spectrograph4)
    (take_image instrument4 Star23 thermograph2)
    (take_image instrument4 Star3 infrared0)
    (take_image instrument4 Star3 infrared1)
    (take_image instrument4 Star3 infrared3)
    (take_image instrument4 Star3 spectrograph4)
    (take_image instrument4 Star3 thermograph2)
    (take_image instrument4 Star4 infrared0)
    (take_image instrument4 Star4 infrared1)
    (take_image instrument4 Star4 infrared3)
    (take_image instrument4 Star4 spectrograph4)
    (take_image instrument4 Star4 thermograph2)
    (take_image instrument4 Star7 infrared0)
    (take_image instrument4 Star7 infrared1)
    (take_image instrument4 Star7 infrared3)
    (take_image instrument4 Star7 spectrograph4)
    (take_image instrument4 Star7 thermograph2)
    (take_image instrument4 Star9 infrared0)
    (take_image instrument4 Star9 infrared1)
    (take_image instrument4 Star9 infrared3)
    (take_image instrument4 Star9 spectrograph4)
    (take_image instrument4 Star9 thermograph2)
    (take_image instrument5 GroundStation1 infrared0)
    (take_image instrument5 GroundStation1 infrared1)
    (take_image instrument5 GroundStation1 infrared3)
    (take_image instrument5 GroundStation1 spectrograph4)
    (take_image instrument5 GroundStation1 thermograph2)
    (take_image instrument5 Phenomenon13 infrared0)
    (take_image instrument5 Phenomenon13 infrared1)
    (take_image instrument5 Phenomenon13 infrared3)
    (take_image instrument5 Phenomenon13 spectrograph4)
    (take_image instrument5 Phenomenon13 thermograph2)
    (take_image instrument5 Phenomenon17 infrared0)
    (take_image instrument5 Phenomenon17 infrared1)
    (take_image instrument5 Phenomenon17 infrared3)
    (take_image instrument5 Phenomenon17 spectrograph4)
    (take_image instrument5 Phenomenon17 thermograph2)
    (take_image instrument5 Phenomenon21 infrared0)
    (take_image instrument5 Phenomenon21 infrared1)
    (take_image instrument5 Phenomenon21 infrared3)
    (take_image instrument5 Phenomenon21 spectrograph4)
    (take_image instrument5 Phenomenon21 thermograph2)
    (take_image instrument5 Phenomenon24 infrared0)
    (take_image instrument5 Phenomenon24 infrared1)
    (take_image instrument5 Phenomenon24 infrared3)
    (take_image instrument5 Phenomenon24 spectrograph4)
    (take_image instrument5 Phenomenon24 thermograph2)
    (take_image instrument5 Phenomenon6 infrared0)
    (take_image instrument5 Phenomenon6 infrared1)
    (take_image instrument5 Phenomenon6 infrared3)
    (take_image instrument5 Phenomenon6 spectrograph4)
    (take_image instrument5 Phenomenon6 thermograph2)
    (take_image instrument5 Planet10 infrared0)
    (take_image instrument5 Planet10 infrared1)
    (take_image instrument5 Planet10 infrared3)
    (take_image instrument5 Planet10 spectrograph4)
    (take_image instrument5 Planet10 thermograph2)
    (take_image instrument5 Planet11 infrared0)
    (take_image instrument5 Planet11 infrared1)
    (take_image instrument5 Planet11 infrared3)
    (take_image instrument5 Planet11 spectrograph4)
    (take_image instrument5 Planet11 thermograph2)
    (take_image instrument5 Planet16 infrared0)
    (take_image instrument5 Planet16 infrared1)
    (take_image instrument5 Planet16 infrared3)
    (take_image instrument5 Planet16 spectrograph4)
    (take_image instrument5 Planet16 thermograph2)
    (take_image instrument5 Planet20 infrared0)
    (take_image instrument5 Planet20 infrared1)
    (take_image instrument5 Planet20 infrared3)
    (take_image instrument5 Planet20 spectrograph4)
    (take_image instrument5 Planet20 thermograph2)
    (take_image instrument5 Planet5 infrared0)
    (take_image instrument5 Planet5 infrared1)
    (take_image instrument5 Planet5 infrared3)
    (take_image instrument5 Planet5 spectrograph4)
    (take_image instrument5 Planet5 thermograph2)
    (take_image instrument5 Planet8 infrared0)
    (take_image instrument5 Planet8 infrared1)
    (take_image instrument5 Planet8 infrared3)
    (take_image instrument5 Planet8 spectrograph4)
    (take_image instrument5 Planet8 thermograph2)
    (take_image instrument5 Star0 infrared0)
    (take_image instrument5 Star0 infrared1)
    (take_image instrument5 Star0 infrared3)
    (take_image instrument5 Star0 spectrograph4)
    (take_image instrument5 Star0 thermograph2)
    (take_image instrument5 Star12 infrared0)
    (take_image instrument5 Star12 infrared1)
    (take_image instrument5 Star12 infrared3)
    (take_image instrument5 Star12 spectrograph4)
    (take_image instrument5 Star12 thermograph2)
    (take_image instrument5 Star14 infrared0)
    (take_image instrument5 Star14 infrared1)
    (take_image instrument5 Star14 infrared3)
    (take_image instrument5 Star14 spectrograph4)
    (take_image instrument5 Star14 thermograph2)
    (take_image instrument5 Star15 infrared0)
    (take_image instrument5 Star15 infrared1)
    (take_image instrument5 Star15 infrared3)
    (take_image instrument5 Star15 spectrograph4)
    (take_image instrument5 Star15 thermograph2)
    (take_image instrument5 Star18 infrared0)
    (take_image instrument5 Star18 infrared1)
    (take_image instrument5 Star18 infrared3)
    (take_image instrument5 Star18 spectrograph4)
    (take_image instrument5 Star18 thermograph2)
    (take_image instrument5 Star19 infrared0)
    (take_image instrument5 Star19 infrared1)
    (take_image instrument5 Star19 infrared3)
    (take_image instrument5 Star19 spectrograph4)
    (take_image instrument5 Star19 thermograph2)
    (take_image instrument5 Star2 infrared0)
    (take_image instrument5 Star2 infrared1)
    (take_image instrument5 Star2 infrared3)
    (take_image instrument5 Star2 spectrograph4)
    (take_image instrument5 Star2 thermograph2)
    (take_image instrument5 Star22 infrared0)
    (take_image instrument5 Star22 infrared1)
    (take_image instrument5 Star22 infrared3)
    (take_image instrument5 Star22 spectrograph4)
    (take_image instrument5 Star22 thermograph2)
    (take_image instrument5 Star23 infrared0)
    (take_image instrument5 Star23 infrared1)
    (take_image instrument5 Star23 infrared3)
    (take_image instrument5 Star23 spectrograph4)
    (take_image instrument5 Star23 thermograph2)
    (take_image instrument5 Star3 infrared0)
    (take_image instrument5 Star3 infrared1)
    (take_image instrument5 Star3 infrared3)
    (take_image instrument5 Star3 spectrograph4)
    (take_image instrument5 Star3 thermograph2)
    (take_image instrument5 Star4 infrared0)
    (take_image instrument5 Star4 infrared1)
    (take_image instrument5 Star4 infrared3)
    (take_image instrument5 Star4 spectrograph4)
    (take_image instrument5 Star4 thermograph2)
    (take_image instrument5 Star7 infrared0)
    (take_image instrument5 Star7 infrared1)
    (take_image instrument5 Star7 infrared3)
    (take_image instrument5 Star7 spectrograph4)
    (take_image instrument5 Star7 thermograph2)
    (take_image instrument5 Star9 infrared0)
    (take_image instrument5 Star9 infrared1)
    (take_image instrument5 Star9 infrared3)
    (take_image instrument5 Star9 spectrograph4)
    (take_image instrument5 Star9 thermograph2)
    (take_image instrument6 GroundStation1 infrared0)
    (take_image instrument6 GroundStation1 infrared1)
    (take_image instrument6 GroundStation1 infrared3)
    (take_image instrument6 GroundStation1 spectrograph4)
    (take_image instrument6 GroundStation1 thermograph2)
    (take_image instrument6 Phenomenon13 infrared0)
    (take_image instrument6 Phenomenon13 infrared1)
    (take_image instrument6 Phenomenon13 infrared3)
    (take_image instrument6 Phenomenon13 spectrograph4)
    (take_image instrument6 Phenomenon13 thermograph2)
    (take_image instrument6 Phenomenon17 infrared0)
    (take_image instrument6 Phenomenon17 infrared1)
    (take_image instrument6 Phenomenon17 infrared3)
    (take_image instrument6 Phenomenon17 spectrograph4)
    (take_image instrument6 Phenomenon17 thermograph2)
    (take_image instrument6 Phenomenon21 infrared0)
    (take_image instrument6 Phenomenon21 infrared1)
    (take_image instrument6 Phenomenon21 infrared3)
    (take_image instrument6 Phenomenon21 spectrograph4)
    (take_image instrument6 Phenomenon21 thermograph2)
    (take_image instrument6 Phenomenon24 infrared0)
    (take_image instrument6 Phenomenon24 infrared1)
    (take_image instrument6 Phenomenon24 infrared3)
    (take_image instrument6 Phenomenon24 spectrograph4)
    (take_image instrument6 Phenomenon24 thermograph2)
    (take_image instrument6 Phenomenon6 infrared0)
    (take_image instrument6 Phenomenon6 infrared1)
    (take_image instrument6 Phenomenon6 infrared3)
    (take_image instrument6 Phenomenon6 spectrograph4)
    (take_image instrument6 Phenomenon6 thermograph2)
    (take_image instrument6 Planet10 infrared0)
    (take_image instrument6 Planet10 infrared1)
    (take_image instrument6 Planet10 infrared3)
    (take_image instrument6 Planet10 spectrograph4)
    (take_image instrument6 Planet10 thermograph2)
    (take_image instrument6 Planet11 infrared0)
    (take_image instrument6 Planet11 infrared1)
    (take_image instrument6 Planet11 infrared3)
    (take_image instrument6 Planet11 spectrograph4)
    (take_image instrument6 Planet11 thermograph2)
    (take_image instrument6 Planet16 infrared0)
    (take_image instrument6 Planet16 infrared1)
    (take_image instrument6 Planet16 infrared3)
    (take_image instrument6 Planet16 spectrograph4)
    (take_image instrument6 Planet16 thermograph2)
    (take_image instrument6 Planet20 infrared0)
    (take_image instrument6 Planet20 infrared1)
    (take_image instrument6 Planet20 infrared3)
    (take_image instrument6 Planet20 spectrograph4)
    (take_image instrument6 Planet20 thermograph2)
    (take_image instrument6 Planet5 infrared0)
    (take_image instrument6 Planet5 infrared1)
    (take_image instrument6 Planet5 infrared3)
    (take_image instrument6 Planet5 spectrograph4)
    (take_image instrument6 Planet5 thermograph2)
    (take_image instrument6 Planet8 infrared0)
    (take_image instrument6 Planet8 infrared1)
    (take_image instrument6 Planet8 infrared3)
    (take_image instrument6 Planet8 spectrograph4)
    (take_image instrument6 Planet8 thermograph2)
    (take_image instrument6 Star0 infrared0)
    (take_image instrument6 Star0 infrared1)
    (take_image instrument6 Star0 infrared3)
    (take_image instrument6 Star0 spectrograph4)
    (take_image instrument6 Star0 thermograph2)
    (take_image instrument6 Star12 infrared0)
    (take_image instrument6 Star12 infrared1)
    (take_image instrument6 Star12 infrared3)
    (take_image instrument6 Star12 spectrograph4)
    (take_image instrument6 Star12 thermograph2)
    (take_image instrument6 Star14 infrared0)
    (take_image instrument6 Star14 infrared1)
    (take_image instrument6 Star14 infrared3)
    (take_image instrument6 Star14 spectrograph4)
    (take_image instrument6 Star14 thermograph2)
    (take_image instrument6 Star15 infrared0)
    (take_image instrument6 Star15 infrared1)
    (take_image instrument6 Star15 infrared3)
    (take_image instrument6 Star15 spectrograph4)
    (take_image instrument6 Star15 thermograph2)
    (take_image instrument6 Star18 infrared0)
    (take_image instrument6 Star18 infrared1)
    (take_image instrument6 Star18 infrared3)
    (take_image instrument6 Star18 spectrograph4)
    (take_image instrument6 Star18 thermograph2)
    (take_image instrument6 Star19 infrared0)
    (take_image instrument6 Star19 infrared1)
    (take_image instrument6 Star19 infrared3)
    (take_image instrument6 Star19 spectrograph4)
    (take_image instrument6 Star19 thermograph2)
    (take_image instrument6 Star2 infrared0)
    (take_image instrument6 Star2 infrared1)
    (take_image instrument6 Star2 infrared3)
    (take_image instrument6 Star2 spectrograph4)
    (take_image instrument6 Star2 thermograph2)
    (take_image instrument6 Star22 infrared0)
    (take_image instrument6 Star22 infrared1)
    (take_image instrument6 Star22 infrared3)
    (take_image instrument6 Star22 spectrograph4)
    (take_image instrument6 Star22 thermograph2)
    (take_image instrument6 Star23 infrared0)
    (take_image instrument6 Star23 infrared1)
    (take_image instrument6 Star23 infrared3)
    (take_image instrument6 Star23 spectrograph4)
    (take_image instrument6 Star23 thermograph2)
    (take_image instrument6 Star3 infrared0)
    (take_image instrument6 Star3 infrared1)
    (take_image instrument6 Star3 infrared3)
    (take_image instrument6 Star3 spectrograph4)
    (take_image instrument6 Star3 thermograph2)
    (take_image instrument6 Star4 infrared0)
    (take_image instrument6 Star4 infrared1)
    (take_image instrument6 Star4 infrared3)
    (take_image instrument6 Star4 spectrograph4)
    (take_image instrument6 Star4 thermograph2)
    (take_image instrument6 Star7 infrared0)
    (take_image instrument6 Star7 infrared1)
    (take_image instrument6 Star7 infrared3)
    (take_image instrument6 Star7 spectrograph4)
    (take_image instrument6 Star7 thermograph2)
    (take_image instrument6 Star9 infrared0)
    (take_image instrument6 Star9 infrared1)
    (take_image instrument6 Star9 infrared3)
    (take_image instrument6 Star9 spectrograph4)
    (take_image instrument6 Star9 thermograph2)
    (take_image instrument7 GroundStation1 infrared0)
    (take_image instrument7 GroundStation1 infrared1)
    (take_image instrument7 GroundStation1 infrared3)
    (take_image instrument7 GroundStation1 spectrograph4)
    (take_image instrument7 GroundStation1 thermograph2)
    (take_image instrument7 Phenomenon13 infrared0)
    (take_image instrument7 Phenomenon13 infrared1)
    (take_image instrument7 Phenomenon13 infrared3)
    (take_image instrument7 Phenomenon13 spectrograph4)
    (take_image instrument7 Phenomenon13 thermograph2)
    (take_image instrument7 Phenomenon17 infrared0)
    (take_image instrument7 Phenomenon17 infrared1)
    (take_image instrument7 Phenomenon17 infrared3)
    (take_image instrument7 Phenomenon17 spectrograph4)
    (take_image instrument7 Phenomenon17 thermograph2)
    (take_image instrument7 Phenomenon21 infrared0)
    (take_image instrument7 Phenomenon21 infrared1)
    (take_image instrument7 Phenomenon21 infrared3)
    (take_image instrument7 Phenomenon21 spectrograph4)
    (take_image instrument7 Phenomenon21 thermograph2)
    (take_image instrument7 Phenomenon24 infrared0)
    (take_image instrument7 Phenomenon24 infrared1)
    (take_image instrument7 Phenomenon24 infrared3)
    (take_image instrument7 Phenomenon24 spectrograph4)
    (take_image instrument7 Phenomenon24 thermograph2)
    (take_image instrument7 Phenomenon6 infrared0)
    (take_image instrument7 Phenomenon6 infrared1)
    (take_image instrument7 Phenomenon6 infrared3)
    (take_image instrument7 Phenomenon6 spectrograph4)
    (take_image instrument7 Phenomenon6 thermograph2)
    (take_image instrument7 Planet10 infrared0)
    (take_image instrument7 Planet10 infrared1)
    (take_image instrument7 Planet10 infrared3)
    (take_image instrument7 Planet10 spectrograph4)
    (take_image instrument7 Planet10 thermograph2)
    (take_image instrument7 Planet11 infrared0)
    (take_image instrument7 Planet11 infrared1)
    (take_image instrument7 Planet11 infrared3)
    (take_image instrument7 Planet11 spectrograph4)
    (take_image instrument7 Planet11 thermograph2)
    (take_image instrument7 Planet16 infrared0)
    (take_image instrument7 Planet16 infrared1)
    (take_image instrument7 Planet16 infrared3)
    (take_image instrument7 Planet16 spectrograph4)
    (take_image instrument7 Planet16 thermograph2)
    (take_image instrument7 Planet20 infrared0)
    (take_image instrument7 Planet20 infrared1)
    (take_image instrument7 Planet20 infrared3)
    (take_image instrument7 Planet20 spectrograph4)
    (take_image instrument7 Planet20 thermograph2)
    (take_image instrument7 Planet5 infrared0)
    (take_image instrument7 Planet5 infrared1)
    (take_image instrument7 Planet5 infrared3)
    (take_image instrument7 Planet5 spectrograph4)
    (take_image instrument7 Planet5 thermograph2)
    (take_image instrument7 Planet8 infrared0)
    (take_image instrument7 Planet8 infrared1)
    (take_image instrument7 Planet8 infrared3)
    (take_image instrument7 Planet8 spectrograph4)
    (take_image instrument7 Planet8 thermograph2)
    (take_image instrument7 Star0 infrared0)
    (take_image instrument7 Star0 infrared1)
    (take_image instrument7 Star0 infrared3)
    (take_image instrument7 Star0 spectrograph4)
    (take_image instrument7 Star0 thermograph2)
    (take_image instrument7 Star12 infrared0)
    (take_image instrument7 Star12 infrared1)
    (take_image instrument7 Star12 infrared3)
    (take_image instrument7 Star12 spectrograph4)
    (take_image instrument7 Star12 thermograph2)
    (take_image instrument7 Star14 infrared0)
    (take_image instrument7 Star14 infrared1)
    (take_image instrument7 Star14 infrared3)
    (take_image instrument7 Star14 spectrograph4)
    (take_image instrument7 Star14 thermograph2)
    (take_image instrument7 Star15 infrared0)
    (take_image instrument7 Star15 infrared1)
    (take_image instrument7 Star15 infrared3)
    (take_image instrument7 Star15 spectrograph4)
    (take_image instrument7 Star15 thermograph2)
    (take_image instrument7 Star18 infrared0)
    (take_image instrument7 Star18 infrared1)
    (take_image instrument7 Star18 infrared3)
    (take_image instrument7 Star18 spectrograph4)
    (take_image instrument7 Star18 thermograph2)
    (take_image instrument7 Star19 infrared0)
    (take_image instrument7 Star19 infrared1)
    (take_image instrument7 Star19 infrared3)
    (take_image instrument7 Star19 spectrograph4)
    (take_image instrument7 Star19 thermograph2)
    (take_image instrument7 Star2 infrared0)
    (take_image instrument7 Star2 infrared1)
    (take_image instrument7 Star2 infrared3)
    (take_image instrument7 Star2 spectrograph4)
    (take_image instrument7 Star2 thermograph2)
    (take_image instrument7 Star22 infrared0)
    (take_image instrument7 Star22 infrared1)
    (take_image instrument7 Star22 infrared3)
    (take_image instrument7 Star22 spectrograph4)
    (take_image instrument7 Star22 thermograph2)
    (take_image instrument7 Star23 infrared0)
    (take_image instrument7 Star23 infrared1)
    (take_image instrument7 Star23 infrared3)
    (take_image instrument7 Star23 spectrograph4)
    (take_image instrument7 Star23 thermograph2)
    (take_image instrument7 Star3 infrared0)
    (take_image instrument7 Star3 infrared1)
    (take_image instrument7 Star3 infrared3)
    (take_image instrument7 Star3 spectrograph4)
    (take_image instrument7 Star3 thermograph2)
    (take_image instrument7 Star4 infrared0)
    (take_image instrument7 Star4 infrared1)
    (take_image instrument7 Star4 infrared3)
    (take_image instrument7 Star4 spectrograph4)
    (take_image instrument7 Star4 thermograph2)
    (take_image instrument7 Star7 infrared0)
    (take_image instrument7 Star7 infrared1)
    (take_image instrument7 Star7 infrared3)
    (take_image instrument7 Star7 spectrograph4)
    (take_image instrument7 Star7 thermograph2)
    (take_image instrument7 Star9 infrared0)
    (take_image instrument7 Star9 infrared1)
    (take_image instrument7 Star9 infrared3)
    (take_image instrument7 Star9 spectrograph4)
    (take_image instrument7 Star9 thermograph2)
    (take_image instrument8 GroundStation1 infrared0)
    (take_image instrument8 GroundStation1 infrared1)
    (take_image instrument8 GroundStation1 infrared3)
    (take_image instrument8 GroundStation1 spectrograph4)
    (take_image instrument8 GroundStation1 thermograph2)
    (take_image instrument8 Phenomenon13 infrared0)
    (take_image instrument8 Phenomenon13 infrared1)
    (take_image instrument8 Phenomenon13 infrared3)
    (take_image instrument8 Phenomenon13 spectrograph4)
    (take_image instrument8 Phenomenon13 thermograph2)
    (take_image instrument8 Phenomenon17 infrared0)
    (take_image instrument8 Phenomenon17 infrared1)
    (take_image instrument8 Phenomenon17 infrared3)
    (take_image instrument8 Phenomenon17 spectrograph4)
    (take_image instrument8 Phenomenon17 thermograph2)
    (take_image instrument8 Phenomenon21 infrared0)
    (take_image instrument8 Phenomenon21 infrared1)
    (take_image instrument8 Phenomenon21 infrared3)
    (take_image instrument8 Phenomenon21 spectrograph4)
    (take_image instrument8 Phenomenon21 thermograph2)
    (take_image instrument8 Phenomenon24 infrared0)
    (take_image instrument8 Phenomenon24 infrared1)
    (take_image instrument8 Phenomenon24 infrared3)
    (take_image instrument8 Phenomenon24 spectrograph4)
    (take_image instrument8 Phenomenon24 thermograph2)
    (take_image instrument8 Phenomenon6 infrared0)
    (take_image instrument8 Phenomenon6 infrared1)
    (take_image instrument8 Phenomenon6 infrared3)
    (take_image instrument8 Phenomenon6 spectrograph4)
    (take_image instrument8 Phenomenon6 thermograph2)
    (take_image instrument8 Planet10 infrared0)
    (take_image instrument8 Planet10 infrared1)
    (take_image instrument8 Planet10 infrared3)
    (take_image instrument8 Planet10 spectrograph4)
    (take_image instrument8 Planet10 thermograph2)
    (take_image instrument8 Planet11 infrared0)
    (take_image instrument8 Planet11 infrared1)
    (take_image instrument8 Planet11 infrared3)
    (take_image instrument8 Planet11 spectrograph4)
    (take_image instrument8 Planet11 thermograph2)
    (take_image instrument8 Planet16 infrared0)
    (take_image instrument8 Planet16 infrared1)
    (take_image instrument8 Planet16 infrared3)
    (take_image instrument8 Planet16 spectrograph4)
    (take_image instrument8 Planet16 thermograph2)
    (take_image instrument8 Planet20 infrared0)
    (take_image instrument8 Planet20 infrared1)
    (take_image instrument8 Planet20 infrared3)
    (take_image instrument8 Planet20 spectrograph4)
    (take_image instrument8 Planet20 thermograph2)
    (take_image instrument8 Planet5 infrared0)
    (take_image instrument8 Planet5 infrared1)
    (take_image instrument8 Planet5 infrared3)
    (take_image instrument8 Planet5 spectrograph4)
    (take_image instrument8 Planet5 thermograph2)
    (take_image instrument8 Planet8 infrared0)
    (take_image instrument8 Planet8 infrared1)
    (take_image instrument8 Planet8 infrared3)
    (take_image instrument8 Planet8 spectrograph4)
    (take_image instrument8 Planet8 thermograph2)
    (take_image instrument8 Star0 infrared0)
    (take_image instrument8 Star0 infrared1)
    (take_image instrument8 Star0 infrared3)
    (take_image instrument8 Star0 spectrograph4)
    (take_image instrument8 Star0 thermograph2)
    (take_image instrument8 Star12 infrared0)
    (take_image instrument8 Star12 infrared1)
    (take_image instrument8 Star12 infrared3)
    (take_image instrument8 Star12 spectrograph4)
    (take_image instrument8 Star12 thermograph2)
    (take_image instrument8 Star14 infrared0)
    (take_image instrument8 Star14 infrared1)
    (take_image instrument8 Star14 infrared3)
    (take_image instrument8 Star14 spectrograph4)
    (take_image instrument8 Star14 thermograph2)
    (take_image instrument8 Star15 infrared0)
    (take_image instrument8 Star15 infrared1)
    (take_image instrument8 Star15 infrared3)
    (take_image instrument8 Star15 spectrograph4)
    (take_image instrument8 Star15 thermograph2)
    (take_image instrument8 Star18 infrared0)
    (take_image instrument8 Star18 infrared1)
    (take_image instrument8 Star18 infrared3)
    (take_image instrument8 Star18 spectrograph4)
    (take_image instrument8 Star18 thermograph2)
    (take_image instrument8 Star19 infrared0)
    (take_image instrument8 Star19 infrared1)
    (take_image instrument8 Star19 infrared3)
    (take_image instrument8 Star19 spectrograph4)
    (take_image instrument8 Star19 thermograph2)
    (take_image instrument8 Star2 infrared0)
    (take_image instrument8 Star2 infrared1)
    (take_image instrument8 Star2 infrared3)
    (take_image instrument8 Star2 spectrograph4)
    (take_image instrument8 Star2 thermograph2)
    (take_image instrument8 Star22 infrared0)
    (take_image instrument8 Star22 infrared1)
    (take_image instrument8 Star22 infrared3)
    (take_image instrument8 Star22 spectrograph4)
    (take_image instrument8 Star22 thermograph2)
    (take_image instrument8 Star23 infrared0)
    (take_image instrument8 Star23 infrared1)
    (take_image instrument8 Star23 infrared3)
    (take_image instrument8 Star23 spectrograph4)
    (take_image instrument8 Star23 thermograph2)
    (take_image instrument8 Star3 infrared0)
    (take_image instrument8 Star3 infrared1)
    (take_image instrument8 Star3 infrared3)
    (take_image instrument8 Star3 spectrograph4)
    (take_image instrument8 Star3 thermograph2)
    (take_image instrument8 Star4 infrared0)
    (take_image instrument8 Star4 infrared1)
    (take_image instrument8 Star4 infrared3)
    (take_image instrument8 Star4 spectrograph4)
    (take_image instrument8 Star4 thermograph2)
    (take_image instrument8 Star7 infrared0)
    (take_image instrument8 Star7 infrared1)
    (take_image instrument8 Star7 infrared3)
    (take_image instrument8 Star7 spectrograph4)
    (take_image instrument8 Star7 thermograph2)
    (take_image instrument8 Star9 infrared0)
    (take_image instrument8 Star9 infrared1)
    (take_image instrument8 Star9 infrared3)
    (take_image instrument8 Star9 spectrograph4)
    (take_image instrument8 Star9 thermograph2)
    (take_image instrument9 GroundStation1 infrared0)
    (take_image instrument9 GroundStation1 infrared1)
    (take_image instrument9 GroundStation1 infrared3)
    (take_image instrument9 GroundStation1 spectrograph4)
    (take_image instrument9 GroundStation1 thermograph2)
    (take_image instrument9 Phenomenon13 infrared0)
    (take_image instrument9 Phenomenon13 infrared1)
    (take_image instrument9 Phenomenon13 infrared3)
    (take_image instrument9 Phenomenon13 spectrograph4)
    (take_image instrument9 Phenomenon13 thermograph2)
    (take_image instrument9 Phenomenon17 infrared0)
    (take_image instrument9 Phenomenon17 infrared1)
    (take_image instrument9 Phenomenon17 infrared3)
    (take_image instrument9 Phenomenon17 spectrograph4)
    (take_image instrument9 Phenomenon17 thermograph2)
    (take_image instrument9 Phenomenon21 infrared0)
    (take_image instrument9 Phenomenon21 infrared1)
    (take_image instrument9 Phenomenon21 infrared3)
    (take_image instrument9 Phenomenon21 spectrograph4)
    (take_image instrument9 Phenomenon21 thermograph2)
    (take_image instrument9 Phenomenon24 infrared0)
    (take_image instrument9 Phenomenon24 infrared1)
    (take_image instrument9 Phenomenon24 infrared3)
    (take_image instrument9 Phenomenon24 spectrograph4)
    (take_image instrument9 Phenomenon24 thermograph2)
    (take_image instrument9 Phenomenon6 infrared0)
    (take_image instrument9 Phenomenon6 infrared1)
    (take_image instrument9 Phenomenon6 infrared3)
    (take_image instrument9 Phenomenon6 spectrograph4)
    (take_image instrument9 Phenomenon6 thermograph2)
    (take_image instrument9 Planet10 infrared0)
    (take_image instrument9 Planet10 infrared1)
    (take_image instrument9 Planet10 infrared3)
    (take_image instrument9 Planet10 spectrograph4)
    (take_image instrument9 Planet10 thermograph2)
    (take_image instrument9 Planet11 infrared0)
    (take_image instrument9 Planet11 infrared1)
    (take_image instrument9 Planet11 infrared3)
    (take_image instrument9 Planet11 spectrograph4)
    (take_image instrument9 Planet11 thermograph2)
    (take_image instrument9 Planet16 infrared0)
    (take_image instrument9 Planet16 infrared1)
    (take_image instrument9 Planet16 infrared3)
    (take_image instrument9 Planet16 spectrograph4)
    (take_image instrument9 Planet16 thermograph2)
    (take_image instrument9 Planet20 infrared0)
    (take_image instrument9 Planet20 infrared1)
    (take_image instrument9 Planet20 infrared3)
    (take_image instrument9 Planet20 spectrograph4)
    (take_image instrument9 Planet20 thermograph2)
    (take_image instrument9 Planet5 infrared0)
    (take_image instrument9 Planet5 infrared1)
    (take_image instrument9 Planet5 infrared3)
    (take_image instrument9 Planet5 spectrograph4)
    (take_image instrument9 Planet5 thermograph2)
    (take_image instrument9 Planet8 infrared0)
    (take_image instrument9 Planet8 infrared1)
    (take_image instrument9 Planet8 infrared3)
    (take_image instrument9 Planet8 spectrograph4)
    (take_image instrument9 Planet8 thermograph2)
    (take_image instrument9 Star0 infrared0)
    (take_image instrument9 Star0 infrared1)
    (take_image instrument9 Star0 infrared3)
    (take_image instrument9 Star0 spectrograph4)
    (take_image instrument9 Star0 thermograph2)
    (take_image instrument9 Star12 infrared0)
    (take_image instrument9 Star12 infrared1)
    (take_image instrument9 Star12 infrared3)
    (take_image instrument9 Star12 spectrograph4)
    (take_image instrument9 Star12 thermograph2)
    (take_image instrument9 Star14 infrared0)
    (take_image instrument9 Star14 infrared1)
    (take_image instrument9 Star14 infrared3)
    (take_image instrument9 Star14 spectrograph4)
    (take_image instrument9 Star14 thermograph2)
    (take_image instrument9 Star15 infrared0)
    (take_image instrument9 Star15 infrared1)
    (take_image instrument9 Star15 infrared3)
    (take_image instrument9 Star15 spectrograph4)
    (take_image instrument9 Star15 thermograph2)
    (take_image instrument9 Star18 infrared0)
    (take_image instrument9 Star18 infrared1)
    (take_image instrument9 Star18 infrared3)
    (take_image instrument9 Star18 spectrograph4)
    (take_image instrument9 Star18 thermograph2)
    (take_image instrument9 Star19 infrared0)
    (take_image instrument9 Star19 infrared1)
    (take_image instrument9 Star19 infrared3)
    (take_image instrument9 Star19 spectrograph4)
    (take_image instrument9 Star19 thermograph2)
    (take_image instrument9 Star2 infrared0)
    (take_image instrument9 Star2 infrared1)
    (take_image instrument9 Star2 infrared3)
    (take_image instrument9 Star2 spectrograph4)
    (take_image instrument9 Star2 thermograph2)
    (take_image instrument9 Star22 infrared0)
    (take_image instrument9 Star22 infrared1)
    (take_image instrument9 Star22 infrared3)
    (take_image instrument9 Star22 spectrograph4)
    (take_image instrument9 Star22 thermograph2)
    (take_image instrument9 Star23 infrared0)
    (take_image instrument9 Star23 infrared1)
    (take_image instrument9 Star23 infrared3)
    (take_image instrument9 Star23 spectrograph4)
    (take_image instrument9 Star23 thermograph2)
    (take_image instrument9 Star3 infrared0)
    (take_image instrument9 Star3 infrared1)
    (take_image instrument9 Star3 infrared3)
    (take_image instrument9 Star3 spectrograph4)
    (take_image instrument9 Star3 thermograph2)
    (take_image instrument9 Star4 infrared0)
    (take_image instrument9 Star4 infrared1)
    (take_image instrument9 Star4 infrared3)
    (take_image instrument9 Star4 spectrograph4)
    (take_image instrument9 Star4 thermograph2)
    (take_image instrument9 Star7 infrared0)
    (take_image instrument9 Star7 infrared1)
    (take_image instrument9 Star7 infrared3)
    (take_image instrument9 Star7 spectrograph4)
    (take_image instrument9 Star7 thermograph2)
    (take_image instrument9 Star9 infrared0)
    (take_image instrument9 Star9 infrared1)
    (take_image instrument9 Star9 infrared3)
    (take_image instrument9 Star9 spectrograph4)
    (take_image instrument9 Star9 thermograph2)
    )
(:goal (and
	(have_image Planet5 infrared0)
	(have_image Phenomenon6 spectrograph4)
	(have_image Star7 infrared0)
	(have_image Planet8 infrared1)
	(have_image Star9 spectrograph4)
	(have_image Planet10 thermograph2)
	(have_image Planet11 infrared3)
	(have_image Phenomenon13 spectrograph4)
	(have_image Star14 thermograph2)
	(have_image Star15 infrared3)
	(have_image Planet16 infrared1)
	(have_image Phenomenon17 spectrograph4)
	(have_image Star18 spectrograph4)
	(have_image Star19 thermograph2)
	(have_image Planet20 thermograph2)
	(have_image Phenomenon21 thermograph2)
	(have_image Star22 infrared1)
	(have_image Star23 spectrograph4)
	(have_image Phenomenon24 infrared0)
))

)
