; Problem taken from https://github.com/AI-Planning/classical-domains

(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0
	instrument0
	instrument1
	instrument2
	satellite1
	instrument3
	image1
	infrared0
	spectrograph2
	Star1
	Star2
	Star0
	Star3
	Star4
	Phenomenon5
	Phenomenon6
	Phenomenon7
)
(:init
	(satellite satellite0)
	(instrument instrument0)
	(supports instrument0 spectrograph2)
	(supports instrument0 infrared0)
	(calibration_target instrument0 Star1)
	(instrument instrument1)
	(supports instrument1 image1)
	(calibration_target instrument1 Star2)
	(instrument instrument2)
	(supports instrument2 infrared0)
	(supports instrument2 image1)
	(calibration_target instrument2 Star0)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star4)
	(satellite satellite1)
	(instrument instrument3)
	(supports instrument3 spectrograph2)
	(supports instrument3 infrared0)
	(supports instrument3 image1)
	(calibration_target instrument3 Star0)
	(on_board instrument3 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star0)
	(mode image1)
	(mode infrared0)
	(mode spectrograph2)
	(direction Star1)
	(direction Star2)
	(direction Star0)
	(direction Star3)
	(direction Star4)
	(direction Phenomenon5)
	(direction Phenomenon6)
	(direction Phenomenon7)

    ; action literals
    (turn_to satellite0 Phenomenon5)
    (turn_to satellite0 Phenomenon6)
    (turn_to satellite0 Phenomenon7)
    (turn_to satellite0 Star0)
    (turn_to satellite0 Star1)
    (turn_to satellite0 Star2)
    (turn_to satellite0 Star3)
    (turn_to satellite0 Star4)
    (turn_to satellite1 Phenomenon5)
    (turn_to satellite1 Phenomenon6)
    (turn_to satellite1 Phenomenon7)
    (turn_to satellite1 Star0)
    (turn_to satellite1 Star1)
    (turn_to satellite1 Star2)
    (turn_to satellite1 Star3)
    (turn_to satellite1 Star4)
    (switch_on instrument0)
    (switch_off instrument0)
    (switch_on instrument1)
    (switch_off instrument1)
    (switch_on instrument2)
    (switch_off instrument2)
    (switch_on instrument3)
    (switch_off instrument3)
    (calibrate instrument0 Phenomenon5)
    (calibrate instrument0 Phenomenon6)
    (calibrate instrument0 Phenomenon7)
    (calibrate instrument0 Star0)
    (calibrate instrument0 Star1)
    (calibrate instrument0 Star2)
    (calibrate instrument0 Star3)
    (calibrate instrument0 Star4)
    (calibrate instrument1 Phenomenon5)
    (calibrate instrument1 Phenomenon6)
    (calibrate instrument1 Phenomenon7)
    (calibrate instrument1 Star0)
    (calibrate instrument1 Star1)
    (calibrate instrument1 Star2)
    (calibrate instrument1 Star3)
    (calibrate instrument1 Star4)
    (calibrate instrument2 Phenomenon5)
    (calibrate instrument2 Phenomenon6)
    (calibrate instrument2 Phenomenon7)
    (calibrate instrument2 Star0)
    (calibrate instrument2 Star1)
    (calibrate instrument2 Star2)
    (calibrate instrument2 Star3)
    (calibrate instrument2 Star4)
    (calibrate instrument3 Phenomenon5)
    (calibrate instrument3 Phenomenon6)
    (calibrate instrument3 Phenomenon7)
    (calibrate instrument3 Star0)
    (calibrate instrument3 Star1)
    (calibrate instrument3 Star2)
    (calibrate instrument3 Star3)
    (calibrate instrument3 Star4)
    (take_image instrument0 Phenomenon5 image1)
    (take_image instrument0 Phenomenon5 infrared0)
    (take_image instrument0 Phenomenon5 spectrograph2)
    (take_image instrument0 Phenomenon6 image1)
    (take_image instrument0 Phenomenon6 infrared0)
    (take_image instrument0 Phenomenon6 spectrograph2)
    (take_image instrument0 Phenomenon7 image1)
    (take_image instrument0 Phenomenon7 infrared0)
    (take_image instrument0 Phenomenon7 spectrograph2)
    (take_image instrument0 Star0 image1)
    (take_image instrument0 Star0 infrared0)
    (take_image instrument0 Star0 spectrograph2)
    (take_image instrument0 Star1 image1)
    (take_image instrument0 Star1 infrared0)
    (take_image instrument0 Star1 spectrograph2)
    (take_image instrument0 Star2 image1)
    (take_image instrument0 Star2 infrared0)
    (take_image instrument0 Star2 spectrograph2)
    (take_image instrument0 Star3 image1)
    (take_image instrument0 Star3 infrared0)
    (take_image instrument0 Star3 spectrograph2)
    (take_image instrument0 Star4 image1)
    (take_image instrument0 Star4 infrared0)
    (take_image instrument0 Star4 spectrograph2)
    (take_image instrument1 Phenomenon5 image1)
    (take_image instrument1 Phenomenon5 infrared0)
    (take_image instrument1 Phenomenon5 spectrograph2)
    (take_image instrument1 Phenomenon6 image1)
    (take_image instrument1 Phenomenon6 infrared0)
    (take_image instrument1 Phenomenon6 spectrograph2)
    (take_image instrument1 Phenomenon7 image1)
    (take_image instrument1 Phenomenon7 infrared0)
    (take_image instrument1 Phenomenon7 spectrograph2)
    (take_image instrument1 Star0 image1)
    (take_image instrument1 Star0 infrared0)
    (take_image instrument1 Star0 spectrograph2)
    (take_image instrument1 Star1 image1)
    (take_image instrument1 Star1 infrared0)
    (take_image instrument1 Star1 spectrograph2)
    (take_image instrument1 Star2 image1)
    (take_image instrument1 Star2 infrared0)
    (take_image instrument1 Star2 spectrograph2)
    (take_image instrument1 Star3 image1)
    (take_image instrument1 Star3 infrared0)
    (take_image instrument1 Star3 spectrograph2)
    (take_image instrument1 Star4 image1)
    (take_image instrument1 Star4 infrared0)
    (take_image instrument1 Star4 spectrograph2)
    (take_image instrument2 Phenomenon5 image1)
    (take_image instrument2 Phenomenon5 infrared0)
    (take_image instrument2 Phenomenon5 spectrograph2)
    (take_image instrument2 Phenomenon6 image1)
    (take_image instrument2 Phenomenon6 infrared0)
    (take_image instrument2 Phenomenon6 spectrograph2)
    (take_image instrument2 Phenomenon7 image1)
    (take_image instrument2 Phenomenon7 infrared0)
    (take_image instrument2 Phenomenon7 spectrograph2)
    (take_image instrument2 Star0 image1)
    (take_image instrument2 Star0 infrared0)
    (take_image instrument2 Star0 spectrograph2)
    (take_image instrument2 Star1 image1)
    (take_image instrument2 Star1 infrared0)
    (take_image instrument2 Star1 spectrograph2)
    (take_image instrument2 Star2 image1)
    (take_image instrument2 Star2 infrared0)
    (take_image instrument2 Star2 spectrograph2)
    (take_image instrument2 Star3 image1)
    (take_image instrument2 Star3 infrared0)
    (take_image instrument2 Star3 spectrograph2)
    (take_image instrument2 Star4 image1)
    (take_image instrument2 Star4 infrared0)
    (take_image instrument2 Star4 spectrograph2)
    (take_image instrument3 Phenomenon5 image1)
    (take_image instrument3 Phenomenon5 infrared0)
    (take_image instrument3 Phenomenon5 spectrograph2)
    (take_image instrument3 Phenomenon6 image1)
    (take_image instrument3 Phenomenon6 infrared0)
    (take_image instrument3 Phenomenon6 spectrograph2)
    (take_image instrument3 Phenomenon7 image1)
    (take_image instrument3 Phenomenon7 infrared0)
    (take_image instrument3 Phenomenon7 spectrograph2)
    (take_image instrument3 Star0 image1)
    (take_image instrument3 Star0 infrared0)
    (take_image instrument3 Star0 spectrograph2)
    (take_image instrument3 Star1 image1)
    (take_image instrument3 Star1 infrared0)
    (take_image instrument3 Star1 spectrograph2)
    (take_image instrument3 Star2 image1)
    (take_image instrument3 Star2 infrared0)
    (take_image instrument3 Star2 spectrograph2)
    (take_image instrument3 Star3 image1)
    (take_image instrument3 Star3 infrared0)
    (take_image instrument3 Star3 spectrograph2)
    (take_image instrument3 Star4 image1)
    (take_image instrument3 Star4 infrared0)
    (take_image instrument3 Star4 spectrograph2)
    )
(:goal (and
	(pointing satellite0 Phenomenon5)
	(have_image Star3 infrared0)
	(have_image Star4 spectrograph2)
	(have_image Phenomenon5 spectrograph2)
	(have_image Phenomenon7 spectrograph2)
))

)
