; Problem taken from https://github.com/AI-Planning/classical-domains

(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0
	instrument0
	instrument1
	instrument2
	satellite1
	instrument3
	satellite2
	instrument4
	instrument5
	satellite3
	instrument6
	instrument7
	image2
	image1
	image0
	image3
	Star3
	GroundStation2
	Star1
	GroundStation4
	GroundStation0
	Phenomenon5
	Star6
	Star7
	Planet8
	Planet9
	Planet10
	Planet11
)
(:init
	(satellite satellite0)
	(instrument instrument0)
	(supports instrument0 image1)
	(supports instrument0 image3)
	(calibration_target instrument0 Star1)
	(instrument instrument1)
	(supports instrument1 image3)
	(calibration_target instrument1 GroundStation0)
	(instrument instrument2)
	(supports instrument2 image0)
	(calibration_target instrument2 GroundStation2)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star6)
	(satellite satellite1)
	(instrument instrument3)
	(supports instrument3 image0)
	(supports instrument3 image2)
	(calibration_target instrument3 GroundStation4)
	(on_board instrument3 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation0)
	(satellite satellite2)
	(instrument instrument4)
	(supports instrument4 image1)
	(supports instrument4 image0)
	(calibration_target instrument4 Star1)
	(instrument instrument5)
	(supports instrument5 image2)
	(supports instrument5 image0)
	(supports instrument5 image1)
	(calibration_target instrument5 Star1)
	(on_board instrument4 satellite2)
	(on_board instrument5 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star6)
	(satellite satellite3)
	(instrument instrument6)
	(supports instrument6 image2)
	(supports instrument6 image1)
	(supports instrument6 image0)
	(calibration_target instrument6 GroundStation4)
	(instrument instrument7)
	(supports instrument7 image3)
	(supports instrument7 image0)
	(supports instrument7 image1)
	(calibration_target instrument7 GroundStation0)
	(on_board instrument6 satellite3)
	(on_board instrument7 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation2)
	(mode image2)
	(mode image1)
	(mode image0)
	(mode image3)
	(direction Star3)
	(direction GroundStation2)
	(direction Star1)
	(direction GroundStation4)
	(direction GroundStation0)
	(direction Phenomenon5)
	(direction Star6)
	(direction Star7)
	(direction Planet8)
	(direction Planet9)
	(direction Planet10)
	(direction Planet11)

    ; action literals
    (turn_to satellite0 GroundStation0)
    (turn_to satellite0 GroundStation2)
    (turn_to satellite0 GroundStation4)
    (turn_to satellite0 Phenomenon5)
    (turn_to satellite0 Planet10)
    (turn_to satellite0 Planet11)
    (turn_to satellite0 Planet8)
    (turn_to satellite0 Planet9)
    (turn_to satellite0 Star1)
    (turn_to satellite0 Star3)
    (turn_to satellite0 Star6)
    (turn_to satellite0 Star7)
    (turn_to satellite1 GroundStation0)
    (turn_to satellite1 GroundStation2)
    (turn_to satellite1 GroundStation4)
    (turn_to satellite1 Phenomenon5)
    (turn_to satellite1 Planet10)
    (turn_to satellite1 Planet11)
    (turn_to satellite1 Planet8)
    (turn_to satellite1 Planet9)
    (turn_to satellite1 Star1)
    (turn_to satellite1 Star3)
    (turn_to satellite1 Star6)
    (turn_to satellite1 Star7)
    (turn_to satellite2 GroundStation0)
    (turn_to satellite2 GroundStation2)
    (turn_to satellite2 GroundStation4)
    (turn_to satellite2 Phenomenon5)
    (turn_to satellite2 Planet10)
    (turn_to satellite2 Planet11)
    (turn_to satellite2 Planet8)
    (turn_to satellite2 Planet9)
    (turn_to satellite2 Star1)
    (turn_to satellite2 Star3)
    (turn_to satellite2 Star6)
    (turn_to satellite2 Star7)
    (turn_to satellite3 GroundStation0)
    (turn_to satellite3 GroundStation2)
    (turn_to satellite3 GroundStation4)
    (turn_to satellite3 Phenomenon5)
    (turn_to satellite3 Planet10)
    (turn_to satellite3 Planet11)
    (turn_to satellite3 Planet8)
    (turn_to satellite3 Planet9)
    (turn_to satellite3 Star1)
    (turn_to satellite3 Star3)
    (turn_to satellite3 Star6)
    (turn_to satellite3 Star7)
    (switch_on instrument0)
    (switch_off instrument0)
    (switch_on instrument1)
    (switch_off instrument1)
    (switch_on instrument2)
    (switch_off instrument2)
    (switch_on instrument3)
    (switch_off instrument3)
    (switch_on instrument4)
    (switch_off instrument4)
    (switch_on instrument5)
    (switch_off instrument5)
    (switch_on instrument6)
    (switch_off instrument6)
    (switch_on instrument7)
    (switch_off instrument7)
    (calibrate instrument0 GroundStation0)
    (calibrate instrument0 GroundStation2)
    (calibrate instrument0 GroundStation4)
    (calibrate instrument0 Phenomenon5)
    (calibrate instrument0 Planet10)
    (calibrate instrument0 Planet11)
    (calibrate instrument0 Planet8)
    (calibrate instrument0 Planet9)
    (calibrate instrument0 Star1)
    (calibrate instrument0 Star3)
    (calibrate instrument0 Star6)
    (calibrate instrument0 Star7)
    (calibrate instrument1 GroundStation0)
    (calibrate instrument1 GroundStation2)
    (calibrate instrument1 GroundStation4)
    (calibrate instrument1 Phenomenon5)
    (calibrate instrument1 Planet10)
    (calibrate instrument1 Planet11)
    (calibrate instrument1 Planet8)
    (calibrate instrument1 Planet9)
    (calibrate instrument1 Star1)
    (calibrate instrument1 Star3)
    (calibrate instrument1 Star6)
    (calibrate instrument1 Star7)
    (calibrate instrument2 GroundStation0)
    (calibrate instrument2 GroundStation2)
    (calibrate instrument2 GroundStation4)
    (calibrate instrument2 Phenomenon5)
    (calibrate instrument2 Planet10)
    (calibrate instrument2 Planet11)
    (calibrate instrument2 Planet8)
    (calibrate instrument2 Planet9)
    (calibrate instrument2 Star1)
    (calibrate instrument2 Star3)
    (calibrate instrument2 Star6)
    (calibrate instrument2 Star7)
    (calibrate instrument3 GroundStation0)
    (calibrate instrument3 GroundStation2)
    (calibrate instrument3 GroundStation4)
    (calibrate instrument3 Phenomenon5)
    (calibrate instrument3 Planet10)
    (calibrate instrument3 Planet11)
    (calibrate instrument3 Planet8)
    (calibrate instrument3 Planet9)
    (calibrate instrument3 Star1)
    (calibrate instrument3 Star3)
    (calibrate instrument3 Star6)
    (calibrate instrument3 Star7)
    (calibrate instrument4 GroundStation0)
    (calibrate instrument4 GroundStation2)
    (calibrate instrument4 GroundStation4)
    (calibrate instrument4 Phenomenon5)
    (calibrate instrument4 Planet10)
    (calibrate instrument4 Planet11)
    (calibrate instrument4 Planet8)
    (calibrate instrument4 Planet9)
    (calibrate instrument4 Star1)
    (calibrate instrument4 Star3)
    (calibrate instrument4 Star6)
    (calibrate instrument4 Star7)
    (calibrate instrument5 GroundStation0)
    (calibrate instrument5 GroundStation2)
    (calibrate instrument5 GroundStation4)
    (calibrate instrument5 Phenomenon5)
    (calibrate instrument5 Planet10)
    (calibrate instrument5 Planet11)
    (calibrate instrument5 Planet8)
    (calibrate instrument5 Planet9)
    (calibrate instrument5 Star1)
    (calibrate instrument5 Star3)
    (calibrate instrument5 Star6)
    (calibrate instrument5 Star7)
    (calibrate instrument6 GroundStation0)
    (calibrate instrument6 GroundStation2)
    (calibrate instrument6 GroundStation4)
    (calibrate instrument6 Phenomenon5)
    (calibrate instrument6 Planet10)
    (calibrate instrument6 Planet11)
    (calibrate instrument6 Planet8)
    (calibrate instrument6 Planet9)
    (calibrate instrument6 Star1)
    (calibrate instrument6 Star3)
    (calibrate instrument6 Star6)
    (calibrate instrument6 Star7)
    (calibrate instrument7 GroundStation0)
    (calibrate instrument7 GroundStation2)
    (calibrate instrument7 GroundStation4)
    (calibrate instrument7 Phenomenon5)
    (calibrate instrument7 Planet10)
    (calibrate instrument7 Planet11)
    (calibrate instrument7 Planet8)
    (calibrate instrument7 Planet9)
    (calibrate instrument7 Star1)
    (calibrate instrument7 Star3)
    (calibrate instrument7 Star6)
    (calibrate instrument7 Star7)
    (take_image instrument0 GroundStation0 image0)
    (take_image instrument0 GroundStation0 image1)
    (take_image instrument0 GroundStation0 image2)
    (take_image instrument0 GroundStation0 image3)
    (take_image instrument0 GroundStation2 image0)
    (take_image instrument0 GroundStation2 image1)
    (take_image instrument0 GroundStation2 image2)
    (take_image instrument0 GroundStation2 image3)
    (take_image instrument0 GroundStation4 image0)
    (take_image instrument0 GroundStation4 image1)
    (take_image instrument0 GroundStation4 image2)
    (take_image instrument0 GroundStation4 image3)
    (take_image instrument0 Phenomenon5 image0)
    (take_image instrument0 Phenomenon5 image1)
    (take_image instrument0 Phenomenon5 image2)
    (take_image instrument0 Phenomenon5 image3)
    (take_image instrument0 Planet10 image0)
    (take_image instrument0 Planet10 image1)
    (take_image instrument0 Planet10 image2)
    (take_image instrument0 Planet10 image3)
    (take_image instrument0 Planet11 image0)
    (take_image instrument0 Planet11 image1)
    (take_image instrument0 Planet11 image2)
    (take_image instrument0 Planet11 image3)
    (take_image instrument0 Planet8 image0)
    (take_image instrument0 Planet8 image1)
    (take_image instrument0 Planet8 image2)
    (take_image instrument0 Planet8 image3)
    (take_image instrument0 Planet9 image0)
    (take_image instrument0 Planet9 image1)
    (take_image instrument0 Planet9 image2)
    (take_image instrument0 Planet9 image3)
    (take_image instrument0 Star1 image0)
    (take_image instrument0 Star1 image1)
    (take_image instrument0 Star1 image2)
    (take_image instrument0 Star1 image3)
    (take_image instrument0 Star3 image0)
    (take_image instrument0 Star3 image1)
    (take_image instrument0 Star3 image2)
    (take_image instrument0 Star3 image3)
    (take_image instrument0 Star6 image0)
    (take_image instrument0 Star6 image1)
    (take_image instrument0 Star6 image2)
    (take_image instrument0 Star6 image3)
    (take_image instrument0 Star7 image0)
    (take_image instrument0 Star7 image1)
    (take_image instrument0 Star7 image2)
    (take_image instrument0 Star7 image3)
    (take_image instrument1 GroundStation0 image0)
    (take_image instrument1 GroundStation0 image1)
    (take_image instrument1 GroundStation0 image2)
    (take_image instrument1 GroundStation0 image3)
    (take_image instrument1 GroundStation2 image0)
    (take_image instrument1 GroundStation2 image1)
    (take_image instrument1 GroundStation2 image2)
    (take_image instrument1 GroundStation2 image3)
    (take_image instrument1 GroundStation4 image0)
    (take_image instrument1 GroundStation4 image1)
    (take_image instrument1 GroundStation4 image2)
    (take_image instrument1 GroundStation4 image3)
    (take_image instrument1 Phenomenon5 image0)
    (take_image instrument1 Phenomenon5 image1)
    (take_image instrument1 Phenomenon5 image2)
    (take_image instrument1 Phenomenon5 image3)
    (take_image instrument1 Planet10 image0)
    (take_image instrument1 Planet10 image1)
    (take_image instrument1 Planet10 image2)
    (take_image instrument1 Planet10 image3)
    (take_image instrument1 Planet11 image0)
    (take_image instrument1 Planet11 image1)
    (take_image instrument1 Planet11 image2)
    (take_image instrument1 Planet11 image3)
    (take_image instrument1 Planet8 image0)
    (take_image instrument1 Planet8 image1)
    (take_image instrument1 Planet8 image2)
    (take_image instrument1 Planet8 image3)
    (take_image instrument1 Planet9 image0)
    (take_image instrument1 Planet9 image1)
    (take_image instrument1 Planet9 image2)
    (take_image instrument1 Planet9 image3)
    (take_image instrument1 Star1 image0)
    (take_image instrument1 Star1 image1)
    (take_image instrument1 Star1 image2)
    (take_image instrument1 Star1 image3)
    (take_image instrument1 Star3 image0)
    (take_image instrument1 Star3 image1)
    (take_image instrument1 Star3 image2)
    (take_image instrument1 Star3 image3)
    (take_image instrument1 Star6 image0)
    (take_image instrument1 Star6 image1)
    (take_image instrument1 Star6 image2)
    (take_image instrument1 Star6 image3)
    (take_image instrument1 Star7 image0)
    (take_image instrument1 Star7 image1)
    (take_image instrument1 Star7 image2)
    (take_image instrument1 Star7 image3)
    (take_image instrument2 GroundStation0 image0)
    (take_image instrument2 GroundStation0 image1)
    (take_image instrument2 GroundStation0 image2)
    (take_image instrument2 GroundStation0 image3)
    (take_image instrument2 GroundStation2 image0)
    (take_image instrument2 GroundStation2 image1)
    (take_image instrument2 GroundStation2 image2)
    (take_image instrument2 GroundStation2 image3)
    (take_image instrument2 GroundStation4 image0)
    (take_image instrument2 GroundStation4 image1)
    (take_image instrument2 GroundStation4 image2)
    (take_image instrument2 GroundStation4 image3)
    (take_image instrument2 Phenomenon5 image0)
    (take_image instrument2 Phenomenon5 image1)
    (take_image instrument2 Phenomenon5 image2)
    (take_image instrument2 Phenomenon5 image3)
    (take_image instrument2 Planet10 image0)
    (take_image instrument2 Planet10 image1)
    (take_image instrument2 Planet10 image2)
    (take_image instrument2 Planet10 image3)
    (take_image instrument2 Planet11 image0)
    (take_image instrument2 Planet11 image1)
    (take_image instrument2 Planet11 image2)
    (take_image instrument2 Planet11 image3)
    (take_image instrument2 Planet8 image0)
    (take_image instrument2 Planet8 image1)
    (take_image instrument2 Planet8 image2)
    (take_image instrument2 Planet8 image3)
    (take_image instrument2 Planet9 image0)
    (take_image instrument2 Planet9 image1)
    (take_image instrument2 Planet9 image2)
    (take_image instrument2 Planet9 image3)
    (take_image instrument2 Star1 image0)
    (take_image instrument2 Star1 image1)
    (take_image instrument2 Star1 image2)
    (take_image instrument2 Star1 image3)
    (take_image instrument2 Star3 image0)
    (take_image instrument2 Star3 image1)
    (take_image instrument2 Star3 image2)
    (take_image instrument2 Star3 image3)
    (take_image instrument2 Star6 image0)
    (take_image instrument2 Star6 image1)
    (take_image instrument2 Star6 image2)
    (take_image instrument2 Star6 image3)
    (take_image instrument2 Star7 image0)
    (take_image instrument2 Star7 image1)
    (take_image instrument2 Star7 image2)
    (take_image instrument2 Star7 image3)
    (take_image instrument3 GroundStation0 image0)
    (take_image instrument3 GroundStation0 image1)
    (take_image instrument3 GroundStation0 image2)
    (take_image instrument3 GroundStation0 image3)
    (take_image instrument3 GroundStation2 image0)
    (take_image instrument3 GroundStation2 image1)
    (take_image instrument3 GroundStation2 image2)
    (take_image instrument3 GroundStation2 image3)
    (take_image instrument3 GroundStation4 image0)
    (take_image instrument3 GroundStation4 image1)
    (take_image instrument3 GroundStation4 image2)
    (take_image instrument3 GroundStation4 image3)
    (take_image instrument3 Phenomenon5 image0)
    (take_image instrument3 Phenomenon5 image1)
    (take_image instrument3 Phenomenon5 image2)
    (take_image instrument3 Phenomenon5 image3)
    (take_image instrument3 Planet10 image0)
    (take_image instrument3 Planet10 image1)
    (take_image instrument3 Planet10 image2)
    (take_image instrument3 Planet10 image3)
    (take_image instrument3 Planet11 image0)
    (take_image instrument3 Planet11 image1)
    (take_image instrument3 Planet11 image2)
    (take_image instrument3 Planet11 image3)
    (take_image instrument3 Planet8 image0)
    (take_image instrument3 Planet8 image1)
    (take_image instrument3 Planet8 image2)
    (take_image instrument3 Planet8 image3)
    (take_image instrument3 Planet9 image0)
    (take_image instrument3 Planet9 image1)
    (take_image instrument3 Planet9 image2)
    (take_image instrument3 Planet9 image3)
    (take_image instrument3 Star1 image0)
    (take_image instrument3 Star1 image1)
    (take_image instrument3 Star1 image2)
    (take_image instrument3 Star1 image3)
    (take_image instrument3 Star3 image0)
    (take_image instrument3 Star3 image1)
    (take_image instrument3 Star3 image2)
    (take_image instrument3 Star3 image3)
    (take_image instrument3 Star6 image0)
    (take_image instrument3 Star6 image1)
    (take_image instrument3 Star6 image2)
    (take_image instrument3 Star6 image3)
    (take_image instrument3 Star7 image0)
    (take_image instrument3 Star7 image1)
    (take_image instrument3 Star7 image2)
    (take_image instrument3 Star7 image3)
    (take_image instrument4 GroundStation0 image0)
    (take_image instrument4 GroundStation0 image1)
    (take_image instrument4 GroundStation0 image2)
    (take_image instrument4 GroundStation0 image3)
    (take_image instrument4 GroundStation2 image0)
    (take_image instrument4 GroundStation2 image1)
    (take_image instrument4 GroundStation2 image2)
    (take_image instrument4 GroundStation2 image3)
    (take_image instrument4 GroundStation4 image0)
    (take_image instrument4 GroundStation4 image1)
    (take_image instrument4 GroundStation4 image2)
    (take_image instrument4 GroundStation4 image3)
    (take_image instrument4 Phenomenon5 image0)
    (take_image instrument4 Phenomenon5 image1)
    (take_image instrument4 Phenomenon5 image2)
    (take_image instrument4 Phenomenon5 image3)
    (take_image instrument4 Planet10 image0)
    (take_image instrument4 Planet10 image1)
    (take_image instrument4 Planet10 image2)
    (take_image instrument4 Planet10 image3)
    (take_image instrument4 Planet11 image0)
    (take_image instrument4 Planet11 image1)
    (take_image instrument4 Planet11 image2)
    (take_image instrument4 Planet11 image3)
    (take_image instrument4 Planet8 image0)
    (take_image instrument4 Planet8 image1)
    (take_image instrument4 Planet8 image2)
    (take_image instrument4 Planet8 image3)
    (take_image instrument4 Planet9 image0)
    (take_image instrument4 Planet9 image1)
    (take_image instrument4 Planet9 image2)
    (take_image instrument4 Planet9 image3)
    (take_image instrument4 Star1 image0)
    (take_image instrument4 Star1 image1)
    (take_image instrument4 Star1 image2)
    (take_image instrument4 Star1 image3)
    (take_image instrument4 Star3 image0)
    (take_image instrument4 Star3 image1)
    (take_image instrument4 Star3 image2)
    (take_image instrument4 Star3 image3)
    (take_image instrument4 Star6 image0)
    (take_image instrument4 Star6 image1)
    (take_image instrument4 Star6 image2)
    (take_image instrument4 Star6 image3)
    (take_image instrument4 Star7 image0)
    (take_image instrument4 Star7 image1)
    (take_image instrument4 Star7 image2)
    (take_image instrument4 Star7 image3)
    (take_image instrument5 GroundStation0 image0)
    (take_image instrument5 GroundStation0 image1)
    (take_image instrument5 GroundStation0 image2)
    (take_image instrument5 GroundStation0 image3)
    (take_image instrument5 GroundStation2 image0)
    (take_image instrument5 GroundStation2 image1)
    (take_image instrument5 GroundStation2 image2)
    (take_image instrument5 GroundStation2 image3)
    (take_image instrument5 GroundStation4 image0)
    (take_image instrument5 GroundStation4 image1)
    (take_image instrument5 GroundStation4 image2)
    (take_image instrument5 GroundStation4 image3)
    (take_image instrument5 Phenomenon5 image0)
    (take_image instrument5 Phenomenon5 image1)
    (take_image instrument5 Phenomenon5 image2)
    (take_image instrument5 Phenomenon5 image3)
    (take_image instrument5 Planet10 image0)
    (take_image instrument5 Planet10 image1)
    (take_image instrument5 Planet10 image2)
    (take_image instrument5 Planet10 image3)
    (take_image instrument5 Planet11 image0)
    (take_image instrument5 Planet11 image1)
    (take_image instrument5 Planet11 image2)
    (take_image instrument5 Planet11 image3)
    (take_image instrument5 Planet8 image0)
    (take_image instrument5 Planet8 image1)
    (take_image instrument5 Planet8 image2)
    (take_image instrument5 Planet8 image3)
    (take_image instrument5 Planet9 image0)
    (take_image instrument5 Planet9 image1)
    (take_image instrument5 Planet9 image2)
    (take_image instrument5 Planet9 image3)
    (take_image instrument5 Star1 image0)
    (take_image instrument5 Star1 image1)
    (take_image instrument5 Star1 image2)
    (take_image instrument5 Star1 image3)
    (take_image instrument5 Star3 image0)
    (take_image instrument5 Star3 image1)
    (take_image instrument5 Star3 image2)
    (take_image instrument5 Star3 image3)
    (take_image instrument5 Star6 image0)
    (take_image instrument5 Star6 image1)
    (take_image instrument5 Star6 image2)
    (take_image instrument5 Star6 image3)
    (take_image instrument5 Star7 image0)
    (take_image instrument5 Star7 image1)
    (take_image instrument5 Star7 image2)
    (take_image instrument5 Star7 image3)
    (take_image instrument6 GroundStation0 image0)
    (take_image instrument6 GroundStation0 image1)
    (take_image instrument6 GroundStation0 image2)
    (take_image instrument6 GroundStation0 image3)
    (take_image instrument6 GroundStation2 image0)
    (take_image instrument6 GroundStation2 image1)
    (take_image instrument6 GroundStation2 image2)
    (take_image instrument6 GroundStation2 image3)
    (take_image instrument6 GroundStation4 image0)
    (take_image instrument6 GroundStation4 image1)
    (take_image instrument6 GroundStation4 image2)
    (take_image instrument6 GroundStation4 image3)
    (take_image instrument6 Phenomenon5 image0)
    (take_image instrument6 Phenomenon5 image1)
    (take_image instrument6 Phenomenon5 image2)
    (take_image instrument6 Phenomenon5 image3)
    (take_image instrument6 Planet10 image0)
    (take_image instrument6 Planet10 image1)
    (take_image instrument6 Planet10 image2)
    (take_image instrument6 Planet10 image3)
    (take_image instrument6 Planet11 image0)
    (take_image instrument6 Planet11 image1)
    (take_image instrument6 Planet11 image2)
    (take_image instrument6 Planet11 image3)
    (take_image instrument6 Planet8 image0)
    (take_image instrument6 Planet8 image1)
    (take_image instrument6 Planet8 image2)
    (take_image instrument6 Planet8 image3)
    (take_image instrument6 Planet9 image0)
    (take_image instrument6 Planet9 image1)
    (take_image instrument6 Planet9 image2)
    (take_image instrument6 Planet9 image3)
    (take_image instrument6 Star1 image0)
    (take_image instrument6 Star1 image1)
    (take_image instrument6 Star1 image2)
    (take_image instrument6 Star1 image3)
    (take_image instrument6 Star3 image0)
    (take_image instrument6 Star3 image1)
    (take_image instrument6 Star3 image2)
    (take_image instrument6 Star3 image3)
    (take_image instrument6 Star6 image0)
    (take_image instrument6 Star6 image1)
    (take_image instrument6 Star6 image2)
    (take_image instrument6 Star6 image3)
    (take_image instrument6 Star7 image0)
    (take_image instrument6 Star7 image1)
    (take_image instrument6 Star7 image2)
    (take_image instrument6 Star7 image3)
    (take_image instrument7 GroundStation0 image0)
    (take_image instrument7 GroundStation0 image1)
    (take_image instrument7 GroundStation0 image2)
    (take_image instrument7 GroundStation0 image3)
    (take_image instrument7 GroundStation2 image0)
    (take_image instrument7 GroundStation2 image1)
    (take_image instrument7 GroundStation2 image2)
    (take_image instrument7 GroundStation2 image3)
    (take_image instrument7 GroundStation4 image0)
    (take_image instrument7 GroundStation4 image1)
    (take_image instrument7 GroundStation4 image2)
    (take_image instrument7 GroundStation4 image3)
    (take_image instrument7 Phenomenon5 image0)
    (take_image instrument7 Phenomenon5 image1)
    (take_image instrument7 Phenomenon5 image2)
    (take_image instrument7 Phenomenon5 image3)
    (take_image instrument7 Planet10 image0)
    (take_image instrument7 Planet10 image1)
    (take_image instrument7 Planet10 image2)
    (take_image instrument7 Planet10 image3)
    (take_image instrument7 Planet11 image0)
    (take_image instrument7 Planet11 image1)
    (take_image instrument7 Planet11 image2)
    (take_image instrument7 Planet11 image3)
    (take_image instrument7 Planet8 image0)
    (take_image instrument7 Planet8 image1)
    (take_image instrument7 Planet8 image2)
    (take_image instrument7 Planet8 image3)
    (take_image instrument7 Planet9 image0)
    (take_image instrument7 Planet9 image1)
    (take_image instrument7 Planet9 image2)
    (take_image instrument7 Planet9 image3)
    (take_image instrument7 Star1 image0)
    (take_image instrument7 Star1 image1)
    (take_image instrument7 Star1 image2)
    (take_image instrument7 Star1 image3)
    (take_image instrument7 Star3 image0)
    (take_image instrument7 Star3 image1)
    (take_image instrument7 Star3 image2)
    (take_image instrument7 Star3 image3)
    (take_image instrument7 Star6 image0)
    (take_image instrument7 Star6 image1)
    (take_image instrument7 Star6 image2)
    (take_image instrument7 Star6 image3)
    (take_image instrument7 Star7 image0)
    (take_image instrument7 Star7 image1)
    (take_image instrument7 Star7 image2)
    (take_image instrument7 Star7 image3)
    )
(:goal (and
	(pointing satellite1 Star1)
	(pointing satellite2 Phenomenon5)
	(have_image Phenomenon5 image0)
	(have_image Star6 image1)
	(have_image Star7 image0)
	(have_image Planet8 image0)
	(have_image Planet9 image3)
	(have_image Planet10 image0)
	(have_image Planet11 image2)
))

)
