; Problem taken from https://github.com/AI-Planning/classical-domains


(define (problem os-sequencedstrips-small-7)
        (:domain openstacks-sequencedstrips)
        (:objects n0 n1 n2 n3 n4 n5 - count o1 o2 o3 o4 o5 - order p1 p2 p3 p4
         p5 - product)
        (:init (machine-available) (next-count n0 n1) (next-count n1 n2)
         (next-count n2 n3) (next-count n3 n4) (next-count n4 n5)
         (stacks-avail n0) (waiting o1) (includes o1 p1) (includes o1 p2)
         (waiting o2) (includes o2 p3) (includes o2 p4) (waiting o3)
         (includes o3 p3) (includes o3 p5) (waiting o4) (includes o4 p1)
         (includes o4 p5) (waiting o5) (includes o5 p2) (includes o5 p4)
    ; action literals
    (setup-machine p1)
    (setup-machine p2)
    (setup-machine p3)
    (setup-machine p4)
    (setup-machine p5)
    (make-product p1)
    (make-product p2)
    (make-product p3)
    (make-product p4)
    (make-product p5)
    (start-order o1)
    (start-order o2)
    (start-order o3)
    (start-order o4)
    (start-order o5)
    (ship-order o1)
    (ship-order o2)
    (ship-order o3)
    (ship-order o4)
    (ship-order o5)
    (open-new-stack)
    )
        (:goal
         (and (shipped o1)
              (shipped o2)
              (shipped o3)
              (shipped o4)
              (shipped o5))))
