; Problem taken from https://github.com/AI-Planning/classical-domains

(define (problem ZTRAVEL-5-20)
(:domain zeno-travel)
(:objects
	plane1
	plane2
	plane3
	plane4
	plane5
	person1
	person2
	person3
	person4
	person5
	person6
	person7
	person8
	person9
	person10
	person11
	person12
	person13
	person14
	person15
	person16
	person17
	person18
	person19
	person20
	city0
	city1
	city2
	city3
	city4
	city5
	city6
	city7
	city8
	city9
	city10
	city11
	city12
	city13
	city14
	city15
	city16
	city17
	fl0
	fl1
	fl2
	fl3
	fl4
	fl5
	fl6
	)
(:init
	(at plane1 city11)
	(aircraft plane1)
	(fuel-level plane1 fl3)
	(at plane2 city12)
	(aircraft plane2)
	(fuel-level plane2 fl3)
	(at plane3 city12)
	(aircraft plane3)
	(fuel-level plane3 fl0)
	(at plane4 city14)
	(aircraft plane4)
	(fuel-level plane4 fl0)
	(at plane5 city14)
	(aircraft plane5)
	(fuel-level plane5 fl6)
	(at person1 city7)
	(person person1)
	(at person2 city16)
	(person person2)
	(at person3 city9)
	(person person3)
	(at person4 city6)
	(person person4)
	(at person5 city6)
	(person person5)
	(at person6 city0)
	(person person6)
	(at person7 city6)
	(person person7)
	(at person8 city8)
	(person person8)
	(at person9 city13)
	(person person9)
	(at person10 city14)
	(person person10)
	(at person11 city7)
	(person person11)
	(at person12 city15)
	(person person12)
	(at person13 city4)
	(person person13)
	(at person14 city14)
	(person person14)
	(at person15 city10)
	(person person15)
	(at person16 city5)
	(person person16)
	(at person17 city10)
	(person person17)
	(at person18 city11)
	(person person18)
	(at person19 city9)
	(person person19)
	(at person20 city3)
	(person person20)
	(city city0)
	(city city1)
	(city city2)
	(city city3)
	(city city4)
	(city city5)
	(city city6)
	(city city7)
	(city city8)
	(city city9)
	(city city10)
	(city city11)
	(city city12)
	(city city13)
	(city city14)
	(city city15)
	(city city16)
	(city city17)
	(next fl0 fl1)
	(next fl1 fl2)
	(next fl2 fl3)
	(next fl3 fl4)
	(next fl4 fl5)
	(next fl5 fl6)
	(flevel fl0)
	(flevel fl1)
	(flevel fl2)
	(flevel fl3)
	(flevel fl4)
	(flevel fl5)
	(flevel fl6)

    ; action literals
    (board person1 plane1)
    (debark person1 plane1)
    (board person1 plane2)
    (debark person1 plane2)
    (board person1 plane3)
    (debark person1 plane3)
    (board person1 plane4)
    (debark person1 plane4)
    (board person1 plane5)
    (debark person1 plane5)
    (board person10 plane1)
    (debark person10 plane1)
    (board person10 plane2)
    (debark person10 plane2)
    (board person10 plane3)
    (debark person10 plane3)
    (board person10 plane4)
    (debark person10 plane4)
    (board person10 plane5)
    (debark person10 plane5)
    (board person11 plane1)
    (debark person11 plane1)
    (board person11 plane2)
    (debark person11 plane2)
    (board person11 plane3)
    (debark person11 plane3)
    (board person11 plane4)
    (debark person11 plane4)
    (board person11 plane5)
    (debark person11 plane5)
    (board person12 plane1)
    (debark person12 plane1)
    (board person12 plane2)
    (debark person12 plane2)
    (board person12 plane3)
    (debark person12 plane3)
    (board person12 plane4)
    (debark person12 plane4)
    (board person12 plane5)
    (debark person12 plane5)
    (board person13 plane1)
    (debark person13 plane1)
    (board person13 plane2)
    (debark person13 plane2)
    (board person13 plane3)
    (debark person13 plane3)
    (board person13 plane4)
    (debark person13 plane4)
    (board person13 plane5)
    (debark person13 plane5)
    (board person14 plane1)
    (debark person14 plane1)
    (board person14 plane2)
    (debark person14 plane2)
    (board person14 plane3)
    (debark person14 plane3)
    (board person14 plane4)
    (debark person14 plane4)
    (board person14 plane5)
    (debark person14 plane5)
    (board person15 plane1)
    (debark person15 plane1)
    (board person15 plane2)
    (debark person15 plane2)
    (board person15 plane3)
    (debark person15 plane3)
    (board person15 plane4)
    (debark person15 plane4)
    (board person15 plane5)
    (debark person15 plane5)
    (board person16 plane1)
    (debark person16 plane1)
    (board person16 plane2)
    (debark person16 plane2)
    (board person16 plane3)
    (debark person16 plane3)
    (board person16 plane4)
    (debark person16 plane4)
    (board person16 plane5)
    (debark person16 plane5)
    (board person17 plane1)
    (debark person17 plane1)
    (board person17 plane2)
    (debark person17 plane2)
    (board person17 plane3)
    (debark person17 plane3)
    (board person17 plane4)
    (debark person17 plane4)
    (board person17 plane5)
    (debark person17 plane5)
    (board person18 plane1)
    (debark person18 plane1)
    (board person18 plane2)
    (debark person18 plane2)
    (board person18 plane3)
    (debark person18 plane3)
    (board person18 plane4)
    (debark person18 plane4)
    (board person18 plane5)
    (debark person18 plane5)
    (board person19 plane1)
    (debark person19 plane1)
    (board person19 plane2)
    (debark person19 plane2)
    (board person19 plane3)
    (debark person19 plane3)
    (board person19 plane4)
    (debark person19 plane4)
    (board person19 plane5)
    (debark person19 plane5)
    (board person2 plane1)
    (debark person2 plane1)
    (board person2 plane2)
    (debark person2 plane2)
    (board person2 plane3)
    (debark person2 plane3)
    (board person2 plane4)
    (debark person2 plane4)
    (board person2 plane5)
    (debark person2 plane5)
    (board person20 plane1)
    (debark person20 plane1)
    (board person20 plane2)
    (debark person20 plane2)
    (board person20 plane3)
    (debark person20 plane3)
    (board person20 plane4)
    (debark person20 plane4)
    (board person20 plane5)
    (debark person20 plane5)
    (board person3 plane1)
    (debark person3 plane1)
    (board person3 plane2)
    (debark person3 plane2)
    (board person3 plane3)
    (debark person3 plane3)
    (board person3 plane4)
    (debark person3 plane4)
    (board person3 plane5)
    (debark person3 plane5)
    (board person4 plane1)
    (debark person4 plane1)
    (board person4 plane2)
    (debark person4 plane2)
    (board person4 plane3)
    (debark person4 plane3)
    (board person4 plane4)
    (debark person4 plane4)
    (board person4 plane5)
    (debark person4 plane5)
    (board person5 plane1)
    (debark person5 plane1)
    (board person5 plane2)
    (debark person5 plane2)
    (board person5 plane3)
    (debark person5 plane3)
    (board person5 plane4)
    (debark person5 plane4)
    (board person5 plane5)
    (debark person5 plane5)
    (board person6 plane1)
    (debark person6 plane1)
    (board person6 plane2)
    (debark person6 plane2)
    (board person6 plane3)
    (debark person6 plane3)
    (board person6 plane4)
    (debark person6 plane4)
    (board person6 plane5)
    (debark person6 plane5)
    (board person7 plane1)
    (debark person7 plane1)
    (board person7 plane2)
    (debark person7 plane2)
    (board person7 plane3)
    (debark person7 plane3)
    (board person7 plane4)
    (debark person7 plane4)
    (board person7 plane5)
    (debark person7 plane5)
    (board person8 plane1)
    (debark person8 plane1)
    (board person8 plane2)
    (debark person8 plane2)
    (board person8 plane3)
    (debark person8 plane3)
    (board person8 plane4)
    (debark person8 plane4)
    (board person8 plane5)
    (debark person8 plane5)
    (board person9 plane1)
    (debark person9 plane1)
    (board person9 plane2)
    (debark person9 plane2)
    (board person9 plane3)
    (debark person9 plane3)
    (board person9 plane4)
    (debark person9 plane4)
    (board person9 plane5)
    (debark person9 plane5)
    (fly plane1 city0)
    (fly plane1 city1)
    (fly plane1 city10)
    (fly plane1 city11)
    (fly plane1 city12)
    (fly plane1 city13)
    (fly plane1 city14)
    (fly plane1 city15)
    (fly plane1 city16)
    (fly plane1 city17)
    (fly plane1 city2)
    (fly plane1 city3)
    (fly plane1 city4)
    (fly plane1 city5)
    (fly plane1 city6)
    (fly plane1 city7)
    (fly plane1 city8)
    (fly plane1 city9)
    (fly plane2 city0)
    (fly plane2 city1)
    (fly plane2 city10)
    (fly plane2 city11)
    (fly plane2 city12)
    (fly plane2 city13)
    (fly plane2 city14)
    (fly plane2 city15)
    (fly plane2 city16)
    (fly plane2 city17)
    (fly plane2 city2)
    (fly plane2 city3)
    (fly plane2 city4)
    (fly plane2 city5)
    (fly plane2 city6)
    (fly plane2 city7)
    (fly plane2 city8)
    (fly plane2 city9)
    (fly plane3 city0)
    (fly plane3 city1)
    (fly plane3 city10)
    (fly plane3 city11)
    (fly plane3 city12)
    (fly plane3 city13)
    (fly plane3 city14)
    (fly plane3 city15)
    (fly plane3 city16)
    (fly plane3 city17)
    (fly plane3 city2)
    (fly plane3 city3)
    (fly plane3 city4)
    (fly plane3 city5)
    (fly plane3 city6)
    (fly plane3 city7)
    (fly plane3 city8)
    (fly plane3 city9)
    (fly plane4 city0)
    (fly plane4 city1)
    (fly plane4 city10)
    (fly plane4 city11)
    (fly plane4 city12)
    (fly plane4 city13)
    (fly plane4 city14)
    (fly plane4 city15)
    (fly plane4 city16)
    (fly plane4 city17)
    (fly plane4 city2)
    (fly plane4 city3)
    (fly plane4 city4)
    (fly plane4 city5)
    (fly plane4 city6)
    (fly plane4 city7)
    (fly plane4 city8)
    (fly plane4 city9)
    (fly plane5 city0)
    (fly plane5 city1)
    (fly plane5 city10)
    (fly plane5 city11)
    (fly plane5 city12)
    (fly plane5 city13)
    (fly plane5 city14)
    (fly plane5 city15)
    (fly plane5 city16)
    (fly plane5 city17)
    (fly plane5 city2)
    (fly plane5 city3)
    (fly plane5 city4)
    (fly plane5 city5)
    (fly plane5 city6)
    (fly plane5 city7)
    (fly plane5 city8)
    (fly plane5 city9)
    (refuel plane1)
    (refuel plane2)
    (refuel plane3)
    (refuel plane4)
    (refuel plane5)
    )
(:goal (and
	(at plane2 city6)
	(at person1 city2)
	(at person2 city17)
	(at person3 city7)
	(at person4 city14)
	(at person5 city9)
	(at person6 city13)
	(at person7 city6)
	(at person8 city8)
	(at person9 city4)
	(at person10 city16)
	(at person11 city6)
	(at person12 city4)
	(at person13 city14)
	(at person14 city2)
	(at person15 city9)
	(at person16 city9)
	(at person17 city15)
	(at person18 city6)
	(at person19 city2)
	(at person20 city17)
	))

)
