(define (problem depotprob4398) (:domain Depot)
(:objects
	depot0 depot1 - Depot
	distributor0 distributor1 - Distributor
	truck0 truck1 truck2 truck3 - Truck
	pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 pallet6 pallet7 - Pallet
	crate0 crate1 crate2 crate3 crate4 crate5 - Crate
	hoist0 hoist1 hoist2 hoist3 hoist4 hoist5 hoist6 hoist7 - Hoist)
(:init
	(at pallet0 depot0)
	(clear crate5)
	(at pallet1 depot1)
	(clear crate3)
	(at pallet2 distributor0)
	(clear crate4)
	(at pallet3 distributor1)
	(clear pallet3)
	(at pallet4 depot1)
	(clear crate0)
	(at pallet5 distributor1)
	(clear pallet5)
	(at pallet6 depot1)
	(clear pallet6)
	(at pallet7 distributor0)
	(clear pallet7)
	(at truck0 depot1)
	(at truck1 depot1)
	(at truck2 depot0)
	(at truck3 distributor1)
	(at hoist0 depot0)
	(available hoist0)
	(at hoist1 depot1)
	(available hoist1)
	(at hoist2 distributor0)
	(available hoist2)
	(at hoist3 distributor1)
	(available hoist3)
	(at hoist4 distributor1)
	(available hoist4)
	(at hoist5 depot1)
	(available hoist5)
	(at hoist6 depot1)
	(available hoist6)
	(at hoist7 distributor1)
	(available hoist7)
	(at crate0 depot1)
	(on crate0 pallet4)
	(at crate1 depot1)
	(on crate1 pallet1)
	(at crate2 depot0)
	(on crate2 pallet0)
	(at crate3 depot1)
	(on crate3 crate1)
	(at crate4 distributor0)
	(on crate4 pallet2)
	(at crate5 depot0)
	(on crate5 crate2)

    ; action literals
    (drive truck0 depot0)
    (drive truck0 depot1)
    (drive truck0 distributor0)
    (drive truck0 distributor1)
    (drive truck1 depot0)
    (drive truck1 depot1)
    (drive truck1 distributor0)
    (drive truck1 distributor1)
    (drive truck2 depot0)
    (drive truck2 depot1)
    (drive truck2 distributor0)
    (drive truck2 distributor1)
    (drive truck3 depot0)
    (drive truck3 depot1)
    (drive truck3 distributor0)
    (drive truck3 distributor1)
    (lift hoist0 crate0)
    (lift hoist0 crate1)
    (lift hoist0 crate2)
    (lift hoist0 crate3)
    (lift hoist0 crate4)
    (lift hoist0 crate5)
    (lift hoist1 crate0)
    (lift hoist1 crate1)
    (lift hoist1 crate2)
    (lift hoist1 crate3)
    (lift hoist1 crate4)
    (lift hoist1 crate5)
    (lift hoist2 crate0)
    (lift hoist2 crate1)
    (lift hoist2 crate2)
    (lift hoist2 crate3)
    (lift hoist2 crate4)
    (lift hoist2 crate5)
    (lift hoist3 crate0)
    (lift hoist3 crate1)
    (lift hoist3 crate2)
    (lift hoist3 crate3)
    (lift hoist3 crate4)
    (lift hoist3 crate5)
    (lift hoist4 crate0)
    (lift hoist4 crate1)
    (lift hoist4 crate2)
    (lift hoist4 crate3)
    (lift hoist4 crate4)
    (lift hoist4 crate5)
    (lift hoist5 crate0)
    (lift hoist5 crate1)
    (lift hoist5 crate2)
    (lift hoist5 crate3)
    (lift hoist5 crate4)
    (lift hoist5 crate5)
    (lift hoist6 crate0)
    (lift hoist6 crate1)
    (lift hoist6 crate2)
    (lift hoist6 crate3)
    (lift hoist6 crate4)
    (lift hoist6 crate5)
    (lift hoist7 crate0)
    (lift hoist7 crate1)
    (lift hoist7 crate2)
    (lift hoist7 crate3)
    (lift hoist7 crate4)
    (lift hoist7 crate5)
    (drop hoist0 crate0)
    (drop hoist0 crate1)
    (drop hoist0 crate2)
    (drop hoist0 crate3)
    (drop hoist0 crate4)
    (drop hoist0 crate5)
    (drop hoist1 crate0)
    (drop hoist1 crate1)
    (drop hoist1 crate2)
    (drop hoist1 crate3)
    (drop hoist1 crate4)
    (drop hoist1 crate5)
    (drop hoist2 crate0)
    (drop hoist2 crate1)
    (drop hoist2 crate2)
    (drop hoist2 crate3)
    (drop hoist2 crate4)
    (drop hoist2 crate5)
    (drop hoist3 crate0)
    (drop hoist3 crate1)
    (drop hoist3 crate2)
    (drop hoist3 crate3)
    (drop hoist3 crate4)
    (drop hoist3 crate5)
    (drop hoist4 crate0)
    (drop hoist4 crate1)
    (drop hoist4 crate2)
    (drop hoist4 crate3)
    (drop hoist4 crate4)
    (drop hoist4 crate5)
    (drop hoist5 crate0)
    (drop hoist5 crate1)
    (drop hoist5 crate2)
    (drop hoist5 crate3)
    (drop hoist5 crate4)
    (drop hoist5 crate5)
    (drop hoist6 crate0)
    (drop hoist6 crate1)
    (drop hoist6 crate2)
    (drop hoist6 crate3)
    (drop hoist6 crate4)
    (drop hoist6 crate5)
    (drop hoist7 crate0)
    (drop hoist7 crate1)
    (drop hoist7 crate2)
    (drop hoist7 crate3)
    (drop hoist7 crate4)
    (drop hoist7 crate5)
    (load hoist0 crate0 truck0)
    (load hoist0 crate0 truck1)
    (load hoist0 crate0 truck2)
    (load hoist0 crate0 truck3)
    (load hoist0 crate1 truck0)
    (load hoist0 crate1 truck1)
    (load hoist0 crate1 truck2)
    (load hoist0 crate1 truck3)
    (load hoist0 crate2 truck0)
    (load hoist0 crate2 truck1)
    (load hoist0 crate2 truck2)
    (load hoist0 crate2 truck3)
    (load hoist0 crate3 truck0)
    (load hoist0 crate3 truck1)
    (load hoist0 crate3 truck2)
    (load hoist0 crate3 truck3)
    (load hoist0 crate4 truck0)
    (load hoist0 crate4 truck1)
    (load hoist0 crate4 truck2)
    (load hoist0 crate4 truck3)
    (load hoist0 crate5 truck0)
    (load hoist0 crate5 truck1)
    (load hoist0 crate5 truck2)
    (load hoist0 crate5 truck3)
    (load hoist1 crate0 truck0)
    (load hoist1 crate0 truck1)
    (load hoist1 crate0 truck2)
    (load hoist1 crate0 truck3)
    (load hoist1 crate1 truck0)
    (load hoist1 crate1 truck1)
    (load hoist1 crate1 truck2)
    (load hoist1 crate1 truck3)
    (load hoist1 crate2 truck0)
    (load hoist1 crate2 truck1)
    (load hoist1 crate2 truck2)
    (load hoist1 crate2 truck3)
    (load hoist1 crate3 truck0)
    (load hoist1 crate3 truck1)
    (load hoist1 crate3 truck2)
    (load hoist1 crate3 truck3)
    (load hoist1 crate4 truck0)
    (load hoist1 crate4 truck1)
    (load hoist1 crate4 truck2)
    (load hoist1 crate4 truck3)
    (load hoist1 crate5 truck0)
    (load hoist1 crate5 truck1)
    (load hoist1 crate5 truck2)
    (load hoist1 crate5 truck3)
    (load hoist2 crate0 truck0)
    (load hoist2 crate0 truck1)
    (load hoist2 crate0 truck2)
    (load hoist2 crate0 truck3)
    (load hoist2 crate1 truck0)
    (load hoist2 crate1 truck1)
    (load hoist2 crate1 truck2)
    (load hoist2 crate1 truck3)
    (load hoist2 crate2 truck0)
    (load hoist2 crate2 truck1)
    (load hoist2 crate2 truck2)
    (load hoist2 crate2 truck3)
    (load hoist2 crate3 truck0)
    (load hoist2 crate3 truck1)
    (load hoist2 crate3 truck2)
    (load hoist2 crate3 truck3)
    (load hoist2 crate4 truck0)
    (load hoist2 crate4 truck1)
    (load hoist2 crate4 truck2)
    (load hoist2 crate4 truck3)
    (load hoist2 crate5 truck0)
    (load hoist2 crate5 truck1)
    (load hoist2 crate5 truck2)
    (load hoist2 crate5 truck3)
    (load hoist3 crate0 truck0)
    (load hoist3 crate0 truck1)
    (load hoist3 crate0 truck2)
    (load hoist3 crate0 truck3)
    (load hoist3 crate1 truck0)
    (load hoist3 crate1 truck1)
    (load hoist3 crate1 truck2)
    (load hoist3 crate1 truck3)
    (load hoist3 crate2 truck0)
    (load hoist3 crate2 truck1)
    (load hoist3 crate2 truck2)
    (load hoist3 crate2 truck3)
    (load hoist3 crate3 truck0)
    (load hoist3 crate3 truck1)
    (load hoist3 crate3 truck2)
    (load hoist3 crate3 truck3)
    (load hoist3 crate4 truck0)
    (load hoist3 crate4 truck1)
    (load hoist3 crate4 truck2)
    (load hoist3 crate4 truck3)
    (load hoist3 crate5 truck0)
    (load hoist3 crate5 truck1)
    (load hoist3 crate5 truck2)
    (load hoist3 crate5 truck3)
    (load hoist4 crate0 truck0)
    (load hoist4 crate0 truck1)
    (load hoist4 crate0 truck2)
    (load hoist4 crate0 truck3)
    (load hoist4 crate1 truck0)
    (load hoist4 crate1 truck1)
    (load hoist4 crate1 truck2)
    (load hoist4 crate1 truck3)
    (load hoist4 crate2 truck0)
    (load hoist4 crate2 truck1)
    (load hoist4 crate2 truck2)
    (load hoist4 crate2 truck3)
    (load hoist4 crate3 truck0)
    (load hoist4 crate3 truck1)
    (load hoist4 crate3 truck2)
    (load hoist4 crate3 truck3)
    (load hoist4 crate4 truck0)
    (load hoist4 crate4 truck1)
    (load hoist4 crate4 truck2)
    (load hoist4 crate4 truck3)
    (load hoist4 crate5 truck0)
    (load hoist4 crate5 truck1)
    (load hoist4 crate5 truck2)
    (load hoist4 crate5 truck3)
    (load hoist5 crate0 truck0)
    (load hoist5 crate0 truck1)
    (load hoist5 crate0 truck2)
    (load hoist5 crate0 truck3)
    (load hoist5 crate1 truck0)
    (load hoist5 crate1 truck1)
    (load hoist5 crate1 truck2)
    (load hoist5 crate1 truck3)
    (load hoist5 crate2 truck0)
    (load hoist5 crate2 truck1)
    (load hoist5 crate2 truck2)
    (load hoist5 crate2 truck3)
    (load hoist5 crate3 truck0)
    (load hoist5 crate3 truck1)
    (load hoist5 crate3 truck2)
    (load hoist5 crate3 truck3)
    (load hoist5 crate4 truck0)
    (load hoist5 crate4 truck1)
    (load hoist5 crate4 truck2)
    (load hoist5 crate4 truck3)
    (load hoist5 crate5 truck0)
    (load hoist5 crate5 truck1)
    (load hoist5 crate5 truck2)
    (load hoist5 crate5 truck3)
    (load hoist6 crate0 truck0)
    (load hoist6 crate0 truck1)
    (load hoist6 crate0 truck2)
    (load hoist6 crate0 truck3)
    (load hoist6 crate1 truck0)
    (load hoist6 crate1 truck1)
    (load hoist6 crate1 truck2)
    (load hoist6 crate1 truck3)
    (load hoist6 crate2 truck0)
    (load hoist6 crate2 truck1)
    (load hoist6 crate2 truck2)
    (load hoist6 crate2 truck3)
    (load hoist6 crate3 truck0)
    (load hoist6 crate3 truck1)
    (load hoist6 crate3 truck2)
    (load hoist6 crate3 truck3)
    (load hoist6 crate4 truck0)
    (load hoist6 crate4 truck1)
    (load hoist6 crate4 truck2)
    (load hoist6 crate4 truck3)
    (load hoist6 crate5 truck0)
    (load hoist6 crate5 truck1)
    (load hoist6 crate5 truck2)
    (load hoist6 crate5 truck3)
    (load hoist7 crate0 truck0)
    (load hoist7 crate0 truck1)
    (load hoist7 crate0 truck2)
    (load hoist7 crate0 truck3)
    (load hoist7 crate1 truck0)
    (load hoist7 crate1 truck1)
    (load hoist7 crate1 truck2)
    (load hoist7 crate1 truck3)
    (load hoist7 crate2 truck0)
    (load hoist7 crate2 truck1)
    (load hoist7 crate2 truck2)
    (load hoist7 crate2 truck3)
    (load hoist7 crate3 truck0)
    (load hoist7 crate3 truck1)
    (load hoist7 crate3 truck2)
    (load hoist7 crate3 truck3)
    (load hoist7 crate4 truck0)
    (load hoist7 crate4 truck1)
    (load hoist7 crate4 truck2)
    (load hoist7 crate4 truck3)
    (load hoist7 crate5 truck0)
    (load hoist7 crate5 truck1)
    (load hoist7 crate5 truck2)
    (load hoist7 crate5 truck3)
    (unload hoist0 crate0 truck0)
    (unload hoist0 crate0 truck1)
    (unload hoist0 crate0 truck2)
    (unload hoist0 crate0 truck3)
    (unload hoist0 crate1 truck0)
    (unload hoist0 crate1 truck1)
    (unload hoist0 crate1 truck2)
    (unload hoist0 crate1 truck3)
    (unload hoist0 crate2 truck0)
    (unload hoist0 crate2 truck1)
    (unload hoist0 crate2 truck2)
    (unload hoist0 crate2 truck3)
    (unload hoist0 crate3 truck0)
    (unload hoist0 crate3 truck1)
    (unload hoist0 crate3 truck2)
    (unload hoist0 crate3 truck3)
    (unload hoist0 crate4 truck0)
    (unload hoist0 crate4 truck1)
    (unload hoist0 crate4 truck2)
    (unload hoist0 crate4 truck3)
    (unload hoist0 crate5 truck0)
    (unload hoist0 crate5 truck1)
    (unload hoist0 crate5 truck2)
    (unload hoist0 crate5 truck3)
    (unload hoist1 crate0 truck0)
    (unload hoist1 crate0 truck1)
    (unload hoist1 crate0 truck2)
    (unload hoist1 crate0 truck3)
    (unload hoist1 crate1 truck0)
    (unload hoist1 crate1 truck1)
    (unload hoist1 crate1 truck2)
    (unload hoist1 crate1 truck3)
    (unload hoist1 crate2 truck0)
    (unload hoist1 crate2 truck1)
    (unload hoist1 crate2 truck2)
    (unload hoist1 crate2 truck3)
    (unload hoist1 crate3 truck0)
    (unload hoist1 crate3 truck1)
    (unload hoist1 crate3 truck2)
    (unload hoist1 crate3 truck3)
    (unload hoist1 crate4 truck0)
    (unload hoist1 crate4 truck1)
    (unload hoist1 crate4 truck2)
    (unload hoist1 crate4 truck3)
    (unload hoist1 crate5 truck0)
    (unload hoist1 crate5 truck1)
    (unload hoist1 crate5 truck2)
    (unload hoist1 crate5 truck3)
    (unload hoist2 crate0 truck0)
    (unload hoist2 crate0 truck1)
    (unload hoist2 crate0 truck2)
    (unload hoist2 crate0 truck3)
    (unload hoist2 crate1 truck0)
    (unload hoist2 crate1 truck1)
    (unload hoist2 crate1 truck2)
    (unload hoist2 crate1 truck3)
    (unload hoist2 crate2 truck0)
    (unload hoist2 crate2 truck1)
    (unload hoist2 crate2 truck2)
    (unload hoist2 crate2 truck3)
    (unload hoist2 crate3 truck0)
    (unload hoist2 crate3 truck1)
    (unload hoist2 crate3 truck2)
    (unload hoist2 crate3 truck3)
    (unload hoist2 crate4 truck0)
    (unload hoist2 crate4 truck1)
    (unload hoist2 crate4 truck2)
    (unload hoist2 crate4 truck3)
    (unload hoist2 crate5 truck0)
    (unload hoist2 crate5 truck1)
    (unload hoist2 crate5 truck2)
    (unload hoist2 crate5 truck3)
    (unload hoist3 crate0 truck0)
    (unload hoist3 crate0 truck1)
    (unload hoist3 crate0 truck2)
    (unload hoist3 crate0 truck3)
    (unload hoist3 crate1 truck0)
    (unload hoist3 crate1 truck1)
    (unload hoist3 crate1 truck2)
    (unload hoist3 crate1 truck3)
    (unload hoist3 crate2 truck0)
    (unload hoist3 crate2 truck1)
    (unload hoist3 crate2 truck2)
    (unload hoist3 crate2 truck3)
    (unload hoist3 crate3 truck0)
    (unload hoist3 crate3 truck1)
    (unload hoist3 crate3 truck2)
    (unload hoist3 crate3 truck3)
    (unload hoist3 crate4 truck0)
    (unload hoist3 crate4 truck1)
    (unload hoist3 crate4 truck2)
    (unload hoist3 crate4 truck3)
    (unload hoist3 crate5 truck0)
    (unload hoist3 crate5 truck1)
    (unload hoist3 crate5 truck2)
    (unload hoist3 crate5 truck3)
    (unload hoist4 crate0 truck0)
    (unload hoist4 crate0 truck1)
    (unload hoist4 crate0 truck2)
    (unload hoist4 crate0 truck3)
    (unload hoist4 crate1 truck0)
    (unload hoist4 crate1 truck1)
    (unload hoist4 crate1 truck2)
    (unload hoist4 crate1 truck3)
    (unload hoist4 crate2 truck0)
    (unload hoist4 crate2 truck1)
    (unload hoist4 crate2 truck2)
    (unload hoist4 crate2 truck3)
    (unload hoist4 crate3 truck0)
    (unload hoist4 crate3 truck1)
    (unload hoist4 crate3 truck2)
    (unload hoist4 crate3 truck3)
    (unload hoist4 crate4 truck0)
    (unload hoist4 crate4 truck1)
    (unload hoist4 crate4 truck2)
    (unload hoist4 crate4 truck3)
    (unload hoist4 crate5 truck0)
    (unload hoist4 crate5 truck1)
    (unload hoist4 crate5 truck2)
    (unload hoist4 crate5 truck3)
    (unload hoist5 crate0 truck0)
    (unload hoist5 crate0 truck1)
    (unload hoist5 crate0 truck2)
    (unload hoist5 crate0 truck3)
    (unload hoist5 crate1 truck0)
    (unload hoist5 crate1 truck1)
    (unload hoist5 crate1 truck2)
    (unload hoist5 crate1 truck3)
    (unload hoist5 crate2 truck0)
    (unload hoist5 crate2 truck1)
    (unload hoist5 crate2 truck2)
    (unload hoist5 crate2 truck3)
    (unload hoist5 crate3 truck0)
    (unload hoist5 crate3 truck1)
    (unload hoist5 crate3 truck2)
    (unload hoist5 crate3 truck3)
    (unload hoist5 crate4 truck0)
    (unload hoist5 crate4 truck1)
    (unload hoist5 crate4 truck2)
    (unload hoist5 crate4 truck3)
    (unload hoist5 crate5 truck0)
    (unload hoist5 crate5 truck1)
    (unload hoist5 crate5 truck2)
    (unload hoist5 crate5 truck3)
    (unload hoist6 crate0 truck0)
    (unload hoist6 crate0 truck1)
    (unload hoist6 crate0 truck2)
    (unload hoist6 crate0 truck3)
    (unload hoist6 crate1 truck0)
    (unload hoist6 crate1 truck1)
    (unload hoist6 crate1 truck2)
    (unload hoist6 crate1 truck3)
    (unload hoist6 crate2 truck0)
    (unload hoist6 crate2 truck1)
    (unload hoist6 crate2 truck2)
    (unload hoist6 crate2 truck3)
    (unload hoist6 crate3 truck0)
    (unload hoist6 crate3 truck1)
    (unload hoist6 crate3 truck2)
    (unload hoist6 crate3 truck3)
    (unload hoist6 crate4 truck0)
    (unload hoist6 crate4 truck1)
    (unload hoist6 crate4 truck2)
    (unload hoist6 crate4 truck3)
    (unload hoist6 crate5 truck0)
    (unload hoist6 crate5 truck1)
    (unload hoist6 crate5 truck2)
    (unload hoist6 crate5 truck3)
    (unload hoist7 crate0 truck0)
    (unload hoist7 crate0 truck1)
    (unload hoist7 crate0 truck2)
    (unload hoist7 crate0 truck3)
    (unload hoist7 crate1 truck0)
    (unload hoist7 crate1 truck1)
    (unload hoist7 crate1 truck2)
    (unload hoist7 crate1 truck3)
    (unload hoist7 crate2 truck0)
    (unload hoist7 crate2 truck1)
    (unload hoist7 crate2 truck2)
    (unload hoist7 crate2 truck3)
    (unload hoist7 crate3 truck0)
    (unload hoist7 crate3 truck1)
    (unload hoist7 crate3 truck2)
    (unload hoist7 crate3 truck3)
    (unload hoist7 crate4 truck0)
    (unload hoist7 crate4 truck1)
    (unload hoist7 crate4 truck2)
    (unload hoist7 crate4 truck3)
    (unload hoist7 crate5 truck0)
    (unload hoist7 crate5 truck1)
    (unload hoist7 crate5 truck2)
    (unload hoist7 crate5 truck3)
    )

(:goal (and
		(on crate0 pallet3)
		(on crate2 pallet1)
		(on crate3 pallet0)
		(on crate4 crate3)
		(on crate5 pallet2)
	)
))
