
(define (problem generatedblocks) (:domain blocks)
  (:objects
        b0 - block
	b1 - block
	b10 - block
	b2 - block
	b3 - block
	b4 - block
	b5 - block
	b6 - block
	b7 - block
	b8 - block
	b9 - block
  )
  (:init
	(clear b0)
	(clear b4)
	(clear b7)
	(handempty)
	(on b0 b1)
	(on b1 b2)
	(on b2 b3)
	(on b4 b5)
	(on b5 b6)
	(on b7 b8)
	(on b8 b9)
	(on b9 b10)
	(ontable b10)
	(ontable b3)
	(ontable b6)

        ; action literals
        (pickup b0)
        (putdown b0)
        (unstack b0)
        (stack b0 b1)
        (stack b0 b10)
        (stack b0 b2)
        (stack b0 b3)
        (stack b0 b4)
        (stack b0 b5)
        (stack b0 b6)
        (stack b0 b7)
        (stack b0 b8)
        (stack b0 b9)
        (pickup b1)
        (putdown b1)
        (unstack b1)
        (stack b1 b0)
        (stack b1 b10)
        (stack b1 b2)
        (stack b1 b3)
        (stack b1 b4)
        (stack b1 b5)
        (stack b1 b6)
        (stack b1 b7)
        (stack b1 b8)
        (stack b1 b9)
        (pickup b10)
        (putdown b10)
        (unstack b10)
        (stack b10 b0)
        (stack b10 b1)
        (stack b10 b2)
        (stack b10 b3)
        (stack b10 b4)
        (stack b10 b5)
        (stack b10 b6)
        (stack b10 b7)
        (stack b10 b8)
        (stack b10 b9)
        (pickup b2)
        (putdown b2)
        (unstack b2)
        (stack b2 b0)
        (stack b2 b1)
        (stack b2 b10)
        (stack b2 b3)
        (stack b2 b4)
        (stack b2 b5)
        (stack b2 b6)
        (stack b2 b7)
        (stack b2 b8)
        (stack b2 b9)
        (pickup b3)
        (putdown b3)
        (unstack b3)
        (stack b3 b0)
        (stack b3 b1)
        (stack b3 b10)
        (stack b3 b2)
        (stack b3 b4)
        (stack b3 b5)
        (stack b3 b6)
        (stack b3 b7)
        (stack b3 b8)
        (stack b3 b9)
        (pickup b4)
        (putdown b4)
        (unstack b4)
        (stack b4 b0)
        (stack b4 b1)
        (stack b4 b10)
        (stack b4 b2)
        (stack b4 b3)
        (stack b4 b5)
        (stack b4 b6)
        (stack b4 b7)
        (stack b4 b8)
        (stack b4 b9)
        (pickup b5)
        (putdown b5)
        (unstack b5)
        (stack b5 b0)
        (stack b5 b1)
        (stack b5 b10)
        (stack b5 b2)
        (stack b5 b3)
        (stack b5 b4)
        (stack b5 b6)
        (stack b5 b7)
        (stack b5 b8)
        (stack b5 b9)
        (pickup b6)
        (putdown b6)
        (unstack b6)
        (stack b6 b0)
        (stack b6 b1)
        (stack b6 b10)
        (stack b6 b2)
        (stack b6 b3)
        (stack b6 b4)
        (stack b6 b5)
        (stack b6 b7)
        (stack b6 b8)
        (stack b6 b9)
        (pickup b7)
        (putdown b7)
        (unstack b7)
        (stack b7 b0)
        (stack b7 b1)
        (stack b7 b10)
        (stack b7 b2)
        (stack b7 b3)
        (stack b7 b4)
        (stack b7 b5)
        (stack b7 b6)
        (stack b7 b8)
        (stack b7 b9)
        (pickup b8)
        (putdown b8)
        (unstack b8)
        (stack b8 b0)
        (stack b8 b1)
        (stack b8 b10)
        (stack b8 b2)
        (stack b8 b3)
        (stack b8 b4)
        (stack b8 b5)
        (stack b8 b6)
        (stack b8 b7)
        (stack b8 b9)
        (pickup b9)
        (putdown b9)
        (unstack b9)
        (stack b9 b0)
        (stack b9 b1)
        (stack b9 b10)
        (stack b9 b2)
        (stack b9 b3)
        (stack b9 b4)
        (stack b9 b5)
        (stack b9 b6)
        (stack b9 b7)
        (stack b9 b8)
    )
  (:goal (and
	(on b4 b10)
	(on b10 b2)
	(on b2 b3)
	(ontable b3)
	(on b5 b8)
	(on b8 b9)
	(on b9 b6)
	(on b6 b7)
	(ontable b7)
	(on b0 b1)
	(ontable b1)))
)
