import re
from pathlib import Path
from random import shuffle

import dspy

from pddlgym.constants import (
    prompts_dir,
    pddlgym_action_prompts_dir,
    pddlgym_domain_prompts_dir,
    pddlgym_object_names_prompts_dir,
    pddlgym_problem_prompts_dir,
)

import pddlgym
from pddlgym.core import PDDLEnv
from pddlgym.parser import parse_plan_step


def get_pddl_gym_domain_prompt(file_name: str) -> str:
    with open(pddlgym_domain_prompts_dir / file_name) as f:
        return f.read()


def get_pddl_gym_problem_prompt(file_name: str) -> str:
    with open(pddlgym_problem_prompts_dir / file_name) as f:
        return f.read()


def get_action_schema_prompt(file_name: str) -> str:
    with open(pddlgym_action_prompts_dir / file_name) as f:
        return f.read()


def get_object_names_prompt(file_name: str) -> str:
    with open(pddlgym_object_names_prompts_dir / file_name) as f:
        return f.read()


def get_combined_pddlgym_prompt(domain: str, problem: str) -> str:
    with open(pddlgym_domain_prompts_dir / domain) as f:
        domain = f.read()
    with open(pddlgym_problem_prompts_dir / problem) as f:
        problem = f.read()
    with open(prompts_dir / "task.md") as f:
        return f.read().format(
            domain=domain,
            problem=problem,
        )


class Problem:
    def __init__(
        self,
        domain_prompt_file: str,
        problem_prompt_file: str,
        action_schema_prompt_file: str,
        object_names_prompt_file: str,
        domain_name: str,
        problem_idx: int,
    ):
        self.domain_prompt_file = domain_prompt_file
        self.problem_prompt_file = problem_prompt_file
        self.action_schema_prompt_file = action_schema_prompt_file
        self.object_names_prompt_file = object_names_prompt_file
        self.domain_name = domain_name
        self.problem_idx = problem_idx

    def make_dspy_example(self) -> dspy.Example:
        """
        Create DSPy example object for the given domain and problem in the format
        expected by https://github.com/vDawgg/pddl_pipeline
        """
        return dspy.Example(
            task_description=get_combined_pddlgym_prompt(
                self.domain_prompt_file,
                self.problem_prompt_file,
            ),
            action_schema=get_action_schema_prompt(self.action_schema_prompt_file),
            object_names=get_object_names_prompt(self.object_names_prompt_file),
            domain_name=self.domain_name,
            problem_index=self.problem_idx,
        ).with_inputs("task_description", "action_schema", "object_names")

    def goal_reached(self, plan_file: Path) -> bool:
        """
        Convenience function for mapping plan files generated by FastDownward to the
        representation expected by pddlgym.
        """
        env: PDDLEnv = pddlgym.make(f"{self.domain_name}-v0")  # type: ignore
        env.fix_problem_index(self.problem_idx)
        state, _ = env.reset()
        with open(plan_file) as f:
            lines = f.readlines()
        plan = []
        for line in lines:
            match = re.match(
                r"^\((?P<function>\S+)\s+(?P<parameters>.+)\)$",
                line,
            )
            if match:
                action = match.group("function")
                # Action name is not known in current domain
                if action not in env.domain.operators:
                    return False
                parameters = match.group("parameters").split(" ")
                # Actions parameter count does not fulfill lower bound.
                if len(parameters) < len(env.domain.operators[action].params):
                    return False
                # This is just a best effort assumption, as we cannot easilly validate whether
                # the needed parameters are given in the correct order
                parameters = parameters[: len(env.domain.operators[action].params)]
                plan.append(f"{action} {' '.join(parameters)}")
        try:
            plan = [
                parse_plan_step(
                    plan_step,
                    list(env.domain.operators.values()),
                    [env.domain.predicates[a] for a in list(env.domain.actions)],
                    state.objects,
                    operators_as_actions=env.domain.operators_as_actions,
                )
                for plan_step in plan
            ]
        except AssertionError:
            return False
        terminated = False
        while not terminated:
            try:
                action = plan.pop(0)
            except IndexError:
                return False
            state, _, terminated, _, _ = env.step(action)
        return True


class NlPddlGymDs:
    def __init__(self, split: tuple = (80, 20), shuffle_ds: bool = True):
        """
        Wrapper for the NL-pddlgym dataset.
        Shuffles the data by default while making sure the distribution of problems
        is respected across the different splits.

        Parameters
        ----------
        split : tuple
            The splits that the ds should be divided into. The ds can either be split
            into 2 (train, test) or 3 (train, val, test) parts.
        shuffle : bool
            Shuffles the dataset.
        """
        assert len(split) == 2 or len(split) == 3, (
            "Splits can only contain 2 or 3 ratios."
        )
        assert sum(split) == 100, "Splits must sum to 100"
        # baking
        baking = [
            Problem(
                domain_prompt_file="Baking.md",
                problem_prompt_file=f"Baking_{i}.md",
                action_schema_prompt_file="Baking.md",
                object_names_prompt_file="Baking.md",
                domain_name="PDDLEnvBaking",
                problem_idx=i,
            )
            for i in range(4)
        ]
        baking.extend(
            [
                Problem(
                    domain_prompt_file="Baking.md",
                    problem_prompt_file=f"BakingTest_{i}.md",
                    action_schema_prompt_file="Baking.md",
                    object_names_prompt_file="Baking.md",
                    domain_name="PDDLEnvBakingTest",
                    problem_idx=i,
                )
                for i in range(4)
            ]
        )
        # blocks
        blocks = [
            Problem(
                domain_prompt_file="Blocks.md",
                problem_prompt_file=f"Blocks_{i}.md",
                action_schema_prompt_file="Blocks.md",
                object_names_prompt_file="Blocks.md",
                domain_name="PDDLEnvBlocks",
                problem_idx=i,
            )
            for i in range(5)
        ]
        blocks.extend(
            [
                Problem(
                    domain_prompt_file="BlocksMedium.md",
                    problem_prompt_file=f"BlocksMedium_{i}.md",
                    action_schema_prompt_file="BlocksMedium.md",
                    object_names_prompt_file="BlocksMedium.md",
                    domain_name="PDDLEnvBlocks_medium",
                    problem_idx=i,
                )
                for i in range(40)
            ]
        )
        # depot
        depot = [
            Problem(
                domain_prompt_file="Depot.md",
                problem_prompt_file=f"Depot_{i}.md",
                action_schema_prompt_file="Depot.md",
                object_names_prompt_file="Depot.md",
                domain_name="PDDLEnvDepot",
                problem_idx=i,
            )
            for i in range(10)
        ]
        depot.extend(
            Problem(
                domain_prompt_file="Depot.md",
                problem_prompt_file=f"DepotTest_{i}.md",
                action_schema_prompt_file="Depot.md",
                object_names_prompt_file="Depot.md",
                domain_name="PDDLEnvDepotTest",
                problem_idx=i,
            )
            for i in range(12)
        )
        # elevator
        elevator = [
            Problem(
                domain_prompt_file="Elevator.md",
                problem_prompt_file=f"Elevator_{i}.md",
                action_schema_prompt_file="Elevator.md",
                object_names_prompt_file="Elevator.md",
                domain_name="PDDLEnvElevator",
                problem_idx=i,
            )
            for i in range(5)
        ]
        elevator.extend(
            [
                Problem(
                    domain_prompt_file="Elevator.md",
                    problem_prompt_file=f"ElevatorTest_{i}.md",
                    action_schema_prompt_file="Elevator.md",
                    object_names_prompt_file="Elevator.md",
                    domain_name="PDDLEnvElevatorTest",
                    problem_idx=i,
                )
                for i in range(5)
            ]
        )
        # ferry
        ferry = [
            Problem(
                domain_prompt_file="Ferry.md",
                problem_prompt_file=f"Ferry_{i}.md",
                action_schema_prompt_file="Ferry.md",
                object_names_prompt_file="Ferry.md",
                domain_name="PDDLEnvFerry",
                problem_idx=i,
            )
            for i in range(4)
        ]
        ferry.extend(
            [
                Problem(
                    domain_prompt_file="Ferry.md",
                    problem_prompt_file=f"FerryTest_{i}.md",
                    action_schema_prompt_file="Ferry.md",
                    object_names_prompt_file="Ferry.md",
                    domain_name="PDDLEnvFerryTest",
                    problem_idx=i,
                )
                for i in range(4)
            ]
        )
        # gripper
        gripper = [
            Problem(
                domain_prompt_file="Gripper.md",
                problem_prompt_file=f"Gripper_{i}.md",
                action_schema_prompt_file="Gripper.md",
                object_names_prompt_file="Gripper.md",
                domain_name="PDDLEnvGripper",
                problem_idx=i,
            )
            for i in range(10)
        ]
        gripper.extend(
            [
                Problem(
                    domain_prompt_file="Gripper.md",
                    problem_prompt_file=f"ManyGripper_{i}.md",
                    action_schema_prompt_file="Gripper.md",
                    object_names_prompt_file="Gripper.md",
                    domain_name="PDDLEnvManygripper",
                    problem_idx=i,
                )
                for i in range(40)
            ]
        )
        # hanoi
        hanoi = [
            Problem(
                domain_prompt_file="Hanoi.md",
                problem_prompt_file=f"Hanoi_{i}.md",
                action_schema_prompt_file="Hanoi.md",
                object_names_prompt_file="Hanoi.md",
                domain_name="PDDLEnvHanoi",
                problem_idx=i,
            )
            for i in range(4)
        ]
        hanoi.extend(
            [
                Problem(
                    domain_prompt_file="Hanoi.md",
                    problem_prompt_file=f"HanoiTest_{i}.md",
                    action_schema_prompt_file="Hanoi.md",
                    object_names_prompt_file="Hanoi.md",
                    domain_name="PDDLEnvHanoiTest",
                    problem_idx=i,
                )
                for i in range(6)
            ]
        )
        # minecraft
        minecraft = [
            Problem(
                domain_prompt_file="Minecraft.md",
                problem_prompt_file=f"Minecraft_{i}.md",
                action_schema_prompt_file="Minecraft.md",
                object_names_prompt_file="Minecraft.md",
                domain_name="PDDLEnvMinecraft",
                problem_idx=i,
            )
            for i in range(30)
        ]
        minecraft.extend(
            Problem(
                domain_prompt_file="Minecraft.md",
                problem_prompt_file=f"MinecraftTest_{i}.md",
                action_schema_prompt_file="Minecraft.md",
                object_names_prompt_file="Minecraft.md",
                domain_name="PDDLEnvMinecraftTest",
                problem_idx=i,
            )
            for i in range(30)
        )
        # minecraft
        movie = [
            Problem(
                domain_prompt_file="Movie.md",
                problem_prompt_file=f"Movie_{i}.md",
                action_schema_prompt_file="Movie.md",
                object_names_prompt_file="Movie.md",
                domain_name="PDDLEnvMovie",
                problem_idx=i,
            )
            for i in range(2)
        ]
        movie.extend(
            Problem(
                domain_prompt_file="Movie.md",
                problem_prompt_file=f"MovieTest_{i}.md",
                action_schema_prompt_file="Movie.md",
                object_names_prompt_file="Movie.md",
                domain_name="PDDLEnvMovieTest",
                problem_idx=i,
            )
            for i in range(1)
        )
        # newspapers
        newspapers = [
            Problem(
                domain_prompt_file="Newspapers.md",
                problem_prompt_file=f"Newspapers_{i}.md",
                action_schema_prompt_file="Newspapers.md",
                object_names_prompt_file="Newspapers.md",
                domain_name="PDDLEnvNewspapers",
                problem_idx=i,
            )
            for i in range(40)
        ]
        # rearrangement
        rearrangement = [
            Problem(
                domain_prompt_file="Rearrangement.md",
                problem_prompt_file=f"Rearrangement_{i}.md",
                action_schema_prompt_file="Rearrangement.md",
                object_names_prompt_file="Rearrangement.md",
                domain_name="PDDLEnvRearrangement",
                problem_idx=i,
            )
            for i in range(20)
        ]
        # search and rescue
        search_and_rescue = [
            Problem(
                domain_prompt_file="SearchAndRescue.md",
                problem_prompt_file=f"SearchAndRescueLevel1_{i}.md",
                action_schema_prompt_file="SearchAndRescue.md",
                object_names_prompt_file="SearchAndRescue.md",
                domain_name="PDDLSearchAndRescueLevel1",
                problem_idx=i,
            )
            for i in range(20)
        ]
        search_and_rescue.extend(
            [
                Problem(
                    domain_prompt_file="SearchAndRescue.md",
                    problem_prompt_file=f"SearchAndRescueLevel2_{i}.md",
                    action_schema_prompt_file="SearchAndRescue.md",
                    object_names_prompt_file="SearchAndRescue.md",
                    domain_name="PDDLSearchAndRescueLevel2",
                    problem_idx=i,
                )
                for i in range(50)
            ]
        )
        # spanner learning
        spanner_learning = [
            Problem(
                domain_prompt_file="SpannerLearning.md",
                problem_prompt_file=f"SpannerLearning_{i}.md",
                action_schema_prompt_file="SpannerLearning.md",
                object_names_prompt_file="SpannerLearning.md",
                domain_name="PDDLEnvSpannerlearning",
                problem_idx=i,
            )
            for i in range(10)
        ]

        all_problems = [
            baking,
            blocks,
            depot,
            elevator,
            ferry,
            gripper,
            hanoi,
            minecraft,
            movie,
            newspapers,
            rearrangement,
            search_and_rescue,
            spanner_learning,
        ]
        if shuffle_ds:
            [shuffle(probs) for probs in all_problems]

        train_split = split[0] / 100
        train_splits = [int(len(prob) * train_split) for prob in all_problems]
        test_split = split[2] / 100 if len(split) == 3 else split[1] / 100
        test_splits = [
            int(len(probs) * (train_split + test_split)) for probs in all_problems
        ]

        self.train = [
            prob
            for split, probs in zip(train_splits, all_problems)
            for prob in probs[:split]
        ]
        self.test = [
            prob
            for train_split, val_split, probs in zip(
                train_splits, test_splits, all_problems
            )
            for prob in probs[train_split:val_split]
        ]
        self.val = [
            prob
            for split, probs in zip(test_splits, all_problems)
            for prob in probs[split:]
        ]

        if shuffle_ds:
            shuffle(self.val)
            shuffle(self.train)
            shuffle(self.test)

    def make_dspy_ds(
        self,
    ) -> tuple[list[dspy.Example], list[dspy.Example], list[dspy.Example]]:
        """
        Make dataset for prompt optimization from natural language descriptions of
        pddlgym tasks in the format expected by DSPy.
        """
        train = [prob.make_dspy_example() for prob in self.train]
        val = [prob.make_dspy_example() for prob in self.val]
        test = [prob.make_dspy_example() for prob in self.test]
        return train, val, test
