(define (problem RING_AND_PEG_11)
    (:domain RING_AND_PEG)
    (:objects
        orange_ring purple_ring cyan_ring magenta_ring
        orange_peg purple_peg cyan_peg magenta_peg yellow_peg red_peg start_position
    )
    (:init
        (ring orange_ring)
        (ring purple_ring)
        (ring cyan_ring)
        (ring magenta_ring)
        (peg orange_peg)
        (peg purple_peg)
        (peg cyan_peg)
        (peg magenta_peg)
        (peg yellow_peg)
        (peg red_peg)
        (peg start_position)
        (onpeg orange_ring orange_peg)
        (onpeg purple_ring cyan_peg)
        (onpeg cyan_ring magenta_peg)
        (onpeg magenta_ring purple_peg)
        (pegempty yellow_peg)
        (pegempty red_peg)
        (at start_position)
        (handempty)

    ; action literals
    (move cyan_peg)
    (move magenta_peg)
    (move orange_peg)
    (move purple_peg)
    (move red_peg)
    (move start_position)
    (move yellow_peg)
    (pick)
    (place)
    )
    (:goal         (and (onpeg orange_ring orange_peg) (onpeg purple_ring purple_peg) (onpeg cyan_ring cyan_peg) (onpeg magenta_ring magenta_peg)))
)
