(define (problem RING_AND_PEG_21)
    (:domain RING_AND_PEG)
    (:objects
        red_ring green_ring blue_ring pink_ring yellow_ring orange_ring purple_ring cyan_ring
        red_peg green_peg blue_peg pink_peg yellow_peg orange_peg purple_peg cyan_peg brown_peg teal_peg black_peg white_peg start_position
    )
    (:init
        (ring red_ring)
        (ring green_ring)
        (ring blue_ring)
        (ring pink_ring)
        (ring yellow_ring)
        (ring orange_ring)
        (ring purple_ring)
        (ring cyan_ring)
        (peg red_peg)
        (peg green_peg)
        (peg blue_peg)
        (peg pink_peg)
        (peg yellow_peg)
        (peg orange_peg)
        (peg purple_peg)
        (peg cyan_peg)
        (peg brown_peg)
        (peg teal_peg)
        (peg black_peg)
        (peg white_peg)
        (peg start_position)
        (onpeg red_ring green_peg)
        (onpeg green_ring blue_peg)
        (onpeg blue_ring pink_peg)
        (onpeg pink_ring yellow_peg)
        (onpeg yellow_ring orange_peg)
        (onpeg orange_ring purple_peg)
        (onpeg purple_ring cyan_peg)
        (onpeg cyan_ring red_peg)
	(pegempty brown_peg)
	(pegempty teal_peg)
	(pegempty black_peg)
	(pegempty white_peg)
        (at start_position)
        (handempty)
    )
    (:goal         (and (onpeg red_ring red_peg) (onpeg green_ring green_peg) (onpeg blue_ring blue_peg) (onpeg pink_ring pink_peg) (onpeg yellow_ring yellow_peg) (onpeg orange_ring orange_peg) (onpeg purple_ring purple_peg) (onpeg cyan_ring cyan_peg)))
)
