(define (problem RING_AND_PEG_20)
    (:domain RING_AND_PEG)
    (:objects
        navy_ring lime_ring coral_ring gold_ring silver_ring indigo_ring red_ring
        red_peg green_peg blue_peg pink_peg navy_peg lime_peg coral_peg gold_peg silver_peg indigo_peg start_position
    )
    (:init
        (ring navy_ring)
        (ring lime_ring)
        (ring coral_ring)
        (ring gold_ring)
        (ring silver_ring)
        (ring indigo_ring)
        (ring red_ring)
        (peg red_peg)
        (peg green_peg)
        (peg blue_peg)
        (peg pink_peg)
        (peg navy_peg)
        (peg lime_peg)
        (peg coral_peg)
        (peg gold_peg)
        (peg silver_peg)
        (peg indigo_peg)
        (peg start_position)
        (onpeg navy_ring navy_peg)
        (onpeg lime_ring lime_peg)
        (onpeg coral_ring green_peg)
        (onpeg gold_ring blue_peg)
        (onpeg silver_ring pink_peg)
        (onpeg indigo_ring coral_peg)
        (onpeg red_ring red_peg)
        (pegempty gold_peg)
        (pegempty silver_peg)
        (pegempty indigo_peg)
        (at start_position)
        (handempty)
    )
    (:goal         (and (onpeg navy_ring navy_peg) (onpeg lime_ring lime_peg) (onpeg coral_ring coral_peg) (onpeg gold_ring gold_peg) (onpeg silver_ring silver_peg) (onpeg indigo_ring indigo_peg) (onpeg red_ring red_peg)))
)
