(define (problem RING_AND_PEG_22)
    (:domain RING_AND_PEG)
    (:objects
        magenta_ring teal_ring brown_ring gray_ring olive_ring maroon_ring navy_ring lime_ring
        magenta_peg teal_peg brown_peg gray_peg olive_peg maroon_peg navy_peg lime_peg coral_peg gold_peg start_position
    )
    (:init
        (ring magenta_ring)
        (ring teal_ring)
        (ring brown_ring)
        (ring gray_ring)
        (ring olive_ring)
        (ring maroon_ring)
        (ring navy_ring)
        (ring lime_ring)
        (peg magenta_peg)
        (peg teal_peg)
        (peg brown_peg)
        (peg gray_peg)
        (peg olive_peg)
        (peg maroon_peg)
        (peg navy_peg)
        (peg lime_peg)
        (peg coral_peg)
        (peg gold_peg)
        (peg start_position)
        (onpeg magenta_ring magenta_peg)
        (onpeg teal_ring teal_peg)
        (onpeg brown_ring brown_peg)
        (onpeg gray_ring olive_peg)
        (onpeg olive_ring maroon_peg)
        (onpeg maroon_ring navy_peg)
        (onpeg navy_ring lime_peg)
        (onpeg lime_ring gray_peg)
        (pegempty coral_peg)
        (pegempty gold_peg)
        (at start_position)
        (handempty)
    )
    (:goal         (and (onpeg magenta_ring magenta_peg) (onpeg teal_ring teal_peg) (onpeg brown_ring brown_peg) (onpeg gray_ring gray_peg) (onpeg olive_ring olive_peg) (onpeg maroon_ring maroon_peg) (onpeg navy_ring navy_peg) (onpeg lime_ring lime_peg)))
)
