(define (problem RING_AND_PEG_19)
    (:domain RING_AND_PEG)
    (:objects
        cyan_ring magenta_ring teal_ring brown_ring gray_ring olive_ring maroon_ring
        cyan_peg magenta_peg teal_peg brown_peg gray_peg olive_peg maroon_peg navy_peg lime_peg start_position
    )
    (:init
        (ring cyan_ring)
        (ring magenta_ring)
        (ring teal_ring)
        (ring brown_ring)
        (ring gray_ring)
        (ring olive_ring)
        (ring maroon_ring)
        (peg cyan_peg)
        (peg magenta_peg)
        (peg teal_peg)
        (peg brown_peg)
        (peg gray_peg)
        (peg olive_peg)
        (peg maroon_peg)
        (peg navy_peg)
        (peg lime_peg)
        (peg start_position)
        (onpeg cyan_ring cyan_peg)
        (onpeg magenta_ring teal_peg)
        (onpeg teal_ring brown_peg)
        (onpeg brown_ring gray_peg)
        (onpeg gray_ring olive_peg)
        (onpeg olive_ring maroon_peg)
        (onpeg maroon_ring magenta_peg)
        (pegempty navy_peg)
        (pegempty lime_peg)
        (at start_position)
        (handempty)

    ; action literals
    (move brown_peg)
    (move cyan_peg)
    (move gray_peg)
    (move lime_peg)
    (move magenta_peg)
    (move maroon_peg)
    (move navy_peg)
    (move olive_peg)
    (move start_position)
    (move teal_peg)
    (pick)
    (place)
    )
    (:goal         (and (onpeg cyan_ring cyan_peg) (onpeg magenta_ring magenta_peg) (onpeg teal_ring teal_peg) (onpeg brown_ring brown_peg) (onpeg gray_ring gray_peg) (onpeg olive_ring olive_peg) (onpeg maroon_ring maroon_peg)))
)
