(define (problem RING_AND_PEG_29)
    (:domain RING_AND_PEG)
    (:objects
        orange_ring purple_ring cyan_ring magenta_ring teal_ring brown_ring gray_ring olive_ring
        orange_peg purple_peg cyan_peg magenta_peg teal_peg brown_peg gray_peg olive_peg red_peg green_peg blue_peg start_position
    )
    (:init
        (ring orange_ring)
        (ring purple_ring)
        (ring cyan_ring)
        (ring magenta_ring)
        (ring teal_ring)
        (ring brown_ring)
        (ring gray_ring)
        (ring olive_ring)
        (peg orange_peg)
        (peg purple_peg)
        (peg cyan_peg)
        (peg magenta_peg)
        (peg teal_peg)
        (peg brown_peg)
        (peg gray_peg)
        (peg olive_peg)
        (peg red_peg)
        (peg green_peg)
        (peg blue_peg)
        (peg start_position)
        (onpeg orange_ring orange_peg)
        (onpeg purple_ring purple_peg)
        (onpeg cyan_ring magenta_peg)
        (onpeg magenta_ring teal_peg)
        (onpeg teal_ring brown_peg)
        (onpeg brown_ring gray_peg)
        (onpeg gray_ring olive_peg)
        (onpeg olive_ring cyan_peg)
        (pegempty red_peg)
        (pegempty green_peg)
        (pegempty blue_peg)
        (at start_position)
        (handempty)

    ; action literals
    (move blue_peg)
    (move brown_peg)
    (move cyan_peg)
    (move gray_peg)
    (move green_peg)
    (move magenta_peg)
    (move olive_peg)
    (move orange_peg)
    (move purple_peg)
    (move red_peg)
    (move start_position)
    (move teal_peg)
    (pick)
    (place)
    )
    (:goal         (and (onpeg orange_ring orange_peg) (onpeg purple_ring purple_peg) (onpeg cyan_ring cyan_peg) (onpeg magenta_ring magenta_peg) (onpeg teal_ring teal_peg) (onpeg brown_ring brown_peg) (onpeg gray_ring gray_peg) (onpeg olive_ring olive_peg)))
)
