(define (problem RING_AND_PEG_09)
    (:domain RING_AND_PEG)
    (:objects
        cyan_ring magenta_ring teal_ring
        cyan_peg magenta_peg teal_peg brown_peg gray_peg olive_peg start_position
    )
    (:init
        (ring cyan_ring)
        (ring magenta_ring)
        (ring teal_ring)
        (peg cyan_peg)
        (peg magenta_peg)
        (peg teal_peg)
        (peg brown_peg)
        (peg gray_peg)
        (peg olive_peg)
        (peg start_position)
        (onpeg cyan_ring teal_peg)
        (onpeg magenta_ring magenta_peg)
        (onpeg teal_ring olive_peg)
        (pegempty brown_peg)
        (pegempty gray_peg)
        (pegempty cyan_peg)
        (at start_position)
        (handempty)
    )
    (:goal         (and (onpeg cyan_ring cyan_peg) (onpeg magenta_ring magenta_peg) (onpeg teal_ring teal_peg)))
)
