(define (problem RING_AND_PEG_25)
    (:domain RING_AND_PEG)
    (:objects
        teal_ring brown_ring gray_ring olive_ring maroon_ring navy_ring lime_ring coral_ring gold_ring
        teal_peg brown_peg gray_peg olive_peg maroon_peg navy_peg lime_peg coral_peg gold_peg silver_peg start_position
    )
    (:init
        (ring teal_ring)
        (ring brown_ring)
        (ring gray_ring)
        (ring olive_ring)
        (ring maroon_ring)
        (ring navy_ring)
        (ring lime_ring)
        (ring coral_ring)
        (ring gold_ring)
        (peg teal_peg)
        (peg brown_peg)
        (peg gray_peg)
        (peg olive_peg)
        (peg maroon_peg)
        (peg navy_peg)
        (peg lime_peg)
        (peg coral_peg)
        (peg gold_peg)
        (peg silver_peg)
        (peg start_position)
        (onpeg teal_ring teal_peg)
        (onpeg brown_ring brown_peg)
        (onpeg gray_ring gray_peg)
        (onpeg olive_ring olive_peg)
        (onpeg maroon_ring navy_peg)
        (onpeg navy_ring lime_peg)
        (onpeg lime_ring coral_peg)
        (onpeg coral_ring gold_peg)
        (onpeg gold_ring maroon_peg)
        (pegempty silver_peg)
        (at start_position)
        (handempty)

    ; action literals
    (move brown_peg)
    (move coral_peg)
    (move gold_peg)
    (move gray_peg)
    (move lime_peg)
    (move maroon_peg)
    (move navy_peg)
    (move olive_peg)
    (move silver_peg)
    (move start_position)
    (move teal_peg)
    (pick)
    (place)
    )
    (:goal         (and (onpeg teal_ring teal_peg) (onpeg brown_ring brown_peg) (onpeg gray_ring gray_peg) (onpeg olive_ring olive_peg) (onpeg maroon_ring maroon_peg) (onpeg navy_ring navy_peg) (onpeg lime_ring lime_peg) (onpeg coral_ring coral_peg) (onpeg gold_ring gold_peg)))
)
