(define (problem RING_AND_PEG_23)
    (:domain RING_AND_PEG)
    (:objects
        coral_ring gold_ring silver_ring indigo_ring red_ring green_ring blue_ring pink_ring
        red_peg green_peg blue_peg pink_peg coral_peg gold_peg silver_peg indigo_peg yellow_peg start_position
    )
    (:init
        (ring coral_ring)
        (ring gold_ring)
        (ring silver_ring)
        (ring indigo_ring)
        (ring red_ring)
        (ring green_ring)
        (ring blue_ring)
        (ring pink_ring)
        (peg red_peg)
        (peg green_peg)
        (peg blue_peg)
        (peg pink_peg)
        (peg coral_peg)
        (peg gold_peg)
        (peg silver_peg)
        (peg indigo_peg)
        (peg yellow_peg)
        (peg start_position)
        (onpeg coral_ring coral_peg)
        (onpeg gold_ring green_peg)
        (onpeg silver_ring blue_peg)
        (onpeg indigo_ring pink_peg)
        (onpeg red_ring gold_peg)
        (onpeg green_ring silver_peg)
        (onpeg blue_ring indigo_peg)
        (onpeg pink_ring red_peg)
        (pegempty yellow_peg)
        (at start_position)
        (handempty)
    )
    (:goal         (and (onpeg coral_ring coral_peg) (onpeg gold_ring gold_peg) (onpeg silver_ring silver_peg) (onpeg indigo_ring indigo_peg) (onpeg red_ring red_peg) (onpeg green_ring green_peg) (onpeg blue_ring blue_peg) (onpeg pink_ring pink_peg)))
)
