(define (problem RING_AND_PEG_16)
    (:domain RING_AND_PEG)
    (:objects
        purple_ring cyan_ring magenta_ring teal_ring brown_ring gray_ring
        purple_peg cyan_peg magenta_peg teal_peg brown_peg gray_peg olive_peg maroon_peg start_position
    )
    (:init
        (ring purple_ring)
        (ring cyan_ring)
        (ring magenta_ring)
        (ring teal_ring)
        (ring brown_ring)
        (ring gray_ring)
        (peg purple_peg)
        (peg cyan_peg)
        (peg magenta_peg)
        (peg teal_peg)
        (peg brown_peg)
        (peg gray_peg)
        (peg olive_peg)
        (peg maroon_peg)
        (peg start_position)
        (onpeg purple_ring purple_peg)
        (onpeg cyan_ring cyan_peg)
        (onpeg magenta_ring teal_peg)
        (onpeg teal_ring brown_peg)
        (onpeg brown_ring gray_peg)
        (onpeg gray_ring magenta_peg)
        (pegempty olive_peg)
        (pegempty maroon_peg)
        (at start_position)
        (handempty)

    ; action literals
    (move brown_peg)
    (move cyan_peg)
    (move gray_peg)
    (move magenta_peg)
    (move maroon_peg)
    (move olive_peg)
    (move purple_peg)
    (move start_position)
    (move teal_peg)
    (pick)
    (place)
    )
    (:goal         (and (onpeg purple_ring purple_peg) (onpeg cyan_ring cyan_peg) (onpeg magenta_ring magenta_peg) (onpeg teal_ring teal_peg) (onpeg brown_ring brown_peg) (onpeg gray_ring gray_peg)))
)
