(define (problem RING_AND_PEG_27)
    (:domain RING_AND_PEG)
    (:objects
        orange_ring purple_ring cyan_ring magenta_ring
        orange_peg purple_peg cyan_peg magenta_peg teal_peg brown_peg gray_peg start_position
    )
    (:init
        (ring orange_ring)
        (ring purple_ring)
        (ring cyan_ring)
        (ring magenta_ring)
        (peg orange_peg)
        (peg purple_peg)
        (peg cyan_peg)
        (peg magenta_peg)
        (peg teal_peg)
        (peg brown_peg)
        (peg gray_peg)
        (peg start_position)
        (onpeg orange_ring orange_peg)
        (onpeg purple_ring purple_peg)
        (onpeg cyan_ring magenta_peg)
        (onpeg magenta_ring cyan_peg)
        (pegempty teal_peg)
        (pegempty brown_peg)
        (pegempty gray_peg)
        (at start_position)
        (handempty)

    ; action literals
    (move brown_peg)
    (move cyan_peg)
    (move gray_peg)
    (move magenta_peg)
    (move orange_peg)
    (move purple_peg)
    (move start_position)
    (move teal_peg)
    (pick)
    (place)
    )
    (:goal         (and (onpeg orange_ring orange_peg) (onpeg purple_ring purple_peg) (onpeg cyan_ring cyan_peg) (onpeg magenta_ring magenta_peg)))
)
