(define (problem RING_AND_PEG_14)
    (:domain RING_AND_PEG)
    (:objects
        brown_ring gray_ring olive_ring maroon_ring navy_ring
        brown_peg gray_peg olive_peg maroon_peg navy_peg red_peg start_position
    )
    (:init
        (ring brown_ring)
        (ring gray_ring)
        (ring olive_ring)
        (ring maroon_ring)
        (ring navy_ring)
        (peg brown_peg)
        (peg gray_peg)
        (peg olive_peg)
        (peg maroon_peg)
        (peg navy_peg)
        (peg red_peg)
        (peg start_position)
        (onpeg brown_ring brown_peg)
        (onpeg gray_ring olive_peg)
        (onpeg olive_ring maroon_peg)
        (onpeg maroon_ring navy_peg)
        (onpeg navy_ring gray_peg)
        (pegempty red_peg)
        (at start_position)
        (handempty)
    )
    (:goal         (and (onpeg brown_ring brown_peg) (onpeg gray_ring gray_peg) (onpeg olive_ring olive_peg) (onpeg maroon_ring maroon_peg) (onpeg navy_ring navy_peg)))
)
